<script setup lang="ts">
import {computed} from 'vue'
import {eventTypes,type Expression} from './productionQualityModel'
import {display} from './incomingModel'
const props=withDefaults(defineProps<{modelValue?:Expression;disabled?:boolean;depth?:number}>(),{depth:1})
const emit=defineEmits<{'update:modelValue':[Expression]}>()
const kind=computed(()=>props.modelValue&&'constant' in props.modelValue?'constant':props.modelValue&&'op' in props.modelValue?'op':'sum')
function change(kind:string){emit('update:modelValue',kind==='constant'?{constant:'0'}:kind==='op'?{op:'ADD',left:{sum:['CHARGE']},right:{sum:['OUTPUT']}}:{sum:['CHARGE']})}
function toggle(type:string,checked:boolean){const old=props.modelValue&&'sum' in props.modelValue?props.modelValue.sum:[];emit('update:modelValue',{sum:checked?[...old,type]:old.filter(x=>x!==type)})}
function operand(side:'left'|'right',v:Expression){if(props.modelValue&&'op' in props.modelValue)emit('update:modelValue',{...props.modelValue,[side]:v})}
</script>
<template><div class="expression"><label><span class="form-field-label">数量来源</span><select class="master-native-input" :value="kind" :disabled="disabled" @change="change(($event.target as HTMLSelectElement).value)"><option value="sum">数量记录汇总</option><option value="constant">固定数值</option><option v-if="depth<8" value="op">运算</option></select></label><a-space v-if="kind==='sum'" wrap><label v-for="type in eventTypes" :key="type"><input type="checkbox" :disabled="disabled" :checked="modelValue&&'sum' in modelValue&&modelValue.sum.includes(type)" @change="toggle(type,($event.target as HTMLInputElement).checked)"/>{{display(type)}}</label></a-space><label v-else-if="modelValue&&'constant' in modelValue"><span class="form-field-label">固定数值</span><input class="master-native-input" :value="modelValue.constant" :disabled="disabled" @input="emit('update:modelValue',{constant:($event.target as HTMLInputElement).value})"/></label><template v-else-if="modelValue&&'op' in modelValue"><label><span class="form-field-label">运算</span><select class="master-native-input" :value="modelValue.op" :disabled="disabled" @change="emit('update:modelValue',{...modelValue,op:($event.target as HTMLSelectElement).value})"><option value="ADD">加</option><option value="SUBTRACT">减</option><option value="MULTIPLY">乘</option><option value="DIVIDE">除</option></select></label><fieldset><legend>左侧数量</legend><BalanceExpressionEditor :model-value="modelValue.left" :depth="depth+1" :disabled="disabled" @update:model-value="operand('left',$event)"/></fieldset><fieldset><legend>右侧数量</legend><BalanceExpressionEditor :model-value="modelValue.right" :depth="depth+1" :disabled="disabled" @update:model-value="operand('right',$event)"/></fieldset></template></div></template>
<style scoped>.expression{display:grid;gap:12px}.expression label{display:flex;align-items:center;gap:8px}.expression select,.expression input:not([type=checkbox]){min-width:0;flex:1}fieldset{min-width:0;border:1px solid #e8e8e8;padding:12px}legend{font-weight:600}</style>
