<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,type Page} from '../../api/http'
import {useControlledRequest} from '../../api/controlled'
import {useAuthStore} from '../../stores/auth'
import {resources,label,display,operations,schemas} from './incomingModel'
import IncomingReferencePicker from './IncomingReferencePicker.vue'
import ProductionSampleControls from './ProductionSampleControls.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),request=useControlledRequest(),{error,busy}=request
const resource=computed(()=>String(route.meta.resource)),def=computed(()=>resources[resource.value]!),base=computed(()=>resource.value==='deviations'?'/deviations':resource.value==='samples'&&scope.value==='PRODUCTION'?'/samples':`/quality/${resource.value}`)
const scope=ref(String(route.query.scope??'INCOMING_MATERIAL')),sampleCreate=ref(false),mainBatchId=ref(String(route.query.mainBatchId??''))
const title=computed(()=>resource.value==='deviations'&&scope.value==='PRODUCTION'?'生产质量调查':def.value.title)
const keyword=ref(''),status=ref(''),materialLotId=ref(''),page=ref(1),rows=ref<Record<string,unknown>[]>([]),total=ref(0)
const statusSchema:Record<string,string>={'inspection-requests':'InspectionRequest','sampling-tasks':'SamplingTask',samples:'Sample','inspection-tasks':'InspectionTask','inspection-reports':'InspectionReport',deviations:'Deviation'}
const states=computed(()=>resource.value==='samples'&&scope.value==='PRODUCTION'?['CREATED','COLLECTED','RECEIVED','IN_TEST','TEST_COMPLETED']:schemas[statusSchema[resource.value]??'']?.properties?.status?.enum??[])
async function changePage(p:{current?:number}){page.value=p.current??1;await search()}
async function search(){await router.replace({query:{...(['samples','deviations'].includes(resource.value)?{scope:scope.value}:{}),...(keyword.value?{keyword:keyword.value}:{}),...(status.value?{status:status.value}:{}),...(materialLotId.value?{materialLotId:materialLotId.value}:{}),...(mainBatchId.value?{mainBatchId:mainBatchId.value}:{}),page:String(page.value)}});await load()}
const columns=computed(()=>[...def.value.columns.map(k=>scope.value==='PRODUCTION'&&k==='materialLotId'?'mainBatchId':k).map(key=>({title:label(key),key,dataIndex:key})),{title:'操作',key:'actions'}])
const canCreate=computed(()=>scope.value==='PRODUCTION'&&resource.value==='samples'?auth.can('qms:sample:create'):operations.some(o=>o.path===base.value&&o.method==='POST'&&auth.can(o.permission)))
async function load(){busy.value=true;try{const data=await api<Page<Record<string,unknown>>>({url:base.value,params:{page:page.value-1,size:20,keyword:keyword.value||undefined,status:status.value||undefined,materialLotId:scope.value==='PRODUCTION'?undefined:materialLotId.value||undefined,...(['samples','deviations'].includes(resource.value)?{investigationScope:scope.value,...(scope.value==='PRODUCTION'?{mainBatchId:mainBatchId.value||undefined}:{})}:{})}});rows.value=data.items;total.value=data.total}catch(e){await request.failure(e)}finally{busy.value=false}}
watch(resource,()=>{scope.value=String(route.query.scope??'INCOMING_MATERIAL');mainBatchId.value=String(route.query.mainBatchId??'');page.value=Math.max(1,Number(route.query.page??1));keyword.value=String(route.query.keyword??'');status.value=String(route.query.status??'');materialLotId.value=String(route.query.materialLotId??'');void load()},{immediate:true})
</script>
<!-- UI Template: T1 Query/List; Phase 2A inspection request pilot only. -->
<template><main class="admin-page master-page" :class="{'t1-query-list':resource==='inspection-requests'}"><header class="admin-page-header"><div v-if="resource==='inspection-requests'"><h1>{{title}}</h1><p v-if="resource==='inspection-requests'">查询来料请验状态与关联物料批次</p></div><h1 v-else>{{title}}</h1><a-button v-if="canCreate" type="primary" @click="resource==='samples'&&scope==='PRODUCTION'?sampleCreate=true:router.push({path:`${base}/create`,query:{...route.query,scope}})">新增{{title}}</a-button></header>
 <a-alert v-if="error" type="error" :message="error" show-icon/>
 <a-card :title="resource==='inspection-requests'?'查询条件':undefined" :class="resource==='inspection-requests'?'query-card':'form-section'"><form :class="resource==='inspection-requests'?'query-form':'master-form incoming-query'" @submit.prevent="page=1;search()"><label v-if="['samples','deviations'].includes(resource)"><span class="form-field-label">质量范围</span><select v-model="scope" class="master-native-input" aria-label="质量范围" @change="page=1;search()"><option value="INCOMING_MATERIAL">来料质量</option><option value="PRODUCTION">生产质量</option></select></label><label><span class="form-field-label">关键字</span><input v-model="keyword" class="master-native-input" aria-label="关键字"/></label><label><span class="form-field-label">状态</span><select v-model="status" class="master-native-input" aria-label="状态"><option value="">全部状态</option><option v-for="state in states" :key="String(state)" :value="String(state)">{{display(state)}}</option></select></label><label v-if="scope==='PRODUCTION'"><span class="form-field-label">生产批</span><IncomingReferencePicker field="mainBatchId" v-model="mainBatchId" :context="{}"/></label><label v-else><span class="form-field-label">物料批次</span><IncomingReferencePicker field="materialLotId" v-model="materialLotId" :context="{}"/></label><a-space v-if="resource==='inspection-requests'"><a-button @click="keyword='';status='';materialLotId='';mainBatchId='';page=1;search()">重置</a-button><a-button type="primary" html-type="submit" :loading="busy">查询</a-button></a-space><a-space v-else class="form-full-row"><a-button type="primary" html-type="submit" :loading="busy">查询</a-button><a-button @click="keyword='';status='';materialLotId='';mainBatchId='';page=1;search()">重置</a-button></a-space></form></a-card>
 <ProductionSampleControls v-if="sampleCreate" :record="{}" create @saved="sampleCreate=false;load()" @cancel="sampleCreate=false"/><a-card :title="resource==='inspection-requests'?'数据列表':undefined" :class="{'result-card':resource==='inspection-requests'}"><div v-if="resource==='inspection-requests'" class="master-toolbar"><span>共 {{total}} 条记录</span></div><a-table :columns="columns" :data-source="rows" row-key="id" :loading="busy" :scroll="{x:900}" :pagination="resource==='inspection-requests'?false:{current:page,total,pageSize:20,showSizeChanger:false}" @change="changePage"><template #bodyCell="{column,record}"><a-button v-if="column.key==='actions'" type="link" @click="router.push({path:`${resource==='samples'?'/quality/samples':base}/${record.id}`,query:{...route.query,scope}})">查看</a-button><strong v-else-if="resource==='inspection-requests'&&column.key==='requestNo'" class="t1-business-id">{{display(record[column.key])}}</strong><span v-else>{{display(record[column.key])}}</span></template></a-table><div v-if="resource==='inspection-requests'" class="table-footer"><span>第 {{page}} 页</span><a-pagination :current="page" :total="total" :page-size="20" :show-size-changer="false" @change="(p:number)=>changePage({current:p})"/></div></a-card>
</main></template>

<style scoped>@media(min-width:1024px){.incoming-query{grid-template-columns:repeat(3,minmax(0,1fr))}}</style>
