<script setup lang="ts">
import {computed} from 'vue'
import {useRouter} from 'vue-router'
import {useAuthStore} from '../../stores/auth'
import {display,type IncomingRow} from './incomingModel'
import {rows,selectFacts,detailLabel} from './incomingDetailModel'
import IncomingFacts from './IncomingFacts.vue'
const props=defineProps<{record:IncomingRow;lot?:IncomingRow;gateText:(row:IncomingRow)=>string}>(),router=useRouter(),auth=useAuthStore()
const blockers=computed(()=>rows(props.record.gateReasons))
</script>
<!-- UI Template: T6. Eligibility and blocker evidence come only from the release-review read model. -->
<template><section class="material-release-overview">
 <a-card class="form-section"><div class="release-context"><div><h2>{{lot?.lotNo??'物料批放行审查'}}</h2><p>{{(lot?.materialSnapshot as IncomingRow|undefined)?.materialName??'—'}}</p><a-tag :color="record.qualityStatus==='RELEASED'?'green':'blue'">{{display(record.qualityStatus)}}</a-tag><a-tag>{{display(record.inventoryStatus)}}</a-tag></div><a-alert :type="record.eligibleForRelease?'success':'warning'" :message="record.eligibleForRelease?'当前满足放行条件，仍须执行授权质量决定':'当前不满足放行条件'" show-icon/></div></a-card>
 <div class="release-decision-grid"><a-card title="放行条件与阻断检查" class="form-section"><p v-if="!blockers.length">当前暂无阻断原因。</p><a-alert v-for="gate in blockers" :key="String(gate.code)" type="warning" show-icon :message="gateText(gate)"/><p class="section-hint">条件依据来自当前服务端审查结果，QC检验合格仍须独立QA物料放行。</p></a-card><a-card title="质量决定摘要" class="form-section"><dl><dt>物料批号</dt><dd>{{lot?.lotNo??'—'}}</dd><dt>质量状态</dt><dd>{{display(record.qualityStatus)}}</dd><dt>库存状态</dt><dd>{{display(record.inventoryStatus)}}</dd><dt>放行资格</dt><dd>{{record.eligibleForRelease?'满足当前审查条件':'存在阻断条件'}}</dd></dl><slot name="actions"/><p v-if="!record.allowedActions||(record.allowedActions as unknown[]).length===0" class="section-hint">{{record.eligibleForRelease?'当前账号不能执行质量决定，请由具备 QA 物料放行权限的人员完成放行。':'当前没有允许的质量决定，请先处理阻断条件后重新审查。'}}</p></a-card></div>
 <a-card title="检验报告与来料调查" class="form-section"><h3>检验报告</h3><p v-if="!rows(record.reports).length">暂无检验报告</p><section v-for="r in rows(record.reports)" :key="String(r.id)" class="release-evidence-row"><strong>{{r.reportNo??'检验报告'}}</strong><a-tag>{{display(r.status)}}</a-tag><a-tag :color="r.overallResult==='PASS'?'green':'red'">{{display(r.overallResult)}}</a-tag><a-button v-if="auth.can('qms:report:view')" type="link" @click="router.push(`/quality/inspection-reports/${r.id}`)">查看检验报告</a-button></section><h3>来料调查</h3><p v-if="!rows(record.investigations).length">暂无来料调查</p><section v-for="r in rows(record.investigations)" :key="String(r.id)" class="release-evidence-row"><strong>{{r.deviationNo??'来料调查'}}</strong><a-tag>{{display(r.status)}}</a-tag><a-button v-if="auth.can('qms:deviation:view')" type="link" @click="router.push(`/deviations/${r.id}`)">查看来料调查</a-button></section></a-card>
 <a-card title="物料质量决定历史" class="form-section"><p v-if="!rows(record.decisions).length">暂无记录</p><IncomingFacts v-for="r in rows(record.decisions)" :key="String(r.id)" :value="selectFacts(r,['decision','decisionAt','reason','releaseBasis','releaseScope'])" :label-formatter="detailLabel"/></a-card>
</section></template>
<style scoped>.material-release-overview{min-width:0}.release-context{display:flex;justify-content:space-between;align-items:center;gap:16px}.release-context h2{font-size:20px;margin:0}.release-context p{margin:8px 0}.release-decision-grid{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr);gap:16px;align-items:start}dl{display:grid;grid-template-columns:90px minmax(0,1fr);gap:12px}dt{color:var(--mes-ui-secondary)}dd{margin:0;overflow-wrap:anywhere}.release-evidence-row{display:flex;align-items:center;flex-wrap:wrap;gap:12px;padding:12px 0;border-bottom:1px solid var(--mes-ui-border)}h3{font-size:15px;margin:16px 0 8px}@media(max-width:900px){.release-context{align-items:start;flex-direction:column}.release-decision-grid{grid-template-columns:1fr}}</style>
