<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {useControlledRequest} from '../../api/controlled'
import {display,label,type IncomingRow} from './incomingModel'
import {permits,qualityActionLabels,qualityOperations} from './productionQualityModel'
import {selectFacts} from './incomingDetailModel'
import ReadReference from '../master/ReadReference.vue'
import IncomingFacts from './IncomingFacts.vue'
import QualityCommandForm from './QualityCommandForm.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),request=useControlledRequest(),{busy,error}=request,record=ref<IncomingRow>({}),batch=ref<IncomingRow>({}),selection=ref<IncomingRow|null>(null),command=ref<{schema:string;url:string;source:IncomingRow;action:string}|null>(null)
const results=computed(()=>(record.value.results??[]) as IncomingRow[]),latest=computed(()=>results.value.filter(r=>!results.value.some(x=>x.balanceRuleId===r.balanceRuleId&&Number(x.calculationVersion)>Number(r.calculationVersion))))
const columns=['balanceRuleId','expectedValue','actualValue','differenceValue','differencePct','status'].map(k=>({title:label(k),dataIndex:k,key:k}))
const investigation=computed(()=>(selection.value?.investigation??null) as IncomingRow|null)
async function load(){busy.value=true;request.clear();try{const [b,v]=await Promise.all([api<IncomingRow>({url:`/navigation/batches/${route.params.id}`,params:{context:'balance'}}),api<IncomingRow>({url:`/main-batches/${route.params.id}/material-balance`})]);batch.value=b;record.value=v;if(selection.value)selection.value=((v.results??[]) as IncomingRow[]).find(r=>r.id===selection.value?.id)??null}catch(e){await request.failure(e)}finally{busy.value=false}}
function open(action:string){let template='',source:IncomingRow=batch.value,url='';if(action==='recalculate'){template='/main-batches/{id}/material-balance/recalculate';url=`/main-batches/${route.params.id}/material-balance/recalculate`}else if(action==='investigations'){template='/balances/{id}/investigations';url=`/balances/${selection.value?.id}/investigations`}else{template=`/balance-investigations/{id}/${action}`;source=investigation.value!;url=`/balance-investigations/${source.id}/${action}`}const op=qualityOperations.find(o=>o.path===template&&o.method==='POST');if(op&&auth.can(op.permission))command.value={schema:op.schema,url,source,action}}
const target=computed(()=>command.value?.action==='approve'?{objectType:'BALANCE_INVESTIGATION',objectId:String(command.value.source.id),meaning:'APPROVE'}:undefined)
watch(()=>route.params.id,()=>{selection.value=null;command.value=null;void load()},{immediate:true})
</script>
<template><main class="admin-page master-page" data-ui-template="T3"><header class="admin-page-header"><div><a-button type="link" @click="router.push('/production/balances')">← 返回物料平衡列表</a-button><h1>物料平衡与偏差</h1><p>{{batch.batchNo}} · <ReadReference field="productId" :value="batch.productId"/></p></div><a-button v-if="auth.can('balance:view')&&permits(record,'recalculate')" @click="open('recalculate')">重新计算</a-button></header><a-alert v-if="error" type="error" :message="error"/><div class="balance-metrics"><a-card v-for="r in latest" :key="String(r.id)" :title="String(r.balanceCode??r.balanceRuleId)"><div class="metric-values"><div>预期数量<strong>{{display(r.expectedValue)}}</strong></div><div>实际数量<strong>{{display(r.actualValue)}}</strong></div><div>差异百分比<strong :class="r.status==='FAIL'?'error':''">{{display(r.differencePct)}}%</strong></div><div>计算结果<strong>{{display(r.status)}}</strong></div></div></a-card></div><a-alert v-if="(record.blockingCodes as unknown[])?.length" type="warning" show-icon message="物料平衡检查未通过，请核对数量事实并完成调查或重新计算。" class="form-section"/><div class="balance-columns"><a-card title="物料平衡明细"><a-table :columns="columns" :data-source="results" row-key="id" :loading="busy" :scroll="{x:850}" :pagination="false" :custom-row="(r:IncomingRow)=>({onClick:()=>selection=r})"><template #bodyCell="{record:r,column}"><a-button v-if="column.key==='balanceRuleId'" type="link" @click="selection=r">{{r.balanceCode??r.balanceRuleId}}</a-button><a-tag v-else-if="column.key==='status'" :color="r.status==='PASS'?'green':'red'">{{display(r.status)}}</a-tag><span v-else>{{display(r[column.key])}}</span></template></a-table></a-card><a-card title="物料平衡调查"><p v-if="!selection">选择一条平衡结果查看调查与证据。</p><template v-else><a-tag>{{display(selection.status)}}</a-tag><IncomingFacts v-if="investigation" :value="selectFacts(investigation,['status','investigationText','decision','approvedAt','reason'])"/><p v-else>尚未建立调查。</p><a-space wrap><a-button v-if="!investigation&&selection.status==='FAIL'&&auth.can('balance:investigate')" @click="open('investigations')">建立调查</a-button><a-button v-for="a in ['investigate','approve'].filter(x=>investigation&&permits(investigation,x)&&auth.can(x==='approve'?'balance:approve':'balance:investigate'))" :key="a" @click="open(a)">{{qualityActionLabels[a]}}</a-button></a-space><details><summary>查看原始数量与规则证据</summary><IncomingFacts :value="selection"/><IncomingFacts v-if="investigation" :value="investigation"/></details></template></a-card></div><a-card v-if="command" :title="qualityActionLabels[command.action]" class="form-section"><QualityCommandForm :key="command.url" :schema-name="command.schema" :url="command.url" :source="command.source" :signature-target="target" @saved="command=null;load()" @cancel="command=null"/></a-card></main></template>
<style scoped>.balance-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px;margin-bottom:16px}.metric-values{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;color:#595959}.metric-values strong{display:block;font-size:24px;color:#102d4e}.balance-columns>.ant-card{min-width:0}.balance-columns>.ant-card:last-child :deep(.master-form){grid-template-columns:1fr}.balance-columns>.ant-card:last-child :deep(.master-form>label){grid-template-columns:100px minmax(0,1fr)}.balance-columns{align-items:start;display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:16px;margin-bottom:16px}details{margin-top:16px}summary{cursor:pointer;color:#1677ff}@media(max-width:1000px){.balance-columns{grid-template-columns:1fr}.balance-metrics{grid-template-columns:1fr}}</style>
