<script setup lang="ts">
import {computed,ref} from 'vue'
import {useAuthStore} from '../../stores/auth'
import {type IncomingRow} from './incomingModel'
import {permits,qualityActionLabels} from './productionQualityModel'
import QualityCommandForm from './QualityCommandForm.vue'
import IncomingFacts from './IncomingFacts.vue'
const props=defineProps<{record:IncomingRow;create?:boolean;initialValue?:IncomingRow}>(),emit=defineEmits<{saved:[IncomingRow]}>(),auth=useAuthStore(),selected=ref(''),capa=ref<IncomingRow|null>(null)
const command=computed(()=>{if(props.create)return {schema:'ProductionDeviationCreateCommand',url:'/deviations',source:props.record,method:'POST'};const a=selected.value;if(!a)return null;if(a==='capas')return {schema:'CapaCreateCommand',url:`/deviations/${props.record.id}/capas`,source:props.record,method:'POST'};if(capa.value)return {schema:{start:'CapaStartCommand',complete:'CapaCompleteCommand',verify:'CapaVerifyCommand'}[a]!,url:`/capas/${capa.value.id}/${a}`,source:capa.value,method:'POST'};return {schema:{edit:'ProductionDeviationUpdateCommand',investigate:'ProductionDeviationInvestigateCommand',decide:'ProductionDeviationDecideCommand',close:'ProductionDeviationCloseCommand'}[a]!,url:`/deviations/${props.record.id}`+(a==='edit'?'':'/'+a),source:props.record,method:a==='edit'?'PUT':'POST'}})
const target=computed(()=>command.value?{objectType:capa.value?'PRODUCTION_CAPA':'PRODUCTION_DEVIATION',objectId:`${command.value.source.id}:${command.value.source.versionNo}`,meaning:selected.value==='decide'?'APPROVE':'VERIFY'}:undefined)
const capas=computed(()=>(props.record.capas??[]) as IncomingRow[])
function open(a:string,row:IncomingRow|null=null){capa.value=row;selected.value=a}
function saved(row:IncomingRow){selected.value='';capa.value=null;emit('saved',row)}
</script>
<template><a-card v-if="!create" title="生产质量调查操作" class="form-section"><a-space wrap><a-button v-for="a in ['edit','investigate','decide','close'].filter(x=>permits(record,x)&&auth.can(x==='edit'?'qms:deviation:update':'qms:deviation:'+x))" :key="a" @click="open(a)">{{a==='edit'?'编辑调查':qualityActionLabels[a]??(a==='decide'?'调查决定':'关闭调查')}}</a-button><a-button v-if="auth.can('qms:capa:create')&&permits(record,'CREATE_CAPA')" @click="open('capas')">新增CAPA</a-button></a-space></a-card><a-card v-if="!create&&auth.can('qms:capa:view')" title="纠正与预防措施" class="form-section"><p v-if="!capas.length">暂无CAPA。</p><section v-for="r in capas" :key="String(r.id)"><IncomingFacts :value="r"/><a-space wrap><a-button v-for="a in ['start','complete','verify'].filter(x=>permits(r,x)&&auth.can(x==='verify'?'qms:capa:verify':'qms:capa:update'))" :key="a" @click="open(a,r)">{{qualityActionLabels[a]}}</a-button></a-space></section></a-card><a-card v-if="command" :title="create?'新增生产质量调查':qualityActionLabels[selected]??'编辑调查'" class="form-section"><QualityCommandForm :key="command.url" :schema-name="command.schema" :url="command.url" :method="command.method" :source="command.source" :initial-value="create?{...initialValue,investigationScope:'PRODUCTION'}:selected==='edit'?record:{}" :signature-target="target" @saved="saved" @cancel="selected='';capa=null"/></a-card></template>
