<script setup lang="ts">
import {computed,reactive,ref,watch} from 'vue'
import {useRoute,useRouter,onBeforeRouteLeave} from 'vue-router'
import axios from 'axios'
import {api,errorMessage} from '../../api/http'
import {qcApi,qcStates,qcCommandHeaders,qcItemPayload,blankQcItem,type QcDetail,type QcVersion,type QcItem} from '../../api/qcSpecifications'
import {useAuthStore} from '../../stores/auth'
import ProcessLookup from '../process/ProcessLookup.vue'
import QcSpecificationItems from './QcSpecificationItems.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),create=computed(()=>route.meta.mode==='create'||route.path.endsWith('/create')),detail=ref<QcDetail|null>(null),busy=ref(false),error=ref(''),conflict=ref(false),versionOpen=ref(false)
const rootForm=reactive({materialId:null as string|null,specificationCode:'',specificationName:'',reason:''}),versionNumber=ref(1),versionReason=ref(''),items=ref<QcItem[]>([blankQcItem()]),requests=qcCommandHeaders()
const columns=[{title:'版本',dataIndex:'versionNoBusiness'},{title:'状态',key:'state'},{title:'编制人',dataIndex:'createdBy'},{title:'批准人',dataIndex:'approvedBy'},{title:'批准时间',dataIndex:'approvedAt'},{title:'记录版本',dataIndex:'versionNo'},{title:'操作',key:'actions'}]
const dirty=computed(()=>create.value?!!(rootForm.materialId||rootForm.specificationCode||rootForm.specificationName||rootForm.reason):versionOpen.value)
function failure(e:unknown){error.value=e instanceof Error&&!axios.isAxiosError(e)?e.message:errorMessage(e);conflict.value=axios.isAxiosError(e)&&e.response?.status===409}
async function load(){error.value='';conflict.value=false;if(!create.value){busy.value=true;try{detail.value=await qcApi.detail(String(route.params.id))}catch(e){failure(e)}finally{busy.value=false}}}
async function saveRoot(){busy.value=true;error.value='';try{if(!rootForm.materialId||!rootForm.specificationCode.trim()||!rootForm.specificationName.trim()||!rootForm.reason.trim())throw Error('请填写物料、标准编码、标准名称和原因');const body={...rootForm,reason:rootForm.reason.trim()};const url='/quality/specifications';const result=await api<QcDetail>({url,method:'POST',data:body,headers:requests.forRequest(url,body)});requests.complete();Object.assign(rootForm,{materialId:null,specificationCode:'',specificationName:'',reason:''});await router.replace(`/quality/specifications/${result.id}`)}catch(e){failure(e)}finally{busy.value=false}}
function newVersion(){versionNumber.value=Math.max(0,...(detail.value?.versions.map(v=>v.versionNoBusiness)??[]))+1;versionReason.value='';items.value=[blankQcItem()];error.value='';conflict.value=false;versionOpen.value=true}
function closeVersion(){if(busy.value)return;if(!window.confirm('关闭将放弃此版本尚未保存的内容，是否继续？'))return;versionOpen.value=false}
async function saveVersion(){busy.value=true;error.value='';try{if(!detail.value||!Number.isInteger(versionNumber.value)||versionNumber.value<1||!versionReason.value.trim())throw Error('请填写正整数版本号和操作原因');const body={versionNoBusiness:versionNumber.value,items:qcItemPayload(items.value),reason:versionReason.value.trim()};const url=`/quality/specifications/${detail.value.id}/versions`;const result=await api<QcVersion>({url,method:'POST',data:body,headers:requests.forRequest(url,body)});requests.complete();versionOpen.value=false;await router.push(`/quality/specification-versions/${result.id}/edit`)}catch(e){failure(e)}finally{busy.value=false}}
function openVersion(id:string,action?:string){void router.push({path:`/quality/specification-versions/${id}/edit`,query:action?{action}:undefined})}
onBeforeRouteLeave(()=>!dirty.value||window.confirm('离开将放弃未保存内容，是否继续？'))
watch(()=>route.fullPath,load,{immediate:true})
</script>
<template><main class="admin-page master-page"><header class="admin-page-header"><div><a-button type="link" @click="router.push('/quality/specifications')">← 返回标准列表</a-button><h1>{{create?'新增QC质量标准':detail?.specificationName??'QC质量标准'}}</h1><p v-if="detail">{{detail.specificationCode}} · {{detail.materialName}}</p></div><a-button v-if="!create&&detail&&auth.can('qms:specification:create')" type="primary" @click="newVersion">＋ 新建版本</a-button></header>
<a-alert v-if="error" type="error" :message="error" show-icon/>
<a-card v-if="create" title="标准基本信息" class="form-section"><form class="master-form" @submit.prevent="saveRoot"><label><span class="form-field-label">物料</span><ProcessLookup v-model="rootForm.materialId" resource="materials" label="物料" :disabled="busy"/></label><label><span class="form-field-label">标准编码</span><input v-model="rootForm.specificationCode" class="master-native-input" aria-label="标准编码" maxlength="100" :disabled="busy" required/></label><label><span class="form-field-label">标准名称</span><input v-model="rootForm.specificationName" class="master-native-input" aria-label="标准名称" maxlength="200" :disabled="busy" required/></label><label><span class="form-field-label">操作原因</span><textarea v-model="rootForm.reason" class="master-native-input" aria-label="操作原因" maxlength="1000" :disabled="busy" required/></label><a-space><a-button type="primary" html-type="submit" :loading="busy" :disabled="!auth.can('qms:specification:create')">保存标准</a-button></a-space></form></a-card>
<template v-else-if="detail"><a-card title="标准信息" class="form-section"><div class="master-form"><label><span class="form-field-label">标准编码</span><span class="master-read-value">{{detail.specificationCode}}</span></label><label><span class="form-field-label">标准名称</span><span class="master-read-value">{{detail.specificationName}}</span></label><label><span class="form-field-label">物料</span><span class="master-read-value">{{detail.materialName}}（{{detail.materialCode}}）</span></label><label><span class="form-field-label">创建时间</span><span class="master-read-value">{{detail.createdAt}}</span></label></div></a-card>
<a-card title="标准版本" class="result-card"><a-table :columns="columns" :data-source="detail.versions" :loading="busy" :pagination="false" row-key="id" :scroll="{x:1100}"><template #bodyCell="{column,record}"><a-tag v-if="column.key==='state'">{{qcStates[record.status as keyof typeof qcStates]}}</a-tag><a-space v-else-if="column.key==='actions'"><a-button type="link" @click="openVersion(record.id)">{{record.status==='DRAFT'&&auth.can('qms:specification:edit')?'编辑 / 查看':'查看'}}</a-button><a-button v-if="record.status==='DRAFT'&&auth.can('qms:specification:approve')&&auth.can('ebr:sign')" type="link" @click="openVersion(record.id,'approve')">批准</a-button><a-button v-if="record.status==='APPROVED'&&auth.can('qms:specification:retire')&&auth.can('ebr:sign')" type="link" @click="openVersion(record.id,'retire')">退役</a-button></a-space></template></a-table></a-card></template>
<a-modal :open="versionOpen" title="新建QC标准版本" width="min(1100px, calc(100vw - 24px))" :footer="null" :mask-closable="false" :closable="!busy" :keyboard="!busy" @cancel="closeVersion"><a-alert v-if="error" type="error" :message="error" show-icon/><form @submit.prevent="saveVersion"><div class="master-form qc-version-fields"><label><span class="form-field-label">业务版本</span><input v-model.number="versionNumber" type="number" min="1" max="2147483647" class="master-native-input" aria-label="业务版本" required :disabled="busy"/></label><label><span class="form-field-label">操作原因</span><textarea v-model="versionReason" class="master-native-input" aria-label="新版本原因" maxlength="1000" required :disabled="busy"/></label></div><QcSpecificationItems v-model="items" :disabled="busy"/><a-space class="qc-modal-actions"><a-button :disabled="busy" @click="closeVersion">取消</a-button><a-button type="primary" html-type="submit" :loading="busy">保存草稿版本</a-button></a-space></form></a-modal></main></template>
<style scoped>:deep(.process-lookup){display:block;min-width:0;width:100%}:deep(.ant-select){width:100%}.qc-version-fields{margin:18px 0}.qc-modal-actions{margin-top:20px}.master-read-value{overflow-wrap:anywhere}</style>
