<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter,onBeforeRouteLeave} from 'vue-router'
import axios from 'axios'
import {api,errorMessage} from '../../api/http'
import {qcApi,qcStates,qcCommandHeaders,qcItemPayload,type QcVersion,type QcItem} from '../../api/qcSpecifications'
import {useAuthStore} from '../../stores/auth'
import QcSpecificationItems from './QcSpecificationItems.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),version=ref<QcVersion|null>(null),items=ref<QcItem[]>([]),busy=ref(false),error=ref(''),conflict=ref(false),reason=ref(''),credential=ref(''),signatureOpen=ref(false),signatureAction=ref<'approve'|'retire'>('approve'),requests=qcCommandHeaders()
let baseline=''
const editable=computed(()=>version.value?.status==='DRAFT'&&auth.can('qms:specification:edit')&&!busy.value),dirty=computed(()=>!!version.value&&JSON.stringify(items.value)!==baseline)
const canApprove=computed(()=>version.value?.status==='DRAFT'&&auth.can('qms:specification:approve')&&auth.can('ebr:sign')&&version.value.createdBy!==auth.identity?.userId),canRetire=computed(()=>version.value?.status==='APPROVED'&&auth.can('qms:specification:retire')&&auth.can('ebr:sign'))
function sync(v:QcVersion){version.value=v;items.value=v.items.map(i=>({...i}));baseline=JSON.stringify(items.value)}
function failure(e:unknown){error.value=e instanceof Error&&!axios.isAxiosError(e)?e.message:errorMessage(e);conflict.value=axios.isAxiosError(e)&&e.response?.status===409}
async function load(){busy.value=true;error.value='';conflict.value=false;credential.value='';signatureOpen.value=false;try{sync(await qcApi.version(String(route.params.id)));reason.value='';if(route.query.action==='approve'&&canApprove.value)openSignature('approve');if(route.query.action==='retire'&&canRetire.value)openSignature('retire')}catch(e){failure(e)}finally{busy.value=false}}
function reload(){if((dirty.value||reason.value)&&!window.confirm('重新加载将放弃未保存内容，是否继续？'))return;void load()}
async function save(){busy.value=true;error.value='';try{if(!version.value||!reason.value.trim())throw Error('请填写操作原因');const body={versionNo:version.value.versionNo,items:qcItemPayload(items.value),reason:reason.value.trim()};const url=`/quality/specification-versions/${version.value.id}`;sync(await api<QcVersion>({url,method:'PUT',data:body,headers:requests.forRequest(url,body,body.versionNo)}));requests.complete();reason.value='';conflict.value=false}catch(e){failure(e)}finally{busy.value=false}}
function openSignature(action:'approve'|'retire'){if(dirty.value){error.value='请先保存定义修改';return}signatureAction.value=action;credential.value='';signatureOpen.value=true}
function closeSignature(){if(busy.value)return;credential.value='';signatureOpen.value=false}
async function sign(){busy.value=true;error.value='';try{if(!version.value||dirty.value)throw Error('请先保存定义修改');if(!reason.value.trim()||!credential.value)throw Error('请填写签名原因和再认证密码');const current=version.value,action=signatureAction.value,body:{versionNo:number;reason:string;reauthToken?:string}={versionNo:current.versionNo,reason:reason.value.trim()},url=`/quality/specification-versions/${current.id}/${action}`;const headers=requests.forRequest(url,body,current.versionNo);const reauth=await api<{reauthToken:string}>({url:'/auth/reauth',method:'POST',data:{objectType:action==='approve'?'QcSpecificationVersion':'QcSpecificationRetirement',objectId:current.id,meaning:'APPROVE',recordVersion:current.versionNoBusiness,credential:credential.value}});body.reauthToken=reauth.reauthToken;sync(await api<QcVersion>({url,method:'POST',data:body,headers}));requests.complete();reason.value='';signatureOpen.value=false;conflict.value=false}catch(e){failure(e)}finally{credential.value='';busy.value=false}}
onBeforeRouteLeave(()=>!dirty.value||window.confirm('离开将放弃未保存的定义修改，是否继续？'))
watch(()=>route.params.id,load,{immediate:true})
</script>
<template><main class="admin-page master-page"><header class="admin-page-header"><div><a-button type="link" @click="router.push(version?`/quality/specifications/${version.specificationId}`:'/quality/specifications')">← 返回标准</a-button><h1>{{version?.specificationName??'QC标准版本'}} · V{{version?.versionNoBusiness??'—'}}</h1><p v-if="version">{{version.materialName}}（{{version.materialCode}}） · {{qcStates[version.status]}}</p></div><a-space><a-button :disabled="busy" @click="reload">重新加载</a-button><a-button v-if="version&&auth.can('audit:view')" @click="router.push({path:'/audit',query:{objectType:'QcSpecificationVersion',objectId:version.id}})">版本审计</a-button></a-space></header>
<a-alert v-if="error" type="error" :message="error" show-icon/><a-alert v-if="conflict" type="warning" message="记录已变化，已保留当前输入。请重新加载并核对后重试。" show-icon/>
<template v-if="version"><a-card title="版本信息" class="form-section"><div class="master-form"><label><span class="form-field-label">标准编码</span><span class="master-read-value">{{version.specificationCode}}</span></label><label><span class="form-field-label">状态</span><span class="master-read-value">{{qcStates[version.status]}}</span></label><label><span class="form-field-label">编制人</span><span class="master-read-value">{{version.createdBy}}</span></label><label><span class="form-field-label">批准人 / 时间</span><span class="master-read-value">{{version.approvedBy??'—'}} / {{version.approvedAt??'—'}}</span></label><label><span class="form-field-label">批准签名</span><span class="master-read-value">{{version.approvalSignatureId??'—'}}</span></label><label><span class="form-field-label">批准原因</span><span class="master-read-value">{{version.approvalReason??'—'}}</span></label><label v-if="version.status==='RETIRED'"><span class="form-field-label">退役人 / 时间</span><span class="master-read-value">{{version.retiredBy}} / {{version.retiredAt}}</span></label><label v-if="version.status==='RETIRED'"><span class="form-field-label">退役签名</span><span class="master-read-value">{{version.retirementSignatureId}}</span></label><label v-if="version.status==='RETIRED'"><span class="form-field-label">退役原因</span><span class="master-read-value">{{version.retirementReason}}</span></label><label class="form-full-row"><span class="form-field-label">内容摘要</span><span class="master-read-value qc-digest">{{version.contentHash??'批准后生成'}}</span></label></div></a-card>
<QcSpecificationItems v-model="items" :disabled="!editable"/>
<a-card v-if="editable||canApprove||canRetire" title="受控操作" class="form-section"><label class="form-inline-row"><span class="form-field-label">操作原因</span><textarea v-model="reason" aria-label="操作原因" maxlength="1000" class="master-native-input" :disabled="busy"/></label><a-space wrap><a-button v-if="editable" type="primary" :disabled="busy||conflict" @click="save">保存草稿</a-button><a-button v-if="canApprove" type="primary" :disabled="busy||dirty||conflict" @click="openSignature('approve')">签名批准</a-button><a-button v-if="canRetire" danger :disabled="busy||conflict" @click="openSignature('retire')">签名退役</a-button></a-space><p v-if="dirty" class="muted">有未保存的检验项目修改。</p></a-card></template>
<a-modal :open="signatureOpen" :title="signatureAction==='approve'?'QC标准批准签名':'QC标准退役签名'" :footer="null" :mask-closable="false" :closable="!busy" :keyboard="!busy" @cancel="closeSignature"><p>签名对象：{{version?.specificationCode}} · V{{version?.versionNoBusiness}}</p><p>操作：{{signatureAction==='approve'?'批准当前版本':'退役当前版本'}}（APPROVE）</p><p>签名人：{{auth.identity?.displayName}}（{{auth.identity?.loginName}}）</p><p>本次签名绑定该版本的全部检验项目、方法、限值和操作原因。</p><a-alert v-if="error" type="error" :message="error" show-icon/><form @submit.prevent="sign"><label class="form-inline-row"><span class="form-field-label">签名原因</span><textarea v-model="reason" class="master-native-input" aria-label="签名原因" maxlength="1000" required :disabled="busy"/></label><label class="form-inline-row"><span class="form-field-label">再认证密码</span><input v-model="credential" type="password" autocomplete="current-password" aria-label="再认证密码" class="master-native-input" required :disabled="busy"/></label><a-space><a-button :disabled="busy" @click="closeSignature">取消签名</a-button><a-button type="primary" html-type="submit" :loading="busy" :disabled="conflict">确认电子签名</a-button></a-space></form></a-modal></main></template>
<style scoped>.master-read-value,.qc-digest{overflow-wrap:anywhere;min-width:0}.form-section{margin-top:16px}.form-inline-row{grid-template-columns:110px minmax(0,1fr)}@media(max-width:560px){.form-inline-row{grid-template-columns:90px minmax(0,1fr);gap:0 8px}}</style>
