import { describe, expect, it } from 'vitest'
import { navigationConfiguration, navigationHome, permittedNavigation, selectedNavigationKey } from './navigation'

describe('approved shared global navigation', () => {
  it('has the seven approved domains and each existing destination occurs once', () => {
    expect([navigationHome.title, ...navigationConfiguration.map(group => group.title)]).toEqual(['首页', '基础管理', 'WMS管理', '质量管理', '生产管理', '成品管理', '系统管理'])
    const items = navigationConfiguration.flatMap(group => group.items)
    expect(new Set(items.map(item => item.key)).size).toBe(items.length)
    expect(new Set(items.map(item => item.path)).size).toBe(items.length)
    expect(items.some(item => item.key === 'execution-execution')).toBe(false)
    expect(navigationConfiguration.find(group=>group.key==='production')?.items.map(item=>item.title)).toEqual(['生产订单','生产批','生产执行','eBR模板','物料平衡'])
    expect(navigationConfiguration.find(group=>group.key==='finished')?.items.map(item=>item.title)).toEqual(['成品入库申请','成品生产入库（待检）','成品请验','成品取样','成品检验','QA批审核','成品放行','成品库存','成品发货出库'])
    expect(navigationConfiguration.find(group => group.key === 'master')?.items.map(item => item.title)).toEqual(['物料主数据', '供应商', '组织', '单位', '单位换算', '设备', '人员资格', '产品管理', '工艺包管理'])
    expect(navigationConfiguration.find(group => group.key === 'wms')?.items.map(item => item.title)).toEqual(['原辅料收货记录', '库存管理', '领料申请', '出库管理', '退料管理'])
    expect(navigationConfiguration.find(group => group.key === 'wms')?.items.map(item => item.path)).toEqual(['/wms/receipts', '/wms/inventory', '/wms/requests', '/wms/issues', '/wms/returns'])
    expect(navigationConfiguration.find(group => group.key === 'quality')?.items.map(item => item.title)).toEqual(['请验单', '取样记录', '样品', '检验记录', '检验报告', 'QC质量标准', '生产质量计划', '生产检验', '质量调查'])
  })
  it('keeps permission-filtered entries and order identical for every shell without mutating the source', () => {
    const permissions = new Set(['production:batch:view', 'wms:finished-inbound:view', 'trace:view'])
    const groups = permittedNavigation(permission => permissions.has(permission))
    expect(groups.map(group => group.title)).toEqual(['生产管理', '成品管理', '系统管理'])
    expect(groups.flatMap(group => group.items).map(item => item.key)).toEqual(['production-batches-list', 'finished-inbound', 'finished-receiving', 'trace'])
    expect(permittedNavigation(() => false)).toEqual([])
    expect(permittedNavigation(p=>p==='qa:release').flatMap(g=>g.items)).toEqual([])
    expect(permittedNavigation(p=>p==='mes:execution:view').flatMap(g=>g.items)).toEqual([])
    expect(navigationConfiguration).toHaveLength(6)
    expect(navigationConfiguration.find(group => group.key === 'finished')?.items).toHaveLength(9)
    const uomOnly = permittedNavigation(permission => permission === 'master:uom:view').flatMap(group => group.items)
    expect(uomOnly.map(item => item.title)).toEqual(['单位', '单位换算'])
    expect(uomOnly.map(item => item.key)).toEqual(['master-units', 'master-unit-conversions'])
  })
  it('selects detail/create/edit pages and contextual T5 without prefix collisions or inaccessible highlights', () => {
    const groups = permittedNavigation(() => true)
    for (const path of ['/production/batches/100', '/production/batches/100/edit']) expect(selectedNavigationKey(path, groups)).toBe('production-batches-list')
    expect(selectedNavigationKey('/mes/execution/200', groups)).toBe('production-execution')
    expect(selectedNavigationKey('/production/batches/100/balance', groups)).toBe('production-balances')
    expect(selectedNavigationKey('/qa/batches/100/review', groups)).toBe('finished-qa-reviews')
    expect(selectedNavigationKey('/qa/batches/100/release', groups)).toBe('finished-releases')
    expect(selectedNavigationKey('/finished/inbound/create', groups)).toBe('finished-inbound')
    expect(selectedNavigationKey('/finished/inbound-other', groups)).toBeUndefined()
    expect(selectedNavigationKey('/mes/execution/200', permittedNavigation(() => false))).toBeUndefined()
    expect(selectedNavigationKey('/', groups)).toBe('dashboard')
  })
})
