package com.hospital.mes.production.application;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.masterdata.infrastructure.ScopedEntity;
import com.hospital.mes.process.application.ProcessQueryService;
import com.hospital.mes.ebr.application.EbrQueryService;
import com.hospital.mes.production.infrastructure.*;
import com.hospital.mes.production.domain.*;
import com.hospital.mes.common.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.math.BigDecimal;
import java.time.Instant;
import static com.hospital.mes.production.application.ProductionInput.*;
import static com.hospital.mes.production.domain.ProductionRules.*;

@org.springframework.stereotype.Service
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class ProductionService {
 @Transactional(propagation=org.springframework.transaction.annotation.Propagation.MANDATORY)
 public void applyFinishedQaDecision(com.hospital.mes.audit.application.CurrentPlatformContext c,long batch,long expected,long finishedLot,String decision,boolean superseding,String reason,String key){
  mutations.context("qa:release");var row=lockBatch(c.organizationId(),batch);ProductionRules.version(row.getVersionNo(),expected);
  gate(Objects.equals(row.getFinishedLotId(),finishedLot),"FINISHED_LOT_BATCH_MISMATCH","Finished lot must be batch-owned");
  var before=view(row);row.setStatus(ProductionRules.finishedQaDecision(row.getStatus(),decision,superseding));db.batches.update(row,expected,c.actorId(),List.of("status"));mutations.auditSnapshot(c,"MainBatch:FINISHED_QA_"+decision,"MainBatch",batch,before,view(row),reason,key);
 }
 @Transactional(propagation=org.springframework.transaction.annotation.Propagation.MANDATORY)
 public void quantityEvidenceRecorded(com.hospital.mes.audit.application.CurrentPlatformContext context,long batchId,long expected,Long outputLot,String reason,String key){
  var row=lockBatch(context.organizationId(),batchId);ProductionRules.version(row.getVersionNo(),expected);
  gate("IN_PROGRESS".equals(row.getStatus()),"QUANTITY_BATCH_NOT_MUTABLE","Quantity facts require an in-progress batch");var before=view(row);
  if(outputLot!=null){gate(row.getFinishedLotId()==null||row.getFinishedLotId().equals(outputLot),"FINISHED_LOT_IDENTITY_CONFLICT","One finished lot per batch");row.setFinishedLotId(outputLot);}
  db.batches.update(row,expected,context.actorId(),outputLot==null?List.of():List.of("finishedLotId"));
  mutations.auditSnapshot(context,"MainBatch:QUANTITY_EVIDENCE","MainBatch",row.getId(),before,view(row),reason,key);
 }
 private org.springframework.beans.factory.ObjectProvider<ProductionBookPort> bookPort;
 @org.springframework.beans.factory.annotation.Autowired public void bookPort(org.springframework.beans.factory.ObjectProvider<ProductionBookPort> port){this.bookPort=port;}
 private final ProductionMaterialPolicyService weighingPolicies;private final ProductionStore db;private final MasterMutation mutations;private final ProductionViews views;private final ObjectMapper json;private final MasterQueryService units;private final ProcessQueryService process;private final EbrQueryService ebr;private final MaterialQueryService materials;private final ApplicationEventPublisher events;private final ObjectProvider<ProductionRuntimeGate> runtime;private final ObjectProvider<ProductionQualityPlanPort> qualityPlans;
 public ProductionService(ProductionMaterialPolicyService weighingPolicies,ProductionStore db,MasterMutation mutations,ProductionViews views,ObjectMapper json,MasterQueryService units,ProcessQueryService process,EbrQueryService ebr,MaterialQueryService materials,ApplicationEventPublisher events,ObjectProvider<ProductionRuntimeGate> runtime,ObjectProvider<ProductionQualityPlanPort> qualityPlans){this.weighingPolicies=weighingPolicies;this.db=db;this.mutations=mutations;this.views=views;this.json=json;this.units=units;this.process=process;this.ebr=ebr;this.materials=materials;this.events=events;this.runtime=runtime;this.qualityPlans=qualityPlans;}
 public ScopedStore.PageData<JsonNode> orders(int page,int size,String keyword,Map<String,String> filters){var c=mutations.context("production:order:view");return page(db.orderMapper,c.organizationId(),page,size,keyword,filters,"order_no",false);}
 public ScopedStore.PageData<JsonNode> batches(int page,int size,String keyword,Map<String,String> filters){var c=mutations.context("production:batch:view");return page(db.batchMapper,c.organizationId(),page,size,keyword,filters,"batch_no",true);}
 private <E extends ScopedEntity> ScopedStore.PageData<JsonNode> page(com.baomidou.mybatisplus.core.mapper.BaseMapper<E> mapper,long org,int page,int size,String keyword,Map<String,String> filters,String number,boolean batch){
  if(page<0||page>1000000||size<1||size>100)throw new IllegalArgumentException("Invalid pagination");var q=new QueryWrapper<E>().eq("org_id",org);if(keyword!=null&&!keyword.isBlank())q.like(number,com.hospital.mes.masterdata.domain.MasterRules.text(keyword,200));
  for(String field:List.of("status","productId","productionOrderId")){String value=filters.get(field);if(value!=null&&!value.isBlank()&&(!field.equals("productionOrderId")||batch))q.eq(field.replaceAll("([a-z])([A-Z])","$1_$2").toLowerCase(Locale.ROOT),value);}
  for(String field:List.of("plannedDateFrom","plannedDateTo")){String value=filters.get(field);if(value!=null&&!value.isBlank()){var date=java.time.LocalDate.parse(value);if(field.endsWith("From"))q.ge("planned_date",date);else q.le("planned_date",date);}}
  long count=mapper.selectCount(q);var rows=mapper.selectList(q.orderByDesc("id").last("LIMIT "+((long)page*size)+","+size));return new ScopedStore.PageData<>(rows.stream().map(x->(JsonNode)view(x)).toList(),count,page,size);
 }
 public JsonNode order(String id){var c=mutations.context("production:order:view");return view(db.orders.get(c.organizationId(),MasterMutation.id(id)));}
 public JsonNode batch(String id){var c=mutations.context("production:batch:view");return view(db.batches.get(c.organizationId(),MasterMutation.id(id)));}
 public List<JsonNode> subBatches(String id){var c=mutations.context("production:batch:view");db.batches.get(c.organizationId(),MasterMutation.id(id));return db.subs(c.organizationId(),MasterMutation.id(id)).stream().map(x->(JsonNode)view(x)).toList();}
 public List<JsonNode> executions(String id){var c=mutations.context("mes:execution:view");db.batches.get(c.organizationId(),MasterMutation.id(id));return db.executions(c.organizationId(),MasterMutation.id(id)).stream().map(x->(JsonNode)view(x)).toList();}
 public JsonNode execution(String id){var c=mutations.context("mes:execution:view");return view(db.executions.get(c.organizationId(),MasterMutation.id(id)));}
 @Transactional public JsonNode createOrder(JsonNode body,String key){fields(body,"orderNo","productId","plannedQty","unitId","plannedDate","reason");var c=mutations.context("production:order:create");String reason=text(body,"reason",1000);return mutations.execute(c,"ProductionOrder:CREATE",key,body,()->{var row=new OrderEntity();applyOrder(row,body,c.organizationId());row.setStatus("DRAFT");db.orders.insert(row,c.organizationId(),c.actorId());mutations.auditSnapshot(c,"ProductionOrder:CREATE","ProductionOrder",row.getId(),null,view(row),reason,key);return row;},this::view,200);}
 @Transactional public JsonNode updateOrder(String id,JsonNode body,String header,String key){fields(body,"orderNo","productId","plannedQty","unitId","plannedDate","versionNo","reason");var c=mutations.context("production:order:update");long expected=version(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"ProductionOrder:EDIT:"+id,key,request(id,expected,body),()->{var row=db.orders.lock(c.organizationId(),MasterMutation.id(id));ProductionRules.version(row.getVersionNo(),expected);requireDraft(row.getStatus());var before=view(row);var children=db.lockedAllocations(c.organizationId(),row.getId());if(!children.isEmpty())gate(row.getProductId()==ProductionInput.id(body,"productId")&&row.getUnitId()==ProductionInput.id(body,"unitId"),"ORDER_HAS_BATCHES","Cannot change product/unit after allocation");applyOrder(row,body,c.organizationId());allocation(row.getPlannedQty(),allocated(row,null,null));db.orders.update(row,expected,c.actorId(),List.of("orderNo","productId","plannedQty","unitId","plannedDate"));mutations.auditSnapshot(c,"ProductionOrder:EDIT","ProductionOrder",row.getId(),before,view(row),reason,key);return row;},this::view,200);}
 private void applyOrder(OrderEntity row,JsonNode body,long org){row.setOrderNo(text(body,"orderNo",80));row.setProductId(ProductionInput.id(body,"productId"));process.requireProduct(org,row.getProductId());row.setPlannedQty(quantity(body,"plannedQty"));row.setUnitId(ProductionInput.id(body,"unitId"));units.unit(org,row.getUnitId());row.setPlannedDate(date(body,"plannedDate"));}
 @Transactional public JsonNode createBatch(JsonNode body,String key){fields(body,"batchNo","productionOrderId","productId","plannedQty","unitId","plannedDate","subBatchPlan","reason");var c=mutations.context("production:batch:create");String reason=text(body,"reason",1000);return mutations.execute(c,"MainBatch:CREATE",key,body,()->{var order=db.orders.lock(c.organizationId(),ProductionInput.id(body,"productionOrderId"));gate(!"COMPLETED".equals(order.getStatus()),"ORDER_COMPLETED","Order has completed");var row=new BatchEntity();applyBatch(row,body,order);allocation(order.getPlannedQty(),allocated(order,null,row));row.setStatus("DRAFT");db.batches.insert(row,c.organizationId(),c.actorId());if(body.hasNonNull("subBatchPlan")){gate(body.get("subBatchPlan").isArray()&&body.get("subBatchPlan").size()<=1000,"SUBBATCH_PLAN_INVALID","Array up to 1000 required");for(var sub:body.get("subBatchPlan"))insertSub(row,sub,c.actorId());}mutations.auditSnapshot(c,"MainBatch:CREATE","MainBatch",row.getId(),null,view(row),reason,key);return row;},this::view,201);}
 @Transactional public JsonNode updateBatch(String id,JsonNode body,String header,String key){fields(body,"batchNo","productionOrderId","productId","plannedQty","unitId","plannedDate","versionNo","reason");var c=mutations.context("production:batch:update");long expected=version(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"MainBatch:EDIT:"+id,key,request(id,expected,body),()->{var initial=db.batches.get(c.organizationId(),MasterMutation.id(id));long requestedOrder=ProductionInput.id(body,"productionOrderId");var orderIds=new TreeSet<>(List.of(initial.getProductionOrderId(),requestedOrder));OrderEntity order=null;for(long orderId:orderIds){var lockedOrder=db.orders.lock(c.organizationId(),orderId);if(orderId==requestedOrder)order=lockedOrder;}var row=db.batches.lock(c.organizationId(),initial.getId());ProductionRules.version(row.getVersionNo(),expected);requireDraft(row.getStatus());var before=view(row);gate(!"COMPLETED".equals(order.getStatus()),"ORDER_COMPLETED","Order has completed");applyBatch(row,body,order);allocation(order.getPlannedQty(),allocated(order,row.getId(),row));db.batches.update(row,expected,c.actorId(),List.of("batchNo","productionOrderId","productId","plannedQty","unitId","plannedDate"));mutations.auditSnapshot(c,"MainBatch:EDIT","MainBatch",row.getId(),before,view(row),reason,key);return row;},this::view,200);}
 private void applyBatch(BatchEntity row,JsonNode body,OrderEntity order){row.setBatchNo(text(body,"batchNo",80));row.setProductionOrderId(order.getId());row.setProductId(ProductionInput.id(body,"productId"));gate(row.getProductId().equals(order.getProductId()),"BATCH_PRODUCT_MISMATCH","Batch product must match order");process.requireProduct(order.getOrgId(),row.getProductId());row.setPlannedQty(quantity(body,"plannedQty"));row.setUnitId(ProductionInput.id(body,"unitId"));units.unit(order.getOrgId(),row.getUnitId());row.setPlannedDate(date(body,"plannedDate"));}
 private BigDecimal allocated(OrderEntity order,Long excluded,BatchEntity addition){BigDecimal total=BigDecimal.ZERO;for(var b:db.lockedAllocations(order.getOrgId(),order.getId()))if(!Objects.equals(b.getId(),excluded))total=total.add(exact(units,order.getOrgId(),b.getUnitId(),order.getUnitId(),null,b.getPlannedQty()));if(addition!=null)total=total.add(exact(units,order.getOrgId(),addition.getUnitId(),order.getUnitId(),null,addition.getPlannedQty()));return total;}
 @Transactional public JsonNode createSubBatch(String id,JsonNode body,String header,String key){fields(body,"subBatchNo","sequenceNo","plannedQty","versionNo","reason");var c=mutations.context("production:subbatch:create");long expected=version(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"SubBatch:CREATE:"+id,key,request(id,expected,body),()->{var row=lockBatch(c.organizationId(),MasterMutation.id(id));ProductionRules.version(row.getVersionNo(),expected);requireDraft(row.getStatus());var before=view(row);var sub=insertSub(row,body,c.actorId());db.batches.update(row,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"MainBatch:ADD_SUBBATCH","MainBatch",row.getId(),before,view(row),reason,key);return sub;},this::view,200);}
 private SubBatchEntity insertSub(BatchEntity batch,JsonNode body,long actor){fields(body,"subBatchNo","sequenceNo","plannedQty","versionNo","reason");var sub=new SubBatchEntity();sub.setMainBatchId(batch.getId());sub.setSubBatchNo(text(body,"subBatchNo",80));gate(body.path("sequenceNo").isInt()&&body.get("sequenceNo").intValue()>0,"SUBBATCH_PLAN_INVALID","Positive sequence required");sub.setSequenceNo(body.get("sequenceNo").intValue());sub.setPlannedQty(body.hasNonNull("plannedQty")?quantity(body,"plannedQty"):null);sub.setStatus("PENDING");db.subs.insert(sub,batch.getOrgId(),actor);return sub;}
 @Transactional public JsonNode releaseBatch(String id,JsonNode body,String header,String key){fields(body,"versionNo","reason","processPackageId","ebrTemplateVersionId");var c=mutations.context("production:batch:release");long expected=version(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"MainBatch:RELEASE:"+id,key,request(id,expected,body),()->{var row=lockBatch(c.organizationId(),MasterMutation.id(id));ProductionRules.version(row.getVersionNo(),expected);requireDraft(row.getStatus());var before=view(row);var order=db.orders.get(c.organizationId(),row.getProductionOrderId());var p=process.requireCurrentIdentified(c.organizationId(),ProductionInput.id(body,"processPackageId"));var e=ebr.requirePublished(c.organizationId(),ProductionInput.id(body,"ebrTemplateVersionId"));gate(p.path("productId").asText().equals(row.getProductId().toString())&&e.hasNonNull("processPackageId")&&e.path("processPackageId").asText().equals(p.path("processPackageId").asText()),"BATCH_DEFINITION_NOT_READY","Product/process/eBR mismatch");var content=json.createObjectNode();content.put("organizationId",Long.toString(c.organizationId()));content.set("process",p);content.set("ebr",e);if(bookPort!=null){var bp=bookPort.getIfAvailable();if(bp!=null){var book=bp.freeze(c.organizationId(),row.getProductId(),p,e);if(book!=null&&!book.isNull())content.set("book",book);}}var materialNodes=content.putArray("materials");var seen=new HashSet<Long>();for(var item:p.path("formula").path("items")){long material=ProductionInput.id(item,"materialId");if(seen.add(material)){var materialSnapshot=(ObjectNode)materials.requireUsable(c.organizationId(),material,Instant.now()).deepCopy();materialSnapshot.set("weighingPolicy",weighingPolicies.requirePolicy(c.organizationId(),material,ProductionInput.id(materialSnapshot,"baseUnitId")));materialNodes.add(materialSnapshot);}}
   var qualityPlanProvider=qualityPlans.getIfAvailable();if(qualityPlanProvider!=null){var qualityPlan=qualityPlanProvider.frozenPlan(c.organizationId(),row.getId(),p.path("route"));if(qualityPlan!=null&&!qualityPlan.isNull())content.set("qualityPlan",qualityPlan);}
   String hash=mutations.digest(content);var snapshot=db.snapshotMapper.selectOne(new QueryWrapper<SnapshotEntity>().eq("org_id",c.organizationId()).eq("snapshot_hash",hash));if(snapshot==null){snapshot=new SnapshotEntity();snapshot.setProcessPackageId(ProductionInput.id(p,"processPackageId"));snapshot.setFormulaVersionId(ProductionInput.id(p,"formulaId"));snapshot.setRouteVersionId(ProductionInput.id(p,"routeId"));snapshot.setEbrTemplateVersionId(ProductionInput.id(body,"ebrTemplateVersionId"));snapshot.setSnapshotJson(content.toString());snapshot.setSnapshotHash(hash);db.snapshots.insert(snapshot,c.organizationId(),c.actorId());}else gate(read(snapshot.getSnapshotJson()).equals(content),"SNAPSHOT_HASH_CONFLICT","Snapshot content collision");
   row.setProcessSnapshotId(snapshot.getId());row.setStatus(ProductionRules.release(row.getStatus()));row.setReleasedAt(now());db.batches.update(row,expected,c.actorId(),List.of("processSnapshotId","status","releasedAt"));var children=db.subs(c.organizationId(),row.getId());var ids=new ArrayList<Long>();if(children.isEmpty())ids.add(newExecution(row,null,c.actorId()));else for(var sub:children){ids.add(newExecution(row,sub,c.actorId()));sub.setStatus("READY");db.subs.update(sub,sub.getVersionNo(),c.actorId(),List.of("status"));}
   if("DRAFT".equals(order.getStatus())){var orderBefore=view(order);order.setStatus("IN_PROGRESS");db.orders.update(order,order.getVersionNo(),c.actorId(),List.of("status"));mutations.auditSnapshot(c,"ProductionOrder:FIRST_BATCH_RELEASED","ProductionOrder",order.getId(),orderBefore,view(order),reason,key);}
   events.publishEvent(new ProductionEvents.BatchReleased(c.organizationId(),c.actorId(),row.getId(),List.copyOf(ids)));runtime().requireInitialized(c.organizationId(),row.getId(),ids);mutations.auditSnapshot(c,"MainBatch:RELEASE","MainBatch",row.getId(),before,view(row),reason,key);return row;},this::view,200);}
 private long newExecution(BatchEntity batch,SubBatchEntity sub,long actor){var row=new ExecutionUnitEntity();row.setMainBatchId(batch.getId());row.setSubBatchId(sub==null?null:sub.getId());row.setUnitType(sub==null?"DIRECT":"SUB_BATCH");row.setExecutionNo(batch.getBatchNo()+"/"+(sub==null?"DIRECT":sub.getSequenceNo()));row.setStatus("READY");db.executions.insert(row,batch.getOrgId(),actor);return row.getId();}
 @Transactional public JsonNode startBatch(String id,JsonNode body,String header,String key){return batchAction(id,body,header,key,"START","production:batch:start");}
 @Transactional public JsonNode completeProduction(String id,JsonNode body,String header,String key){return batchAction(id,body,header,key,"COMPLETE","production:batch:complete");}
 @Transactional public JsonNode submitQa(String id,JsonNode body,String header,String key){return batchAction(id,body,header,key,"SUBMIT_QA","qa:batch-review");}
 private JsonNode batchAction(String id,JsonNode body,String header,String key,String action,String permission){fields(body,"versionNo","reason","reauthToken");var c=mutations.context(permission);long expected=version(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"MainBatch:"+action+":"+id,key,request(id,expected,body),()->{var row=lockBatch(c.organizationId(),MasterMutation.id(id));ProductionRules.version(row.getVersionNo(),expected);var before=view(row);var changed=new ArrayList<String>(List.of("status"));switch(action){case "START"->{row.setStatus(ProductionRules.startBatch(row.getStatus()));gate(db.executions(c.organizationId(),row.getId()).stream().anyMatch(x->"READY".equals(x.getStatus())),"BATCH_NOT_READY","A READY execution is required");row.setStartedAt(now());changed.add("startedAt");}case "COMPLETE"->{if(!"IN_PROGRESS".equals(row.getStatus()))throw new StateTransitionException("INVALID_BATCH_STATE","Batch not in progress");gate(db.executions(c.organizationId(),row.getId()).stream().allMatch(x->"COMPLETED".equals(x.getStatus())),"BATCH_EXECUTION_INCOMPLETE","Execution incomplete");runtime().requireProductionComplete(c.organizationId(),row.getId());row.setStatus("PRODUCTION_COMPLETED");row.setCompletedAt(now());changed.add("completedAt");}case "SUBMIT_QA"->{if(!"PRODUCTION_COMPLETED".equals(row.getStatus()))throw new StateTransitionException("INVALID_BATCH_STATE","Production incomplete");runtime().requireQaSubmissionReady(c.organizationId(),row.getId());row.setStatus("PENDING_QA");}default->throw new IllegalArgumentException("Unknown batch action");}db.batches.update(row,expected,c.actorId(),changed);if(action.equals("COMPLETE"))completeOrderIfReady(row,c,reason,key);mutations.auditSnapshot(c,"MainBatch:"+action,"MainBatch",row.getId(),before,view(row),reason,key);return row;},this::view,200);}
 private void completeOrderIfReady(BatchEntity batch,com.hospital.mes.audit.application.CurrentPlatformContext c,String reason,String key){var order=db.orders.lock(c.organizationId(),batch.getProductionOrderId());var children=db.lockedAllocations(c.organizationId(),order.getId());BigDecimal total=BigDecimal.ZERO;for(var child:children)total=total.add(exact(units,order.getOrgId(),child.getUnitId(),order.getUnitId(),null,child.getPlannedQty()));if(total.compareTo(order.getPlannedQty())==0&&children.stream().allMatch(x->Set.of("PRODUCTION_COMPLETED","PENDING_QA","QA_RELEASED","REJECTED").contains(x.getStatus()))){var before=view(order);order.setStatus("COMPLETED");db.orders.update(order,order.getVersionNo(),c.actorId(),List.of("status"));mutations.auditSnapshot(c,"ProductionOrder:COMPLETE","ProductionOrder",order.getId(),before,view(order),reason,key);}}
 private ProductionRuntimeGate runtime(){var value=runtime.getIfAvailable();if(value==null)throw new ComplianceException("DEPENDENCY_NOT_READY","Actual production runtime gate unavailable");return value;}
 private BatchEntity lockBatch(long org,long id){var row=db.batches.get(org,id);db.orders.lock(org,row.getProductionOrderId());return db.batches.lock(org,id);}
 private Map<String,Object> request(String id,long version,JsonNode body){var payload=body.deepCopy();((ObjectNode)payload).remove("reauthToken");return Map.of("id",id,"version",version,"body",payload);}
 private JsonNode read(String text){try{return json.readTree(text);}catch(java.io.IOException ex){throw new IllegalStateException("Invalid stored JSON",ex);}}
 public JsonNode view(ScopedEntity row){var out=views.view(row);if(row instanceof BatchEntity b){var subs=out.putArray("subBatches");db.subs(b.getOrgId(),b.getId()).forEach(x->subs.add(views.view(x)));var executions=out.putArray("executionUnits");db.executions(b.getOrgId(),b.getId()).forEach(x->executions.add(views.view(x)));out.set("processSnapshot",b.getProcessSnapshotId()==null?json.nullNode():views.view(db.snapshots.get(b.getOrgId(),b.getProcessSnapshotId())));}var actions=out.putArray("allowedActions");if(row instanceof OrderEntity o&&"DRAFT".equals(o.getStatus()))actions.add("EDIT");if(row instanceof BatchEntity b){switch(b.getStatus()){case "DRAFT"->{actions.add("EDIT");actions.add("RELEASE");actions.add("ADD_SUBBATCH");}case "RELEASED"->{actions.add("START");actions.add("RESERVATIONS");}case "IN_PROGRESS"->{actions.add("COMPLETE_PRODUCTION");actions.add("RESERVATIONS");}case "PRODUCTION_COMPLETED"->actions.add("SUBMIT_QA");default->{}}}return out;}
}
