package com.hospital.mes.process.domain;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static com.hospital.mes.process.domain.ProcessCommands.*;
class ProcessRulesTest {
 Operation op(String code,List<String> predecessors,List<Parameter> params){return new Operation(code,code,code.equals("A")?1:2,null,null,predecessors,null,false,params);}
 @Test void tcProc001And004OnlyDraftIsMutable(){ProcessRules.draft("DRAFT");for(String s:List.of("SUBMITTED","APPROVED","EFFECTIVE"))assertThatThrownBy(()->ProcessRules.draft(s)).hasMessageContaining("draft");assertThat(ProcessRules.transition("DRAFT","SUBMIT")).isEqualTo("SUBMITTED");assertThat(ProcessRules.transition("SUBMITTED","APPROVE")).isEqualTo("APPROVED");assertThat(ProcessRules.transition("APPROVED","PUBLISH")).isEqualTo("EFFECTIVE");assertThatThrownBy(()->ProcessRules.transition("DRAFT","PUBLISH")).hasMessageContaining("not allowed");}
 @Test void tcProc002RejectCyclesAndMissingReferences(){var cycle=new RouteSave(0L,"test","R",List.of(op("A",List.of("B"),List.of()),op("B",List.of("A"),List.of())));ProcessRules.route(cycle,false);assertThatThrownBy(()->ProcessRules.route(cycle,true)).hasMessageContaining("cycle");assertThatThrownBy(()->ProcessRules.route(new RouteSave(0L,"test","R",List.of(op("A",List.of("missing"),List.of()))),true)).hasMessageContaining("does not exist");ProcessRules.route(new RouteSave(0L,"test","R",List.of(op("A",List.of(),List.of()),op("B",List.of("A"),List.of()))),true);}
 @Test void parameterLimitsModesAndDecimalPrecision(){for(String mode:List.of("MANUAL","AUTO","HYBRID"))ProcessRules.route(new RouteSave(0L,"test","R",List.of(op("A",List.of(),List.of(new Parameter("P","Pressure",mode,null,"-1.123456","2"))))),true);assertThatThrownBy(()->ProcessRules.route(new RouteSave(0L,"test","R",List.of(op("A",List.of(),List.of(new Parameter("P","Pressure","AUTO",null,"3","2"))))),true)).hasMessageContaining("lower limit");assertThatThrownBy(()->ProcessRules.decimal("1.1234567",18,true,"qty")).hasMessageContaining("decimal");assertThatThrownBy(()->ProcessRules.decimal("1000000000000",18,true,"qty")).hasMessageContaining("precision");}
 @Test void completionRulesRejectExecutableExpressions(){var o=new Operation("A","Mix",1,null,new CompletionRule("eval(1)",null),List.of(),null,false,List.of());assertThatThrownBy(()->ProcessRules.route(new RouteSave(0L,"test","R",List.of(o)),true)).hasMessageContaining("unknown kind");}
 @Test void bomRejectsDuplicateLinesNegativeQuantities(){var i=new FormulaLine(1,"1","1","1",null,true);assertThatThrownBy(()->ProcessRules.formula(new FormulaSave(0L,"test","F","1","1",List.of(i,i)))).hasMessageContaining("duplicate");assertThatThrownBy(()->ProcessRules.formula(new FormulaSave(0L,"test","F","0","1",List.of(i)))).hasMessageContaining("positive");}
}
