package com.hospital.mes.process.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.process.infrastructure.*;
import com.hospital.mes.process.domain.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.masterdata.infrastructure.ScopedEntity;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.common.exception.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.time.*;
import static com.hospital.mes.process.domain.ProcessCommands.*;
import static com.hospital.mes.process.domain.ProcessRules.*;

@Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class ProcessService {
 private final ProcessStore db;private final ProcessDefinitions definitions;private final MasterMutation mutations;private final MasterQueryService units;private final ObjectMapper json;private final SignatureApplicationService signing;private final SignatureRepository signatures;private final SignatureCanonicalizer canonicalizer;private final org.springframework.context.ApplicationEventPublisher events;
 public ProcessService(ProcessStore db,ProcessDefinitions definitions,MasterMutation mutations,MasterQueryService units,ObjectMapper json,SignatureApplicationService signing,SignatureRepository signatures,SignatureCanonicalizer canonicalizer,org.springframework.context.ApplicationEventPublisher events){this.db=db;this.definitions=definitions;this.mutations=mutations;this.units=units;this.json=json;this.signing=signing;this.signatures=signatures;this.canonicalizer=canonicalizer;this.events=events;}
 public ScopedStore.PageData<JsonNode> products(int page,int size,String keyword,Map<String,String> filters){var c=mutations.context("master:product:view");var p=db.products().list(c.organizationId(),page,size,keyword,filters);return new ScopedStore.PageData<>(p.items().stream().map(this::view).map(n->(JsonNode)n).toList(),p.total(),page,size);}
 public JsonNode product(String id){var c=mutations.context("master:product:view");return view(db.products().get(c.organizationId(),MasterMutation.id(id)));}
 @Transactional public JsonNode createProduct(ProductCreate r,String key){var c=mutations.context("master:product:create");return mutations.execute(c,"Product:CREATE",key,r,()->{var p=new ProductEntity();p.setProductCode(text(r.productCode(),64,"productCode"));if(db.products().count(c.organizationId(),"product_code",p.getProductCode(),null)>0)throw new ResourceConflictException("DUPLICATE_CODE","productCode already exists");apply(p,r.productName(),r.dosageForm(),r.specification(),r.baseUnitId(),c.organizationId());p.setStatus("ACTIVE");db.products().insert(p,c.organizationId(),c.actorId());mutations.audit(c,"Product:CREATE","Product",null,p,null,key);return p;},e->view(e),200);}
 @Transactional public JsonNode updateProduct(String id,ProductUpdate r,String header,String key){var c=mutations.context("master:product:update");long expected=MasterMutation.version(header,r.versionNo());String reason=text(r.reason(),1000,"reason");gate(Set.of("UPDATE","DISABLE").contains(r.action()==null?"":r.action()),"action: UPDATE/DISABLE required");return mutations.execute(c,"Product:"+r.action()+":"+id,key,Map.of("id",id,"version",expected,"body",r),()->{var p=db.products().lock(c.organizationId(),MasterMutation.id(id));expected(p,expected);var before=view(p);if(r.action().equals("DISABLE")){gate("ACTIVE".equals(p.getStatus()),"product already inactive");p.setStatus("INACTIVE");db.products().update(p,expected,c.actorId(),List.of("status"));}else{apply(p,r.productName(),r.dosageForm(),r.specification(),r.baseUnitId(),c.organizationId());db.products().update(p,expected,c.actorId(),List.of("productName","dosageForm","specification","baseUnitId"));}mutations.auditSnapshot(c,"Product:"+r.action(),"Product",p.getId(),before,view(p),reason,key);return p;},this::view,200);}
 private void apply(ProductEntity p,String name,String dosage,String spec,String unit,long org){p.setProductName(text(name,200,"productName"));p.setDosageForm(optional(dosage,100,"dosageForm"));p.setSpecification(optional(spec,200,"specification"));p.setBaseUnitId(MasterMutation.id(unit));units.unit(org,p.getBaseUnitId());}
 public ScopedStore.PageData<JsonNode> packages(int page,int size,String keyword,Map<String,String> filters){var c=mutations.context("process:package:view");var p=db.packagePage(c.organizationId(),page,size,keyword,filters);return new ScopedStore.PageData<>(p.items().stream().map(row->{Long selected=null;if(java.util.stream.Stream.of("status","version","effectiveFrom").anyMatch(k->filters.get(k)!=null&&!filters.get(k).isBlank()))selected=db.matchingVersions(c.organizationId(),filters.get("status"),filters.get("version"),filters.get("effectiveFrom")).stream().filter(v->v.getPackageId().equals(row.getId())).max(Comparator.comparing(VersionEntity::getBusinessVersion)).map(VersionEntity::getId).orElse(null);return packageView(row,selected);}).toList(),p.total(),page,size);}
 public JsonNode getPackage(String id,String versionId){var c=mutations.context("process:package:view");return packageView(db.packages().get(c.organizationId(),MasterMutation.id(id)),versionId==null?null:MasterMutation.id(versionId));}
 @Transactional public JsonNode createPackage(PackageCreate r,String key){var c=mutations.context("process:package:create");return mutations.execute(c,"ProcessPackage:CREATE",key,r,()->{var product=db.products().get(c.organizationId(),MasterMutation.id(r.productId()));gate(product.getStatus().equals("ACTIVE"),"product: inactive");var p=new PackageEntity();p.setProductId(product.getId());p.setPackageCode(text(r.packageCode(),64,"packageCode"));if(db.packages().count(c.organizationId(),"package_code",p.getPackageCode(),null)>0)throw new ResourceConflictException("DUPLICATE_CODE","packageCode already exists");p.setStatus("ACTIVE");db.packages().insert(p,c.organizationId(),c.actorId());var v=newVersion(p,1,c);mutations.auditSnapshot(c,"ProcessPackage:CREATE","ProcessPackage",p.getId(),null,packageView(p,v.getId()),null,key);mutations.auditSnapshot(c,"ProcessVersion:CREATE","ProcessVersion",v.getId(),null,versionView(v,true),null,key);return p;},e->packageView((PackageEntity)e,null),200);}
 @Transactional public JsonNode updatePackage(String id,PackageUpdate r,String header,String key){var c=mutations.context("process:package:update");long expected=MasterMutation.version(header,r.versionNo());String reason=text(r.reason(),1000,"reason");gate("DISABLE".equals(r.action()),"action: DISABLE required");return mutations.execute(c,"ProcessPackage:DISABLE:"+id,key,Map.of("id",id,"version",expected,"body",r),()->{var p=db.packages().lock(c.organizationId(),MasterMutation.id(id));expected(p,expected);var before=view(p);gate("ACTIVE".equals(p.getStatus()),"package already inactive");p.setStatus("INACTIVE");db.packages().update(p,expected,c.actorId(),List.of("status"));mutations.auditSnapshot(c,"ProcessPackage:DISABLE","ProcessPackage",p.getId(),before,view(p),reason,key);return p;},e->packageView((PackageEntity)e,null),200);}
 @Transactional public JsonNode createVersion(String id,VersionCreate r,String header,String key){var c=mutations.context("process:package:edit");long expected=MasterMutation.version(header,r.versionNo());String reason=text(r.reason(),1000,"reason");return mutations.execute(c,"ProcessVersion:CREATE:"+id,key,Map.of("id",id,"version",expected,"body",r),()->{var p=db.packages().lock(c.organizationId(),MasterMutation.id(id));expected(p,expected);gate(p.getStatus().equals("ACTIVE"),"package: inactive");var vs=db.versions(c.organizationId(),p.getId());if(vs.stream().anyMatch(v->v.getStatus().equals("DRAFT")))throw new ResourceConflictException("DRAFT_EXISTS","Maintain the existing draft first");VersionEntity source=null;if(r.sourceVersionId()!=null){source=db.versions().get(c.organizationId(),MasterMutation.id(r.sourceVersionId()));if(!source.getPackageId().equals(p.getId()))throw new NoSuchElementException("Version not in package");}var v=newVersion(p,vs.stream().mapToInt(VersionEntity::getBusinessVersion).max().orElse(0)+1,c);if(source!=null){var f=definitions.formula(c.organizationId(),source);if(f!=null)definitions.saveFormula(c,v,f);var route=definitions.route(c.organizationId(),source);if(route!=null)definitions.saveRoute(c,v,route);}db.packages().update(p,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"ProcessVersion:CREATE","ProcessVersion",v.getId(),null,versionView(v,true),reason,key);return p;},e->packageView((PackageEntity)e,null),200);}
 private VersionEntity newVersion(PackageEntity p,int number,com.hospital.mes.audit.application.CurrentPlatformContext c){var v=new VersionEntity();v.setPackageId(p.getId());v.setBusinessVersion(number);v.setStatus("DRAFT");db.versions().insert(v,c.organizationId(),c.actorId());return v;}
 public JsonNode formula(String id){var c=mutations.context("process:package:view");return definitions.formulaView(c.organizationId(),db.versions().get(c.organizationId(),MasterMutation.id(id)));}
 public JsonNode route(String id){var c=mutations.context("process:package:view");return definitions.routeView(c.organizationId(),db.versions().get(c.organizationId(),MasterMutation.id(id)));}
 @Transactional public JsonNode saveFormula(String id,FormulaSave r,String header,String key){var c=mutations.context("process:package:edit");long expected=MasterMutation.version(header,r.versionNo());String reason=text(r.reason(),1000,"reason");return mutations.execute(c,"ProcessVersion:FORMULA:"+id,key,Map.of("id",id,"version",expected,"body",r),()->{var v=lockVersion(c.organizationId(),id);expected(v,expected);draft(v.getStatus());definitions.usableRoot(c.organizationId(),v);var before=versionView(v,true);definitions.saveFormula(c,v,r);db.versions().update(v,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"ProcessVersion:FORMULA","ProcessVersion",v.getId(),before,versionView(v,true),reason,key);return v;},e->versionView((VersionEntity)e,true),200);}
 @Transactional public JsonNode saveRoute(String id,RouteSave r,String header,String key){var c=mutations.context("process:package:edit");long expected=MasterMutation.version(header,r.versionNo());String reason=text(r.reason(),1000,"reason");return mutations.execute(c,"ProcessVersion:ROUTE:"+id,key,Map.of("id",id,"version",expected,"body",r),()->{var v=lockVersion(c.organizationId(),id);expected(v,expected);draft(v.getStatus());definitions.usableRoot(c.organizationId(),v);var before=versionView(v,true);definitions.saveRoute(c,v,r);db.versions().update(v,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"ProcessVersion:ROUTE","ProcessVersion",v.getId(),before,versionView(v,true),reason,key);return v;},e->versionView((VersionEntity)e,true),200);}
 @Transactional public JsonNode lint(String id,Transition r,String header,String key){var c=mutations.context("process:package:edit");long expected=MasterMutation.version(header,r.versionNo());String reason=text(r.reason(),1000,"reason");return mutations.execute(c,"ProcessVersion:LINT:"+id,key,Map.of("id",id,"version",expected,"reason",reason),()->{var v=lockVersion(c.organizationId(),id);expected(v,expected);definitions.lint(c.organizationId(),v);mutations.auditSnapshot(c,"ProcessVersion:LINT","ProcessVersion",v.getId(),versionView(v,true),versionView(v,true),reason,key);return v;},e->json.createObjectNode().put("valid",true).set("issues",json.createArrayNode()),200);}
 @Transactional public JsonNode transition(String id,String action,Transition r,String header,String key){var c=mutations.context("process:package:"+action.toLowerCase(Locale.ROOT));if(action.equals("APPROVE"))mutations.context("ebr:sign");long expected=MasterMutation.version(header,r.versionNo());String reason=text(r.reason(),1000,"reason");return mutations.execute(c,"ProcessVersion:"+action+":"+id,key,Map.of("id",id,"version",expected,"reason",reason),()->{var v=lockVersion(c.organizationId(),id);expected(v,expected);String next=ProcessRules.transition(v.getStatus(),action);definitions.lint(c.organizationId(),v);var before=versionView(v,true);if(action.equals("APPROVE")){definitions.independentApprover(c.organizationId(),v,c.actorId());var signature=signing.sign(new SignCommand(c,"ProcessVersion",id,SignatureMeaning.APPROVE,v.getBusinessVersion(),r.reauthToken(),com.hospital.mes.audit.idempotency.PlatformIdempotencyService.digest(key+":sign"),null));v.setContentHash(signature.recordDigest());}if(action.equals("PUBLISH")){requireValidSignature(v);v.setEffectiveFrom(LocalDateTime.now(ZoneOffset.UTC).truncatedTo(java.time.temporal.ChronoUnit.MILLIS));}v.setStatus(next);db.versions().update(v,expected,c.actorId(),List.of("status","contentHash","effectiveFrom"));mutations.auditSnapshot(c,"ProcessVersion:"+action,"ProcessVersion",v.getId(),before,versionView(v,true),reason,key);events.publishEvent(switch(action){case "SUBMIT"->new ProcessEvents.Submitted(c.organizationId(),v.getId());case "APPROVE"->new ProcessEvents.Approved(c.organizationId(),v.getId());case "PUBLISH"->new ProcessEvents.Published(c.organizationId(),v.getId());default->throw new IllegalArgumentException("Unknown process command");});return v;},e->versionView((VersionEntity)e,true),200);}
 private VersionEntity lockVersion(long org,String id){var found=db.versions().get(org,MasterMutation.id(id));db.packages().lock(org,found.getPackageId());return db.versions().lock(org,found.getId());}
 public JsonNode snapshot(long org,long versionId,boolean usable){var v=db.versions().get(org,versionId);if(usable){gate(Set.of("APPROVED","EFFECTIVE").contains(v.getStatus()),"process version not approved");definitions.usableRoot(org,v);requireValidSignature(v);}return definitions.signable(org,v).canonicalRecord().deepCopy();}
 private void requireValidSignature(VersionEntity v){String digest=canonicalizer.digest(definitions.signable(v.getOrgId(),v));gate(digest.equals(v.getContentHash()),"process content hash changed");gate(signatures.findValid(v.getOrgId(),"ProcessVersion",v.getId().toString()).stream().anyMatch(s->s.meaning()==SignatureMeaning.APPROVE&&s.recordDigest().equals(digest)),"process approval signature not valid");}
 private JsonNode packageView(PackageEntity p,Long selected){var n=view(p);n.put("productName",db.products().get(p.getOrgId(),p.getProductId()).getProductName());var versions=db.versions(p.getOrgId(),p.getId());VersionEntity choice=null;if(selected!=null){choice=versions.stream().filter(v->v.getId().equals(selected)).findFirst().orElseThrow(()->new NoSuchElementException("Version not in package"));}else if(!versions.isEmpty())choice=versions.getFirst();n.set("selectedVersion",choice==null?json.nullNode():versionView(choice,true));var a=n.putArray("versions");versions.forEach(v->a.add(versionView(v,false)));return n;}
 private ObjectNode versionView(VersionEntity v,boolean content){var n=view(v);n.set("formula",content?definitions.formulaView(v.getOrgId(),v):json.nullNode());n.set("route",content?definitions.routeView(v.getOrgId(),v):json.nullNode());n.putNull("approval");if(v.getContentHash()!=null)signatures.findValid(v.getOrgId(),"ProcessVersion",v.getId().toString()).stream().filter(s->s.meaning()==SignatureMeaning.APPROVE&&s.recordDigest().equals(v.getContentHash())).max(Comparator.comparing(SignatureRecord::signedAt)).ifPresent(s->{var a=n.putObject("approval");a.put("signerId",Long.toString(s.signerId()));a.put("signedAt",s.signedAt().toString());a.put("signatureId",Long.toString(s.id()));a.put("recordDigest",s.recordDigest());});return n;}
 private ObjectNode view(ScopedEntity e){var n=(ObjectNode)mutations.view(e);for(String key:List.of("productId","packageId","packageVersionId"))if(n.hasNonNull(key))n.put(key,n.get(key).asText());return n;}
 private void expected(ScopedEntity row,long version){if(row.getVersionNo()!=version)throw new ResourceConflictException("VERSION_CONFLICT","Reload before saving");}
}
