package com.hospital.mes.process.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.process.infrastructure.*;
import com.hospital.mes.process.domain.ProcessRules;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.audit.application.CurrentPlatformContext;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.common.exception.*;
import java.util.*;
import java.time.*;
import static com.hospital.mes.process.domain.ProcessCommands.*;
import static com.hospital.mes.process.domain.ProcessRules.*;

@org.springframework.stereotype.Service
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class ProcessDefinitions {
 private final ProcessStore db;private final MasterQueryService units;private final MaterialQueryService materials;private final ObjectMapper json;private final MasterMutation mutations;
 public ProcessDefinitions(ProcessStore db,MasterQueryService units,MaterialQueryService materials,ObjectMapper json,MasterMutation mutations){this.db=db;this.units=units;this.materials=materials;this.json=json;this.mutations=mutations;}
 public FormulaSave formula(long org,VersionEntity v){var f=db.formula(org,v);if(f==null)return null;return new FormulaSave(v.getVersionNo(),null,f.getFormulaCode(),decimal(f.getBatchBasisQty()),f.getUnitId().toString(),db.items(org,f.getId()).stream().map(i->new FormulaLine(i.getLineNo(),i.getMaterialId().toString(),decimal(i.getRequiredQty()),i.getUnitId().toString(),decimal(i.getOveragePct()),i.getCritical())).toList());}
 public RouteSave route(long org,VersionEntity v){var r=db.route(org,v);if(r==null)return null;return new RouteSave(v.getVersionNo(),null,r.getRouteCode(),db.operations(org,r.getId()).stream().map(o->new Operation(o.getOperationCode(),o.getOperationName(),o.getSequenceNo(),o.getRequiredRole(),read(o.getCompletionRule(),CompletionRule.class),readCodes(o.getPredecessorCodesJson()),o.getRequiredEquipmentType(),o.getClearanceRequired(),db.parameters(org,o.getId()).stream().map(p->new Parameter(p.getParameterCode(),p.getParameterName(),p.getAcquisitionMode(),p.getUnitId()==null?null:p.getUnitId().toString(),decimal(p.getLowerLimit()),decimal(p.getUpperLimit()))).toList(),readIpc(o.getIpcDefinitionsJson()))).toList());}
 public JsonNode formulaView(long org,VersionEntity v){var f=formula(org,v);return f==null?json.nullNode():((ObjectNode)json.valueToTree(f)).without("reason");}
 public JsonNode routeView(long org,VersionEntity v){var r=route(org,v);return r==null?json.nullNode():((ObjectNode)json.valueToTree(r)).without("reason");}
 public SignableObject signable(long org,VersionEntity v){var pkg=db.packages().get(org,v.getPackageId());var n=json.createObjectNode();n.put("packageId",pkg.getId().toString());n.put("packageCode",pkg.getPackageCode());if(pkg.getProductId()!=null)n.put("productId",pkg.getProductId().toString());if(!(v instanceof CurrentDefinitionEntity))n.put("businessVersion",v.getBusinessVersion());var f=formulaView(org,v).deepCopy();var r=routeView(org,v).deepCopy();if(f.isObject())((ObjectNode)f).remove("versionNo");if(r.isObject())((ObjectNode)r).remove("versionNo");n.set("formula",f);n.set("route",r);return new SignableObject(v instanceof CurrentDefinitionEntity?"CurrentProcessDefinition":"ProcessVersion",v.getId().toString(),v.getBusinessVersion(),n,List.of());}
 public void usableRoot(long org,VersionEntity v){var p=db.packages().get(org,v.getPackageId());gate("ACTIVE".equals(p.getStatus()),"package: inactive");if(p.getProductId()!=null)gate("ACTIVE".equals(db.products().get(org,p.getProductId()).getStatus()),"product: inactive");}
 public void lint(long org,VersionEntity v){usableRoot(org,v);var f=formula(org,v);var r=route(org,v);gate(r!=null,"route: definition required");if(v instanceof CurrentDefinitionEntity){if(f!=null){validateFormula(org,f);gate(!f.items().isEmpty(),"formula.items: at least one material required");}validateRoute(org,r,true);return;}gate(f!=null,"formula: definition required");validateFormula(org,f);gate(!f.items().isEmpty(),"formula.items: at least one material required");validateRoute(org,r,true);}
 public void independentApprover(long org,VersionEntity v,long actor){gate(v.getCreatedBy()!=actor&&v.getUpdatedBy()!=actor,"approval: creator/submitter cannot approve");var f=db.formula(org,v);var r=db.route(org,v);if(f!=null){gate(f.getUpdatedBy()!=actor,"approval: formula editor cannot approve");for(var i:db.items(org,f.getId()))gate(i.getUpdatedBy()!=actor,"approval: BOM editor cannot approve");}if(r!=null){gate(r.getUpdatedBy()!=actor,"approval: route editor cannot approve");for(var o:db.operations(org,r.getId())){gate(o.getUpdatedBy()!=actor,"approval: operation editor cannot approve");for(var p:db.parameters(org,o.getId()))gate(p.getUpdatedBy()!=actor,"approval: parameter editor cannot approve");}}}
 public void validateFormula(long org,FormulaSave f){ProcessRules.formula(f);units.unit(org,MasterMutation.id(f.unitId()));for(var i:f.items()){String path="formula.items["+i.lineNo()+"]";try{var material=materials.requireUsable(org,MasterMutation.id(i.materialId()),Instant.now());units.convert(org,MasterMutation.id(i.unitId()),material.get("baseUnitId").asLong(),MasterMutation.id(i.materialId()),ProcessRules.decimal(i.requiredQty(),18,true,path));}catch(ComplianceException|NoSuchElementException ex){throw new ComplianceException("LINT_FAILED",path+": material/unit unavailable or incompatible");}}}
 public void validateRoute(long org,RouteSave r,boolean lint){ProcessRules.route(r,lint);for(var o:r.operations())for(var ipc:o.ipcDefinitions())if(ipc.unitId()!=null)units.unit(org,MasterMutation.id(ipc.unitId()));for(var o:r.operations())for(var p:o.parameters())if(p.unitId()!=null&&!p.unitId().isBlank())units.unit(org,MasterMutation.id(p.unitId()));}
 public void saveFormula(CurrentPlatformContext c,VersionEntity v,FormulaSave request){
  validateFormula(c.organizationId(),request);var f=db.formula(c.organizationId(),v);boolean fresh=f==null;if(fresh){f=new FormulaEntity();if(v instanceof CurrentDefinitionEntity)f.setCurrentDefinitionId(v.getId());else {f.setPackageVersionId(v.getId());f.setBusinessVersion(v.getBusinessVersion());}}
  var existing=fresh?List.<FormulaItemEntity>of():db.items(c.organizationId(),f.getId());Set<Integer> wanted=new HashSet<>();request.items().forEach(i->wanted.add(i.lineNo()));for(var item:existing)retained(wanted.contains(item.getLineNo()));
  f.setFormulaCode(text(request.formulaCode(),64,"formulaCode"));f.setBatchBasisQty(ProcessRules.decimal(request.batchBasisQty(),18,true,"batchBasisQty"));f.setUnitId(MasterMutation.id(request.unitId()));if(fresh)db.formulas().insert(f,c.organizationId(),c.actorId());else db.formulas().update(f,f.getVersionNo(),c.actorId(),List.of("formulaCode","batchBasisQty","unitId"));
  for(var line:request.items()){var item=existing.stream().filter(i->i.getLineNo().equals(line.lineNo())).findFirst().orElse(null);boolean add=item==null;if(add){item=new FormulaItemEntity();item.setFormulaVersionId(f.getId());item.setLineNo(line.lineNo());}item.setMaterialId(MasterMutation.id(line.materialId()));item.setRequiredQty(ProcessRules.decimal(line.requiredQty(),18,true,"requiredQty"));item.setUnitId(MasterMutation.id(line.unitId()));item.setOveragePct(nullableDecimal(line.overagePct(),9,"overagePct"));item.setCritical(line.critical());if(add)db.items().insert(item,c.organizationId(),c.actorId());else db.items().update(item,item.getVersionNo(),c.actorId(),List.of("materialId","requiredQty","unitId","overagePct","critical"));}
 }
 public void saveRoute(CurrentPlatformContext c,VersionEntity v,RouteSave request){
  validateRoute(c.organizationId(),request,false);var r=db.route(c.organizationId(),v);boolean fresh=r==null;if(fresh){r=new RouteEntity();if(v instanceof CurrentDefinitionEntity)r.setCurrentDefinitionId(v.getId());else {r.setPackageVersionId(v.getId());r.setBusinessVersion(v.getBusinessVersion());}}var existing=fresh?List.<OperationEntity>of():db.operations(c.organizationId(),r.getId());Set<String> wanted=new HashSet<>();request.operations().forEach(o->wanted.add(o.operationCode()));for(var o:existing)retained(wanted.contains(o.getOperationCode()));r.setRouteCode(text(request.routeCode(),64,"routeCode"));if(fresh)db.routes().insert(r,c.organizationId(),c.actorId());else db.routes().update(r,r.getVersionNo(),c.actorId(),List.of("routeCode"));
  for(var op:request.operations()){
   var o=existing.stream().filter(x->x.getOperationCode().equals(op.operationCode())).findFirst().orElse(null);boolean add=o==null;if(add){o=new OperationEntity();o.setRouteVersionId(r.getId());o.setOperationCode(op.operationCode());}var parameters=add?List.<ParameterEntity>of():db.parameters(c.organizationId(),o.getId());Set<String> parameterCodes=new HashSet<>();op.parameters().forEach(p->parameterCodes.add(p.parameterCode()));for(var p:parameters)retained(parameterCodes.contains(p.getParameterCode()));
   o.setOperationName(text(op.operationName(),200,"operationName"));o.setSequenceNo(op.sequenceNo());o.setRequiredRole(optional(op.requiredRole(),64,"requiredRole"));o.setCompletionRule(op.completionRule()==null?null:encode(op.completionRule()));o.setPredecessorCodesJson(encode(op.predecessorCodes()));o.setRequiredEquipmentType(optional(op.requiredEquipmentType(),64,"requiredEquipmentType"));o.setClearanceRequired(op.clearanceRequired());o.setIpcDefinitionsJson(encode(op.ipcDefinitions()));if(add)db.operations().insert(o,c.organizationId(),c.actorId());else db.operations().update(o,o.getVersionNo(),c.actorId(),List.of("operationName","sequenceNo","requiredRole","completionRule","predecessorCodesJson","requiredEquipmentType","clearanceRequired","ipcDefinitionsJson"));
   for(var param:op.parameters()){var p=parameters.stream().filter(x->x.getParameterCode().equals(param.parameterCode())).findFirst().orElse(null);boolean newParam=p==null;if(newParam){p=new ParameterEntity();p.setOperationDefId(o.getId());p.setParameterCode(param.parameterCode());}p.setParameterName(text(param.parameterName(),200,"parameterName"));p.setAcquisitionMode(param.acquisitionMode());p.setUnitId(param.unitId()==null||param.unitId().isBlank()?null:MasterMutation.id(param.unitId()));p.setLowerLimit(nullableDecimal(param.lowerLimit(),18,"lowerLimit"));p.setUpperLimit(nullableDecimal(param.upperLimit(),18,"upperLimit"));if(newParam)db.parameters().insert(p,c.organizationId(),c.actorId());else db.parameters().update(p,p.getVersionNo(),c.actorId(),List.of("parameterName","acquisitionMode","unitId","lowerLimit","upperLimit"));}
  }
 }
 private static void retained(boolean yes){if(!yes)throw new ResourceConflictException("RETAINED_DEFINITION_REQUIRED","Referenced definitions must be retained to preserve execution and lineage identities");}
 private java.util.List<IpcDefinition> readIpc(String value){try{return value==null?java.util.List.of():json.readValue(value,new com.fasterxml.jackson.core.type.TypeReference<java.util.List<IpcDefinition>>(){});}catch(Exception e){throw new IllegalStateException("Invalid stored IPC definition",e);}}
 private static String decimal(java.math.BigDecimal v){return v==null?null:v.stripTrailingZeros().toPlainString();}
 private String encode(Object value){try{return json.writeValueAsString(value);}catch(Exception ex){throw new IllegalArgumentException("Invalid definition",ex);}}
 private <T>T read(String value,Class<T> type){if(value==null)return null;try{return json.readValue(value,type);}catch(Exception ex){throw new IllegalStateException("Stored definition invalid",ex);}}
 private List<String> readCodes(String value){try{return json.readValue(value,new com.fasterxml.jackson.core.type.TypeReference<List<String>>(){});}catch(Exception ex){throw new IllegalStateException("Stored predecessors invalid",ex);}}
}
