package com.hospital.mes.process.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.process.infrastructure.*;
import com.hospital.mes.process.domain.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.masterdata.infrastructure.ScopedEntity;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.common.exception.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.time.*;
import static com.hospital.mes.process.domain.ProcessCommands.*;
import static com.hospital.mes.process.domain.ProcessRules.*;

@Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class ProcessService {
 private final ProcessStore db;private final ProcessDefinitions definitions;private final MasterMutation mutations;private final MasterQueryService units;private final ObjectMapper json;private final SignatureApplicationService signing;private final SignatureRepository signatures;private final SignatureCanonicalizer canonicalizer;private final org.springframework.context.ApplicationEventPublisher events;
 public ProcessService(ProcessStore db,ProcessDefinitions definitions,MasterMutation mutations,MasterQueryService units,ObjectMapper json,SignatureApplicationService signing,SignatureRepository signatures,SignatureCanonicalizer canonicalizer,org.springframework.context.ApplicationEventPublisher events){this.db=db;this.definitions=definitions;this.mutations=mutations;this.units=units;this.json=json;this.signing=signing;this.signatures=signatures;this.canonicalizer=canonicalizer;this.events=events;}
 public ScopedStore.PageData<JsonNode> products(int page,int size,String keyword,Map<String,String> filters){var c=mutations.context("master:product:view");var p=db.products().list(c.organizationId(),page,size,keyword,filters);return new ScopedStore.PageData<>(p.items().stream().map(this::view).map(n->(JsonNode)n).toList(),p.total(),page,size);}
 public JsonNode product(String id){var c=mutations.context("master:product:view");return view(db.products().get(c.organizationId(),MasterMutation.id(id)));}
 @Transactional(isolation=org.springframework.transaction.annotation.Isolation.READ_COMMITTED) public JsonNode createProduct(ProductCreate r,String key){var c=mutations.context("master:product:create");return mutations.execute(c,"Product:CREATE",key,r,()->{var p=new ProductEntity();p.setProductCode(text(r.productCode(),64,"productCode"));if(db.products().count(c.organizationId(),"product_code",p.getProductCode(),null)>0)throw new ResourceConflictException("DUPLICATE_CODE","productCode already exists");apply(p,r.productName(),r.dosageForm(),r.specification(),r.baseUnitId(),c.organizationId());p.setStatus("ACTIVE");db.products().insert(p,c.organizationId(),c.actorId());return p;},e->view(e),200);}
 @Transactional(isolation=org.springframework.transaction.annotation.Isolation.READ_COMMITTED) public JsonNode updateProduct(String id,ProductUpdate r,String header,String key){var c=mutations.context("master:product:update");long expected=0L;String reason=text(r.reason()==null||r.reason().isBlank()?"工艺配置维护（系统记录）":r.reason(),1000,"reason");gate(Set.of("UPDATE","DISABLE").contains(r.action()==null?"":r.action()),"action: UPDATE/DISABLE required");return mutations.execute(c,"Product:"+r.action()+":"+id,key,Map.of("id",id,"version",expected,"body",r),()->{var p=db.products().lock(c.organizationId(),MasterMutation.id(id));var before=view(p);if(r.action().equals("DISABLE")){gate("ACTIVE".equals(p.getStatus()),"product already inactive");p.setStatus("INACTIVE");db.products().update(p,expected,c.actorId(),List.of("status"));}else{apply(p,r.productName(),r.dosageForm(),r.specification(),r.baseUnitId(),c.organizationId());db.products().update(p,expected,c.actorId(),List.of("productName","dosageForm","specification","baseUnitId"));}return p;},this::view,200);}
 private void apply(ProductEntity p,String name,String dosage,String spec,String unit,long org){p.setProductName(text(name,200,"productName"));p.setDosageForm(optional(dosage,100,"dosageForm"));p.setSpecification(optional(spec,200,"specification"));p.setBaseUnitId(MasterMutation.id(unit));units.unit(org,p.getBaseUnitId());}
 public ScopedStore.PageData<JsonNode> packages(int page,int size,String keyword,Map<String,String> filters){var c=mutations.context("process:package:view");var rows=db.packagePage(c.organizationId(),page,size,keyword,filters);return new ScopedStore.PageData<>(rows.items().stream().map(p->packageView(p,null)).toList(),rows.total(),page,size);}
 public JsonNode getPackage(String id,String versionId){var c=mutations.context("process:package:view");return packageView(db.packages().get(c.organizationId(),MasterMutation.id(id)),versionId==null?null:MasterMutation.id(versionId));}
 @Transactional(isolation=org.springframework.transaction.annotation.Isolation.READ_COMMITTED) public JsonNode createPackage(PackageCreate r,String key){var c=mutations.context("process:package:create");return mutations.execute(c,"ProcessPackage:CREATE",key,r,()->{var p=new PackageEntity();if(r.productId()!=null&&!r.productId().isBlank()){var product=db.products().get(c.organizationId(),MasterMutation.id(r.productId()));gate(product.getStatus().equals("ACTIVE"),"product: inactive");p.setProductId(product.getId());}p.setPackageCode(text(r.packageCode(),64,"packageCode"));if(db.packages().count(c.organizationId(),"package_code",p.getPackageCode(),null)>0)throw new ResourceConflictException("DUPLICATE_CODE","packageCode already exists");p.setStatus("ACTIVE");db.packages().insert(p,c.organizationId(),c.actorId());var v=new CurrentDefinitionEntity();v.setPackageId(p.getId());v.setStatus("DRAFT");db.current().insert(v,c.organizationId(),c.actorId());return p;},e->packageView((PackageEntity)e,null),200);}
 @Transactional(isolation=org.springframework.transaction.annotation.Isolation.READ_COMMITTED) public JsonNode updatePackage(String id,PackageUpdate r,String header,String key){var c=mutations.context("process:package:update");long expected=0L;String reason=text(r.reason()==null||r.reason().isBlank()?"工艺配置维护（系统记录）":r.reason(),1000,"reason");gate("DISABLE".equals(r.action()),"action: DISABLE required");return mutations.execute(c,"ProcessPackage:DISABLE:"+id,key,Map.of("id",id,"version",expected,"body",r),()->{var p=db.packages().lock(c.organizationId(),MasterMutation.id(id));var before=view(p);gate("ACTIVE".equals(p.getStatus()),"package already inactive");p.setStatus("INACTIVE");db.packages().update(p,expected,c.actorId(),List.of("status"));return p;},e->packageView((PackageEntity)e,null),200);}
 @Transactional(isolation=org.springframework.transaction.annotation.Isolation.READ_COMMITTED) public JsonNode saveCurrentDefinition(String id,CurrentDefinitionSave r,String header,String key){var c=mutations.context("process:package:edit");gate(r.route()!=null,"route required");return mutations.execute(c,"ProcessPackage:MAINTAIN_CURRENT:"+id,key,Map.of("id",id,"body",r),()->{var p=db.packages().lock(c.organizationId(),MasterMutation.id(id));gate("ACTIVE".equals(p.getStatus()),"package: inactive");if(r.formula()!=null){definitions.validateFormula(c.organizationId(),r.formula());gate(!r.formula().items().isEmpty(),"formula.items: at least one material required");}definitions.validateRoute(c.organizationId(),r.route(),true);var target=db.current(c.organizationId(),p.getId());db.current().lock(c.organizationId(),target.getId());if(r.formula()!=null)definitions.saveFormula(c,target,r.formula());definitions.saveRoute(c,target,r.route());definitions.lint(c.organizationId(),target);target.setStatus("EFFECTIVE");db.current().update(target,0,c.actorId(),List.of("status"));db.packages().update(p,0,c.actorId(),List.of());events.publishEvent(new ProcessEvents.Maintained(c.organizationId(),p.getId()));return p;},e->packageView((PackageEntity)e,null),200);}
 @Deprecated public JsonNode createVersion(String id,VersionCreate r,String header,String key){throw new UnsupportedOperationException("Process revision management was retired");}
 @Deprecated public JsonNode formula(String id){throw new UnsupportedOperationException("Use the current process package definition");}
 @Deprecated public JsonNode route(String id){throw new UnsupportedOperationException("Use the current process package definition");}
 @Deprecated public JsonNode saveFormula(String id,FormulaSave r,String header,String key){throw new UnsupportedOperationException("Process revision management was retired");}
 @Deprecated public JsonNode saveRoute(String id,RouteSave r,String header,String key){throw new UnsupportedOperationException("Process revision management was retired");}
 @Deprecated public JsonNode lint(String id,Transition r,String header,String key){throw new UnsupportedOperationException("Process revision management was retired");}
 @Deprecated public JsonNode transition(String id,String action,Transition r,String header,String key){throw new UnsupportedOperationException("Process revision management was retired");}
 public JsonNode currentSnapshot(long org,long packageId,boolean usable){var root=db.current(org,packageId);if(usable){gate("EFFECTIVE".equals(root.getStatus()),"current process definition incomplete");definitions.lint(org,root);}return definitions.signable(org,root).canonicalRecord().deepCopy();}
 public JsonNode snapshot(long org,long versionId,boolean usable){var v=db.versions().get(org,versionId);if(usable){gate(Set.of("APPROVED","EFFECTIVE").contains(v.getStatus()),"process version not approved");definitions.usableRoot(org,v);requireValidSignature(v);}return definitions.signable(org,v).canonicalRecord().deepCopy();}
 private void requireValidSignature(VersionEntity v){String digest=canonicalizer.digest(definitions.signable(v.getOrgId(),v));gate(digest.equals(v.getContentHash()),"process content hash changed");if(!"DIRECT".equals(v.getActivationMode()))gate(signatures.findValid(v.getOrgId(),"ProcessVersion",v.getId().toString()).stream().anyMatch(s->s.meaning()==SignatureMeaning.APPROVE&&s.recordDigest().equals(digest)),"process approval signature not valid");}
 private JsonNode packageView(PackageEntity p,Long ignored){var n=view(p);if(p.getProductId()!=null)n.put("productName",db.products().get(p.getOrgId(),p.getProductId()).getProductName());else n.put("productName","通用生产工艺");var root=db.current(p.getOrgId(),p.getId());var current=json.createObjectNode();current.put("id",root.getId().toString());current.put("status",root.getStatus());current.set("formula",definitions.formulaView(p.getOrgId(),root));current.set("route",definitions.routeView(p.getOrgId(),root));for(String field:List.of("formula","route"))if(current.path(field).isObject())((ObjectNode)current.path(field)).remove("versionNo");n.set("currentDefinition",current);return n;}
 private ObjectNode versionView(VersionEntity v,boolean content){var n=view(v);n.set("formula",content?definitions.formulaView(v.getOrgId(),v):json.nullNode());n.set("route",content?definitions.routeView(v.getOrgId(),v):json.nullNode());n.putNull("approval");if(v.getContentHash()!=null)signatures.findValid(v.getOrgId(),"ProcessVersion",v.getId().toString()).stream().filter(s->s.meaning()==SignatureMeaning.APPROVE&&s.recordDigest().equals(v.getContentHash())).max(Comparator.comparing(SignatureRecord::signedAt)).ifPresent(s->{var a=n.putObject("approval");a.put("signerId",Long.toString(s.signerId()));a.put("signedAt",s.signedAt().toString());a.put("signatureId",Long.toString(s.id()));a.put("recordDigest",s.recordDigest());});return n;}
 private ObjectNode view(ScopedEntity e){var n=(ObjectNode)mutations.view(e);for(String key:List.of("productId","packageId","packageVersionId"))if(n.hasNonNull(key))n.put(key,n.get(key).asText());return n;}
 private void expected(ScopedEntity row,long version){if(row.getVersionNo()!=version)throw new ResourceConflictException("VERSION_CONFLICT","Reload before saving");}
}
