<script setup lang="ts">
import {ref,watch,computed} from 'vue'
import axios from 'axios'
import {api,errorMessage,idempotencyKey,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import type {MasterRecord} from '../../master/resources'
interface Unit {id:string;unitName:string;unitCode:string}
interface Conversion extends MasterRecord {fromUnitId:string;toUnitId:string;factor:string}
const props=defineProps<{materialId:string;baseUnitId:string;writable:boolean}>(),auth=useAuthStore(),items=ref<Conversion[]>([]),units=ref<Unit[]>([]),editing=ref<Conversion|null>(null),open=ref(false),from=ref(''),to=ref(''),factor=ref(''),reason=ref(''),error=ref(''),busy=ref(false),conflict=ref(false),page=ref(0),total=ref(0)
const canWrite=computed(()=>props.writable&&auth.can(`master:uom:${editing.value?'update':'create'}`))
let pendingKey=idempotencyKey(),pendingBody=''
function unitName(id:string){return units.value.find(x=>x.id===id)?.unitName??id}
async function load(p=0){if(!auth.can('master:uom:view'))return;error.value='';try{const [rows,u]=await Promise.all([api<Page<Conversion>>({url:'/unit-conversions',params:{materialId:props.materialId,page:p,size:20}}),api<Page<Unit>>({url:'/units',params:{size:100}})]);items.value=rows.items;page.value=rows.page;total.value=rows.total;units.value=u.items;for(const id of new Set([props.baseUnitId,...rows.items.flatMap(r=>[r.fromUnitId,r.toUnitId])]))if(!units.value.some(u=>u.id===id))units.value.push(await api<Unit>({url:`/units/${id}`}))}catch(e){error.value=errorMessage(e)}}
async function search(keyword=''){try{const p=await api<Page<Unit>>({url:'/units',params:{keyword,size:100}});const selected=units.value.filter(u=>[from.value,to.value].includes(u.id));units.value=[...p.items,...selected.filter(u=>!p.items.some(n=>n.id===u.id))]}catch(e){error.value=errorMessage(e)}}
function start(row:Conversion|null=null){editing.value=row;from.value=row?.fromUnitId??props.baseUnitId;to.value=row?.toUnitId??'';factor.value=row?.factor??'';reason.value='';conflict.value=false;open.value=true}
async function save(){busy.value=true;error.value='';try{if(!from.value||!to.value||!factor.value)throw new Error('请填写单位和换算因子');const data={fromUnitId:from.value,toUnitId:to.value,factor:factor.value,materialId:props.materialId,...(editing.value?{action:'UPDATE',reason:'基础资料维护（系统记录）'}:{})};const encoded=JSON.stringify(data);if(encoded!==pendingBody){pendingKey=idempotencyKey();pendingBody=encoded}await api({url:`/unit-conversions${editing.value?`/${editing.value.id}`:''}`,method:editing.value?'PUT':'POST',data,headers:{'Idempotency-Key':pendingKey}});pendingBody='';open.value=false;await load(page.value)}catch(e){error.value=e instanceof Error&&!axios.isAxiosError(e)?e.message:errorMessage(e);conflict.value=axios.isAxiosError(e)&&e.response?.status===409}finally{busy.value=false}}
watch(()=>props.materialId,()=>load(),{immediate:true})
</script>
<template><a-card title="物料单位换算" class="form-section"><template v-if="auth.can('master:uom:view')"><a-alert v-if="error" type="error" :message="error"/><a-alert v-if="conflict" type="warning" message="换算已被修改，请重新载入该行后编辑。"/>
<div class="table-scroll"><table><thead><tr><th>原单位</th><th>目标单位</th><th>换算因子</th><th v-if="writable">操作</th></tr></thead><tbody><tr v-for="row in items" :key="row.id"><td>{{unitName(row.fromUnitId)}}</td><td>{{unitName(row.toUnitId)}}</td><td>{{row.factor}}</td><td v-if="writable"><a-button v-if="auth.can('master:uom:update')" @click="start(row)">编辑换算</a-button></td></tr></tbody></table></div><a-empty v-if="!items.length" description="暂无物料专属换算"/><a-pagination v-if="total>20" :current="page+1" :total="total" :page-size="20" :show-size-changer="false" @change="(p:number)=>load(p-1)"/>
<a-button v-if="writable&&auth.can('master:uom:create')" @click="start()">添加单位换算</a-button><form v-if="open&&canWrite" class="master-form" @submit.prevent="save"><label><span class="form-field-label">原单位</span><a-select v-model:value="from" aria-label="换算原单位" show-search :filter-option="false" @search="search"><a-select-option v-for="u in units" :key="u.id" :value="u.id">{{u.unitName}}（{{u.unitCode}}）</a-select-option></a-select></label><label><span class="form-field-label">目标单位</span><a-select v-model:value="to" aria-label="换算目标单位" show-search :filter-option="false" @search="search"><a-select-option v-for="u in units" :key="u.id" :value="u.id">{{u.unitName}}（{{u.unitCode}}）</a-select-option></a-select></label><label><span class="form-field-label">换算因子</span><input v-model="factor" class="master-native-input" required inputmode="decimal"/></label><a-space><a-button type="primary" html-type="submit" :disabled="conflict" :loading="busy">保存换算</a-button><a-button @click="open=false">取消</a-button><a-button v-if="conflict" @click="open=false;load(page)">重新加载换算</a-button></a-space></form></template><p v-else class="muted">需要单位查看权限才能查看换算。</p></a-card></template>
