<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import axios from 'axios'
import {api,errorMessage,idempotencyKey,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {supplierPayload,type SupplierLink} from '../../master/material'
interface Supplier {id:string;supplierCode:string;supplierName:string;qualificationStatus:string;validTo:string|null}
const props=defineProps<{materialId:string;writable:boolean}>(),emit=defineEmits<{updated:[]}>(),auth=useAuthStore(),items=ref<SupplierLink[]>([]),options=ref<Supplier[]>([]),choice=ref<string>(),version=ref(0),reason=ref(''),error=ref(''),busy=ref(false),conflict=ref(false)
const selectedPreferred=computed(()=>items.value.find(x=>x.preferred)?.supplierId??'')
let pendingKey=idempotencyKey(),pendingBody=''
async function search(keyword=''){if(!auth.can('master:supplier:view'))return;try{const p=await api<Page<Supplier>>({url:'/suppliers',params:{keyword,qualificationStatus:'APPROVED',size:100}});options.value=p.items.filter(x=>!items.value.some(r=>r.supplierId===x.id))}catch(e){error.value=errorMessage(e)}}
async function load(){error.value='';conflict.value=false;try{const result=await api<{versionNo:number;suppliers:SupplierLink[]}>({url:`/materials/${props.materialId}/suppliers`});items.value=result.suppliers.map(r=>({...r}));version.value=result.versionNo;await search()}catch(e){error.value=errorMessage(e)}}
function prefer(id:string){for(const item of items.value)item.preferred=item.supplierId===id}
function add(){const supplier=options.value.find(x=>x.id===choice.value);if(!supplier)return;items.value.push({supplierId:supplier.id,supplierCode:supplier.supplierCode,supplierName:supplier.supplierName,approved:true,preferred:!items.value.some(x=>x.approved),validTo:null});choice.value=undefined;void search()}
function deactivate(item:SupplierLink){item.approved=false;item.preferred=false}
async function save(){busy.value=true;error.value='';try{if(!reason.value.trim())throw new Error('请填写关系变更原因');const data={versionNo:version.value,reason:reason.value.trim(),suppliers:supplierPayload(items.value)};const encoded=JSON.stringify(data);if(encoded!==pendingBody){pendingKey=idempotencyKey();pendingBody=encoded}await api({url:`/materials/${props.materialId}/suppliers`,method:'PUT',data,headers:{'Idempotency-Key':pendingKey,'If-Match':`"${version.value}"`}});pendingBody='';reason.value='';emit('updated');await load()}catch(e){error.value=e instanceof Error&&!axios.isAxiosError(e)?e.message:errorMessage(e);conflict.value=axios.isAxiosError(e)&&e.response?.status===409}finally{busy.value=false}}
watch(()=>props.materialId,load,{immediate:true})
</script>
<template><a-card title="供应商与首选供应商" class="form-section"><a-alert v-if="error" type="error" :message="error"/><a-alert v-if="conflict" type="warning" message="关系已变更，请重新加载。"><template #action><a-button @click="load">重新加载关系</a-button></template></a-alert>
<form @submit.prevent="save"><div class="table-scroll"><table><thead><tr><th>供应商</th><th>关系有效</th><th>首选供应商</th><th>关系有效截止日期（UTC）</th><th v-if="writable">操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.supplierId"><td>{{item.supplierName??item.supplierId}} <small>{{item.supplierCode}}</small></td><td><input v-if="writable" v-model="item.approved" type="checkbox" :aria-label="`关系有效 ${item.supplierName??item.supplierId}`" @change="!item.approved&&(item.preferred=false)"/><span v-else>{{item.approved?'有效':'已撤销'}}</span></td><td><input type="radio" name="preferred-supplier" :checked="selectedPreferred===item.supplierId" :disabled="!writable||!item.approved" :aria-label="`首选供应商 ${item.supplierName??item.supplierId}`" @change="prefer(item.supplierId)"/></td><td><input v-if="writable" v-model="item.validTo" type="date" class="master-native-input" :aria-label="`关系截止日期 ${item.supplierName??item.supplierId}`"/><span v-else>{{item.validTo??'—'}}</span></td><td v-if="writable"><a-button :disabled="!item.approved" @click="deactivate(item)">撤销关系</a-button></td></tr></tbody></table></div><a-empty v-if="!items.length" description="暂无供应商关系"/>
<template v-if="writable"><a-space class="supplier-picker" wrap><a-select v-model:value="choice" aria-label="选择供应商" show-search :filter-option="false" placeholder="按编码或名称查找合格供应商" style="width:280px;max-width:100%" :disabled="!auth.can('master:supplier:view')" @search="search"><a-select-option v-for="s in options" :key="s.id" :value="s.id">{{s.supplierName}}（{{s.supplierCode}}）</a-select-option></a-select><a-button :disabled="!choice" @click="add">添加供应商</a-button></a-space><label class="form-inline-row"><span class="form-field-label">关系变更原因 <span class="required-mark">*</span></span><textarea v-model="reason" class="master-native-input" required maxlength="1000"/></label><a-button type="primary" html-type="submit" :loading="busy" :disabled="conflict">保存供应商关系</a-button><p>可关联多个供应商，有效关系中只能指定一个首选；撤销保留历史记录。</p></template></form></a-card></template>
