<script setup lang="ts">
import {computed,ref,reactive,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import axios from 'axios'
import {api,errorMessage,idempotencyKey,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {statusLabel,type MasterRecord} from '../../master/resources'
import {materialFields,initialMaterialForm,materialPayload} from '../../master/material'
import MaterialSuppliers from './MaterialSuppliers.vue'
import MaterialConversions from './MaterialConversions.vue'
interface Unit {id:string;unitCode:string;unitName:string}
const route=useRoute(),router=useRouter(),auth=useAuthStore(),record=ref<MasterRecord|null>(null),form=reactive(initialMaterialForm()),units=ref<Unit[]>([]),error=ref(''),busy=ref(false),conflict=ref(false),reason=ref('')
const activeTab=ref('basic'),qualityKeys=['gradePurity','appearance','requiresIncomingInspection']
const visibleFields=computed(()=>readonly.value?materialFields.filter(f=>activeTab.value==='quality'?qualityKeys.includes(f.key):!qualityKeys.includes(f.key)):materialFields)
const create=computed(()=>route.meta.mode==='create'),readonly=computed(()=>route.meta.mode==='view')
let pendingKey=idempotencyKey(),pendingBody=''
async function searchUnits(keyword=''){if(!auth.can('master:uom:view'))return;try{const result=await api<Page<Unit>>({url:'/units',params:{keyword,size:100}});const selected=units.value.filter(u=>[form.baseUnitId,form.packUnitId].includes(u.id));units.value=[...result.items,...selected.filter(u=>!result.items.some(n=>n.id===u.id))]}catch(e){error.value=errorMessage(e)}}
async function load(){error.value='';conflict.value=false;record.value=null;Object.assign(form,initialMaterialForm());reason.value='';try{if(!create.value){record.value=await api<MasterRecord>({url:`/materials/${route.params.id}`});for(const f of materialFields){const value=record.value[f.key];form[f.key]=f.kind==='datetime'&&typeof value==='string'?value.replace(/Z$/,''):value??null}units.value=[{id:String(record.value.baseUnitId),unitCode:String(record.value.baseUnitCode??''),unitName:String(record.value.baseUnitName??'')},...(record.value.packUnitId?[{id:String(record.value.packUnitId),unitCode:'',unitName:String(record.value.packUnitName??'')}]:[])]}await searchUnits()}catch(e){error.value=errorMessage(e)}}
async function save(disable=false){busy.value=true;error.value='';try{if(!create.value&&!reason.value.trim())throw new Error('请填写变更原因');const r=record.value;const body=disable?{versionNo:r?.versionNo,reason:reason.value.trim()}:{...materialPayload(form,!create.value),...(!create.value?{versionNo:r?.versionNo,reason:reason.value.trim()}:{})};const url=create.value?'/materials':`/materials/${r?.id}${disable?'/disable':''}`,method=create.value||disable?'POST':'PUT';const encoded=JSON.stringify({url,body});if(encoded!==pendingBody){pendingKey=idempotencyKey();pendingBody=encoded}const updated=await api<MasterRecord>({url,method,data:body,headers:{'Idempotency-Key':pendingKey,...(r?{'If-Match':`"${r.versionNo}"`}:{})}});record.value=updated;reason.value='';pendingBody='';await router.push({path:`/master/materials/${updated.id}`,query:route.query})}catch(e){error.value=e instanceof Error&&!axios.isAxiosError(e)?e.message:errorMessage(e);conflict.value=axios.isAxiosError(e)&&e.response?.status===409}finally{busy.value=false}}
function edit(){void router.push({path:`/master/materials/${record.value?.id}/edit`,query:route.query})}
watch(()=>route.fullPath,load,{immediate:true})
</script>
<!-- UI Template: T2 for create/edit; existing read-only structure is unchanged. -->
<template><main :data-ui-template="readonly?'T3':'T2'" class="admin-page master-page" :class="{'material-form-page':!readonly}"><header class="admin-page-header"><div><a-button type="link" @click="router.push({path:'/master/materials',query:route.query})">← 返回物料列表</a-button><h1>{{create?'新增物料':readonly?'物料基本信息':'维护物料基本信息'}}</h1><p v-if="record">{{record.materialCode}} · {{statusLabel[String(record.status)]}}</p></div><a-button v-if="readonly&&auth.can('master:material:update')" type="primary" @click="edit">维护基本信息</a-button></header>
<a-alert v-if="error" type="error" :message="error" show-icon/><a-alert v-if="conflict" type="warning" message="记录已变化，输入已保留，请重新加载后继续。"><template #action><a-button @click="load">重新加载</a-button></template></a-alert>
<a-tabs v-if="readonly" v-model:active-key="activeTab"><a-tab-pane key="basic" tab="基本信息"/><a-tab-pane key="quality" tab="质量控制"/><a-tab-pane key="suppliers" tab="供应商"/><a-tab-pane key="usage" tab="使用范围"/></a-tabs><a-card v-if="!readonly||activeTab==='basic'||activeTab==='quality'" :title="activeTab==='quality'&&readonly?'质量控制':'基本信息'" class="form-section"><form class="master-form" @submit.prevent="save()"><label v-for="f in visibleFields" :key="f.key"><span class="form-field-label">{{f.label}}<span v-if="f.required" class="required-mark"> *</span></span>
<span v-if="readonly" class="master-read-value">{{f.key==='baseUnitId'?record?.baseUnitName:f.key==='packUnitId'?(record?.packUnitName??'—'):form[f.key]===null?'—':typeof form[f.key]==='boolean'?(form[f.key]?'是':'否'):form[f.key]}}</span>
<input v-else-if="f.kind==='boolean'" v-model="form[f.key]" type="checkbox"/>
<a-select v-else-if="f.kind==='unit'" :value="typeof form[f.key]==='string'?String(form[f.key]):undefined" :aria-label="f.label" show-search :filter-option="false" :allow-clear="!f.required" :disabled="!auth.can('master:uom:view')" placeholder="选择单位" @search="searchUnits" @change="(v:unknown)=>form[f.key]=v==null?null:String(v)"><a-select-option v-for="u in units" :key="u.id" :value="u.id">{{u.unitName}} {{u.unitCode?`（${u.unitCode}）`:''}}</a-select-option></a-select>
<textarea v-else-if="f.key==='remark'" :value="String(form[f.key]??'')" class="master-native-input" :maxlength="f.max??undefined" @input="form[f.key]=($event.target as HTMLTextAreaElement).value"/>
<input v-else v-model="form[f.key]" class="master-native-input" :type="f.kind==='datetime'?'datetime-local':'text'" :required="f.required" :maxlength="f.max??undefined" :disabled="!create&&f.key==='materialCode'"/>
</label><label v-if="!create&&!readonly" class="form-full-row"><span class="form-field-label">变更原因 <span class="required-mark">*</span></span><textarea v-model="reason" class="master-native-input" required maxlength="1000"/></label><a-space v-if="!readonly"><a-button type="primary" html-type="submit" :loading="busy" :disabled="conflict">保存基本信息</a-button><a-button @click="router.push('/master/materials')">取消</a-button></a-space></form></a-card>
<template v-if="record"><MaterialConversions v-if="!readonly||activeTab==='basic'" :material-id="record.id" :base-unit-id="String(record.baseUnitId)" :writable="!readonly"/><MaterialSuppliers v-if="!readonly||activeTab==='suppliers'" :material-id="record.id" :writable="!readonly&&record.status!=='INACTIVE'&&auth.can('master:material:update')" @updated="load"/>
<a-card v-if="readonly&&activeTab==='usage'" title="使用范围" class="form-section"><a-empty description="当前记录未提供使用范围信息"/></a-card><a-card title="审计与停用" class="form-section"><a-button v-if="auth.can('audit:view')" @click="router.push({path:'/audit',query:{objectId:record.id,objectType:'Material'}})">查看审计记录</a-button><template v-if="readonly&&record.status==='ACTIVE'&&auth.can('master:material:disable')"><label class="form-inline-row"><span class="form-field-label">停用原因</span><textarea v-model="reason" class="master-native-input" maxlength="1000"/></label><a-button danger :disabled="busy||conflict" @click="save(true)">停用物料</a-button></template></a-card></template>
<p v-if="create" class="muted">保存基本信息后可维护单位换算、多个供应商和首选供应商。</p></main></template>
