import {test,expect} from '@playwright/test'
import {resolve} from 'node:path'
import {mkdirSync} from 'node:fs'
const output=resolve('../../docs/acceptance/batch-reference-2026-10-06');mkdirSync(output,{recursive:true})
test('PC Production Batch T4 reference keeps factual progress and source navigation',async({page,isMobile})=>{
 test.skip(isMobile,'本轮按PC参考图实施')
 await page.setViewportSize({width:1280,height:853})
 const errors:string[]=[],requests:string[]=[]
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())})
 let privileged=true
 const batch={id:'100',batchNo:'PB-20261005-001',productId:'9',productionOrderId:'10',plannedQty:'10000',unitId:'12',plannedDate:'2026-10-05',status:'IN_PROGRESS',createdAt:'2026-10-01T14:22:00Z',startedAt:'2026-10-05T08:30:00Z',completedAt:null,versionNo:4,allowedActions:['COMPLETE_PRODUCTION'],processSnapshot:{id:'130',snapshot:{process:{route:{operations:[{operationDefId:'12',operationName:'称量'},{operationDefId:'13',operationName:'投料'}]}}}},subBatches:[]}
 const units=[{id:'101',executionNo:'EU-001',status:'COMPLETED'},{id:'102',executionNo:'EU-002',status:'COMPLETED'},{id:'103',executionNo:'EU-003',status:'IN_PROGRESS'}]
 await page.route('**/api/v1/**',r=>{
  const path=new URL(r.request().url()).pathname.replace('/api/v1','');requests.push(path)
  const send=(data:unknown)=>r.fulfill({json:{code:'OK',data,message:'success',traceId:'batch-reference'}})
  if(path==='/auth/me')return send({userId:'5',organizationId:'1',displayName:'生产管理员',permissionCodes:['production:batch:view','production:order:view','master:product:view','master:uom:view','mes:execution:view','mes:operation:view',...(privileged?['wms:reservation:view','qa:batch-review','ebr:form:view','balance:view','production:batch:complete','qms:plan:view','qms:deviation:view','trace:view','audit:view']:[])],mustChangePassword:false})
  if(path==='/main-batches/100')return send(batch)
  if(path==='/main-batches/100/execution-units')return send(units)
  if(path==='/main-batches/100/reservations')return send([{id:'501',materialLotId:'30',reservedQty:'10.000',unitId:'11',status:'ACTIVE'}])
  if(path==='/products/9')return send({id:'9',productCode:'PRD-001',productName:'复方软膏',dosageForm:'软膏剂',specification:'50 g/支'})
  if(path==='/production-orders/10')return send({id:'10',orderNo:'WO-20261005-001',status:'OPEN',createdAt:'2026-10-01T00:00:00Z'})
  if(path==='/units/12')return send({id:'12',unitName:'支'})
  if(/^\/execution-units\/10[123]\/operations$/.test(path)){const completed=!path.includes('103');return send([{id:path+'-1',operationDefId:'12',operationSeq:1,status:completed?'COMPLETED':'IN_PROGRESS',startedAt:'2026-10-05T08:30:00Z'},{id:path+'-2',operationDefId:'13',operationSeq:2,status:completed?'COMPLETED':'PENDING'}])}
  if(path==='/qa/batches/100/review-model')return send({mainBatchId:'100',batchNo:batch.batchNo,status:'IN_PROGRESS',gates:[{code:'PRODUCTION_QC',passed:false,blockingCodes:['PRODUCTION_QC_REQUIRED_RESULT'],evidenceIds:[]}],allowedActions:[]})
  if(path==='/main-batches/100/material-balance')return send({results:[{id:'701',balanceRuleId:'7',calculationVersion:1,status:'FAIL',differencePct:'2'},{id:'702',balanceRuleId:'7',calculationVersion:2,status:'PASS',differencePct:'0'}]})
  if(path==='/main-batches/100/ebr')return send({forms:[],pdfManifests:[],decisions:[],deviations:[],balances:[],signatures:[]})
  if(path==='/quality/production-plans')return send({items:[],total:0,page:0,size:20})
  if(path==='/main-batches/100/quantity-events')return send({items:[],total:0,page:0,size:100})
  return send([])
 })
 await page.goto('/production/batches/100')
 await expect(page.getByRole('heading',{name:'生产批 360° 视图',exact:true})).toBeVisible()
 await expect(page.locator('.summary-product')).toContainText('复方软膏')
 await expect(page.locator('.overall-progress')).toContainText('4 / 6 工序已完成')
 await expect(page.locator('.module-grid')).toContainText('2 / 3')
 await expect(page.locator('.module-grid')).toContainText('1 / 1')
 await expect(page.locator('.batch-lifecycle li')).toHaveCount(6)
 await expect(page.locator('.batch-lifecycle li').first()).toContainText('未完成')
 await expect(page.locator('.batch-lifecycle li').last()).toContainText('未放行')
 await expect(page.locator('.batch-files')).toContainText('暂无可读取的归档文件')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await expect(page.getByRole('tab',{name:'相关批次',exact:true})).toBeVisible()
 await page.screenshot({path:resolve(output,'batch-pc-1280x853.png')})
 await page.screenshot({path:resolve(output,'batch-pc-full.png'),fullPage:true})
 await page.getByRole('tab',{name:'生产执行',exact:true}).click()
 await expect(page.getByRole('table').first()).toContainText('EU-003')
 await page.getByRole('tab',{name:'质量控制',exact:true}).click()
 await expect(page.getByText('尚未建立生产质量计划。',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'更多受控操作',exact:true}).click()
 await page.getByRole('button',{name:'完成生产',exact:true}).click()
 await expect(page.getByLabel('操作原因',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:/^取\s*消$/}).click()
 privileged=false;requests.length=0;await page.reload()
 await expect(page.getByRole('heading',{name:'生产批 360° 视图',exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'QA审核',exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'批记录',exact:true})).toHaveCount(0)
 expect(requests.some(p=>p.includes('review-model')||p.includes('material-balance')||p.endsWith('/ebr'))).toBe(false)
 expect(errors).toEqual([])
})
