import {test,expect,type Page} from '@playwright/test'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
const envelope=(data:unknown)=>({code:'OK',message:'success',data,traceId:'ebr-runtime-ui'})
async function setup(page:Page,submitted=false){
 const field={fieldCode:'A',groupCode:null,label:'实际重量',fieldType:'NUMBER',sourceType:'MANUAL',dataType:'DECIMAL',unitId:'7',precisionScale:3,requiredFlag:true,readonlyFlag:false,defaultExpr:null,placeholder:null,helpText:null,sequenceNo:1,validationJson:null,options:[]}
 const device={...field,fieldCode:'DEVICE',label:'仪器结果',fieldType:'INSTRUMENT_VALUE',sourceType:'INSTRUMENT',readonlyFlag:true,sequenceNo:2}
 const revision={id:'90',formInstanceId:'30',fieldDefId:'40',fieldCode:'A',occurrencePath:'',revisionNo:1,previousRevisionId:null,rawValueJson:'"2.000"',normalizedValueJson:'"2.000"',unitId:'7',sourceType:'MANUAL',sourceRef:null,recordedBy:'5',recordedAt:'2026-10-03T00:00:00Z',changeReason:'原始记录',superseded:false}
 const model={id:'30',operationExecutionId:'20',formDefId:'40',formCode:'F',formName:'现场重量记录',occurrenceNo:1,status:submitted?'SUBMITTED':'DRAFT',formRevision:1,versionNo:2,submittedBy:submitted?'5':null,submittedAt:submitted?'2026-10-03T00:00:00Z':null,definitionHash:'a'.repeat(64),definition:{formCode:'F',formName:'现场重量记录',operationDefId:'10',schemaVersion:'1.0',sequenceNo:1,fields:[field,device]},fields:[{fieldCode:'A',occurrencePath:'',label:'实际重量',type:'NUMBER',value:'2.000',displayValue:'2.000',unitId:'7',required:true,readonly:submitted,visible:true,validationState:'VALID',source:'MANUAL',provenance:['90'],allowedActions:submitted?['CORRECT']:['EDIT','CORRECT']},{fieldCode:'DEVICE',occurrencePath:'',label:'仪器结果',type:'INSTRUMENT_VALUE',value:'2.001',displayValue:'2.001',unitId:'7',required:true,readonly:true,visible:true,validationState:'VALID',source:'INSTRUMENT',provenance:['91'],allowedActions:['CORRECT']}],currentValues:[revision],valueRevisions:[revision],ruleExecutions:[],reviewRequirements:[{reviewRuleId:'60',objectScope:'FORM',objectCode:'F',reviewType:'VERIFY',requiredRole:'QA',independentUserRequired:true,sequenceNo:1}],signatureRequirements:[],reviews:[] as unknown[],signatureIds:[] as string[],allowedActions:submitted?['REVIEW','CORRECT']:['SAVE','SUBMIT','CORRECT']}
 const writes:Array<{path:string;body:Record<string,unknown>;headers:Record<string,string>}>=[]
 await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname,method=route.request().method(),send=(data:unknown)=>route.fulfill({json:envelope(data)})
  if(path.endsWith('/auth/me'))return send({userId:'6',organizationId:'1',loginName:'runtime',displayName:'现场复核人',roleCodes:['QA'],permissionCodes:['ebr:form:view','ebr:form:edit','ebr:form:submit','ebr:record:correct','ebr:review:verify','ebr:sign','mes:execution:view'],mustChangePassword:false})
  if(method==='GET'&&path.endsWith('/forms/30/render-model'))return send(model)
  const body=route.request().postDataJSON() as Record<string,unknown>;writes.push({path,body,headers:route.request().headers()})
  if(path.endsWith('/auth/reauth'))return send({reauthToken:'bound-token'})
  if(path.endsWith('/draft-values'))return route.fulfill({status:409,json:{code:'REVISION_CONFLICT',message:'内容修订已变化'}})
  if(path.endsWith('/submit'))return route.fulfill({status:422,json:{code:'EBR_RULE_BLOCKED',message:'范围校验阻断，证据已保留'}})
  if(path.endsWith('/reviews')){model.status='VERIFIED';model.reviews=[{id:'100',formRevision:1,reviewRuleId:'60',reviewType:'VERIFY',reviewerId:'6',decision:'PASS',comment:body.comment,reason:body.reason,reviewedAt:'2026-10-03T00:10:00Z',signatureId:'110',invalidatedAt:null,invalidationReason:null}];return send(model)}
  if(path.endsWith('/corrections')){model.status='DRAFT';model.formRevision=2;model.valueRevisions=[{...revision,superseded:true},{...revision,id:'92',revisionNo:2,previousRevisionId:'90' as unknown as null,normalizedValueJson:JSON.stringify(body.newValue),changeReason:String(body.reason)}];model.reviews=model.reviews.map(r=>({...r as object,invalidatedAt:'2026-10-03T00:20:00Z',invalidationReason:String(body.reason)}));return send(model)}
  return send([])
 })
 return writes
}
test('runtime fields remain inline and 409 preserves exact input',async({page},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const writes=await setup(page);await page.goto('/mes/execution/1/forms/30');await expect(page.getByRole('heading',{name:'现场重量记录'})).toBeVisible();await expect(page.getByLabel('实际重量',{exact:false})).toBeVisible();await expect(page.getByText('2.001',{exact:true})).toBeVisible();for(const row of await page.locator('.runtime-field:visible').all()){expect(await row.evaluate(el=>{const label=el.children[0]!.getBoundingClientRect(),input=el.children[1]!.getBoundingClientRect();return label.right<=input.left+2&&Math.abs(label.top-input.top)<14})).toBe(true)}await page.getByLabel('实际重量',{exact:false}).fill('123456789012345678.123');await page.getByLabel('操作原因',{exact:true}).fill('实际测量');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByText('内容修订已变化',{exact:true})).toBeVisible();await expect(page.getByLabel('实际重量',{exact:false})).toHaveValue('123456789012345678.123');expect(writes.find(w=>w.path.endsWith('/draft-values'))?.body.values).toEqual([{fieldCode:'A',occurrencePath:'',value:'123456789012345678.123',unitId:'7',sourceRef:null}]);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:join(tmpdir(),`ebr-runtime-${info.project.name}.png`),fullPage:true});expect(errors).toEqual([])})
test('blocked submission preserves operator reason and displayed content',async({page})=>{await setup(page);await page.goto('/mes/execution/1/forms/30');await page.getByLabel('操作原因',{exact:true}).fill('提交原始观测');await page.getByRole('button',{name:'提交记录',exact:true}).click();await expect(page.getByText('范围校验阻断，证据已保留',{exact:true})).toBeVisible();await expect(page.getByLabel('操作原因',{exact:true})).toHaveValue('提交原始观测');await expect(page.getByLabel('实际重量',{exact:false})).toHaveValue('2.000')})
test('review reauthentication binds frozen rule identity and correction retains history',async({page})=>{const writes=await setup(page,true);await page.goto('/mes/execution/1/forms/30');await page.getByRole('button',{name:'核对 · QA · F',exact:true}).click();await page.getByLabel('签名原因',{exact:true}).fill('独立核对原始记录');await page.getByLabel('再认证密码',{exact:true}).fill('test-password');await page.getByRole('button',{name:'确认电子签名',exact:true}).click();await page.getByText('更多记录与审计证据',{exact:true}).click();await expect(page.getByText('VERIFY · PASS · 修订 1',{exact:true})).toBeVisible();expect(writes.find(w=>w.path.endsWith('/auth/reauth'))?.body).toMatchObject({objectType:'EBR_REVIEW_RECORD',objectId:'30:1:60',meaning:'VERIFY',recordVersion:1});expect(writes.find(w=>w.path.endsWith('/reviews'))?.headers['if-match']).toBe('"1"');await page.getByRole('button',{name:'受控更正',exact:true}).first().click();await page.getByText('更正后值',{exact:true}).locator('..').locator('input').fill('2.500');await page.getByLabel('更正原因',{exact:true}).fill('原始读数转录更正');await page.getByRole('button',{name:'保存受控更正',exact:true}).click();await expect(page.getByText('已被后续修订替代',{exact:true})).toBeVisible();await expect(page.getByText('已失效：原始读数转录更正',{exact:true})).toBeVisible();expect(writes.find(w=>w.path.endsWith('/corrections'))?.body).toEqual({formRevision:1,reason:'原始读数转录更正',newValue:'2.500'})})
