import {test,expect,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {join} from 'node:path'
import {createHash} from 'node:crypto'
const dir=process.env.MES_EBR_EVIDENCE_DIR!;mkdirSync(dir,{recursive:true})
const book=JSON.parse(readFileSync(join(dir,'rollback-real-book.json'),'utf8'))
const pdf=readFileSync(join(dir,'rollback-real-book.pdf'))
const record={id:'synthetic-archive',pdf_hash:createHash('sha256').update(pdf).digest('hex'),archive_kind:'REVIEW_COPY',created_at:'synthetic rollback fixture'}
async function setup(page:Page,allowed=true){const calls={content:0,generate:0,body:null as unknown};await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname;const send=(data:unknown)=>route.fulfill({json:{code:'OK',message:'success',data,traceId:'rollback-db-capture-ui'}})
if(path.endsWith('/auth/me'))return send({userId:'5',organizationId:'1',loginName:'synthetic',displayName:'合成验收人员',roleCodes:['QA'],permissionCodes:allowed?['ebr:form:view','ebr:pdf:generate','production:batch:view','master:product:view','master:uom:view','ebr:template:view','ebr:template:create','ebr:template:publish','process:package:view','ebr:form:edit','ebr:review:verify','ebr:review:approve','mes:execution:view','mes:operation:view']:[],mustChangePassword:false})
if(path.endsWith('/book/pdfs/synthetic-archive/content')){calls.content++;return route.fulfill({contentType:'application/pdf',body:pdf})}
if(path.endsWith('/book/pdfs')){if(route.request().method()==='POST'){calls.generate++;calls.body=route.request().postDataJSON();return send(record)}return send([record])}
if(/\/forms\/[^/]+\/render-model$/.test(path))return send(JSON.parse(readFileSync(join(dir,'rollback-real-form.json'),'utf8')));if(path.endsWith('/book'))return send(book)
if(path.endsWith('/ebr/book-templates'))return send([{id:'2',templateCode:'SYNTHETIC-BOOK',revision:1,status:'PUBLISHED',versionNo:2,createdBy:'8',definition:book.book.definition}])
return send({items:[],total:0,page:0,size:100})
});return calls}
test('captured real rollback book renders source directory and same PDF download',async({page},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const calls=await setup(page);await page.goto(`/production/batches/${book.mainBatchId}/book`);await expect(page.getByRole('heading',{name:'生产批记录册',exact:true})).toBeVisible();await expect(page.locator('.directory-item')).toHaveCount(book.entries.length);for(const e of book.entries){await page.locator('.directory-item').filter({hasText:e.definition.title}).click();await expect(page.locator('.book-record>header h2')).toHaveText(e.definition.title);await expect(page.locator('.paper-record')).toHaveCount(e.documents.length)}await page.locator('body').press('Control+Home');const shellHeader=await page.locator('.header').boundingBox();expect(shellHeader?.y).toBe(0);await page.screenshot({path:join(dir,`book-directory-${info.project.name}.png`),fullPage:false});await page.getByRole('button',{name:'预览 / 重打',exact:true}).click();await expect(page.getByTitle('PDF 文档预览')).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载 PDF',exact:true}).click();await(await download).saveAs(join(dir,`book-download-${info.project.name}.pdf`));expect(createHash('sha256').update(readFileSync(join(dir,`book-download-${info.project.name}.pdf`))).digest('hex')).toBe(record.pdf_hash);expect(calls.content).toBe(1);expect(errors).toEqual([]);await page.screenshot({path:join(dir,`book-pdf-${info.project.name}.png`),fullPage:false})})
test('template version and source mapping drawer render',async({page},info)=>{await setup(page);await page.goto('/ebr/book-templates');await expect(page.getByRole('heading',{name:'生产批记录册模板',exact:true})).toBeVisible();await page.getByRole('button',{name:'查看 / 新版本',exact:true}).click();await expect(page.locator('.mapping-row')).toHaveCount(book.book.definition.mappings.length);await page.screenshot({path:join(dir,`book-template-${info.project.name}.png`),fullPage:false})})
test('unauthorized user cannot enter book routes',async({page})=>{await setup(page,false);await page.goto(`/production/batches/${book.mainBatchId}/book`);await expect(page).toHaveURL(/\/$/);await page.goto('/ebr/book-templates');await expect(page).toHaveURL(/\/$/)})
test('book links actual captured form to existing entry and review page without a second record',async({page},info)=>{await setup(page);await page.goto(`/production/batches/${book.mainBatchId}/book`);const entry=book.entries.find((e:any)=>e.definition.kind==='FORM'&&e.documents.some((d:any)=>d.formId));await page.locator('.directory-item').filter({hasText:entry.definition.title}).click();await page.getByRole('button',{name:'填写 / 复核',exact:true}).first().click();const form=JSON.parse(readFileSync(join(dir,'rollback-real-form.json'),'utf8'));await expect(page).toHaveURL(new RegExp('/forms/'+entry.documents[0].formId+'$'));await expect(page.getByRole('heading',{name:form.formName,exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/保存草稿|暂存/})).toBeVisible();await page.screenshot({path:join(dir,`book-original-form-${info.project.name}.png`),fullPage:false})})
