import {test,expect,type Page} from '@playwright/test'
// Browser plugin/skill not available: repository Playwright. API fixtures prove UI only.
const envelope=(data:unknown)=>({code:'OK',message:'success',data,traceId:'functional-ui-fixture'})
async function sameRow(page:Page){const label=page.getByLabel('操作原因',{exact:true});const box=await label.boundingBox();const tag=await label.locator('..').locator('.form-field-label').boundingBox();expect(box).not.toBeNull();expect(tag).not.toBeNull();expect(tag!.x+tag!.width).toBeLessThanOrEqual(box!.x+2);expect(Math.max(tag!.y,box!.y)).toBeLessThan(Math.min(tag!.y+tag!.height,box!.y+box!.height))}
test('signed inventory restriction uses existing lot page and horizontal fields',async({page},info)=>{
 let frozen=false;const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 const lot=()=>({id:'30',lotNo:'LOT-CLOSURE',versionNo:frozen?1:0,materialId:'20',qualityStatus:'RELEASED',inventoryStatus:frozen?'FROZEN':'AVAILABLE',materialSnapshot:{materialName:'原料A'},inventoryDecisions:frozen?[{id:'90',action:'FREEZE',reason:'调查期间暂停使用',signatureId:'100'}]:[],allowedActions:frozen?['UNFREEZE']:['FREEZE']})
 await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/api/v1','');const send=(data:unknown)=>route.fulfill({json:envelope(data)});if(path==='/auth/me')return send({userId:'6',organizationId:'1',loginName:'qa',displayName:'质量人员',roleCodes:[],permissionCodes:['wms:inventory:view','qa:material-inventory:freeze','qa:material-inventory:unfreeze','ebr:sign'],mustChangePassword:false});if(path==='/wms/material-lots/30')return send(lot());if(path==='/inventory')return send({items:[],page:0,size:20,total:0});if(path==='/auth/reauth'){expect(route.request().postDataJSON()).toMatchObject({objectType:'INVENTORY_DECISION',objectId:'30:0',recordVersion:0,meaning:'APPROVE'});return send({reauthToken:'ui-token'})}if(path==='/material-lots/30/freeze'){expect(route.request().postDataJSON()).toEqual({versionNo:0,reason:'调查期间暂停使用',signature:{reauthToken:'ui-token'}});expect(route.request().headers()['if-match']).toBe('"0"');frozen=true;return send(lot())}return send([])})
 await page.goto('/wms/material-lots/30');await expect(page.getByRole('heading',{name:'物料批次 360° 视图'})).toBeVisible();await page.getByRole('tab',{name:'库存流转',exact:true}).click();await page.getByRole('button',{name:'冻结库存',exact:true}).click();await page.getByLabel('操作原因',{exact:true}).fill('调查期间暂停使用');await page.getByLabel('签名密码',{exact:true}).fill('ui-only-password');await sameRow(page);await page.screenshot({path:info.outputPath('inventory-controls.png')});await page.getByRole('button',{name:'签名并提交',exact:true}).click();await expect(page.getByRole('button',{name:'解除冻结',exact:true})).toBeVisible();expect(errors).toEqual([])
})
test('execution workbench records frozen IPC with exact signature binding',async({page},info)=>{
 test.skip(info.project.name==='chromium-mobile','Approved T5 PC-only contract: design-qa.md, 2026-10-05; no mobile implementation.')
 let submitted=false;const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 const operation=()=>({id:'102',versionNo:1,status:'IN_PROGRESS',operationName:'混合',operationDefId:'110',clearanceRequired:false,equipmentUsages:[],parameterValues:[],clearanceRecords:[],allowedActions:['PAUSE','COMPLETE'],ipcInstances:[{id:'200',versionNo:submitted?1:0,operationExecutionId:'102',ipcCode:'PH',status:submitted?'TESTING':'PENDING',definitionSnapshot:{resultType:'NUMERIC',lowerLimit:'1',upperLimit:'3',methodReference:'SOP-IPC/V1'},results:submitted?[{id:'201',resultNumeric:'2',resultConclusion:'PASS'}]:[],allowedActions:submitted?['REVIEW_RESULT']:['SUBMIT_RESULT']}]})
 await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/api/v1','');const send=(data:unknown)=>route.fulfill({json:envelope(data)});if(path==='/auth/me')return send({userId:'6',organizationId:'1',loginName:'qc',displayName:'检验人员',roleCodes:[],permissionCodes:['mes:execution:view','mes:operation:view','qms:ipc:view','qms:ipc:record','qms:ipc:review','ebr:sign'],mustChangePassword:false});if(path==='/execution-units/101')return send({id:'101',executionNo:'EXEC-CLOSURE',status:'IN_PROGRESS'});if(path==='/execution-units/101/operations')return send([operation()]);if(path==='/auth/reauth'){expect(route.request().postDataJSON()).toMatchObject({objectType:'IPC_RESULT',objectId:'200:0',recordVersion:0,meaning:'VERIFY'});return send({reauthToken:'ipc-ui-token'})}if(path==='/ipc/200/submit-result'){expect(route.request().postDataJSON()).toEqual({versionNo:0,reason:'记录原始实测值',previousRevisionId:null,resultNumeric:'2',signature:{reauthToken:'ipc-ui-token'}});submitted=true;return send(operation().ipcInstances[0])}return send([])})
 await page.goto('/mes/execution/101');await expect(page.getByRole('heading',{name:'生产执行工作台'})).toBeVisible();await page.getByRole('tab',{name:'IPC',exact:true}).click();await page.getByRole('button',{name:'记录 IPC 结果',exact:true}).click();await page.getByLabel('IPC 原始数值结果',{exact:true}).fill('2');await page.getByLabel('操作原因',{exact:true}).fill('记录原始实测值');await page.getByLabel('签名密码',{exact:true}).fill('ui-only-password');await sameRow(page);await page.screenshot({path:info.outputPath('ipc-controls.png')});await page.getByRole('button',{name:'签名并提交',exact:true}).click();await expect(page.getByRole('button',{name:'独立复核 IPC',exact:true})).toBeVisible();expect(errors).toEqual([])
})
