import {test,expect,type Page} from '@playwright/test'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
const envelope=(data:unknown)=>({code:'OK',message:'success',data,traceId:'incoming-ui-contract'})
async function setup(page:Page){
 let uploads=0,links=0,version=0
 const permissions=['qms:inspection-request:view','qms:inspection-request:create','qms:inspection-request:submit','qms:inspection-request:accept','qms:specification:view','qms:report:view','qms:report:create','qa:material-release:view','qa:material-release:decide','ebr:sign','wms:inventory:view','wms:receipt:view','wms:receipt:update','attachment:upload','attachment:view','production:order:view','production:order:create','master:product:view','master:uom:view']
 const request={id:'30',requestNo:'IQ-30',materialLotId:'60',qcSpecificationVersionId:'21',requestType:'INITIAL',status:'DRAFT',versionNo:0,items:[{id:'31'}]}
 await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname,method=route.request().method(),send=(data:unknown)=>route.fulfill({json:envelope(data)}),list=(items:unknown[])=>({items,total:items.length,page:0,size:20})
  if(path.endsWith('/auth/me'))return send({userId:'5',organizationId:'1',loginName:'quality',displayName:'质量人员',roleCodes:['QA'],permissionCodes:permissions,mustChangePassword:false})
  if(path.endsWith('/auth/reauth'))return send({reauthToken:'bound-token'})
  if(path.endsWith('/wms/material-lots'))return send(list([{id:'60',lotNo:'LOT-60',materialId:'11',qualityStatus:'QUARANTINE',inventoryStatus:'BLOCKED'}]))
  if(path.endsWith('/wms/material-lots/60'))return send({id:'60',lotNo:'LOT-60',materialId:'11',versionNo:0,qualityStatus:'QUARANTINE',inventoryStatus:'BLOCKED'})
  if(path.endsWith('/quality/specifications'))return send(list([{id:'20',materialId:'11',specificationCode:'QC-20',specificationName:'来料标准',versions:[{id:'21',status:'APPROVED',versionNoBusiness:1}]}]))
  if(path.endsWith('/quality/specifications/20'))return send({id:'20',materialId:'11',versions:[{id:'21',status:'APPROVED',versionNoBusiness:1}]})
  if(path.endsWith('/quality/specification-versions/21'))return send({id:'21',status:'APPROVED',items:[]})
  if(path.endsWith('/units'))return send(list([{id:'10',unitCode:'KG',unitName:'千克'}]))
  if(path.endsWith('/quality/inspection-requests')){if(method==='POST'){expect(route.request().postDataJSON()).toMatchObject({materialLotId:'60',qcSpecificationVersionId:'21',requestedQuantity:'5',reason:'正式请验'});return send(request)}return send(list([request]))}
  if(path.endsWith('/quality/inspection-requests/30/submit')){request.status='SUBMITTED';request.versionNo++;return send(request)}
  if(path.endsWith('/quality/inspection-requests/30'))return send(request)
  if(path.endsWith('/qa/material-lots/60/release-review'))return send({materialLotId:'60',versionNo:5,allowedActions:['release-decisions'],qualityStatus:'PENDING_QA_RELEASE',inventoryStatus:'BLOCKED',eligibleForRelease:false,gateReasons:[{code:'OOS_OPEN',message:'OOS尚未处理',evidenceIds:['40']}],reports:[{id:'50',reportNo:'RPT-50',status:'APPROVED',overallResult:'PASS'}],investigations:[],decisions:[],signingTargets:[{action:'MATERIAL_RELEASE_DECISION',objectType:'MATERIAL_RELEASE_DECISION',recordId:'60:5',recordVersion:5,meaning:'RELEASE'}]})
  if(path.endsWith('/qa/material-lots/60/release-decisions'))return route.fulfill({status:422,json:{code:'OOS_OPEN',message:'OOS尚未处理，禁止放行'}})
  if(path.endsWith('/wms/receipts/70'))return send({id:'70',receiptNo:'REC-70',supplierId:'7',warehouseId:'8',transportCheckPassed:true,recordStatus:'APPROVED',versionNo:version,items:[],allowedActions:[]})
  if(path.endsWith('/attachments')&&!path.includes('/receipts/')){uploads++;return send({id:'90',fileName:'coa.txt',mediaType:'text/plain',byteLength:3,sha256:'a'.repeat(64),uploadedBy:'5',uploadedAt:'2026-10-03T00:00:00Z',recordVersion:1,retentionStatus:'RETAINED'})}
  if(path.endsWith('/wms/receipts/70/attachments')){if(method==='GET')return send([]);links++;if(links===1){version=1;return route.fulfill({status:409,json:{code:'VERSION_CONFLICT',message:'记录已变化'}})}return send({id:'91'})}
  if(path.includes('/suppliers')||path.includes('/warehouses'))return send(list([]))
  return send(list([]))
 })
 return ()=>({uploads,links})
}
async function inline(page:Page){const pairs=page.locator('.query-form > label:visible, .master-form > label:visible');expect(await pairs.count()).toBeGreaterThan(0);for(const pair of await pairs.all()){expect(await pair.evaluate(el=>{const a=el.children[0]?.getBoundingClientRect(),b=el.children[1]?.getBoundingClientRect();return !!a&&!!b&&a.right<=b.left+2&&Math.abs(a.top-b.top)<18})).toBe(true)}}
test('request query and create retain formal inline layout',async({page},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await page.goto('/quality/inspection-requests');await expect(page.getByRole('heading',{name:'请验单',exact:true})).toBeVisible();await page.getByLabel('关键字',{exact:true}).fill('IQ');await page.getByRole('button',{name:/^查\s*询$/}).click();await expect(page.getByText('IQ-30',{exact:true})).toBeVisible();await inline(page);await page.getByRole('button',{name:'新增请验单',exact:true}).click();await expect(page.getByLabel('请验数量',{exact:true})).toBeVisible();await inline(page);await expect(page.locator('vite-error-overlay')).toHaveCount(0);await page.screenshot({path:join(tmpdir(),`incoming-request-${info.project.name}.png`),fullPage:true});expect(errors).toEqual([])})
test('report is automatic and QA OOS failure preserves decision input',async({page},info)=>{await setup(page);await page.goto('/quality/inspection-reports/create');await expect(page.getByText('根据请验单的全部必检项目自动汇总已复核结果，并保留原始结果和调查依据。')).toBeVisible();await expect(page.getByLabel('原始数值结果')).toHaveCount(0);await page.goto('/qa/material-lots/60/release');await expect(page.getByText('OOS尚未处理',{exact:true})).toBeVisible();await page.getByRole('button',{name:'QA物料决定',exact:true}).click();await page.getByLabel('质量决定',{exact:true}).selectOption('RELEASED');await page.getByLabel('放行依据',{exact:true}).selectOption('FULL_INSPECTION');await page.getByLabel('检验报告',{exact:true}).selectOption('50');await page.getByLabel('操作原因',{exact:true}).fill('核对放行证据');await page.getByRole('button',{name:'核对并签名',exact:true}).click();await page.getByLabel('签名密码',{exact:true}).fill('test-password');await page.getByRole('button',{name:'签名并提交',exact:true}).click();await expect(page.getByText('OOS尚未处理，禁止放行',{exact:true})).toBeVisible();await expect(page.getByLabel('操作原因',{exact:true})).toHaveValue('核对放行证据');await page.screenshot({path:join(tmpdir(),`incoming-release-${info.project.name}.png`),fullPage:true})})
test('receipt attachment conflict retries saved upload without duplicate bytes',async({page})=>{const counts=await setup(page);await page.goto('/wms/receipts/70');await page.getByLabel('随货文件',{exact:true}).setInputFiles({name:'coa.txt',mimeType:'text/plain',buffer:Buffer.from('COA')});await page.getByLabel('关联原因',{exact:true}).fill('原始供应商COA');await page.getByRole('button',{name:'上传并关联',exact:true}).click();await expect(page.getByText('文件 coa.txt 已上传，待关联。重试将使用该文件。')).toBeVisible();await page.getByRole('button',{name:'重新加载',exact:true}).click();await expect(page.getByLabel('关联原因',{exact:true})).toHaveValue('原始供应商COA');await page.getByRole('button',{name:'重试关联',exact:true}).click();await expect.poll(()=>counts()).toEqual({uploads:1,links:2})})
