import {test,expect} from '@playwright/test'
import fs from 'node:fs'
const dir=process.env.MES_UI_SCREENSHOT_DIR??'../../docs/acceptance/material-field-cleanup-2026-10-06'
const material={id:'901',orgId:'1',versionNo:7,updatedAt:'2026-10-06T00:00:00Z',allowedActions:['UPDATE','DISABLE'],status:'ACTIVE',materialCode:'MAT-CLEAN',materialName:'字段清理验证',materialType:'RAW',specification:'25 kg/桶',gradePurity:'药用',storageCondition:'阴凉干燥',baseUnitId:'11',baseUnitName:'千克',packUnitId:'12',packUnitName:'桶',packSpec:'25 kg',requiresIncomingInspection:true,remark:'保留备注',manufacturerName:'隐藏厂家原值',appearance:'隐藏外观原值',lotControlled:false,effectiveFrom:'2026-01-01T00:00:00Z',effectiveTo:'2028-01-01T00:00:00Z'}
test('material T1/T2/T3 cleanup preserves hidden write fields and existing supplier facts',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});let body:any;const queries:URL[]=[]
 await page.route('**/api/v1/**',r=>{const url=new URL(r.request().url()),path=url.pathname;const reply=(data:unknown)=>r.fulfill({json:{code:'OK',data,message:'success',traceId:'material-cleanup'}})
 if(path.endsWith('/auth/me'))return reply({userId:'7',organizationId:'1',displayName:'验证人员',loginName:'test',roleCodes:[],mustChangePassword:false,permissionCodes:['master:material:view','master:material:create','master:material:update','master:uom:view','master:supplier:view']})
 if(path.endsWith('/materials/901/suppliers'))return reply({versionNo:7,suppliers:[{supplierId:'51',supplierCode:'SUP-51',supplierName:'原料供应商',qualificationStatus:'APPROVED',manufacturerName:'来源厂家甲',approved:true,preferred:true,validTo:'2028-01-01'}]})
 if(path.endsWith('/materials/901')){if(r.request().method()==='PUT'){body=r.request().postDataJSON();return reply({...material,...body,versionNo:8})}return reply(material)}
 if(path.endsWith('/materials')){queries.push(url);return reply({items:[material],total:21,page:Number(url.searchParams.get('page')??0),size:20})}
 if(path.endsWith('/units'))return reply({items:[{id:'11',unitCode:'kg',unitName:'千克'},{id:'12',unitCode:'桶',unitName:'桶'}],total:2,page:0,size:100})
 return reply({items:[],total:0,page:0,size:20})})
 fs.mkdirSync(dir,{recursive:true})
 await page.goto('/master/materials');await expect(page.locator('.ant-table-thead')).toContainText('存储环境');const headers=await page.locator('.ant-table-thead th').allTextContents();expect(headers).toEqual(['物料编码','物料名称','物料类型','规格','基本单位','存储环境','状态','操作']);await page.getByRole('button',{name:/查\s*询/}).click();expect(queries.at(-1)?.searchParams.get('sort')).toBe('id,desc');await page.screenshot({path:dir+'/material-list.png',fullPage:true})
 await page.goto('/master/materials/901');await expect(page.getByRole('heading',{name:'物料基本信息'})).toBeVisible();await expect(page.locator('.master-form')).toContainText('药用');await expect(page.locator('.master-form')).toContainText('是否入库必验');for(const name of ['生产厂家','生效时间','失效时间','批号管理','外观','隐藏厂家原值','隐藏外观原值','更新时间','记录版本'])await expect(page.locator('main.master-page').getByText(name,{exact:true})).toHaveCount(0);await expect(page.locator('.material-object-summary')).toContainText(material.materialName);await expect(page.locator('.material-basic-card .required-mark')).toHaveCount(0);await page.screenshot({path:dir+'/material-detail.png',fullPage:true});await page.screenshot({path:dir+'/material-detail-desktop.png',fullPage:false})
 await page.getByRole('tab',{name:'供应商',exact:true}).click();await expect(page.locator('main.master-page')).toContainText('原料供应商');await expect(page.locator('main.master-page')).toContainText('合格');await expect(page.locator('main.master-page')).toContainText('来源厂家甲');await page.screenshot({path:dir+'/material-suppliers.png',fullPage:true})
 await page.goto('/master/materials/901/edit');await expect(page.getByLabel('物料名称')).toHaveValue(material.materialName);await page.getByLabel('物料名称').fill('维护后名称');await expect(page.getByLabel('存储环境')).toHaveValue('阴凉干燥');await page.locator('.master-form').getByLabel('变更原因').fill('仅维护名称');await expect(page.locator('.material-form-actions')).toBeInViewport();await page.evaluate(()=>window.scrollTo(0,0));await expect(page.locator('.material-form-actions')).toBeInViewport();await page.screenshot({path:dir+'/material-edit.png',fullPage:true});await page.screenshot({path:dir+'/material-edit-desktop.png',fullPage:false});await page.getByRole('button',{name:'保存基本信息',exact:true}).click();await expect(page).toHaveURL(/materials\/901(?:\?|$)/);expect(body).toMatchObject({versionNo:7,manufacturerName:material.manufacturerName,appearance:material.appearance,lotControlled:false,effectiveFrom:new Date(material.effectiveFrom).toISOString(),effectiveTo:new Date(material.effectiveTo).toISOString(),reason:'仅维护名称'});expect(body.storageCondition).toBe('阴凉干燥')
 await page.goto('/master/materials/create');await expect(page.getByRole('heading',{name:'新增物料'})).toBeVisible();const labels=await page.locator('.master-form .form-field-label').allTextContents();expect(labels.map(x=>x.replace(/ \*/g,'').trim())).toEqual(['物料编码','物料名称','物料类型','规格','等级 / 纯度','基本单位','包装单位','包装规格','是否入库必验','存储环境','备注']);const groups=page.locator('.material-field-section');await expect(groups).toHaveCount(4);const boxes=await groups.evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return {x:r.x,y:r.y}}));expect(boxes[0].x).toBe(boxes[1].x);expect(boxes[2].x).toBe(boxes[3].x);expect(boxes[2].x).toBeGreaterThan(boxes[0].x);expect(boxes[1].y).toBeGreaterThan(boxes[0].y);await expect(page.locator('.material-form-actions')).toBeInViewport();await page.screenshot({path:dir+'/material-create.png',fullPage:true});await page.screenshot({path:dir+'/material-create-desktop.png',fullPage:false});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([])
})

test('receipt and lot present frozen source manufacturer rather than material master',async({page})=>{
 const source={relationshipId:'61',materialId:'901',supplierId:'51',supplierCode:'SUP-51',supplierName:'冻结来源供应商',manufacturerName:'冻结厂家乙'};const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.route('**/api/v1/**',r=>{const path=new URL(r.request().url()).pathname;const reply=(data:unknown)=>r.fulfill({json:{code:'OK',message:'success',data,traceId:'source-ui'}});
 if(path.endsWith('/auth/me'))return reply({userId:'7',organizationId:'1',displayName:'来源验证',permissionCodes:['wms:inventory:view','wms:receipt:view'],mustChangePassword:false});
 if(path.endsWith('/wms/material-lots/201'))return reply({id:'201',receiptItemId:'101',lotNo:'SOURCE-LOT',materialId:'901',materialSnapshot:{...material,manufacturerName:'遗留主数据厂家'},sourceSnapshot:source,qualityStatus:'QUARANTINE',inventoryStatus:'BLOCKED',allowedActions:[]});
 if(path.endsWith('/attachments'))return reply([]);
 if(path.endsWith('/wms/receipts/401'))return reply({id:'401',versionNo:1,receiptNo:'SOURCE-RECEIPT',supplierId:'51',warehouseId:'10',recordStatus:'APPROVED',transportCheckPassed:true,allowedActions:[],items:[{id:'101',materialId:'901',lotNo:'SOURCE-LOT',supplierLotNo:'SUPLOT',receivedQty:'1',unitId:'11',packageCount:1,packageCheckPassed:true,sealCheckPassed:true,labelCheckPassed:true,damageCheckPassed:true,contaminationCheckPassed:true,sourceSnapshot:source}]});
 return reply({items:[],total:0,page:0,size:20})});
 fs.mkdirSync(dir,{recursive:true});await page.goto('/wms/material-lots/201');await expect(page.locator('.lot-summary')).toContainText('冻结厂家乙');await expect(page.locator('.lot-summary')).toContainText('冻结来源供应商');await expect(page.getByText('遗留主数据厂家',{exact:true})).toHaveCount(0);await page.screenshot({path:dir+'/material-lot-source.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.goto('/wms/receipts/401');await expect(page.locator('.receipt-page')).toContainText('冻结厂家乙');await expect(page.locator('.receipt-page')).toContainText('冻结来源供应商');await page.screenshot({path:dir+'/receipt-source.png',fullPage:true});expect(errors).toEqual([])
})
