import {test,expect,type Page} from '@playwright/test'
// Browser plugin skill not available in this session: repository Playwright; API mocked UI only.
const envelope=(data:unknown)=>({code:'OK',message:'success',data,traceId:'mes012-ui'})
async function horizontal(page:Page){const input=page.getByLabel('操作原因',{exact:true}),a=await input.boundingBox(),b=await input.locator('..').locator('.form-field-label').boundingBox();expect(a&&b).toBeTruthy();expect(b!.x+b!.width).toBeLessThanOrEqual(a!.x+2);expect(Math.max(a!.y,b!.y)).toBeLessThan(Math.min(a!.y+a!.height,b!.y+b!.height))}
test('production plan uses safe quantity fields and exact signed approval',async({page})=>{
 let approved=false;const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname.replace('/api/v1',''),send=(d:unknown)=>route.fulfill({json:envelope(d)});if(p==='/auth/me')return send({userId:'8',organizationId:'1',displayName:'计划审批',permissionCodes:['qms:plan:view','qms:plan:approve','ebr:sign'],mustChangePassword:false});if(p==='/quality/production-plans/51')return send({id:'51',versionNo:approved?1:0,mainBatchId:'41',finishedMaterialId:'21',qcSpecificationVersionId:'31',balanceRules:[],status:approved?'APPROVED':'DRAFT',allowedActions:approved?[]:['APPROVE']});if(p==='/auth/reauth'){expect(route.request().postDataJSON()).toMatchObject({objectType:'PRODUCTION_QUALITY_PLAN',objectId:'51',recordVersion:0,meaning:'APPROVE'});return send({reauthToken:'plan-ui'})}if(p==='/quality/production-plans/51/approve'){expect(route.request().postDataJSON()).toEqual({versionNo:0,reason:'独立审核生产质量计划',signature:{reauthToken:'plan-ui'}});expect(route.request().headers()['if-match']).toBe('"0"');approved=true;return send({id:'51'})}return send({items:[],total:0,page:0,size:20})})
 await page.goto('/quality/production-plans/51');await expect(page.getByRole('heading',{name:'生产质量计划',exact:true})).toBeVisible();await page.getByRole('button',{name:/批\s*准/}).click();await page.getByLabel('操作原因',{exact:true}).fill('独立审核生产质量计划');await horizontal(page);await page.getByRole('button',{name:'核对并签名'}).click();await page.getByLabel('签名密码',{exact:true}).fill('ui-password');await page.getByRole('button',{name:'签名并提交'}).click();await expect(page.getByRole('button',{name:/批\s*准/})).toHaveCount(0);expect(errors).toEqual([])
})
test('balance investigation preserves FAIL and signs investigation version',async({page})=>{
 let approved=false;await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname.replace('/api/v1',''),send=(d:unknown)=>route.fulfill({json:envelope(d)});if(p==='/auth/me')return send({userId:'9',organizationId:'1',displayName:'QA',permissionCodes:['balance:view','balance:approve','ebr:sign'],mustChangePassword:false});if(p==='/main-batches/41')return send({id:'41',versionNo:7,status:'IN_PROGRESS'});if(p==='/main-batches/41/material-balance')return send({mainBatchId:'41',allowedActions:[],blockingCodes:approved?[]:['BALANCE_FAILED'],results:[{id:'61',balanceRuleId:'60',calculationVersion:1,expectedValue:'100',actualValue:'98',differenceValue:'-2',differencePct:'-2',status:'FAIL',investigation:{id:'71',versionNo:2,status:approved?'APPROVED_EXCEPTION':'INVESTIGATING',investigationText:'实际损耗已核对',allowedActions:approved?[]:['APPROVE']}}]});if(p==='/auth/reauth'){expect(route.request().postDataJSON()).toMatchObject({objectType:'BALANCE_INVESTIGATION',objectId:'71',recordVersion:2,meaning:'APPROVE'});return send({reauthToken:'balance-ui'})}if(p==='/balance-investigations/71/approve'){expect(route.request().postDataJSON()).toMatchObject({versionNo:2,decision:'ACCEPT_EXCEPTION',signature:{reauthToken:'balance-ui'}});approved=true;return send({id:'71'})}return send({items:[],total:0})})
 await page.goto('/production/batches/41/balance');await expect(page.getByRole('heading',{name:'物料平衡与偏差'})).toBeVisible();await page.getByRole('button',{name:'60',exact:true}).click();await page.getByRole('button',{name:/批\s*准/}).evaluate(el=>el.scrollIntoView({block:'center'}));await page.getByRole('button',{name:/批\s*准/}).click();await page.getByLabel('操作原因',{exact:true}).fill('独立批准实测损耗例外');await page.getByLabel('质量决定',{exact:true}).selectOption('ACCEPT_EXCEPTION');await horizontal(page);await page.getByRole('button',{name:'核对并签名'}).click();await page.getByLabel('签名密码',{exact:true}).fill('ui-password');await page.getByRole('button',{name:'签名并提交'}).click();await expect(page.getByText('已批准例外',{exact:true}).filter({visible:true})).toHaveCount(1);await expect(page.locator('.ant-tag').filter({hasText:'不合格'})).toHaveCount(1)
})
test('quality scope selector loads actual production sample endpoint',async({page})=>{
 let scoped=false;await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url()),p=url.pathname.replace('/api/v1',''),send=(d:unknown)=>route.fulfill({json:envelope(d)});if(p==='/auth/me')return send({userId:'8',organizationId:'1',displayName:'QC',permissionCodes:['qms:test:view','qms:sample:view'],mustChangePassword:false});if(p==='/samples'){expect(url.searchParams.get('investigationScope')).toBe('PRODUCTION');scoped=true;return send({items:[{id:'90',sampleNo:'PS-90',sampleType:'TEST_SAMPLE',quantity:'1',unitId:'1',status:'COLLECTED'}],total:1,page:0,size:20})}return send({items:[],total:0,page:0,size:20})})
 await page.goto('/quality/samples');await page.getByLabel('质量范围',{exact:true}).selectOption('PRODUCTION');await expect(page.getByText('PS-90',{exact:true})).toBeVisible();expect(scoped).toBe(true)
})
test('plan creation renders structured quantity sources and selectable identities',async({page})=>{
 await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname.replace('/api/v1',''),send=(d:unknown)=>route.fulfill({json:envelope(d)});if(p==='/auth/me')return send({userId:'8',organizationId:'1',displayName:'计划员',permissionCodes:['qms:plan:create','qms:plan:view'],mustChangePassword:false});if(p==='/main-batches')return send({items:[{id:'41',batchNo:'MB-41',status:'DRAFT'}],total:1});if(p==='/materials')return send({items:[{id:'21',materialName:'制剂成品',materialCode:'FIN-21',materialType:'FINISHED'}],total:1});if(p==='/units')return send({items:[{id:'11',unitCode:'kg'}],total:1});if(p==='/quality/specifications')return send({items:[{id:'30',specificationCode:'QC-30'}],total:1});if(p==='/quality/specifications/30')return send({id:'30',versions:[{id:'31',status:'APPROVED',versionNoBusiness:1}]});return send({items:[],total:0})})
 await page.goto('/quality/production-plans/create');await expect(page.getByRole('heading',{name:'新增生产质量计划'})).toBeVisible();await page.getByLabel('生产批',{exact:true}).selectOption('41');await page.getByLabel('成品物料',{exact:true}).selectOption('21');await page.getByLabel('质量标准版本',{exact:true}).selectOption('31');await expect(page.getByText('数量来源',{exact:true})).toHaveCount(2);await expect(page.getByRole('checkbox')).toHaveCount(16);await expect(page.getByLabel('计算规则',{exact:true})).toHaveCount(0);await page.getByLabel('操作原因',{exact:true}).fill('定义生产质量标准与物料平衡');await horizontal(page)
})
test('production result signs current instance version and excludes text on numeric items',async({page})=>{
 let saved=false;await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname.replace('/api/v1',''),send=(d:unknown)=>route.fulfill({json:envelope(d)});if(p==='/auth/me')return send({userId:'8',organizationId:'1',displayName:'QC',permissionCodes:['qms:test:view','qms:test:record','ebr:sign'],mustChangePassword:false});if(p==='/quality/production-tests/81')return send({id:'81',versionNo:saved?4:3,sampleId:'90',status:saved?'COMPLETED':'READY',results:[],specificationSnapshot:{item:{resultType:'NUMERIC',lowerLimit:'1',upperLimit:'3'}},allowedActions:saved?[]:['RECORD_RESULT']});if(p==='/auth/reauth'){expect(route.request().postDataJSON()).toMatchObject({objectType:'PRODUCTION_TEST_RESULT',objectId:'81:3',recordVersion:3,meaning:'VERIFY'});return send({reauthToken:'test-ui'})}if(p==='/quality/production-tests/81/results'){expect(route.request().postDataJSON()).toEqual({versionNo:3,reason:'记录原始生产检验结果',resultNumeric:'2.00000001',signature:{reauthToken:'test-ui'}});saved=true;return send({id:'81'})}return send({items:[],total:0})})
 await page.goto('/quality/production-tests/81');await page.getByRole('button',{name:'记录原始结果'}).click();await expect(page.getByLabel('原始文本结果',{exact:true})).toHaveCount(0);await page.getByLabel('原始数值结果',{exact:true}).fill('2.00000001');await page.getByLabel('操作原因',{exact:true}).fill('记录原始生产检验结果');await horizontal(page);await page.getByRole('button',{name:'核对并签名'}).click();await page.getByLabel('签名密码',{exact:true}).fill('ui-password');await page.getByRole('button',{name:'签名并提交'}).click();await expect(page.getByRole('button',{name:'记录原始结果'})).toHaveCount(0)
})
test('production CAPA verification retains history and signs own version',async({page})=>{
 let verified=false;await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname.replace('/api/v1',''),send=(d:unknown)=>route.fulfill({json:envelope(d)});if(p==='/auth/me')return send({userId:'9',organizationId:'1',displayName:'QA',permissionCodes:['qms:deviation:view','qms:capa:view','qms:capa:verify','ebr:sign'],mustChangePassword:false});if(p==='/deviations/101')return send({id:'101',versionNo:8,investigationScope:'PRODUCTION',mainBatchId:'41',status:'DECIDED',allowedActions:[],capas:[{id:'111',versionNo:verified?5:4,capaNo:'CAPA-111',status:verified?'VERIFIED':'COMPLETED',actionText:'校准取样流程',completionText:'已完成培训',allowedActions:verified?[]:['VERIFY'],reviews:verified?[{id:'121',decision:'VERIFIED',reason:'独立检查整改有效'}]:[]}]});if(p==='/auth/reauth'){expect(route.request().postDataJSON()).toMatchObject({objectType:'PRODUCTION_CAPA',objectId:'111:4',recordVersion:4,meaning:'VERIFY'});return send({reauthToken:'capa-ui'})}if(p==='/capas/111/verify'){expect(route.request().postDataJSON()).toEqual({versionNo:4,reason:'独立检查整改有效',decision:'VERIFIED',signature:{reauthToken:'capa-ui'}});verified=true;return send({id:'111'})}return send({items:[],total:0})})
 await page.goto('/deviations/101?scope=PRODUCTION');await page.getByRole('button',{name:'独立验证',exact:true}).click();await page.getByLabel('质量决定',{exact:true}).selectOption('VERIFIED');await page.getByLabel('操作原因',{exact:true}).fill('独立检查整改有效');await horizontal(page);await page.getByRole('button',{name:'核对并签名'}).click();await page.getByLabel('签名密码',{exact:true}).fill('ui-password');await page.getByRole('button',{name:'签名并提交'}).click();await expect(page.getByRole('button',{name:'独立验证',exact:true})).toHaveCount(0);await expect(page.getByText('独立检查整改有效',{exact:true}).first()).toBeVisible()
})
test('quantity observation and reversal bind latest batch version instead of event version zero',async({page})=>{
 let version=7,recorded=false,reversed=false;await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname.replace('/api/v1',''),send=(d:unknown)=>route.fulfill({json:envelope(d)});if(p==='/auth/me')return send({userId:'8',organizationId:'1',displayName:'生产人员',permissionCodes:['production:batch:view','balance:view','mes:quantity:record','mes:quantity:reverse','ebr:sign'],mustChangePassword:false});if(p==='/main-batches/41')return send({id:'41',versionNo:version,status:'IN_PROGRESS',allowedActions:[]});if(p==='/units')return send({items:[{id:'11',unitCode:'kg'}],total:1});if(p==='/auth/reauth'){expect(route.request().postDataJSON()).toMatchObject({objectType:'PRODUCTION_QUANTITY',objectId:`41:${version}`,recordVersion:version,meaning:'VERIFY'});return send({reauthToken:`quantity-${version}`})}if(p==='/main-batches/41/quantity-events'&&route.request().method()==='POST'){expect(route.request().postDataJSON()).toEqual({versionNo:7,eventType:'LOSS',amount:'0.000001',unitId:'11',sourceRef:'loss-41',reason:'实测损耗',signature:{reauthToken:'quantity-7'}});expect(route.request().headers()['if-match']).toBe('"7"');recorded=true;version=8;return send({id:'131',versionNo:0})}if(p==='/quantity-events/131/reverse'){expect(route.request().postDataJSON()).toEqual({versionNo:8,reason:'冲销错误测量',signature:{reauthToken:'quantity-8'}});expect(route.request().headers()['if-match']).toBe('"8"');reversed=true;version=9;return send({id:'132',versionNo:0})}if(p==='/main-batches/41/quantity-events')return send({items:recorded?[{id:'131',versionNo:0,eventType:'LOSS',sourceType:'PRODUCTION_OBSERVATION',sourceRef:'loss-41',amount:'0.000001',unitId:'11'},...(reversed?[{id:'132',versionNo:0,eventType:'REVERSAL',sourceType:'PRODUCTION_REVERSAL',reversalOfId:'131',amount:'-0.000001'}]:[])]:[],total:reversed?2:recorded?1:0});return send({items:[],total:0})})
 await page.goto('/production/batches/41');await page.getByRole('button',{name:'记录产量与损耗',exact:true}).click();await page.getByLabel('数量类型',{exact:true}).selectOption('LOSS');await page.getByLabel('数量',{exact:true}).fill('0.000001');await page.getByLabel('单位',{exact:true}).selectOption('11');await page.getByLabel('来源标识',{exact:true}).fill('loss-41');await page.getByLabel('操作原因',{exact:true}).fill('实测损耗');await page.getByRole('button',{name:'核对并签名'}).click();await page.getByLabel('签名密码',{exact:true}).fill('ui-password');await page.getByRole('button',{name:'签名并提交'}).click();await page.getByText('损耗 · 0.000001 · loss-41',{exact:true}).click();await page.getByRole('button',{name:'冲销数量记录',exact:true}).click();await page.getByLabel('操作原因',{exact:true}).fill('冲销错误测量');await page.getByRole('button',{name:'核对并签名'}).click();await page.getByLabel('签名密码',{exact:true}).fill('ui-password');await page.getByRole('button',{name:'签名并提交'}).click();await expect(page.getByRole('button',{name:'冲销数量记录',exact:true})).toHaveCount(0);expect(reversed).toBe(true)
})
