import {test,expect} from '@playwright/test'
// Scoped API-mocked UI regression, repository Playwright fallback.
const envelope=(data:unknown)=>({code:'OK',message:'success',data,traceId:'mes012-reference-ui'})
test('multi-item production testing selects frozen item identities after sample enters IN_TEST',async({page})=>{
 let sampleStatus='RECEIVED';const created:string[]=[]
 await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/api/v1',''),send=(data:unknown)=>route.fulfill({json:envelope(data)});if(path==='/auth/me')return send({userId:'8',organizationId:'1',displayName:'QC',permissionCodes:['qms:test:view','qms:test:record','qms:sample:view'],mustChangePassword:false});if(path==='/samples')return send({items:[{id:'90',sampleNo:'PS-90',sampleType:'TEST_SAMPLE',status:sampleStatus}],total:1});if(path==='/samples/90')return send({id:'90',mainBatchId:'41',productionPlanId:'51',qcSpecificationVersionId:'31',status:sampleStatus});if(path==='/quality/specification-versions/31')return send({id:'31',items:[{id:'901',specificationItemId:'101',itemCode:'PH',itemName:'酸碱度'},{id:'902',specificationItemId:'102',itemCode:'CONTENT',itemName:'含量'}]});if(path==='/quality/production-tests'&&route.request().method()==='POST'){const body=route.request().postDataJSON();expect(body).toEqual({sampleId:'90',specificationItemId:created.length?'102':'101',reason:'建立冻结标准项目检验'});expect(body).not.toHaveProperty('qcSpecificationItemId');created.push(body.specificationItemId);sampleStatus='IN_TEST';return send({id:created.length===1?'81':'82'})}if(path==='/quality/production-tests/81'||path==='/quality/production-tests/82')return send({id:path.endsWith('81')?'81':'82',sampleId:'90',versionNo:0,status:'READY',allowedActions:[]});return send({items:[],total:0})})
 for(const item of ['101','102']){await page.goto('/quality/production-tests/create');await expect(page.getByLabel('样品',{exact:true}).locator('option[value="90"]')).toHaveCount(1);await page.getByLabel('样品',{exact:true}).selectOption('90');const picker=page.getByLabel('质量标准项目',{exact:true});await expect(picker).toHaveJSProperty('tagName','SELECT');await picker.selectOption(item);await page.getByLabel('操作原因',{exact:true}).fill('建立冻结标准项目检验');await page.getByRole('button',{name:/提\s*交/}).click();await expect(page).toHaveURL(new RegExp(`/quality/production-tests/${item==='101'?'81':'82'}$`))}
 expect(created).toEqual(['101','102']);expect(sampleStatus).toBe('IN_TEST')
})
test('approved production retest picker selects exact old test and batch investigation with actual request key',async({page})=>{
 let retested=false
 await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url()),path=url.pathname.replace('/api/v1',''),send=(data:unknown)=>route.fulfill({json:envelope(data)});if(path==='/auth/me')return send({userId:'8',organizationId:'1',displayName:'QC',permissionCodes:['qms:test:view','qms:test:retest','qms:deviation:view','qms:sample:view'],mustChangePassword:false});if(path==='/quality/production-tests/81')return send({id:'81',sampleId:'90',versionNo:retested?4:3,status:'COMPLETED',allowedActions:retested?[]:['RETEST']});if(path==='/samples/90')return send({id:'90',mainBatchId:'41',qcSpecificationVersionId:'31'});if(path==='/deviations'){expect(url.searchParams.get('mainBatchId')).toBe('41');expect(url.searchParams.get('investigationScope')).toBe('PRODUCTION');const good={status:'DECIDED',decisionCode:'AUTHORIZE_RETEST',productionTestInstanceId:'81',mainBatchId:'41'};return send({items:[{...good,id:'111',deviationNo:'RETEST-81'},{...good,id:'112',productionTestInstanceId:'82'},{...good,id:'113',mainBatchId:'42'},{...good,id:'114',status:'INVESTIGATING'},{...good,id:'115',decisionCode:'REJECT'}],total:5})}if(path==='/quality/production-tests/81/retest'){expect(route.request().postDataJSON()).toEqual({versionNo:3,reason:'按原始无效结果调查复检',investigationId:'111'});expect(route.request().postDataJSON()).not.toHaveProperty('approvedInvestigationId');expect(route.request().headers()['if-match']).toBe('"3"');retested=true;return send({id:'82'})}return send({items:[],total:0})})
 await page.goto('/quality/production-tests/81');await page.getByRole('button',{name:'批准复检',exact:true}).click();const picker=page.getByLabel('批准复检调查',{exact:true});await expect(picker).toHaveJSProperty('tagName','SELECT');await expect(picker.locator('option')).toHaveCount(2);await picker.selectOption('111');await page.getByLabel('操作原因',{exact:true}).fill('按原始无效结果调查复检');await page.getByRole('button',{name:/提\s*交/}).click();await expect(page.getByRole('button',{name:'批准复检',exact:true})).toHaveCount(0);expect(retested).toBe(true)
})
