import {test,expect,type Page} from '@playwright/test'
const env=(data:unknown)=>({code:'OK',message:'success',data,traceId:'wms-browser-mock'})
async function setup(page:Page,conflict=false,emptyStock=false){
 let receipt:any={id:'50',receiptNo:'REC-1',supplierId:'7',warehouseId:'8',transportCheckPassed:true,recordStatus:'DRAFT',versionNo:0,allowedActions:['UPDATE','CONFIRM'],items:[],confirmedAt:null};
 const permissions=['audit:view','wms:receipt:view','wms:receipt:create','wms:receipt:update','wms:receipt:confirm','wms:inventory:view','wms:inventory:move','wms:inventory:adjust','wms:issue:view','wms:issue:create','wms:issue:update','master:supplier:view','master:material:view','master:uom:view']
 const lookups:any={suppliers:[{id:'7',supplierCode:'SUP-1',supplierName:'合格供应商'}],warehouses:[{id:'8',warehouseCode:'W-1',warehouseName:'原料库'}],locations:[{id:'9',locationCode:'LOC-1',locationName:'待验区'},{id:'12',locationCode:'LOC-2',locationName:'存储区'}],containers:[],units:[{id:'10',unitCode:'BAG',unitName:'袋'}],materials:[{id:'11',materialCode:'MAT-1',materialName:'原料甲'}]}
 await page.route('**/api/v1/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname,send=(d:unknown)=>route.fulfill({json:env(d)}),list=(items:unknown[])=>({items,total:items.length,page:0,size:20}),segments=path.split('/'),resource=segments[3]!
 if(path.endsWith('/auth/me'))return send({userId:'5',organizationId:'1',loginName:'warehouse',displayName:'仓储员',roleCodes:[],permissionCodes:permissions,mustChangePassword:false})
 if(lookups[resource])return send(segments.length===4?list(lookups[resource]):lookups[resource].find((r:any)=>r.id===segments[4]))
 if(path.endsWith('/wms/receipts')){if(req.method()==='GET')return send(list([receipt]));const body=req.postDataJSON();expect(body).not.toHaveProperty('purchaseReference');expect(body.items[0]).toHaveProperty('receivedQty');expect(req.headers()['idempotency-key']).toBeTruthy();receipt={...receipt,...body,items:body.items.map((i:any,n:number)=>({...i,id:String(51+n)}))};return send(receipt)}
 if(path.endsWith('/wms/receipts/50')){if(req.method()==='PUT'){expect(req.headers()['if-match']).toBe('"0"');if(conflict)return route.fulfill({status:409,json:{code:'VERSION_CONFLICT',message:'记录版本变化'}});receipt={...receipt,...req.postDataJSON(),versionNo:1}}return send(receipt)}
 if(path.endsWith('/wms/receipts/50/confirm')){expect(req.postDataJSON().reason).toBeTruthy();receipt={...receipt,recordStatus:'APPROVED',versionNo:receipt.versionNo+1,allowedActions:[],confirmedBy:'5',confirmedAt:'2026-10-03T00:00:00Z',items:receipt.items.map((i:any)=>({...i,materialLotId:'60',requiresIncomingInspectionSnapshot:true}))};return send(receipt)}
 if(path.endsWith('/wms/material-lots/60'))return send({id:'60',lotNo:'LOT-1',materialId:'11',receiptItemId:'51',versionNo:0,qualityStatus:'QUARANTINE',inventoryStatus:'BLOCKED',requiresIncomingInspectionSnapshot:true,materialSnapshot:{materialName:'原料甲'},allowedActions:['MOVE','ADJUST']})
 if(path.endsWith('/inventory'))return send(list(emptyStock?[]:[{materialLotId:'60',lotNo:'LOT-1',locationId:'9',unitId:'10',quantity:'5',versionNo:0}]))
 if(path.endsWith('/inventory/move')){expect(req.postDataJSON()).toMatchObject({materialLotId:'60',fromLocationId:'9',toLocationId:'12',quantity:'1',unitId:'10',versionNo:0,reason:'移至存储区'});expect(req.headers()['if-match']).toBe('"0"');return send({id:'60'})}
 if(path.endsWith('/inventory/adjust')){expect(req.postDataJSON()).toMatchObject({materialLotId:'60',locationId:'9',deltaQty:'2',unitId:'10',reason:'盘盈'});return send({id:'60'})}
 if(path.endsWith('/material-issues'))return send(list([]))
 return route.fulfill({status:404,json:{code:'NOT_FOUND',message:path}})
 })
}
async function select(page:Page,label:string,text:string){await page.locator(`.ant-select[aria-label="${label}"]`).click();await page.locator('.ant-select-dropdown:visible .ant-select-item-option').filter({hasText:text}).click()}
test('multi-line receipt confirm lot inventory and implemented issue route',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await page.goto('/wms/receipts/create?keyword=REC-Test&page=2')
 await page.getByLabel('收货单号',{exact:true}).fill('REC-1');await select(page,'供应商','合格供应商');await select(page,'仓库','原料库');await page.getByLabel('运输检查通过',{exact:true}).check();await page.getByRole('button',{name:'添加收货明细',exact:true}).click()
 for(let i=1;i<=2;i++){await select(page,`物料 ${i}`,'原料甲');await page.getByLabel(`物料批号 ${i}`,{exact:true}).fill(`LOT-${i}`);await page.getByLabel(`供应商批号 ${i}`,{exact:true}).fill(`SUPLOT-${i}`);await page.getByLabel(`收货数量 ${i}`,{exact:true}).fill('5');await select(page,`收货单位 ${i}`,'袋');await select(page,`库位 ${i}`,'待验区');for(const name of ['包装','封签','标签','破损','污染'])await page.getByLabel(`${name}检查通过 ${i}`,{exact:true}).check()}
 const pair=page.locator('.master-form>label').first();expect(await pair.evaluate(el=>{const a=el.children[0]!.getBoundingClientRect(),b=el.children[1]!.getBoundingClientRect();return a.right<=b.left+1&&Math.abs(a.top-b.top)<12})).toBe(true)
 await page.keyboard.press('Escape');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:info.outputPath('receipt-create.png'),fullPage:true});await page.getByRole('button',{name:'保存收货单',exact:true}).click();await expect(page.getByRole('heading',{name:'收货单详情',exact:true})).toBeVisible();await page.getByLabel('操作原因',{exact:true}).fill('逐项核实收货');await page.getByRole('button',{name:'确认收货',exact:true}).click();await expect(page.getByRole('button',{name:'编辑收货单',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'查看物料批 LOT-1',exact:true}).click();await expect(page.getByText('禁止生产使用',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'库存流转',exact:true}).click();await page.getByRole('button',{name:'移库',exact:true}).click();await select(page,'目标库位','存储区');await page.getByLabel('库存数量',{exact:true}).fill('1');await page.getByLabel('操作原因',{exact:true}).fill('移至存储区');await page.getByRole('button',{name:'提交移库',exact:true}).click();await expect(page.getByText('移库已记录',{exact:true})).toBeVisible();await page.keyboard.press('Escape');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:info.outputPath('lot-inventory.png'),fullPage:true});await page.goto('/wms/issues/create');await expect(page.getByRole('heading',{name:'新增出库单',exact:true})).toBeVisible();await expect(page.getByText(/DEPENDENCY_NOT_READY|依赖未就绪/)).toHaveCount(0);await expect(page.getByLabel('生产批',{exact:true})).toBeVisible();await expect(page.getByLabel('出库单号',{exact:true})).toBeVisible();expect(errors).toEqual([])
})
test('receipt stale save keeps user input and return query',async({page})=>{await setup(page,true);await page.goto('/wms/receipts/50/edit?keyword=REC-Test&page=2');await page.getByLabel('收货单号',{exact:true}).fill('UNSAVED');await page.getByLabel('操作原因',{exact:true}).fill('修改单号');await page.getByRole('button',{name:'保存收货单',exact:true}).click();await expect(page.getByText('记录已变化，输入已保留，请重新加载后继续。')).toBeVisible();await expect(page.getByLabel('收货单号',{exact:true})).toHaveValue('UNSAVED');page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'← 返回收货列表',exact:true}).click();await expect(page.getByLabel('单号查询')).toHaveValue('REC-Test');expect(new URL(page.url()).searchParams.get('page')).toBe('2')})

test('empty stock retains controlled positive adjustment entry',async({page})=>{await setup(page,false,true);await page.goto('/wms/material-lots/60');await page.getByRole('tab',{name:'库存流转',exact:true}).click();await expect(page.getByText('暂无库存记录',{exact:true})).toBeVisible();await page.getByRole('button',{name:'新增库存调整',exact:true}).click();await select(page,'来源库位','待验区');await select(page,'库存单位','袋');await page.getByLabel('库存数量',{exact:true}).fill('2');await page.getByLabel('操作原因',{exact:true}).fill('盘盈');await page.getByRole('button',{name:'提交调整',exact:true}).click();await expect(page.getByText('库存调整已记录',{exact:true})).toBeVisible()})
