import {expect,test,type Page} from '@playwright/test'
const env=(data:unknown)=>({code:'OK',message:'success',data,traceId:'basic-browser'})
async function setup(page:Page){
 const units=[{id:'1',unitCode:'kg',unitName:'千克'},{id:'2',unitCode:'g',unitName:'克'}]
 const suppliers=[{id:'41',supplierCode:'SUP-A',supplierName:'供应商甲',qualificationStatus:'APPROVED'},{id:'42',supplierCode:'SUP-B',supplierName:'供应商乙',qualificationStatus:'APPROVED'}]
 let m:any={id:'21',materialCode:'MAT-001',materialName:'复方甘油涂剂',materialType:'FINISHED',baseUnitId:'1',baseUnitName:'千克',baseUnitCode:'kg',lotControlled:true,requiresIncomingInspection:true,status:'ACTIVE',versionNo:0,allowedActions:['UPDATE','DISABLE']},links:any[]=[],conversions:any[]=[]
 await page.route('**/api/v1/**',async r=>{const req=r.request(),p=new URL(req.url()).pathname,method=req.method(),send=(data:unknown,status=200)=>r.fulfill({status,json:env(data)}),list=(items:unknown[])=>({items,total:items.length,page:0,size:20})
 if(p==='/api/v1/auth/me')return send({userId:'7',organizationId:'1',displayName:'管理员',loginName:'tester',roleCodes:['SYSTEM_ADMIN'],mustChangePassword:false,permissionCodes:['master:material:view','master:material:create','master:material:update','master:material:disable','master:supplier:view','master:uom:view','master:uom:create','master:uom:update','audit:view']})
 if(p==='/api/v1/units')return send(list(units));if(p==='/api/v1/suppliers')return send(list(suppliers))
 if(p==='/api/v1/materials'){if(method==='GET')return send(list([m]));const b=req.postDataJSON();expect(b.baseUnitId).toBe('1');for(const k of ['data','versionId','quality','genericName','englishName','aliasName'])expect(b).not.toHaveProperty(k);expect(req.headers()['idempotency-key']).toBeTruthy();m={...m,...b};return send(m,201)}
 if(p==='/api/v1/materials/21'){if(method==='PUT'){const b=req.postDataJSON();expect(b).not.toHaveProperty('materialCode');expect(b).not.toHaveProperty('versionId');expect(b.reason).toBeTruthy();expect(req.headers()['if-match']).toBe(`"${m.versionNo}"`);m={...m,...b,versionNo:m.versionNo+1}}return send(m)}
 if(p==='/api/v1/materials/21/suppliers'){if(method==='PUT'){const b=req.postDataJSON();expect(b.suppliers).toHaveLength(2);expect(b.suppliers.filter((v:any)=>v.preferred)).toEqual([{supplierId:'42',approved:true,preferred:true,validTo:null}]);expect(req.headers()['if-match']).toBe(`"${m.versionNo}"`);links=b.suppliers.map((v:any)=>({...v,...suppliers.find(s=>s.id===v.supplierId)}));m.versionNo++}return send({id:'21',versionNo:m.versionNo,suppliers:links})}
 if(p==='/api/v1/unit-conversions'){if(method==='POST'){const b=req.postDataJSON();expect(b).toEqual({materialId:'21',fromUnitId:'1',toUnitId:'2',factor:'1000'});conversions=[{id:'51',versionNo:0,...b}];return send(conversions[0],201)}expect(new URL(req.url()).searchParams.get('materialId')).toBe('21');return send(list(conversions))}
 if(/\/(versions|submit|approve)$/.test(p))throw Error('Retired material workflow requested');return send(list([]))
 })
}
async function select(page:Page,label:string,text:string){await page.locator(`[aria-label="${label}"].ant-select`).click();await page.locator('.ant-select-dropdown:visible').getByText(text,{exact:true}).click()}
test('basic create and direct maintenance without version approval',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await page.goto('/master/materials/create');await page.getByLabel('物料编码').fill('MAT-NEW');await page.getByLabel('物料名称').fill('新制剂');await page.getByLabel('物料类型').fill('FINISHED');await select(page,'基本单位','千克 （kg）');await page.getByRole('button',{name:'保存基本信息'}).click();await expect(page.getByRole('heading',{name:'物料基本信息',exact:true})).toBeVisible();await expect(page.getByText('新制剂',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/版本|批准|提交/})).toHaveCount(0);await page.getByRole('button',{name:'维护基本信息'}).click();await page.getByLabel('物料名称').fill('维护后的制剂');await page.getByLabel('变更原因 *',{exact:true}).fill('维护基本名称');await page.getByRole('button',{name:'保存基本信息'}).click();await expect(page.getByText('维护后的制剂',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('material-basic.png'),fullPage:true});expect(errors).toEqual([])
})
test('multiple suppliers with exactly one preferred',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await page.goto('/master/materials/21/edit');await select(page,'选择供应商','供应商甲（SUP-A）');await page.getByRole('button',{name:'添加供应商'}).click();await expect(page.getByRole('radio',{name:'首选供应商 供应商甲'})).toBeChecked();await select(page,'选择供应商','供应商乙（SUP-B）');await page.getByRole('button',{name:'添加供应商'}).click();await page.getByRole('radio',{name:'首选供应商 供应商乙'}).check();await expect(page.getByRole('radio',{name:'首选供应商 供应商甲'})).not.toBeChecked();await page.getByLabel('关系变更原因').fill('设置多个供应商与唯一首选');await page.getByRole('button',{name:'保存供应商关系'}).click();await expect(page.getByLabel('关系变更原因')).toHaveValue('');await expect(page.getByRole('radio',{name:'首选供应商 供应商乙'})).toBeChecked();await page.screenshot({path:info.outputPath('material-suppliers.png'),fullPage:true});expect(errors).toEqual([])
})
test('material specific conversion with named units',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await page.goto('/master/materials/21/edit');await page.getByRole('button',{name:'添加单位换算'}).click();await select(page,'换算目标单位','克（g）');await page.getByLabel('换算因子',{exact:true}).fill('1000');await page.getByRole('button',{name:'保存换算',exact:true}).click();await expect(page.getByRole('cell',{name:'1000',exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'千克',exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'克',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('material-conversion.png'),fullPage:true});expect(errors).toEqual([])
})
