import {test,expect,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import {createHash} from 'node:crypto'
const evidence=process.env.MES_PRINT_EVIDENCE_DIR??join(tmpdir(),'mes-print-ui-evidence');mkdirSync(evidence,{recursive:true})
const envelope=(data:unknown)=>({code:'OK',message:'success',data,traceId:'printing-ui-isolated-fixture'})
const template={id:'801',templateCode:'QC-REPORT',templateName:'中文检验报告',templateRevision:2,businessType:'INSPECTION_REPORT',status:'PUBLISHED',versionNo:1,previewHash:'a'.repeat(64)}
async function setup(page:Page,allowed=true){const calls:{pdf:number;generate:number;body:unknown}={pdf:0,generate:0,body:null};await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname,send=(data:unknown)=>route.fulfill({json:envelope(data)}),list=(items:unknown[])=>({items,total:items.length,page:0,size:20})
 if(path.endsWith('/auth/me'))return send({userId:'5',organizationId:'1',loginName:'qa',displayName:'打印验收人员',roleCodes:['QA'],permissionCodes:allowed?['print:template:view','print:template:manage','print:template:publish','print:document:generate','qms:report:view']:['qms:report:view'],mustChangePassword:false})
 if(path.endsWith('/printing/templates'))return send(list([template]))
 if(path.endsWith('/printing/fields'))return send({definitions:[{key:'reportNo',label:'报告编号',group:'报告信息',description:'系统检验报告号',example:'R-001',repeated:false}]})
 if(path.endsWith('/printing/applicable'))return send([template])
 if(path.endsWith('/printing/editor/sessions'))return route.fulfill({status:503,json:{code:'EDITOR_NOT_READY',message:'文档服务尚未配置'}})
 if(path.endsWith('/printing/artifacts')){if(route.request().method()==='POST'){calls.generate++;calls.body=route.request().postDataJSON();return send({id:'901',reportNo:'R-001',businessVersion:3,templateRevision:2,formal:false})}return send([])}
 if(path.endsWith('/printing/artifacts/901/pdf')){calls.pdf++;return route.fulfill({contentType:'application/pdf',body:readFileSync(process.env.MES_PRINT_PDF_FIXTURE!)})}
 if(path.endsWith('/quality/inspection-reports/17'))return send({id:'17',reportNo:'R-001',inspectionRequestId:'30',status:'APPROVED',recordStatus:'APPROVED',overallResult:'PASS',versionNo:3,createdBy:'5',createdAt:'2026-10-08T00:00:00Z',updatedBy:'5',updatedAt:'2026-10-08T00:00:00Z',evidenceDigest:'fixture-only',supersedesReportId:null,approvalSignatureId:null,reviewedBy:null,approvedBy:null,reviewedAt:null,approvedAt:null,signatureEvidence:[],items:[],allowedActions:[]})
 return send(list([]))
});return calls}
test('template management filters and Chinese field guidance render without runtime errors',async({page},info)=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await page.goto('/admin/print-templates');await expect(page).toHaveURL(/admin\/print-templates$/);await expect(page.getByRole('heading',{name:'打印模板',exact:true})).toBeVisible();await expect(page.getByText('中文检验报告',{exact:true})).toBeVisible();await page.getByRole('button',{name:'可用字段',exact:true}).click();await expect(page.getByText('报告编号',{exact:true})).toBeVisible();await expect(page.getByText('系统检验报告号',{exact:true})).toBeVisible();await expect(page.locator('.ant-drawer-content-wrapper')).toHaveCSS('transform','none');await expect(page.locator('vite-error-overlay')).toHaveCount(0);await page.screenshot({path:join(evidence,`template-fields-${info.project.name}.png`),fullPage:true});expect(errors).toEqual([])})
test('missing Word service is reported and never claims a successful save',async({page},info)=>{await setup(page);await page.goto('/admin/print-templates/801/edit');await expect(page.getByText(/在线 Word 尚未就绪/)).toBeVisible();await expect(page.getByText(/Word 已回存/)).toHaveCount(0);await page.screenshot({path:join(evidence,`word-dependency-${info.project.name}.png`),fullPage:true})})
test('business preview and download share the actual archived PDF fixture',async({page},info)=>{test.skip(!process.env.MES_PRINT_PDF_FIXTURE,'Requires previously generated real LibreOffice PDF fixture');const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const calls=await setup(page);await page.goto('/quality/inspection-reports/17');await expect(page.getByText('报告打印',{exact:true})).toBeVisible();await page.getByRole('button',{name:'生成并预览 PDF',exact:true}).click();await expect(page.getByTitle('PDF 文档预览')).toBeVisible();await expect(page.locator('.ant-modal')).toHaveCSS('transform','none');expect(calls.body).toEqual({businessType:'INSPECTION_REPORT',businessId:'17',templateVersionId:'801',formal:false});const event=page.waitForEvent('download');await page.getByRole('button',{name:'下载 PDF',exact:true}).click();const downloaded=await event;const path=join(evidence,`downloaded-${info.project.name}.pdf`);await downloaded.saveAs(path);expect(createHash('sha256').update(readFileSync(path)).digest('hex')).toBe(createHash('sha256').update(readFileSync(process.env.MES_PRINT_PDF_FIXTURE!)).digest('hex'));expect(calls.pdf).toBe(1);expect(calls.generate).toBe(1);expect(errors).toEqual([]);await expect(page.locator('vite-error-overlay')).toHaveCount(0);await page.screenshot({path:join(evidence,`inspection-pdf-${info.project.name}.png`),fullPage:true})})
test('unauthorized user has no template management route or report print control',async({page})=>{await setup(page,false);await page.goto('/admin/print-templates');await expect(page).toHaveURL(/\/$/);await page.goto('/quality/inspection-reports/17');await expect(page.getByRole('button',{name:'生成并预览 PDF',exact:true})).toHaveCount(0)})
