import {test,expect,type Page} from '@playwright/test'
import {mkdirSync} from 'node:fs'
import {resolve} from 'node:path'
test.use({viewport:{width:1440,height:900}})
const out=resolve('../../docs/acceptance/trace-finished-inventory-2026-10-06/screenshots');mkdirSync(out,{recursive:true})
const permissions=['wms:inventory:view','production:batch:view','master:product:view','trace:view','mes:charge:view','mes:charge:create','mes:operation:view','wms:issue:view','wms:request:view','wms:finished-shipment:view']
const row={materialLotId:'61',materialId:'40',lotNo:'FG-20261006-001',materialCode:'FG-001',materialName:'成品物料',mainBatchId:'100',batchNo:'PB-20261006-001',productId:'20',productCode:'PRD-001',productName:'复方软膏',productSpecification:'50 g/支',onHandQty:'10.000000',reservedQty:'0.000000',availableQty:'10.000000',unitName:'支',unitId:'10',qualityStatus:'QUARANTINE',inventoryStatus:'BLOCKED',locationBalances:[{warehouseId:'1',warehouseName:'成品库',locationId:'11',locationName:'A01',onHandQty:'10.000000',unitName:'支'}]}
const node=(type:string,id:string,label:string)=>({type,id,label,status:null,revision:null})
const edge=(sourceType:string,sourceId:string,targetType:string,targetId:string,relation='实际来源')=>({sourceType,sourceId,targetType,targetId,relation})
const graph={nodes:[node('MATERIAL_LOT','50','来料批次 ML-001'),node('MAIN_BATCH','100','生产批 PB-20261006-001'),node('EXECUTION_UNIT','10','执行单元 EU-001'),node('OPERATION','20','工序 投料'),node('CHARGE','30','CHARGE 30'),node('MATERIAL_ISSUE','70','出库单 OUT-001'),node('MATERIAL_ISSUE_ITEM','71','出库明细 71'),node('ISSUE_RETURN','72','退料记录 72'),node('FINISHED_SHIPMENT','90','成品发货 SHIP-001')],edges:[edge('MAIN_BATCH','100','EXECUTION_UNIT','10'),edge('EXECUTION_UNIT','10','OPERATION','20'),edge('OPERATION','20','CHARGE','30'),edge('CHARGE','30','MATERIAL_LOT','50','CONSUMED_FROM'),edge('MATERIAL_ISSUE','70','MATERIAL_ISSUE_ITEM','71'),edge('MATERIAL_ISSUE_ITEM','71','ISSUE_RETURN','72')]}
async function fixture(page:Page){const errors:string[]=[],reads:URL[]=[],writes:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.route('**/api/v1/**',async r=>{const u=new URL(r.request().url()),path=u.pathname.replace('/api/v1','');reads.push(u);if(r.request().method()!=='GET')writes.push(path);let data:any={items:[],total:0,page:0,size:20};if(path==='/auth/me')data={userId:'9',organizationId:'1',displayName:'制剂库存管理员',permissionCodes:permissions,roleCodes:[],mustChangePassword:false};else if(path==='/wms/inventory')data={items:u.searchParams.get('page')==='1'?[]:[row],total:21,page:Number(u.searchParams.get('page')??0),size:20};else if(path==='/trace')data=graph;else if(path==='/execution-units/10')data={id:'10',executionNo:'EU-001',mainBatchId:'100',status:'IN_PROGRESS',versionNo:0};else if(path.startsWith('/execution-units/10/'))data=[];else if(path==='/main-batches/100')data={id:'100',batchNo:'PB-20261006-001',productId:'20',status:'IN_PROGRESS',executionUnits:[],processSnapshot:{snapshot:{process:{formula:{items:[]},route:{operations:[]}}}}};else if(path==='/products')data={items:[{id:'20',productCode:'PRD-001',productName:'复方软膏'}],total:1,page:0,size:20};else if(path==='/main-batches')data={items:[{id:'100',batchNo:'PB-20261006-001',productId:'20'}],total:1,page:0,size:20};else if(path==='/wms/material-lots/61')data={id:'61',lotNo:row.lotNo,materialId:'40',materialSnapshot:{materialName:row.materialName,materialType:'FINISHED',baseUnitId:'10'},qualityStatus:'QUARANTINE',inventoryStatus:'BLOCKED',versionNo:0};else if(path==='/finished-material-lots/61/chain')data={mainBatchId:'100',lot:{id:'61',lotNo:row.lotNo},receiving:[],shipments:[],access:{production:'NOT_AUTHORIZED'}};await r.fulfill({json:{code:'OK',data,traceId:'targeted-pc-read-fixture'}})});return {errors,reads,writes}}
async function screenshot(page:Page,name:string){await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:resolve(out,name+'.png'),fullPage:true,animations:'disabled'})}
test('finished inventory T1 keeps server scope through query reset paging and opens actual lot',async({page})=>{
 const f=await fixture(page);await page.goto('/finished/inventory?finishedOnly=false');await expect(page.locator('main[data-ui-template="T1"] h1')).toHaveText('成品库存');await expect(page.getByRole('cell',{name:'复方软膏 PRD-001',exact:true})).toBeVisible();await expect(page.locator('.ant-table').getByText('50 g/支',{exact:true})).toBeVisible();await expect(page.locator('.ant-table').getByText('待验',{exact:true})).toBeVisible();await expect(page.getByText('成品库存',{exact:true}).first()).toBeVisible();await screenshot(page,'finished-inventory-desktop');
 const product=page.getByLabel('产品查询',{exact:true});expect((await page.locator('.process-lookup>.ant-select').boundingBox())?.width).toBeGreaterThan(180);await product.click();await page.locator('.ant-select-dropdown').getByText('复方软膏（PRD-001）',{exact:true}).click();await page.getByLabel('关键字',{exact:true}).fill('复方软膏');await page.getByRole('button',{name:/查\s*询/,exact:true}).click();await expect.poll(()=>f.reads.filter(u=>u.pathname.endsWith('/wms/inventory')).at(-1)?.searchParams.get('keyword')).toBe('复方软膏');expect(f.reads.filter(u=>u.pathname.endsWith('/wms/inventory')).at(-1)?.searchParams.get('productId')).toBe('20');
 await page.getByRole('button',{name:/重\s*置/,exact:true}).click();await expect(page.getByLabel('关键字',{exact:true})).toHaveValue('');await page.locator('.ant-pagination').getByTitle('2',{exact:true}).click();await expect.poll(()=>f.reads.filter(u=>u.pathname.endsWith('/wms/inventory')).at(-1)?.searchParams.get('page')).toBe('1');await page.locator('.ant-pagination').getByTitle('1',{exact:true}).click();await page.getByRole('button',{name:row.lotNo,exact:true}).click();await expect(page).toHaveURL(/wms\/material-lots\/61/);expect(f.reads.filter(u=>u.pathname.endsWith('/wms/inventory')).every(u=>u.searchParams.get('finishedOnly')==='true')).toBe(true);expect(f.writes).toEqual([]);expect(f.errors).toEqual([])
})
test('trace T4 emphasizes actual charge without weighing and resolves existing source destinations',async({page})=>{
 const f=await fixture(page);await page.goto('/trace?materialLotId=50');await expect(page.locator('main[data-ui-template="T4"]')).toBeVisible();await expect(page.locator('.trace-node').filter({hasText:'投料记录'})).toBeVisible();await expect(page.locator('.trace-node').filter({hasText:'称量记录'})).toHaveCount(0);await screenshot(page,'actual-charge-trace-desktop');
 await page.locator('.trace-node').filter({hasText:'投料记录'}).click();await expect(page.getByRole('button',{name:'查看来源记录',exact:true})).toBeVisible();await screenshot(page,'charge-source-drawer-desktop');await page.getByRole('button',{name:'查看来源记录',exact:true}).click();await expect(page).toHaveURL(/mes\/execution\/10\/charge/);
 await page.goto('/trace?materialLotId=50');await page.locator('.trace-node').filter({hasText:'退料记录'}).click();await page.getByRole('button',{name:'查看来源记录',exact:true}).click();await expect(page).toHaveURL(/wms\/issues\/70/);expect(f.writes).toEqual([]);expect(f.errors).toEqual([])
})
test('finished inventory cannot be overwritten by a delayed raw inventory response',async({page})=>{
 const f=await fixture(page);let releaseRaw!:()=>void,rawStarted!:()=>void,rawCompleted!:()=>void;
 const delayed=new Promise<void>(resolve=>{releaseRaw=resolve}),started=new Promise<void>(resolve=>{rawStarted=resolve}),completed=new Promise<void>(resolve=>{rawCompleted=resolve});
 await page.route('**/api/v1/wms/inventory?*',async r=>{const finished=new URL(r.request().url()).searchParams.get('finishedOnly')==='true';if(!finished){rawStarted();await delayed}await r.fulfill({json:{code:'OK',data:{items:[finished?row:{...row,materialLotId:'50',lotNo:'RAW-DELAYED',materialName:'原料延迟响应'}],total:1,page:0,size:20},traceId:'scope-race-fixture'}});if(!finished)rawCompleted()});
 const rawFinished=page.waitForEvent('requestfinished',{predicate:r=>{const url=new URL(r.url());return url.pathname.endsWith('/wms/inventory')&&url.searchParams.get('finishedOnly')!=='true'}});
 await page.goto('/wms/inventory');await started;await page.locator('.ant-menu').getByText('成品库存',{exact:true}).click();await expect(page.getByRole('button',{name:row.lotNo,exact:true})).toBeVisible();releaseRaw();await completed;await rawFinished;await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(page.locator('main[data-ui-template="T1"] h1')).toHaveText('成品库存');await expect(page.getByRole('button',{name:row.lotNo,exact:true})).toBeVisible();await expect(page.getByText('RAW-DELAYED',{exact:true})).toHaveCount(0);expect(f.errors).toEqual([])
})
