package com.hospital.mes.reporting.application;
import com.hospital.mes.reporting.infrastructure.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.common.exception.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import com.fasterxml.jackson.databind.*;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import java.time.*;import java.util.*;import java.net.*;
@Service @ConditionalOnProperty(prefix="mes.print.editor",name="enabled",havingValue="true")
public class PrintEditorService {
 public static final String PLUGIN="asc.{ED351CE4-0E66-497C-B658-540510CD853D}";
 private final PrintEditorSessionMapper sessions;private final ScopedStore<PrintTemplateVersion> templates;private final MasterMutation mutations;private final PrintService printing;private final EditorActorPort actors;private final EditorJwt jwt;private final String officeUrl,publicBase;
 public PrintEditorService(PrintEditorSessionMapper sessions,PrintTemplateVersionMapper templates,MasterMutation mutations,PrintService printing,EditorActorPort actors,@Value("${mes.print.editor.jwt-secret:}")String secret,@Value("${mes.print.editor.document-server-url:}")String officeUrl,@Value("${mes.print.editor.public-base-url:}")String publicBase){this.sessions=sessions;this.templates=new ScopedStore<>(templates,List.of(),Map.of());this.mutations=mutations;this.printing=printing;this.actors=actors;this.jwt=new EditorJwt(secret,Clock.systemUTC());this.officeUrl=origin(officeUrl);this.publicBase=origin(publicBase);}
 private static String origin(String raw){URI u=URI.create(raw);if(!Set.of("http","https").contains(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null||u.getQuery()!=null||u.getFragment()!=null||!(u.getPath().isEmpty()||u.getPath().equals("/")))throw new IllegalArgumentException("Editor origin must be an administrator-configured HTTP(S) origin");return raw.replaceAll("/$","");}
 @Transactional public Map<String,Object> open(String templateVersionId){var c=mutations.context("print:template:manage");mutations.context("print:template:view");var source=templates.get(c.organizationId(),MasterMutation.id(templateVersionId));var s=new PrintEditorSession();s.setId(UUID.randomUUID().toString());s.setOrgId(c.organizationId());s.setActorId(c.actorId());s.setLoginSessionId(c.sessionId());s.setSourceTemplateVersionId(source.getId());s.setExpiresAt(LocalDateTime.now(ZoneOffset.UTC).plusHours(2));s.setVersionNo(0L);sessions.insert(s);String token=capability(s);String transfer=publicBase+"/api/v1/printing/editor/transfer/"+s.getId();var document=Map.of("fileType","docx","key","mes-"+s.getId(),"title",source.getTemplateName()+" · 新版本编辑","url",transfer+"/document?token="+token,"permissions",Map.of("edit",true,"download",false,"print",false,"review",false));var editor=Map.of("lang","zh-CN","mode","edit","user",Map.of("id",""+c.actorId(),"name","模板维护人员"),"callbackUrl",transfer+"/callback?token="+token,"customization",Map.of("forcesave",true,"autosave",true,"plugins",Map.of("autostart",List.of(PLUGIN),"pluginsData",List.of(transfer+"/plugin-config?token="+token))));var config=new LinkedHashMap<String,Object>();config.put("documentType","word");config.put("type","desktop");config.put("document",document);config.put("editorConfig",editor);config.put("exp",s.getExpiresAt().toEpochSecond(ZoneOffset.UTC));config.put("token",jwt.sign(config));return Map.of("sessionId",s.getId(),"documentServerUrl",officeUrl,"config",config);}
 private String capability(PrintEditorSession s){return jwt.sign(Map.of("aud","mes-editor-transfer","sid",s.getId(),"exp",s.getExpiresAt().toEpochSecond(ZoneOffset.UTC)));}
 private PrintEditorSession require(String id,String token,boolean lock){if(!id.equals(jwt.verify(token,"mes-editor-transfer").path("sid").asText()))throw new PermissionException("EDITOR_TOKEN_INVALID","Editor session mismatch");var q=new QueryWrapper<PrintEditorSession>().eq("id",id);if(lock)q.last("FOR UPDATE");var s=sessions.selectOne(q);if(s==null||!s.getExpiresAt().isAfter(LocalDateTime.now(ZoneOffset.UTC)))throw new PermissionException("EDITOR_SESSION_EXPIRED","Editor session expired");actors.requireActiveEditor(s.getOrgId(),s.getActorId(),s.getLoginSessionId());return s;}
 public byte[] document(String id,String token){var s=require(id,token,false);return templates.get(s.getOrgId(),s.getSourceTemplateVersionId()).getDocx().clone();}
 public List<PrintField> dictionary(String id,String token){var s=require(id,token,false);var t=templates.get(s.getOrgId(),s.getSourceTemplateVersionId());return printing.provider(t.getBusinessType()).fieldDefinitions();}
 public byte[] loop(String id,String token,List<String> columns){return EditorLoopDocx.create(columns,dictionary(id,token));}
 public Map<String,Object> plugin(String id,String token){require(id,token,false);String query="?session="+id+"&token="+URLEncoder.encode(token,java.nio.charset.StandardCharsets.UTF_8)+"&office="+URLEncoder.encode(officeUrl,java.nio.charset.StandardCharsets.UTF_8);return Map.of("name","MES中文打印字段","guid",PLUGIN,"version","1.0.0","variations",List.of(Map.of("description","中文字段与检验项目循环表","url",publicBase+"/onlyoffice-plugin/index.html"+query,"isViewer",false,"EditorsSupport",List.of("word"),"isVisual",true,"isModal",false,"isInsideMode",true,"initDataType","none","initData","","buttons",List.of())));}
 public Map<String,Object> status(String id){var c=mutations.context("print:template:manage");var s=sessions.selectOne(new QueryWrapper<PrintEditorSession>().eq("id",id).eq("org_id",c.organizationId()).eq("actor_id",c.actorId()));if(s==null)throw new NoSuchElementException();return Map.of("sessionId",s.getId(),"savedTemplateVersionId",s.getSavedTemplateVersionId()==null?"":s.getSavedTemplateVersionId().toString(),"expiresAt",s.getExpiresAt().toString());}
 @Transactional public Map<String,Integer> callback(String id,String token,String authorization,JsonNode body){
  var s=require(id,token,true);String bearer=authorization!=null&&authorization.startsWith("Bearer ")?authorization.substring(7):body.path("token").asText(null);var signed=jwt.verify(bearer,null);if(signed.has("payload"))signed=signed.path("payload");for(String field:List.of("key","status","url","users","filetype"))if(!signed.path(field).equals(body.path(field)))throw new PermissionException("EDITOR_CALLBACK_INVALID","Callback body differs from signed payload");if(!("mes-"+id).equals(body.path("key").asText()))throw new PermissionException("EDITOR_CALLBACK_INVALID","Callback document mismatch");int status=body.path("status").asInt(-1);if(status==1||status==4)return Map.of("error",0);if(status!=2&&status!=6)throw new ComplianceException("EDITOR_SAVE_FAILED","Office reported unsuccessful save");if(!"docx".equals(body.path("filetype").asText("docx")))throw new IllegalArgumentException("DOCX required");if(!body.path("users").isArray()||body.path("users").size()!=1||!body.path("users").get(0).asText().equals(s.getActorId().toString()))throw new PermissionException("EDITOR_CALLBACK_INVALID","Editor actor mismatch");byte[] docx=EditorDownloadPolicy.download(officeUrl,body.path("url").asText());String hash=PrintService.hash(docx);if(hash.equals(s.getLastContentHash()))return Map.of("error",0);var c=actors.requireActiveEditor(s.getOrgId(),s.getActorId(),s.getLoginSessionId());var source=templates.get(s.getOrgId(),s.getSourceTemplateVersionId());var saved=printing.uploadFromEditor(c,source.getTemplateCode(),source.getTemplateName(),source.getBusinessType(),docx,"在线Word编辑会话 "+s.getId()+" 保存新版本");var update=new UpdateWrapper<PrintEditorSession>().eq("id",s.getId()).eq("version_no",s.getVersionNo()).set("saved_template_version_id",Long.parseLong(saved.path("id").asText())).set("last_content_hash",hash).set("version_no",s.getVersionNo()+1);if(sessions.update(null,update)!=1)throw new ResourceConflictException("EDITOR_CONFLICT","Concurrent editor save");return Map.of("error",0);
 }
}
