package com.hospital.mes.reporting.application;
import com.hospital.mes.reporting.infrastructure.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.audit.application.CurrentPlatformContext;
import com.hospital.mes.common.exception.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import java.time.*;
import java.util.*;
@Service @ConditionalOnProperty(prefix="spring.datasource",name="url")
public class PrintService {
 private final PrintTemplateVersionMapper templates;private final PrintBindingMapper bindings;private final PrintArtifactMapper artifacts;
 private final ScopedStore<PrintTemplateVersion> templateStore;private final ScopedStore<PrintBinding> bindingStore;private final ScopedStore<PrintArtifact> artifactStore;
 private final MasterMutation mutations;private final ObjectMapper json;private final DocxGuard guard;private final DocxRenderer renderer;private final PdfConverter converter;private final Map<String,PrintDataProvider> providers;private final NativePrintDesigner nativeDesigner;
 public PrintService(PrintTemplateVersionMapper templates,PrintBindingMapper bindings,PrintArtifactMapper artifacts,MasterMutation mutations,ObjectMapper json,DocxGuard guard,DocxRenderer renderer,PdfConverter converter,List<PrintDataProvider> providers){
  this.templates=templates;this.bindings=bindings;this.artifacts=artifacts;this.mutations=mutations;this.json=json;this.guard=guard;this.renderer=renderer;this.converter=converter;this.nativeDesigner=new NativePrintDesigner(json);
  templateStore=new ScopedStore<>(templates,List.of("template_code","template_name"),Map.of("businessType","business_type","status","status"));bindingStore=new ScopedStore<>(bindings,List.of(),Map.of());artifactStore=new ScopedStore<>(artifacts,List.of(),Map.of());
  var map=new HashMap<String,PrintDataProvider>();for(var p:providers)if(map.put(p.businessType(),p)!=null)throw new IllegalStateException("Duplicate print provider");this.providers=Map.copyOf(map);
 }
 public PrintDataProvider provider(String type){var p=providers.get(type);if(p==null)throw new IllegalArgumentException("不支持的打印业务类型");return p;}
 private JsonNode view(com.hospital.mes.masterdata.infrastructure.ScopedEntity row){var n=json.createObjectNode();n.put("id",row.getId().toString()).put("orgId",row.getOrgId().toString()).put("createdBy",row.getCreatedBy().toString()).put("versionNo",row.getVersionNo());n.put("createdAt",String.valueOf(row.getCreatedAt()));
  if(row instanceof PrintTemplateVersion t){n.put("templateCode",t.getTemplateCode()).put("templateName",t.getTemplateName()).put("templateRevision",t.getTemplateRevision()).put("businessType",t.getBusinessType()).put("status",t.getStatus()).put("contentHash",t.getContentHash()).put("previewHash",t.getPreviewHash()).put("publishedAt",String.valueOf(t.getPublishedAt()));}
  else if(row instanceof PrintArtifact a){n.put("businessType",a.getBusinessType()).put("businessId",a.getBusinessId()).put("businessVersion",a.getBusinessVersion()).put("reportNo",a.getReportNo()).put("templateVersionId",a.getTemplateVersionId().toString()).put("templateRevision",a.getTemplateRevision()).put("formal",a.getFormal()).put("snapshotHash",a.getSnapshotHash()).put("pdfHash",a.getPdfHash());}
  else if(row instanceof PrintBinding b){n.put("businessType",b.getBusinessType()).put("templateVersionId",b.getTemplateVersionId().toString()).put("enabled",b.getEnabled());}return n;
 }

 /** Internal booklet adapter: exact immutable version; historical INACTIVE versions remain usable. */
 public JsonNode requirePublishedTemplate(String id,String type){var c=mutations.context("print:template:view");var t=templateStore.get(c.organizationId(),MasterMutation.id(id));state(t.getStatus().equals("PUBLISHED")&&t.getBusinessType().equals(type),"Published compatible template required");return view(t);}
 public byte[] renderFrozen(String id,String type,Map<String,Object> data){var c=mutations.context("print:document:generate");var t=templateStore.get(c.organizationId(),MasterMutation.id(id));state(Set.of("PUBLISHED","INACTIVE").contains(t.getStatus())&&t.getBusinessType().equals(type),"Frozen published template required");if(!hash(t.getDocx()).equals(t.getContentHash()))throw new ComplianceException("PRINT_ARCHIVE_CORRUPT","Template hash mismatch");var p=provider(type);if(!p.fields().containsAll(data.keySet().stream().filter(k->!k.equals("items")).toList()))throw new IllegalArgumentException("Unknown mapped book field");return converter.convert(renderer.render(t.getDocx(),data,p.fields(),p.itemFields()));}
 public JsonNode types(){mutations.context("print:template:view");var a=json.createArrayNode();providers.keySet().stream().sorted().forEach(a::add);return a;}
 public Map<String,Object> fields(String type){mutations.context("print:template:view");var p=provider(type);return Map.of("definitions",p.fieldDefinitions(),"fields",p.fields().stream().sorted().toList(),"itemFields",p.itemFields().stream().sorted().toList(),"example",p.example());}
 /** A validated Chinese-field layout is converted to real DOCX and appended using the ordinary immutable template path. */
 public JsonNode nativeDesignDefaults(String type){mutations.context("print:template:view");provider(type);return nativeDesigner.defaults();}
 @Transactional(readOnly=true) public JsonNode nativeDesign(String templateId){var c=mutations.context("print:template:view");var template=templateStore.get(c.organizationId(),MasterMutation.id(templateId));var result=json.createObjectNode();result.set("template",view(template));result.set("design",nativeDesigner.extract(template.getDocx()));return result;}
 @Transactional public JsonNode createNativeDesign(String code,String name,String type,JsonNode design,String reason){
  var c=mutations.context("print:template:manage");var p=provider(type);
  byte[] docx=nativeDesigner.generate(design,p.fieldDefinitions());
  return uploadFromEditor(c,code,name,type,docx,reason);
 }
 public JsonNode list(int page,int size,String keyword,Map<String,String> filters){var c=mutations.context("print:template:view");if(page<0||page>1000000||size<1||size>100)throw new IllegalArgumentException("Invalid pagination");var q=new QueryWrapper<PrintTemplateVersion>().eq("org_id",c.organizationId());if(keyword!=null&&!keyword.isBlank()){if(keyword.length()>200)throw new IllegalArgumentException("Keyword too long");q.and(w->w.like("template_code",keyword).or().like("template_name",keyword));}for(String f:List.of("status","businessType"))if(filters.get(f)!=null&&!filters.get(f).isBlank())q.eq(f.equals("status")?"status":"business_type",filters.get(f));long count=templates.selectCount(q);q.select("id","org_id","template_code","template_name","template_revision","business_type","status","content_hash","preview_hash","published_at","created_by","created_at","version_no").orderByDesc("id").last("LIMIT "+((long)page*size)+","+size);var out=json.createObjectNode();out.put("page",page).put("size",size).put("total",count);var items=out.putArray("items");templates.selectList(q).forEach(row->items.add(view(row)));return out;}

 public JsonNode applicable(String type){var c=mutations.context("print:document:generate");provider(type);var out=json.createArrayNode();for(var b:bindings.selectList(new QueryWrapper<PrintBinding>().eq("org_id",c.organizationId()).eq("business_type",type).eq("enabled",true).orderByAsc("id"))){var t=templateStore.get(c.organizationId(),b.getTemplateVersionId());if("PUBLISHED".equals(t.getStatus()))out.add(view(t));}return out;}
 @Transactional public JsonNode upload(String code,String name,String type,byte[] content,String reason){
  return uploadFromEditor(mutations.context("print:template:manage"),code,name,type,content,reason);
 }
 JsonNode uploadFromEditor(CurrentPlatformContext c,String code,String name,String type,byte[] content,String reason){
  if(!c.hasPermission("print:template:manage"))throw new PermissionException("PERMISSION_DENIED","Template maintenance permission required");if(code==null||!code.matches("[A-Za-z0-9_-]{1,60}")||name==null||name.isBlank()||name.length()>120)throw new IllegalArgumentException("模板编码/名称无效");reason(reason);
  var p=provider(type);guard.validate(content,p.fields(),p.itemFields());
  var previous=templates.selectList(new QueryWrapper<PrintTemplateVersion>().eq("org_id",c.organizationId()).eq("template_code",code).orderByDesc("template_revision").last("FOR UPDATE"));
  if(!previous.isEmpty()&&!type.equals(previous.getFirst().getBusinessType()))throw new IllegalArgumentException("同一模板编码不能改变业务类型");
  var row=new PrintTemplateVersion();row.setTemplateCode(code);row.setTemplateName(name.strip());row.setTemplateRevision(previous.isEmpty()?1:previous.getFirst().getTemplateRevision()+1);row.setBusinessType(type);row.setStatus("DRAFT");row.setDocx(content.clone());row.setContentHash(hash(content));templateStore.insert(row,c.organizationId(),c.actorId());audit(c,"PRINT_TEMPLATE_UPLOAD",row,reason);return view(row);
 }
 @Transactional public JsonNode validate(String id,long expected,String reason){var c=mutations.context("print:template:manage");reason(reason);var row=templateStore.lock(c.organizationId(),MasterMutation.id(id));version(row.getVersionNo(),expected);state(Set.of("DRAFT","VALIDATED").contains(row.getStatus()),"已发布版本不可重新验证或覆盖");var p=provider(row.getBusinessType());if(!guard.validate(row.getDocx(),p.fields(),p.itemFields()).containsAll(Set.of("modeLabel","reportNo")))throw new IllegalArgumentException("模板必须插入正式/草稿标记与报告编号");byte[] pdf=converter.convert(renderer.render(row.getDocx(),p.example(),p.fields(),p.itemFields()));row.setPreviewPdf(pdf);row.setPreviewHash(hash(pdf));row.setStatus("VALIDATED");templateStore.update(row,expected,c.actorId(),List.of("previewPdf","previewHash","status"));audit(c,"PRINT_TEMPLATE_VALIDATE",row,reason);return view(row);}
 @Transactional public JsonNode publish(String id,long expected,String reason){var c=mutations.context("print:template:publish");reason(reason);var row=templateStore.lock(c.organizationId(),MasterMutation.id(id));version(row.getVersionNo(),expected);state("VALIDATED".equals(row.getStatus())&&row.getPreviewPdf()!=null&&hash(row.getPreviewPdf()).equals(row.getPreviewHash()),"真实 PDF 验证通过后才能发布");row.setStatus("PUBLISHED");row.setPublishedAt(LocalDateTime.now(ZoneOffset.UTC));templateStore.update(row,expected,c.actorId(),List.of("status","publishedAt"));audit(c,"PRINT_TEMPLATE_PUBLISH",row,reason);return view(row);}
 @Transactional public JsonNode deactivate(String id,long expected,String reason){var c=mutations.context("print:template:publish");reason(reason);var row=templateStore.lock(c.organizationId(),MasterMutation.id(id));version(row.getVersionNo(),expected);state("PUBLISHED".equals(row.getStatus()),"仅已发布版本可停用");row.setStatus("INACTIVE");templateStore.update(row,expected,c.actorId(),List.of("status"));audit(c,"PRINT_TEMPLATE_DEACTIVATE",row,reason);return view(row);}
 @Transactional public JsonNode bind(String id,String type,boolean enabled,String reason){var c=mutations.context("print:template:publish");reason(reason);var row=templateStore.lock(c.organizationId(),MasterMutation.id(id));state("PUBLISHED".equals(row.getStatus()),"只允许绑定已发布版本");state(row.getBusinessType().equals(type),"业务字段合同不兼容");provider(type);var b=bindings.selectOne(new QueryWrapper<PrintBinding>().eq("org_id",c.organizationId()).eq("business_type",type).eq("template_version_id",row.getId()).last("FOR UPDATE"));if(b==null){b=new PrintBinding();b.setBusinessType(type);b.setTemplateVersionId(row.getId());b.setEnabled(enabled);bindingStore.insert(b,c.organizationId(),c.actorId());}else{long v=b.getVersionNo();b.setEnabled(enabled);bindingStore.update(b,v,c.actorId(),List.of("enabled"));}audit(c,"PRINT_TEMPLATE_BIND",b,reason);return view(b);}
 @Transactional public JsonNode generate(String type,String businessId,String templateId,boolean formal){
  var c=mutations.context("print:document:generate");var p=provider(type);var snapshot=p.load(businessId,formal); // adapter locks the authoritative business aggregate
  String key=formal?hash((c.organizationId()+"|"+type+"|"+businessId+"|"+snapshot.businessVersion()+"|"+templateId).getBytes(java.nio.charset.StandardCharsets.UTF_8)):null;
  if(formal){var old=artifacts.selectOne(new QueryWrapper<PrintArtifact>().eq("org_id",c.organizationId()).eq("formal_key",key));if(old!=null)return view(old);}
  var template=templateStore.lock(c.organizationId(),MasterMutation.id(templateId));state("PUBLISHED".equals(template.getStatus())&&type.equals(template.getBusinessType()),"需适用的已发布模板");
  state(bindings.selectCount(new QueryWrapper<PrintBinding>().eq("org_id",c.organizationId()).eq("business_type",type).eq("template_version_id",template.getId()).eq("enabled",true))==1,"模板未绑定当前业务");
  byte[] docx=renderer.render(template.getDocx(),snapshot.data(),p.fields(),p.itemFields());byte[] pdf=converter.convert(docx);
  var row=new PrintArtifact();row.setBusinessType(type);row.setBusinessId(businessId);row.setBusinessVersion(snapshot.businessVersion());row.setReportNo(snapshot.reportNo());row.setTemplateVersionId(template.getId());row.setTemplateRevision(template.getTemplateRevision());row.setFormal(formal);row.setFormalKey(key);try{row.setSnapshotJson(json.writeValueAsString(snapshot.data()));}catch(Exception e){throw new IllegalStateException(e);}row.setSnapshotHash(mutations.digest(snapshot.data()));row.setDocx(docx);row.setPdf(pdf);row.setPdfHash(hash(pdf));artifactStore.insert(row,c.organizationId(),c.actorId());audit(c,formal?"PRINT_FORMAL_ARCHIVE":"PRINT_DRAFT_ARCHIVE",row,"Generate from authorized server snapshot");return view(row);
 }
 public JsonNode history(String type,String businessId){var c=mutations.context("print:document:generate");provider(type).authorizeRead(businessId);var out=json.createArrayNode();artifacts.selectList(new QueryWrapper<PrintArtifact>().eq("org_id",c.organizationId()).eq("business_type",type).eq("business_id",businessId).select("id","org_id","created_by","created_at","version_no","business_type","business_id","business_version","report_no","template_version_id","template_revision","formal","snapshot_hash","pdf_hash").orderByDesc("id")).forEach(a->out.add(view(a)));return out;}
 public byte[] pdf(String id){var c=mutations.context("print:document:generate");var row=artifactStore.get(c.organizationId(),MasterMutation.id(id));provider(row.getBusinessType()).authorizeRead(row.getBusinessId());if(!hash(row.getPdf()).equals(row.getPdfHash()))throw new ComplianceException("PRINT_ARCHIVE_CORRUPT","归档 PDF 摘要不匹配");return row.getPdf().clone();}
 public byte[] preview(String id){var c=mutations.context("print:template:view");var row=templateStore.get(c.organizationId(),MasterMutation.id(id));if(row.getPreviewPdf()==null)throw new ComplianceException("PRINT_PREVIEW_REQUIRED","请先进行真实 PDF 验证");if(!hash(row.getPreviewPdf()).equals(row.getPreviewHash()))throw new ComplianceException("PRINT_ARCHIVE_CORRUPT","模板预览摘要不匹配");return row.getPreviewPdf().clone();}
 public byte[] template(String id){var c=mutations.context("print:template:view");return templateStore.get(c.organizationId(),MasterMutation.id(id)).getDocx().clone();}
 private void audit(CurrentPlatformContext c,String action,com.hospital.mes.masterdata.infrastructure.ScopedEntity row,String reason){mutations.auditSnapshot(c,action,row.getClass().getSimpleName(),row.getId(),null,view(row),reason,UUID.randomUUID().toString());}
 public static String hash(byte[] bytes){try{return HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(bytes));}catch(Exception e){throw new IllegalStateException(e);}}
 private static void reason(String reason){if(reason==null||reason.isBlank()||reason.length()>500)throw new IllegalArgumentException("需填写操作原因（最多500字）");}
 private static void version(long actual,long expected){if(actual!=expected)throw new ResourceConflictException("VERSION_CONFLICT","模板已变更，请刷新");}
 private static void state(boolean valid,String message){if(!valid)throw new ComplianceException("PRINT_STATE_INVALID",message);}
}
