package com.hospital.mes.reporting.application;
import org.apache.poi.xwpf.usermodel.*;import java.io.*;import java.util.*;
/** Safe plain data -> real Word table, shared by record preview and book rendering. */
@org.springframework.stereotype.Component
public class RecordTableDocx {
 public byte[] create(String title,String mode,List<String> columns,List<List<String>> rows){if(columns.isEmpty()||columns.size()>8||rows.size()>10000)throw new IllegalArgumentException("Record table limit");try(var doc=new XWPFDocument()){var sect=doc.getDocument().getBody().addNewSectPr();var size=sect.addNewPgSz();size.setW(java.math.BigInteger.valueOf(11906));size.setH(java.math.BigInteger.valueOf(16838));var margins=sect.addNewPgMar();margins.setTop(java.math.BigInteger.valueOf(850));margins.setBottom(java.math.BigInteger.valueOf(850));margins.setLeft(java.math.BigInteger.valueOf(850));margins.setRight(java.math.BigInteger.valueOf(850));var p=doc.createParagraph();p.setAlignment(ParagraphAlignment.CENTER);if(!p.getCTP().isSetPPr())p.getCTP().addNewPPr();p.setKeepNext(true);run(p,wrap(title,50),16,true);p=doc.createParagraph();if(!p.getCTP().isSetPPr())p.getCTP().addNewPPr();p.setKeepNext(true);run(p,wrap(mode,72),11,false);var table=doc.createTable(1,columns.size());table.setWidth("100%");var properties=table.getCTTbl().getTblPr();properties.addNewTblLayout().setType(org.openxmlformats.schemas.wordprocessingml.x2006.main.STTblLayoutType.FIXED);var grid=table.getCTTbl().getTblGrid();if(grid==null)grid=table.getCTTbl().addNewTblGrid();while(grid.sizeOfGridColArray()>0)grid.removeGridCol(0);for(int i=0;i<columns.size();i++)grid.addNewGridCol().setW(java.math.BigInteger.valueOf(10206/columns.size()));table.getRow(0).setRepeatHeader(true);table.getRow(0).getCtRow().getTrPr().getTblHeaderArray(0).setVal(true);for(int i=0;i<columns.size();i++)cell(table.getRow(0).getCell(i),columns.get(i),true,10206/columns.size());for(var values:rows){var row=table.createRow();row.setCantSplitRow(true);for(int i=0;i<columns.size();i++)cell(row.getCell(i),i<values.size()?values.get(i):"",false,10206/columns.size());}var out=new ByteArrayOutputStream();doc.write(out);return out.toByteArray();}catch(IOException e){throw new IllegalStateException(e);}}
 private static void cell(XWPFTableCell cell,String value,boolean bold,int width){cell.setWidth(Integer.toString(width));cell.removeParagraph(0);run(cell.addParagraph(),wrap(value,Math.max(4,(width-200)/200)),10,bold);}

 // Explicit line breaks retain every character and do not depend on Latin word wrapping in FOP.
 private static String wrap(String text,int limit){var out=new StringBuilder();int width=0;for(int cp:text.codePoints().toArray()){if(cp=='\n'){out.appendCodePoint(cp);width=0;continue;}int cost=cp>255?2:1;if(width+cost>limit){out.append('\n');width=0;}out.appendCodePoint(cp);width+=cost;}return out.toString();}
 private static void run(XWPFParagraph p,String value,int size,boolean bold){if(value.length()>20000)throw new IllegalArgumentException("Record text limit");var r=p.createRun();r.setFontFamily("Microsoft YaHei");r.setFontSize(size);r.setBold(bold);String[] lines=value.replace("\r","").split("\n",-1);for(int i=0;i<lines.length;i++){if(i>0)r.addBreak();r.setText(lines[i]);}}
}
