package com.hospital.mes.masterdata.domain;
import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.*;import java.time.*;
class MaterialSupplierRulesTest {
 @Test void directlyUsableActiveAndLegacyStates(){for(String state:java.util.List.of("ACTIVE","DRAFT","APPROVED")){assertThat(MaterialRules.enabled(state)).isTrue();MaterialRules.usable(state,null,null,Instant.now());}assertThat(MaterialRules.disable("ACTIVE")).isEqualTo("INACTIVE");assertThatThrownBy(()->MaterialRules.disable("INACTIVE")).hasMessageContaining("already inactive");}
 @Test void inactiveAndEffectiveGate(){var at=Instant.parse("2026-10-03T00:00:00Z");assertThatThrownBy(()->MaterialRules.usable("INACTIVE",null,null,at)).hasMessageContaining("MATERIAL_NOT_ACTIVE");assertThatThrownBy(()->MaterialRules.usable("ACTIVE",LocalDateTime.parse("2026-10-04T00:00:00"),null,at)).hasMessageContaining("MATERIAL_NOT_ACTIVE");}
 @Test void utcDatesAndRequiredFlags(){assertThat(MaterialRules.time("2026-10-03T08:00:00+08:00")).isEqualTo(LocalDateTime.parse("2026-10-03T00:00:00"));assertThatThrownBy(()->MaterialRules.period(LocalDateTime.now(),LocalDateTime.now().minusDays(1))).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->MaterialRules.required(null)).isInstanceOf(IllegalArgumentException.class);}
 @Test void supplierInclusiveUtcExpiry(){var end=LocalDate.parse("2026-10-03");SupplierRules.usable("APPROVED",end,true,end,Instant.parse("2026-10-03T23:59:59.999Z"));assertThatThrownBy(()->SupplierRules.usable("APPROVED",end,true,end,Instant.parse("2026-10-04T00:00:00Z"))).hasMessageContaining("SUPPLIER_NOT_APPROVED");}
 @Test void unqualifiedDisabledAndRevokedRejected(){for(String status:java.util.List.of("UNAPPROVED","INACTIVE"))assertThatThrownBy(()->SupplierRules.usable(status,null,true,null,Instant.now())).hasMessageContaining("SUPPLIER_NOT_APPROVED");assertThatThrownBy(()->SupplierRules.usable("APPROVED",null,false,null,Instant.now())).hasMessageContaining("SUPPLIER_NOT_APPROVED");}
}
