package com.hospital.mes.qc.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.audit.application.*;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.audit.idempotency.PlatformIdempotencyService;
import com.hospital.mes.common.exception.PermissionException;
import com.hospital.mes.masterdata.application.MasterQueryService;
import com.hospital.mes.qc.domain.*;
import com.hospital.mes.qc.infrastructure.*;
import java.util.*;
import java.time.ZoneOffset;
import org.springframework.stereotype.Service;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
@Service @ConditionalOnProperty(prefix="spring.datasource",name="url")
public class QcDefinitions {
 private final QcStore db; private final ObjectMapper json; private final MasterQueryService units; private final AuditQueryService audit; private final SignatureRepository signatures; private final SignatureCanonicalizer canonicalizer; private final QcSigningIntent intent;
 public QcDefinitions(QcStore db,ObjectMapper json,MasterQueryService units,AuditQueryService audit,SignatureRepository signatures,SignatureCanonicalizer canonicalizer,QcSigningIntent intent){this.db=db;this.json=json;this.units=units;this.audit=audit;this.signatures=signatures;this.canonicalizer=canonicalizer;this.intent=intent;}
 public void validate(long org,List<QcCommands.Item> items){QcSpecificationRules.validateItems(items);for(var i:items)if(i.unitId()!=null)try{units.unit(org,QcSpecificationRules.id(i.unitId()));}catch(NoSuchElementException e){throw new QcNotFoundException();}}
 public void validateVersion(SpecificationVersionEntity v){validate(v.getOrgId(),db.items(v.getOrgId(),v.getId(),true).stream().map(this::command).toList());}
 public QcCommands.Item command(SpecificationItemEntity i){return new QcCommands.Item(i.getItemCode(),i.getItemName(),i.getRequired(),i.getResultType(),decimal(i.getLowerLimit()),decimal(i.getUpperLimit()),id(i.getUnitId()),i.getTextAcceptanceCriteria(),i.getMethodCode(),i.getMethodVersion());}
 public void independent(SpecificationVersionEntity v,long actor){if(v.getCreatedBy()==actor)throw author();for(String action:List.of("QC_SPEC_VERSION_CREATED","QC_SPEC_VERSION_EDITED")){var events=audit.query(v.getOrgId(),new AuditEventQuery(actor,action,"QcSpecificationVersion",v.getId().toString(),null,null,null,null,null,0,1));if(!events.items().isEmpty()||events.total()>0)throw author();}}
 private PermissionException author(){return new PermissionException("QC_SPEC_INDEPENDENT_APPROVER_REQUIRED","A definition author cannot approve this version");}
 public ObjectNode definition(SpecificationVersionEntity v){var root=db.root(v.getOrgId(),v.getSpecificationId());var n=json.createObjectNode();n.put("orgId",id(v.getOrgId()));n.put("specificationId",id(root.getId()));n.put("specificationCode",root.getSpecificationCode());n.put("specificationName",root.getSpecificationName());n.put("materialId",id(root.getMaterialId()));n.put("specificationVersionId",id(v.getId()));n.put("versionNoBusiness",v.getVersionNoBusiness());var a=n.putArray("items");db.items(v.getOrgId(),v.getId(),true).stream().sorted(Comparator.comparing(SpecificationItemEntity::getItemCode).thenComparing(SpecificationItemEntity::getId)).forEach(i->a.add(itemNode(i)));return n;}
 public ObjectNode itemNode(SpecificationItemEntity i){var n=json.createObjectNode();n.put("specificationItemId",id(i.getId()));n.put("itemCode",i.getItemCode());n.put("itemName",i.getItemName());n.put("required",i.getRequired());n.put("resultType",i.getResultType());n.put("lowerLimit",decimal(i.getLowerLimit()));n.put("upperLimit",decimal(i.getUpperLimit()));n.put("unitId",id(i.getUnitId()));n.put("textAcceptanceCriteria",i.getTextAcceptanceCriteria());n.put("methodCode",i.getMethodCode());n.put("methodVersion",i.getMethodVersion());return n;}
 public String contentHash(SpecificationVersionEntity v){try{return PlatformIdempotencyService.digest(new org.erdtman.jcs.JsonCanonicalizer(json.writeValueAsBytes(definition(v))).getEncodedString());}catch(java.io.IOException e){throw new IllegalStateException(e);}}
 public SignableObject signable(long org,String id,String action){var v=db.version(org,QcSpecificationRules.id(id),false);var pending=intent.current();String reason=action.equals("APPROVE")?v.getApprovalReason():v.getRetirementReason();if(pending!=null&&pending.org()==org&&pending.versionId()==v.getId()&&pending.action().equals(action))reason=pending.reason();if(reason==null)throw QcSpecificationRules.conflict("QC_SPEC_SIGNATURE_INVALID","No authorized signing intent or committed signature evidence");var n=json.createObjectNode();n.set("definition",definition(v));n.put("action",action);n.put("reason",reason);List<String> evidence=new ArrayList<>(List.of("QcSpecificationVersion:"+id));if(action.equals("RETIRE")){n.put("approvalSignatureId",id(v.getApprovalSignatureId()));evidence.add("Signature:"+v.getApprovalSignatureId());}return new SignableObject(type(action),id,v.getVersionNoBusiness(),n,evidence);}
 public void validateSigning(SignatureValidationContext c,SignableObject object,String action){long id=QcSpecificationRules.id(object.objectId());intent.require(c.platform(),id,action);if(!c.platform().hasPermission("qms:specification:"+(action.equals("APPROVE")?"approve":"retire"))||!c.platform().hasPermission("ebr:sign"))throw new PermissionException("PERMISSION_DENIED","QC command and signing permissions required");var v=db.version(c.platform().organizationId(),id,true);QcSpecificationRules.transition(v.getStatus(),action);validateVersion(v);if(action.equals("APPROVE"))independent(v,c.platform().actorId());else requireValid(v);}
 public void requireValid(SpecificationVersionEntity v){try{if(v.getContentHash()==null||!v.getContentHash().equals(contentHash(v))||v.getApprovalSignatureId()==null)throw invalidSignature();var s=signatures.find(v.getOrgId(),v.getApprovalSignatureId());if(s.status()!=SignatureStatus.VALID||s.meaning()!=SignatureMeaning.APPROVE||!s.objectType().equals("QcSpecificationVersion")||!s.objectId().equals(v.getId().toString())||s.signerId()!=v.getApprovedBy()||!s.recordDigest().equals(canonicalizer.digest(signable(v.getOrgId(),v.getId().toString(),"APPROVE"))))throw invalidSignature();}catch(NoSuchElementException e){throw invalidSignature();}}
 private com.hospital.mes.common.exception.ResourceConflictException invalidSignature(){return QcSpecificationRules.conflict("QC_SPEC_SIGNATURE_INVALID","QC specification approval signature or content is invalid");}
 public SpecificationSnapshot snapshot(SpecificationVersionEntity v){var r=db.root(v.getOrgId(),v.getSpecificationId());return new SpecificationSnapshot(r.getId(),r.getSpecificationCode(),r.getSpecificationName(),r.getMaterialId(),v.getId(),v.getVersionNoBusiness(),v.getContentHash(),v.getApprovalSignatureId(),v.getApprovedBy(),v.getApprovedAt().toInstant(ZoneOffset.UTC),db.items(v.getOrgId(),v.getId(),true).stream().map(i->new SpecificationItemSnapshot(i.getId(),i.getItemCode(),i.getItemName(),i.getRequired(),i.getResultType(),i.getLowerLimit(),i.getUpperLimit(),i.getUnitId(),i.getTextAcceptanceCriteria(),i.getMethodCode(),i.getMethodVersion())).toList());}
 public static String type(String action){return action.equals("APPROVE")?"QcSpecificationVersion":"QcSpecificationRetirement";}
 public static String id(Long id){return id==null?null:id.toString();}
 public static String decimal(java.math.BigDecimal value){return value==null?null:value.setScale(6).toPlainString();}
}
