package com.hospital.mes.qc.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.hospital.mes.audit.application.CurrentPlatformContext;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.audit.idempotency.PlatformIdempotencyService;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.masterdata.infrastructure.ScopedEntity;
import com.hospital.mes.qc.domain.*;
import com.hospital.mes.qc.infrastructure.*;
import org.springframework.stereotype.Service;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.dao.DuplicateKeyException;
import java.util.*;
import java.time.*;
import static com.hospital.mes.qc.domain.QcSpecificationRules.*;
@Service @ConditionalOnProperty(prefix="spring.datasource",name="url")
public class QcSpecificationService {
 private final QcStore db; private final QcDefinitions definitions; private final MasterMutation mutation; private final MaterialQueryService materials; private final ObjectMapper json; private final SignatureApplicationService signing; private final QcSigningIntent intent;
 public QcSpecificationService(QcStore db,QcDefinitions definitions,MasterMutation mutation,MaterialQueryService materials,ObjectMapper json,SignatureApplicationService signing,QcSigningIntent intent){this.db=db;this.definitions=definitions;this.mutation=mutation;this.materials=materials;this.json=json;this.signing=signing;this.intent=intent;}
 @Transactional(readOnly=true)
 public QcViews.Page<QcViews.SpecificationSummary> list(int page,int size,String keyword,String materialId,String status){var c=mutation.context("qms:specification:view");var result=db.list(c.organizationId(),page,size,keyword,materialId==null?null:id(materialId),status);return new QcViews.Page<>(result.items().stream().map(r->decode(rootNode(r,false),QcViews.SpecificationSummary.class)).toList(),result.total(),page,size);}
 @Transactional(readOnly=true)
 public QcViews.SpecificationDetail get(String id){var c=mutation.context("qms:specification:view");return decode(rootNode(db.root(c.organizationId(),id(id)),true),QcViews.SpecificationDetail.class);}
 @Transactional(readOnly=true)
 public QcViews.SpecificationVersionDetail getVersion(String id){var c=mutation.context("qms:specification:view");return decode(versionNode(db.version(c.organizationId(),id(id),false),true),QcViews.SpecificationVersionDetail.class);}
 @Transactional
 public QcViews.SpecificationDetail create(QcCommands.CreateSpecification request,String key){var c=mutation.context("qms:specification:create");if(request==null)throw invalid("Request required");long material=id(request.materialId());String code=text(request.specificationCode(),100),name=text(request.specificationName(),200),reason=text(request.reason(),1000);var body=new QcCommands.CreateSpecification(Long.toString(material),code,name,reason);try{return decode(mutation.execute(c,"QC_SPEC_CREATE",key,body,()->{try{materials.requireUsable(c.organizationId(),material,Instant.now());}catch(NoSuchElementException e){throw new QcNotFoundException();}var r=new SpecificationEntity();r.setMaterialId(material);r.setSpecificationCode(code);r.setSpecificationName(name);db.insertRoot(r,c.organizationId(),c.actorId());mutation.auditSnapshot(c,"QC_SPEC_CREATED","QcSpecification",r.getId(),null,rootNode(r,true),reason,key);return r;},r->rootNode((SpecificationEntity)r,true),201),QcViews.SpecificationDetail.class);}catch(DuplicateKeyException e){throw conflict("QC_SPEC_CODE_EXISTS","QC specification code already exists");}}
 @Transactional
 public QcViews.SpecificationVersionDetail createVersion(String rootId,QcCommands.CreateVersion request,String key){var c=mutation.context("qms:specification:create");long root=id(rootId);db.root(c.organizationId(),root);if(request==null||request.versionNoBusiness()==null||request.versionNoBusiness()<1)throw invalid("Positive business version required");String reason=text(request.reason(),1000);definitions.validate(c.organizationId(),request.items());try{return decode(mutation.execute(c,"QC_SPEC_VERSION_CREATE:"+root,key,request,()->{var v=new SpecificationVersionEntity();v.setSpecificationId(root);v.setVersionNoBusiness(request.versionNoBusiness());v.setStatus("DRAFT");db.insertVersion(v,c.organizationId(),c.actorId());replaceItems(v,request.items(),c.actorId());mutation.auditSnapshot(c,"QC_SPEC_VERSION_CREATED","QcSpecificationVersion",v.getId(),null,versionNode(v,true),reason,key);return v;},v->versionNode((SpecificationVersionEntity)v,true),201),QcViews.SpecificationVersionDetail.class);}catch(DuplicateKeyException e){throw conflict("QC_SPEC_VERSION_EXISTS","QC business version or item code already exists");}}
 @Transactional
 public QcViews.SpecificationVersionDetail editVersion(String versionId,QcCommands.EditVersion request,String header,String key){var c=mutation.context("qms:specification:edit");long version=id(versionId);db.version(c.organizationId(),version,false);if(request==null)throw invalid("Request required");long expected=expected(header,request.versionNo());String reason=text(request.reason(),1000);definitions.validate(c.organizationId(),request.items());return decode(mutation.execute(c,"QC_SPEC_VERSION_EDIT:"+version,key,Map.of("id",versionId,"version",expected,"items",request.items(),"reason",reason),()->{var v=locked(c,version,expected);requireDraft(v.getStatus());var before=versionNode(v,true);replaceItems(v,request.items(),c.actorId());db.updateVersion(v,expected,"DRAFT",c.actorId());mutation.auditSnapshot(c,"QC_SPEC_VERSION_EDITED","QcSpecificationVersion",v.getId(),before,versionNode(v,true),reason,key);return v;},v->versionNode((SpecificationVersionEntity)v,true),200),QcViews.SpecificationVersionDetail.class);}
 @Transactional
 public QcViews.SpecificationVersionDetail approveVersion(String id,QcCommands.SignVersion request,String header,String key){return sign(id,request,header,key,"APPROVE");}
 @Transactional
 public QcViews.SpecificationVersionDetail retireVersion(String id,QcCommands.SignVersion request,String header,String key){return sign(id,request,header,key,"RETIRE");}
 private QcViews.SpecificationVersionDetail sign(String versionId,QcCommands.SignVersion request,String header,String key,String action){String permission=action.equals("APPROVE")?"approve":"retire";var c=mutation.context("qms:specification:"+permission);mutation.context("ebr:sign");long version=id(versionId);db.version(c.organizationId(),version,false);if(request==null)throw invalid("Request required");long expected=expected(header,request.versionNo());String reason=text(request.reason(),1000);return decode(mutation.execute(c,"QC_SPEC_VERSION_"+action+":"+version,key,Map.of("id",versionId,"version",expected,"reason",reason),()->{var v=locked(c,version,expected);String previous=v.getStatus();String next=transition(previous,action);definitions.validateVersion(v);if(action.equals("APPROVE"))definitions.independent(v,c.actorId());else definitions.requireValid(v);var before=versionNode(v,true);var signature=intent.execute(c,version,action,reason,()->signing.sign(new SignCommand(c,QcDefinitions.type(action),versionId,SignatureMeaning.APPROVE,v.getVersionNoBusiness(),request.reauthToken(),PlatformIdempotencyService.digest(key+":"+action+":sign"),null)));if(action.equals("APPROVE")){v.setContentHash(definitions.contentHash(v));v.setApprovedBy(c.actorId());v.setApprovedAt(LocalDateTime.ofInstant(signature.signedAt(),ZoneOffset.UTC));v.setApprovalSignatureId(id(signature.id()));v.setApprovalReason(reason);}else{v.setRetiredBy(c.actorId());v.setRetiredAt(LocalDateTime.ofInstant(signature.signedAt(),ZoneOffset.UTC));v.setRetirementSignatureId(id(signature.id()));v.setRetirementReason(reason);}v.setStatus(next);db.updateVersion(v,expected,previous,c.actorId());mutation.auditSnapshot(c,"QC_SPEC_VERSION_"+(action.equals("APPROVE")?"APPROVED":"RETIRED"),"QcSpecificationVersion",v.getId(),before,versionNode(v,true),reason,key);return v;},v->versionNode((SpecificationVersionEntity)v,true),200),QcViews.SpecificationVersionDetail.class);}
 private SpecificationVersionEntity locked(CurrentPlatformContext c,long id,long expected){var v=db.version(c.organizationId(),id,true);if(v.getVersionNo()!=expected)throw conflict("RECORD_CHANGED","QC record changed; reload before retrying");return v;}
 private void replaceItems(SpecificationVersionEntity v,List<QcCommands.Item> wanted,long actor){var old=db.items(v.getOrgId(),v.getId(),false);Map<String,SpecificationItemEntity> existing=new HashMap<>();for(var e:old)existing.put(e.getItemCode().toUpperCase(Locale.ROOT),e);Set<Long> retained=new HashSet<>();for(var line:wanted){String code=text(line.itemCode(),100);var e=existing.get(code.toUpperCase(Locale.ROOT));boolean fresh=e==null;if(fresh){e=new SpecificationItemEntity();e.setSpecificationVersionId(v.getId());e.setItemCode(code);}e.setItemName(text(line.itemName(),200));e.setRequired(line.required());e.setResultType(line.resultType());e.setLowerLimit(decimal(line.lowerLimit()));e.setUpperLimit(decimal(line.upperLimit()));e.setUnitId(line.unitId()==null?null:id(line.unitId()));e.setTextAcceptanceCriteria(line.textAcceptanceCriteria()==null?null:text(line.textAcceptanceCriteria(),1000));e.setMethodCode(text(line.methodCode(),100));e.setMethodVersion(text(line.methodVersion(),50));e.setActive(true);if(fresh)db.insertItem(e,v.getOrgId(),actor);else db.updateItem(e,actor);retained.add(e.getId());}for(var e:old)if(!retained.contains(e.getId())&&Boolean.TRUE.equals(e.getActive())){e.setActive(false);db.updateItem(e,actor);}}
 private ObjectNode base(ScopedEntity e){var n=json.createObjectNode();n.put("id",e.getId().toString());n.put("orgId",e.getOrgId().toString());n.put("createdBy",e.getCreatedBy().toString());n.put("createdAt",time(e.getCreatedAt()));n.put("updatedBy",e.getUpdatedBy().toString());n.put("updatedAt",time(e.getUpdatedAt()));n.put("versionNo",e.getVersionNo());return n;}
 private ObjectNode rootNode(SpecificationEntity r,boolean versions){var n=base(r);n.put("materialId",r.getMaterialId().toString());n.put("specificationCode",r.getSpecificationCode());n.put("specificationName",r.getSpecificationName());materialDisplay(n,r.getOrgId(),r.getMaterialId());if(versions){var a=n.putArray("versions");db.versions(r.getOrgId(),r.getId()).forEach(v->a.add(versionNode(v,false)));}return n;}
 private ObjectNode versionNode(SpecificationVersionEntity v,boolean detail){var n=base(v);n.put("specificationId",v.getSpecificationId().toString());n.put("versionNoBusiness",v.getVersionNoBusiness());n.put("status",v.getStatus());n.put("contentHash",v.getContentHash());n.put("approvedBy",QcDefinitions.id(v.getApprovedBy()));n.put("approvedAt",time(v.getApprovedAt()));n.put("approvalSignatureId",QcDefinitions.id(v.getApprovalSignatureId()));n.put("approvalReason",v.getApprovalReason());n.put("retiredBy",QcDefinitions.id(v.getRetiredBy()));n.put("retiredAt",time(v.getRetiredAt()));n.put("retirementSignatureId",QcDefinitions.id(v.getRetirementSignatureId()));n.put("retirementReason",v.getRetirementReason());if(detail){var r=db.root(v.getOrgId(),v.getSpecificationId());n.put("specificationCode",r.getSpecificationCode());n.put("specificationName",r.getSpecificationName());n.put("materialId",r.getMaterialId().toString());materialDisplay(n,r.getOrgId(),r.getMaterialId());var a=n.putArray("items");db.items(v.getOrgId(),v.getId(),true).forEach(i->a.add(definitions.itemNode(i)));}return n;}
 private void materialDisplay(ObjectNode n,long org,long material){try{var m=materials.snapshot(org,material);n.put("materialCode",m.path("materialCode").asText());n.put("materialName",m.path("materialName").asText());}catch(NoSuchElementException e){throw new QcNotFoundException();}}
 private static String time(LocalDateTime t){return t==null?null:t.toInstant(ZoneOffset.UTC).toString();}
 private <T>T decode(JsonNode n,Class<T> type){return json.convertValue(n,type);}
}
