package com.hospital.mes.execution.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.hospital.mes.execution.infrastructure.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.audit.signature.SignatureMeaning;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import static com.hospital.mes.production.application.ProductionInput.*;
import static com.hospital.mes.production.domain.ProductionRules.*;
@org.springframework.stereotype.Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class ClearanceService {
 private final ExecutionStore db;private final QualityOperationQueryService operations;private final ClearanceRecordMapper records;private final ClearanceReviewMapper reviews;private final MasterMutation mutations;private final SignedRecordSupport signing;private final ObjectMapper json;
 public ClearanceService(ExecutionStore db,QualityOperationQueryService operations,ClearanceRecordMapper records,ClearanceReviewMapper reviews,MasterMutation mutations,SignedRecordSupport signing,ObjectMapper json){this.db=db;this.operations=operations;this.records=records;this.reviews=reviews;this.mutations=mutations;this.signing=signing;this.json=json;}
 private List<ClearanceRecordEntity> rows(long org,long operation,boolean current){var q=new QueryWrapper<ClearanceRecordEntity>().eq("org_id",org).eq("operation_execution_id",operation).orderByAsc("id");if(current)q.last("FOR UPDATE");return records.selectList(q);}
 private ClearanceReviewEntity reviewOf(long org,long record,boolean current){var q=new QueryWrapper<ClearanceReviewEntity>().eq("org_id",org).eq("clearance_record_id",record);if(current)q.last("FOR UPDATE");return reviews.selectOne(q);}
 public JsonNode history(long org,long operation){operations.get(org,operation);var a=json.createArrayNode();for(var row:rows(org,operation,false)){var n=SignedRecordSupport.publicView(row,json);n.remove(List.of("signatureEvidenceJson","versionNo","updatedBy","updatedAt"));var review=reviewOf(org,row.getId(),false);if(review!=null){var v=SignedRecordSupport.publicView(review,json);v.remove(List.of("signatureEvidenceJson","versionNo","updatedBy","updatedAt"));n.set("review",v);}a.add(n);}return a;}
 private List<EquipmentUsageEntity> usages(long org,long op){return db.equipmentUsageMapper.selectList(new QueryWrapper<EquipmentUsageEntity>().eq("org_id",org).eq("operation_execution_id",op).orderByAsc("id").last("FOR UPDATE"));}
 public void requirePassed(long org,long op){var history=rows(org,op,true);var usages=usages(org,op);List<Long> scopes=new ArrayList<>();if(usages.isEmpty())scopes.add(null);else usages.forEach(x->scopes.add(x.getId()));for(Long scope:scopes){var current=history.stream().filter(x->Objects.equals(x.getEquipmentUsageId(),scope)).reduce((a,b)->b).orElse(null);gate(current!=null,"PRECONDITION_FAILED","Required clearance record absent");var review=reviewOf(org,current.getId(),true);gate("PASS".equals(current.getOutcome())&&review!=null&&"APPROVED".equals(review.getDecision())&&signing.valid(org,current.getSignatureId())&&signing.valid(org,review.getSignatureId()),"PRECONDITION_FAILED","Current clearance must pass independent signed review");}}
 private void mutable(OperationEntity op){gate(Set.of("PENDING","READY","PAUSED").contains(op.getStatus()),"CLEARANCE_OPERATION_NOT_MUTABLE","Record clearance before running");}
 @Transactional public JsonNode record(String target,JsonNode body,String header,String key){fields(body,"versionNo","equipmentUsageId","previousRecordId","outcome","reason","signature");var c=mutations.context("mes:clearance:record");long expected=SignedRecordSupport.expected(body,header);return mutations.execute(c,"Clearance:RECORD:"+target,key,Map.of("target",target,"body",body),()->{
  var locked=operations.lock(c.organizationId(),MasterMutation.id(target));var op=locked.operation();version(op.getVersionNo(),expected);mutable(op);gate(locked.definition().path("clearanceRequired").asBoolean(),"CLEARANCE_NOT_REQUIRED","Frozen definition does not require clearance");
  Long usage=optionalId(body,"equipmentUsageId");var bindings=usages(c.organizationId(),op.getId());gate(bindings.isEmpty()?usage==null:bindings.stream().anyMatch(x->x.getId().equals(usage)),"CLEARANCE_SCOPE_MISMATCH","Clearance must name a current equipment binding");
  var previous=rows(c.organizationId(),op.getId(),true).stream().filter(x->Objects.equals(x.getEquipmentUsageId(),usage)).reduce((a,b)->b).orElse(null);gate(Objects.equals(previous==null?null:previous.getId(),optionalId(body,"previousRecordId")),"CLEARANCE_PREDECESSOR_CONFLICT","Exact current predecessor required");String outcome=text(body,"outcome",10);gate(Set.of("PASS","FAIL").contains(outcome),"CLEARANCE_OUTCOME_INVALID","PASS/FAIL required");
  var row=new ClearanceRecordEntity();row.setOperationExecutionId(op.getId());row.setEquipmentUsageId(usage);row.setPreviousRecordId(previous==null?null:previous.getId());row.setOutcome(outcome);row.setReason(text(body,"reason",1000));row.setPerformedBy(c.actorId());row.setPerformedAt(now());var evidence=signing.sign(c,"CLEARANCE_RECORD",target+":"+expected,expected,SignatureMeaning.VERIFY,row,body.get("signature"),key,List.of("OperationExecution:"+target));row.setSignatureId(evidence.id());row.setSignatureEvidenceJson(evidence.envelope());new ScopedStore<>(records,List.of(),Map.of()).insert(row,c.organizationId(),c.actorId());
  if(usage!=null){var binding=bindings.stream().filter(x->x.getId().equals(usage)).findFirst().orElseThrow();binding.setClearanceStatus("PENDING_REVIEW");db.equipmentUsages.update(binding,binding.getVersionNo(),c.actorId(),List.of("clearanceStatus"));}
  db.operations.update(op,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"CLEARANCE_RECORD","ClearanceRecord",row.getId(),null,mutations.view(row),row.getReason(),key);return op;
 },row->summary((OperationEntity)row),200);}
 @Transactional public JsonNode review(String target,JsonNode body,String header,String key){fields(body,"versionNo","clearanceRecordId","decision","reason","signature");var c=mutations.context("mes:clearance:review");long expected=SignedRecordSupport.expected(body,header);return mutations.execute(c,"Clearance:REVIEW:"+target,key,Map.of("target",target,"body",body),()->{
  var op=operations.lock(c.organizationId(),MasterMutation.id(target)).operation();version(op.getVersionNo(),expected);mutable(op);long recordId=id(body,"clearanceRecordId");var record=rows(c.organizationId(),op.getId(),true).stream().filter(x->x.getId()==recordId).findFirst().orElseThrow();var current=rows(c.organizationId(),op.getId(),true).stream().filter(x->Objects.equals(x.getEquipmentUsageId(),record.getEquipmentUsageId())).reduce((a,b)->b).orElseThrow();gate(current.getId().equals(record.getId()),"CLEARANCE_PREDECESSOR_CONFLICT","Only current record can be reviewed");gate(record.getPerformedBy()!=c.actorId(),"INDEPENDENT_REVIEW_REQUIRED","Recorder cannot review");gate(reviewOf(c.organizationId(),recordId,true)==null,"CLEARANCE_ALREADY_REVIEWED","Review is immutable");gate(signing.valid(c.organizationId(),record.getSignatureId()),"CLEARANCE_SIGNATURE_INVALID","Original signature invalid");String decision=text(body,"decision",20);gate(Set.of("APPROVED","REJECTED").contains(decision),"CLEARANCE_REVIEW_INVALID","Review decision invalid");gate(!decision.equals("APPROVED")||record.getOutcome().equals("PASS"),"CLEARANCE_FAILED","Failed clearance cannot be approved");
  var review=new ClearanceReviewEntity();review.setClearanceRecordId(recordId);review.setDecision(decision);review.setReason(text(body,"reason",1000));review.setReviewedBy(c.actorId());review.setReviewedAt(now());var evidence=signing.sign(c,"CLEARANCE_REVIEW",target+":"+expected,expected,SignatureMeaning.APPROVE,review,body.get("signature"),key,List.of("ClearanceRecord:"+recordId));review.setSignatureId(evidence.id());review.setSignatureEvidenceJson(evidence.envelope());new ScopedStore<>(reviews,List.of(),Map.of()).insert(review,c.organizationId(),c.actorId());
  if(record.getEquipmentUsageId()!=null){var binding=db.equipmentUsages.lock(c.organizationId(),record.getEquipmentUsageId());binding.setClearanceStatus(decision.equals("APPROVED")?"PASSED":"FAILED");db.equipmentUsages.update(binding,binding.getVersionNo(),c.actorId(),List.of("clearanceStatus"));}db.operations.update(op,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"CLEARANCE_REVIEW","ClearanceReview",review.getId(),null,mutations.view(review),review.getReason(),key);return op;
 },row->summary((OperationEntity)row),200);}
 private JsonNode summary(OperationEntity op){var n=SignedRecordSupport.publicView(op,json);n.set("clearanceRecords",history(op.getOrgId(),op.getId()));return n;}
}
