package com.hospital.mes.execution.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.hospital.mes.execution.infrastructure.*;
import com.hospital.mes.execution.domain.ExecutionRules;
import com.hospital.mes.production.application.*;
import com.hospital.mes.production.domain.ProductionEvents;
import com.hospital.mes.production.domain.ProductionRules;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.masterdata.infrastructure.ScopedEntity;
import com.hospital.mes.equipment.application.EquipmentQueryService;
import com.hospital.mes.audit.application.CurrentPlatformContext;
import com.hospital.mes.common.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.context.event.EventListener;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import static com.hospital.mes.production.application.ProductionInput.*;
import static com.hospital.mes.production.domain.ProductionRules.gate;
@org.springframework.stereotype.Service
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class ExecutionService {
 @org.springframework.beans.factory.annotation.Autowired private ClearanceService clearance;
 @org.springframework.beans.factory.annotation.Autowired private com.hospital.mes.audit.application.CurrentPlatformContextResolver currentContext;
 @org.springframework.beans.factory.annotation.Autowired private ObjectProvider<ExecutionQualityPort> quality;
 private final ExecutionStore db;private final ProductionQueryService production;private final ExecutionUnitCommands unitCommands;private final MasterMutation mutations;private final ProductionViews views;private final ObjectMapper json;private final EquipmentQueryService equipment;private final MasterQueryService units;private final QualificationGate qualifications;private final ObjectProvider<ExecutionRuntimePort> runtime;private final ObjectProvider<ExecutionMaterialPort> material;
 public ExecutionService(ExecutionStore db,ProductionQueryService production,ExecutionUnitCommands unitCommands,MasterMutation mutations,ProductionViews views,ObjectMapper json,EquipmentQueryService equipment,MasterQueryService units,QualificationGate qualifications,ObjectProvider<ExecutionRuntimePort> runtime,ObjectProvider<ExecutionMaterialPort> material){this.db=db;this.production=production;this.unitCommands=unitCommands;this.mutations=mutations;this.views=views;this.json=json;this.equipment=equipment;this.units=units;this.qualifications=qualifications;this.runtime=runtime;this.material=material;}
 @EventListener @org.springframework.core.annotation.Order(0) @Transactional(propagation=org.springframework.transaction.annotation.Propagation.MANDATORY)
 public void initialize(ProductionEvents.BatchReleased event){for(long unitId:event.executionUnitIds()){var context=production.execution(event.organizationId(),unitId);for(var def:context.snapshot().path("process").path("route").path("operations")){var row=new OperationEntity();row.setExecutionUnitId(unitId);row.setOperationDefId(id(def,"operationDefId"));row.setOperationSeq(def.path("sequenceNo").intValue());row.setStatus(def.path("predecessorCodes").isEmpty()?"READY":"PENDING");row.setGateEvidenceJson("[]");db.operations.insert(row,event.organizationId(),event.actorId());runtime().initializeOperation(event.organizationId(),event.actorId(),event.mainBatchId(),unitId,row.getId(),row.getOperationDefId(),context.snapshot());quality.getObject().initialize(event.organizationId(),event.actorId(),row.getId(),def);}}}
 public List<JsonNode> operations(String unit){var c=mutations.context("mes:operation:view");production.execution(c.organizationId(),MasterMutation.id(unit));return rows(c.organizationId(),MasterMutation.id(unit)).stream().map(x->(JsonNode)view(x)).toList();}
 public List<OperationEntity> rows(long org,long unit){return db.operationMapper.selectList(new QueryWrapper<OperationEntity>().eq("org_id",org).eq("execution_unit_id",unit).orderByAsc("operation_seq","id"));}
 public JsonNode operation(long org,long id){return view(db.operations.get(org,id));}
 public void requireInitialized(long org,long unit){var context=production.execution(org,unit);gate(rows(org,unit).size()==context.snapshot().path("process").path("route").path("operations").size(),"DEPENDENCY_NOT_READY","Operation initialization incomplete");}
 @Transactional public JsonNode start(String id,JsonNode body,String header,String key){return action(id,body,header,key,"START","mes:operation:start");}
 @Transactional public JsonNode pause(String id,JsonNode body,String header,String key){return action(id,body,header,key,"PAUSE","mes:operation:pause");}
 @Transactional public JsonNode resume(String id,JsonNode body,String header,String key){return action(id,body,header,key,"RESUME","mes:operation:start");}
 @Transactional public JsonNode complete(String id,JsonNode body,String header,String key){return action(id,body,header,key,"COMPLETE","mes:operation:complete");}
 private JsonNode action(String id,JsonNode body,String header,String key,String action,String permission){fields(body,"versionNo","reason","reauthToken");var c=mutations.context(permission);long expected=version(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"Operation:"+action+":"+id,key,Map.of("id",id,"version",expected,"reason",reason),()->{var found=db.operations.get(c.organizationId(),MasterMutation.id(id));var context=production.lockExecution(c.organizationId(),found.getExecutionUnitId());var row=db.operations.lock(c.organizationId(),found.getId());ProductionRules.version(row.getVersionNo(),expected);gate("IN_PROGRESS".equals(context.batchStatus()),"PRECONDITION_FAILED","MainBatch must be in progress");var before=view(row);var def=definition(context.snapshot(),row.getOperationDefId());String next=switch(action){case "START"->ExecutionRules.start(row.getStatus());case "PAUSE"->ExecutionRules.pause(row.getStatus());case "RESUME"->ExecutionRules.resume(row.getStatus());case "COMPLETE"->ExecutionRules.complete(row.getStatus());default->throw new IllegalArgumentException("Unknown operation command");};
  if(action.equals("START")||action.equals("RESUME")){var at=Instant.now();startGates(c,row,def,context,at);var evidence=qualifications.evidence(c,action.equals("START")?"operation-start":"operation-resume",at);row.setGateEvidenceJson(appendEvidence(row.getGateEvidenceJson(),evidence));openRuns(c,row,key);if(row.getStartedAt()==null)row.setStartedAt(now());row.setOperatorId(c.actorId());unitCommands.operationStarted(c,row.getExecutionUnitId(),reason,key);}
  if(action.equals("COMPLETE")){quality.getObject().requireComplete(c.organizationId(),row.getId(),def);runtime().requireOperationComplete(c.organizationId(),row.getId());gate(completion(c.organizationId(),row,def.path("completionRule"),def),"PRECONDITION_FAILED","Frozen completion rule not satisfied");row.setCompletedAt(now());closeRuns(c,row,key);}
  if(action.equals("PAUSE"))closeRuns(c,row,key);
  row.setStatus(next);db.operations.update(row,expected,c.actorId(),List.of("status","startedAt","completedAt","operatorId","gateEvidenceJson"));
  if(action.equals("COMPLETE")){promoteSuccessors(c,row,context.snapshot(),reason,key);if(rows(c.organizationId(),row.getExecutionUnitId()).stream().allMatch(x->"COMPLETED".equals(x.getStatus())))unitCommands.allOperationsCompleted(c,row.getExecutionUnitId(),reason,key);}
  if(action.equals("PAUSE")&&rows(c.organizationId(),row.getExecutionUnitId()).stream().noneMatch(x->"IN_PROGRESS".equals(x.getStatus())))unitCommands.runningOperationsPaused(c,row.getExecutionUnitId(),reason,key);
  mutations.auditSnapshot(c,"Operation:"+action,"OperationExecution",row.getId(),before,view(row),reason,key);return row;},this::view,200);}
 private void startGates(CurrentPlatformContext c,OperationEntity row,JsonNode def,ProductionQueryService.ExecutionContext context,Instant at){String role=def.path("requiredRole").asText("");gate(role.isBlank()||c.roleCodes().contains(role),"QUALIFICATION_REQUIRED","Required operation role absent");gate(predecessorsComplete(c.organizationId(),row.getExecutionUnitId(),def,context.snapshot()),"PRECONDITION_FAILED","Predecessors incomplete");if(def.path("clearanceRequired").asBoolean())clearance.requirePassed(c.organizationId(),row.getId());var usages=usages(c.organizationId(),row.getId());String type=def.path("requiredEquipmentType").asText("");gate(type.isBlank()||!usages.isEmpty(),"PRECONDITION_FAILED","Equipment binding required");for(var usage:usages){var e=equipment.requireUsable(c.organizationId(),usage.getEquipmentId(),at);gate(type.isBlank()||type.equals(e.type()),"PRECONDITION_FAILED","Wrong equipment type");}materials().requireOperationMaterials(c.organizationId(),context.mainBatchId());}
 private boolean predecessorsComplete(long org,long unit,JsonNode def,JsonNode snapshot){var completed=new HashSet<String>();for(var row:rows(org,unit))if("COMPLETED".equals(row.getStatus()))completed.add(definition(snapshot,row.getOperationDefId()).path("operationCode").asText());for(var predecessor:def.path("predecessorCodes"))if(!completed.contains(predecessor.asText()))return false;return true;}
 private void promoteSuccessors(CurrentPlatformContext c,OperationEntity completed,JsonNode snapshot,String reason,String key){for(var successor:rows(c.organizationId(),completed.getExecutionUnitId()))if("PENDING".equals(successor.getStatus())&&predecessorsComplete(c.organizationId(),successor.getExecutionUnitId(),definition(snapshot,successor.getOperationDefId()),snapshot)){var before=view(successor);successor.setStatus("READY");db.operations.update(successor,successor.getVersionNo(),c.actorId(),List.of("status"));mutations.auditSnapshot(c,"Operation:PREREQUISITES_COMPLETED","OperationExecution",successor.getId(),before,view(successor),reason,key);}}
 private boolean completion(long org,OperationEntity row,JsonNode rule,JsonNode def){if(rule.isMissingNode()||rule.isNull())return parametersComplete(org,row,def);return switch(rule.path("kind").asText()){case "PARAMETERS_WITHIN_LIMITS"->parametersComplete(org,row,def);case "EBR_COMPLETE"->{runtime().requireOperationComplete(org,row.getId());yield true;}case "REVIEW_COMPLETE"->{runtime().requireOperationReview(org,row.getId());yield true;}case "ALL"->{boolean all=true;for(var child:rule.path("rules"))all&=completion(org,row,child,def);yield all;}case "ANY"->{boolean any=false;for(var child:rule.path("rules")){try{any|=completion(org,row,child,def);}catch(ComplianceException ignored){}}yield any;}default->false;};}
 private boolean parametersComplete(long org,OperationEntity row,JsonNode def){for(var parameter:def.path("parameters")){var values=db.parameterValueMapper.selectList(new QueryWrapper<ParameterValueEntity>().eq("org_id",org).eq("operation_execution_id",row.getId()).eq("parameter_def_id",id(parameter,"parameterDefId")).orderByDesc("captured_at","id").last("LIMIT 1"));if(values.isEmpty())return false;var value=values.getFirst();if(parameter.hasNonNull("lowerLimit")||parameter.hasNonNull("upperLimit")){if(value.getRawValue()==null)return false;BigDecimal normalized=value.getRawValue();if(parameter.hasNonNull("unitId")){if(value.getUnitId()==null)return false;normalized=exact(units,org,value.getUnitId(),id(parameter,"unitId"),null,normalized);}if(parameter.hasNonNull("lowerLimit")&&normalized.compareTo(new BigDecimal(parameter.get("lowerLimit").asText()))<0)return false;if(parameter.hasNonNull("upperLimit")&&normalized.compareTo(new BigDecimal(parameter.get("upperLimit").asText()))>0)return false;}}return true;}
 @Transactional public JsonNode bindEquipment(String id,JsonNode body,String header,String key){fields(body,"equipmentId","usageRole","versionNo","reason");var c=mutations.context("mes:equipment:bind");long expected=version(body,header);String why=text(body,"reason",1000);return mutations.execute(c,"Operation:BIND:"+id,key,Map.of("id",id,"version",expected,"body",body),()->{var found=db.operations.get(c.organizationId(),MasterMutation.id(id));var context=production.lockExecution(c.organizationId(),found.getExecutionUnitId());var op=db.operations.lock(c.organizationId(),found.getId());ProductionRules.version(op.getVersionNo(),expected);gate(Set.of("PENDING","READY","PAUSED").contains(op.getStatus()),"INVALID_OPERATION_STATE","Bind equipment before running");var def=definition(context.snapshot(),op.getOperationDefId());var e=equipment.requireUsable(c.organizationId(),id(body,"equipmentId"),Instant.now());String type=def.path("requiredEquipmentType").asText("");gate(type.isBlank()||type.equals(e.type()),"PRECONDITION_FAILED","Wrong equipment type");var before=view(op);var row=new EquipmentUsageEntity();row.setExecutionUnitId(op.getExecutionUnitId());row.setOperationExecutionId(op.getId());row.setEquipmentId(MasterMutation.id(e.id()));row.setUsageRole(text(body,"usageRole",50));row.setBoundAt(now());db.equipmentUsages.insert(row,c.organizationId(),c.actorId());db.operations.update(op,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"Operation:BIND","OperationExecution",op.getId(),before,view(op),why,key);return row;},this::view,200);}
 @Transactional public JsonNode recordParameter(String id,JsonNode body,String header,String key){return parameter(id,body,header,key,false);}
 /** Only a trusted server-side device inbox adapter may call this application entry. */
 @Transactional public JsonNode recordDeviceParameter(String id,JsonNode body,String header,String key){return parameter(id,body,header,key,true);}
 private JsonNode parameter(String id,JsonNode body,String header,String key,boolean trustedDevice){fields(body,"parameterDefId","sourceMode","rawValue","textValue","unitId","equipmentId","sourceMessageId","capturedAt","versionNo","reason");var c=mutations.context("mes:param:record");long expected=version(body,header);String why=text(body,"reason",1000);return mutations.execute(c,"Operation:PARAMETER:"+id,key,Map.of("id",id,"version",expected,"body",body),()->{var found=db.operations.get(c.organizationId(),MasterMutation.id(id));var context=production.lockExecution(c.organizationId(),found.getExecutionUnitId());var op=db.operations.lock(c.organizationId(),found.getId());var def=definition(context.snapshot(),op.getOperationDefId());JsonNode parameter=null;for(var p:def.path("parameters"))if(p.path("parameterDefId").asText().equals(text(body,"parameterDefId",30)))parameter=p;gate(parameter!=null,"PARAMETER_NOT_IN_OPERATION","Parameter not in frozen operation");String source=text(body,"sourceMode",30);gate(Set.of("MANUAL","DEVICE").contains(source),"INVALID_PARAMETER_SOURCE","Unknown source");if(source.equals("DEVICE")&&!trustedDevice)throw new PermissionException("PERMISSION_DENIED","Device evidence requires trusted inbox adapter");String mode=parameter.path("acquisitionMode").asText();gate(mode.equals("HYBRID")||mode.equals("MANUAL")&&source.equals("MANUAL")||mode.equals("AUTO")&&source.equals("DEVICE"),"INVALID_PARAMETER_SOURCE","Source does not match frozen acquisition mode");
  var row=new ParameterValueEntity();row.setOperationExecutionId(op.getId());row.setParameterDefId(id(body,"parameterDefId"));row.setSourceMode(source);boolean raw=body.hasNonNull("rawValue"),txt=body.hasNonNull("textValue");gate(raw!=txt,"PARAMETER_VALUE_REQUIRED","Exactly one numeric or text value required");if(raw){String value=text(body,"rawValue",50);gate(value.matches("-?[0-9]+(\\.[0-9]{1,8})?"),"PARAMETER_VALUE_INVALID","DECIMAL(24,8) required");var decimal=new BigDecimal(value);gate(decimal.precision()-decimal.scale()<=16,"PARAMETER_VALUE_INVALID","Numeric range exceeded");row.setRawValue(decimal);}else row.setTextValue(text(body,"textValue",1000));row.setUnitId(optionalId(body,"unitId"));if(parameter.hasNonNull("unitId")){gate(row.getUnitId()!=null,"UNIT_REQUIRED","Parameter unit required");if(raw)exact(units,c.organizationId(),row.getUnitId(),id(parameter,"unitId"),null,row.getRawValue());}else gate(row.getUnitId()==null,"UNIT_MISMATCH","Unitless parameter cannot receive a unit");
  if(source.equals("DEVICE")){row.setEquipmentId(id(body,"equipmentId"));gate(usages(c.organizationId(),op.getId()).stream().anyMatch(x->x.getEquipmentId().equals(row.getEquipmentId())),"PRECONDITION_FAILED","Device not bound to operation");equipment.requireUsable(c.organizationId(),row.getEquipmentId(),Instant.now());row.setSourceMessageId(text(body,"sourceMessageId",100));var captured=Instant.parse(text(body,"capturedAt",50));gate(captured.getNano()%1000000==0,"PARAMETER_TIME_PRECISION","Captured timestamp supports milliseconds");row.setCapturedAt(LocalDateTime.ofInstant(captured,ZoneOffset.UTC));var existing=db.parameterValueMapper.selectOne(new QueryWrapper<ParameterValueEntity>().eq("org_id",c.organizationId()).eq("equipment_id",row.getEquipmentId()).eq("parameter_def_id",row.getParameterDefId()).eq("source_message_id",row.getSourceMessageId()));if(existing!=null){if(!sameValue(existing,row))throw new ResourceConflictException("DEVICE_MESSAGE_CONFLICT","Message identity reused with different evidence");return existing;}}else{gate(!body.hasNonNull("equipmentId")&&!body.hasNonNull("sourceMessageId")&&!body.hasNonNull("capturedAt"),"INVALID_PARAMETER_SOURCE","Manual source identity/time is server-owned");row.setCapturedAt(now());}
  ProductionRules.version(op.getVersionNo(),expected);gate("IN_PROGRESS".equals(op.getStatus()),"INVALID_OPERATION_STATE","Operation must be running");var before=view(op);db.parameterValues.insert(row,c.organizationId(),c.actorId());db.operations.update(op,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"Operation:PARAMETER","OperationExecution",op.getId(),before,view(op),why,key);return row;},this::view,200);}
 private boolean sameValue(ParameterValueEntity a,ParameterValueEntity b){return Objects.equals(a.getOperationExecutionId(),b.getOperationExecutionId())&&Objects.equals(a.getTextValue(),b.getTextValue())&&(a.getRawValue()==null?b.getRawValue()==null:b.getRawValue()!=null&&a.getRawValue().compareTo(b.getRawValue())==0)&&Objects.equals(a.getUnitId(),b.getUnitId())&&Objects.equals(a.getCapturedAt(),b.getCapturedAt());}
 private List<EquipmentUsageEntity> usages(long org,long operation){return db.equipmentUsageMapper.selectList(new QueryWrapper<EquipmentUsageEntity>().eq("org_id",org).eq("operation_execution_id",operation).orderByAsc("id"));}
 private void openRuns(CurrentPlatformContext c,OperationEntity operation,String key){for(var usage:usages(c.organizationId(),operation.getId())){var run=new EquipmentRunEntity();run.setEquipmentUsageId(usage.getId());run.setRunNo(operation.getId()+":"+usage.getId()+":"+UUID.randomUUID());run.setStatus("RUNNING");run.setStartedAt(now());db.equipmentRuns.insert(run,c.organizationId(),c.actorId());mutations.auditSnapshot(c,"EquipmentRun:START","EquipmentRun",run.getId(),null,view(run),"Operation start/resume",key);}}
 private void closeRuns(CurrentPlatformContext c,OperationEntity operation,String key){for(var usage:usages(c.organizationId(),operation.getId()))for(var run:db.equipmentRunMapper.selectList(new QueryWrapper<EquipmentRunEntity>().eq("org_id",c.organizationId()).eq("equipment_usage_id",usage.getId()).eq("status","RUNNING").last("FOR UPDATE"))){var before=view(run);run.setStatus("ENDED");run.setEndedAt(now());db.equipmentRuns.update(run,run.getVersionNo(),c.actorId(),List.of("status","endedAt"));mutations.auditSnapshot(c,"EquipmentRun:END","EquipmentRun",run.getId(),before,view(run),"Operation pause/complete",key);}}
 public JsonNode definition(JsonNode snapshot,long definition){for(var d:snapshot.path("process").path("route").path("operations"))if(d.path("operationDefId").asText().equals(Long.toString(definition)))return d;throw new ComplianceException("PRECONDITION_FAILED","Operation missing from immutable snapshot");}
 private String appendEvidence(String current,JsonNode evidence){try{var a=(ArrayNode)json.readTree(current);a.add(evidence);return a.toString();}catch(java.io.IOException ex){throw new IllegalStateException(ex);}}
 private ExecutionRuntimePort runtime(){var p=runtime.getIfAvailable();if(p==null)throw new ComplianceException("DEPENDENCY_NOT_READY","Actual eBR runtime unavailable");return p;}
 private ExecutionMaterialPort materials(){var p=material.getIfAvailable();if(p==null)throw new ComplianceException("DEPENDENCY_NOT_READY","Actual material gate unavailable");return p;}
 public JsonNode view(ScopedEntity row){var out=views.view(row);if(row instanceof OperationEntity op){out.put("clearanceRequired",definition(production.execution(op.getOrgId(),op.getExecutionUnitId()).snapshot(),op.getOperationDefId()).path("clearanceRequired").asBoolean());out.set("clearanceRecords",clearance.history(op.getOrgId(),op.getId()));out.set("ipcInstances",currentContext.current().hasPermission("qms:ipc:view")?quality.getObject().instances(op.getOrgId(),op.getId()):json.createArrayNode());var us=out.putArray("equipmentUsages");usages(op.getOrgId(),op.getId()).forEach(x->us.add(view(x)));var ps=out.putArray("parameterValues");db.parameterValueMapper.selectList(new QueryWrapper<ParameterValueEntity>().eq("org_id",op.getOrgId()).eq("operation_execution_id",op.getId()).orderByAsc("id")).forEach(x->ps.add(views.view(x)));out.putArray("gates");var actions=out.putArray("allowedActions");switch(op.getStatus()){case "READY"->{actions.add("START");actions.add("BIND_EQUIPMENT");}case "IN_PROGRESS"->{actions.add("PAUSE");actions.add("COMPLETE");actions.add("RECORD_PARAMETER");}case "PAUSED"->{actions.add("RESUME");actions.add("BIND_EQUIPMENT");}default->{}}}if(row instanceof EquipmentUsageEntity usage){var runs=out.putArray("runs");db.equipmentRunMapper.selectList(new QueryWrapper<EquipmentRunEntity>().eq("org_id",row.getOrgId()).eq("equipment_usage_id",usage.getId()).orderByAsc("id")).forEach(x->runs.add(views.view(x)));}return out;}
}
