package com.hospital.mes.execution.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.hospital.mes.execution.infrastructure.*;
import com.hospital.mes.execution.domain.ExecutionRules;
import com.hospital.mes.production.application.*;
import com.hospital.mes.production.domain.ProductionRules;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.masterdata.infrastructure.ScopedEntity;
import com.hospital.mes.equipment.application.EquipmentQueryService;
import com.hospital.mes.audit.application.CurrentPlatformContext;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.common.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.time.*;
import java.math.*;
import static com.hospital.mes.production.application.ProductionInput.*;
import static com.hospital.mes.production.domain.ProductionRules.gate;
@org.springframework.stereotype.Service
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class WeighChargeService {
 private final ProductionMaterialPolicyService weighingPolicies;private final ExecutionStore db;private final ProductionQueryService production;private final MasterQueryService units;private final MasterMutation mutations;private final ProductionViews views;private final ObjectMapper json;private final QualificationGate qualifications;private final EquipmentQueryService equipment;private final WeighingPolicyPort policy;private final ObjectProvider<ExecutionMaterialPort> material;private final ObjectProvider<ChargeStockPort> stock;private final WeighingSignableProvider signable;private final SignatureApplicationService signing;private final SignatureRepository signatures;private final SignatureCanonicalizer canonicalizer;
 public WeighChargeService(ProductionMaterialPolicyService weighingPolicies,ExecutionStore db,ProductionQueryService production,MasterQueryService units,MasterMutation mutations,ProductionViews views,ObjectMapper json,QualificationGate qualifications,EquipmentQueryService equipment,WeighingPolicyPort policy,ObjectProvider<ExecutionMaterialPort> material,ObjectProvider<ChargeStockPort> stock,WeighingSignableProvider signable,SignatureApplicationService signing,SignatureRepository signatures,SignatureCanonicalizer canonicalizer){this.weighingPolicies=weighingPolicies;this.db=db;this.production=production;this.units=units;this.mutations=mutations;this.views=views;this.json=json;this.qualifications=qualifications;this.equipment=equipment;this.policy=policy;this.material=material;this.stock=stock;this.signable=signable;this.signing=signing;this.signatures=signatures;this.canonicalizer=canonicalizer;}
 public List<JsonNode> weighings(String unitId){var c=mutations.context("mes:weigh:view");long unit=MasterMutation.id(unitId);production.execution(c.organizationId(),unit);return db.weighingMapper.selectList(new QueryWrapper<WeighingEntity>().eq("org_id",c.organizationId()).eq("execution_unit_id",unit).orderByAsc("id")).stream().map(this::view).toList();}
 public List<JsonNode> charges(String unitId){var c=mutations.context("mes:charge:view");long unit=MasterMutation.id(unitId);production.execution(c.organizationId(),unit);return chargeRows(c.organizationId(),unit).stream().map(this::view).toList();}
 @Transactional public JsonNode createWeighing(JsonNode body,String key){fields(body,"executionUnitId","materialLotId","formulaItemId","targetQty","actualQty","unitId","scaleEquipmentId","versionNo","reason");var c=mutations.context("mes:weigh:create");long expected=version(body,null);String reason=text(body,"reason",1000);return mutations.execute(c,"Weighing:CREATE",key,body,()->{long execution=id(body,"executionUnitId");var context=production.lockExecution(c.organizationId(),execution);ProductionRules.version(context.versionNo(),expected);gate(Set.of("RELEASED","IN_PROGRESS").contains(context.batchStatus())&&!"COMPLETED".equals(context.executionStatus()),"INVALID_BATCH_STATE","Active released execution required");var formula=formula(context.snapshot(),id(body,"formulaItemId"));long materialId=id(formula,"materialId");var materialPolicy=materialPolicy(context.snapshot(),materialId);long lot=id(body,"materialLotId");requireLot(c,context.mainBatchId(),lot,materialId);long unit=id(body,"unitId");BigDecimal target=target(c.organizationId(),execution,context.snapshot(),formula,unit),actual=quantity(body,"actualQty");gate(quantity(body,"targetQty").compareTo(target)==0,"WEIGHING_TARGET_MISMATCH","Target must match exact frozen formula requirement");BigDecimal precision=decimalPolicy(materialPolicy,"precision");precision=exact(units,c.organizationId(),id(materialPolicy,"baseUnitId"),unit,materialId,precision);ProductionRules.weighing(target,actual,decimalPolicy(materialPolicy,"tolerancePct"),precision);
  var at=Instant.now();var control=policy.requirePolicy(c.organizationId(),materialId);var scale=equipment.equipmentEvidence(c.organizationId(),id(body,"scaleEquipmentId"),at);gate(control.scaleEquipmentTypes().contains(scale.equipmentType())&&scale.calibrationDueDate()!=null,"WEIGHING_SCALE_INVALID","A configured calibrated scale is required");var scaleEvidence=json.createObjectNode();scaleEvidence.put("equipmentId",scale.equipmentId());scaleEvidence.put("versionNo",scale.versionNo());scaleEvidence.put("equipmentType",scale.equipmentType());scaleEvidence.put("status",scale.status());scaleEvidence.put("calibrationDueDate",scale.calibrationDueDate().toString());scaleEvidence.put("checkedAt",at.toString());var controlEvidence=scaleEvidence.putObject("policy");controlEvidence.put("policyVersion","INCOMING-WEIGH-1");controlEvidence.put("independentVerificationRequired",true);controlEvidence.put("signatureRequired",true);controlEvidence.set("scaleEquipmentTypes",json.valueToTree(new TreeSet<>(control.scaleEquipmentTypes())));controlEvidence.put("configurationHash",control.configurationHash());var gateEvidence=qualifications.evidence(c,"weigh-create",at);gateEvidence.put("materialId",Long.toString(materialId));
  var row=new WeighingEntity();row.setExecutionUnitId(execution);row.setMaterialLotId(lot);row.setBomItemId(id(body,"formulaItemId"));row.setTargetQty(target);row.setActualQty(actual);row.setUnitId(unit);row.setWeighedBy(c.actorId());row.setStatus("CONFIRMED");row.setScaleEquipmentId(id(body,"scaleEquipmentId"));row.setEquipmentEvidenceJson(scaleEvidence.toString());row.setGateEvidenceJson(json.createArrayNode().add(gateEvidence).toString());row.setSignatureEvidenceJson("[]");db.weighings.insert(row,c.organizationId(),c.actorId());mutations.auditSnapshot(c,"Weighing:CREATE","WeighingRecord",row.getId(),null,view(row),reason,key);return row;},this::view,201);}
 @Transactional public JsonNode verifyWeighing(String id,JsonNode body,String header,String key){fields(body,"versionNo","reason","reauthToken");var c=mutations.context("mes:weigh:verify");mutations.context("ebr:sign");long expected=version(body,header);String why=text(body,"reason",1000);return mutations.execute(c,"Weighing:VERIFY:"+id,key,Map.of("id",id,"version",expected,"reason",why),()->{var found=db.weighings.get(c.organizationId(),MasterMutation.id(id));var context=production.lockExecution(c.organizationId(),found.getExecutionUnitId());long materialId=id(formula(context.snapshot(),found.getBomItemId()),"materialId");requireLot(c,context.mainBatchId(),found.getMaterialLotId(),materialId);var row=db.weighings.lock(c.organizationId(),found.getId());ProductionRules.version(row.getVersionNo(),expected);if(!"CONFIRMED".equals(row.getStatus()))throw new StateTransitionException("INVALID_WEIGHING_STATE","Only confirmed weighing can be verified");ExecutionRules.independent(row.getWeighedBy(),c.actorId(),true);var before=view(row);row.setVerifiedBy(c.actorId());row.setStatus("VERIFIED");row.setGateEvidenceJson(append(row.getGateEvidenceJson(),qualifications.evidence(c,"weigh-verify",Instant.now())));var canonical=(ObjectNode)view(row);canonical.remove("signatureEvidence");canonical.remove("allowedActions");canonical.put("action","VERIFY");String target=row.getId()+":VERIFY:"+expected;var evidenceIds=List.of("WeighingRecord:"+row.getId(),"MaterialLot:"+row.getMaterialLotId(),"Equipment:"+row.getScaleEquipmentId());var object=new SignableObject("WEIGHING_VERIFICATION",target,expected,canonical,evidenceIds);var signature=signable.withIntent(c.organizationId(),c.actorId(),object,()->signing.sign(new SignCommand(c,object.objectType(),target,SignatureMeaning.VERIFY,expected,text(body,"reauthToken",10000),com.hospital.mes.audit.idempotency.PlatformIdempotencyService.digest(key+":verify"),null)));
  var envelope=json.createObjectNode();envelope.put("action","VERIFY");envelope.put("objectType",object.objectType());envelope.put("objectId",object.objectId());envelope.put("recordVersion",object.recordVersion());envelope.set("canonicalRecord",canonical.deepCopy());envelope.set("evidenceIds",json.valueToTree(evidenceIds));envelope.put("signatureId",signature.id());row.setSignatureEvidenceJson(append(row.getSignatureEvidenceJson(),envelope));db.weighings.update(row,expected,c.actorId(),List.of("verifiedBy","status","gateEvidenceJson","signatureEvidenceJson"));mutations.auditSnapshot(c,"Weighing:VERIFY","WeighingRecord",row.getId(),before,view(row),why,key);return row;},this::view,200);}
 @Transactional public JsonNode createCharge(JsonNode body,String key){fields(body,"executionUnitId","operationExecutionId","materialLotId","weighingRecordId","chargedQty","unitId","versionNo","reason");var c=mutations.context("mes:charge:create");long expected=version(body,null);String reason=text(body,"reason",1000);return mutations.execute(c,"MaterialCharge:CREATE",key,body,()->{long execution=id(body,"executionUnitId");var context=production.lockExecution(c.organizationId(),execution);var operation=db.operations.lock(c.organizationId(),id(body,"operationExecutionId"));ProductionRules.version(operation.getVersionNo(),expected);gate(operation.getExecutionUnitId()==execution&&"IN_PROGRESS".equals(operation.getStatus())&&"IN_PROGRESS".equals(context.batchStatus()),"INVALID_OPERATION_STATE","Charge requires same running operation and batch");long lot=id(body,"materialLotId");var lotFact=materials().lot(c.organizationId(),lot);long materialId=id(lotFact,"materialId");requireLot(c,context.mainBatchId(),lot,materialId);var materialPolicy=materialPolicy(context.snapshot(),materialId);Long weighingId=optionalId(body,"weighingRecordId");WeighingEntity weighing=null;JsonNode formula;
  if(weighingId!=null){weighing=db.weighings.lock(c.organizationId(),weighingId);gate(weighing.getExecutionUnitId()==execution&&weighing.getMaterialLotId()==lot,"WEIGHING_CONTEXT_MISMATCH","Weighing does not match execution and lot");requireVerified(weighing);formula=formula(context.snapshot(),weighing.getBomItemId());gate(id(formula,"materialId")==materialId,"MATERIAL_NOT_IN_BOM","Weighing BOM mismatch");}else{gate(materialPolicy.path("required").isBoolean()&&!materialPolicy.path("required").booleanValue(),"WEIGHING_REQUIRED","Frozen material policy requires verified weighing");var matching=new ArrayList<JsonNode>();for(var f:context.snapshot().path("process").path("formula").path("items"))if(id(f,"materialId")==materialId)matching.add(f);gate(matching.size()==1,"MATERIAL_NOT_IN_BOM","Unweighed charge requires an unambiguous frozen BOM line");formula=matching.getFirst();}
  long unit=id(body,"unitId");BigDecimal qty=quantity(body,"chargedQty");var prior=chargeRows(c.organizationId(),execution).stream().filter(x->"CONFIRMED".equals(x.getStatus())).toList();if(weighing!=null){BigDecimal used=BigDecimal.ZERO;for(var previous:prior)if(Objects.equals(previous.getWeighingRecordId(),weighingId))used=used.add(exact(units,c.organizationId(),previous.getUnitId(),weighing.getUnitId(),materialId,previous.getChargedQty()));gate(used.add(exact(units,c.organizationId(),unit,weighing.getUnitId(),materialId,qty)).compareTo(weighing.getActualQty())<=0,"CHARGE_QTY_INVALID","Charge exceeds remaining weighed quantity");}else{BigDecimal used=BigDecimal.ZERO;for(var previous:prior){var sourceLot=materials().lot(c.organizationId(),previous.getMaterialLotId());if(id(sourceLot,"materialId")==materialId)used=used.add(exact(units,c.organizationId(),previous.getUnitId(),unit,materialId,previous.getChargedQty()));}gate(used.add(qty).compareTo(target(c.organizationId(),execution,context.snapshot(),formula,unit))<=0,"CHARGE_QTY_INVALID","Charge exceeds frozen formula requirement");}
  BigDecimal formulaUsed=BigDecimal.ZERO;for(var previous:prior){String previousFormula=null;for(var ev:read(previous.getGateEvidenceJson()))if(ev.hasNonNull("formulaItemId")){previousFormula=ev.get("formulaItemId").asText();break;}if(formula.path("formulaItemId").asText().equals(previousFormula))formulaUsed=formulaUsed.add(exact(units,c.organizationId(),previous.getUnitId(),unit,materialId,previous.getChargedQty()));}BigDecimal formulaMaximum=target(c.organizationId(),execution,context.snapshot(),formula,unit);if(weighing!=null)formulaMaximum=formulaMaximum.multiply(BigDecimal.ONE.add(decimalPolicy(materialPolicy,"tolerancePct").movePointLeft(2)));gate(formulaUsed.add(qty).compareTo(formulaMaximum)<=0,"CHARGE_QTY_INVALID","Aggregate charge exceeds frozen formula allowance across all weighings");
  var gateEvidence=qualifications.evidence(c,"charge-create",Instant.now());gateEvidence.put("materialId",Long.toString(materialId));gateEvidence.put("formulaItemId",formula.path("formulaItemId").asText());var row=new ChargeEntity();row.setExecutionUnitId(execution);row.setOperationExecutionId(operation.getId());row.setMaterialLotId(lot);row.setWeighingRecordId(weighingId);row.setChargedQty(qty);row.setUnitId(unit);row.setChargedBy(c.actorId());row.setVerifiedBy(weighing==null?null:weighing.getVerifiedBy());row.setChargedAt(now());row.setStatus("CONFIRMED");row.setGateEvidenceJson(json.createArrayNode().add(gateEvidence).toString());row.setSignatureEvidenceJson("[]");db.charges.insert(row,c.organizationId(),c.actorId());stock().consume(c,context.mainBatchId(),lot,row.getId(),qty,unit,key);quantityEvent(c,context.mainBatchId(),row,"CHARGE",qty,key);var genealogy=new GenealogyEntity();genealogy.setMainBatchId(context.mainBatchId());genealogy.setInputMaterialLotId(lot);genealogy.setChargeId(row.getId());genealogy.setRelationType("MATERIAL_CHARGE");db.genealogys.insert(genealogy,c.organizationId(),c.actorId());mutations.auditSnapshot(c,"Genealogy:CHARGE","Genealogy",genealogy.getId(),null,views.view(genealogy),reason,key);
  var beforeOperation=views.view(operation);db.operations.update(operation,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"Operation:CHARGE","OperationExecution",operation.getId(),beforeOperation,views.view(operation),reason,key);if(weighing!=null){var beforeWeighing=view(weighing);db.weighings.update(weighing,weighing.getVersionNo(),c.actorId(),List.of());mutations.auditSnapshot(c,"Weighing:CHARGE_REFERENCED","WeighingRecord",weighing.getId(),beforeWeighing,view(weighing),reason,key);}mutations.auditSnapshot(c,"MaterialCharge:CREATE","MaterialCharge",row.getId(),null,view(row),reason,key);return row;},this::view,201);}
 @Transactional public JsonNode reverseCharge(String id,JsonNode body,String header,String key){fields(body,"versionNo","reason","reauthToken");var c=mutations.context("mes:charge:reverse");long expected=version(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"MaterialCharge:REVERSE:"+id,key,Map.of("id",id,"version",expected,"reason",reason),()->{var found=db.charges.get(c.organizationId(),MasterMutation.id(id));var context=production.lockExecution(c.organizationId(),found.getExecutionUnitId());var operation=db.operations.lock(c.organizationId(),found.getOperationExecutionId());gate("IN_PROGRESS".equals(context.batchStatus())&&Set.of("IN_PROGRESS","PAUSED").contains(operation.getStatus()),"CHARGE_REVERSAL_FORBIDDEN","Completed downstream operation/batch prevents reversal");stock().lockLot(c.organizationId(),found.getMaterialLotId());var row=db.charges.lock(c.organizationId(),found.getId());ProductionRules.version(row.getVersionNo(),expected);if(!"CONFIRMED".equals(row.getStatus()))throw new StateTransitionException("CHARGE_ALREADY_REVERSED","Charge is not confirmed");var before=view(row);row.setGateEvidenceJson(append(row.getGateEvidenceJson(),qualifications.evidence(c,"charge-reverse",Instant.now())));stock().reverse(c,context.mainBatchId(),row.getMaterialLotId(),row.getId(),key);quantityEvent(c,context.mainBatchId(),row,"CHARGE_REVERSE",row.getChargedQty().negate(),key);row.setStatus("REVERSED");db.charges.update(row,expected,c.actorId(),List.of("status","gateEvidenceJson"));mutations.auditSnapshot(c,"MaterialCharge:REVERSE","MaterialCharge",row.getId(),before,view(row),reason,key);return row;},this::view,200);}
 private void requireVerified(WeighingEntity row){gate("VERIFIED".equals(row.getStatus())&&row.getVerifiedBy()!=null&&!row.getVerifiedBy().equals(row.getWeighedBy()),"WEIGHING_VERIFICATION_REQUIRED","Independent verified weighing required");boolean valid=false;for(var e:read(row.getSignatureEvidenceJson())){var signature=signatures.find(row.getOrgId(),MasterMutation.id(e.path("signatureId").asText()));var object=signable.loadForSignature(row.getOrgId(),e.path("objectId").asText());var current=view(row);var signed=e.path("canonicalRecord");for(String field:List.of("id","executionUnitId","materialLotId","formulaItemId","targetQty","actualQty","unitId","weighedBy","verifiedBy","status","scaleEquipmentId","equipmentEvidence","gateEvidence"))gate(current.path(field).equals(signed.path(field)),"SIGNATURE_INVALID","Current weighing evidence differs from signed immutable record");if(signature.status()==SignatureStatus.VALID&&signature.meaning()==SignatureMeaning.VERIFY&&signature.signerId()==row.getVerifiedBy()&&signature.recordDigest().equals(canonicalizer.digest(object)))valid=true;}gate(valid,"SIGNATURE_INVALID","Valid weighing verification signature required");}
 private void quantityEvent(CurrentPlatformContext c,long batch,ChargeEntity charge,String type,BigDecimal qty,String key){var event=new QuantityEventEntity();event.setMainBatchId(batch);event.setExecutionUnitId(charge.getExecutionUnitId());event.setOperationExecutionId(charge.getOperationExecutionId());event.setEventType(type);event.setMaterialLotId(charge.getMaterialLotId());event.setAmount(qty);event.setUnitId(charge.getUnitId());event.setSourceType("MaterialCharge");event.setSourceRef(charge.getId().toString());event.setOccurredAt(now());db.quantityEvents.insert(event,c.organizationId(),c.actorId());mutations.auditSnapshot(c,"QuantityEvent:"+type,"QuantityEvent",event.getId(),null,views.view(event),"Actual charge evidence",key);}
 private List<ChargeEntity> chargeRows(long org,long execution){return db.chargeMapper.selectList(new QueryWrapper<ChargeEntity>().eq("org_id",org).eq("execution_unit_id",execution).orderByAsc("id"));}
 private BigDecimal target(long org,long execution,JsonNode snapshot,JsonNode item,long unit){var formula=snapshot.path("process").path("formula");var plan=production.executionPlan(org,execution);gate(plan!=null,"BATCH_PLAN_REQUIRED","Execution requires an explicit plan quantity");var normalizedPlan=exact(units,org,production.executionPlanUnit(org,execution),id(formula,"unitId"),null,plan);BigDecimal target;try{target=new BigDecimal(item.path("requiredQty").asText()).multiply(normalizedPlan).divide(new BigDecimal(formula.path("batchBasisQty").asText()));if(item.hasNonNull("overagePct"))target=target.multiply(BigDecimal.ONE.add(new BigDecimal(item.get("overagePct").asText()).movePointLeft(2)));target=target.setScale(6,RoundingMode.UNNECESSARY);}catch(ArithmeticException ex){throw new ComplianceException("QUANTITY_PRECISION_LOSS","Formula target cannot be represented exactly");}return exact(units,org,id(item,"unitId"),unit,id(item,"materialId"),target);}
 private JsonNode formula(JsonNode snapshot,long item){for(var f:snapshot.path("process").path("formula").path("items"))if(f.path("formulaItemId").asText().equals(Long.toString(item)))return f;throw new ComplianceException("MATERIAL_NOT_IN_BOM","BOM line not in immutable snapshot");}
 private JsonNode materialPolicy(JsonNode snapshot,long material){for(var m:snapshot.path("materials"))if(m.path("id").asText().equals(Long.toString(material)))return weighingPolicies.requireFrozen(m.path("weighingPolicy"),id(snapshot,"organizationId"),material,id(m,"baseUnitId"));throw new ComplianceException("MATERIAL_NOT_IN_BOM","Material not in frozen batch");}
 private BigDecimal decimalPolicy(JsonNode material,String field){gate(material.hasNonNull(field),"WEIGHING_POLICY_REQUIRED","Frozen "+field+" required");return new BigDecimal(material.get(field).asText());}
 private void requireLot(CurrentPlatformContext c,long batch,long lot,long materialId){var fact=materials().lot(c.organizationId(),lot);gate(id(fact,"materialId")==materialId,"MATERIAL_NOT_IN_BOM","Lot does not match frozen BOM material");materials().requireEligible(c.organizationId(),batch,lot,materialId,Instant.now());}
 private ExecutionMaterialPort materials(){var p=material.getIfAvailable();if(p==null)throw new ComplianceException("DEPENDENCY_NOT_READY","Actual material eligibility unavailable");return p;}
 private ChargeStockPort stock(){var p=stock.getIfAvailable();if(p==null)throw new ComplianceException("DEPENDENCY_NOT_READY","Actual inventory consumer unavailable");return p;}
 private JsonNode read(String value){try{return json.readTree(value);}catch(java.io.IOException ex){throw new IllegalStateException("Stored evidence invalid",ex);}}
 private String append(String current,JsonNode entry){var array=(ArrayNode)read(current);array.add(entry);return array.toString();}
 private JsonNode view(ScopedEntity row){var out=views.view(row);if(row instanceof WeighingEntity w){out.set("formulaItemId",out.remove("bomItemId"));var actions=out.putArray("allowedActions");if("CONFIRMED".equals(w.getStatus()))actions.add("VERIFY");}if(row instanceof ChargeEntity ch){var actions=out.putArray("allowedActions");if("CONFIRMED".equals(ch.getStatus()))actions.add("REVERSE");}return out;}
}
