package com.hospital.mes.ebr.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.ebr.domain.*;
import com.hospital.mes.ebr.infrastructure.*;
import com.hospital.mes.audit.application.*;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.common.exception.*;
import com.hospital.mes.masterdata.application.*;
import org.springframework.transaction.annotation.*;
import java.util.*;
import java.time.*;
/** Public producer/consumer API. Runtime completion is proven from frozen forms and real evidence. */
@org.springframework.stereotype.Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class EbrRuntimeService {
 private final EbrRuntimeStore db;private final EbrStore definitions;private final EbrRuntimeModel model;private final EbrRuntimeTransactions transactions;private final MasterMutation mutations;private final ObjectMapper json;private final CurrentPlatformContextResolver contexts;private final SignatureRepository signatures;
 public EbrRuntimeService(EbrRuntimeStore db,EbrStore definitions,EbrRuntimeModel model,EbrRuntimeTransactions transactions,MasterMutation mutations,ObjectMapper json,CurrentPlatformContextResolver contexts,SignatureRepository signatures){this.db=db;this.definitions=definitions;this.model=model;this.transactions=transactions;this.mutations=mutations;this.json=json;this.contexts=contexts;this.signatures=signatures;}
 public record EbrGateEvidence(boolean complete,List<String> blockingCodes,List<Long> formInstanceIds,List<Long> revisionIds,List<Long> signatureIds){public EbrGateEvidence{blockingCodes=List.copyOf(blockingCodes);formInstanceIds=List.copyOf(formInstanceIds);revisionIds=List.copyOf(revisionIds);signatureIds=List.copyOf(signatureIds);}}
 @Transactional(propagation=Propagation.MANDATORY) public void initializeOperation(long org,long actor,long batch,long execution,long operation,long operationDef,JsonNode snapshot){var ctx=model.port().lockOperation(org,operation);if(ctx.mainBatchId()!=batch||ctx.executionUnitId()!=execution||ctx.operationDefId()!=operationDef||!ctx.snapshot().equals(snapshot))throw new ComplianceException("EBR_SNAPSHOT_INVALID","Actual execution snapshot mismatch");JsonNode payload=snapshot.path("ebr");if(!payload.isObject()||!payload.hasNonNull("definitionHash"))throw new ComplianceException("EBR_SNAPSHOT_INVALID","Frozen eBR definition required");ObjectNode canonical=payload.deepCopy();String hash=canonical.remove("definitionHash").asText();if(!hash.equals(mutations.digest(canonical)))throw new ComplianceException("EBR_SNAPSHOT_INVALID","Frozen definition digest mismatch");var definition=json.convertValue(payload.path("definition"),EbrCommands.Definition.class);EbrRuntimeRules.requireBindings(definition);long template=MasterMutation.id(payload.path("templateVersionId").asText());var existing=db.rows(RuntimeBatchSnapshotEntity.class,org,"main_batch_id",batch);if(existing.isEmpty()){var row=new RuntimeBatchSnapshotEntity();row.setMainBatchId(batch);row.setTemplateVersionId(template);row.setDefinitionHash(hash);row.setSnapshotJson(model.encode(payload));row.setFrozenAt(LocalDateTime.now(ZoneOffset.UTC));db.store(RuntimeBatchSnapshotEntity.class).insert(row,org,actor);var c=contexts.current();if(c.organizationId()!=org||c.actorId()!=actor)throw new PermissionException("PERMISSION_DENIED","Actual release actor required");mutations.audit(c,"EBR_BATCH_FROZEN","EBR_BATCH_SNAPSHOT",null,row,"Production batch release",null);}else if(!model.parse(existing.getFirst().getSnapshotJson()).equals(payload))throw new ComplianceException("EBR_SNAPSHOT_INVALID","Batch snapshot is immutable");var source=definitions.rows(FormEntity.class,org,"template_version_id",template);var present=db.forms(org,operation);for(var form:definition.forms())if(MasterMutation.id(form.operationDefId())==operationDef){var def=source.stream().filter(x->x.getFormCode().equals(form.formCode())).findFirst().orElseThrow(()->new ComplianceException("EBR_SNAPSHOT_INVALID","Frozen form definition source missing"));if(present.stream().noneMatch(x->x.getFormDefId().equals(def.getId())&&x.getOccurrenceNo()==1)){var f=new RuntimeFormEntity();f.setOperationExecutionId(operation);f.setFormDefId(def.getId());f.setOccurrenceNo(1);f.setStatus("DRAFT");f.setRevision(0);db.store(RuntimeFormEntity.class).insert(f,org,actor);mutations.audit(contexts.current(),"EBR_FORM_INITIALIZED","EBR_FORM_INSTANCE",null,f,"Production batch release",null);}}requireInitialized(org,operation);}
 @Transactional(readOnly=true) public void requireInitialized(long org,long operation){var ctx=model.port().operation(org,operation);var row=db.snapshot(org,ctx.mainBatchId());JsonNode snapshot=model.parse(row.getSnapshotJson());if(!snapshot.equals(ctx.snapshot().path("ebr")))throw new ComplianceException("EBR_SNAPSHOT_INVALID","Runtime snapshot differs from execution snapshot");var definition=json.convertValue(snapshot.path("definition"),EbrCommands.Definition.class);EbrRuntimeRules.requireBindings(definition);var source=definitions.rows(FormEntity.class,org,"template_version_id",row.getTemplateVersionId());Set<Long> expected=new HashSet<>();for(var form:definition.forms())if(MasterMutation.id(form.operationDefId())==ctx.operationDefId())expected.add(source.stream().filter(x->x.getFormCode().equals(form.formCode())).findFirst().orElseThrow().getId());var actual=db.forms(org,operation);if(actual.size()!=expected.size()||actual.stream().anyMatch(f->f.getOccurrenceNo()!=1||!expected.contains(f.getFormDefId())))throw new ComplianceException("EBR_RUNTIME_NOT_INITIALIZED","Actual frozen form instance set missing or inconsistent");}
 @Transactional(readOnly=true) public EbrGateEvidence evaluateOperation(long org,long operation){requireInitialized(org,operation);List<String> blocked=new ArrayList<>();List<Long> forms=new ArrayList<>(),values=new ArrayList<>(),signed=new ArrayList<>();for(var f:db.forms(org,operation)){forms.add(f.getId());blocked.addAll(model.blockers(f));if(!model.evaluate(f,"ON_OPERATION_COMPLETE",contexts.current().roleCodes(),Instant.now()).allowed())blocked.add("EBR_RULE_BLOCKED");db.current(f).forEach(v->values.add(v.getId()));signatures.findValid(org,"EBR_FORM_INSTANCE",f.getId().toString()).forEach(s->signed.add(s.id()));db.reviews(f).stream().filter(model::reviewValid).forEach(r->signed.add(r.getSignatureId()));}return new EbrGateEvidence(blocked.isEmpty(),blocked,forms,values,signed);}
 @Transactional(propagation=Propagation.MANDATORY) public void requireOperationComplete(long org,long operation){model.port().lockOperation(org,operation);var c=contexts.current();if(c.organizationId()!=org)throw new PermissionException("PERMISSION_DENIED","Organization mismatch");requireInitialized(org,operation);for(var f:db.forms(org,operation)){var result=transactions.persistRules(c,f,"ON_OPERATION_COMPLETE",null,"Operation completion validation");if(!result.allowed()||!model.blockers(f).isEmpty())throw new ComplianceException("EBR_OPERATION_INCOMPLETE","Required values, rules, signatures or reviews are incomplete");}}
 @Transactional(propagation=Propagation.MANDATORY) public void requireOperationReview(long org,long operation){model.port().lockOperation(org,operation);var evidence=evaluateOperation(org,operation);if(!evidence.complete())throw new ComplianceException("EBR_REVIEW_REQUIRED",String.join(",",evidence.blockingCodes()));}
 @Transactional(readOnly=true) public JsonNode forms(String execution){var c=mutations.context("ebr:form:view");var result=json.createArrayNode();var items=result;for(long operation:model.port().operationIds(c.organizationId(),MasterMutation.id(execution))){requireInitialized(c.organizationId(),operation);db.forms(c.organizationId(),operation).forEach(f->items.add(model.summary(f)));}return result;}
 @Transactional(readOnly=true) public JsonNode render(String id){var c=mutations.context("ebr:form:view");return model.render(db.store(RuntimeFormEntity.class).get(c.organizationId(),MasterMutation.id(id)),c);}
 @Transactional(readOnly=true) public JsonNode batch(String id){var c=mutations.context("ebr:form:view");long batch=MasterMutation.id(id);var snapshot=db.snapshot(c.organizationId(),batch);var result=json.createObjectNode();result.put("mainBatchId",id);result.put("templateVersionId",snapshot.getTemplateVersionId().toString());result.put("definitionHash",snapshot.getDefinitionHash());var forms=result.putArray("forms");for(long operation:model.port().batchOperationIds(c.organizationId(),batch)){var evidence=evaluateOperation(c.organizationId(),operation);db.forms(c.organizationId(),operation).forEach(f->forms.add(model.render(f,c)));}return result;}
 /** No transaction: a rule-blocked outcome is raised only after the worker proxy has committed. */
 public JsonNode command(String operation,String id,Object request,String match,String key){String permission=switch(operation){case "SAVE"->"ebr:form:edit";case "SUBMIT"->"ebr:form:submit";case "CORRECT"->"ebr:record:correct";case "REVIEW"->"ebr:sign";default->throw new IllegalArgumentException("Unknown command");};var c=mutations.context(permission);var result=transactions.command(c,operation,MasterMutation.id(id),request,match,key);if(result.blockedCode()!=null)throw new ComplianceException(result.blockedCode(),result.message());return result.data();}
}
