package com.hospital.mes.ebr.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.ebr.domain.*;
import com.hospital.mes.ebr.infrastructure.*;
import com.hospital.mes.audit.application.*;
import com.hospital.mes.audit.idempotency.*;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.common.exception.*;
import com.hospital.mes.masterdata.application.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.time.*;
import static com.hospital.mes.ebr.domain.EbrRuntimeCommands.*;
/** The transaction returns blocked outcomes normally so rule evidence and idempotency commit. */
@org.springframework.stereotype.Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class EbrRuntimeTransactions {
 private final EbrRuntimeStore db;private final EbrRuntimeModel model;private final MasterMutation mutations;private final PlatformIdempotencyService keys;private final ObjectMapper json;private final SignatureApplicationService signing;private final SignatureTransactionService signatureTx;private final EbrReviewIntent intents;private final ObjectProvider<EbrDeviationPort> deviations;
 public EbrRuntimeTransactions(EbrRuntimeStore db,EbrRuntimeModel model,MasterMutation mutations,PlatformIdempotencyService keys,ObjectMapper json,SignatureApplicationService signing,SignatureTransactionService signatureTx,EbrReviewIntent intents,ObjectProvider<EbrDeviationPort> deviations){this.db=db;this.model=model;this.mutations=mutations;this.keys=keys;this.json=json;this.signing=signing;this.signatureTx=signatureTx;this.intents=intents;this.deviations=deviations;}
 public record Outcome(String blockedCode,String message,JsonNode data){public static Outcome success(JsonNode data){return new Outcome(null,null,data);}public static Outcome blocked(String code,String message,JsonNode data){return new Outcome(code,message,data);}}
 @Transactional public Outcome command(CurrentPlatformContext c,String operation,long id,Object request,String match,String key){
  String reason=request instanceof Save r?r.reason():request instanceof Command r?r.reason():request instanceof Correction r?r.reason():((Review)request).reason();EbrRuntimeRules.reason(reason);
  var payload=json.createObjectNode();payload.put("id",Long.toString(id));payload.put("ifMatch",match);payload.set("request",json.valueToTree(request));
  var decision=keys.begin(new IdempotencyCommand(c.organizationId(),c.actorId(),"EBR_RUNTIME_"+operation,key,model.encode(payload)));
  if(decision.type()==IdempotencyDecisionType.REPLAY)return json.convertValue(model.parse(decision.responseJson()),Outcome.class);
  if(decision.type()==IdempotencyDecisionType.CONFLICT)throw new ResourceConflictException("IDEMPOTENCY_KEY_REUSED","Key reused with different request");
  if(decision.type()==IdempotencyDecisionType.IN_PROGRESS_CONFLICT)throw new ResourceConflictException("IDEMPOTENCY_IN_PROGRESS","Command is in progress");
  RuntimeValueEntity corrected=operation.equals("CORRECT")?db.store(RuntimeValueEntity.class).get(c.organizationId(),id):null;
  var f=db.store(RuntimeFormEntity.class).get(c.organizationId(),corrected==null?id:corrected.getFormInstanceId());model.context(f,true);f=db.store(RuntimeFormEntity.class).lock(c.organizationId(),f.getId());model.active(f);
  Long requested=request instanceof Save r?r.formRevision():request instanceof Command r?r.formRevision():request instanceof Correction r?r.formRevision():((Review)request).formRevision();long expected=EbrRuntimeRules.expected(match,requested);if(expected!=f.getRevision())throw new ResourceConflictException("REVISION_CONFLICT","Form content changed");
  JsonNode before=model.render(f,c);Outcome outcome;
  switch(operation){
   case "SAVE"->{save(c,f,(Save)request,key);outcome=Outcome.success(model.render(f,c));}
   case "SUBMIT"->outcome=submit(c,f,reason,key);
   case "CORRECT"->{correct(c,f,corrected,(Correction)request,key);outcome=Outcome.success(model.render(f,c));}
   case "REVIEW"->{review(c,f,(Review)request,key);outcome=Outcome.success(model.render(f,c));}
   default->throw new IllegalArgumentException("Unknown runtime command");
  }
  mutations.auditSnapshot(c,"EBR_FORM_"+operation,"EBR_FORM_INSTANCE",f.getId(),before,model.render(f,c),reason,key);
  keys.complete(decision.handle(),outcome.blockedCode()==null?200:422,model.encode(outcome),"EBR_FORM_INSTANCE",f.getId().toString());return outcome;
 }
 private void save(CurrentPlatformContext c,RuntimeFormEntity f,Save r,String key){if(!f.getStatus().equals("DRAFT"))throw new ResourceConflictException("INVALID_FORM_STATE","Only draft form is editable");if(r.values()==null||r.values().isEmpty()||r.values().size()>500)throw new IllegalArgumentException("One to 500 field values required");Set<String> seen=new HashSet<>();var definition=model.definition(f);for(var v:r.values()){if(v==null||!seen.add(v.fieldCode()+"|"+v.occurrencePath()))throw new IllegalArgumentException("Duplicate field occurrence");var field=model.field(f,v.fieldCode());EbrRuntimeRules.occurrence(definition,field,v.occurrencePath());var normalized=EbrRuntimeRules.normalize(field,v.value(),v.unitId(),false);if("BARCODE".equals(field.sourceType())&&(v.sourceRef()==null||v.sourceRef().isBlank()))throw new IllegalArgumentException("Barcode source reference required");if("MANUAL".equals(field.sourceType())&&v.sourceRef()!=null)throw new IllegalArgumentException("Manual value has no source reference");append(c,f,field,v.occurrencePath(),v.value(),normalized,v.unitId(),field.sourceType(),v.sourceRef(),r.reason());}
  bump(c,f,true);invalidateDependents(c,f,r.values().getFirst().fieldCode(),r.reason());persistRules(c,f,"ON_CHANGE",key,r.reason());persistRules(c,f,"ON_SAVE",key,r.reason());
 }
 private void append(CurrentPlatformContext c,RuntimeFormEntity f,EbrCommands.Field field,String path,JsonNode raw,JsonNode normalized,String unit,String source,String sourceRef,String reason){if(sourceRef!=null&&sourceRef.length()>128)throw new IllegalArgumentException("Source reference too long");var prior=db.current(f).stream().filter(v->v.getFieldCode().equals(field.fieldCode())&&v.getOccurrencePath().equals(path)).findFirst().orElse(null);var value=new RuntimeValueEntity();value.setFormInstanceId(f.getId());value.setFieldDefId(model.fieldId(f,field.fieldCode()));value.setFieldCode(field.fieldCode());value.setOccurrencePath(path);value.setRevisionNo(prior==null?1:prior.getRevisionNo()+1);value.setPreviousRevisionId(prior==null?null:prior.getId());value.setRawValue(null);value.setDerivedValue(null);value.setRawValueJson(model.encode(raw==null?NullNode.instance:raw));value.setNormalizedValueJson(model.encode(normalized));value.setUnitId(unit==null?null:MasterMutation.id(unit));value.setSourceType(source);value.setSourceRef(sourceRef);value.setChangeReason(reason);value.setRecordedAt(now());value.setRecordedBy(c.actorId());db.store(RuntimeValueEntity.class).insert(value,c.organizationId(),c.actorId());}
 private Outcome submit(CurrentPlatformContext c,RuntimeFormEntity f,String reason,String key){String next=EbrRuntimeRules.transition(f.getStatus(),"SUBMIT");boolean rejectedSame=db.reviews(f).stream().anyMatch(r->r.getDecision().equals("REJECT")&&r.getFormRevision().equals(f.getRevision()));if(rejectedSame)throw new ComplianceException("EBR_REJECTED_REVISION","Save a new content revision before resubmitting rejected content");var result=persistRules(c,f,"ON_SUBMIT",key,reason);if(!result.allowed())return Outcome.blocked("EBR_RULE_BLOCKED","Submission blocked by frozen rules",model.render(f,c));f.setStatus(next);f.setSubmittedAt(now());f.setSubmittedBy(c.actorId());bump(c,f,false);return Outcome.success(model.render(f,c));}
 private void correct(CurrentPlatformContext c,RuntimeFormEntity f,RuntimeValueEntity old,Correction r,String key){if(!db.current(f).stream().anyMatch(v->v.getId().equals(old.getId())))throw new ResourceConflictException("FIELD_REVISION_CONFLICT","Correction target is not the current revision");var field=model.field(f,old.getFieldCode());var normalized=EbrRuntimeRules.normalize(field,r.newValue(),old.getUnitId()==null?null:old.getUnitId().toString(),true);append(c,f,field,old.getOccurrencePath(),r.newValue(),normalized,old.getUnitId()==null?null:old.getUnitId().toString(),old.getSourceType(),old.getSourceRef(),r.reason());invalidate(c,f,r.reason());bump(c,f,true);invalidateDependents(c,f,old.getFieldCode(),r.reason());persistRules(c,f,"ON_CHANGE",key,r.reason());}
 private void invalidate(CurrentPlatformContext c,RuntimeFormEntity f,String reason){invalidate(c,f,reason,null);}
 private void invalidate(CurrentPlatformContext c,RuntimeFormEntity f,String reason,Long retainedReviewId){signatureTx.invalidateSignatures(c,"EBR_FORM_INSTANCE",f.getId().toString(),reason);for(var row:db.reviews(f))if(row.getInvalidatedAt()==null&&!Objects.equals(row.getId(),retainedReviewId)){var e=model.parse(row.getSignatureEvidenceJson());signatureTx.invalidateSignatures(c,"EBR_REVIEW_RECORD",e.path("objectId").asText(),reason);row.setInvalidatedAt(now());row.setInvalidationReason(reason);db.store(RuntimeReviewEntity.class).update(row,row.getVersionNo(),c.actorId(),List.of("invalidatedAt","invalidationReason"));}f.setStatus("DRAFT");f.setSubmittedAt(null);f.setSubmittedBy(null);}
 private void invalidateDependents(CurrentPlatformContext c,RuntimeFormEntity source,String changed,String reason){var ctx=model.context(source,false);Set<String> changedCodes=new HashSet<>(model.form(source).fields().stream().map(EbrCommands.Field::fieldCode).toList());changedCodes.add(changed);Set<Long> touched=new HashSet<>(Set.of(source.getId()));boolean progress;do{progress=false;for(long op:model.port().operationIds(c.organizationId(),ctx.executionUnitId()))for(var sibling:db.forms(c.organizationId(),op)){if(touched.contains(sibling.getId()))continue;var form=model.form(sibling);var rules=model.definition(sibling).rules().stream().filter(r->r.formCode()==null||r.formCode().equals(form.formCode())||form.fields().stream().anyMatch(x->x.fieldCode().equals(r.fieldCode()))).toList();boolean depends=rules.stream().anyMatch(r->EbrDsl.parse(r.expression()).references().stream().anyMatch(changedCodes::contains))||form.fields().stream().filter(x->x.defaultExpr()!=null).anyMatch(x->EbrDsl.parse(x.defaultExpr()).references().stream().anyMatch(changedCodes::contains));if(depends){if(sibling.getRevision()==0&&sibling.getStatus().equals("DRAFT")&&db.values(sibling).isEmpty()&&db.reviews(sibling).isEmpty()){touched.add(sibling.getId());form.fields().forEach(x->changedCodes.add(x.fieldCode()));progress=true;continue;}model.context(sibling,true);sibling=db.store(RuntimeFormEntity.class).lock(c.organizationId(),sibling.getId());model.active(sibling);var before=model.render(sibling,c);invalidate(c,sibling,reason);bump(c,sibling,true);mutations.auditSnapshot(c,"EBR_DEPENDENCY_INVALIDATED","EBR_FORM_INSTANCE",sibling.getId(),before,model.render(sibling,c),reason,null);touched.add(sibling.getId());form.fields().forEach(x->changedCodes.add(x.fieldCode()));progress=true;}}}while(progress);}
 private void review(CurrentPlatformContext c,RuntimeFormEntity f,Review request,String key){if(f.getStatus().equals("DRAFT"))throw new ComplianceException("EBR_FORM_NOT_SUBMITTED","Submit before review");long ruleId=MasterMutation.id(request.reviewRuleId());var rule=model.reviewRule(f,ruleId);String type=rule.path("reviewType").asText();if(!c.hasPermission(type.equals("VERIFY")?"ebr:review:verify":"ebr:review:approve")||!c.hasPermission("ebr:sign")||!c.roleCodes().contains(rule.path("requiredRole").asText()))throw new PermissionException("PERMISSION_DENIED","Frozen review permission and role required");if(!Set.of("PASS","REJECT").contains(request.decision()))throw new IllegalArgumentException("PASS or REJECT required");if(request.comment()!=null&&request.comment().length()>1000)throw new IllegalArgumentException("Review comment too long");if(rule.path("independentUserRequired").asBoolean()&&(Objects.equals(f.getSubmittedBy(),c.actorId())||db.values(f).stream().anyMatch(v->v.getRecordedBy()==c.actorId())))throw new PermissionException("INDEPENDENT_REVIEWER_REQUIRED","Reviewer must differ from every field author and submitter");if(db.reviews(f).stream().anyMatch(r->r.getFormRevision().equals(f.getRevision())&&r.getReviewRuleId()==ruleId))throw new ResourceConflictException("REVIEW_ALREADY_RECORDED","Rule already reviewed for current revision");for(var prior:model.reviewRules(f))if(((type.equals("APPROVE")&&prior.path("reviewType").asText().equals("VERIFY"))||(prior.path("objectScope").equals(rule.path("objectScope"))&&prior.path("objectCode").equals(rule.path("objectCode"))&&prior.path("reviewType").equals(rule.path("reviewType"))&&prior.path("sequenceNo").asInt()<rule.path("sequenceNo").asInt()))&&!model.satisfied(f,prior))throw new ComplianceException("EBR_REVIEW_SEQUENCE","Earlier frozen review required");
  var formObject=model.formSignable(f);var record=json.createObjectNode();record.set("formEvidence",formObject.canonicalRecord());record.set("frozenRule",rule);record.put("reviewRuleId",Long.toString(ruleId));record.put("formRevision",f.getRevision());record.put("reviewerId",Long.toString(c.actorId()));record.put("roleSnapshot",rule.path("requiredRole").asText());record.put("decision",request.decision());record.put("comment",request.comment());record.put("reason",request.reason());var reviewedAt=now();record.put("reviewedAt",EbrRuntimeModel.time(reviewedAt));String objectId=f.getId()+":"+f.getRevision()+":"+ruleId;var object=new SignableObject("EBR_REVIEW_RECORD",objectId,f.getRevision(),record,formObject.evidenceIds());var meaning=SignatureMeaning.valueOf(type);var signed=intents.execute(c,object,meaning,()->signing.sign(new SignCommand(c,object.objectType(),objectId,meaning,object.recordVersion(),request.reauthToken(),"ebr-review-sign:"+PlatformIdempotencyService.digest(key),null)));
  var envelope=json.createObjectNode();envelope.put("objectId",objectId);envelope.put("recordVersion",object.recordVersion());envelope.set("canonicalRecord",record);envelope.set("evidenceIds",json.valueToTree(object.evidenceIds()));envelope.put("signatureId",signed.id());var row=new RuntimeReviewEntity();row.setObjectType("EBR_FORM_INSTANCE");row.setObjectId(f.getId());row.setFormRevision(f.getRevision());row.setReviewRuleId(ruleId);row.setReviewType(type);row.setReviewerId(c.actorId());row.setRoleSnapshot(rule.path("requiredRole").asText());row.setDecision(request.decision());row.setComment(request.comment());row.setReason(request.reason());row.setReviewedAt(reviewedAt);row.setSignatureId(MasterMutation.id(signed.id()));row.setSignatureEvidenceJson(model.encode(envelope));db.store(RuntimeReviewEntity.class).insert(row,c.organizationId(),c.actorId());
  if(request.decision().equals("REJECT")){invalidate(c,f,request.reason(),row.getId());}else{boolean allVerify=model.reviewRules(f).stream().filter(r->r.path("reviewType").asText().equals("VERIFY")).allMatch(r->model.satisfied(f,r));boolean allApprove=model.reviewRules(f).stream().filter(r->r.path("reviewType").asText().equals("APPROVE")).allMatch(r->model.satisfied(f,r));if(type.equals("APPROVE")&&allVerify&&allApprove)f.setStatus("APPROVED");else if(allVerify&&!model.reviewRules(f).stream().filter(r->r.path("reviewType").asText().equals("VERIFY")).toList().isEmpty())f.setStatus("VERIFIED");}bump(c,f,false);
 }
 public EbrCommands.SimulationResult persistRules(CurrentPlatformContext c,RuntimeFormEntity f,String trigger,String key,String reason){var evaluation=model.evaluation(f,trigger,c.roleCodes(),Instant.now());var result=evaluation.result();if(Set.of("ON_CHANGE","ON_SAVE","ON_SUBMIT").contains(trigger))appendDerived(c,f,evaluation.effectiveInputs(),reason);for(var r:result.results()){var row=new RuntimeRuleEntity();row.setFormInstanceId(f.getId());row.setRuleCode(r.ruleCode().length()<=64?r.ruleCode():"EVAL:"+PlatformIdempotencyService.digest(r.ruleCode()).substring(0,59));row.setRuleVersion(r.ruleVersion());row.setTriggerPoint(trigger);row.setPassed(r.passed());row.setSeverity(r.severity());row.setInputSnapshotJson(model.encode(r.inputSnapshot()));row.setOutputJson(model.encode(r.outputValue()));row.setEngineVersion(r.engineVersion());row.setExecutedAt(LocalDateTime.ofInstant(Instant.parse(r.executedAt()),ZoneOffset.UTC));db.store(RuntimeRuleEntity.class).insert(row,c.organizationId(),c.actorId());var def=model.definition(f).rules().stream().filter(x->x.ruleCode().equals(r.ruleCode())).findFirst().orElse(null);if(def!=null&&Boolean.TRUE.equals(def.deviationTrigger())&&(!r.passed()||("DEVIATION".equals(def.ruleType())&&r.outputValue().asBoolean()))){var port=deviations.getIfAvailable();if(port==null)throw new ComplianceException("EBR_DEVIATION_PRODUCER_REQUIRED","Configured deviation requires actual QMS producer");var ctx=model.context(f,false);port.record(c.organizationId(),c.actorId(),ctx.mainBatchId(),ctx.operationId(),f.getId(),r.ruleCode(),json.valueToTree(r.inputSnapshot()),reason,"ebr-rule:"+row.getId());}}
  return result;
 }
 public void appendSource(CurrentPlatformContext c,RuntimeFormEntity f,EbrRuntimeSources.SourceValue value,String key){var field=model.field(f,value.fieldCode());var normalized=EbrRuntimeRules.normalize(field,value.value(),value.unitId(),true);append(c,f,field,value.occurrencePath(),value.value(),normalized,value.unitId(),value.sourceType(),value.sourceRef(),value.reason());bump(c,f,true);invalidateDependents(c,f,value.fieldCode(),value.reason());persistRules(c,f,"ON_CHANGE",key,value.reason());persistRules(c,f,"ON_SAVE",key,value.reason());}
 private void appendDerived(CurrentPlatformContext c,RuntimeFormEntity f,List<EbrCommands.Input> inputs,String reason){for(var field:model.form(f).fields()){if(!Set.of("SYSTEM","DERIVED").contains(field.sourceType())&&field.defaultExpr()==null)continue;var input=inputs.stream().filter(x->x.fieldCode().equals(field.fieldCode())).findFirst().orElse(null);if(input==null)continue;var group=model.definition(f).sections().stream().flatMap(s->s.groups().stream()).filter(g->Objects.equals(g.groupCode(),field.groupCode())).findFirst().orElse(null);boolean repeat=group!=null&&group.repeatMode().equals("LIST");for(int i=0;i<input.values().size();i++){String path=repeat?group.groupCode()+"["+i+"]":"";if(!repeat&&i>0)throw new IllegalArgumentException("Nonrepeat derived value cardinality mismatch");EbrRuntimeRules.occurrence(model.definition(f),field,path);JsonNode computed=input.values().get(i);if(computed.isNumber())computed=TextNode.valueOf(computed.decimalValue().toPlainString());var normalized=EbrRuntimeRules.normalize(field,computed,field.unitId(),true);var current=db.current(f).stream().filter(x->x.getFieldCode().equals(field.fieldCode())&&x.getOccurrencePath().equals(path)).findFirst().orElse(null);if(current==null||!model.parse(current.getNormalizedValueJson()).equals(normalized))append(c,f,field,path,NullNode.instance,normalized,field.unitId(),field.sourceType(),"frozen-definition:"+model.snapshot(f).path("definitionHash").asText(),reason);}}}
 private void bump(CurrentPlatformContext c,RuntimeFormEntity f,boolean revision){if(revision)f.setRevision(Math.addExact(f.getRevision(),1));db.store(RuntimeFormEntity.class).update(f,f.getVersionNo(),c.actorId(),List.of("revision","status","submittedAt","submittedBy"));}
 private static LocalDateTime now(){return LocalDateTime.now(ZoneOffset.UTC).truncatedTo(java.time.temporal.ChronoUnit.MILLIS);}
}
