package com.hospital.mes.ebr.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.ebr.domain.*;
import com.hospital.mes.ebr.infrastructure.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.audit.application.CurrentPlatformContext;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.common.exception.*;
import org.springframework.beans.factory.ObjectProvider;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import static com.hospital.mes.ebr.domain.EbrCommands.*;
@org.springframework.stereotype.Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class EbrRuntimeModel {
 private final EbrRoleEvidence roles;private final EbrRuntimeStore db;private final EbrStore definitions;private final ObjectMapper json;private final ObjectProvider<EbrExecutionPort> execution;private final EbrEngine engine;private final MasterQueryService units;private final SignatureRepository signatures;private final SignatureCanonicalizer canonical;
 public EbrRuntimeModel(EbrRuntimeStore db,EbrStore definitions,ObjectMapper json,ObjectProvider<EbrExecutionPort> execution,EbrEngine engine,MasterQueryService units,SignatureRepository signatures,SignatureCanonicalizer canonical,EbrRoleEvidence roles){this.roles=roles;this.db=db;this.definitions=definitions;this.json=json;this.execution=execution;this.engine=engine;this.units=units;this.signatures=signatures;this.canonical=canonical;}
 public EbrExecutionPort port(){var p=execution.getIfAvailable();if(p==null)throw new ComplianceException("EBR_OPERATION_NOT_ACTIVE","Actual execution producer unavailable");return p;}
 public EbrExecutionPort.OperationContext context(RuntimeFormEntity f,boolean lock){return lock?port().lockOperation(f.getOrgId(),f.getOperationExecutionId()):port().operation(f.getOrgId(),f.getOperationExecutionId());}
 public void active(RuntimeFormEntity f){var c=context(f,false);if(!"IN_PROGRESS".equals(c.operationStatus()))throw new ComplianceException("EBR_OPERATION_NOT_ACTIVE","Operation must be IN_PROGRESS for runtime recording");}
 public JsonNode snapshot(RuntimeFormEntity f){return parse(db.snapshot(f.getOrgId(),context(f,false).mainBatchId()).getSnapshotJson());}
 public Definition definition(RuntimeFormEntity f){return json.convertValue(snapshot(f).path("definition"),Definition.class);}
 public Form form(RuntimeFormEntity f){var source=definitions.store(FormEntity.class).get(f.getOrgId(),f.getFormDefId());return definition(f).forms().stream().filter(x->x.formCode().equals(source.getFormCode())).findFirst().orElseThrow(()->new ComplianceException("EBR_SNAPSHOT_INVALID","Frozen form not found"));}
 public Field field(RuntimeFormEntity f,String code){return form(f).fields().stream().filter(x->x.fieldCode().equals(code)).findFirst().orElseThrow(()->new IllegalArgumentException("Unknown frozen field: "+code));}
 public long fieldId(RuntimeFormEntity f,String code){return definitions.rows(FieldEntity.class,f.getOrgId(),"form_def_id",f.getFormDefId()).stream().filter(x->x.getFieldCode().equals(code)).findFirst().orElseThrow().getId();}
 public static boolean applies(Definition d,Form f,String scope,String code){return switch(scope){case "TEMPLATE"->true;case "FORM"->f.formCode().equals(code);case "FIELD"->f.fields().stream().anyMatch(x->x.fieldCode().equals(code));case "GROUP"->f.fields().stream().anyMatch(x->Objects.equals(x.groupCode(),code));case "SECTION"->d.sections().stream().filter(x->x.sectionCode().equals(code)).flatMap(x->x.groups().stream()).anyMatch(g->f.fields().stream().anyMatch(x->Objects.equals(x.groupCode(),g.groupCode())));default->false;};}
 public List<SignatureRule> signatureRules(RuntimeFormEntity f){var d=definition(f);var form=form(f);return d.signatureRules().stream().filter(r->applies(d,form,r.objectScope(),r.objectCode())).sorted(Comparator.comparing(SignatureRule::sequenceNo)).toList();}
 public List<ObjectNode> reviewRules(RuntimeFormEntity f){var d=definition(f);var form=form(f);long template=snapshot(f).path("templateVersionId").asLong();var source=definitions.rows(ReviewRuleEntity.class,f.getOrgId(),"template_version_id",template);return d.reviewRules().stream().filter(r->applies(d,form,r.objectScope(),r.objectCode())).sorted(Comparator.comparing(ReviewRule::sequenceNo)).map(r->{var row=source.stream().filter(x->x.getObjectScope().equals(r.objectScope())&&x.getObjectCode().equals(r.objectCode())&&x.getReviewType().equals(r.reviewType())&&x.getSequenceNo().equals(r.sequenceNo())).findFirst().orElseThrow(()->new ComplianceException("EBR_SNAPSHOT_INVALID","Frozen review source missing"));ObjectNode n=json.valueToTree(r);n.put("reviewRuleId",row.getId().toString());return n;}).toList();}
 public ObjectNode reviewRule(RuntimeFormEntity f,long id){return reviewRules(f).stream().filter(r->r.path("reviewRuleId").asLong()==id).findFirst().orElseThrow(()->new IllegalArgumentException("Review rule not applicable to frozen form"));}
 public List<Input> inputs(RuntimeFormEntity f){var ctx=context(f,false);Map<String,List<JsonNode>> collected=new TreeMap<>();for(long op:port().operationIds(f.getOrgId(),ctx.executionUnitId()))for(var sibling:db.forms(f.getOrgId(),op))for(var v:db.current(sibling)){JsonNode value=parse(v.getNormalizedValueJson());if(value.isNull())continue;Field field=field(sibling,v.getFieldCode());var list=collected.computeIfAbsent(v.getFieldCode(),k->new ArrayList<>());if(value.isArray())value.forEach(x->list.add(x.deepCopy()));else if(Set.of("NUMBER","TIMER","CALCULATED","INSTRUMENT_VALUE").contains(field.fieldType()))list.add(DecimalNode.valueOf(new BigDecimal(value.asText())));else list.add(value);}return collected.entrySet().stream().map(e->new Input(e.getKey(),List.copyOf(e.getValue()))).toList();}
 public SimulationResult evaluate(RuntimeFormEntity f,String trigger,Set<String> roles,Instant at){return evaluation(f,trigger,roles,at).result();}
 public EbrEngine.RuntimeEvaluation evaluation(RuntimeFormEntity f,String trigger,Set<String> roles,Instant at){var d=definition(f);var selected=form(f);var context=context(f,false);Set<String> codes=selected.fields().stream().map(Field::fieldCode).collect(java.util.stream.Collectors.toSet());var scopedRules=d.rules().stream().filter(r->(r.formCode()==null&&r.fieldCode()==null)||selected.formCode().equals(r.formCode())||(r.fieldCode()!=null&&codes.contains(r.fieldCode()))).toList();var relevant=new Definition(d.sections(),d.forms(),scopedRules,d.signatureRules(),d.reviewRules());var evaluation=engine.evaluateWithValues(relevant,inputs(f),trigger,roles,Map.of("operation",context.operationStatus(),"batch",context.batchStatus(),"form",f.getStatus()),at,(value,from,to)->new BigDecimal(units.convert(f.getOrgId(),MasterMutation.id(from),MasterMutation.id(to),null,value).convertedValue()),snapshot(f).path("templateVersionId").asText()+":"+snapshot(f).path("version").asText());var result=evaluation.result();List<RuleResult> filtered=new ArrayList<>(result.results().stream().filter(r->(!r.ruleCode().startsWith("REQUIRED:")||codes.contains(r.ruleCode().substring(9)))&&(!r.ruleCode().startsWith("DEFAULT:")||codes.contains(r.ruleCode().substring(8)))).toList());if(Set.of("ON_SUBMIT","ON_OPERATION_COMPLETE").contains(trigger))occurrenceChecks(f,d,selected,filtered,at);return new EbrEngine.RuntimeEvaluation(new SimulationResult(filtered.stream().noneMatch(r->!r.passed()&&"BLOCK".equals(r.severity())),List.copyOf(filtered)),evaluation.effectiveInputs());}
 private void occurrenceChecks(RuntimeFormEntity f,Definition d,Form form,List<RuleResult> results,Instant at){var values=db.current(f);Set<String> repeatedGroups=d.sections().stream().flatMap(s->s.groups().stream()).filter(g->"LIST".equals(g.repeatMode())).map(Group::groupCode).collect(java.util.stream.Collectors.toSet());Set<String> repeatedFields=form.fields().stream().filter(field->repeatedGroups.contains(field.groupCode())).map(Field::fieldCode).collect(java.util.stream.Collectors.toSet());results.removeIf(result->result.ruleCode().startsWith("REQUIRED:")&&repeatedFields.contains(result.ruleCode().substring(9)));for(var group:d.sections().stream().flatMap(s->s.groups().stream()).filter(g->"LIST".equals(g.repeatMode())).toList()){var fields=form.fields().stream().filter(x->Objects.equals(x.groupCode(),group.groupCode())).toList();if(fields.isEmpty())continue;Set<Integer> indices=new TreeSet<>();for(var v:values)if(fields.stream().anyMatch(x->x.fieldCode().equals(v.getFieldCode()))&&!parse(v.getNormalizedValueJson()).isNull()){String path=v.getOccurrencePath();int open=path.lastIndexOf('[');if(open>=0)indices.add(Integer.parseInt(path.substring(open+1,path.length()-1)));}boolean valid=indices.size()>=(group.minOccurs()==null?0:group.minOccurs())&&(group.maxOccurs()==null||indices.size()<=group.maxOccurs());for(int i=0;i<indices.size();i++)valid&=indices.contains(i);for(int i:indices)for(var field:fields)if(field.requiredFlag()){String path=group.groupCode()+"["+i+"]";valid&=values.stream().anyMatch(v->v.getFieldCode().equals(field.fieldCode())&&v.getOccurrencePath().equals(path)&&EbrRuntimeRules.hasValue(parse(v.getNormalizedValueJson())));}if(!valid)results.add(new RuleResult("OCCURRENCE:"+group.groupCode(),false,"BLOCK","Required group occurrences or fields missing",inputs(f),NullNode.instance,at.toString(),EbrDsl.ENGINE_VERSION,snapshot(f).path("version").asText()));}}
 public boolean validSignature(long org,long signatureId,String type,String objectId,long version,JsonNode record,List<String> evidence){try{var s=signatures.find(org,signatureId);return s.status()==SignatureStatus.VALID&&s.objectType().equals(type)&&s.objectId().equals(objectId)&&s.recordDigest().equals(canonical.digest(new SignableObject(type,objectId,version,record,evidence)));}catch(NoSuchElementException e){return false;}}
 public SignableObject formSignable(RuntimeFormEntity f){var n=json.createObjectNode();n.put("formId",f.getId().toString());n.put("formRevision",f.getRevision());n.put("definitionHash",snapshot(f).path("definitionHash").asText());var a=n.putArray("values");List<String> evidence=new ArrayList<>();for(var v:db.current(f)){ObjectNode value=valueView(v,false);a.add(value);evidence.add("FieldValueRevision:"+v.getId());}return new SignableObject("EBR_FORM_INSTANCE",f.getId().toString(),f.getRevision(),n,evidence);}
 public boolean satisfied(RuntimeFormEntity f,ObjectNode rule){return db.reviews(f).stream().filter(r->r.getFormRevision().equals(f.getRevision())&&r.getReviewRuleId()==rule.path("reviewRuleId").asLong()&&r.getInvalidatedAt()==null&&r.getDecision().equals("PASS")).anyMatch(this::reviewValid);}
 public boolean reviewValid(RuntimeReviewEntity r){JsonNode envelope=parse(r.getSignatureEvidenceJson());List<String> ids=new ArrayList<>();envelope.path("evidenceIds").forEach(x->ids.add(x.asText()));return validSignature(r.getOrgId(),r.getSignatureId(),"EBR_REVIEW_RECORD",envelope.path("objectId").asText(),r.getFormRevision(),envelope.path("canonicalRecord"),ids);}
 public List<String> blockers(RuntimeFormEntity f){List<String> blocked=new ArrayList<>();if(f.getStatus().equals("DRAFT"))blocked.add("EBR_FORM_NOT_SUBMITTED");for(var r:reviewRules(f))if(!satisfied(f,r))blocked.add("EBR_REVIEW_REQUIRED:"+r.path("reviewRuleId").asText());var object=formSignable(f);var valid=signatures.findValid(f.getOrgId(),object.objectType(),object.objectId());for(var rule:signatureRules(f))if(valid.stream().noneMatch(s->s.meaning().name().equals(rule.meaning())&&s.recordDigest().equals(canonical.digest(object))&&roles.matches(s,rule)))blocked.add("EBR_SIGNATURE_REQUIRED:"+rule.meaning()+":"+rule.objectCode());return List.copyOf(blocked);}
 public ObjectNode summary(RuntimeFormEntity f){var n=json.createObjectNode();var form=form(f);n.put("id",f.getId().toString());n.put("operationExecutionId",f.getOperationExecutionId().toString());n.put("formDefId",f.getFormDefId().toString());n.put("formCode",form.formCode());n.put("formName",form.formName());n.put("occurrenceNo",f.getOccurrenceNo());n.put("status",f.getStatus());n.put("formRevision",f.getRevision());n.put("versionNo",f.getVersionNo());n.put("submittedBy",f.getSubmittedBy()==null?null:f.getSubmittedBy().toString());n.put("submittedAt",time(f.getSubmittedAt()));n.put("definitionHash",snapshot(f).path("definitionHash").asText());return n;}
 public ObjectNode render(RuntimeFormEntity f,CurrentPlatformContext actor){var n=summary(f);var def=form(f);n.set("definition",json.valueToTree(def));var current=db.current(f);var fields=n.putArray("fields");List<RuleResult> rendering=new ArrayList<>(evaluate(f,"ON_CHANGE",actor.roleCodes(),Instant.now()).results());rendering.addAll(evaluate(f,"ON_SAVE",actor.roleCodes(),Instant.now()).results());for(var field:def.fields()){for(String path:renderPaths(f,field,current)){var value=current.stream().filter(v->v.getFieldCode().equals(field.fieldCode())&&v.getOccurrencePath().equals(path)).findFirst().orElse(null);ObjectNode rendered=renderer(field,path,value==null?NullNode.instance:parse(value.getNormalizedValueJson()),value==null?null:value.getId());applyRendererPolicy(f,actor,field,rendered,rendering);fields.add(rendered);}}var values=n.putArray("currentValues");current.forEach(v->values.add(valueView(v,false)));var revisions=n.putArray("valueRevisions");Set<Long> now=current.stream().map(RuntimeValueEntity::getId).collect(java.util.stream.Collectors.toSet());db.values(f).forEach(v->revisions.add(valueView(v,!now.contains(v.getId()))));n.set("ruleExecutions",json.valueToTree(db.rows(RuntimeRuleEntity.class,f.getOrgId(),"form_instance_id",f.getId()).stream().map(this::ruleView).toList()));n.set("reviewRequirements",json.valueToTree(reviewRules(f)));n.set("signatureRequirements",json.valueToTree(signatureRules(f)));n.set("reviews",json.valueToTree(db.reviews(f).stream().map(this::reviewView).toList()));var ids=n.putArray("signatureIds");signatures.findValid(f.getOrgId(),"EBR_FORM_INSTANCE",f.getId().toString()).forEach(s->ids.add(Long.toString(s.id())));var actions=n.putArray("allowedActions");boolean active=context(f,false).operationStatus().equals("IN_PROGRESS");if(active&&f.getStatus().equals("DRAFT")){if(actor.hasPermission("ebr:form:edit"))actions.add("SAVE");if(actor.hasPermission("ebr:form:submit"))actions.add("SUBMIT");}if(active&&actor.hasPermission("ebr:record:correct"))actions.add("CORRECT");if(active&&!f.getStatus().equals("DRAFT")&&(actor.hasPermission("ebr:review:verify")||actor.hasPermission("ebr:review:approve")))actions.add("REVIEW");return n;}
 private List<String> renderPaths(RuntimeFormEntity f,Field field,List<RuntimeValueEntity> current){var group=definition(f).sections().stream().flatMap(s->s.groups().stream()).filter(g->Objects.equals(g.groupCode(),field.groupCode())).findFirst().orElse(null);if(group==null||!group.repeatMode().equals("LIST"))return List.of("");TreeSet<Integer> indices=new TreeSet<>();for(int i=0;i<Math.max(1,group.minOccurs()==null?0:group.minOccurs());i++)indices.add(i);for(var v:current){String prefix=group.groupCode()+"[";if(v.getOccurrencePath().startsWith(prefix))indices.add(Integer.parseInt(v.getOccurrencePath().substring(prefix.length(),v.getOccurrencePath().length()-1)));}return indices.stream().map(i->group.groupCode()+"["+i+"]").toList();}
 private void applyRendererPolicy(RuntimeFormEntity f,CurrentPlatformContext actor,Field field,ObjectNode rendered,List<RuleResult> results){var d=definition(f);Set<String> visibility=new HashSet<>();for(var section:d.sections())if(section.visibilityRuleCode()!=null&&section.groups().stream().anyMatch(g->Objects.equals(g.groupCode(),field.groupCode())))visibility.add(section.visibilityRuleCode());boolean visible=true;String validation=rendered.path("validationState").asText();for(var rule:d.rules()){if(!rule.activeFlag())continue;boolean target=Objects.equals(rule.fieldCode(),field.fieldCode())||(rule.fieldCode()==null&&(rule.formCode()==null||rule.formCode().equals(form(f).formCode())));var result=results.stream().filter(r->r.ruleCode().equals(rule.ruleCode())).reduce((a,b)->b).orElse(null);if(result==null)continue;if(visibility.contains(rule.ruleCode())||(target&&Set.of("VISIBILITY","BRANCH").contains(rule.ruleType())))visible&=result.passed()&&result.outputValue().asBoolean();if(target&&!result.passed())validation="BLOCK".equals(result.severity())?"BLOCK":validation.equals("BLOCK")?"BLOCK":"WARN";}rendered.put("visible",visible);rendered.put("validationState",validation);boolean active=context(f,false).operationStatus().equals("IN_PROGRESS");boolean editable=active&&f.getStatus().equals("DRAFT")&&!rendered.path("readonly").asBoolean()&&actor.hasPermission("ebr:form:edit");rendered.put("readonly",!editable);var actions=(ArrayNode)rendered.path("allowedActions");if(editable)actions.add("EDIT");if(active&&actor.hasPermission("ebr:record:correct")&&!rendered.path("provenance").isEmpty())actions.add("CORRECT");}
 private ObjectNode renderer(Field f,String path,JsonNode value,Long provenance){var n=json.createObjectNode();n.put("fieldCode",f.fieldCode());n.put("occurrencePath",path);n.put("label",f.label());n.put("type",f.fieldType());n.set("value",value);n.put("displayValue",value.isNull()?"":value.isValueNode()?value.asText():value.toString());n.put("unitId",f.unitId());n.put("required",f.requiredFlag());n.put("readonly",f.readonlyFlag()||!Set.of("MANUAL","BARCODE").contains(f.sourceType()));n.put("visible",true);n.put("validationState",f.requiredFlag()&&!EbrRuntimeRules.hasValue(value)?"MISSING":"VALID");n.put("source",f.sourceType());var p=n.putArray("provenance");if(provenance!=null)p.add(provenance.toString());n.putArray("allowedActions");return n;}
 public ObjectNode valueView(RuntimeValueEntity v,boolean superseded){var n=json.createObjectNode();n.put("id",v.getId().toString());n.put("formInstanceId",v.getFormInstanceId().toString());n.put("fieldDefId",v.getFieldDefId().toString());n.put("fieldCode",v.getFieldCode());n.put("occurrencePath",v.getOccurrencePath());n.put("revisionNo",v.getRevisionNo());n.put("previousRevisionId",v.getPreviousRevisionId()==null?null:v.getPreviousRevisionId().toString());n.put("rawValueJson",v.getRawValueJson());n.put("normalizedValueJson",v.getNormalizedValueJson());n.put("unitId",v.getUnitId()==null?null:v.getUnitId().toString());n.put("sourceType",v.getSourceType());n.put("sourceRef",v.getSourceRef());n.put("recordedBy",v.getRecordedBy().toString());n.put("recordedAt",time(v.getRecordedAt()));n.put("changeReason",v.getChangeReason());n.put("superseded",superseded);return n;}
 private ObjectNode ruleView(RuntimeRuleEntity r){var n=json.createObjectNode();n.put("id",r.getId().toString());n.put("formInstanceId",r.getFormInstanceId().toString());n.put("ruleCode",r.getRuleCode());n.put("ruleVersion",r.getRuleVersion());n.put("triggerPoint",r.getTriggerPoint());n.put("passed",r.getPassed());n.put("severity",r.getSeverity());n.put("inputSnapshotJson",r.getInputSnapshotJson());n.put("outputJson",r.getOutputJson());n.put("engineVersion",r.getEngineVersion());n.put("executedAt",time(r.getExecutedAt()));return n;}
 private ObjectNode reviewView(RuntimeReviewEntity r){var n=json.createObjectNode();n.put("id",r.getId().toString());n.put("formInstanceId",r.getObjectId().toString());n.put("formRevision",r.getFormRevision());n.put("reviewRuleId",r.getReviewRuleId().toString());n.put("reviewType",r.getReviewType());n.put("reviewerId",r.getReviewerId().toString());n.put("roleSnapshot",r.getRoleSnapshot());n.put("decision",r.getDecision());n.put("comment",r.getComment());n.put("reason",r.getReason());n.put("reviewedAt",time(r.getReviewedAt()));n.put("signatureId",r.getSignatureId().toString());n.put("invalidatedAt",time(r.getInvalidatedAt()));n.put("invalidationReason",r.getInvalidationReason());return n;}
 public JsonNode parse(String s){if(s==null)return NullNode.instance;try{return json.readTree(s);}catch(java.io.IOException e){throw new IllegalStateException("Corrupt eBR evidence",e);}}
 public String encode(Object value){try{return json.writeValueAsString(value);}catch(java.io.IOException e){throw new IllegalStateException(e);}}
 public static String time(LocalDateTime t){return t==null?null:t.toInstant(ZoneOffset.UTC).toString();}
}
