<script setup lang="ts">
import {computed,ref,onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {useAuthStore} from '../../stores/auth'
import {queryAuditEvents} from '../../api/audit'
import type {AuditEvent} from '../../types/audit'
import {AppstoreOutlined,RightOutlined} from '@ant-design/icons-vue'
const router=useRouter(),auth=useAuthStore()
const activity=ref<AuditEvent[]>([]),activityError=ref('')
onMounted(async()=>{if(!auth.can('audit:view'))return;try{activity.value=(await queryAuditEvents({page:0,size:5})).items}catch{activityError.value='近期受控活动暂时无法加载'}})
const entries=computed(()=>router.getRoutes().filter(r=>r.meta.permission&&auth.can(String(r.meta.permission))&&!r.path.includes(':')&&!r.path.endsWith('/create')&&r.name!=='change-password').filter(r=>r.meta.mode==='list'||r.meta.resource||['users','roles','audit','trace','integration-operations','ebr-templates','qc-specifications','wms-receipts','wms-issues'].includes(String(r.name))))
const groups=computed(()=>{const map=new Map<string,typeof entries.value>();for(const r of entries.value){const domain=r.path.startsWith('/master')||r.path.startsWith('/process')?'基础主数据':r.path.startsWith('/wms')?'仓库管理':r.path.startsWith('/production')||r.path.startsWith('/ebr')?'生产管理':r.path.startsWith('/quality')||r.path.startsWith('/deviations')?'质量管理':'系统管理';map.set(domain,[...(map.get(domain)??[]),r])}return [...map].map(([title,routes])=>({title,routes}))})
</script>
<template><main class="admin-page master-page dashboard" data-ui-template="Specialized"><header class="admin-page-header"><div><h1>工作台</h1><p>{{auth.identity?.displayName}} · 当前可访问的业务入口</p></div></header><a-alert v-if="!entries.length" type="info" message="当前账号暂无业务菜单权限，请联系管理员。" show-icon/><a-card v-for="group in groups" :key="group.title" :title="group.title" class="form-section"><div class="workspace-links"><a-button v-for="item in group.routes" :key="item.path" @click="router.push(item.path)"><AppstoreOutlined/><span>{{item.meta.title}}</span><RightOutlined/></a-button></div></a-card><a-card v-if="auth.can('audit:view')" title="近期受控活动" class="form-section"><a-alert v-if="activityError" type="warning" :message="activityError"/><a-list v-else :data-source="activity"><template #renderItem="{item}"><a-list-item><a-list-item-meta :title="`${item.objectType} · ${item.action}`" :description="`${item.occurredAt} · ${item.reason??'—'}`"/><a-button type="link" @click="router.push({path:'/audit',query:{objectType:item.objectType,objectId:item.objectId}})">查看审计</a-button></a-list-item></template><template #emptyText>暂无受控活动</template></a-list></a-card><p class="section-hint">入口按当前账号权限显示；不展示未经服务端提供的运行状态或业务指标。</p></main></template>
<style scoped>.workspace-links{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:16px}.workspace-links .ant-btn{height:56px;display:flex;align-items:center;gap:12px;text-align:left}.workspace-links .ant-btn span:nth-child(2){flex:1}.workspace-links .anticon{color:var(--mes-ui-primary)}@media(max-width:767px){.workspace-links{grid-template-columns:1fr}}</style>
