package com.hospital.mes.qc.domain;
import static org.assertj.core.api.Assertions.*;
import java.math.BigDecimal;
import java.util.*;
import org.junit.jupiter.api.Test;
class QcSpecificationRulesTest {
 @Test void onlyNamedForwardTransitions(){assertThat(QcSpecificationRules.transition("DRAFT","APPROVE")).isEqualTo("APPROVED");assertThat(QcSpecificationRules.transition("APPROVED","RETIRE")).isEqualTo("RETIRED");for(String s:List.of("APPROVED","RETIRED"))assertThatThrownBy(()->QcSpecificationRules.requireDraft(s)).hasMessageContaining("DRAFT");assertThatThrownBy(()->QcSpecificationRules.transition("DRAFT","RETIRE")).hasMessageContaining("transition");}
 @Test void numericBoundsAreInclusiveAndMissingValueNeverPasses(){var i=item("NUMERIC","1","3","9",null);QcSpecificationRules.validateItems(List.of(i));assertThat(QcSpecificationRules.numericPass(i,new BigDecimal("1"))).isTrue();assertThat(QcSpecificationRules.numericPass(i,new BigDecimal("3"))).isTrue();assertThat(QcSpecificationRules.numericPass(i,null)).isFalse();assertThat(QcSpecificationRules.numericPass(i,new BigDecimal("3.1"))).isFalse();}
 @Test void shapePrecisionAndDuplicateCodesFailClosed(){for(var i:List.of(item("NUMERIC",null,null,"9",null),item("NUMERIC","4","2","9",null),item("NUMERIC","0.0000001",null,"9",null),item("NUMERIC","1",null,"9","text"),item("TEXT","1",null,null,"white"),item("TEXT",null,null,null," ")))assertThatThrownBy(()->QcSpecificationRules.validateItems(List.of(i))).isInstanceOf(com.hospital.mes.common.exception.ValidationException.class);var i=item("TEXT",null,null,null,"white powder");QcSpecificationRules.validateItems(List.of(i));assertThatThrownBy(()->QcSpecificationRules.validateItems(List.of(i,i))).hasMessageContaining("Duplicate");}
 @Test void strictLockAndRedactedToken(){assertThat(QcSpecificationRules.expected("\"2\"",2L)).isEqualTo(2);assertThatThrownBy(()->QcSpecificationRules.expected("2",2L)).hasMessageContaining("quoted");assertThatThrownBy(()->QcSpecificationRules.expected("\"2\"",1L)).hasMessageContaining("match");assertThat(new QcCommands.SignVersion(2L,"approval","secret-value").toString()).doesNotContain("secret-value");}
 @Test void unknownAndReadOnlyFieldsAreRejectedWithPermissiveGlobalMapper() throws Exception {var mapper=new com.fasterxml.jackson.databind.ObjectMapper().disable(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);assertThatThrownBy(()->mapper.readValue("{\"materialId\":\"1\",\"status\":\"APPROVED\"}",QcCommands.CreateSpecification.class)).hasMessageContaining("Unknown field");assertThatThrownBy(()->mapper.readValue("{\"itemCode\":\"A\",\"specificationItemId\":\"7\"}",QcCommands.Item.class)).hasMessageContaining("Unknown field");assertThat(mapper.writeValueAsString(new QcCommands.SignVersion(0L,"reason","secret-value"))).doesNotContain("secret-value");}
 @Test void oneSidedBoundsHaveInclusiveEndpointAndMissingValuesNeverPass(){
  for(var i:List.of(item("NUMERIC","1",null,"9",null),item("NUMERIC",null,"1","9",null))){QcSpecificationRules.validateItems(List.of(i));assertThat(QcSpecificationRules.numericPass(i,new BigDecimal("1"))).isTrue();assertThat(QcSpecificationRules.numericPass(i,null)).isFalse();}
  assertThat(QcSpecificationRules.numericPass(item("NUMERIC","1",null,"9",null),new BigDecimal("0.999999"))).isFalse();assertThat(QcSpecificationRules.numericPass(item("NUMERIC",null,"1","9",null),new BigDecimal("1.000001"))).isFalse();
 }
 private QcCommands.Item item(String type,String lo,String hi,String unit,String text){return new QcCommands.Item("ASSAY","Assay",true,type,lo,hi,unit,text,"M1","1");}
}
