package com.hospital.mes.qms.infrastructure;
import java.util.*;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.springframework.stereotype.Component;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
@Component @ConditionalOnProperty(prefix="spring.datasource",name="url")
public class IncomingMappers {
 private final Map<String,BaseMapper<? extends IncomingRow>> mappers;
 public IncomingMappers(InspectionRequestRowMapper inspectionRequest, InspectionRequestItemRowMapper inspectionRequestItem, SamplingTaskRowMapper samplingTask, SamplingDetailRowMapper samplingDetail, SampleRowMapper sample, InspectionTaskRowMapper inspectionTask, InspectionItemRowMapper inspectionItem, TestExecutionRowMapper testExecution, TestResultRevisionRowMapper testResultRevision, InspectionReportRowMapper inspectionReport, InspectionReportItemRowMapper inspectionReportItem, DeviationRowMapper deviation, ReleaseDecisionRowMapper releaseDecision){mappers=Map.ofEntries(Map.entry("qms_inspection_request",inspectionRequest),Map.entry("qms_inspection_request_item",inspectionRequestItem),Map.entry("qms_sampling_task",samplingTask),Map.entry("qms_sampling_detail",samplingDetail),Map.entry("qms_sample",sample),Map.entry("qms_inspection_task",inspectionTask),Map.entry("qms_inspection_item",inspectionItem),Map.entry("qms_test_execution",testExecution),Map.entry("qms_test_result_revision",testResultRevision),Map.entry("qms_inspection_report",inspectionReport),Map.entry("qms_inspection_report_item",inspectionReportItem),Map.entry("qms_deviation",deviation),Map.entry("qms_release_decision",releaseDecision));}
 @SuppressWarnings("unchecked") public BaseMapper<IncomingRow> mapper(String table){var m=mappers.get(table);if(m==null)throw new IllegalArgumentException("Unknown incoming table");return (BaseMapper<IncomingRow>)(BaseMapper<?>)m;}
 public IncomingRow create(String table){return switch(table){case "qms_inspection_request" -> new InspectionRequestRow();case "qms_inspection_request_item" -> new InspectionRequestItemRow();case "qms_sampling_task" -> new SamplingTaskRow();case "qms_sampling_detail" -> new SamplingDetailRow();case "qms_sample" -> new SampleRow();case "qms_inspection_task" -> new InspectionTaskRow();case "qms_inspection_item" -> new InspectionItemRow();case "qms_test_execution" -> new TestExecutionRow();case "qms_test_result_revision" -> new TestResultRevisionRow();case "qms_inspection_report" -> new InspectionReportRow();case "qms_inspection_report_item" -> new InspectionReportItemRow();case "qms_deviation" -> new DeviationRow();case "qms_release_decision" -> new ReleaseDecisionRow();default -> throw new IllegalArgumentException("Unknown incoming table");};}
}
