package com.hospital.mes.release.application;
import com.hospital.mes.reporting.application.*;import com.hospital.mes.reporting.infrastructure.*;import org.apache.pdfbox.Loader;import org.apache.pdfbox.text.PDFTextStripper;import org.junit.jupiter.api.Test;import java.util.*;import java.nio.file.*;import static org.junit.jupiter.api.Assertions.*;
class BookPdfComposerTest {
 @Test void realFopWordRecordsBecomeChineseBookWithContentsBookmarksAndEveryRow()throws Exception{var word=new RecordTableDocx();var rows=new ArrayList<List<String>>();for(int i=1;i<=75;i++)rows.add(List.of("合成检查项目"+i,"按冻结规程记录，较长中文规定用于验证自动换行和跨页表格；不得自动确认正常。","合成实际值"+i));byte[] docx=word.create("合成配制记录","合成数据 · 草稿",List.of("检查项目","标准/规定","实际记录"),rows);byte[] body=new Docx4jFopPdfConverter().convert(docx);byte[] book=new BookPdfComposer().compose(List.of("品名：合成制剂","规格：合成规格A","批号：SYNTHETIC-ONLY"),List.of(new BookPdfComposer.Part("配制记录",body),new BookPdfComposer.Part("分装包装记录",new Docx4jFopPdfConverter().convert(word.create("分装包装记录","合成数据 — 草稿",List.of("检验项目","标准/规定","实际记录"),rows)))),"REVIEW_COPY");if(System.getProperty("mes.book.evidence")!=null){Files.createDirectories(Path.of(System.getProperty("mes.book.evidence")));Files.write(Path.of(System.getProperty("mes.book.evidence"),"diagnostic-fop.pdf"),book);}try(var pdf=Loader.loadPDF(book)){assertTrue(pdf.getNumberOfPages()>4);assertNotNull(pdf.getDocumentCatalog().getDocumentOutline().getFirstChild());var headerStripper=new PDFTextStripper();headerStripper.setStartPage(4);headerStripper.setEndPage(4);assertTrue(headerStripper.getText(pdf).replaceAll("\\s+","").contains("标准/规定"),"Real continuation page must repeat Word table header");String text=new PDFTextStripper().getText(pdf).replaceAll("\\s+","");assertTrue(text.contains("生产批记录册"));assertTrue(text.contains("目录"));assertTrue(text.contains("合成检查项目75"),text.substring(0,Math.min(text.length(),2500)));assertTrue(text.contains("草稿"));assertTrue(text.contains("第"+pdf.getNumberOfPages()+"/"+pdf.getNumberOfPages()+"页"));}String dir=System.getProperty("mes.book.evidence");if(dir!=null){Files.createDirectories(Path.of(dir));Files.write(Path.of(dir,"synthetic-record.docx"),docx);Files.write(Path.of(dir,"synthetic-book-fop.pdf"),book);}}
 @Test void realLibreOfficeBodyIsVerifiedSeparately()throws Exception{String home=System.getProperty("mes.book.office");org.junit.jupiter.api.Assumptions.assumeTrue(home!=null);var docx=new RecordTableDocx().create("合成分装记录","合成数据 · 草稿",List.of("项目","实际"),List.of(List.of("包装数量","合成75")));var body=new LibreOfficePdfConverter(home).convert(docx);var bytes=new BookPdfComposer().compose(List.of("合成数据验收"),List.of(new BookPdfComposer.Part("分装记录",body)),"REVIEW_COPY");if(System.getProperty("mes.book.evidence")!=null){Files.createDirectories(Path.of(System.getProperty("mes.book.evidence")));Files.write(Path.of(System.getProperty("mes.book.evidence"),"diagnostic-lo.pdf"),bytes);}try(var pdf=Loader.loadPDF(bytes)){String extracted=new PDFTextStripper().getText(pdf).replaceAll("\\s+","");assertTrue(extracted.contains("合成75"),extracted);}String dir=System.getProperty("mes.book.evidence");if(dir!=null)Files.write(Path.of(dir,"synthetic-book-libreoffice.pdf"),bytes);}
 @Test void imageAppendixProducesRealPdfAndRejectsInvalidBytes()throws Exception{var image=new java.awt.image.BufferedImage(100,200,java.awt.image.BufferedImage.TYPE_INT_RGB);var out=new java.io.ByteArrayOutputStream();javax.imageio.ImageIO.write(image,"png",out);var composer=new BookPdfComposer();try(var pdf=Loader.loadPDF(composer.imageAttachment(out.toByteArray()))){assertEquals(1,pdf.getNumberOfPages());assertTrue(pdf.getPage(0).getResources().getXObjectNames().iterator().hasNext());}assertThrows(IllegalArgumentException.class,()->composer.imageAttachment(new byte[]{1,2,3}));}
 @Test void corruptSourcePdfFailsWithoutArtifact(){assertThrows(IllegalStateException.class,()->new BookPdfComposer().compose(List.of("合成"),List.of(new BookPdfComposer.Part("错误",new byte[]{1,2,3})),"REVIEW_COPY"));}

 @Test void longEvidenceIdentifiersStayWithinPageAndRetainEveryCharacter()throws Exception{
  String digest="0123456789abcdef".repeat(4),identifier="PREPARE_ACTUAL_LONG_SOURCE_IDENTIFIER_20261008";
  var bytes=new Docx4jFopPdfConverter().convert(new RecordTableDocx().create("合成排版边界验收","来源摘要："+digest,List.of("字段标识","项目","标准","实际","单位","来源","明细"),List.of(List.of(identifier,"中文长字段","保持全部证据","实际已填写的合成值","毫升","MANUAL",digest))));
  try(var pdf=Loader.loadPDF(bytes)){
   var outside=new ArrayList<String>();
   var stripper=new PDFTextStripper(){@Override protected void processTextPosition(org.apache.pdfbox.text.TextPosition pos){if(pos.getXDirAdj()+pos.getWidthDirAdj()>pdf.getPage(getCurrentPageNo()-1).getMediaBox().getWidth()-35)outside.add(pos.getUnicode());super.processTextPosition(pos);}};
   String text=stripper.getText(pdf).replaceAll("\\s+","");
   assertTrue(outside.isEmpty(),"Text must not cross right page edge: "+outside);
   assertTrue(text.contains(identifier));assertTrue(text.contains(digest));
  }
 }
 @Test void directoryKeepsDistinctExecutionSuffixesAndFullBookmarks()throws Exception{
  String prefix="PREPARE / SYNTHETIC_BOOK_LONG_EXECUTION_20261008_";
  var word=new RecordTableDocx();byte[] body=new Docx4jFopPdfConverter().convert(word.create("合成目录验收","草稿",List.of("项目"),List.of()));
  var bytes=new BookPdfComposer().compose(List.of("合成"),List.of(new BookPdfComposer.Part(prefix+"/1",body),new BookPdfComposer.Part(prefix+"/2",body)),"REVIEW_COPY");
  try(var pdf=Loader.loadPDF(bytes)){var strip=new PDFTextStripper();strip.setStartPage(2);strip.setEndPage(2);String toc=strip.getText(pdf);assertTrue(toc.contains("/1"));assertTrue(toc.contains("/2"));var mark=pdf.getDocumentCatalog().getDocumentOutline().getFirstChild();assertEquals(prefix+"/1",mark.getTitle());assertEquals(prefix+"/2",mark.getNextSibling().getTitle());}
 }

}
