package com.hospital.mes.process.integration;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import com.fasterxml.jackson.databind.*;
import com.hospital.mes.audit.application.*;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.process.application.*;
import com.hospital.mes.process.domain.ProcessCommands.*;
import com.hospital.mes.masterdata.application.*;
import java.time.*;import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.http.MediaType;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
/** Native persistent DEV: every unique fixture and command is rolled back. Never modifies shared seeds. */
@SpringBootTest @ActiveProfiles("ci") @AutoConfigureMockMvc @Transactional
class ProcessIT {
 @Autowired ProcessService service;@Autowired ProcessQueryService query;@Autowired UnitService units;@Autowired UnitConversionService conversions;@Autowired MaterialService materials;
 @Autowired JdbcTemplate jdbc;@Autowired ObjectMapper json;@Autowired MockMvc mvc;@Autowired PlatformTransactionManager transactions;@Autowired SignatureTransactionService signatures;
 @MockitoBean CurrentPlatformContextResolver contexts;@MockitoBean ReauthenticationPort reauth;@MockitoSpyBean AuditApplicationService audit;@MockitoSpyBean com.hospital.mes.process.infrastructure.ProcessStore store;
 String suffix,unit,material;long creator,approver;Set<String> permissions;CurrentPlatformContext context;
 @BeforeEach void setup(){suffix=UUID.randomUUID().toString().replace("-","").substring(0,12);permissions=new HashSet<>(Set.of("ebr:sign"));for(String p:List.of("master:product:","master:uom:","master:material:","process:package:"))for(String a:List.of("view","create","update","edit","submit","approve","publish"))permissions.add(p+a);creator=actor("proc_c"+suffix);approver=actor("proc_a"+suffix);as(1,creator);when(reauth.consume(anyString(),any())).thenReturn(new ConsumedReauthentication(Instant.now(),"PASSWORD"));unit=units.create(new UnitCommands.Create("PU"+suffix,"Process unit","MASS",3),key()).path("id").asText();var body=Map.of("materialCode","PM"+suffix,"materialName","Process material","materialType","RAW","baseUnitId",unit,"lotControlled",true);material=materials.create(json.convertValue(body,MaterialCommands.Create.class),key()).path("id").asText();}
 long actor(String name){jdbc.update("INSERT INTO sys_user(login_name,login_name_normalized,display_name,password_hash,enabled,must_change_password) VALUES(?,?,?,?,TRUE,FALSE)",name,name,"Process rollback actor","test-only");return jdbc.queryForObject("SELECT id FROM sys_user WHERE login_name_normalized=?",Long.class,name);}
 void as(long org,long actor){context=new CurrentPlatformContext(org,actor,Set.of("PROCESS_TEST"),permissions,"session","proc-"+suffix);when(contexts.current()).thenReturn(context);}
 String key(){return UUID.randomUUID().toString();}
 JsonNode pkg(){var product=service.createProduct(new ProductCreate("PP"+suffix,"Product",null,null,unit),key());return service.createPackage(new PackageCreate(product.path("id").asText(),"PKG"+suffix),key());}
 FormulaSave formula(long version,String u){return new FormulaSave(version,"BOM evidence","F"+suffix,"10",unit,List.of(new FormulaLine(1,material,"2",u,"0",true)));}
 RouteSave route(long version,boolean cycle){var param=new Parameter("TEMP","Temperature","HYBRID",unit,"1","3");return new RouteSave(version,"Route evidence","R"+suffix,List.of(new Operation("A","Mix",1,null,new CompletionRule("PARAMETERS_WITHIN_LIMITS",null),cycle?List.of("B"):List.of(),null,true,List.of(param)),new Operation("B","Fill",2,null,null,List.of("A"),null,false,List.of())));}
 JsonNode defined(JsonNode p){String id=p.path("selectedVersion").path("id").asText();service.saveFormula(id,formula(0,unit),null,key());return service.saveRoute(id,route(1,false),null,key());}
 JsonNode transition(JsonNode v,String action){return service.transition(v.path("id").asText(),action,new Transition(v.path("versionNo").asLong(),"Controlled "+action,"test-token"),null,key());}
 @Test void tcProc001And004SignedLifecycleImmutableContentAndCopy(){var p=pkg();var draft=defined(p);String id=draft.path("id").asText();assertThat(service.lint(id,new Transition(2L,"Validation",null),null,key()).path("valid").asBoolean()).isTrue();assertThat(draft.path("route").path("operations").get(0).path("completionRule").has("rules")).isFalse();var submitted=transition(draft,"SUBMIT");as(1,approver);String approvalKey=key();var command=new Transition(submitted.path("versionNo").asLong(),"QA approval","test-token");var approved=service.transition(id,"APPROVE",command,null,approvalKey);assertThat(service.transition(id,"APPROVE",command,null,approvalKey)).isEqualTo(approved);verify(reauth,times(1)).consume(eq("test-token"),argThat(b->b.userId()==approver&&b.objectType().equals("ProcessVersion")&&b.objectId().equals(id)&&b.recordVersion()==1));long signature=approved.path("approval").path("signatureId").asLong();assertThat(signatures.verify(1,signature)).isTrue();var snapshot=query.requireUsable(1,Long.parseLong(id));var published=transition(approved,"PUBLISH");assertThat(published.path("status").asText()).isEqualTo("EFFECTIVE");assertThat(signatures.verify(1,signature)).isTrue();assertThat(query.requireUsable(1,Long.parseLong(id))).isEqualTo(snapshot);assertThatThrownBy(()->service.saveFormula(id,formula(5,unit),null,key())).hasMessageContaining("draft");assertThatThrownBy(()->service.saveRoute(id,route(5,false),null,key())).hasMessageContaining("draft");var copied=service.createVersion(p.path("id").asText(),new VersionCreate(0L,"new revision",id),null,key());assertThat(copied.path("selectedVersion").path("businessVersion").asInt()).isEqualTo(2);assertThat(copied.path("selectedVersion").path("formula").path("items")).hasSize(1);assertThat(query.snapshot(1,Long.parseLong(id))).isEqualTo(snapshot);assertThat(service.packages(0,20,"PKG"+suffix,Map.of("status","EFFECTIVE")).items().getFirst().path("selectedVersion").path("id").asText()).isEqualTo(id);assertThatThrownBy(()->service.createVersion(p.path("id").asText(),new VersionCreate(1L,"duplicate draft",null),null,key())).hasMessageContaining("existing draft");}
 @Test void tcProc002CycleBlockedWithConcretePathAndNoTransition(){var p=pkg();String id=p.path("selectedVersion").path("id").asText();service.saveFormula(id,formula(0,unit),null,key());service.saveRoute(id,route(1,true),null,key());assertThatThrownBy(()->service.lint(id,new Transition(2L,"Validate",null),null,key())).hasMessageContaining("cycle");assertThatThrownBy(()->service.transition(id,"SUBMIT",new Transition(2L,"Submit",null),null,key())).hasMessageContaining("cycle");assertThat(jdbc.queryForObject("SELECT status FROM proc_package_version WHERE id=?",String.class,id)).isEqualTo("DRAFT");}
 @Test void tcProc003MaterialUomIntegrationAndUnavailableMaterial(){var p=pkg();String id=p.path("selectedVersion").path("id").asText();String volume=units.create(new UnitCommands.Create("VOL"+suffix,"Volume","VOLUME",3),key()).path("id").asText();assertThatThrownBy(()->service.saveFormula(id,formula(0,volume),null,key())).hasMessageContaining("formula.items[1]");conversions.create(new UnitConversionCommands.Create(volume,unit,"2",material),key());assertThat(service.saveFormula(id,formula(0,volume),null,key()).path("formula").path("items")).hasSize(1);jdbc.update("UPDATE md_material SET status='INACTIVE' WHERE id=?",material);assertThatThrownBy(()->service.saveFormula(id,formula(1,volume),null,key())).hasMessageContaining("unavailable");}
 @Test void permissionsOrganizationClosedDtoAndApi200() throws Exception {var p=pkg();String id=p.path("id").asText();mvc.perform(get("/api/v1/process-packages/"+id).with(user("test").authorities(new SimpleGrantedAuthority("process:package:view")))).andExpect(status().isOk()).andExpect(jsonPath("$.data.selectedVersion.status").value("DRAFT"));mvc.perform(post("/api/v1/products").with(user("test").authorities(new SimpleGrantedAuthority("master:product:create"))).header("Idempotency-Key",key()).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(new ProductCreate("API"+suffix,"Api",null,null,unit)))).andExpect(status().isOk());mvc.perform(put("/api/v1/process-versions/"+p.path("selectedVersion").path("id").asText()+"/formula").with(user("test").authorities(new SimpleGrantedAuthority("process:package:edit"))).header("Idempotency-Key",key()).contentType(MediaType.APPLICATION_JSON).content("{\"unexpected\":true}")).andExpect(status().isBadRequest());mvc.perform(get("/api/v1/process-packages/"+id).with(user("test").authorities(new SimpleGrantedAuthority("master:product:view")))).andExpect(status().isForbidden());as(2,creator);assertThatThrownBy(()->service.getPackage(id,null)).isInstanceOf(NoSuchElementException.class);}
 @Test void staleWritesReplayRetainedRowsAndOneDraftConstraint(){var p=pkg();String id=p.path("selectedVersion").path("id").asText();String k=key();var saved=service.saveFormula(id,formula(0,unit),null,k);assertThat(service.saveFormula(id,formula(0,unit),null,k)).isEqualTo(saved);assertThatThrownBy(()->service.saveFormula(id,formula(0,unit),null,key())).hasMessageContaining("Reload");assertThatThrownBy(()->service.saveFormula(id,new FormulaSave(1L,"omit","F","1",unit,List.of()),null,key())).hasMessageContaining("retained");assertThatThrownBy(()->jdbc.update("INSERT INTO proc_package_version(org_id,created_by,updated_by,package_id,version,status) VALUES(1,?,?,?,2,'DRAFT')",creator,creator,p.path("id").asLong())).isInstanceOf(org.springframework.dao.DuplicateKeyException.class);permissions.remove("process:package:edit");as(1,creator);assertThatThrownBy(()->service.saveFormula(id,formula(0,unit),null,k)).hasMessageContaining("Permission required");}
 @Test void creatorCannotApproveAndReauthFailurePreservesSubmitted(){var submitted=transition(defined(pkg()),"SUBMIT");assertThatThrownBy(()->transition(submitted,"APPROVE")).hasMessageContaining("cannot approve");verifyNoInteractions(reauth);as(1,approver);when(reauth.consume(anyString(),any())).thenThrow(new com.hospital.mes.common.exception.ComplianceException("REAUTH_INVALID","Invalid bound challenge"));assertThatThrownBy(()->transition(submitted,"APPROVE")).hasMessageContaining("challenge");assertThat(jdbc.queryForObject("SELECT status FROM proc_package_version WHERE id=?",String.class,submitted.path("id").asText())).isEqualTo("SUBMITTED");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature WHERE object_type='ProcessVersion' AND object_id=?",Long.class,submitted.path("id").asText())).isZero();}
 @Test void approvalAuditFailureRollsBackSignatureStateAndIdempotency(){var submitted=transition(defined(pkg()),"SUBMIT");as(1,approver);String id=submitted.path("id").asText(),k=key();var tx=new TransactionTemplate(transactions);tx.setPropagationBehavior(org.springframework.transaction.TransactionDefinition.PROPAGATION_NESTED);doAnswer(inv->{var command=(com.hospital.mes.audit.domain.AuditCommand)inv.getArgument(0);if(command.action().equals("ProcessVersion:APPROVE"))throw new IllegalStateException("injected approval audit failure");return inv.callRealMethod();}).when(audit).append(any());assertThatThrownBy(()->tx.execute(t->service.transition(id,"APPROVE",new Transition(3L,"Approve","test-token"),null,k))).hasMessageContaining("injected approval audit failure");assertThat(jdbc.queryForObject("SELECT status FROM proc_package_version WHERE id=?",String.class,id)).isEqualTo("SUBMITTED");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature WHERE object_type='ProcessVersion' AND object_id=?",Long.class,id)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,k)).isZero();}
 @Test void physicalMigrationChainAndApprovedSchema(){assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM flyway_schema_history WHERE success=0",Long.class)).isZero();assertThat(jdbc.queryForObject("SELECT MAX(CAST(version AS UNSIGNED)) FROM flyway_schema_history WHERE success=1",Long.class)).isGreaterThanOrEqualTo(11);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='proc_operation_def' AND column_name IN ('predecessor_codes_json','required_equipment_type','clearance_required')",Long.class)).isEqualTo(3);}

 @Test void explicitResignRequiresImmediatePredecessorAndRollsBackRejectedAttempt() {
  var submitted=transition(defined(pkg()),"SUBMIT");
  as(1,approver);
  String id=submitted.path("id").asText();
  var consumed=new ConsumedReauthentication(Instant.now(),"PASSWORD");
  var first=signatures.signInTransaction(new SignCommand(context,"ProcessVersion",id,SignatureMeaning.APPROVE,1,"consumed",key(),null),consumed);
  long firstId=Long.parseLong(first.id());
  signatures.invalidate(context,firstId,0L,"First approval invalidated for regression fixture");
  var second=signatures.signInTransaction(new SignCommand(context,"ProcessVersion",id,SignatureMeaning.APPROVE,1,"consumed",key(),firstId),consumed);
  long secondId=Long.parseLong(second.id());
  signatures.invalidate(context,secondId,0L,"Second approval invalidated for regression fixture");
  Long auditBefore=jdbc.queryForObject("SELECT COUNT(*) FROM gxp_audit_event WHERE org_id=1 AND object_type='ProcessVersion' AND object_id=?",Long.class,id);
  String rejectedKey=key();
  var tx=new TransactionTemplate(transactions);
  tx.setPropagationBehavior(org.springframework.transaction.TransactionDefinition.PROPAGATION_NESTED);
  assertThatThrownBy(()->tx.execute(t->signatures.signInTransaction(new SignCommand(context,"ProcessVersion",id,SignatureMeaning.APPROVE,1,"consumed",rejectedKey,firstId),consumed)))
      .isInstanceOf(com.hospital.mes.common.exception.ResourceConflictException.class)
      .hasMessageContaining("Superseded signature");
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature WHERE org_id=1 AND object_type='ProcessVersion' AND object_id=?",Long.class,id)).isEqualTo(2L);
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_audit_event WHERE org_id=1 AND object_type='ProcessVersion' AND object_id=?",Long.class,id)).isEqualTo(auditBefore);
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,rejectedKey)).isZero();
  var third=signatures.signInTransaction(new SignCommand(context,"ProcessVersion",id,SignatureMeaning.APPROVE,1,"consumed",key(),secondId),consumed);
  assertThat(third.revokedSignatureId()).isEqualTo(Long.toString(secondId));
  assertThat(signatures.verify(1,Long.parseLong(third.id()))).isTrue();
  assertThat(jdbc.queryForList("SELECT status FROM gxp_signature WHERE id IN (?,?) ORDER BY id",String.class,firstId,secondId)).containsExactly("INVALIDATED","INVALIDATED");
  assertThat(jdbc.queryForObject("SELECT record_digest FROM gxp_signature WHERE id=?",String.class,firstId)).isEqualTo(first.recordDigest());
  assertThat(jdbc.queryForObject("SELECT record_digest FROM gxp_signature WHERE id=?",String.class,secondId)).isEqualTo(second.recordDigest());
 }

 @Test void simultaneousWriterRejectsStaleVersionAfterWaitingForPackageLock() throws Exception {
  var tx=new TransactionTemplate(transactions);tx.setPropagationBehavior(org.springframework.transaction.TransactionDefinition.PROPAGATION_REQUIRES_NEW);
  long[] ids=tx.execute(t->{long a=actor("prace_"+suffix);jdbc.update("INSERT INTO md_unit(org_id,created_by,updated_by,unit_code,unit_name,dimension,scale) VALUES(1,?,?,?,'Race fixture','MASS',3)",a,a,"PRU"+suffix);long u=jdbc.queryForObject("SELECT id FROM md_unit WHERE unit_code=?",Long.class,"PRU"+suffix);jdbc.update("INSERT INTO md_product(org_id,created_by,updated_by,product_code,product_name,base_unit_id,status) VALUES(1,?,?,?,'Race fixture',?,'ACTIVE')",a,a,"PRP"+suffix,u);long p=jdbc.queryForObject("SELECT id FROM md_product WHERE product_code=?",Long.class,"PRP"+suffix);jdbc.update("INSERT INTO proc_package(org_id,created_by,updated_by,product_id,package_code,status) VALUES(1,?,?,?,?,'ACTIVE')",a,a,p,"PRK"+suffix);long k=jdbc.queryForObject("SELECT id FROM proc_package WHERE package_code=?",Long.class,"PRK"+suffix);jdbc.update("INSERT INTO proc_package_version(org_id,created_by,updated_by,package_id,version,status) VALUES(1,?,?,?,1,'DRAFT')",a,a,k);long v=jdbc.queryForObject("SELECT id FROM proc_package_version WHERE package_id=?",Long.class,k);return new long[]{a,u,p,k,v};});
  as(1,ids[0]);var held=new java.util.concurrent.CountDownLatch(1);var waiting=new java.util.concurrent.CountDownLatch(1);var pool=java.util.concurrent.Executors.newFixedThreadPool(2);
  doAnswer(call->{waiting.countDown();return call.callRealMethod();}).when(store).packages();
  try {var write=pool.submit(()->tx.execute(t->{jdbc.queryForList("SELECT id FROM proc_package WHERE id=? FOR UPDATE",ids[3]);held.countDown();try{if(!waiting.await(5,java.util.concurrent.TimeUnit.SECONDS))throw new AssertionError("Second transaction did not reach package lock");}catch(InterruptedException e){throw new RuntimeException(e);}jdbc.update("UPDATE proc_package_version SET version_no=1 WHERE id=?",ids[4]);return null;}));assertThat(held.await(5,java.util.concurrent.TimeUnit.SECONDS)).isTrue();var read=pool.submit(()->{try{tx.execute(t->service.saveRoute(Long.toString(ids[4]),route(0,false),null,key()));return (RuntimeException)null;}catch(RuntimeException e){return e;}});write.get(10,java.util.concurrent.TimeUnit.SECONDS);assertThat(read.get(10,java.util.concurrent.TimeUnit.SECONDS)).isInstanceOf(com.hospital.mes.common.exception.ResourceConflictException.class);Long count=tx.execute(t->jdbc.queryForObject("SELECT COUNT(*) FROM proc_route_version WHERE package_version_id=?",Long.class,ids[4]));assertThat(count).isZero();}
  finally {pool.shutdownNow();pool.awaitTermination(10,java.util.concurrent.TimeUnit.SECONDS);reset(store);tx.execute(t->{jdbc.update("DELETE FROM proc_package_version WHERE id=? AND package_id=?",ids[4],ids[3]);jdbc.update("DELETE FROM proc_package WHERE id=? AND package_code=?",ids[3],"PRK"+suffix);jdbc.update("DELETE FROM md_product WHERE id=? AND product_code=?",ids[2],"PRP"+suffix);jdbc.update("DELETE FROM md_unit WHERE id=? AND unit_code=?",ids[1],"PRU"+suffix);jdbc.update("DELETE FROM sys_user WHERE id=? AND login_name_normalized=?",ids[0],"prace_"+suffix);return null;});}
 }
}
