package com.hospital.mes.configuration;
import com.hospital.mes.reporting.application.*;import com.hospital.mes.ebr.application.*;import com.hospital.mes.masterdata.application.*;import com.hospital.mes.common.exception.*;import java.util.*;
@org.springframework.stereotype.Component @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class EbrFormPrintProvider implements PrintDataProvider {
 private final EbrRuntimeService runtime;private final MasterMutation mutations;private final MasterQueryService units;
 public EbrFormPrintProvider(EbrRuntimeService runtime,MasterMutation mutations,MasterQueryService units){this.runtime=runtime;this.mutations=mutations;this.units=units;}
 public String moduleLabel(){return "生产管理";}
 public String documentLabel(){return "eBR过程表单";}
 public String businessType(){return "EBR_PROCESS_FORM";}
 public Set<String> fields(){return Set.of("modeLabel","reportNo","formName","formStatus","definitionHash","signatureReference");}
 public Set<String> itemFields(){return Set.of("sequence","fieldCode","label","standard","actual","unit","source","occurrence");}
 public List<PrintField> fieldDefinitions(){var out=new ArrayList<PrintField>();for(String f:fields().stream().sorted().toList())out.add(new PrintField(f,switch(f){case "modeLabel"->"草稿/正式标识";case "reportNo"->"表单编号";case "formName"->"表单名称";case "formStatus"->"审核状态";case "definitionHash"->"冻结定义摘要";default->"电子签名记录引用";},"过程表单","来自受控eBR实例","合成示例",false));for(String f:itemFields().stream().sorted().toList())out.add(new PrintField(f,switch(f){case "label"->"项目";case "standard"->"标准/规定";case "actual"->"实际记录";case "unit"->"单位";case "source"->"数据来源";case "occurrence"->"明细行";case "sequence"->"序号";default->"稳定字段标识";},"循环记录明细","由后端稳定fieldCode映射","合成示例",true));return List.copyOf(out);}
 public Map<String,Object> example(){return Map.of("modeLabel","合成示例 · 草稿","reportNo","SYNTHETIC-FORM","formName","过程记录","formStatus","DRAFT","definitionHash","示例摘要","signatureReference","未签署", "items",List.of(Map.of("sequence","1","fieldCode","ACTUAL","label","实际数量","standard","按冻结工艺执行","actual","12.5","unit","示例单位","source","MANUAL","occurrence","")));}
 public void authorizeRead(String id){runtime.render(id);}
 public PrintSnapshot load(String id,boolean formal){var c=mutations.context("ebr:form:view");var f=runtime.render(id);if(formal&&!runtime.evaluateOperation(c.organizationId(),f.path("operationExecutionId").asLong()).complete())throw new ComplianceException("EBR_FORM_INCOMPLETE","Actual form review/signature gates required");var values=new LinkedHashMap<String,Object>();values.put("modeLabel",formal?"正式记录":"草稿 · 未完成正式审核");values.put("reportNo",f.path("formCode").asText()+"-"+id);values.put("formName",f.path("formName").asText());values.put("formStatus",f.path("status").asText());values.put("definitionHash",f.path("definitionHash").asText());values.put("signatureReference",f.path("signatureIds").isEmpty()?"未签署":f.path("signatureIds").toString());var rows=new ArrayList<Map<String,Object>>();int seq=0;for(var field:f.path("fields")){if(!field.path("visible").asBoolean())continue;String standard="";for(var definition:f.path("definition").path("fields"))if(definition.path("fieldCode").equals(field.path("fieldCode")))standard=definition.path("helpText").asText("");rows.add(Map.of("sequence",Integer.toString(++seq),"fieldCode",field.path("fieldCode").asText(),"label",field.path("label").asText(),"standard",standard,"actual",field.path("displayValue").asText(""),"unit",unit(field.path("unitId").asText("")),"source",field.path("source").asText(),"occurrence",field.path("occurrencePath").asText("")));}values.put("items",rows);return new PrintSnapshot(mutations.digest(Map.of("definitionHash",f.path("definitionHash"),"formRevision",f.path("formRevision"),"currentValues",f.path("currentValues"),"reviews",f.path("reviews"),"signatureIds",f.path("signatureIds"))),f.path("formCode").asText()+"-"+id,values);}
 private String unit(String id){if(id.isBlank())return "";var c=mutations.context("master:uom:view");return units.unitName(c.organizationId(),MasterMutation.id(id));}
}
