package com.hospital.mes.ebr.domain;
/** Concrete closed definition and command contracts; no client-authored publication schema. */
public final class EbrCommands {
 private EbrCommands(){}
 public record Option(String optionCode,String optionLabel,String optionValue,Integer sequenceNo,Boolean activeFlag){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Field(String fieldCode,String groupCode,String label,String fieldType,String sourceType,String dataType,String unitId,Integer precisionScale,Boolean requiredFlag,Boolean readonlyFlag,String defaultExpr,String placeholder,String helpText,Integer sequenceNo,String validationJson,java.util.List<Option> options){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Group(String groupCode,String title,Integer sequenceNo,Integer layoutColumns,String repeatMode,Integer minOccurs,Integer maxOccurs){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Section(String sectionCode,String title,Integer sequenceNo,String repeatMode,String visibilityRuleCode,Boolean pageBreakFlag,java.util.List<Group> groups){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Form(String formCode,String formName,String operationDefId,String schemaVersion,Integer sequenceNo,java.util.List<Field> fields){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Rule(String ruleCode,String formCode,String fieldCode,String ruleType,String triggerPoint,String expression,String severity,String errorCode,String messageTemplate,Boolean deviationTrigger,Boolean activeFlag){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record SignatureRule(String objectScope,String objectCode,String meaning,String requiredRole,Boolean reauthRequired,Integer sequenceNo,Boolean invalidateOnChange){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record ReviewRule(String objectScope,String objectCode,String reviewType,String requiredRole,Boolean independentUserRequired,Integer sequenceNo){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Definition(java.util.List<Section> sections,java.util.List<Form> forms,java.util.List<Rule> rules,java.util.List<SignatureRule> signatureRules,java.util.List<ReviewRule> reviewRules){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Create(String packageVersionId,String templateCode){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Save(Long versionNo,String reason,Definition definition){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record VersionCreate(Long versionNo,String reason,Boolean copyDefinition){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Command(Long versionNo,String reason){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Input(String fieldCode,java.util.List<com.fasterxml.jackson.databind.JsonNode> values){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Simulation(Long versionNo,String reason,String triggerPoint,java.util.List<Input> inputs){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Summary(String id,String packageVersionId,String templateCode,Integer version,String status,String contentHash,String effectiveFrom,String approvedBy,String approvedAt,Long versionNo,java.util.List<String> allowedActions){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Detail(String id,String packageVersionId,String templateCode,Integer version,String status,String contentHash,String effectiveFrom,String approvedBy,String approvedAt,Long versionNo,java.util.List<String> allowedActions,Definition definition,java.util.List<Summary> versions,java.util.List<OperationChoice> operationChoices){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Page(java.util.List<Summary> items,Long total,Integer page,Integer size){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Issue(String path,String code,String message){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Lint(Boolean valid,java.util.List<Issue> issues){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record RuleResult(String ruleCode,Boolean passed,String severity,String message,java.util.List<Input> inputSnapshot,com.fasterxml.jackson.databind.JsonNode outputValue,String executedAt,String engineVersion,String ruleVersion){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record SimulationResult(Boolean allowed,java.util.List<RuleResult> results){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Difference(String path,String before,String after){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Comparison(String leftId,String rightId,java.util.List<Difference> differences){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record OperationChoice(String id,String operationCode,String operationName){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
}
