package com.hospital.mes.ebr.domain;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.common.exception.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
public final class EbrRuntimeRules {
 private EbrRuntimeRules(){}
 public static void requireBindings(EbrCommands.Definition d){for(var f:d.forms())if(f.operationDefId()==null)throw new ComplianceException("EBR_OPERATION_BINDING_REQUIRED","Explicit operation binding required: "+f.formCode());}
 public static String transition(String status,String action){if(status.equals("DRAFT")&&action.equals("SUBMIT"))return "SUBMITTED";if(status.equals("SUBMITTED")&&action.equals("VERIFY"))return "VERIFIED";if(Set.of("SUBMITTED","VERIFIED").contains(status)&&action.equals("APPROVE"))return "APPROVED";if(Set.of("SUBMITTED","VERIFIED","APPROVED").contains(status)&&Set.of("CORRECT","REJECT").contains(action))return "DRAFT";throw new ResourceConflictException("INVALID_FORM_STATE","Invalid form state transition");}
 public static long expected(String h,Long body){if(h==null||!h.matches("\"(0|[1-9][0-9]*)\""))throw new IllegalArgumentException("Quoted If-Match required");long n=Long.parseLong(h.substring(1,h.length()-1));if(body==null||body!=n)throw new IllegalArgumentException("formRevision must match If-Match");return n;}
 // A saved empty selection is still an authored row, but cannot satisfy a required value.
 public static boolean hasValue(Object value){if(value==null)return false;if(value instanceof JsonNode node){if(node.isNull()||node.isMissingNode())return false;if(node.isTextual())return !node.asText().isBlank();if(node.isArray()){for(var item:node)if(hasValue(item))return true;return false;}return true;}if(value instanceof CharSequence text)return !text.toString().isBlank();if(value instanceof java.util.Collection<?> values)return values.stream().anyMatch(EbrRuntimeRules::hasValue);return true;}
 public static String reason(String s){return EbrDefinitionRules.text(s,1000,"reason");}
 public static JsonNode normalize(EbrCommands.Field f,JsonNode value,String unit,boolean correction){if(!correction&&(Boolean.TRUE.equals(f.readonlyFlag())||!Set.of("MANUAL","BARCODE").contains(f.sourceType())))throw new ComplianceException("EBR_SOURCE_REQUIRED","Controlled source cannot be edited manually");if(!Objects.equals(f.unitId(),unit))throw new IllegalArgumentException("Field unit must match frozen unit");if(value==null||value.isNull())return NullNode.instance;if(value.toString().length()>4000)throw new IllegalArgumentException("Field value too long");String type=f.fieldType();if(Set.of("NUMBER","TIMER","CALCULATED","INSTRUMENT_VALUE").contains(type)){if(!value.isTextual()||!value.asText().matches("-?[0-9]+(\\.[0-9]+)?"))throw new IllegalArgumentException("Exact decimal string required");BigDecimal d=new BigDecimal(value.asText());if(d.precision()-d.scale()>18||d.scale()>(f.precisionScale()==null?12:f.precisionScale()))throw new IllegalArgumentException("Field precision exceeded");return TextNode.valueOf(d.toPlainString());}if(type.equals("BOOLEAN")){if(!value.isBoolean())throw new IllegalArgumentException("Boolean required");return value.deepCopy();}if(type.equals("MULTI_ENUM")){if(!value.isArray())throw new IllegalArgumentException("Enum array required");Set<String> seen=new HashSet<>();for(var x:value){option(f,x);if(!seen.add(x.asText()))throw new IllegalArgumentException("Duplicate enum option");}return value.deepCopy();}if(!value.isTextual())throw new IllegalArgumentException("Text value required");if(type.equals("ENUM"))option(f,value);try{if(type.equals("DATE"))LocalDate.parse(value.asText());if(type.equals("TIME"))LocalTime.parse(value.asText());if(type.equals("DATETIME"))Instant.parse(value.asText());}catch(java.time.format.DateTimeParseException e){throw new IllegalArgumentException("Invalid date/time value");}return value.deepCopy();}
 private static void option(EbrCommands.Field f,JsonNode x){if(!x.isTextual()||f.options().stream().noneMatch(o->Boolean.TRUE.equals(o.activeFlag())&&o.optionValue().equals(x.asText())))throw new IllegalArgumentException("Active enum option required");}
 public static void occurrence(EbrCommands.Definition d,EbrCommands.Field f,String path){if(path==null||path.length()>255)throw new IllegalArgumentException("Occurrence path required");var g=d.sections().stream().flatMap(s->s.groups().stream()).filter(x->Objects.equals(x.groupCode(),f.groupCode())).findFirst().orElse(null);if(g==null||"NONE".equals(g.repeatMode())){if(!path.isEmpty())throw new IllegalArgumentException("Nonrepeating field has empty occurrence path");return;}var match=java.util.regex.Pattern.compile(java.util.regex.Pattern.quote(g.groupCode())+"\\[(0|[1-9][0-9]*)\\]").matcher(path);if(!match.matches())throw new IllegalArgumentException("Invalid group occurrence path");int index;try{index=Integer.parseInt(match.group(1));}catch(NumberFormatException e){throw new IllegalArgumentException("Occurrence index too large");}if(index>=500||(g.maxOccurs()!=null&&index>=g.maxOccurs()))throw new IllegalArgumentException("Occurrence exceeds maximum");}
}
