package com.hospital.mes.wms.api;
import com.fasterxml.jackson.databind.JsonNode;
import com.hospital.mes.common.api.ApiResponse;
import com.hospital.mes.common.trace.TraceIdProvider;
import com.hospital.mes.wms.application.WmsService;
import com.hospital.mes.wms.domain.WmsCommands.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import java.util.*;
@RestController @RequestMapping("/api/v1") @ConditionalOnProperty(prefix="spring.datasource",name="url")
public class WmsController {
 private final WmsService service;private final com.hospital.mes.wms.application.WmsProductionService production;private final TraceIdProvider traces;
 public WmsController(WmsService service,com.hospital.mes.wms.application.WmsProductionService production,TraceIdProvider traces){this.service=service;this.production=production;this.traces=traces;}
 @GetMapping("/containers") public ApiResponse<?> operation0(@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestParam(name="keyword",required=false) String keyword,@RequestParam Map<String,String> filters){return ApiResponse.success(service.list("Container",page,size,keyword,filters),traces.currentTraceId());}
 @PostMapping("/containers") public ApiResponse<?> operation1(@RequestBody ContainerCreate body,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(service.maintenance("Container",null,body,null,key),traces.currentTraceId());}
 @GetMapping("/containers/{id}") public ApiResponse<?> operation2(@PathVariable("id") String id){return ApiResponse.success(service.get("Container",id),traces.currentTraceId());}
 @PutMapping("/containers/{id}") public ApiResponse<?> operation3(@PathVariable("id") String id,@RequestBody ContainerUpdate body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(service.maintenance("Container",id,body,version,key),traces.currentTraceId());}
 @GetMapping("/inventory") public ApiResponse<?> operation4(@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestParam(name="keyword",required=false) String keyword,@RequestParam Map<String,String> filters){return ApiResponse.success(service.inventory(page,size,keyword,filters),traces.currentTraceId());}
 @PostMapping("/inventory/adjust") public ApiResponse<?> operation5(@RequestBody InventoryAdjust body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(service.adjust(body,version,key),traces.currentTraceId());}
 @PostMapping("/inventory/move") public ApiResponse<?> operation6(@RequestBody InventoryMove body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(service.move(body,version,key),traces.currentTraceId());}
 @PostMapping("/inventory/receive") public ApiResponse<?> operation7(@RequestBody ReceiptCreate body,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(service.createReceipt(body,key,true),traces.currentTraceId());}
 @GetMapping("/locations") public ApiResponse<?> operation8(@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestParam(name="keyword",required=false) String keyword,@RequestParam Map<String,String> filters){return ApiResponse.success(service.list("Location",page,size,keyword,filters),traces.currentTraceId());}
 @PostMapping("/locations") public ApiResponse<?> operation9(@RequestBody LocationCreate body,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(service.maintenance("Location",null,body,null,key),traces.currentTraceId());}
 @GetMapping("/locations/{id}") public ApiResponse<?> operation10(@PathVariable("id") String id){return ApiResponse.success(service.get("Location",id),traces.currentTraceId());}
 @PutMapping("/locations/{id}") public ApiResponse<?> operation11(@PathVariable("id") String id,@RequestBody LocationUpdate body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(service.maintenance("Location",id,body,version,key),traces.currentTraceId());}
 @GetMapping("/material-issues") public ApiResponse<?> operation12(@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestParam(name="keyword",required=false) String keyword,@RequestParam Map<String,String> filters){return ApiResponse.success(service.list("MaterialIssue",page,size,keyword,filters),traces.currentTraceId());}
 @PostMapping("/material-issues") public ApiResponse<?> operation13(@RequestBody JsonNode body,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(production.createIssue(body,key),traces.currentTraceId());}
 @GetMapping("/material-issues/{id}") public ApiResponse<?> operation14(@PathVariable("id") String id){return ApiResponse.success(service.get("MaterialIssue",id),traces.currentTraceId());}
 @PutMapping("/material-issues/{id}") public ApiResponse<?> operation15(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(production.updateIssue(id,body,version,key),traces.currentTraceId());}
 @PostMapping("/material-issues/{id}/confirm") public ApiResponse<?> operation16(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(production.confirmIssue(id,body,version,key),traces.currentTraceId());}
 @PostMapping("/material-issues/{id}/returns") public ApiResponse<?> operation17(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(production.returnIssue(id,body,version,key),traces.currentTraceId());}
 @GetMapping("/material-lots") public ApiResponse<?> operation18(@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestParam(name="keyword",required=false) String keyword,@RequestParam Map<String,String> filters){return ApiResponse.success(service.list("MaterialLot",page,size,keyword,filters),traces.currentTraceId());}
 @PostMapping("/material-lots") public ApiResponse<?> operation19(@RequestBody DependencyCommand body,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(service.unavailable("wms:inventory:create",true),traces.currentTraceId());}
 @GetMapping("/material-lots/{id}") public ApiResponse<?> operation20(@PathVariable("id") String id){return ApiResponse.success(service.get("MaterialLot",id),traces.currentTraceId());}
 @PutMapping("/material-lots/{id}") public ApiResponse<?> operation21(@PathVariable("id") String id,@RequestBody DependencyCommand body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(service.unavailable("wms:inventory:update",true),traces.currentTraceId());}
 @GetMapping("/warehouses") public ApiResponse<?> operation22(@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestParam(name="keyword",required=false) String keyword,@RequestParam Map<String,String> filters){return ApiResponse.success(service.list("Warehouse",page,size,keyword,filters),traces.currentTraceId());}
 @PostMapping("/warehouses") public ApiResponse<?> operation23(@RequestBody WarehouseCreate body,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(service.maintenance("Warehouse",null,body,null,key),traces.currentTraceId());}
 @GetMapping("/warehouses/{id}") public ApiResponse<?> operation24(@PathVariable("id") String id){return ApiResponse.success(service.get("Warehouse",id),traces.currentTraceId());}
 @PutMapping("/warehouses/{id}") public ApiResponse<?> operation25(@PathVariable("id") String id,@RequestBody WarehouseUpdate body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(service.maintenance("Warehouse",id,body,version,key),traces.currentTraceId());}
 @GetMapping("/wms/receipts") public ApiResponse<?> operation26(@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestParam(name="keyword",required=false) String keyword,@RequestParam Map<String,String> filters){return ApiResponse.success(service.list("Receipt",page,size,keyword,filters),traces.currentTraceId());}
 @PostMapping("/wms/receipts") public ApiResponse<?> operation27(@RequestBody ReceiptCreate body,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(service.createReceipt(body,key,false),traces.currentTraceId());}
 @GetMapping("/wms/receipts/{id}") public ApiResponse<?> operation28(@PathVariable("id") String id){return ApiResponse.success(service.get("Receipt",id),traces.currentTraceId());}
 @PostMapping("/wms/receipts/{id}/confirm") public ApiResponse<?> operation29(@PathVariable("id") String id,@RequestBody Command body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(service.confirmReceipt(id,body,version,key),traces.currentTraceId());}
 @GetMapping("/wms/material-lots") public ApiResponse<?> operation30(@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestParam(name="keyword",required=false) String keyword,@RequestParam Map<String,String> filters){return ApiResponse.success(service.list("MaterialLot",page,size,keyword,filters),traces.currentTraceId());}
 @GetMapping("/wms/material-lots/{id}") public ApiResponse<?> operation31(@PathVariable("id") String id){return ApiResponse.success(service.get("MaterialLot",id),traces.currentTraceId());}
 @PutMapping("/wms/receipts/{id}") public ApiResponse<?> operation32(@PathVariable("id") String id,@RequestBody ReceiptUpdate body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(service.updateReceipt(id,body,version,key),traces.currentTraceId());}
 @GetMapping("/main-batches/{id}/reservations") public ApiResponse<?> operation33(@PathVariable("id") String id){return ApiResponse.success(service.reservations(id),traces.currentTraceId());}
 @PostMapping("/main-batches/{id}/reservations") public ApiResponse<?> operation34(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader("Idempotency-Key") String key,@RequestHeader(name="If-Match",required=false) String version){return ApiResponse.success(production.reserve(id,body,version,key),traces.currentTraceId());}
}
