<script setup lang="ts">
import {onMounted,onUnmounted,ref} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,errorMessage} from '../../api/http'
const route=useRoute(),router=useRouter(),error=ref(''),busy=ref(false),sessionId=ref(''),savedId=ref(''),editorReady=ref(false)
let editor:{destroyEditor():void}|undefined,timer:ReturnType<typeof setInterval>|undefined
type OfficeWindow=Window&{DocsAPI?:{DocEditor:new(id:string,config:Record<string,unknown>)=>{destroyEditor():void}}}
async function status(){if(!sessionId.value)return;try{const s=await api<{savedTemplateVersionId:string}>({url:`/printing/editor/sessions/${sessionId.value}`});savedId.value=s.savedTemplateVersionId}catch(e){error.value=errorMessage(e);if(timer)clearInterval(timer)}}
async function open(){busy.value=true;error.value='';try{const s=await api<{sessionId:string;documentServerUrl:string;config:Record<string,unknown>}>({url:'/printing/editor/sessions',method:'POST',data:{templateVersionId:String(route.params.id)}});sessionId.value=s.sessionId;const office=s.documentServerUrl;const u=new URL(office);if(!['http:','https:'].includes(u.protocol))throw new Error('无效的文档服务地址');if(!(window as OfficeWindow).DocsAPI)await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src=`${office}/web-apps/apps/api/documents/api.js`;script.onload=()=>resolve();script.onerror=()=>reject(new Error('在线 Word 服务不可达'));document.head.appendChild(script)});editor=new (window as OfficeWindow).DocsAPI!.DocEditor('word-editor',{...s.config,events:{onDocumentReady:()=>{editorReady.value=true},onError:()=>{error.value='Word 编辑器报告错误，请检查文档服务及会话状态'}}});timer=setInterval(()=>void status(),5000)}catch(e){error.value=e instanceof Error&&e.message.includes('Word')?e.message:`在线 Word 尚未就绪：${errorMessage(e)}。请由管理员配置已批准的 ONLYOFFICE 服务。`}finally{busy.value=false}}
onMounted(()=>void open());onUnmounted(()=>{if(timer)clearInterval(timer);editor?.destroyEditor()})
</script>
<!-- UI Template: T3; document detail with embedded Word editor. -->
<template><section class="admin-page master-page" data-ui-template="T3"><div class="admin-page-header editor-heading"><div><h1>Word 模板编辑</h1><p>保留原版式，在 Word 内使用中文字段面板插入字段和检验项目循环表。</p></div><a-space><a-button @click="router.push('/admin/print-templates')">返回模板列表</a-button><a-button :disabled="!sessionId" @click="status">检查保存状态</a-button></a-space></div><a-alert v-if="error" type="error" :message="error" show-icon/><a-alert v-if="savedId" type="success" message="Word 已回存为独立草稿版本，原版本未覆盖。返回模板列表验证 PDF 后发布。" show-icon/><a-alert v-else-if="editorReady" type="info" message="在 Word 中点击保存，等待回存完成。只有收到服务端签名回调后才会显示保存成功。" show-icon/><a-spin :spinning="busy"><div class="word-shell"><div id="word-editor"/></div></a-spin></section></template>
<style scoped>.editor-heading{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;align-items:center;margin-bottom:16px}.editor-heading h1{font-size:24px;margin:0}.editor-heading p{color:#68758a}.word-shell{height:calc(100vh - 240px);min-height:550px;margin-top:16px;border:1px solid #dce3ed;background:#f3f5f8}#word-editor{height:100%;width:100%}</style>
