package com.hospital.mes.printing;
import com.hospital.mes.configuration.InspectionPrintProvider;import com.hospital.mes.reporting.application.*;import com.hospital.mes.qms.application.IncomingQualityService;import com.hospital.mes.qms.infrastructure.*;import com.hospital.mes.wms.infrastructure.*;import com.hospital.mes.system.infrastructure.*;import com.hospital.mes.masterdata.infrastructure.*;import com.hospital.mes.masterdata.application.MasterMutation;import com.hospital.mes.audit.application.CurrentPlatformContext;import com.hospital.mes.audit.signature.*;import com.hospital.mes.common.exception.*;import com.fasterxml.jackson.databind.*;import org.junit.jupiter.api.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class InspectionPrintProviderTest {
 IncomingQualityService quality;IncomingStore db;MaterialLotMapper lots;SysUserMapper users;MasterMutation mutations;SignatureTransactionService signatures;UnitMapper units;ObjectMapper json=new ObjectMapper();InspectionPrintProvider provider;InspectionReportRow report;
 @BeforeEach void setup()throws Exception {quality=mock(IncomingQualityService.class);db=mock(IncomingStore.class);lots=mock(MaterialLotMapper.class);users=mock(SysUserMapper.class);mutations=mock(MasterMutation.class);signatures=mock(SignatureTransactionService.class);units=mock(UnitMapper.class);when(mutations.context("qms:report:view")).thenReturn(new CurrentPlatformContext(1,2,Set.of("QA"),Set.of("qms:report:view"),"fixture-session","fixture-request"));report=new InspectionReportRow();report.setId(22L);report.setOrgId(1L);report.setVersionNo(3L);report.setReportNo("DEMO");report.setInspectionRequestId(30L);report.setStatus("APPROVED");report.setRecordStatus("APPROVED");report.setOverallResult("PASS");report.setEvidenceDigest("fixture-only");report.setApprovalSignatureId(9L);report.setApprovedBy(2L);var canonical=json.createObjectNode().put("meaning","APPROVE").put("reportNo","DEMO").put("inspectionRequestId","30").put("overallResult","PASS").put("evidenceDigest","fixture-only");report.setApprovalSignatureEvidenceJson(json.writeValueAsString(new SignableObject("INSPECTION_REPORT","22",2,canonical,List.of())));when(db.lock("qms_inspection_report",1,22)).thenReturn(report);when(signatures.verify(1,9)).thenReturn(true);var request=new InspectionRequestRow();request.setRequestNo("DEMO-REQUEST");request.setMaterialLotId(60L);when(db.get("qms_inspection_request",1,30)).thenReturn(request);var lot=new MaterialLotEntity();lot.setLotNo("DEMO-LOT");lot.setMaterialSnapshotJson("{\"materialName\":\"合成测试物料\"}");when(lots.selectOne(any())).thenReturn(lot);var item=new InspectionItemRow();item.setItemName("合成项目");item.setTextAcceptanceCriteria("受控标准");item.setUnitId(10L);when(db.get("qms_inspection_item",1,40)).thenReturn(item);var execution=new TestExecutionRow();execution.setPerformedBy(2L);when(db.get("qms_test_execution",1,50)).thenReturn(execution);var user=new SysUserEntity();user.setDisplayName("合成测试人员");when(users.selectById(2L)).thenReturn(user);var unit=new UnitEntity();unit.setUnitName("%");when(units.selectOne(any())).thenReturn(unit);var view=json.createObjectNode();var lines=view.putArray("items");for(int i=1;i<=75;i++){var line=lines.addObject().put("id",""+i).put("inspectionItemId","40");line.set("result",json.createObjectNode().put("testExecutionId","50").put("resultNumeric","99.5").put("resultUnitId","10").put("resultConclusion","PASS").put("recordedAt","2026-10-08"));line.set("originalResult",json.createObjectNode().put("resultNumeric","98.5").put("resultUnitId","10").put("resultConclusion","FAIL"));}when(quality.view("qms_inspection_report",report)).thenReturn(view);provider=new InspectionPrintProvider(quality,db,lots,users,mutations,signatures,json,units);}
 @Test void draftReadsAllServerItemsAndUnitsWithoutAttributingFormalApproval(){var snapshot=provider.load("22",false);assertEquals(75,((List<?>)snapshot.data().get("items")).size());var last=(Map<?,?>)((List<?>)snapshot.data().get("items")).getLast();assertEquals("75",last.get("sequence"));assertEquals("99.5 %",last.get("result"));assertEquals("98.5 % / FAIL",last.get("originalResult"));assertTrue(snapshot.data().get("modeLabel").toString().contains("草稿"));assertEquals("无（草稿）",snapshot.data().get("signatureReference"));verifyNoInteractions(signatures);}
 @Test void formalRequiresApprovedRecordAndVerifiedExistingSignature(){report.setRecordStatus("DRAFT");assertThrows(ComplianceException.class,()->provider.load("22",true));report.setRecordStatus("APPROVED");when(signatures.verify(1,9)).thenReturn(false);assertThrows(ComplianceException.class,()->provider.load("22",true));}
 @Test void wrongReportOrVersionSignatureBindingIsRejected(){report.setApprovalSignatureEvidenceJson(report.getApprovalSignatureEvidenceJson().replace("\"objectId\":\"22\"","\"objectId\":\"99\""));assertEquals("PRINT_APPROVAL_BINDING_INVALID",assertThrows(ComplianceException.class,()->provider.load("22",true)).code());verifyNoInteractions(lots);}
 @Test void validFormalUsesCurrentBusinessVersionAndExistingSignatureReference(){var data=provider.load("22",true).data();assertEquals("3",data.get("businessVersion"));assertEquals("正式报告",data.get("modeLabel"));assertEquals("9",data.get("signatureReference"));verify(signatures).verify(1,9);}
 @Test void deniedReportReadStopsBeforeLoadingBusinessSources(){when(mutations.context("qms:report:view")).thenThrow(new PermissionException("PERMISSION_DENIED","revoked"));assertThrows(PermissionException.class,()->provider.load("22",false));verifyNoInteractions(db,lots,signatures);}
}
