import { scenarios, materialRoutes, resolveScenario } from './model.mjs';

const app = document.querySelector('#app');
const state = { query: '', validation: false, conflict: false, selectedTab: '概览', toast: '', signature: false };

const icons = ['AU','IN','IA','EQ','MD','SP','PR','eB','WM','BT','EX','WG','QA','RL'];
const esc = (value='') => String(value).replace(/[&<>"']/g, (ch) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const status = (text, tone='green') => `<span class="status ${tone}">${text}</span>`;
const btn = (text, style='', action='') => `<button class="btn ${style}" ${action ? `data-action="${action}"` : ''}>${text}</button>`;

function hashRoute() { return decodeURIComponent(location.hash.slice(1)) || scenarios[0].route; }
function go(route) { location.hash = encodeURI(route); }

function shell(page, body) {
  const nav = scenarios.map((item,index)=>`<div class="nav-item ${page.id===item.id?'active':''}" data-route="${item.route}"><span class="nav-icon">${icons[index]}</span><span>${item.title}</span></div>`).join('');
  return `<div class="app">
    <header class="topbar"><div class="brand"><span class="brand-mark"></span><span>医院制剂 MES</span></div><span class="env">GMP · 验证环境</span><div class="topfill"></div><div class="top-status"><span class="online"></span><span>系统运行正常</span><span>华东医院制剂中心</span><span class="avatar">陈</span><span>陈质管</span></div></header>
    <aside class="sidebar"><div class="nav-group">核心工作台</div>${nav}</aside>
    <main class="main"><div class="crumbbar"><span>医院制剂 MES</span><span>›</span><span>${page.task}</span><span>›</span><strong>${page.title}</strong><span class="right muted">UI PROTOTYPE BASELINE V1.0.2 FROZEN</span></div><section class="content">
      <div class="page-head"><div><h1>${page.title}</h1><div class="page-sub">受控业务界面 · 数据为原型演示 · 所有动作遵循权限与 allowedActions</div></div><div class="head-actions">${headerActions(page)}</div></div>
      <div class="trace"><div><label>Requirement</label><b>${page.requirement}</b></div><div><label>Route</label><b>${page.route}</b></div><div><label>API</label><b>${page.api}</b></div><div><label>Permission</label><b>${page.permission}</b></div></div>
      ${body}
    </section></main>${state.toast?`<div class="toast">✓ ${state.toast}</div>`:''}${state.signature?signatureModal():''}
  </div>`;
}

function headerActions(page){
  if(page.mode==='audit-query') return btn('刷新','','');
  if(page.mode==='integration-ops') return btn('刷新','','');
  if(page.mode==='query') return `${btn('导出','')} ${btn('＋ 新增','primary','create')}`;
  if(page.mode==='edit'||page.mode==='create') return btn('返回查询','','back-query');
  if(page.mode==='release') return `${btn('退回','','reject')} ${btn('放行决定','primary','sign')}`;
  return `${btn('审计追踪','','audit')} ${btn('打印受控副本','')}`;
}

const genericRows = {
  'UI-IAM-USR-Q': [['zhang.wei','张伟','生产操作员','启用','2026-09-29 08:12'],['li.min','李敏','QA审核员','启用','2026-09-29 07:48'],['wang.qiang','王强','库房管理员','锁定','2026-09-27 16:40'],['chen.yu','陈宇','工艺工程师','启用','2026-09-28 17:21']],
  'UI-EQP-Q': [['EQP-MIX-014','真空均质乳化机','生产设备','在役','2026-11-18'],['EQP-BAL-027','精密电子天平','称量设备','在役','2026-10-08'],['EQP-FIL-008','板框过滤器','生产设备','维护中','2026-12-22'],['EQP-TMP-033','温湿度记录仪','监测设备','在役','2027-01-16']],
  'UI-SUP-Q': [['SUP-0017','华南药用辅料有限公司','合格','2027-06-30','A级'],['SUP-0023','国药包装材料股份','合格','2027-02-28','A级'],['SUP-0039','沪江化学试剂厂','待复审','2026-10-15','B级'],['SUP-0041','安宁玻璃制品有限公司','暂停','2026-09-20','C级']],
  'UI-WMS-REC-Q': [['REC-260929-018','甘油','华南药用辅料','GLY-20260918','待验','2026-09-29'],['REC-260928-006','纯化水','院内制水站','PW-260928','已收货','2026-09-28'],['REC-260927-032','乳化剂 OP-10','华南药用辅料','OP10-8271','已检验','2026-09-27'],['REC-260926-014','羟苯乙酯','沪江化学试剂厂','HB-0922-07','隔离','2026-09-26']],
};

function queryPage(page){
  const isMat=page.id==='UI-MAT-Q';
  const rows=isMat?[['MAT-00028','复方甘油搽剂','成品','100 mL/瓶','瓶','已批准','V3'],['MAT-00116','甘油','原料','药用级','kg','已批准','V5'],['MAT-00207','纯化水','原料','内控标准','kg','已批准','V2'],['MAT-00341','乳化剂 OP-10','辅料','药用级','kg','待审批','V1']]:genericRows[page.id]||[];
  const headers=isMat?['编码','名称','类别','规格','基本单位','状态','版本','操作']:page.id==='UI-IAM-USR-Q'?['用户名','姓名','角色','状态','最后登录','操作']:page.id==='UI-EQP-Q'?['设备编码','名称','类型','状态','校准到期','操作']:page.id==='UI-SUP-Q'?['供应商编码','名称','资质状态','有效期','评级','操作']:['收货单号','物料','供应商','供应商批号','状态','收货日期','操作'];
  return `<div class="card search"><div class="card-head">查询条件 <small>条件同步 URL，返回时保留</small></div><div class="card-body"><div class="fields"><div class="field"><label>${isMat?'物料编码 / 名称':'编码 / 关键字'}</label><input class="input" id="queryInput" value="${esc(state.query)}" placeholder="请输入"></div><div class="field"><label>状态</label><select class="select"><option>全部状态</option><option>启用 / 合格</option><option>待审批</option></select></div><div class="field"><label>组织</label><select class="select"><option>华东医院制剂中心</option></select></div><div class="field"><label>更新时间</label><input class="input" value="2026-09-01 ～ 2026-09-29"></div></div><div class="search-actions">${btn('重置','','reset')} ${btn('查询','primary','search')}</div></div></div>
  <div class="toolbar">${btn('＋ 新增','primary','create')} ${btn('批量导出')}<span class="spacer"></span><span class="muted">共 ${rows.length*8+3} 条记录 · 最新同步 09:42:18</span></div>
  <div class="card table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((row,i)=>`<tr class="${i===0?'selected':''}">${row.map((cell,j)=>`<td class="${j===0?'code':''}">${j===3||(!isMat&&j===2)?(['启用','在役','合格','待检','已批准','待审批','冻结','锁定','维护中','暂停'].includes(cell)?status(cell,cell==='启用'||cell==='在役'||cell==='合格'||cell==='已批准'?'green':cell==='待审批'||cell==='待检'||cell==='维护中'?'amber':'red'):cell):cell}</td>`).join('')}<td><span class="link" data-action="view">查看</span><span class="link" data-action="edit">编辑</span></td></tr>`).join('')}</tbody></table><div class="pagination"><span>20 条/页</span><span class="pagebox">‹</span><span class="pagebox active">1</span><span class="pagebox">2</span><span class="pagebox">3</span><span class="pagebox">›</span></div></div>`;
}

function materialForm(page){
  const edit=page.mode==='edit'; const create=page.mode==='create';
  return `${state.conflict?`<div class="notice danger"><b>409 版本冲突：</b>该物料已由“李敏”于 09:41 更新。为保护审计链，必须重新加载最新版本后再修改。 ${btn('重新加载','danger','reload')}</div>`:''}
  ${state.validation?'<div class="notice danger"><b>422 业务校验未通过：</b>质量标准编号不能为空。已保留全部输入，并定位到错误字段。</div>':''}
  <div class="card form-card"><div class="tabs"><div class="tab active">基本信息</div><div class="tab">质量与规格</div><div class="tab">供应商</div><div class="tab">版本说明</div></div>
  <div class="form-section"><h3>物料标识</h3><div class="form-grid"><div class="field"><label>物料编码</label><input class="input" value="${create?'':'MAT-00028'}" placeholder="系统生成" ${edit?'readonly':''}></div><div class="field"><label>物料名称 *</label><input class="input" value="${create?'':'复方甘油搽剂'}"></div><div class="field"><label>类别 *</label><select class="select"><option>成品</option><option>原料</option><option>辅料</option></select></div><div class="field"><label>规格 *</label><input class="input" value="100 mL/瓶"></div><div class="field"><label>基本单位 *</label><select class="select"><option>瓶</option><option>kg</option></select></div><div class="field"><label>关键物料</label><select class="select"><option>是</option><option>否</option></select></div></div></div>
  <div class="form-section"><h3>质量属性</h3><div class="form-grid"><div class="field"><label>质量标准编号 *</label><input class="input ${state.validation?'error':''}" value="${state.validation?'':'QSP-MAT-2026-041'}">${state.validation?'<div class="help-error">请选择当前有效的质量标准</div>':''}</div><div class="field"><label>储存条件</label><input class="input" value="密闭，阴凉处保存"></div><div class="field"><label>有效期（月）</label><input class="input" value="24"></div></div></div></div><div class="footer-actions">${btn('取消','','back-query')} ${btn('保存草稿','','save-draft')} ${btn(edit?'模拟 409':'模拟 422','',edit?'conflict':'validation')} ${btn(create?'保存':'保存变更','primary','save')}</div>`;
}

function materialView(page){return `<div class="notice"><b>版本冻结规则：</b>当前 V3 已批准，不允许原位编辑。变更必须通过“创建新版本”生成 V4 草稿。</div><div class="grid-2"><div class="card"><div class="card-head">物料主记录 <span class="right">${status('已批准','green')} &nbsp; V3</span></div><div class="tabs"><div class="tab active">概览</div><div class="tab">规格与质量</div><div class="tab">批准供应商</div><div class="tab">修订记录</div></div><div class="card-body"><div class="desc"><div><label>物料编码</label><strong class="code">MAT-00028</strong></div><div><label>物料名称</label><strong>复方甘油搽剂</strong></div><div><label>类别</label><strong>成品</strong></div><div><label>规格</label><strong>100 mL/瓶</strong></div><div><label>基本单位</label><strong>瓶</strong></div><div><label>质量标准</label><strong>QSP-MAT-2026-041</strong></div><div><label>生效日期</label><strong>2026-08-18</strong></div><div><label>批准人</label><strong>李敏 / QA</strong></div><div><label>电子签名</label><strong>已验证 · 签名 ID #SG-83214</strong></div></div></div></div><div class="card"><div class="card-head">状态与审计</div><div class="card-body"><div class="timeline"><div class="timeline-item"><b>V3 批准并生效</b><small>李敏 · 2026-08-18 14:32 · eSignature</small></div><div class="timeline-item"><b>QA 复核完成</b><small>陈质管 · 2026-08-18 13:06</small></div><div class="timeline-item"><b>提交审批</b><small>张伟 · 2026-08-17 16:20</small></div><div class="timeline-item"><b>创建 V3 修订</b><small>王芳 · 2026-08-16 10:14</small></div></div>${btn('创建新版本','primary','edit')}</div></div></div>`}

function auditPage(){return `<div class="stat-row"><div class="card stat"><div class="k">今日审计事件</div><div class="v">API total</div><div class="delta">GET /audit-events · UTC日范围</div></div></div><div class="card table-wrap"><div class="card-head">AuditEvent 查询 <span class="right muted">固定排序 occurred_at DESC, id DESC</span></div><table class="data-table"><thead><tr><th>时间</th><th>Actor / Role</th><th>Action</th><th>Object</th><th>Transaction / Request</th><th>Source</th></tr></thead><tbody><tr><td colspan="6" class="muted">原型状态：由具体 AuditEventPageResponse 驱动；必须支持 loading / empty / error / 403。</td></tr></tbody></table></div>`}

function integrationPage(){return `<div class="stat-row"><div class="card stat"><div class="k">Outbox Pending / Retry Wait</div><div class="v">API total</div><div class="delta">GET /integration/messages?direction=OUTBOX</div></div><div class="card stat"><div class="k">Dead Letter</div><div class="v">API total</div><div class="delta">status=DEAD_LETTER</div></div></div><div class="card table-wrap"><div class="card-head">Inbox / Outbox Operations <span class="right muted">重试需 integration:view + integration:retry</span></div><table class="data-table"><thead><tr><th>Message Ref</th><th>方向/系统</th><th>Message ID</th><th>状态</th><th>Retry</th><th>Next Retry</th><th>操作</th></tr></thead><tbody><tr><td colspan="7" class="muted">原型状态：由 IntegrationMessagePageResponse 驱动；人工重试提交 reason、If-Match 与 Idempotency-Key。</td></tr></tbody></table></div>`}

function processView(){return `<div class="notice"><b>Snapshot 规则：</b>生产批创建时固化 ProcessVersion、BOM、Route 与 eBRVersion；后续主数据变更不追溯改写批快照。</div><div class="grid-2"><div class="card"><div class="card-head">工艺包 PP-2026-014 <span class="right">${status('已发布','green')} V6</span></div><div class="tabs"><div class="tab active">处方</div><div class="tab">工艺路线</div><div class="tab">参数限度</div><div class="tab">版本比较</div></div><div class="card-body"><table class="data-table"><thead><tr><th>序号</th><th>物料</th><th>理论量</th><th>允许偏差</th></tr></thead><tbody><tr><td>01</td><td>甘油</td><td>36.000 kg</td><td>±0.50%</td></tr><tr><td>02</td><td>纯化水</td><td>62.650 kg</td><td>±1.00%</td></tr><tr><td>03</td><td>羟苯乙酯</td><td>0.150 kg</td><td>±0.20%</td></tr><tr><td>04</td><td>乳化剂 OP-10</td><td>1.200 kg</td><td>±0.50%</td></tr></tbody></table></div></div><div class="card"><div class="card-head">发布校验</div><div class="card-body"><div class="timeline"><div class="timeline-item"><b>处方完整性</b><small>4/4 物料通过</small></div><div class="timeline-item"><b>路线连通性</b><small>6 个工序，无孤立节点</small></div><div class="timeline-item"><b>参数限度</b><small>18 项已定义上下限</small></div><div class="timeline-item"><b>eBR 模板绑定</b><small>EBR-CREAM-06 · V4</small></div></div></div></div></div>`}

function designer(){return `<div class="notice"><b>eBR Version V4 · DRAFT</b>　保存使用 If-Match: 8；发布后定义不可变，运行实例引用完整快照。</div><div class="kanban"><div class="card palette"><div class="card-head">字段组件</div><div class="card-body"><div class="component-row"><span class="handle">⠿</span>文本输入</div><div class="component-row"><span class="handle">⠿</span>数值 + 单位</div><div class="component-row"><span class="handle">⠿</span>设备扫码</div><div class="component-row"><span class="handle">⠿</span>物料扫码</div><div class="component-row"><span class="handle">⠿</span>电子签名</div><div class="component-row"><span class="handle">⠿</span>公式计算</div></div></div><div class="card canvas"><div class="paper"><span class="section-chip">工序 03 · 均质</span><h2>均质关键参数记录</h2><p class="muted">执行前确认设备状态与校准有效性。</p><div class="designer-block"><b>设备确认</b><div class="fields" style="margin-top:10px"><div class="field"><label>设备编码</label><input class="input" value="EQP-MIX-014"></div><div class="field"><label>校准状态</label><input class="input" value="有效至 2026-11-18"></div></div></div><div class="designer-block"><b>工艺参数</b><div class="form-grid" style="margin-top:10px"><div class="field"><label>转速 (rpm)</label><input class="input" value="2800"></div><div class="field"><label>时间 (min)</label><input class="input" value="20"></div><div class="field"><label>温度 (℃)</label><input class="input" value="42.6"></div></div></div><div class="designer-block"><b>操作确认</b><p class="muted">完成后由操作人签名，关键参数需复核人双签。</p>${btn('操作人签名','primary')}</div></div></div><div class="card inspector"><div class="card-head">字段属性</div><div class="card-body"><div class="field"><label>字段名称</label><input class="input" value="均质转速"></div><br><div class="field"><label>字段编码</label><input class="input" value="homogenize_rpm"></div><br><div class="field"><label>数据类型</label><select class="select"><option>Decimal</option></select></div><br><div class="grid-equal"><div class="field"><label>最小值</label><input class="input" value="2700"></div><div class="field"><label>最大值</label><input class="input" value="2900"></div></div><br><label><input type="checkbox" checked> 必填</label><br><br><label><input type="checkbox" checked> 超限触发偏差</label><br><br>${btn('运行 Lint','primary','toast')}</div></div></div>`}

function batchView(){return `<div class="stat-row"><div class="card stat"><div class="k">正式批号</div><div class="v code" style="font-size:18px">MB-20260928-006</div><div class="delta">复方甘油搽剂</div></div><div class="card stat"><div class="k">当前状态</div><div class="v" style="font-size:18px">${status('IN_PROCESS','blue')}</div><div class="muted">allowedActions: PAUSE</div></div><div class="card stat"><div class="k">计划 / 实际</div><div class="v">100 / 68</div><div class="muted">kg · 完成 68%</div></div><div class="card stat"><div class="k">eBR 完整度</div><div class="v">81%</div><div class="delta">6 / 8 工序记录完成</div></div></div><div class="grid-2"><div class="card"><div class="card-head">执行进度</div><div class="card-body"><div class="progress"><i></i></div><div class="timeline" style="margin-top:18px"><div class="timeline-item"><b>01 领料与复核　${status('完成','green')}</b><small>张伟 / 王强 · 08:20</small></div><div class="timeline-item"><b>02 称量　${status('完成','green')}</b><small>所有称量双人复核通过 · 08:58</small></div><div class="timeline-item"><b>03 均质　${status('执行中','blue')}</b><small>EQP-MIX-014 · 已运行 12m 18s</small></div><div class="timeline-item"><b>04 灌装　${status('等待','gray')}</b><small>前置 Gate：均质完成</small></div></div></div></div><div class="card"><div class="card-head">批快照</div><div class="card-body"><div class="desc" style="grid-template-columns:1fr 1fr"><div><label>ProcessVersion</label><strong>PP-2026-014 / V6</strong></div><div><label>eBRVersion</label><strong>EBR-CREAM-06 / V4</strong></div><div><label>BOM Hash</label><strong class="code">9bf7…e2a1</strong></div><div><label>Route Hash</label><strong class="code">6a0c…73d8</strong></div></div><br><div class="notice warning"><b>1 个提示：</b>灌装线清场确认将在 10:30 到期。</div>${btn('暂停生产','','sign')}</div></div></div>`}

function execution(){return `<div class="workbench"><div class="card"><div class="card-head">执行单元 · EU-03</div><div class="step-list"><div class="step done"><b>01 设备预检</b><div class="muted">完成 · 08:42</div></div><div class="step done"><b>02 物料确认</b><div class="muted">完成 · 08:49</div></div><div class="step active"><b>03 均质运行</b><div class="muted">执行中 · 12m 18s</div></div><div class="step"><b>04 取样</b><div class="muted">等待 Gate</div></div><div class="step"><b>05 清场</b><div class="muted">未开始</div></div></div></div><div class="card"><div class="card-head">工序 03 · 均质运行 <span class="right">${status('RUNNING','blue')}</span></div><div class="card-body"><div class="grid-equal"><div><div class="metric"><strong>2,798</strong><span>rpm</span></div><div class="progress"><i style="width:96%"></i></div><p class="muted">目标 2,800 rpm · 允许 2,700–2,900</p></div><div><div class="metric"><strong>42.6</strong><span>℃</span></div><div class="progress"><i style="width:71%;background:#13a8a8"></i></div><p class="muted">控制范围 40.0–45.0 ℃</p></div></div><div class="notice" style="margin-top:16px"><b>Equipment Gate 已通过：</b>EQP-MIX-014 在役；清洁状态合格；校准有效至 2026-11-18。</div><div class="form-grid"><div class="field"><label>过程观察</label><input class="input" value="物料均匀，无可见结块"></div><div class="field"><label>记录人</label><input class="input" value="张伟" readonly></div><div class="field"><label>记录时间</label><input class="input" value="2026-09-29 09:42:18" readonly></div></div></div></div><div class="card"><div class="card-head">执行控制</div><div class="card-body"><div class="gauge"></div><p style="text-align:center"><b>设备实时可用率</b></p>${btn('暂停工序','','sign')} ${btn('完成工序','primary','sign')}<hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><b>扫描输入</b><p class="muted">扫描设备、物料或人员凭证</p><input class="input" placeholder="等待扫码…"></div></div></div>`}

function weighing(){return `<div class="grid-2"><div><div class="card"><div class="card-head">称量任务 WGH-20260929-031 <span class="right">${status('待复核','amber')}</span></div><div class="card-body"><div class="form-grid"><div class="field"><label>物料</label><input class="input" value="甘油 / MAT-00116" readonly></div><div class="field"><label>物料批</label><input class="input" value="GLY-20260918" readonly></div><div class="field"><label>容器</label><input class="input" value="CNT-0441" readonly></div></div><div class="grid-equal" style="margin-top:18px"><div><div class="metric"><strong>36.012</strong><span>kg 净重</span></div><div class="progress"><i style="width:74%;background:#13a8a8"></i></div><p class="muted">目标 36.000 kg · 偏差 +0.033%</p></div><div class="notice"><b>天平 EQP-BAL-027</b><br>校准有效 · 水平状态正常 · 零点确认通过</div></div></div></div><div class="card" style="margin-top:12px"><div class="card-head">投料确认</div><div class="card-body"><table class="data-table"><thead><tr><th>序号</th><th>物料</th><th>称量净重</th><th>投料状态</th></tr></thead><tbody><tr><td>01</td><td>甘油</td><td>36.012 kg</td><td>${status('已扫码','green')}</td></tr><tr><td>02</td><td>纯化水</td><td>62.645 kg</td><td>${status('已投料','green')}</td></tr><tr><td>03</td><td>羟苯乙酯</td><td>0.150 kg</td><td>${status('等待','gray')}</td></tr></tbody></table></div></div></div><div class="card"><div class="card-head">双人复核 Gate</div><div class="card-body"><div class="notice warning"><b>复核人资格检查</b><br>需具备 <span class="code">mes:weigh:verify</span>，且不得与操作人为同一人。</div><div class="field"><label>操作人</label><input class="input" value="张伟 · OP-0182" readonly></div><br><div class="field"><label>复核人凭证</label><input class="input" placeholder="扫描工牌或输入账号"></div><br>${btn('复核并电子签名','primary','sign')}<hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><p class="muted">所有称量与投料形成不可覆盖的 QuantityEvent 和 Genealogy 记录；冲销只允许创建反向事件。</p></div></div></div>`}

function balance(){return `<div class="stat-row"><div class="card stat"><div class="k">理论投入</div><div class="v">100.000</div><div class="muted">kg</div></div><div class="card stat"><div class="k">实际产出</div><div class="v">98.640</div><div class="muted">kg</div></div><div class="card stat"><div class="k">样品 / 损耗</div><div class="v">0.520</div><div class="muted">kg</div></div><div class="card stat"><div class="k">平衡率</div><div class="v" style="color:var(--amber)">99.16%</div><div class="muted">限度 99.50–100.50%</div></div></div><div class="notice warning"><b>Material Balance Gate BLOCKED：</b>平衡率低于下限，必须完成调查并由 QA 批准后才能进入批放行。</div><div class="grid-2"><div class="card"><div class="card-head">物料平衡明细</div><div class="card-body"><table class="data-table"><thead><tr><th>物料</th><th>投入</th><th>产出/结余</th><th>差异</th><th>状态</th></tr></thead><tbody><tr><td>甘油</td><td>36.012</td><td>35.990</td><td>-0.022</td><td>${status('正常','green')}</td></tr><tr><td>纯化水</td><td>62.645</td><td>61.842</td><td>-0.803</td><td>${status('调查','red')}</td></tr><tr><td>辅料合计</td><td>1.350</td><td>1.328</td><td>-0.022</td><td>${status('正常','green')}</td></tr></tbody></table></div></div><div class="card"><div class="card-head">调查 INV-BAL-0028</div><div class="card-body"><div class="timeline"><div class="timeline-item"><b>自动触发调查</b><small>09:28 · 平衡率 99.16%</small></div><div class="timeline-item"><b>生产说明已提交</b><small>09:34 · 灌装管路残留估算 0.76 kg</small></div><div class="timeline-item"><b>QA 审核待办</b><small>责任人：李敏</small></div></div>${btn('查看偏差 DEV-260929-07')} ${btn('批准调查','primary','sign')}</div></div></div>`}

function release(){const gates=[['eBR 完整性','8/8 表单已提交并复核','ok'],['偏差与 CAPA','DEV-260929-07 已批准关闭','ok'],['物料平衡','调查 INV-BAL-0028 已批准','ok'],['IPC / QC 结果','12/12 结果符合标准','ok'],['电子签名完整性','26 个签名全部验证通过','ok'],['最终 eBR PDF','等待放行决定后生成归档','warn']];return `<div class="notice"><b>批放行决策模型：</b>所有 Gate 证据来自冻结快照与不可变审计记录。放行/拒绝都必须使用专用 GxpSignatureDialog。</div><div class="grid-2"><div class="card"><div class="card-head">放行 Gate Checklist <span class="right">${status('5/6 就绪','amber')}</span></div><div class="card-body"><div class="gate-list">${gates.map(([t,e,k])=>`<div class="gate ${k==='warn'?'warn':''}"><div class="check">${k==='warn'?'!':'✓'}</div><div><b>${t}</b><div class="evidence">${e}</div></div></div>`).join('')}</div></div></div><div><div class="card"><div class="card-head">批次摘要</div><div class="card-body"><div class="desc" style="grid-template-columns:1fr 1fr"><div><label>正式批号</label><strong class="code">MB-20260928-006</strong></div><div><label>产品</label><strong>复方甘油搽剂</strong></div><div><label>批量</label><strong>100 kg / 1,000 瓶</strong></div><div><label>当前状态</label><strong>${status('QA_REVIEW','blue')}</strong></div><div><label>生产完成</label><strong>2026-09-29 08:56</strong></div><div><label>审核人</label><strong>陈质管</strong></div></div></div></div><div class="card" style="margin-top:12px"><div class="card-head">允许动作</div><div class="card-body"><p class="code">allowedActions: [RELEASE, REJECT]</p>${btn('拒绝','','reject')} ${btn('签名并放行','primary','sign')}</div></div></div></div>`}

function signatureModal(){return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>GxP 电子签名</h2><span class="right muted">21 CFR Part 11 / GMP</span></div><div class="modal-body"><div class="signature-meaning"><b>签名含义：${hashRoute().includes('release')?'批准该批次放行':'确认并执行受控状态动作'}</b><br><span class="muted">记录将包含身份、时间、原因、对象版本和签名含义。</span></div><div class="field"><label>签名人</label><input class="input" value="陈质管 (QA-0018)" readonly></div><br><div class="field"><label>签名原因 *</label><select class="select"><option>已审核全部证据，同意执行</option><option>偏差调查结论可接受</option></select></div><br><div class="field"><label>密码确认 *</label><input class="input" type="password" value="signature"></div><p class="muted">密码仅发送至 POST /auth/reauth；签名使用五分钟、单次、对象绑定 token。密码和 token 不进入日志、AuditEvent 或 auth_context_json。</p></div><div class="modal-foot">${btn('取消','','close-modal')} ${btn('确认电子签名','primary','confirm-sign')}</div></div></div>`}

function render(){
  const page=resolveScenario(hashRoute()); let body='';
  if(page.mode==='audit-query') body=auditPage(); else if(page.mode==='integration-ops') body=integrationPage(); else if(page.mode==='query') body=queryPage(page); else if(page.mode==='create'||page.mode==='edit') body=materialForm(page); else if(page.id==='UI-MAT-V') body=materialView(page); else if(page.id==='UI-PKG-V') body=processView(); else if(page.mode==='designer') body=designer(); else if(page.mode==='batch') body=batchView(); else if(page.mode==='execution') body=execution(); else if(page.mode==='weighing') body=weighing(); else if(page.mode==='balance') body=balance(); else if(page.mode==='release') body=release(); else body=processView();
  app.innerHTML=shell(page,body); bind();
}

function bind(){
  document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',()=>go(el.dataset.route)));
  document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>handle(el.dataset.action)));
  document.querySelector('#queryInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')handle('search')});
}

function handle(action){
  const route=hashRoute();
  if(action==='create') return go(route===materialRoutes.query?materialRoutes.create:materialRoutes.create);
  if(action==='view') return go(materialRoutes.view);
  if(action==='edit') return go(materialRoutes.edit);
  if(action==='back-query') return go(materialRoutes.query);
  if(action==='search'){state.query=document.querySelector('#queryInput')?.value||'';state.toast='查询完成，条件已同步至页面状态';}
  if(action==='reset'){state.query='';state.toast='查询条件已重置';}
  if(action==='validation'){state.validation=true;state.conflict=false;}
  if(action==='conflict'){state.conflict=true;state.validation=false;}
  if(action==='reload'){state.conflict=false;state.toast='已重新加载最新版本 V4';}
  if(action==='save'||action==='save-draft'){state.toast=action==='save'?'保存成功，审计事件已记录':'草稿已保存';}
  if(action==='sign'||action==='reject'){state.signature=true;}
  if(action==='close-modal'){state.signature=false;}
  if(action==='confirm-sign'){state.signature=false;state.toast='电子签名验证通过，状态动作已提交';}
  if(action==='toast'||action==='audit'){state.toast=action==='audit'?'已打开只读审计时间线':'Lint 完成：0 错误，2 条建议';}
  render(); setTimeout(()=>{state.toast='';document.querySelector('.toast')?.remove()},2600);
}

window.addEventListener('hashchange',()=>{state.validation=false;state.conflict=false;state.signature=false;render()});
render();

