package com.hospital.mes.process.domain;
import com.hospital.mes.common.exception.*;
import com.hospital.mes.process.domain.ProcessCommands.*;
import java.math.BigDecimal;
import java.util.*;
public final class ProcessRules {
 private ProcessRules(){}
 public static void gate(boolean ok,String path){if(!ok)throw new ComplianceException("LINT_FAILED",path);}
 public static String text(String s,int max,String field){gate(s!=null&&!s.isBlank()&&s.length()<=max,field+": required/max "+max);return s.strip();}
 public static String optional(String s,int max,String field){return s==null||s.isBlank()?null:text(s,max,field);}
 public static BigDecimal decimal(String s,int precision,boolean positive,String field){gate(s!=null&&s.matches("-?\\d+(\\.\\d{1,6})?"),field+": decimal string required");var n=new BigDecimal(s);gate(n.precision()-n.scale()<=precision-6,field+": precision exceeded");gate(!positive||n.signum()>0,field+": must be positive");return n;}
 public static BigDecimal nullableDecimal(String s,int precision,String path){return s==null||s.isBlank()?null:decimal(s,precision,false,path);}
 public static void draft(String state){if(!"DRAFT".equals(state))throw new ResourceConflictException("PROCESS_VERSION_IMMUTABLE","Only draft definitions can be edited");}
 public static String transition(String state,String action){if(!"PUBLISH".equals(action)||!Set.of("DRAFT","SUBMITTED","APPROVED").contains(state))throw new ResourceConflictException("INVALID_STATE","Action "+action+" is not allowed in "+state);return "EFFECTIVE";}
 public static void formula(FormulaSave f){text(f.formulaCode(),64,"formula.formulaCode");decimal(f.batchBasisQty(),18,true,"formula.batchBasisQty");gate(f.items()!=null&&f.items().size()<=500,"formula.items: max 500");Set<Integer> lines=new HashSet<>();for(var row:f.items()){gate(row!=null,"formula.items: null row");String p="formula.items["+row.lineNo()+"]";gate(row.lineNo()!=null&&row.lineNo()>0&&lines.add(row.lineNo()),p+": duplicate/invalid line");decimal(row.requiredQty(),18,true,p+".requiredQty");var over=nullableDecimal(row.overagePct(),9,p+".overagePct");gate(over==null||over.signum()>=0,p+".overagePct: nonnegative required");gate(row.critical()!=null,p+".critical: required");}}
 public static void route(RouteSave r,boolean lint){
  text(r.routeCode(),64,"route.routeCode");gate(r.operations()!=null&&r.operations().size()<=200,"route.operations: max 200");Map<String,Operation> nodes=new LinkedHashMap<>();Set<Integer> sequence=new HashSet<>();
  for(var o:r.operations()){gate(o!=null,"route.operations: null row");String p="route.operations["+o.operationCode()+"]";text(o.operationCode(),64,p+".code");text(o.operationName(),200,p+".name");gate(nodes.putIfAbsent(o.operationCode(),o)==null,p+": duplicate operation");gate(o.sequenceNo()!=null&&o.sequenceNo()>0&&sequence.add(o.sequenceNo()),p+": duplicate/invalid sequence");optional(o.requiredRole(),64,p+".requiredRole");optional(o.requiredEquipmentType(),64,p+".requiredEquipmentType");gate(o.clearanceRequired()!=null,p+".clearanceRequired: required");completion(o.completionRule(),0,p+".completionRule");IpcDefinitionRules.validate(o.ipcDefinitions());gate(o.predecessorCodes()!=null&&o.predecessorCodes().size()<=200,p+".predecessorCodes: required/max 200");Set<String> predecessors=new HashSet<>();for(String prev:o.predecessorCodes()){text(prev,64,p+".predecessorCodes");gate(predecessors.add(prev)&&!prev.equals(o.operationCode()),p+": duplicate/self predecessor");}
   gate(o.parameters()!=null&&o.parameters().size()<=200,p+".parameters: required/max 200");Set<String> codes=new HashSet<>();for(var param:o.parameters()){gate(param!=null,p+".parameters: null row");String pp=p+".parameters["+param.parameterCode()+"]";text(param.parameterCode(),64,pp);text(param.parameterName(),200,pp+".name");gate(codes.add(param.parameterCode()),pp+": duplicate parameter");gate(Set.of("MANUAL","AUTO","HYBRID").contains(param.acquisitionMode()==null?"":param.acquisitionMode()),pp+": invalid acquisition mode");var lo=nullableDecimal(param.lowerLimit(),18,pp+".lowerLimit");var hi=nullableDecimal(param.upperLimit(),18,pp+".upperLimit");gate(lo==null||hi==null||lo.compareTo(hi)<=0,pp+": lower limit exceeds upper");}
  }
  if(lint){gate(!nodes.isEmpty(),"route.operations: at least one required");Map<String,Integer> state=new HashMap<>();for(String code:nodes.keySet())visit(code,nodes,state);}
 }
 private static void visit(String code,Map<String,Operation> nodes,Map<String,Integer> state){gate(nodes.containsKey(code),"route.operations["+code+"]: predecessor does not exist");int s=state.getOrDefault(code,0);gate(s!=1,"route.operations["+code+"]: cycle detected");if(s==2)return;state.put(code,1);for(String p:nodes.get(code).predecessorCodes())visit(p,nodes,state);state.put(code,2);}
 private static void completion(CompletionRule rule,int depth,String path){if(rule==null)return;gate(depth<8,path+": nesting too deep");String k=rule.kind();gate(k!=null,path+": kind required");if("ALL".equals(k)||"ANY".equals(k)){gate(rule.rules()!=null&&!rule.rules().isEmpty()&&rule.rules().size()<=20,path+": 1-20 rules required");for(var child:rule.rules()){gate(child!=null,path+": null rule");completion(child,depth+1,path);}}else{gate(Set.of("EBR_COMPLETE","PARAMETERS_WITHIN_LIMITS","REVIEW_COMPLETE").contains(k),path+": unknown kind");gate(rule.rules()==null,path+": leaf cannot have rules");}}
}
