package com.hospital.mes.process.domain;
public final class ProcessCommands {
 private ProcessCommands(){}
 public record ProductCreate(String productCode,String productName,String dosageForm,String specification,String baseUnitId){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record ProductUpdate(@com.fasterxml.jackson.annotation.JsonIgnore Long versionNo,String reason,String action,String productName,String dosageForm,String specification,String baseUnitId){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record PackageCreate(String productId,String packageCode){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record PackageUpdate(@com.fasterxml.jackson.annotation.JsonIgnore Long versionNo,String reason,String action){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record CurrentDefinitionSave(@com.fasterxml.jackson.annotation.JsonIgnore Long versionNo,@com.fasterxml.jackson.annotation.JsonIgnore String sourceVersionId,@com.fasterxml.jackson.annotation.JsonIgnore Long sourceVersionNo,FormulaSave formula,RouteSave route){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record VersionCreate(@com.fasterxml.jackson.annotation.JsonIgnore Long versionNo,String reason,@com.fasterxml.jackson.annotation.JsonIgnore String sourceVersionId){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Transition(@com.fasterxml.jackson.annotation.JsonIgnore Long versionNo,String reason,String reauthToken){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);}  @Override public String toString(){return "Transition[versionNo="+versionNo+", reauthToken=[REDACTED]]";} }
 public record FormulaLine(Integer lineNo,String materialId,String requiredQty,String unitId,String overagePct,Boolean critical){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record FormulaSave(@com.fasterxml.jackson.annotation.JsonIgnore Long versionNo,String reason,String formulaCode,String batchBasisQty,String unitId,java.util.List<FormulaLine> items){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Parameter(String parameterCode,String parameterName,String acquisitionMode,String unitId,String lowerLimit,String upperLimit){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
 public record CompletionRule(String kind,java.util.List<CompletionRule> rules){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record Operation(String operationCode,String operationName,Integer sequenceNo,String requiredRole,CompletionRule completionRule,java.util.List<String> predecessorCodes,String requiredEquipmentType,Boolean clearanceRequired,java.util.List<Parameter> parameters,java.util.List<IpcDefinition> ipcDefinitions){ public Operation { ipcDefinitions=ipcDefinitions==null?java.util.List.of():java.util.List.copyOf(ipcDefinitions); } public Operation(String code,String name,Integer seq,String role,CompletionRule rule,java.util.List<String> predecessors,String equipment,Boolean clearance,java.util.List<Parameter> params){this(code,name,seq,role,rule,predecessors,equipment,clearance,params,java.util.List.of());} @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
 public record IpcDefinition(String ipcCode,String name,Boolean required,String resultType,String lowerLimit,String upperLimit,String expectedText,String unitId,String methodReference){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown IPC field: "+field);} }
 public record RouteSave(@com.fasterxml.jackson.annotation.JsonIgnore Long versionNo,String reason,String routeCode,java.util.List<Operation> operations){ @com.fasterxml.jackson.annotation.JsonAnySetter public void reject(String field,Object value){throw new IllegalArgumentException("Unknown field: "+field);} }
}
