import {api,idempotencyKey} from './http'
import type {EbrForm,EbrSignatureRule} from '../views/ebr/types'
export type RuntimeValue=string|boolean|string[]|null
export interface RuntimeField{fieldCode:string;occurrencePath:string;label:string;type:string;value:RuntimeValue;displayValue:string;unitId:string|null;required:boolean;readonly:boolean;visible:boolean;validationState:'VALID'|'MISSING'|'BLOCK'|'WARN';source:string;provenance:string[];allowedActions:string[]}
export interface ValueRevision{id:string;fieldCode:string;occurrencePath:string;revisionNo:number;previousRevisionId:string|null;rawValueJson:string;normalizedValueJson:string;sourceType:string;sourceRef:string|null;recordedBy:string;recordedAt:string;changeReason:string;superseded:boolean}
export interface ReviewRule{reviewRuleId:string;objectScope:string;objectCode:string;reviewType:'VERIFY'|'APPROVE';requiredRole:string;independentUserRequired:boolean;sequenceNo:number}
export interface RuntimeReview{id:string;formRevision:number;reviewRuleId:string;reviewType:string;reviewerId:string;decision:string;comment:string|null;reason:string;reviewedAt:string;signatureId:string;invalidatedAt:string|null;invalidationReason:string|null}
export interface RuntimeRuleExecution{id:string;ruleCode:string;triggerPoint:string;passed:boolean;severity:string|null;outputJson:string|null;executedAt:string;inputSnapshotJson:string}
export interface FormRuntime{id:string;operationExecutionId:string;formDefId:string;formCode:string;formName:string;occurrenceNo:number;status:'DRAFT'|'SUBMITTED'|'VERIFIED'|'APPROVED';formRevision:number;versionNo:number;definitionHash:string;submittedBy:string|null;submittedAt:string|null;definition:EbrForm;fields:RuntimeField[];currentValues:ValueRevision[];valueRevisions:ValueRevision[];ruleExecutions:RuntimeRuleExecution[];reviewRequirements:ReviewRule[];signatureRequirements:EbrSignatureRule[];reviews:RuntimeReview[];signatureIds:string[];allowedActions:string[]}
export const runtimeStates={DRAFT:'草稿',SUBMITTED:'已提交',VERIFIED:'已核对',APPROVED:'已批准'}
export function runtimeKey(field:Pick<RuntimeField,'fieldCode'|'occurrencePath'>){return `${field.fieldCode}|${field.occurrencePath}`}
export function runtimePayload(fields:RuntimeField[],values:Record<string,RuntimeValue>,sources:Record<string,string>){return fields.filter(f=>f.allowedActions.includes('EDIT')).map(f=>{const key=runtimeKey(f),value=values[key]??null;if(['NUMBER','TIMER','CALCULATED','INSTRUMENT_VALUE'].includes(f.type)&&value!==null&&(typeof value!=='string'||!/^\-?[0-9]+(\.[0-9]+)?$/.test(value)))throw Error(`${f.label} 必须填写精确数值`);return {fieldCode:f.fieldCode,occurrencePath:f.occurrencePath,value,unitId:f.unitId,sourceRef:f.source==='BARCODE'?(sources[key]?.trim()||null):null}})}
export function runtimeHeaders(){let fingerprint='',key='';return {forRequest(url:string,body:Record<string,unknown>,revision:number){const {reauthToken:_,...safe}=body;const next=JSON.stringify({url,body:safe,revision});if(next!==fingerprint){fingerprint=next;key=idempotencyKey()}return {'Idempotency-Key':key,'If-Match':`"${revision}"`}},complete(){fingerprint=''}}}
export const runtimeApi={get:(id:string)=>api<FormRuntime>({url:`/forms/${id}/render-model`})}
