import {describe,it,expect,vi} from 'vitest'
import {readFileSync} from 'node:fs'
import {resolve} from 'node:path'
const source=readFileSync(resolve(process.cwd(),'public/onlyoffice-plugin/plugin.js'),'utf8')
const html=readFileSync(resolve(process.cwd(),'public/onlyoffice-plugin/index.html'),'utf8')
describe('Community Word plugin safety contract',()=>{
 it('uses a fixed local SDK and ignores an attacker-controlled office URL',async()=>{document.body.innerHTML='<input id="search"><div id="error"></div><div id="fields"></div><div id="columns"></div><button id="insert-loop"></button>';const calls=vi.fn(),plugin:{init?:()=>Promise<void>;executeMethod:typeof calls;button?:()=>void}={executeMethod:calls};const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>[{key:'reportNo',label:'报告编号',group:'报告信息',description:'系统报告号',example:'DEMO',repeated:false},{key:'itemName',label:'检验项目',group:'检验项目',description:'项目名称',example:'外观',repeated:true}]});new Function('window','document','location','fetch',source)({Asc:{plugin}},document,{search:'?session=test&token=fixture&office=https://untrusted.invalid',origin:'http://mes.test'},fetch);await plugin.init!();expect(document.querySelectorAll('script')).toHaveLength(0);expect(html).toContain('src="vendor/plugins.js"');(document.querySelector('#fields button') as HTMLButtonElement).click();expect(calls).toHaveBeenCalledWith('AddContentControl',[2,{Tag:'mes-field:reportNo',Alias:'报告编号',PlaceHolderText:'【报告编号】',Lock:0}],expect.any(Function));expect(fetch).toHaveBeenCalledWith('/api/v1/printing/editor/transfer/test/dictionary?token=fixture',{credentials:'omit'})})
 it('inserts selected loop columns through a DOCX URL, without an arbitrary script expression',async()=>{document.body.innerHTML='<input id="search"><div id="error"></div><div id="fields"></div><div id="columns"></div><button id="insert-loop"></button>';const calls=vi.fn(),plugin:{init?:()=>Promise<void>;executeMethod:typeof calls;button?:()=>void}={executeMethod:calls};const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>[{key:'itemName',label:'检验项目',group:'检验项目',description:'项目名称',example:'外观',repeated:true}]});new Function('window','document','location','fetch',source)({Asc:{plugin}},document,{search:'?session=test&token=fixture',origin:'http://mes.test'},fetch);await plugin.init!();(document.querySelector('#insert-loop') as HTMLButtonElement).click();const [method,args]=calls.mock.calls[0]!;expect(method).toBe('InsertAndReplaceContentControls');expect(args[0][0]).toMatchObject({Props:{Tag:'mes-table:items',Alias:'检验项目明细'},Url:'http://mes.test/api/v1/printing/editor/transfer/test/loop?token=fixture&columns=itemName'});expect(args[0][0]).not.toHaveProperty('Script')})
})
