<script setup lang="ts">
import {ref,computed,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,errorMessage,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import IncomingReferencePicker from '../quality/IncomingReferencePicker.vue'
import ReadReference from '../master/ReadReference.vue'
import {definitions,status,type Row} from './model'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),def=computed(()=>definitions[String(route.meta.resource)]!),filters=ref({keyword:'',status:'',mainBatchId:''}),data=ref<Page<Row>>({items:[],total:0,page:0,size:20}),busy=ref(false),error=ref('')
const columns=computed(()=>[{title:'业务编号',dataIndex:def.value.number},{title:'生产批 / 成品请验',key:'source'},{title:'数量 / 综合结论',key:'quantity'},{title:'业务状态',key:'status'},{title:'创建时间',dataIndex:'createdAt'},{title:'操作',key:'actions'}])
async function load(page=0){busy.value=true;error.value='';try{const params={page,size:20,keyword:filters.value.keyword||undefined,...(def.value.states.length?{status:filters.value.status||undefined}:{}),...(['inbound','requests','shipments'].includes(String(route.meta.resource))?{mainBatchId:filters.value.mainBatchId||undefined}:{})};await router.replace({query:Object.fromEntries(Object.entries(params).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]))});data.value=await api({url:def.value.api,params})}catch(e){error.value=errorMessage(e)}finally{busy.value=false}}
watch(()=>route.meta.resource,()=>{filters.value={keyword:String(route.query.keyword??''),status:String(route.query.status??''),mainBatchId:String(route.query.mainBatchId??'')};void load(Number(route.query.page??0))},{immediate:true})
</script><template><main data-ui-template="T1" class="admin-page master-page t1-query-list"><header class="admin-page-header"><div><h1>{{def.title}}</h1><p>成品受控业务记录 · 生产批、质量证据与库存追溯</p></div><a-button v-if="def.create&&auth.can(def.permission+':create')" type="primary" @click="router.push(def.path+'/create')">＋ 新增{{def.title}}</a-button></header><a-card title="查询条件" class="query-card"><form class="query-form" @submit.prevent="load()"><label><span class="form-field-label">关键字</span><a-input v-model:value="filters.keyword" aria-label="关键字"/></label><label v-if="['inbound','requests','shipments'].includes(String(route.meta.resource))"><span class="form-field-label">生产批</span><IncomingReferencePicker v-model="filters.mainBatchId" field="mainBatchId" :context="{}" input-label="生产批查询"/></label><label v-if="def.states.length"><span class="form-field-label">状态</span><a-select v-model:value="filters.status" allow-clear aria-label="状态"><a-select-option v-for="s in def.states" :key="s" :value="s">{{status[s]}}</a-select-option></a-select></label><a-space><a-button @click="filters={keyword:'',status:'',mainBatchId:''};load()">重置</a-button><a-button type="primary" html-type="submit">查询</a-button></a-space></form></a-card><a-alert v-if="error" type="error" :message="error" show-icon/><a-card title="数据列表" class="result-card"><a-table :columns="columns" :data-source="data.items" row-key="id" :loading="busy" :pagination="false" :scroll="{x:900}"><template #bodyCell="{column,record}"><ReadReference v-if="column.key==='source'&&record.mainBatchId" field="mainBatchId" :value="record.mainBatchId" :name="record.batch?.batchNo"/><a-button v-else-if="column.key==='source'" type="link" @click="router.push('/finished/requests/'+record.inspectionRequestId)">成品请验引用 {{record.inspectionRequestId}}</a-button><span v-else-if="column.key==='quantity'">{{record.quantity??status[record.overallConclusion]??'—'}} <ReadReference v-if="record.unitId" field="unitId" :value="record.unitId"/></span><a-tag v-else-if="column.key==='status'">{{status[record.status]??'取样已记录'}}</a-tag><a-button v-else-if="column.key==='actions'" type="link" @click="router.push({path:def.path+'/'+record.id,query:route.query})">查看</a-button></template></a-table><div class="table-footer"><span>共 {{data.total}} 条</span><a-pagination :current="data.page+1" :page-size="data.size" :total="data.total" :show-size-changer="false" @change="(p:number)=>load(p-1)"/></div></a-card></main></template>
