<script setup lang="ts">
import {ref,watch} from 'vue'
import {useRouter} from 'vue-router'
import {api,errorMessage} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {status,type Row} from './model'
const props=defineProps<{lotId:string}>(),chain=ref<Row>({}),error=ref(''),router=useRouter(),auth=useAuthStore()
watch(()=>props.lotId,async()=>{try{chain.value=await api({url:'/finished-material-lots/'+props.lotId+'/chain'})}catch(e){error.value=errorMessage(e)}},{immediate:true})
</script><template><section><a-alert v-if="error" type="error" :message="error"/><div class="finished-chain"><article v-for="r in chain.receiving??[]" :key="'receive'+r.id"><h3>成品仓库接收</h3><strong>{{r.requestNo}}</strong><p>{{status[r.status]}} · {{r.quantity}} · {{r.confirmedAt??'尚未确认'}}</p><a-button type="link" @click="router.push('/finished/inbound/'+r.id)">查看入库申请</a-button></article><article v-for="r in chain.finishedQuality?.requests??[]" :key="'qc'+r.id"><h3>成品请验与取样</h3><strong>{{r.inspectionRequestNo}}</strong><p>{{status[r.status]}} · {{r.samplingRecords.length}} 条取样记录</p><a-button type="link" @click="router.push('/finished/requests/'+r.id)">查看成品请验</a-button><div v-for="report in r.reports" :key="report.id"><p>{{report.reportNo}} · {{status[report.status]}} · {{status[report.overallConclusion]}}</p><a-button type="link" @click="router.push('/finished/reports/'+report.id)">查看成品报告</a-button></div></article><article v-for="r in chain.decisions??[]" :key="'decision'+r.id"><h3>QA批放行</h3><p>{{r.decision==='RELEASED'?'已放行':'已拒绝'}} · {{r.decisionAt}}</p><a-button type="link" @click="router.push('/qa/batches/'+r.mainBatchId+'/review')">查看QA批审核</a-button></article><article v-for="r in chain.shipments??[]" :key="'shipment'+r.id"><h3>成品发货出库</h3><strong>{{r.shipmentNo}}</strong><p>{{status[r.status]}} · {{r.quantity}} · {{r.receivingParty}}</p><p>{{r.confirmedAt??'尚未发货'}} · {{r.ledgerId?'已关联实际库存流水':'尚未扣库'}}</p><a-button type="link" @click="router.push('/finished/shipments/'+r.id)">查看发货出库单</a-button></article></div><p v-for="(value,key) in chain.access" :key="key" v-show="value==='NOT_AUTHORIZED'">部分来源记录无查看权限，未展示其业务事实。</p><a-space><a-button v-if="chain.mainBatchId&&auth.can('trace:view')" @click="router.push({path:'/trace',query:{mainBatchId:chain.mainBatchId}})">生产投料与来料反向追溯</a-button><a-button v-if="chain.mainBatchId&&auth.can('wms:finished-shipment:create')&&chain.lot?.qualityStatus==='RELEASED'&&chain.lot?.inventoryStatus==='AVAILABLE'" @click="router.push({path:'/finished/shipments/create',query:{mainBatchId:chain.mainBatchId}})">创建成品发货单</a-button></a-space></section></template><style scoped>.finished-chain{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.finished-chain article{border:1px solid #e6edf5;border-radius:8px;padding:16px;overflow-wrap:anywhere}h3{font-size:15px}p{color:#667085}@media(max-width:1000px){.finished-chain{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
