export type Row=Record<string,any>
export interface Command {fields:string[];signed?:{type:string;meaning:string}}
export interface Definition {title:string;api:string;path:string;permission:string;number:string;states:string[];create?:Command;actions:Record<string,{title:string;permission:string;command:Command;path:string}>}
export const commands:Record<string,Command>={inboundCreate:{fields:['requestNo','mainBatchId','reason']},requestCreate:{fields:['inspectionRequestNo','inboundRequestId','reason']},shipmentCreate:{fields:['shipmentNo','mainBatchId','locationId','quantity','unitId','receivingParty','reason']},reason:{fields:['reason']},confirmReceipt:{fields:['locationId','reason'],signed:{type:'FINISHED_WAREHOUSE_RECEIPT',meaning:'VERIFY'}},sample:{fields:['samplingNo','sampleNo','sampleType','samplingLocation','quantity','unitId','samplingMethod','reason'],signed:{type:'FINISHED_SAMPLING',meaning:'VERIFY'}},report:{fields:['reportNo','reason']},approve:{fields:['reason'],signed:{type:'FINISHED_INSPECTION_REPORT',meaning:'APPROVE'}},ship:{fields:['reason'],signed:{type:'FINISHED_SHIPMENT',meaning:'VERIFY'}}}
export const definitions:Record<string,Definition>={
 inbound:{title:'成品入库申请',api:'/finished-inbound-requests',path:'/finished/inbound',permission:'wms:finished-inbound',number:'requestNo',states:['DRAFT','SUBMITTED','CONFIRMED','CANCELLED'],create:commands.inboundCreate,actions:{SUBMIT:{title:'提交入库申请',permission:'wms:finished-inbound:submit',command:commands.reason!,path:'submit'},CONFIRM:{title:'仓库确认接收',permission:'wms:finished-inbound:confirm',command:commands.confirmReceipt!,path:'confirm'},CANCEL:{title:'取消申请',permission:'wms:finished-inbound:cancel',command:commands.reason!,path:'cancel'}}},
 requests:{title:'成品请验单',api:'/quality/finished-inspection-requests',path:'/finished/requests',permission:'qms:finished-request',number:'inspectionRequestNo',states:['DRAFT','SUBMITTED','ACCEPTED','COMPLETED'],create:commands.requestCreate,actions:{SUBMIT:{title:'提交成品请验',permission:'qms:finished-request:submit',command:commands.reason!,path:'submit'},ACCEPT:{title:'QC接收请验',permission:'qms:finished-request:accept',command:commands.reason!,path:'accept'},SAMPLE:{title:'执行成品取样',permission:'qms:finished-sampling:create',command:commands.sample!,path:'sample'},GENERATE_REPORT:{title:'生成成品检验报告',permission:'qms:finished-report:generate',command:commands.report!,path:'generate-report'}}},
 sampling:{title:'成品取样记录',api:'/quality/finished-sampling-records',path:'/finished/sampling',permission:'qms:finished-sampling',number:'samplingNo',states:[],actions:{}},
 reports:{title:'成品检验报告',api:'/quality/finished-inspection-reports',path:'/finished/reports',permission:'qms:finished-report',number:'reportNo',states:['GENERATED','APPROVED'],actions:{APPROVE:{title:'独立QC审批',permission:'qms:finished-report:approve',command:commands.approve!,path:'approve'}}},
 shipments:{title:'成品发货出库',api:'/finished-shipments',path:'/finished/shipments',permission:'wms:finished-shipment',number:'shipmentNo',states:['DRAFT','CONFIRMED','CANCELLED'],create:commands.shipmentCreate,actions:{CONFIRM:{title:'确认发货出库',permission:'wms:finished-shipment:confirm',command:commands.ship!,path:'confirm'},CANCEL:{title:'取消发货',permission:'wms:finished-shipment:cancel',command:commands.reason!,path:'cancel'}}}
}
export const labels:Record<string,string>={requestNo:'入库申请单号',inspectionRequestNo:'成品请验单号',shipmentNo:'发货出库单号',mainBatchId:'生产批',inboundRequestId:'已确认成品入库',locationId:'库位',quantity:'数量',unitId:'单位',receivingParty:'接收方',reason:'操作原因',samplingNo:'取样记录编号',sampleNo:'样品编号',sampleType:'样品类型',samplingLocation:'取样位置',samplingMethod:'取样方法',reportNo:'检验报告编号',materialLotId:'成品库存批次',productId:'产品',inspectionRequestId:'成品请验单',qcSpecificationVersionId:'冻结质量标准版本',createdBy:'申请人',createdAt:'创建时间',submittedBy:'提交人',submittedAt:'提交时间',confirmedBy:'确认人',confirmedAt:'确认时间',acceptedBy:'QC接收人',acceptedAt:'QC接收时间',sampledBy:'取样人',sampledAt:'取样时间',generatedBy:'报告生成人',generatedAt:'报告生成时间',approvedBy:'审批人',approvedAt:'审批时间',signatureId:'电子签名引用',releaseDecisionId:'QA放行决定引用',ledgerId:'库存流水引用',generationNo:'报告归档代次',sourceDigest:'冻结来源摘要',evidenceDigest:'报告证据摘要'}
export const status:Record<string,string>={DRAFT:'草稿',SUBMITTED:'已提交',CONFIRMED:'已确认',CANCELLED:'已取消',ACCEPTED:'QC已接收',COMPLETED:'已完成',GENERATED:'已生成',APPROVED:'已批准',PASS:'合格',FAIL:'不合格',INVALID:'无效',TEST_SAMPLE:'检验样',RETENTION_SAMPLE:'留样',RETEST_SAMPLE:'复检样',OTHER_APPROVED:'其他批准样品'}
export function canAct(row:Row,action:string,permission:boolean){return permission&&Array.isArray(row.allowedActions)&&row.allowedActions.includes(action)}
export function commandBody(command:Command,form:Row,version?:number):Row{const result:Row=version===undefined?{}:{versionNo:version};for(const field of command.fields){const value=String(form[field]??'').trim();if(!value)throw Error('请填写'+labels[field]);if(field==='quantity'&&!/^(?:0|[1-9][0-9]{0,11})(?:\.[0-9]{1,6})?$/.test(value))throw Error('数量最多12位整数、6位小数');if(field==='reason'&&value.length>1000)throw Error('操作原因最多1000字');result[field]=value}return result}

export function inboundCreateBody(form:Row):Row{
 const body=commandBody(commands.inboundCreate!,form)
 if(form.createInspectionDraft===true){const number=String(form.inspectionRequestNo??'').trim();if(!number||number.length>80)throw Error('请填写成品请验单号（最多80字）');body.createInspectionDraft=true;body.inspectionRequestNo=number}
 return body
}
