<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,idempotencyKey} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {useControlledRequest} from '../../api/controlled'
import {productionOperations,productionActions,formSchema} from './productionModel'
import {schemas,commandBody,display} from '../quality/incomingModel'
import IncomingFormFields from '../quality/IncomingFormFields.vue'
import IncomingFacts from '../quality/IncomingFacts.vue'
import ExecutionOverview from './ExecutionOverview.vue'

type Row=Record<string,unknown>
const route=useRoute(),router=useRouter(),auth=useAuthStore(),request=useControlledRequest(),{busy,error,conflict}=request
const execution=ref<Row|null>(null),operations=ref<Row[]>([]),weighings=ref<Row[]>([]),charges=ref<Row[]>([]),forms=ref<Row[]>([]),form=ref<Row>({}),password=ref(''),eligibility=ref<Row|null>(null),stock=ref<Row|null>(null)
const batch=ref<Row|null>(null)
const frozen=computed(()=>((batch.value?.processSnapshot as Row|undefined)?.snapshot??{}) as Row)
const process=computed(()=>(frozen.value.process??{}) as Row)
const frozenMaterials=computed<Row[]>(()=>Array.isArray(frozen.value.materials)?frozen.value.materials as Row[]:[])
const formContext=computed(()=>{const formulaItems=(((process.value.formula??{}) as Row).items??[]) as Row[];const selectedFormula=formulaItems.find(i=>String(i.formulaItemId)===String(form.value.formulaItemId));return {operations:operations.value,weighings:weighings.value,formulaItems,materialId:selectedFormula?.materialId,materialIds:[...new Set(formulaItems.map(i=>String(i.materialId??'')).filter(Boolean))],parameters:((((process.value.route??{}) as Row).operations??[]) as Row[]).find(o=>String(o.operationDefId)===String(selected.value?.source.operationDefId))?.parameters??[]}})
const selected=ref<{url:string;schema:string;version:number;title:string;source:Row}|null>(null)
const weighingMode=computed(()=>route.meta.mode==='weighing'),chargeMode=computed(()=>route.meta.mode==='charge'),signed=computed(()=>selected.value?.schema==='WeighingVerifyCommand')
let lastFingerprint='',lastKey=idempotencyKey()
async function load(){busy.value=true;request.clear();try{execution.value=await api({url:`/execution-units/${route.params.id}`});const jobs:Array<Promise<void>>=[];if(auth.can('production:batch:view')&&execution.value?.mainBatchId)jobs.push(api<Row>({url:`/main-batches/${execution.value!.mainBatchId}`}).then(x=>{batch.value=x}));if(auth.can('mes:operation:view'))jobs.push(api<Row[]>({url:`/execution-units/${route.params.id}/operations`}).then(x=>{operations.value=x}));if(auth.can('mes:weigh:view'))jobs.push(api<Row[]>({url:`/execution-units/${route.params.id}/weighings`}).then(x=>{weighings.value=x}));if(auth.can('mes:charge:view'))jobs.push(api<Row[]>({url:`/execution-units/${route.params.id}/material-charges`}).then(x=>{charges.value=x}));if(auth.can('ebr:form:view'))jobs.push(api<Row[]>({url:`/execution-units/${route.params.id}/forms`}).then(x=>{forms.value=x}));const outcomes=await Promise.allSettled(jobs);for(const outcome of outcomes)if(outcome.status==='rejected')await request.failure(outcome.reason)}catch(e){await request.failure(e)}finally{busy.value=false}}
function open(url:string,source:Row,title:string){const path=url.replace(/\/[0-9]+(?=\/|$)/g,'/{id}');const command=productionOperations.find(o=>o.path===path&&o.method==='POST');if(!command||!auth.can(command.permission))return;selected.value={url,schema:command.schema,version:Number(source.versionNo??0),title,source};form.value={};password.value='';eligibility.value=null;stock.value=null;request.clear()}
function operationActions(row:Row){return ['equipment-usages','parameter-values','start','pause','resume','complete'].filter(a=>{const op=productionOperations.find(o=>o.path===`/operations/{id}/${a}`);const states:Record<string,string[]>={start:['READY'],pause:['IN_PROGRESS'],resume:['PAUSED'],complete:['IN_PROGRESS'],'equipment-usages':['PENDING','READY','PAUSED'],'parameter-values':['IN_PROGRESS']};return op&&auth.can(op.permission)&&states[a]?.includes(String(row.status))})}
async function checkLot(){const id=form.value.materialLotId;if(!id)return;try{eligibility.value=await api({url:`/wms/material-lots/${id}/eligibility`});stock.value=await api({url:'/wms/inventory',params:{materialLotId:id,page:0,size:100}})}catch(e){await request.failure(e)}}
async function save(){if(!selected.value)return;busy.value=true;try{const s=selected.value,body=commandBody(schemas[s.schema]!,{...form.value,versionNo:s.version,executionUnitId:String(route.params.id),...(s.schema==='ParameterRecord'?{sourceMode:'MANUAL'}:{})}) as Row;body.versionNo=s.version;if(schemas[s.schema]!.properties?.executionUnitId)body.executionUnitId=String(route.params.id);if(s.schema==='ParameterRecord')body.sourceMode='MANUAL';if(s.schema==='ChargeCreate'){const op=operations.value.find(o=>String(o.id)===String(body.operationExecutionId));if(!op)throw Error('请选择当前执行单元的实际工序');body.versionNo=Number(op.versionNo)}const fingerprint=JSON.stringify({url:s.url,body});if(fingerprint!==lastFingerprint){lastFingerprint=fingerprint;lastKey=idempotencyKey()}
 if(signed.value){if(!password.value)throw Error('请输入签名密码');const r=await api<{reauthToken:string}>({url:'/auth/reauth',method:'POST',data:{objectType:'WEIGHING_VERIFICATION',objectId:`${s.source.id}:VERIFY:${s.version}`,recordVersion:s.version,meaning:'VERIFY',credential:password.value}});body.reauthToken=r.reauthToken}
 await api({url:s.url,method:'POST',data:body,headers:{'Idempotency-Key':lastKey,'If-Match':`"${body.versionNo}"`}});lastFingerprint='';selected.value=null;form.value={};await load()
 }catch(e){await request.failure(e)}finally{password.value='';busy.value=false}}
watch(()=>route.fullPath,()=>{selected.value=null;form.value={};void load()},{immediate:true})
</script>
<template><main class="admin-page master-page execution-workbench" data-ui-template="T4"><header v-if="weighingMode||chargeMode||!execution" class="admin-page-header"><div><a-button type="link" @click="router.back()">← 返回</a-button><h1>{{weighingMode?'称量工作台':chargeMode?'投料工作台':'生产执行工作台'}}</h1><p>{{execution?.executionNo}} · {{display(execution?.status)}}</p></div><a-space wrap><a-button v-if="auth.can('mes:weigh:create')" @click="router.push(`/mes/execution/${route.params.id}/weighing`)">称量</a-button><a-button v-if="auth.can('mes:charge:create')" @click="router.push(`/mes/execution/${route.params.id}/charge`)">投料</a-button><a-button v-if="execution&&weighingMode&&auth.can('mes:weigh:create')" type="primary" @click="open('/weighings',execution,'新增称量')">新增称量</a-button><a-button v-if="execution&&chargeMode&&auth.can('mes:charge:create')" type="primary" @click="open('/material-charges',execution,'新增投料')">新增投料</a-button></a-space></header><a-alert v-if="error" type="error" :message="error"/><a-alert v-if="conflict" type="warning" message="记录已变化，当前输入已保留。重新加载后请再次选择操作。"><template #action><a-button @click="load">重新加载</a-button></template></a-alert>
<a-card v-if="weighingMode&&frozenMaterials.length" title="批次冻结称量策略" class="form-section"><p class="policy-summary-hint">称量时依据冻结策略和实际设备校准信息核对，以下是受控摘要。</p><a-table :data-source="frozenMaterials" :columns="[{title:'物料名称',dataIndex:'materialName'},{title:'基本单位',dataIndex:'baseUnitName'},{title:'是否必须称量',key:'required'},{title:'称量精度',key:'precision'},{title:'允许偏差',key:'tolerance'}]" :row-key="(r:Row)=>String(r.materialCode??r.id)" :pagination="false" size="small"><template #bodyCell="{column,record:r}"><template v-if="column.key==='required'">{{r.weighingPolicy?.required?'是':'否'}}</template><template v-else-if="column.key==='precision'">{{r.weighingPolicy?.precision??'—'}}</template><template v-else-if="column.key==='tolerance'">{{r.weighingPolicy?.tolerancePct==null?'—':r.weighingPolicy.tolerancePct+'%'}}</template></template></a-table><details class="weighing-policy-evidence"><summary>查看冻结策略完整证据</summary><IncomingFacts :value="{materials:frozen.materials}"/></details></a-card>
<ExecutionOverview v-if="execution&&!weighingMode&&!chargeMode" :execution="execution" :batch="batch" :operations="operations" :weighings="weighings" :charges="charges" :forms="forms" :actions="operationActions" @command="(operation,action)=>open(`/operations/${operation.id}/${action}`,operation,productionActions[action]!)" @reload="load"/>
<a-card v-for="weighing in (weighingMode?weighings:[])" :key="String(weighing.id)" title="称量记录" class="form-section"><IncomingFacts :value="weighing"/><a-button v-if="auth.can('mes:weigh:verify')&&auth.can('ebr:sign')&&weighing.status==='CONFIRMED'" @click="open(`/weighings/${weighing.id}/verify`,weighing,'独立复核称量')">独立复核</a-button></a-card>
<a-card v-for="charge in (chargeMode?charges:[])" :key="String(charge.id)" title="投料记录" class="form-section"><IncomingFacts :value="charge"/><a-button v-if="charge.status==='CONFIRMED'&&auth.can('mes:charge:reverse')" @click="open(`/material-charges/${charge.id}/reverse`,charge,'冲销投料')">冲销投料</a-button><a-button v-if="auth.can('trace:view')" type="link" @click="router.push({path:'/trace',query:{materialLotId:String(charge.materialLotId)}})">追溯来料质量链</a-button></a-card>
<a-card v-if="selected" :title="selected.title" class="form-section"><form @submit.prevent="save"><IncomingFormFields v-model="form" :schema="formSchema(selected.schema)" :context="formContext" :disabled="busy"/><a-button v-if="['WeighingCreate','ChargeCreate'].includes(selected.schema)&&auth.can('wms:inventory:view')" @click="checkLot">核对物料放行与库存</a-button><IncomingFacts v-if="eligibility" :value="eligibility"/><IncomingFacts v-if="stock" :value="stock"/><div v-if="signed" class="master-form"><label><span class="form-field-label">签名密码</span><input v-model="password" type="password" autocomplete="current-password" class="master-native-input" aria-label="签名密码" required/></label></div><a-space style="margin-top:16px"><a-button type="primary" html-type="submit" :loading="busy" :disabled="conflict">{{signed?'签名并复核':'提交'}}</a-button><a-button @click="selected=null;form={}">取消</a-button></a-space></form></a-card></main></template>

<style scoped>
.policy-summary-hint{margin:0 0 10px;color:#667085;font-size:12px}.weighing-policy-evidence{margin-top:10px;font-size:12px;color:#607086}.weighing-policy-evidence summary{cursor:pointer}#app .execution-workbench :deep(.incoming-form>label:has(.incoming-reference)){align-items:start}#app .execution-workbench :deep(.incoming-form>label:has(.incoming-reference)>.form-field-label){padding-top:10px}
#app .execution-workbench>.admin-page-header{background:transparent;border:0;padding:4px 0 16px;box-shadow:none}
</style>
