<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {useControlledRequest} from '../../api/controlled'
import './productionModel'
import {label,display,schemas} from '../quality/incomingModel'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),request=useControlledRequest(),{busy,error}=request,rows=ref<Record<string,unknown>[]>([]),total=ref(0),page=ref(1),keyword=ref(''),status=ref('')
const batch=computed(()=>route.meta.resource==='batches'),title=computed(()=>batch.value?'生产批':'生产订单'),base=computed(()=>batch.value?'/main-batches':'/production-orders'),ui=computed(()=>batch.value?'/production/batches':'/production/orders'),permission=computed(()=>batch.value?'production:batch':'production:order')
function batchStatus(value:unknown){return ({PENDING_QA:'待 QA 审核',QA_RELEASED:'已 QA 放行'} as Record<string,string>)[String(value)]??display(value)}
const batchStates=computed(()=>schemas.MainBatch?.properties?.status?.enum??[])
const columns=computed(()=>[batch.value?'batchNo':'orderNo','productId','plannedQty','unitId','plannedDate','status'].map(k=>({title:label(k),key:k,dataIndex:k})).concat([{title:'操作',key:'actions',dataIndex:'actions'}]))
async function load(){busy.value=true;try{const result=await api<Page<Record<string,unknown>>>({url:base.value,params:{page:page.value-1,size:20,keyword:keyword.value||undefined,status:status.value||undefined}});rows.value=result.items;total.value=result.total}catch(e){await request.failure(e)}finally{busy.value=false}}
watch(base,()=>{page.value=1;void load()},{immediate:true})
</script>
<!-- UI Template: T1 Query/List; Phase 2A production batch pilot. -->
<template><main class="admin-page master-page" :class="{'t1-query-list':batch,'t1-two-filters':batch}"><header class="admin-page-header"><div v-if="batch"><h1>{{title}}</h1><p v-if="batch">查询生产批状态与计划信息</p></div><h1 v-else>{{title}}</h1><a-button v-if="auth.can(`${permission}:create`)" type="primary" @click="router.push(`${ui}/create`)">新增{{title}}</a-button></header><a-alert v-if="error" type="error" :message="error"/><a-card :title="batch?'查询条件':undefined" :class="batch?'query-card':'form-section'"><form :class="batch?'query-form':'master-form'" @submit.prevent="page=1;load()"><label><span class="form-field-label">关键字</span><input v-model="keyword" class="master-native-input" aria-label="关键字"/></label><label><span class="form-field-label">状态</span><select v-if="batch" v-model="status" class="master-native-input" aria-label="状态"><option value="">全部状态</option><option v-for="state in batchStates" :key="String(state)" :value="String(state)">{{batchStatus(state)}}</option></select><input v-else v-model="status" class="master-native-input" aria-label="状态"/></label><a-space v-if="batch"><a-button @click="keyword='';status='';page=1;load()">重置</a-button><a-button type="primary" html-type="submit" :loading="busy">查询</a-button></a-space><a-space v-else><a-button type="primary" html-type="submit" :loading="busy">查询</a-button><a-button @click="keyword='';status='';page=1;load()">重置</a-button></a-space></form></a-card><a-card :title="batch?'数据列表':undefined" :class="{'result-card':batch}"><div v-if="batch" class="master-toolbar"><span>共 {{total}} 条记录</span></div><a-table :columns="columns" :data-source="rows" row-key="id" :loading="busy" :scroll="{x:850}" :pagination="batch?false:{current:page,total,pageSize:20,showSizeChanger:false}" @change="(p:{current?:number})=>{page=p.current??1;load()}"><template #bodyCell="{column,record}"><a-button v-if="column.key==='actions'" type="link" @click="router.push(`${ui}/${record.id}`)">查看</a-button><strong v-else-if="batch&&column.key==='batchNo'" class="t1-business-id">{{display(record[column.key])}}</strong><span v-else>{{batch&&column.key==='status'?batchStatus(record[column.key]):display(record[column.key])}}</span></template></a-table><div v-if="batch" class="table-footer"><span>第 {{page}} 页</span><a-pagination :current="page" :total="total" :page-size="20" :show-size-changer="false" @change="(p:number)=>{page=p;load()}"/></div></a-card></main></template>
