<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter,onBeforeRouteLeave} from 'vue-router'
import {api} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {useControlledRequest} from '../../api/controlled'
import {productionOperations,productionActions,formSchema} from './productionModel'
import {schemas,commandBody} from '../quality/incomingModel'
import IncomingFormFields from '../quality/IncomingFormFields.vue'
import IncomingFacts from '../quality/IncomingFacts.vue'
import ReadReference from '../master/ReadReference.vue'
import BatchOverview from './BatchOverview.vue'
import {display} from '../quality/incomingModel'
import BatchQualityControls from '../quality/BatchQualityControls.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),request=useControlledRequest(),{busy,error,conflict}=request
const record=ref<Record<string,unknown>|null>(null),form=ref<Record<string,unknown>>({}),selected=ref(''),executions=ref<Record<string,unknown>[]>([]),reservations=ref<Record<string,unknown>[]>([]),saved=ref(false)
const batch=computed(()=>route.meta.resource==='batches'),base=computed(()=>batch.value?'/main-batches':'/production-orders'),ui=computed(()=>batch.value?'/production/batches':'/production/orders'),title=computed(()=>batch.value?'生产批':'生产订单'),create=computed(()=>route.meta.mode==='create'),edit=computed(()=>route.meta.mode==='edit'),permission=computed(()=>batch.value?'production:batch':'production:order')
const operation=computed(()=>selected.value?productionOperations.find(o=>o.path===`${base.value}/{id}/${selected.value}`):undefined)
const schemaName=computed(()=>operation.value?.schema??`${batch.value?'Batch':'Order'}${create.value?'Create':'Edit'}`)
const actions=computed(()=>batch.value?['release','start','complete-production','sub-batches','reservations','submit-qa'].filter(a=>{const op=productionOperations.find(o=>o.path===`${base.value}/{id}/${a}`);return op&&auth.can(op.permission)&&(record.value?.allowedActions instanceof Array?record.value.allowedActions.includes(a==='sub-batches'?'ADD_SUBBATCH':a.split('-').join('_').toUpperCase()):false)}):[])
async function load(){busy.value=true;request.clear();try{if(!create.value){record.value=await api({url:`${base.value}/${route.params.id}`});if(edit.value)form.value={...record.value};if(batch.value){if(auth.can('mes:execution:view'))executions.value=await api({url:`${base.value}/${route.params.id}/execution-units`});if(auth.can('wms:reservation:view'))reservations.value=await api({url:`${base.value}/${route.params.id}/reservations`})}}else{record.value=null;form.value={}}}catch(e){await request.failure(e)}finally{busy.value=false}}
function open(action:string){selected.value=action;form.value={};request.clear()}
async function save(){busy.value=true;try{const body=commandBody(schemas[schemaName.value]!,{...form.value,...(record.value?{versionNo:record.value.versionNo}:{})}) as Record<string,unknown>;if(record.value&&schemas[schemaName.value]!.properties?.versionNo)body.versionNo=record.value.versionNo;const url=create.value?base.value:`${base.value}/${route.params.id}${selected.value?'/'+selected.value:''}`;const result=await request.mutate<Record<string,unknown>>(url,create.value||selected.value?'POST':'PUT',body,record.value?.versionNo as number|undefined);saved.value=true;selected.value='';form.value={};if(create.value||edit.value)await router.replace(`${ui.value}/${result.id}`);else await load()}catch(e){await request.failure(e)}finally{busy.value=false}}
onBeforeRouteLeave(()=>saved.value||!Object.keys(form.value).length||window.confirm('离开将放弃未保存输入，是否继续？'))
watch(()=>route.fullPath,()=>{selected.value='';saved.value=false;void load()},{immediate:true})
</script>
<template><main class="admin-page master-page" :data-ui-template="create||edit?'T2':batch?'T4':'T3'"><header v-if="!batch||create||edit||!record" class="admin-page-header"><div><a-button type="link" @click="router.push({path:ui,query:route.query})">← 返回列表</a-button><h1>{{create?'新增':edit?'编辑':''}}{{title}}</h1><p v-if="record&&!edit">{{record.batchNo??record.orderNo}} <a-tag>{{display(record.status)}}</a-tag></p></div><a-space wrap><a-button v-if="record&&!edit&&auth.can(`${permission}:update`)&&record.status==='DRAFT'" @click="router.push(`${ui}/${record.id}/edit`)">编辑</a-button><a-button v-for="a in actions" :key="a" @click="open(a)">{{productionActions[a]}}</a-button><a-button v-if="batch&&record&&auth.can('qa:batch-review')" @click="router.push(`/qa/batches/${record.id}/review`)">QA 批审</a-button><a-button v-if="batch&&record&&auth.can('trace:view')" @click="router.push({path:'/trace',query:{mainBatchId:String(record.id)}})">完整追溯</a-button></a-space></header><a-alert v-if="error" :message="error" type="error"/><a-alert v-if="conflict" type="warning" message="记录已变化，输入已保留。"><template #action><a-button @click="load">重新加载</a-button></template></a-alert>
<BatchOverview v-if="batch&&record&&!edit" :record="record" :executions="executions" :reservations="reservations"><template #actions><a-space wrap><a-button v-if="record.status==='DRAFT'&&auth.can('production:batch:update')" @click="router.push(`${ui}/${record.id}/edit`)">编辑</a-button><a-button v-for="a in actions" :key="a" @click="open(a)">{{productionActions[a]}}</a-button></a-space></template><template #quality><BatchQualityControls :batch="record" @refresh="load"/></template></BatchOverview>
<a-card v-else-if="record&&!edit" title="生产订单详情" class="form-section"><div class="master-form"><label v-for="[key,title] in [['orderNo','订单编号'],['status','业务状态'],['productId','产品'],['plannedQty','计划数量'],['unitId','单位'],['plannedDate','计划日期']]" :key="key"><span class="form-field-label">{{title}}</span><ReadReference v-if="key==='productId'||key==='unitId'" :field="key!" :value="record[key!]"/><span v-else class="master-read-value">{{display(record[key!])}}</span></label></div><details><summary>更多记录与审计证据</summary><IncomingFacts :value="record"/></details></a-card>
<a-card v-if="create||edit||selected" :title="selected?productionActions[selected]:title+'信息'" class="form-section"><form @submit.prevent="save"><IncomingFormFields v-model="form" :schema="formSchema(schemaName)" :context="record??{}" :disabled="busy"/><a-space style="margin-top:16px"><a-button type="primary" html-type="submit" :loading="busy" :disabled="conflict">提交</a-button><a-button v-if="selected" @click="selected='';form={}">取消</a-button></a-space></form></a-card></main></template>
