import contract from './production-contract.json'
import {schemas,labels,enumLabels,referenceFields,type Schema} from '../quality/incomingModel'
Object.assign(schemas,contract.schemas)
Object.assign(labels,{orderNo:'生产订单号',productId:'产品',plannedQty:'计划数量',plannedDate:'计划日期',batchNo:'生产批号',productionOrderId:'生产订单',subBatchPlan:'子批计划',subBatchNo:'子批号',subBatchSeq:'子批序号',processPackageId:'生产工艺',ebrTemplateVersionId:'eBR模板版本',mainBatchId:'生产批',executionUnitId:'执行单元',executionNo:'执行单元号',operationExecutionId:'工序执行',operationDefId:'工序定义',operationName:'工序名称',operationSeq:'工序顺序',formulaItemId:'处方明细',targetQty:'目标数量',actualQty:'实称数量',scaleEquipmentId:'称量设备',weighingRecordId:'称量记录',chargedQty:'投料数量',reservedQty:'预留数量',weighedBy:'称量人',weighedAt:'称量时间',verifiedBy:'复核人',verifiedAt:'复核时间',chargedBy:'投料人',chargedAt:'投料时间',usageRole:'设备用途',parameterDefId:'参数定义',sourceMode:'采集方式',rawValue:'原始数值',textValue:'文本值',capturedAt:'采集时间',sourceMessageId:'设备消息',actualStartAt:'实际开始时间',actualEndAt:'实际结束时间',processSnapshotId:'冻结工艺快照',productionMode:'生产模式',nodes:'追溯记录',edges:'追溯关系',from:'来源',to:'目标',type:'类型',label:'名称',revision:'记录版本'})
Object.assign(enumLabels,{READY:'就绪',PAUSED:'已暂停',CONFIRMED:'已确认',VERIFIED:'已复核',REVERSED:'已冲销',ALLOCATED:'已分配',IN_PRODUCTION:'生产中',PRODUCTION_COMPLETED:'生产完成',MANUAL:'人工采集',DEVICE:'设备采集'})
export const productionOperations=contract.operations
export function formSchema(name:string):Schema{const schema=schemas[name]!;return {...schema,properties:Object.fromEntries(Object.entries(schema.properties??{}).filter(([key])=>!['versionNo','executionUnitId',...(name==='ParameterRecord'?['sourceMode','capturedAt','equipmentId','sourceMessageId']:[])].includes(key)))}}
export const productionActions:Record<string,string>={release:'下达生产批',start:'开始',pause:'暂停',resume:'恢复',complete:'完成工序','complete-production':'完成生产','submit-qa':'提交QA','sub-batches':'新增子批',reservations:'预留物料','equipment-usages':'绑定设备','parameter-values':'记录参数',verify:'独立复核',reverse:'冲销投料'}

Object.assign(labels,{weighingPolicy:"冻结称量策略",required:"必须称量",precision:"称量精度",tolerancePct:"允差百分比",policyVersion:"策略版本",configurationHash:"配置摘要",processSnapshot:"冻结工艺快照",snapshot:"快照内容",materials:"物料快照",process:"工艺",ebr:"电子批记录",baseUnitId:"基本单位",organizationId:"组织"})
for(const field of ["productId","productionOrderId","processPackageId","ebrTemplateVersionId","operationExecutionId","formulaItemId","scaleEquipmentId","equipmentId","weighingRecordId","parameterDefId"])referenceFields.add(field)

Object.assign(labels,{signatureRequired:"要求电子签名",independentVerificationRequired:"要求独立复核",scaleEquipmentTypes:"允许的称量设备类型",equipmentEvidence:"设备使用证据",gateEvidence:"业务校验依据",qualifications:"人员资格证据",checkedAt:"校验时间",actorId:"操作人",validFrom:"生效日期",validTo:"有效截止日期",calibrationDueDate:"校准有效期",equipmentType:"设备类型",code:"编码",userId:"人员",policy:"验证策略",canonicalRecord:"签名记录快照",definitionHash:"定义摘要",signatureId:"电子签名编号",returns:"退料记录",returnedBy:"退料人",returnedAt:"退料时间",issueItemId:"出库明细",issueId:"出库单",reason:"操作原因",processSnapshotId:"工艺快照编号",startedAt:"开始时间",completedAt:"完成时间"})
