<script setup lang="ts">
import {computed,ref,onMounted} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api} from '../../api/http'
import {useControlledRequest} from '../../api/controlled'
import './productionModel'
import IncomingFacts from '../quality/IncomingFacts.vue'
import IncomingReferencePicker from '../quality/IncomingReferencePicker.vue'
import {useAuthStore} from '../../stores/auth'
import {display} from '../quality/incomingModel'
const auth=useAuthStore(),selected=ref<Record<string,unknown>|null>(null),keyword=ref(''),nodeType=ref('')
const route=useRoute(),router=useRouter(),request=useControlledRequest(),{busy,error}=request,mainBatchId=ref(String(route.query.mainBatchId??'')),materialLotId=ref(String(route.query.materialLotId??'')),result=ref<Record<string,unknown>|null>(null)
async function search(){busy.value=true;try{if(Boolean(mainBatchId.value.trim())===Boolean(materialLotId.value.trim()))throw Error("请选择生产批或物料批中的一个进行追溯");result.value=await api({url:'/trace',params:{mainBatchId:mainBatchId.value||undefined,materialLotId:materialLotId.value||undefined}})}catch(e){await request.failure(e)}finally{busy.value=false}}
const nodes=computed(()=>(result.value?.nodes??[]) as Record<string,unknown>[])
function existingDestination(n:Record<string,unknown>){if(n.type==='QC_SPECIFICATION_VERSION')return `/quality/specification-versions/${n.id}/edit`;const paths:Record<string,string>={MAIN_BATCH:'/production/batches',EXECUTION_UNIT:'/mes/execution',MATERIAL_LOT:'/wms/material-lots',RECEIPT:'/wms/receipts',INSPECTION_REQUEST:'/quality/inspection-requests',SAMPLING_TASK:'/quality/sampling-tasks',SAMPLE:'/quality/samples',INSPECTION_TASK:'/quality/inspection-tasks',REPORT:'/quality/inspection-reports',INVESTIGATION:'/deviations'};return paths[String(n.type)]?`${paths[String(n.type)]}/${n.id}`:undefined}
const typeNames:Record<string,string>={MAIN_BATCH:'生产批',EXECUTION_UNIT:'执行单元',MATERIAL_LOT:'物料批次',RECEIPT:'收货记录',RECEIPT_ITEM:'收货明细',INSPECTION_REQUEST:'请验单',SAMPLING_TASK:'取样记录',SAMPLING_DETAIL:'取样明细',SAMPLE:'样品',INSPECTION_TASK:'检验记录',INSPECTION_ITEM:'检验项目',TEST_EXECUTION:'检验执行',RESULT_REVISION:'结果修订',REPORT:'检验报告',RELEASE_DECISION:'物料放行',INVESTIGATION:'质量调查',OPERATION:'工序',CHARGE:'投料记录',WEIGHING:'称量记录',SIGNATURE:'电子签名'}
const permissions:Record<string,string>={MAIN_BATCH:'production:batch:view',EXECUTION_UNIT:'mes:operation:view',MATERIAL_LOT:'wms:inventory:view',RECEIPT:'wms:receipt:view',INSPECTION_REQUEST:'qms:inspection-request:view',SAMPLING_TASK:'qms:sampling:view',SAMPLE:'qms:test:view',INSPECTION_TASK:'qms:test:view',REPORT:'qms:report:view',INVESTIGATION:'qms:deviation:view',QC_SPECIFICATION_VERSION:'qms:specification:view'}
function destination(n:Record<string,unknown>){return auth.can(permissions[String(n.type)]??'')?existingDestination(n):undefined}
interface Edge {sourceType:string;sourceId:string;targetType:string;targetId:string;relation:string}
const edges=computed(()=>(result.value?.edges??[]) as Edge[])
const visibleNodes=computed(()=>nodes.value.filter(n=>(!nodeType.value||n.type===nodeType.value)&&(!keyword.value||String(n.label).includes(keyword.value)||String(n.id).includes(keyword.value))))
function key(n:Record<string,unknown>){return `${n.type}:${n.id}`}
const positions=computed(()=>new Map(visibleNodes.value.map((n,i)=>[key(n),{x:(i%3)*270+16,y:Math.floor(i/3)*150+16}])))
const lines=computed(()=>edges.value.flatMap(e=>{const a=positions.value.get(e.sourceType+':'+e.sourceId),b=positions.value.get(e.targetType+':'+e.targetId);return a&&b?[{...e,a,b}]:[]}))
const graphHeight=computed(()=>Math.max(170,Math.ceil(visibleNodes.value.length/3)*150+16))
const relations=computed(()=>[...new Set(edges.value.map(e=>e.relation))])
const selectedEdges=computed(()=>edges.value.filter(e=>selected.value&&(e.sourceType+':'+e.sourceId===key(selected.value)||e.targetType+':'+e.targetId===key(selected.value))))
function description(n:Record<string,unknown>){const type=String(n.type);return String(n.label??'').replace(type,typeNames[type]??type)}
onMounted(()=>{if(mainBatchId.value||materialLotId.value)void search()})
</script>
<!-- Specialized read-only lineage explorer; returned nodes and edges are the only source. -->
<template><main class="admin-page master-page" data-ui-template="Specialized"><header class="admin-page-header"><div><h1>完整追溯</h1><p>生产与来料质量的既有记录及关联关系</p></div><a-button v-if="materialLotId&&auth.can('wms:inventory:view')" @click="router.push(`/wms/material-lots/${materialLotId}`)">物料批详情</a-button></header><a-alert v-if="error" type="error" :message="error"/>
<a-card class="query-card"><form class="query-form" @submit.prevent="search"><label><span class="form-field-label">生产批</span><IncomingReferencePicker v-if="auth.can('production:batch:view')" v-model="mainBatchId" field="mainBatchId" :context="{}"/><input v-else v-model="mainBatchId" class="master-native-input" aria-label="生产批"/></label><label><span class="form-field-label">物料批次</span><IncomingReferencePicker v-if="auth.can('wms:inventory:view')" v-model="materialLotId" field="materialLotId" :context="{}"/><input v-else v-model="materialLotId" class="master-native-input" aria-label="物料批次"/></label><a-space><a-button type="primary" html-type="submit" :loading="busy">查询追溯</a-button></a-space></form></a-card>
<a-card v-if="result" title="实际业务记录与关系"><div class="trace-filters"><label>记录类型<select v-model="nodeType" class="master-native-input"><option value="">全部</option><option v-for="type in [...new Set(nodes.map(n=>String(n.type)))]" :key="type" :value="type">{{typeNames[type]??type}}</option></select></label><label>记录编号或名称<input v-model="keyword" class="master-native-input"/></label><span class="muted">{{visibleNodes.length}} 个记录 · {{lines.length}} 条关系</span></div>
<div class="trace-scroll"><div class="trace-canvas" :style="{height:graphHeight+'px'}"><svg width="810" :height="graphHeight" aria-label="业务关联图"><defs><marker id="trace-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8" fill="var(--mes-ui-primary)"/></marker></defs><path v-for="(line,i) in lines" :key="i" :d="`M${line.a.x+120},${line.a.y+105} C${line.a.x+120},${line.a.y+135} ${line.b.x+120},${line.b.y-25} ${line.b.x+120},${line.b.y}`" fill="none" stroke="var(--mes-ui-primary)" stroke-width="1.5" marker-end="url(#trace-arrow)"/></svg><button v-for="node in visibleNodes" :key="key(node)" :aria-label="String(node.label)" class="trace-node" :style="{left:positions.get(key(node))!.x+'px',top:positions.get(key(node))!.y+'px'}" @click="selected=node"><small>{{typeNames[String(node.type)]??node.type}}</small><strong>{{description(node)}}</strong><span>{{display(node.status)}}</span></button></div></div><p v-if="!nodes.length" class="muted">暂无关联记录</p><div class="trace-legend"><strong>关系图例</strong><span v-for="relation in relations" :key="relation">→ {{relation}}</span></div><details><summary>完整追溯证据</summary><IncomingFacts :value="result"/></details></a-card>
<a-drawer :open="!!selected" title="来源记录详情" :width="480" @close="selected=null"><template v-if="selected"><h3>{{description(selected)}}</h3><dl><dt>记录类型</dt><dd>{{typeNames[String(selected.type)]??selected.type}}</dd><dt>业务状态</dt><dd>{{display(selected.status)}}</dd></dl><a-button v-if="destination(selected)" type="primary" @click="router.push(destination(selected)!)">查看来源记录</a-button><p v-else class="muted">暂无可访问的来源详情入口。</p><h3>关联关系</h3><p v-for="(edge,i) in selectedEdges" :key="i">{{typeNames[edge.sourceType]??edge.sourceType}} → {{typeNames[edge.targetType]??edge.targetType}} · {{edge.relation}}</p><details><summary>来源引用与版本证据</summary><IncomingFacts :value="selected"/></details></template></a-drawer></main></template>
<style scoped>.trace-filters,.trace-legend{display:flex;gap:16px;align-items:center;flex-wrap:wrap;margin-bottom:16px}.trace-filters label{display:flex;gap:10px;align-items:center}.trace-scroll{overflow:auto;max-height:650px;border:1px solid var(--mes-ui-border);border-radius:8px;background:var(--mes-ui-background)}.trace-canvas{position:relative;min-width:810px}.trace-canvas svg{position:absolute;inset:0}.trace-node{position:absolute;width:240px;height:105px;border:1px solid var(--mes-ui-border);border-radius:8px;background:white;text-align:left;padding:12px;cursor:pointer;color:var(--mes-ui-text)}.trace-node:hover,.trace-node:focus-visible{border-color:var(--mes-ui-primary);outline:2px solid #dbeafe}.trace-node strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px;margin:8px 0}.trace-node small,.trace-node span{color:var(--mes-ui-secondary);font-size:12px}.trace-legend{margin:16px 0;font-size:12px;overflow-wrap:anywhere}@media(max-width:767px){.trace-filters label{width:100%}.trace-filters input,.trace-filters select{min-width:0;flex:1}.trace-node{font-size:13px}}dt{color:var(--mes-ui-secondary)}dd{margin:4px 0 16px;overflow-wrap:anywhere}</style>
