package com.hospital.mes.incoming;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.hospital.mes.audit.application.*;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.qc.application.*;
import com.hospital.mes.qc.domain.*;
import com.hospital.mes.qms.application.*;
import com.hospital.mes.wms.application.WmsService;
import com.hospital.mes.wms.domain.WmsCommands.*;
import java.util.*;
import java.time.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
/** Real WMS/QC/QMS/signature database integration. Unique fixtures, rollback only; never edits seeds. */
@SpringBootTest(properties={"mes.qualification.required-codes.sample-execute=IQ_INCOMING_IT","mes.qualification.required-codes.test-execute=IQ_INCOMING_IT","mes.qualification.required-codes.test-review=IQ_INCOMING_IT","mes.qualification.required-codes.qa-release=IQ_INCOMING_IT"})
@ActiveProfiles("ci") @Transactional
public abstract class IncomingQualityFixture {

 @Autowired protected IncomingQualityService service;@Autowired protected IncomingQualityQueryService queries;@Autowired protected QcSpecificationService qc;@Autowired protected WmsService wms;@Autowired protected UnitService units;@Autowired protected MaterialService materials;@Autowired protected SupplierService suppliers;@Autowired protected MaterialSupplierService links;@Autowired protected ObjectMapper json;@Autowired protected JdbcTemplate jdbc;@Autowired protected SignatureTransactionService verifier;@Autowired protected PlatformTransactionManager transactions;
 @MockitoBean protected CurrentPlatformContextResolver contexts;@MockitoBean protected ReauthenticationPort reauth;@MockitoSpyBean protected AuditApplicationService audit;
 protected String suffix,unit,material,lot,version;protected long author,approver,analyst,reviewer,qa;protected Set<String> permissions;
 @BeforeEach protected void setup(){suffix=UUID.randomUUID().toString().replace("-","").substring(0,12);permissions=new HashSet<>();for(String prefix:List.of("master:uom:","master:material:","master:supplier:","wms:inventory:","wms:receipt:","qms:specification:","qms:inspection-request:","qms:sampling:","qms:test:","qms:report:","qms:deviation:","qa:material-release:"))for(String action:List.of("view","create","update","edit","confirm","approve","retire","submit","accept","assign","execute","complete","approve-plan","correct","review","decide","investigate","close"))permissions.add(prefix+action);permissions.addAll(Set.of("ebr:sign","audit:view"));author=actor("a");approver=actor("p");analyst=actor("t");reviewer=actor("r");qa=actor("q");as(author);when(reauth.consume(anyString(),any())).thenReturn(new ConsumedReauthentication(Instant.now(),"PASSWORD"));
 unit=units.create(new UnitCommands.Create("IU"+suffix,"Incoming kg","MASS",6),key()).path("id").asText();material=materials.create(json.convertValue(Map.of("materialCode","IM"+suffix,"materialName","Incoming salt","materialType","RAW","baseUnitId",unit,"lotControlled",true),MaterialCommands.Create.class),key()).path("id").asText();var supplier=suppliers.create(new SupplierCommands.Create("IS"+suffix,"Incoming source",LocalDate.now(ZoneOffset.UTC).plusYears(1)),key());String supplierId=supplier.path("id").asText();links.assign(material,new SupplierCommands.Assign(0L,"Approved supplier",List.of(new SupplierCommands.Relationship(supplierId,true,true,null))),null,key());var wh=wms.maintenance("Warehouse",null,new WarehouseCreate("IW"+suffix,"Incoming","RAW"),null,key());String whId=wh.path("id").asText();String location=wms.maintenance("Location",null,new LocationCreate(whId,"IL"+suffix,"Incoming area"),null,key()).path("id").asText();var item=new ReceiptItemInput(material,"ILOT"+suffix,"SUP"+suffix,null,LocalDate.now(ZoneOffset.UTC).minusDays(1).toString(),LocalDate.now(ZoneOffset.UTC).plusYears(1).toString(),null,"10",unit,null,2L,location,null,true,true,true,true,true);var receipt=wms.createReceipt(new ReceiptCreate("IR"+suffix,supplierId,null,null,whId,true,List.of(item)),key(),true);lot=receipt.path("items").get(0).path("materialLotId").asText();
 var spec=qc.create(new QcCommands.CreateSpecification(material,"IQ"+suffix,"Incoming assay","Standard"),key());var draft=qc.createVersion(spec.id(),new QcCommands.CreateVersion(1,List.of(new QcCommands.Item("ASSAY","Assay",true,"NUMERIC","1","3",unit,null,"METHOD","1")),"Define"),key());as(approver);version=qc.approveVersion(draft.id(),new QcCommands.SignVersion(0L,"Approve","token"),"\"0\"",key()).id();as(analyst);
 }
 protected long actor(String code){String name="iq_"+code+suffix;jdbc.update("INSERT INTO sys_user(login_name,login_name_normalized,display_name,password_hash,enabled,must_change_password) VALUES(?,?,?,?,TRUE,FALSE)",name,name,"Incoming rollback actor","test-only");long id=jdbc.queryForObject("SELECT id FROM sys_user WHERE login_name_normalized=?",Long.class,name);jdbc.update("INSERT INTO md_qualification(org_id,created_by,updated_by,user_id,qualification_code,valid_from,valid_to,status) VALUES(1,?,?,?,'IQ_INCOMING_IT',?,?,'ACTIVE')",id,id,id,LocalDate.now(ZoneOffset.UTC).minusDays(1),LocalDate.now(ZoneOffset.UTC).plusYears(1));return id;}
 protected void as(long actor){when(contexts.current()).thenReturn(new CurrentPlatformContext(1,actor,Set.of("INCOMING_TEST"),permissions,"incoming-session","incoming-"+suffix));}
 protected String key(){return UUID.randomUUID().toString();}protected ObjectNode body(Object...pairs){var n=json.createObjectNode();for(int i=0;i<pairs.length;i+=2)n.set((String)pairs[i],json.valueToTree(pairs[i+1]));return n;}protected String id(JsonNode n){return n.path("id").asText();}protected String token(JsonNode n){return "\""+n.path("versionNo").asLong()+"\"";}
 protected JsonNode get(String table,String id){return service.get(table,table.equals("qms_inspection_task")?"qms:test:view":"qms:sampling:view",id);}
 protected JsonNode request(){var n=service.createRequest(body("materialLotId",lot,"qcSpecificationVersionId",version,"requestType","INITIAL","reason","Incoming inspection","requestedQuantity","10","requestedUnitId",unit,"requestedPackageCount",2,"requestedDate",LocalDate.now(ZoneOffset.UTC).toString(),"priority","NORMAL"),key());n=service.requestAction(id(n),"submit",body("reason","Submit"),token(n),key());return service.requestAction(id(n),"accept",body("reason","QC accepted"),token(n),key());}
 protected JsonNode sample(JsonNode request){var task=service.createSampling(body("inspectionRequestId",id(request),"inspectionRequestItemId",request.path("items").get(0).path("id").asText(),"samplingPlan","One container, controlled sample","requiredPackageCount",1,"reason","Plan"),key());task=service.samplingAction(id(task),"assign",body("assignedTo",Long.toString(analyst),"reason","Assign"),token(task),key());task=service.samplingAction(id(task),"start",body("reason","Start"),token(task),key());task=service.samplingAction(id(task),"details",body("containerNo","PK1","sampleQuantity","1","unitId",unit,"sampledAt",Instant.now().minusSeconds(5).toString(),"packageResealed",true,"samples",List.of(Map.of("sampleType","TEST_SAMPLE","quantity","0.8"),Map.of("sampleType","RETENTION_SAMPLE","quantity","0.2")),"reason","Sampled"),token(task),key());task=service.samplingAction(id(task),"complete",body("reason","Complete","reauthToken","token"),token(task),key());assertThat(task.path("details").get(0).path("samples")).hasSize(2);var sample=task.path("details").get(0).path("samples").get(0);return service.sampleAction(id(sample),"receive",body("receivedAt",Instant.now().toString(),"storageLocation","QC store","reason","Received"),token(sample),key());}
 protected JsonNode task(JsonNode request,JsonNode sample){var t=service.createTask(body("inspectionRequestId",id(request),"sampleId",id(sample),"reason","Analyze"),key());t=service.taskAction(id(t),"assign",body("assignedTo",Long.toString(analyst),"reason","Assign"),token(t),key());return service.taskAction(id(t),"start",body("reason","Start"),token(t),key());}
 protected JsonNode execution(JsonNode task){return service.execution(task.path("items").get(0).path("id").asText(),false,body("rawData",Map.of("readout","original"),"calculationInput",Map.of(),"startedAt",Instant.now().minusSeconds(2).toString(),"completedAt",Instant.now().minusSeconds(1).toString(),"performedBy",Long.toString(analyst),"reason","Execute"),token(task),key());}
 protected JsonNode result(JsonNode task,JsonNode execution,String numeric,String conclusion){var current=get("qms_inspection_task",id(task));return service.result(task.path("items").get(0).path("id").asText(),false,body("testExecutionId",id(execution),"resultNumeric",numeric,"resultUnitId",unit,"resultConclusion",conclusion,"reauthToken","token"),token(current),key());}
 protected JsonNode review(JsonNode task,JsonNode result){as(analyst);var t=get("qms_inspection_task",id(task));t=service.taskAction(id(t),"submit-review",body("reason","Submit"),token(t),key());as(reviewer);return service.taskAction(id(t),"review",body("resultRevisionIds",List.of(id(result)),"reauthToken","token","reason","Review"),token(t),key());}
 protected JsonNode report(JsonNode request){as(analyst);var report=service.createReport(body("inspectionRequestId",id(request),"reason","Aggregate"),key());as(reviewer);report=service.reportAction(id(report),"review",body("reason","Review"),token(report),key());as(approver);return service.reportAction(id(report),"approve",body("reason","Approve","reauthToken","token"),token(report),key());}
}
