package com.hospital.mes.masterdata.application;
import com.fasterxml.jackson.databind.JsonNode;import com.hospital.mes.masterdata.infrastructure.*;import com.hospital.mes.masterdata.domain.*;import com.hospital.mes.common.exception.*;
import java.util.*;import java.time.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
@Service @ConditionalOnProperty(prefix="spring.datasource",name="url")
public class SupplierService {
 private final SupplierStore store;private final MasterMutation mutations;
 public SupplierService(SupplierStore store,MasterMutation mutations){this.store=store;this.mutations=mutations;}
 public ScopedStore.PageData<JsonNode> list(int page,int size,String keyword,Map<String,String> filters){var c=mutations.context("master:supplier:view");var p=store.list(c.organizationId(),page,size,keyword,filters);return new ScopedStore.PageData<>(p.items().stream().map(mutations::view).toList(),p.total(),page,size);}
 public JsonNode get(String id){var c=mutations.context("master:supplier:view");return mutations.view(store.get(c.organizationId(),MasterMutation.id(id)));}
 @Transactional(isolation=org.springframework.transaction.annotation.Isolation.READ_COMMITTED) public JsonNode create(SupplierCommands.Create r,String key){var c=mutations.context("master:supplier:create");return mutations.execute(c,"Supplier:CREATE",key,r,()->{var e=new SupplierEntity();e.setSupplierCode(MasterRules.text(r.supplierCode(),64));e.setSupplierName(MasterRules.text(r.supplierName(),200));e.setValidTo(r.validTo());e.setQualificationStatus("APPROVED");store.insert(e,c.organizationId(),c.actorId());return e;});}
 @Transactional(isolation=org.springframework.transaction.annotation.Isolation.READ_COMMITTED) public JsonNode command(String id,SupplierCommands.Update r,String header,String key){var c=mutations.context("master:supplier:update");long version=0L;String reason=MasterRules.text(r.reason()==null||r.reason().isBlank()?"基础资料维护（系统记录）":r.reason(),1000);return mutations.execute(c,"Supplier:"+id,key,Map.of("id",id,"version",version,"body",r),()->{var e=store.lock(c.organizationId(),MasterMutation.id(id));var before=new SupplierEntity();org.springframework.beans.BeanUtils.copyProperties(e,before);if("INACTIVE".equals(e.getQualificationStatus()))throw new StateTransitionException("INVALID_STATE","Inactive supplier cannot change");switch(MasterRules.text(r.action(),40)){case "UPDATE" -> {e.setSupplierName(MasterRules.text(r.supplierName(),200));e.setValidTo(r.validTo());e.setQualificationStatus("APPROVED");}case "DISABLE" -> e.setQualificationStatus("INACTIVE");default -> throw new IllegalArgumentException("Unknown action");}store.update(e,version,c.actorId(),List.of("supplierName","qualificationStatus","validTo"));return e;});}
}
