package com.hospital.mes.qms.application;
import static com.hospital.mes.production.application.ProductionInput.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.audit.application.*;
import com.hospital.mes.audit.signature.SignatureMeaning;
import com.hospital.mes.common.exception.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.masterdata.infrastructure.ScopedEntity;
import com.hospital.mes.production.application.ProductionQueryService;
import com.hospital.mes.qms.infrastructure.*;
import java.math.*;
import java.time.*;
import java.util.*;
import org.springframework.transaction.annotation.*;

/** Finished quality documents reference existing production samples and immutable original results. */
@org.springframework.stereotype.Service
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class FinishedInspectionService {
 private final FinishedInspectionRequestMapper requestsMapper;
 private final FinishedSamplingRecordMapper samplingMapper;
 private final FinishedInspectionReportMapper reportsMapper;
 private final FinishedReportReviewMapper reviewsMapper;
 private final ScopedStore<FinishedInspectionRequestEntity> requests;
 private final ScopedStore<FinishedSamplingRecordEntity> sampling;
 private final ScopedStore<FinishedInspectionReportEntity> reports;
 private final ScopedStore<FinishedReportReviewEntity> reviews;
 private final ProductionQueryService batches;
 private final ProductionQualityService quality;
 private final FinishedWarehousePort warehouse;
 private final MasterQueryService units;
 private final MasterMutation mutations;
 private final SignedRecordSupport signing;
 private final CurrentPlatformContextResolver contexts;
 private final ObjectMapper json;
 private final IncomingStore raw;private final IncomingActorPort actors;
 public FinishedInspectionService(FinishedInspectionRequestMapper r,FinishedSamplingRecordMapper s,FinishedInspectionReportMapper p,FinishedReportReviewMapper v,ProductionQueryService batches,ProductionQualityService quality,FinishedWarehousePort warehouse,MasterQueryService units,MasterMutation mutations,SignedRecordSupport signing,CurrentPlatformContextResolver contexts,ObjectMapper json,IncomingStore raw,IncomingActorPort actors){
  this.requestsMapper=r;this.samplingMapper=s;this.reportsMapper=p;this.reviewsMapper=v;this.requests=new ScopedStore<>(r,List.of("inspection_request_no"),Map.of("status","status","mainBatchId","main_batch_id"));this.sampling=new ScopedStore<>(s,List.of("sampling_no"),Map.of("inspectionRequestId","inspection_request_id"));this.reports=new ScopedStore<>(p,List.of("report_no"),Map.of("status","status","inspectionRequestId","inspection_request_id"));this.reviews=new ScopedStore<>(v,List.of(),Map.of());this.batches=batches;this.quality=quality;this.warehouse=warehouse;this.units=units;this.mutations=mutations;this.signing=signing;this.contexts=contexts;this.json=json;this.raw=raw;this.actors=actors;
 }
 private static LocalDateTime now(){return LocalDateTime.now(ZoneOffset.UTC).truncatedTo(java.time.temporal.ChronoUnit.MILLIS);}
 private static void gate(boolean ok,String code){if(!ok)throw new ComplianceException(code,code);}
 private static void version(long actual,long expected){if(actual!=expected)throw new ResourceConflictException("VERSION_CONFLICT","Record changed");}
 private static long expected(JsonNode body,String header){if(header==null||!header.matches("\"(?:0|[1-9][0-9]*)\""))throw new IllegalArgumentException("Exact quoted If-Match required");return SignedRecordSupport.expected(body,header);}
 private static void independent(long actor,long source){gate(actor!=source,"FINISHED_QC_INDEPENDENT_REQUIRED");}
 private JsonNode read(String value){try{return json.readTree(value);}catch(java.io.IOException e){throw new IllegalStateException("Corrupt frozen finished evidence",e);}}
 private void mutable(long org,long batch){gate(Set.of("PRODUCTION_COMPLETED","PENDING_QA").contains(batches.lockBatch(org,batch).status()),"FINISHED_QUALITY_STATE_CONFLICT");}
 @Transactional public JsonNode createRequest(JsonNode body,String key){return create(body,key,false);}
 @Transactional(propagation=Propagation.MANDATORY) public JsonNode createInboundDraft(JsonNode body,String key){return create(body,key,true);}
 private JsonNode create(JsonNode body,String key,boolean earlyDraft){fields(body,"inspectionRequestNo","inboundRequestId","reason");var c=mutations.context("qms:finished-request:create");return mutations.execute(c,"FINISHED_INSPECTION_CREATE",key,body,()->{
  var receipt=warehouse.inbound(c.organizationId(),id(body,"inboundRequestId"));long batch=receipt.path("mainBatchId").asLong();var root=batches.lockBatch(c.organizationId(),batch);gate("PRODUCTION_COMPLETED".equals(root.status()),"FINISHED_PRODUCTION_REQUIRED");var current=earlyDraft?receipt:warehouse.confirmed(c.organizationId(),batch);if(earlyDraft)gate(Set.of("DRAFT","SUBMITTED","CONFIRMED").contains(current.path("status").asText()),"FINISHED_INBOUND_SOURCE_INACTIVE");gate(current.path("id").asLong()==id(body,"inboundRequestId"),"FINISHED_RECEIPT_MISMATCH");var plan=root.snapshot().path("qualityPlan");gate("APPROVED".equals(plan.path("status").asText())&&signing.valid(c.organizationId(),plan.path("signatureId").asLong()),"QUALITY_PLAN_REQUIRED");var row=new FinishedInspectionRequestEntity();row.setInspectionRequestNo(text(body,"inspectionRequestNo",80));row.setMainBatchId(batch);row.setMaterialLotId(current.path("materialLotId").asLong());row.setInboundRequestId(current.path("id").asLong());row.setQcSpecificationVersionId(plan.path("qcSpecificationVersionId").asLong());row.setSpecificationSnapshotJson(plan.toString());row.setSpecificationDigest(mutations.digest(plan));row.setStatus("DRAFT");row.setReason(text(body,"reason",1000));requests.insert(row,c.organizationId(),c.actorId());mutations.auditSnapshot(c,"FINISHED_INSPECTION_CREATE","FinishedInspectionRequest",row.getId(),null,view(row),row.getReason(),key);return row;
 },x->view((FinishedInspectionRequestEntity)x),201);}
 @Transactional public JsonNode requestAction(String target,String action,JsonNode body,String header,String key){if(!Set.of("submit","accept").contains(action))throw new IllegalArgumentException("Unknown finished request action");fields(body,"versionNo","reason");var c=mutations.context("qms:finished-request:"+action);long expected=expected(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"FINISHED_INSPECTION_"+action+":"+target,key,Map.of("target",target,"body",body),()->{
  var found=requests.get(c.organizationId(),MasterMutation.id(target));mutable(c.organizationId(),found.getMainBatchId());var row=requests.lock(c.organizationId(),found.getId());version(row.getVersionNo(),expected);warehouse.confirmed(c.organizationId(),row.getMainBatchId());var before=view(row);var changed=new ArrayList<String>(List.of("status","reason"));row.setReason(reason);
  if(action.equals("submit")){gate("DRAFT".equals(row.getStatus()),"FINISHED_REQUEST_STATE_CONFLICT");row.setStatus("SUBMITTED");row.setSubmittedBy(c.actorId());row.setSubmittedAt(now());changed.addAll(List.of("submittedBy","submittedAt"));}else{gate("SUBMITTED".equals(row.getStatus()),"FINISHED_REQUEST_STATE_CONFLICT");row.setStatus("ACCEPTED");row.setAcceptedBy(c.actorId());row.setAcceptedAt(now());changed.addAll(List.of("acceptedBy","acceptedAt"));}requests.update(row,expected,c.actorId(),changed);mutations.auditSnapshot(c,"FINISHED_INSPECTION_"+action.toUpperCase(Locale.ROOT),"FinishedInspectionRequest",row.getId(),before,view(row),reason,key);return row;
 },x->view((FinishedInspectionRequestEntity)x),200);}
 private BigDecimal convert(long org,long lotMaterial,BigDecimal amount,long from,long to){var c=units.convert(org,from,to,lotMaterial,amount);var actual=amount.multiply(new BigDecimal(c.factor()));gate(actual.compareTo(new BigDecimal(c.convertedValue()))==0,"QUANTITY_PRECISION_LOSS");return actual;}
 @Transactional public JsonNode sample(String target,JsonNode body,String header,String key){fields(body,"versionNo","samplingNo","sampleNo","sampleType","samplingLocation","quantity","unitId","samplingMethod","reason","signature");var c=mutations.context("qms:finished-sampling:create");long expected=expected(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"FINISHED_SAMPLING:"+target,key,Map.of("target",target,"body",body),()->{
  var found=requests.get(c.organizationId(),MasterMutation.id(target));gate("PRODUCTION_COMPLETED".equals(batches.lockBatch(c.organizationId(),found.getMainBatchId()).status()),"FINISHED_PRODUCTION_REQUIRED");var request=requests.lock(c.organizationId(),found.getId());version(request.getVersionNo(),expected);gate("ACCEPTED".equals(request.getStatus()),"FINISHED_QC_ACCEPTANCE_REQUIRED");var receipt=warehouse.confirmed(c.organizationId(),request.getMainBatchId());BigDecimal quantity=com.hospital.mes.qms.domain.IncomingRules.quantity(text(body,"quantity",30));long unit=id(body,"unitId"),base=receipt.path("unitId").asLong(),material=read(request.getSpecificationSnapshotJson()).path("finishedMaterialId").asLong();BigDecimal total=convert(c.organizationId(),material,quantity,unit,base);
  for(var prior:samplingRows(c.organizationId(),request.getId()))total=total.add(convert(c.organizationId(),material,prior.getQuantity(),prior.getUnitId(),base));gate(total.compareTo(new BigDecimal(receipt.path("quantity").asText()))<=0,"FINISHED_SAMPLE_QUANTITY_EXCEEDED");
  actors.requireQualified(c.organizationId(),c.actorId(),"sample-execute");var sample=quality.createFinishedSample(c,request.getMainBatchId(),request.getMaterialLotId(),text(body,"sampleNo",80),text(body,"sampleType",30),quantity,unit,"FinishedInspectionRequest:"+request.getId());var row=new FinishedSamplingRecordEntity();row.setInspectionRequestId(request.getId());row.setSampleId(sample.getId());row.setMaterialLotId(request.getMaterialLotId());row.setSamplingNo(text(body,"samplingNo",80));row.setSamplingLocation(text(body,"samplingLocation",200));row.setSamplingMethod(text(body,"samplingMethod",1000));row.setQuantity(quantity);row.setUnitId(unit);row.setSampledBy(c.actorId());row.setSampledAt(now());row.setReason(reason);var signature=signing.sign(c,"FINISHED_SAMPLING",request.getId()+":"+expected,expected,SignatureMeaning.VERIFY,row,body.get("signature"),key,List.of("FinishedInspectionRequest:"+request.getId(),"Sample:"+sample.getId(),"MaterialLot:"+row.getMaterialLotId()));row.setSignatureId(signature.id());row.setSignatureEvidenceJson(signature.envelope());sampling.insert(row,c.organizationId(),c.actorId());requests.update(request,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"FINISHED_SAMPLING","FinishedSamplingRecord",row.getId(),null,view(row),reason,key);mutations.auditSnapshot(c,"FINISHED_SAMPLE_CREATED","Sample",sample.getId(),null,raw.view(sample),reason,key);return row;
 },x->view((FinishedSamplingRecordEntity)x),201);}
 private List<FinishedSamplingRecordEntity> samplingRows(long org,long request){return samplingMapper.selectList(new QueryWrapper<FinishedSamplingRecordEntity>().eq("org_id",org).eq("inspection_request_id",request).orderByAsc("id").last("LOCK IN SHARE MODE"));}
 private List<FinishedInspectionReportEntity> reportRows(long org,long request){return reportsMapper.selectList(new QueryWrapper<FinishedInspectionReportEntity>().eq("org_id",org).eq("inspection_request_id",request).orderByAsc("generation_no").last("LOCK IN SHARE MODE"));}
 private JsonNode aggregate(FinishedInspectionRequestEntity request){
  long org=request.getOrgId();var receipt=warehouse.confirmed(org,request.getMainBatchId());var records=samplingRows(org,request.getId());gate(!records.isEmpty(),"FINISHED_SAMPLING_REQUIRED");for(var sampling:records)gate(signing.valid(org,sampling.getSignatureId()),"FINISHED_SAMPLING_SIGNATURE_INVALID");var all=quality.sourceEvidence(org,request.getMainBatchId());var plan=read(request.getSpecificationSnapshotJson());var n=json.createObjectNode();n.put("inspectionRequestId",request.getId()+"");n.put("mainBatchId",request.getMainBatchId()+"");n.put("materialLotId",request.getMaterialLotId()+"");n.put("qcSpecificationVersionId",request.getQcSpecificationVersionId()+"");n.put("specificationDigest",request.getSpecificationDigest());n.put("receivingSourceDigest",receipt.path("sourceDigest").asText());n.set("specification",plan.path("specification"));var samplingFacts=n.putArray("samplingRecords");records.forEach(x->samplingFacts.add(SignedRecordSupport.publicView(x,json)));Set<Long> sampleIds=new HashSet<>();records.forEach(x->sampleIds.add(x.getSampleId()));var samples=n.putArray("samples");Set<Long> inspectionSamples=new HashSet<>();for(var sample:all.path("samples"))if(sampleIds.contains(sample.path("id").asLong())){gate(sample.path("mainBatchId").asLong()==request.getMainBatchId()&&sample.path("materialLotId").asLong()==request.getMaterialLotId()&&sample.path("qcSpecificationVersionId").asLong()==request.getQcSpecificationVersionId(),"FINISHED_SAMPLE_PROVENANCE_MISMATCH");samples.add(sample);if("TEST_SAMPLE".equals(sample.path("sampleType").asText()))inspectionSamples.add(sample.path("id").asLong());}gate(!inspectionSamples.isEmpty(),"FINISHED_TEST_SAMPLE_REQUIRED");
  var tests=n.putArray("tests");for(var test:all.path("tests"))if(sampleIds.contains(test.path("sampleId").asLong()))tests.add(test);n.set("investigations",all.path("deviations"));var items=n.putArray("items");boolean overallPass=true;
  for(var item:plan.path("specification").path("items")){
   JsonNode effective=null;var original=n.arrayNode();for(var test:tests)if(test.path("qcSpecificationItemId").asLong()==item.path("specificationItemId").asLong()&&inspectionSamples.contains(test.path("sampleId").asLong())){
    for(var result:test.path("results")){original.add(result);if(test.path("currentResultRevisionId").asLong()!=result.path("id").asLong()||!signing.valid(org,result.path("signatureId").asLong()))continue;boolean reviewed=false;for(var review:result.path("reviews"))if("CONFIRMED".equals(review.path("disposition").asText())&&signing.valid(org,review.path("signatureId").asLong())&&review.path("reviewedBy").asLong()!=result.path("recordedBy").asLong())reviewed=true;
     if(reviewed&&test.hasNonNull("approvedInvestigationId")){boolean approved=false;for(var d:all.path("deviations"))if(d.path("id").asLong()==test.path("approvedInvestigationId").asLong()&&"CLOSED".equals(d.path("status").asText())&&d.path("selectedResultRevisionId").asLong()==result.path("id").asLong()&&signing.valid(org,d.path("closeSignatureId").asLong()))approved=true;reviewed=approved;}
     if(reviewed&&(effective==null||result.path("id").asLong()>effective.path("id").asLong()))effective=result;
    }
   }
   // Every original FAIL needs its own signed closed investigation and a selected authorized result.
   // A later unrelated sample is never an OOS disposition.
   for(var failed:original)if("FAIL".equals(failed.path("resultConclusion").asText())){
    boolean resolved=false;
    for(var d:all.path("deviations"))if(d.path("originalResultRevisionId").asLong()==failed.path("id").asLong()&&"CLOSED".equals(d.path("status").asText())&&signing.valid(org,d.path("closeSignatureId").asLong())){
     for(var t:tests)if(t.path("qcSpecificationItemId").asLong()==item.path("specificationItemId").asLong()&&t.path("approvedInvestigationId").asLong()==d.path("id").asLong()&&inspectionSamples.contains(t.path("sampleId").asLong()))for(var selected:t.path("results"))if(selected.path("id").asLong()==d.path("selectedResultRevisionId").asLong()&&selected.path("id").asLong()==t.path("currentResultRevisionId").asLong()&&"PASS".equals(selected.path("resultConclusion").asText())&&signing.valid(org,selected.path("signatureId").asLong()))for(var review:selected.path("reviews"))if("CONFIRMED".equals(review.path("disposition").asText())&&signing.valid(org,review.path("signatureId").asLong())&&review.path("reviewedBy").asLong()!=selected.path("recordedBy").asLong())resolved=true;
    }
    if(!resolved){effective=failed;break;}
   }
   if(item.path("required").asBoolean())gate(effective!=null,"FINISHED_REPORT_RESULTS_INCOMPLETE");var line=items.addObject();line.set("standard",item);line.set("originalResults",original);if(effective!=null){line.set("effectiveResult",effective);line.put("conclusion",effective.path("resultConclusion").asText());if(item.path("required").asBoolean()&&!"PASS".equals(effective.path("resultConclusion").asText()))overallPass=false;}else{line.putNull("effectiveResult");line.put("conclusion","NOT_TESTED");}
  }
  n.put("overallConclusion",overallPass?"PASS":"FAIL");return n;
 }
 @Transactional public JsonNode generateReport(String target,JsonNode body,String header,String key){fields(body,"versionNo","reportNo","reason");var c=mutations.context("qms:finished-report:generate");long expected=expected(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"FINISHED_REPORT_GENERATE:"+target,key,Map.of("target",target,"body",body),()->{var found=requests.get(c.organizationId(),MasterMutation.id(target));mutable(c.organizationId(),found.getMainBatchId());var request=requests.lock(c.organizationId(),found.getId());version(request.getVersionNo(),expected);gate(Set.of("ACCEPTED","COMPLETED").contains(request.getStatus()),"FINISHED_QC_ACCEPTANCE_REQUIRED");var aggregate=aggregate(request);var row=new FinishedInspectionReportEntity();row.setReportNo(text(body,"reportNo",80));row.setInspectionRequestId(request.getId());var previous=reportRows(c.organizationId(),request.getId());row.setGenerationNo(previous.isEmpty()?1L:previous.getLast().getGenerationNo()+1);row.setOverallConclusion(aggregate.path("overallConclusion").asText());row.setStatus("GENERATED");row.setEvidenceDigest(mutations.digest(aggregate));row.setSummaryJson(aggregate.toString());row.setGeneratedBy(c.actorId());row.setGeneratedAt(now());row.setReason(reason);reports.insert(row,c.organizationId(),c.actorId());requests.update(request,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"FINISHED_REPORT_GENERATED","FinishedInspectionReport",row.getId(),null,view(row),reason,key);return row;},x->view((FinishedInspectionReportEntity)x),201);}
 @Transactional public JsonNode approveReport(String target,JsonNode body,String header,String key){fields(body,"versionNo","reason","signature");var c=mutations.context("qms:finished-report:approve");long expected=expected(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"FINISHED_REPORT_APPROVE:"+target,key,Map.of("target",target,"body",body),()->{
  var found=reports.get(c.organizationId(),MasterMutation.id(target));var parent=requests.get(c.organizationId(),found.getInspectionRequestId());mutable(c.organizationId(),parent.getMainBatchId());var request=requests.lock(c.organizationId(),parent.getId());var row=reports.lock(c.organizationId(),found.getId());version(row.getVersionNo(),expected);gate("GENERATED".equals(row.getStatus()),"FINISHED_REPORT_STATE_CONFLICT");independent(c.actorId(),row.getGeneratedBy());actors.requireQualified(c.organizationId(),c.actorId(),"test-review");var source=aggregate(request);gate(row.getEvidenceDigest().equals(mutations.digest(source)),"FINISHED_REPORT_EVIDENCE_CHANGED");gate(reportRows(c.organizationId(),request.getId()).getLast().getId().equals(row.getId()),"FINISHED_REPORT_SUPERSEDED");for(var test:source.path("tests"))for(var result:test.path("results"))independent(c.actorId(),result.path("recordedBy").asLong());var before=view(row);row.setStatus("APPROVED");row.setApprovedBy(c.actorId());row.setApprovedAt(now());var evidence=signing.sign(c,"FINISHED_INSPECTION_REPORT",row.getId()+":"+expected,expected,SignatureMeaning.APPROVE,row,body.get("signature"),key,List.of("FinishedInspectionRequest:"+request.getId(),"MaterialLot:"+request.getMaterialLotId()));row.setSignatureId(evidence.id());row.setSignatureEvidenceJson(evidence.envelope());reports.update(row,expected,c.actorId(),List.of("status","approvedBy","approvedAt","signatureId","signatureEvidenceJson"));var review=new FinishedReportReviewEntity();review.setReportId(row.getId());review.setReviewDecision("APPROVE");review.setReviewedBy(c.actorId());review.setReviewedAt(now());review.setSignatureId(evidence.id());review.setSignatureEvidenceJson(evidence.envelope());review.setReason(reason);reviews.insert(review,c.organizationId(),c.actorId());request.setStatus("COMPLETED");requests.update(request,request.getVersionNo(),c.actorId(),List.of("status"));mutations.auditSnapshot(c,"FINISHED_REPORT_APPROVED","FinishedInspectionReport",row.getId(),before,view(row),reason,key);return row;
 },x->view((FinishedInspectionReportEntity)x),200);}
 @Transactional(propagation=Propagation.MANDATORY) public JsonNode releaseEvidence(long org,long batch){var n=json.createObjectNode();var codes=n.putArray("blockingCodes");FinishedInspectionRequestEntity request=requestsMapper.selectOne(new QueryWrapper<FinishedInspectionRequestEntity>().eq("org_id",org).eq("main_batch_id",batch).last("FOR UPDATE"));if(request==null){codes.add("FINISHED_INSPECTION_REQUEST_REQUIRED");return n;}n.set("request",view(request));if(!"COMPLETED".equals(request.getStatus()))codes.add("FINISHED_INSPECTION_INCOMPLETE");var all=reportRows(org,request.getId());if(all.isEmpty()){codes.add("FINISHED_REPORT_REQUIRED");return n;}var report=all.getLast();n.set("report",view(report));if(!"APPROVED".equals(report.getStatus())||!signing.valid(org,report.getSignatureId()))codes.add("FINISHED_REPORT_APPROVAL_REQUIRED");if(!"PASS".equals(report.getOverallConclusion()))codes.add("FINISHED_REPORT_NOT_PASS");try{var source=aggregate(request);if(!report.getEvidenceDigest().equals(mutations.digest(source)))codes.add("FINISHED_REPORT_EVIDENCE_CHANGED");}catch(ComplianceException ex){codes.add(ex.code());}return n;}
 private ObjectNode publicView(ScopedEntity row){return SignedRecordSupport.publicView(row,json);}
 private ObjectNode view(FinishedInspectionRequestEntity row){return view(row,false);}
 private ObjectNode view(FinishedInspectionRequestEntity row,boolean internal){var n=publicView(row);n.remove("specificationSnapshotJson");n.set("specificationSnapshot",read(row.getSpecificationSnapshotJson()));n.set("batch",batches.batchFact(row.getOrgId(),row.getMainBatchId()));if(internal||contexts.current().hasPermission("qms:finished-sampling:view")){var records=n.putArray("samplingRecords");samplingRows(row.getOrgId(),row.getId()).forEach(x->records.add(view(x)));}if(internal||contexts.current().hasPermission("qms:finished-report:view")){var all=n.putArray("reports");reportRows(row.getOrgId(),row.getId()).forEach(x->all.add(view(x)));}var actions=n.putArray("allowedActions");var c=contexts.current();if(!Set.of("PRODUCTION_COMPLETED","PENDING_QA").contains(batches.batch(row.getOrgId(),row.getMainBatchId()).status()))return n;if("DRAFT".equals(row.getStatus())&&c.hasPermission("qms:finished-request:submit")&&"CONFIRMED".equals(warehouse.inbound(row.getOrgId(),row.getInboundRequestId()).path("status").asText()))actions.add("SUBMIT");if("SUBMITTED".equals(row.getStatus())&&c.hasPermission("qms:finished-request:accept"))actions.add("ACCEPT");if("ACCEPTED".equals(row.getStatus())&&c.hasPermission("qms:finished-sampling:create"))actions.add("SAMPLE");if(Set.of("ACCEPTED","COMPLETED").contains(row.getStatus())&&c.hasPermission("qms:finished-report:generate"))actions.add("GENERATE_REPORT");return n;}
 private ObjectNode view(FinishedSamplingRecordEntity row){var n=publicView(row);if(contexts.current().hasPermission("qms:sample:view"))n.set("sample",quality.get(ProductionQualityService.SAMPLE,row.getSampleId()+""));n.putArray("allowedActions");return n;}
 private ObjectNode view(FinishedInspectionReportEntity row){var n=publicView(row);n.remove("summaryJson");n.set("summary",read(row.getSummaryJson()));var list=n.putArray("reviews");reviewsMapper.selectList(new QueryWrapper<FinishedReportReviewEntity>().eq("org_id",row.getOrgId()).eq("report_id",row.getId()).orderByAsc("id")).forEach(x->list.add(publicView(x)));var actions=n.putArray("allowedActions");var c=contexts.current();if(Set.of("PRODUCTION_COMPLETED","PENDING_QA").contains(batches.batch(row.getOrgId(),requests.get(row.getOrgId(),row.getInspectionRequestId()).getMainBatchId()).status())&&"GENERATED".equals(row.getStatus())&&c.actorId()!=row.getGeneratedBy()&&c.hasPermission("qms:finished-report:approve"))actions.add("APPROVE");return n;}
 @Transactional(readOnly=true) public JsonNode getRequest(String id){var c=mutations.context("qms:finished-request:view");return view(requests.get(c.organizationId(),MasterMutation.id(id)));}
 @Transactional(readOnly=true) public JsonNode getReport(String id){var c=mutations.context("qms:finished-report:view");return view(reports.get(c.organizationId(),MasterMutation.id(id)));}
 @Transactional(readOnly=true) public JsonNode getSampling(String id){var c=mutations.context("qms:finished-sampling:view");return view(sampling.get(c.organizationId(),MasterMutation.id(id)));}
 @Transactional(readOnly=true) public ScopedStore.PageData<JsonNode> list(String resource,int page,int size,Map<String,String> filters){String permission=switch(resource){case "requests"->"qms:finished-request:view";case "sampling"->"qms:finished-sampling:view";case "reports"->"qms:finished-report:view";default->throw new IllegalArgumentException("Unknown finished quality resource");};var c=mutations.context(permission);Set<String> accepted=resource.equals("requests")?Set.of("page","size","keyword","mainBatchId","status","sort"):resource.equals("reports")?Set.of("page","size","keyword","inspectionRequestId","status","sort"):Set.of("page","size","keyword","inspectionRequestId","sort");filters.keySet().forEach(k->{if(!accepted.contains(k))throw new IllegalArgumentException("Unknown filter: "+k);});if(resource.equals("requests")){var data=requests.list(c.organizationId(),page,size,filters.get("keyword"),filters);return new ScopedStore.PageData<>(data.items().stream().map(x->(JsonNode)view(x)).toList(),data.total(),page,size);}if(resource.equals("sampling")){var data=sampling.list(c.organizationId(),page,size,filters.get("keyword"),filters);return new ScopedStore.PageData<>(data.items().stream().map(x->(JsonNode)view(x)).toList(),data.total(),page,size);}var data=reports.list(c.organizationId(),page,size,filters.get("keyword"),filters);return new ScopedStore.PageData<>(data.items().stream().map(x->(JsonNode)view(x)).toList(),data.total(),page,size);}
 public List<String> envelopes(String type,long org,String target){long id=MasterMutation.id(target.split(":")[0]);if(type.equals("FINISHED_SAMPLING"))return samplingRows(org,id).stream().map(FinishedSamplingRecordEntity::getSignatureEvidenceJson).filter(Objects::nonNull).toList();var row=reports.get(org,id);return row.getSignatureEvidenceJson()==null?List.of():List.of(row.getSignatureEvidenceJson());}
 private JsonNode stable(JsonNode value){if(value.isObject()){((ObjectNode)value).remove(List.of("allowedActions","batch","sample"));value.elements().forEachRemaining(this::stable);}else if(value.isArray())value.elements().forEachRemaining(this::stable);return value;}
 public JsonNode sourceEvidence(long org,long batch){batches.batch(org,batch);var n=json.createObjectNode();var list=n.putArray("requests");for(var r:requestsMapper.selectList(new QueryWrapper<FinishedInspectionRequestEntity>().eq("org_id",org).eq("main_batch_id",batch).orderByAsc("id")))list.add(stable(view(r,true)));return n;}
}
