package com.hospital.mes.qms.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.hospital.mes.qms.infrastructure.*;
import com.hospital.mes.qms.domain.IpcRules;
import com.hospital.mes.execution.application.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.audit.signature.SignatureMeaning;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.annotation.Propagation;
import java.util.*;
import static com.hospital.mes.production.application.ProductionInput.*;
import static com.hospital.mes.production.domain.ProductionRules.*;
@org.springframework.stereotype.Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class IpcService implements ExecutionQualityPort {
 private final IpcInstanceMapper instances;private final IpcResultMapper results;private final IpcReviewMapper reviews;private final ScopedStore<IpcInstanceEntity> store;private final QualityOperationQueryService operations;private final MasterMutation mutations;private final SignedRecordSupport signing;private final ObjectMapper json;
 public IpcService(IpcInstanceMapper instances,IpcResultMapper results,IpcReviewMapper reviews,QualityOperationQueryService operations,MasterMutation mutations,SignedRecordSupport signing,ObjectMapper json){this.instances=instances;this.results=results;this.reviews=reviews;this.operations=operations;this.mutations=mutations;this.signing=signing;this.json=json;store=new ScopedStore<>(instances,List.of("ipc_code"),Map.of("operationExecutionId","operation_execution_id","ipcCode","ipc_code","status","status"));}
 @Transactional(propagation=Propagation.MANDATORY) public void initialize(long org,long actor,long op,JsonNode definition){for(var def:definition.path("ipcDefinitions")){var row=new IpcInstanceEntity();row.setOperationExecutionId(op);row.setIpcCode(def.path("ipcCode").asText());row.setStatus("PENDING");row.setDefinitionSnapshotJson(def.toString());store.insert(row,org,actor);var c=mutations.context("production:batch:release");mutations.auditSnapshot(c,"IPC_INITIALIZE","IpcInstance",row.getId(),null,view(row),"Frozen operation IPC initialization",null);}}
 private List<IpcInstanceEntity> current(long org,long op,boolean lock){var q=new QueryWrapper<IpcInstanceEntity>().eq("org_id",org).eq("operation_execution_id",op).orderByAsc("id");if(lock)q.last("FOR UPDATE");return instances.selectList(q);}
 private IpcResultEntity result(long org,long id,boolean lock){var q=new QueryWrapper<IpcResultEntity>().eq("org_id",org).eq("id",id);if(lock)q.last("FOR UPDATE");var row=results.selectOne(q);if(row==null)throw new NoSuchElementException("IPC result not found");return row;}
 private IpcReviewEntity review(long org,long id,boolean lock){var q=new QueryWrapper<IpcReviewEntity>().eq("org_id",org).eq("ipc_result_revision_id",id);if(lock)q.last("FOR UPDATE");return reviews.selectOne(q);}
 private JsonNode parse(String value){try{return json.readTree(value);}catch(java.io.IOException ex){throw new IllegalStateException("Invalid frozen IPC definition",ex);}}
 public JsonNode instances(long org,long op){operations.get(org,op);var a=json.createArrayNode();current(org,op,false).forEach(x->a.add(view(x)));return a;}
 public void requireComplete(long org,long op,JsonNode definition){var rows=current(org,op,true);for(var instance:rows){if(instance.getCurrentResultRevisionId()==null)continue;var original=result(org,instance.getCurrentResultRevisionId(),true);var decision=review(org,original.getId(),true);if("FAIL".equals(original.getResultConclusion()))gate(decision!=null&&"INVALIDATED".equals(decision.getDisposition())&&signing.valid(org,decision.getSignatureId()),"IPC_VALID_FAIL_BLOCKING","An original valid FAIL blocks completion, including optional IPC");}for(var def:definition.path("ipcDefinitions")){if(!def.path("required").asBoolean())continue;var instance=rows.stream().filter(x->x.getIpcCode().equals(def.path("ipcCode").asText())).findFirst().orElse(null);gate(instance!=null&&parse(instance.getDefinitionSnapshotJson()).equals(def),"IPC_REQUIRED_PENDING","Frozen required IPC instance missing");gate(instance.getCurrentResultRevisionId()!=null,"IPC_REQUIRED_PENDING","Required IPC has no original result");var original=result(org,instance.getCurrentResultRevisionId(),true);var review=review(org,original.getId(),true);gate(original.getIpcInstanceId().equals(instance.getId())&&"PASS".equals(original.getResultConclusion())&&review!=null&&"CONFIRMED".equals(review.getDisposition())&&review.getReviewedBy().longValue()!=original.getRecordedBy().longValue()&&signing.valid(org,original.getSignatureId())&&signing.valid(org,review.getSignatureId()),"IPC_REQUIRED_PENDING","Required IPC must have independently confirmed valid PASS result");}}
 public JsonNode get(String target){var c=mutations.context("qms:ipc:view");return view(store.get(c.organizationId(),MasterMutation.id(target)));}
 public ScopedStore.PageData<JsonNode> list(int page,int size,Map<String,String> filters){var c=mutations.context("qms:ipc:view");var rows=store.list(c.organizationId(),page,size,null,filters);return new ScopedStore.PageData<>(rows.items().stream().map(this::view).toList(),rows.total(),page,size);}
 @Transactional public JsonNode create(JsonNode body,String key){fields(body,"operationExecutionId","ipcCode","reason");var c=mutations.context("qms:ipc:record");long operation=id(body,"operationExecutionId");String code=text(body,"ipcCode",64);text(body,"reason",1000);return mutations.execute(c,"IPC:CREATE",key,body,()->{var locked=operations.lock(c.organizationId(),operation);IpcRules.mutableOperation(locked.operation().getStatus());gate(locked.definition().path("ipcDefinitions").findValuesAsText("ipcCode").contains(code),"IPC_NOT_FROZEN","IPC must be defined in frozen operation");return current(c.organizationId(),operation,true).stream().filter(x->x.getIpcCode().equals(code)).findFirst().orElseThrow(()->new com.hospital.mes.common.exception.ComplianceException("IPC_INITIALIZATION_MISSING","Atomic release initialization is required"));},row->view((IpcInstanceEntity)row),200);}
 private IpcInstanceEntity lock(long org,long id){var found=store.get(org,id);var operation=operations.lock(org,found.getOperationExecutionId());IpcRules.mutableOperation(operation.operation().getStatus());return store.lock(org,id);}
 @Transactional public JsonNode submit(String target,JsonNode body,String header,String key){fields(body,"versionNo","previousRevisionId","resultNumeric","resultText","reason","signature");var c=mutations.context("qms:ipc:record");long expected=SignedRecordSupport.expected(body,header);String why=text(body,"reason",1000);return mutations.execute(c,"IPC:RESULT:"+target,key,Map.of("target",target,"body",body),()->{
  var instance=lock(c.organizationId(),MasterMutation.id(target));version(instance.getVersionNo(),expected);Long previous=optionalId(body,"previousRevisionId");gate(Objects.equals(previous,instance.getCurrentResultRevisionId()),"IPC_PREDECESSOR_CONFLICT","Exact current revision required");int revision=1;if(previous!=null){var old=result(c.organizationId(),previous,true);var approved=review(c.organizationId(),previous,true);gate(approved!=null&&"INVALIDATED".equals(approved.getDisposition())&&signing.valid(c.organizationId(),approved.getSignatureId()),"IPC_ORIGINAL_RESULT_PROTECTED","A valid original result cannot be overwritten/retested without signed invalidation");revision=old.getRevisionNo()+1;}
  var def=parse(instance.getDefinitionSnapshotJson());var row=new IpcResultEntity();row.setIpcInstanceId(instance.getId());row.setRevisionNo(revision);row.setPreviousRevisionId(previous);row.setDefinitionSnapshotJson(def.toString());row.setResultConclusion(IpcRules.conclusion(def,body));if(body.hasNonNull("resultNumeric"))row.setResultNumeric(IpcRules.numeric(body.get("resultNumeric").asText()));else row.setResultText(text(body,"resultText",1000));row.setReasonForChange(why);row.setRecordedBy(c.actorId());row.setRecordedAt(now());var evidence=signing.sign(c,"IPC_RESULT",target+":"+expected,expected,SignatureMeaning.VERIFY,row,body.get("signature"),key,List.of("IpcInstance:"+target));row.setSignatureId(evidence.id());row.setSignatureEvidenceJson(evidence.envelope());new ScopedStore<>(results,List.of(),Map.of()).insert(row,c.organizationId(),c.actorId());instance.setCurrentResultRevisionId(row.getId());instance.setStatus("TESTING");instance.setResult(row.getResultConclusion());instance.setCompletedAt(null);store.update(instance,expected,c.actorId(),List.of("currentResultRevisionId","status","result","completedAt"));mutations.auditSnapshot(c,"IPC_RESULT","IpcResultRevision",row.getId(),null,mutations.view(row),why,key);return instance;
 },row->view((IpcInstanceEntity)row),200);}
 @Transactional public JsonNode reviewResult(String target,JsonNode body,String header,String key){fields(body,"versionNo","resultRevisionId","disposition","reason","signature");var c=mutations.context("qms:ipc:review");long expected=SignedRecordSupport.expected(body,header);return mutations.execute(c,"IPC:REVIEW:"+target,key,Map.of("target",target,"body",body),()->{
  var instance=lock(c.organizationId(),MasterMutation.id(target));version(instance.getVersionNo(),expected);long resultId=id(body,"resultRevisionId");gate(Objects.equals(instance.getCurrentResultRevisionId(),resultId),"IPC_PREDECESSOR_CONFLICT","Review must name current exact result");var original=result(c.organizationId(),resultId,true);gate(original.getRecordedBy()!=c.actorId(),"INDEPENDENT_REVIEW_REQUIRED","Recorder cannot review result");gate(review(c.organizationId(),resultId,true)==null,"IPC_ALREADY_REVIEWED","Review cannot be replaced");gate(signing.valid(c.organizationId(),original.getSignatureId()),"IPC_SIGNATURE_INVALID","Original result signature invalid");String disposition=text(body,"disposition",20);gate(Set.of("CONFIRMED","INVALIDATED").contains(disposition),"IPC_REVIEW_INVALID","Disposition invalid");
  var row=new IpcReviewEntity();row.setIpcResultRevisionId(resultId);row.setDisposition(disposition);row.setReason(text(body,"reason",1000));row.setReviewedBy(c.actorId());row.setReviewedAt(now());var evidence=signing.sign(c,"IPC_REVIEW",resultId+":"+expected,expected,SignatureMeaning.APPROVE,row,body.get("signature"),key,List.of("IpcResultRevision:"+resultId));row.setSignatureId(evidence.id());row.setSignatureEvidenceJson(evidence.envelope());new ScopedStore<>(reviews,List.of(),Map.of()).insert(row,c.organizationId(),c.actorId());instance.setStatus(disposition.equals("CONFIRMED")?"COMPLETED":"TESTING");instance.setResult(disposition.equals("CONFIRMED")?original.getResultConclusion():"INVALID");instance.setCompletedAt(disposition.equals("CONFIRMED")?now():null);store.update(instance,expected,c.actorId(),List.of("status","result","completedAt"));mutations.auditSnapshot(c,"IPC_REVIEW","IpcReview",row.getId(),null,mutations.view(row),row.getReason(),key);return instance;
 },row->view((IpcInstanceEntity)row),200);}
 private ObjectNode immutableView(com.hospital.mes.masterdata.infrastructure.ScopedEntity row){var n=SignedRecordSupport.publicView(row,json);n.remove(List.of("signatureEvidenceJson","updatedBy","updatedAt","versionNo"));return n;}
 public JsonNode view(IpcInstanceEntity row){var n=SignedRecordSupport.publicView(row,json);n.remove("definitionSnapshotJson");n.set("definitionSnapshot",parse(row.getDefinitionSnapshotJson()));var items=n.putArray("results");for(var result:results.selectList(new QueryWrapper<IpcResultEntity>().eq("org_id",row.getOrgId()).eq("ipc_instance_id",row.getId()).orderByAsc("revision_no"))){var r=immutableView(result);r.remove("definitionSnapshotJson");r.set("definitionSnapshot",parse(result.getDefinitionSnapshotJson()));var review=review(row.getOrgId(),result.getId(),false);if(review!=null)r.set("review",immutableView(review));items.add(r);}var actions=n.putArray("allowedActions");if(Set.of("READY","IN_PROGRESS","PAUSED").contains(operations.get(row.getOrgId(),row.getOperationExecutionId()).getStatus())){if(row.getCurrentResultRevisionId()==null)actions.add("SUBMIT_RESULT");else{var review=review(row.getOrgId(),row.getCurrentResultRevisionId(),false);if(review==null)actions.add("REVIEW_RESULT");else if("INVALIDATED".equals(review.getDisposition()))actions.add("SUBMIT_RESULT");}}return n;}
}
