<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { api, errorMessage, idempotencyKey, type Page, type Permission } from '../../api/http'
import { useAuthStore } from '../../stores/auth'
import { useRouter, onBeforeRouteLeave } from 'vue-router'
import { catalogTree, type MenuEntry as Menu } from './menuCatalog'
const detailOpen=ref(false)
const permissionCatalog = ref<Permission[]>([]), nodeType = ref<'DIRECTORY'|'MENU'>('MENU'), selectedKey=ref<string[]>([])
const router=useRouter(), functionOpen=ref(false), functionCode=ref<string|undefined>(), functionReason=ref(''), functionBusy=ref(false), functionError=ref('')
const newFunction=reactive({code:'',name:'',reason:''}), defineFunction=ref(false), createdFunctionCode=ref<string|undefined>()
const currentFunctions=computed(()=>permissionCatalog.value.filter(p=>selectedMenu.value?.permissionCodes?.includes(p.permissionCode)))
const auth = useAuthStore(), menus = ref<Menu[]>([]), loading = ref(false), busy = ref(false), error = ref(''), notice = ref(''), keyword = ref(''), opened = ref(false), editing = ref<Menu | null>(null)
const form = reactive({ menuCode: '', menuName: '', routePath: '', permissionCode: undefined as string|undefined, requiredPermissions: '' ,parentId: undefined as string | undefined, sortNo: 0, status: 'ACTIVE' as 'ACTIVE' | 'INACTIVE', reason: '' })
const filtered = computed(() => menus.value.filter(m => `${m.menuCode} ${m.menuName} ${m.routePath}`.toLowerCase().includes(keyword.value.trim().toLowerCase())))
const tree = computed(() => catalogTree(menus.value))
interface Row extends Menu {children?: Row[]}
const treeRows=computed(()=>{function rows(nodes: ReturnType<typeof catalogTree>):Row[]{return nodes.flatMap(node=>{const children=rows(node.children);const query=keyword.value.trim().toLowerCase();const match=!query||`${node.entry.menuName} ${node.entry.menuCode} ${node.entry.routePath}`.toLowerCase().includes(query);return match||children.length?[{...node.entry,...(children.length?{children}:{})}]:[]})}return rows(tree.value)})
const selectedMenu = computed(()=>menus.value.find(m=>m.id===selectedKey.value[0]))
const permissionOptions = computed(()=>permissionCatalog.value.map(p=>({value:p.permissionCode,label:`${p.permissionName} (${p.permissionCode})`})))
const columns = [{ title: '菜单名称', dataIndex: 'menuName' }, { title: '节点类型', key: 'parent' }, { title: '页面地址', dataIndex: 'routePath' }, { title: '排序', dataIndex: 'sortNo' }, { title: '状态', key: 'status' }, { title: '操作', key: 'actions' }]
const parents = computed(() => {const available=menus.value.filter(m => m.id !== editing.value?.id && !isDescendant(m.id, editing.value?.id));function nodes(tree:ReturnType<typeof catalogTree>):any[]{return tree.map(n=>({value:n.key,title:n.title,children:nodes(n.children)}))}return nodes(catalogTree(available))})
function isDescendant(id: string, ancestor?: string) { const seen = new Set<string>(); let current = menus.value.find(m => m.id === id); while (current?.parentId && !seen.has(current.id)) { if (current.parentId === ancestor) return true; seen.add(current.id); current = menus.value.find(m => m.id === current!.parentId) } return false }
async function load() { loading.value = true; error.value = ''; try { const all: Menu[] = []; for (let page = 0; ; page++) { const result = await api<Page<Menu>>({ url: '/menus', params: { page, size: 100 } }); all.push(...result.items); if (all.length >= result.total) break; if (!result.items.length) throw new Error('菜单目录加载不完整') } menus.value = all } catch (cause) { error.value = errorMessage(cause) } finally { loading.value = false } }
function edit(menu: Menu | null) { editing.value = menu; nodeType.value=menu && !menu.routePath?'DIRECTORY':'MENU'; Object.assign(form, menu ? { ...menu, routePath:menu.routePath??'',permissionCode:menu.permissionCode??undefined,requiredPermissions:menu.requiredPermissions??'',parentId: menu.parentId ?? undefined, reason: '' } : { menuCode: '', menuName: '', routePath: '', permissionCode:undefined,requiredPermissions:'',parentId: undefined, sortNo: 0, status: 'ACTIVE', reason: '' }); opened.value = true; error.value = ''; notice.value = '' }
const snapshot = () => JSON.stringify([form,nodeType.value])
const initial = ref('')
function open(menu: Menu | null) { edit(menu); initial.value = snapshot() }
onBeforeRouteLeave(()=> !busy.value && !functionBusy.value && ((!opened.value || snapshot()===initial.value) && !functionOpen.value || window.confirm('离开将放弃未保存的菜单配置，是否继续？')))
function close() { if (busy.value) return; if (snapshot() !== initial.value && !window.confirm('放弃未保存的菜单修改？')) return; opened.value = false }
async function save() {
  if (busy.value || !auth.can(editing.value ? 'iam:menu:update' : 'iam:menu:create')) return
  error.value = ''
  if (!form.menuCode.trim() || !form.menuName.trim() || (nodeType.value==='MENU' && (!form.routePath.trim() || !form.permissionCode))) { error.value = '请填写编码、名称、菜单页面与查看权限'; return }
  if (nodeType.value==='MENU' && (!form.routePath.startsWith('/') || form.routePath.startsWith('//'))) { error.value = '页面地址须以 / 开头，并指向系统已有页面'; return }
  if(nodeType.value==='MENU' && router.resolve(form.routePath).matched.some(r=>r.path.includes(':pathMatch'))) { error.value='页面地址未关联到已有业务页面';return }
  if (form.parentId && isDescendant(form.parentId, editing.value?.id)) { error.value = '上级菜单不能是当前菜单的下级'; return }
  busy.value = true
  try { const data = { menuName: form.menuName.trim(), routePath: nodeType.value==='DIRECTORY'?null:form.routePath.trim(),permissionCode:nodeType.value==='DIRECTORY'?null:form.permissionCode,requiredPermissions:nodeType.value==='DIRECTORY'?'':form.requiredPermissions.trim(), parentId: form.parentId ?? null, sortNo: form.sortNo, status: form.status, reason: '菜单配置维护（系统记录）' }; await api<Menu>({ method: editing.value ? 'PUT' : 'POST', url: editing.value ? `/menus/${editing.value.id}` : '/menus', headers: { 'Idempotency-Key': idempotencyKey(), ...(editing.value ? { 'If-Match': `"${editing.value.version}"` } : {}) }, data: editing.value ? data : { ...data, menuCode: form.menuCode.trim() } }); opened.value = false; notice.value = '菜单配置已保存'; await load();window.dispatchEvent(new Event('mes-navigation-changed')) } catch (cause) { error.value = errorMessage(cause) } finally { busy.value = false }
}
onMounted(async()=>{await load();if(auth.can('iam:permission:view'))try{for(let page=0;;page++){const data=await api<Page<Permission>>({url:'/permissions',params:{page,size:100,status:'ACTIVE'}});permissionCatalog.value.push(...data.items);if(permissionCatalog.value.length>=data.total)break;if(!data.items.length)break}}catch(cause){error.value=errorMessage(cause)}})
function openFunction(create:boolean) { functionOpen.value=true;defineFunction.value=create;functionCode.value=undefined;functionReason.value='';functionError.value='';createdFunctionCode.value=undefined;Object.assign(newFunction,{code:'',name:'',reason:''}) }
async function bindFunction() {
  const menu=selectedMenu.value;if(!menu || functionBusy.value)return
  functionError.value='';const reason='菜单子权限维护（系统记录）'
  if((defineFunction.value?(!newFunction.code.trim() || !newFunction.name.trim()):!functionCode.value)){functionError.value='请填写权限';return}
  if(defineFunction.value && !/^[a-z][a-z0-9-]*(?::[a-z][a-z0-9-]*){2}$/.test(newFunction.code.trim())){functionError.value='权限编码使用三段格式，例如 qms:report:export';return}
  functionBusy.value=true
  try {
    let code=functionCode.value
    if(defineFunction.value){
      if(!createdFunctionCode.value){const permission=await api<Permission>({method:'POST',url:'/permissions',headers:{'Idempotency-Key':idempotencyKey()},data:{permissionCode:newFunction.code.trim(),permissionName:newFunction.name.trim(),permissionType:'ACTION',routePath:null,status:'ACTIVE',reason}});createdFunctionCode.value=permission.permissionCode;permissionCatalog.value.push(permission)}
      code=createdFunctionCode.value
    }
    const saved=await api<Menu>({method:'POST',url:`/menus/${menu.id}/permissions`,headers:{'Idempotency-Key':idempotencyKey(),'If-Match':`"${menu.version}"`},data:{permissionCodes:[...new Set([...(menu.permissionCodes??[]),code!])],reason}})
    menus.value=menus.value.map(m=>m.id===saved.id?saved:m);functionOpen.value=false;notice.value='子权限已关联到菜单'
  } catch(cause){functionError.value=`${createdFunctionCode.value?'权限定义已创建，菜单关联未完成；重试只会重新关联。':''}${errorMessage(cause)}`}finally{functionBusy.value=false}
}
</script>
<template>
  <main data-ui-template="T1" class="admin-page t1-query-list">
    <header class="admin-page-header"><div><h1>菜单管理</h1></div><a-button v-if="auth.can('iam:menu:create')" type="primary" @click="open(null)">新增菜单</a-button></header>
    
    <a-alert v-if="error && !opened" type="error" :message="error" show-icon /><a-alert v-if="notice" type="success" :message="notice" show-icon />
    <a-card title="查询条件" class="query-card"><div class="query-form"><label><span class="form-field-label">名称、编码或页面地址</span><a-input v-model:value="keyword" aria-label="搜索菜单目录" allow-clear /></label><a-button :loading="loading" @click="load">刷新</a-button></div></a-card>
    <a-card title="菜单设置" class="result-card"><a-table v-if="menus.length" :columns="columns" :data-source="treeRows" row-key="id" :pagination="false" :loading="loading" :scroll="{x:900}" default-expand-all-rows><template #bodyCell="{column,record}"><template v-if="column.key==='parent'">{{record.routePath?'菜单':'目录'}}</template><template v-else-if="column.key==='status'"><a-tag :color="record.status==='ACTIVE'?'success':'default'">{{record.status==='ACTIVE'?'启用':'停用'}}</a-tag></template><template v-else-if="column.key==='actions'"><a-button type="link" @click="selectedKey=[record.id];detailOpen=true">详情与子权限</a-button><a-button v-if="auth.can('iam:menu:update')" type="link" @click="open(record)">编辑</a-button></template></template></a-table><a-empty v-else-if="!loading" description="暂无菜单" /></a-card>
    <a-drawer v-if="selectedMenu" :open="detailOpen" :width="680" :title="`${selectedMenu.menuName} · 菜单详情`" @close="detailOpen=false"><a-descriptions :column="2"><a-descriptions-item label="页面地址">{{selectedMenu.routePath??'目录不跳转'}}</a-descriptions-item><a-descriptions-item label="节点类型">{{selectedMenu.routePath?'菜单':'目录'}}</a-descriptions-item></a-descriptions><template v-if="selectedMenu.routePath"><div class="menu-function-heading"><h3>控制权限</h3><a-space><a-button v-if="auth.can('iam:menu:update') && auth.can('iam:permission:view')" @click="openFunction(false)">关联已有权限</a-button><a-button v-if="auth.can('iam:menu:update') && auth.can('iam:permission:create')" type="primary" @click="openFunction(true)">新增子权限</a-button></a-space></div><a-list :data-source="currentFunctions"><template #renderItem="{item}"><a-list-item><a-list-item-meta :title="item.permissionName" :description="item.permissionCode" /><a-tag>{{item.permissionCode===selectedMenu.permissionCode?'菜单查看':/:(view|create|update|edit|delete|remove)$/.test(item.permissionCode)?'普通权限':'特殊功能'}}</a-tag></a-list-item></template></a-list></template><p v-else class="muted">目录只维护上下级关系；在下面的菜单中维护功能权限。</p></a-drawer>
    <a-modal centered wrap-class-name="menu-edit-modal" :open="opened" :width="760" :body-style="{maxHeight:'calc(100svh - 190px)',overflowY:'auto'}" :title="editing?'编辑菜单':'新增菜单'" :closable="!busy" :mask-closable="false" @cancel="close"><section data-ui-template="T2"><a-alert v-if="error" type="error" :message="error" show-icon /><a-form layout="vertical" class="menu-edit-grid"><a-form-item label="节点类型"><a-radio-group v-model:value="nodeType" :disabled="busy"><a-radio value="DIRECTORY">目录</a-radio><a-radio value="MENU">菜单</a-radio></a-radio-group></a-form-item><a-form-item label="菜单编码" required><a-input v-model:value="form.menuCode" aria-label="菜单编码" :disabled="!!editing || busy" :maxlength="64" /></a-form-item><a-form-item label="菜单名称" required><a-input v-model:value="form.menuName" aria-label="菜单名称" :disabled="busy" :maxlength="100" /></a-form-item><a-form-item v-if="nodeType==='MENU'" label="页面地址" required><a-input v-model:value="form.routePath" aria-label="页面地址" :disabled="busy" placeholder="例如 /master/materials" :maxlength="255" /></a-form-item><a-form-item v-if="nodeType==='MENU'" label="查看权限" required><a-select v-model:value="form.permissionCode" aria-label="菜单查看权限" :options="permissionOptions" show-search option-filter-prop="label" :disabled="busy" placeholder="选择现有页面的查看权限" /></a-form-item><a-form-item v-if="nodeType==='MENU'" label="附加查看权限"><a-input v-model:value="form.requiredPermissions" :disabled="busy" placeholder="多个现有权限编码用英文逗号分隔" /></a-form-item><a-form-item label="上级菜单"><a-tree-select v-model:value="form.parentId" aria-label="上级菜单" :tree-data="parents" show-search tree-node-filter-prop="title" tree-default-expand-all allow-clear :disabled="busy" placeholder="选择上级菜单，支持输入搜索" /></a-form-item><a-form-item label="排序"><a-input-number v-model:value="form.sortNo" aria-label="菜单排序" :precision="0" :min="0" :disabled="busy" /></a-form-item><a-form-item label="状态"><a-radio-group v-model:value="form.status" :disabled="busy"><a-radio value="ACTIVE">启用</a-radio><a-radio value="INACTIVE">停用</a-radio></a-radio-group></a-form-item></a-form></section><template #footer><a-space><a-button :disabled="busy" @click="close">取消</a-button><a-button type="primary" :loading="busy" @click="save">保存菜单配置</a-button></a-space></template></a-modal>
    <a-modal ok-text="保存子权限" cancel-text="取消" :open="functionOpen" :title="defineFunction?'新增菜单子权限':'关联已有权限'" :confirm-loading="functionBusy" :mask-closable="false" :closable="!functionBusy" :cancel-button-props="{disabled:functionBusy}" @cancel="functionOpen=false" @ok="bindFunction"><a-alert v-if="functionError" type="error" :message="functionError" show-icon /><a-form layout="vertical"><template v-if="defineFunction"><a-form-item label="功能名称" required><a-input v-model:value="newFunction.name" aria-label="子权限名称" :maxlength="100" :disabled="functionBusy || !!createdFunctionCode" placeholder="例如 打印、导出" /></a-form-item><a-form-item label="权限编码" required><a-input v-model:value="newFunction.code" aria-label="子权限编码" :maxlength="160" :disabled="functionBusy || !!createdFunctionCode" placeholder="例如 qms:report:export" /></a-form-item></template><template v-else><a-form-item label="已有权限" required><a-select v-model:value="functionCode" :options="permissionOptions" show-search option-filter-prop="label" :disabled="functionBusy" /></a-form-item></template></a-form></a-modal>
  </main>
</template>
<style scoped>.menu-function-heading{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-top:20px}.menu-tree-workspace{display:flex;gap:32px;align-items:flex-start}.menu-tree{width:360px;flex-shrink:0;max-height:680px;overflow:auto}.menu-node-info{flex:1;min-width:0}@media(max-width:900px){.menu-tree-workspace{flex-direction:column}.menu-tree{width:100%;max-height:400px}}.admin-page :deep(.ant-alert){margin-bottom:16px}@media(max-width:600px){:deep(.ant-drawer-content-wrapper){max-width:100vw}}</style>

<style>.menu-edit-modal .menu-edit-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 24px}.menu-edit-modal .ant-form-item{margin-bottom:18px}.menu-edit-modal .ant-select{width:100%}@media(max-width:640px){.menu-edit-modal .menu-edit-grid{grid-template-columns:1fr}}</style>
