<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, errorMessage, type Page, type Role } from '../../api/http'
import { useAuthStore } from '../../stores/auth'
const route=useRoute(); const router=useRouter(); const auth=useAuthStore(); const data=ref<Page<Role>>({items:[],total:0,page:0,size:20})
const queryText=(value:unknown)=>typeof value==='string'?value:''
const keyword=ref(queryText(route.query.keyword)); const status=ref(queryText(route.query.status)||undefined); const loading=ref(false); const error=ref('')
const columns=[{title:'角色编码',dataIndex:'roleCode',sorter:(a:Role,b:Role)=>a.roleCode.localeCompare(b.roleCode)},{title:'角色名称',dataIndex:'roleName',sorter:(a:Role,b:Role)=>a.roleName.localeCompare(b.roleName)},{title:'权限数',key:'permissions',sorter:(a:Role,b:Role)=>a.permissionCodes.length-b.permissionCodes.length},{title:'状态',key:'status',sorter:(a:Role,b:Role)=>a.status.localeCompare(b.status)},{title:'操作',key:'actions'}]
async function load(page=Number(route.query.page??0)){loading.value=true;error.value='';try{await router.replace({query:{keyword:keyword.value||undefined,status:status.value,page:page||undefined}});data.value=await api<Page<Role>>({url:'/roles',params:{page,size:20,keyword:keyword.value||undefined,status:status.value}})}catch(cause){error.value=errorMessage(cause)}finally{loading.value=false}}
function reset(){keyword.value='';status.value=undefined;void load()} onMounted(()=>load())
</script>
<template><main data-ui-template="T1" class="admin-page t1-query-list"><header class="admin-page-header"><div><h1>角色与权限</h1></div><a-button v-if="auth.can('iam:role:create')" type="primary" @click="router.push({path:'/admin/roles/create',query:route.query})">新增角色</a-button></header>
<a-card title="查询条件" class="query-card"><form class="query-form" @submit.prevent="load(0)"><label><span class="form-field-label">编码或名称</span><a-input v-model:value="keyword" allow-clear /></label><label><span class="form-field-label">状态</span><a-select show-search option-filter-prop="children" v-model:value="status" allow-clear style="width:160px"><a-select-option value="ACTIVE">启用</a-select-option><a-select-option value="INACTIVE">停用</a-select-option></a-select></label><a-space><a-button type="primary" html-type="submit">查询</a-button><a-button @click="reset">重置</a-button></a-space></form></a-card>
<a-alert v-if="error" type="error" :message="error" show-icon /><a-card title="角色列表" class="result-card"><a-table :columns="columns" :data-source="data.items" row-key="id" :loading="loading" :scroll="{x:900}" :pagination="false"><template #bodyCell="{column,record}"><template v-if="column.key==='permissions'">{{record.permissionCodes.length}}</template><template v-else-if="column.key==='status'"><a-tag :color="record.status==='ACTIVE'?'success':'default'">{{record.status==='ACTIVE'?'启用':'停用'}}</a-tag></template><template v-else-if="column.key==='actions'"><a-button type="link" @click="router.push({path:`/admin/roles/${record.id}`,query:route.query})">查看</a-button><a-button v-if="auth.can('iam:role:update')" type="link" @click="router.push({path:`/admin/roles/${record.id}/edit`,query:route.query})">编辑</a-button></template></template></a-table><div class="table-footer"><span>共 {{data.total}} 条</span><a-pagination :current="data.page+1" :page-size="data.size" :total="data.total" :show-size-changer="false" @change="(p:number)=>load(p-1)" /></div></a-card></main></template>
