<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, errorMessage, idempotencyKey, type Page, type Permission, type Role } from '../../api/http'
import { useAuthStore } from '../../stores/auth'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const mode=computed(()=>String(route.meta.mode));const isCreate=computed(()=>mode.value==='create');const readonly=computed(()=>mode.value==='view')
const permissionGroups=computed(()=>{const groups=new Map<string,Permission[]>();for(const p of permissions.value){const key=p.permissionCode.split(':')[0]??'other';groups.set(key,[...(groups.get(key)??[]),p])}const names:Record<string,string>={iam:'身份与权限',master:'基础主数据',process:'产品与工艺',production:'生产管理',mes:'生产执行',wms:'仓储管理',qms:'质量管理',qa:'质量决定',ebr:'电子批记录',audit:'审计追踪',trace:'完整追溯',integration:'集成运维',balance:'物料平衡'};return [...groups].map(([key,items])=>({key,title:names[key]??'其他权限',items}))})
const role=ref<Role|null>(null);const permissions=ref<Permission[]>([]);const roleCode=ref('');const roleName=ref('');const status=ref<'ACTIVE'|'INACTIVE'>('ACTIVE');const selected=ref<string[]>([]);const busy=ref(false);const error=ref('');const notice=ref('')
async function load(){try{if(!isCreate.value){role.value=await api<Role>({url:`/roles/${route.params.id}`});roleCode.value=role.value.roleCode;roleName.value=role.value.roleName;status.value=role.value.status;selected.value=[...role.value.permissionCodes]}
if(auth.can('iam:permission:view'))permissions.value=(await api<Page<Permission>>({url:'/permissions',params:{page:0,size:100,status:'ACTIVE'}})).items}catch(cause){error.value=errorMessage(cause)}}
async function save(){busy.value=true;error.value='';notice.value='';try{if(isCreate.value){role.value=await api<Role>({method:'POST',url:'/roles',headers:{'Idempotency-Key':idempotencyKey()},data:{roleCode:roleCode.value.trim(),roleName:roleName.value.trim(),reason:'IAM role administration'}})}else if(role.value){role.value=await api<Role>({method:'PUT',url:`/roles/${role.value.id}`,headers:{'Idempotency-Key':idempotencyKey(),'If-Match':`"${role.value.version}"`},data:{roleName:roleName.value.trim(),status:status.value,reason:'IAM role administration'}})}
if(role.value&&auth.can('iam:role:update')&&auth.can('iam:permission:view'))role.value=await api<Role>({method:'POST',url:`/roles/${role.value.id}/permissions`,headers:{'Idempotency-Key':idempotencyKey(),'If-Match':`"${role.value.version}"`},data:{permissionCodes:selected.value,reason:'IAM permission assignment'}});notice.value='角色已保存';if(isCreate.value&&role.value)await router.replace({path:`/admin/roles/${role.value.id}/edit`,query:route.query})}catch(cause){error.value=errorMessage(cause)}finally{busy.value=false}}
onMounted(load)
</script>
<template><main :data-ui-template="readonly?'T3':'T2'" class="admin-page"><header class="admin-page-header"><div><a-button type="link" @click="router.push({path:'/admin/roles',query:route.query})">← 返回角色列表</a-button><h1>{{isCreate?'新增角色':readonly?'角色详情':'编辑角色'}}</h1></div><a-button v-if="readonly&&auth.can('iam:role:update')&&role" type="primary" @click="router.push({path:`/admin/roles/${role.id}/edit`,query:route.query})">编辑</a-button></header>
<a-alert v-if="error" type="error" :message="error" show-icon/><a-alert v-if="notice" type="success" :message="notice" show-icon/><a-card title="角色信息" class="form-section"><a-form layout="horizontal" class="detail-form"><a-form-item label="角色编码"><a-input v-model:value="roleCode" :disabled="readonly||!isCreate"/></a-form-item><a-form-item label="角色名称"><a-input v-model:value="roleName" :disabled="readonly"/></a-form-item><a-form-item label="状态"><a-select v-model:value="status" :disabled="readonly||isCreate"><a-select-option value="ACTIVE">启用</a-select-option><a-select-option value="INACTIVE">停用</a-select-option></a-select></a-form-item></a-form></a-card>
<a-card title="权限与菜单" class="form-section"><p class="muted">MENU 权限决定导航可见性，ACTION 权限决定按钮和操作能力。</p><a-checkbox-group v-model:value="selected" :disabled="readonly||!auth.can('iam:permission:view')" class="permission-grid"><section v-for="group in permissionGroups" :key="group.key" class="permission-domain"><h3>{{group.title}}</h3><label v-for="permission in group.items" :key="permission.id" class="permission-row"><a-checkbox :value="permission.permissionCode"/><span><strong>{{permission.permissionName}}</strong><small>{{permission.permissionCode}} · {{permission.permissionType}}</small></span></label></section></a-checkbox-group>
<a-space v-if="!readonly"><a-button type="primary" :loading="busy" @click="save">保存</a-button><a-button @click="router.push({path:'/admin/roles',query:route.query})">取消</a-button></a-space></a-card></main></template>

<style scoped>.permission-domain{grid-column:1/-1;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.permission-domain h3{grid-column:1/-1;font-size:15px;margin:8px 0}.permission-domain label{min-width:0}@media(max-width:900px){.permission-domain{grid-template-columns:1fr}}</style>
