package com.hospital.mes.reporting.application;
import com.hospital.mes.reporting.infrastructure.*;import com.hospital.mes.masterdata.application.MasterMutation;import com.hospital.mes.audit.application.CurrentPlatformContext;import com.hospital.mes.common.exception.PermissionException;import com.fasterxml.jackson.databind.*;import org.junit.jupiter.api.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import static org.mockito.AdditionalMatchers.aryEq;
class EditorCallbackTest {
 static final String TEST_ONLY_SECRET="not-a-deployment-key-fixture-only-0123456789";
 PrintEditorSessionMapper sessions;PrintTemplateVersionMapper templates;PrintService printing;EditorActorPort actors;PrintEditorService editor;EditorJwt jwt;PrintEditorSession session;String capability;ObjectMapper json=new ObjectMapper();com.sun.net.httpserver.HttpServer server;String origin;byte[] source;
 @BeforeEach void setup()throws Exception {source=InspectionSampleTemplate.create();server=com.sun.net.httpserver.HttpServer.create(new java.net.InetSocketAddress("127.0.0.1",0),0);server.createContext("/cache/files/source.docx",exchange->{exchange.sendResponseHeaders(200,source.length);try(var out=exchange.getResponseBody()){out.write(source);}});server.start();origin="http://127.0.0.1:"+server.getAddress().getPort();sessions=mock(PrintEditorSessionMapper.class);templates=mock(PrintTemplateVersionMapper.class);printing=mock(PrintService.class);actors=mock(EditorActorPort.class);jwt=new EditorJwt(TEST_ONLY_SECRET,Clock.systemUTC());session=new PrintEditorSession();session.setId("session-1");session.setOrgId(1L);session.setActorId(2L);session.setLoginSessionId("iam-session");session.setSourceTemplateVersionId(10L);session.setVersionNo(0L);session.setExpiresAt(LocalDateTime.now(ZoneOffset.UTC).plusMinutes(5));when(sessions.selectOne(any())).thenReturn(session);when(actors.requireActiveEditor(1,2,"iam-session")).thenReturn(new CurrentPlatformContext(1,2,Set.of("QA"),Set.of("print:template:manage","print:template:view"),"iam-session","request"));capability=jwt.sign(Map.of("sid",session.getId(),"aud","mes-editor-transfer","exp",Instant.now().plusSeconds(300).getEpochSecond()));editor=new PrintEditorService(sessions,templates,mock(MasterMutation.class),printing,actors,TEST_ONLY_SECRET,origin,"http://localhost:5173");}
 @AfterEach void stop(){server.stop(0);}
 Map<String,Object> body(){return Map.of("key","mes-session-1","status",6,"url",origin+"/cache/files/source.docx","users",List.of("2"),"filetype","docx");}
 @Test void signedCallbackDownloadsRealDocxAndAppendsDraftWithoutOverwritingSource(){var t=new PrintTemplateVersion();t.setId(10L);t.setOrgId(1L);t.setTemplateCode("QC");t.setTemplateName("报告");t.setBusinessType("INSPECTION_REPORT");t.setPrintType("DOCUMENT");when(templates.selectOne(any())).thenReturn(t);when(printing.uploadFromEditor(any(),eq("QC"),eq("报告"),eq("INSPECTION_REPORT"),eq("DOCUMENT"),aryEq(source),anyString())).thenReturn(json.createObjectNode().put("id","11"));when(sessions.update(isNull(),any())).thenReturn(1);var body=body();assertEquals(Map.of("error",0),editor.callback(session.getId(),capability,"Bearer "+jwt.sign(body),json.valueToTree(body)));verify(printing).uploadFromEditor(any(),eq("QC"),eq("报告"),eq("INSPECTION_REPORT"),eq("DOCUMENT"),aryEq(source),anyString());verify(templates,never()).update(any(),any());}
 @Test void replayOfSameContentAcknowledgesWithoutAnotherVersion(){session.setLastContentHash(PrintService.hash(source));var body=body();assertEquals(Map.of("error",0),editor.callback(session.getId(),capability,"Bearer "+jwt.sign(body),json.valueToTree(body)));verifyNoInteractions(printing,templates);verify(sessions,never()).update(any(),any());}
 @Test void tamperedCallbackActorsRejectedBeforeDownloadOrMutation(){var signed=body();var changed=new LinkedHashMap<>(signed);changed.put("users",List.of("999"));assertThrows(PermissionException.class,()->editor.callback(session.getId(),capability,"Bearer "+jwt.sign(signed),json.valueToTree(changed)));verifyNoInteractions(printing,templates);}
 @Test void revokedIamSessionAndUnsignedCallbackCannotSave(){doThrow(new PermissionException("EDITOR_SESSION_REVOKED","revoked")).when(actors).requireActiveEditor(1,2,"iam-session");assertThrows(PermissionException.class,()->editor.callback(session.getId(),capability,null,json.valueToTree(body())));verifyNoInteractions(printing,templates);}
}
