<script setup lang="ts">
import {ref,watch} from 'vue'
import {useRouter,useRoute,onBeforeRouteLeave} from 'vue-router'
import {api,type Page} from '../../api/http'
import {useControlledRequest} from '../../api/controlled'
import ReadReference from '../master/ReadReference.vue'
import {useAuthStore} from '../../stores/auth'
import ProcessLookup from '../process/ProcessLookup.vue'
const route=useRoute(),router=useRouter(),control=useControlledRequest(),auth=useAuthStore(),lotFacts=ref<Record<string,any>>({}),options=ref<Record<string,any>[]>([]),issueId=ref(String(route.query.issueId??'')),issue=ref<Record<string,any>|null>(null),history=ref<Record<string,any>[]>([]),itemId=ref(''),quantity=ref(''),unitId=ref(''),reason=ref(''),saved=ref(false)
async function search(keyword=''){try{options.value=(await api<Page<Record<string,any>>>({url:'/material-issues',params:{status:'CONFIRMED',keyword,size:100}})).items}catch(e){await control.failure(e)}}
async function load(){control.clear();issue.value=null;history.value=[];itemId.value='';if(!issueId.value)return;control.busy.value=true;try{issue.value=await api({url:`/material-issues/${issueId.value}`});lotFacts.value={};if(auth.can('wms:inventory:view'))await Promise.all([...new Set<string>(issue.value!.items.map((i:Record<string,any>)=>String(i.materialLotId)))].map(async id=>{try{lotFacts.value[id]=await api({url:`/wms/material-lots/${id}`})}catch{/* Bound identity remains visible if its optional lookup is unavailable. */}}));let page=0,total=0;do{const data=await api<Page<Record<string,any>>>({url:'/material-returns',params:{issueId:issueId.value,page:page++,size:100}});history.value.push(...data.items);total=data.total}while(history.value.length<total)}catch(e){issue.value=null;await control.failure(e)}finally{control.busy.value=false}}
function previous(id:string){return history.value.find(r=>r.issueItemId===id)}
watch(issueId,load,{immediate:true});watch(itemId,id=>{unitId.value=issue.value?.items.find((i:Record<string,any>)=>i.id===id)?.unitId??'';quantity.value=''})
async function submit(){control.busy.value=true;control.error.value='';try{if(!reason.value.trim()||!itemId.value||!quantity.value||!unitId.value)throw Error('请选择出库明细并填写退料数量、单位和原因');const source=issue.value!;await control.mutate(`/material-issues/${source.id}/returns`,'POST',{versionNo:source.versionNo,reason:reason.value,items:[{issueItemId:itemId.value,quantity:quantity.value,unitId:unitId.value}]},source.versionNo);saved.value=true;await router.push({path:'/wms/returns',query:{issueId:source.id}})}catch(e){await control.failure(e)}finally{control.busy.value=false}}
onBeforeRouteLeave(()=>saved.value||(!quantity.value&&!reason.value)||window.confirm('离开将放弃未提交的退料输入，是否继续？'))
void search()
</script>
<template><main data-ui-template="T2" class="admin-page master-page"><header class="admin-page-header"><div><a-button type="link" @click="router.push('/wms/returns')">← 返回退料管理</a-button><h1>登记退料</h1><p>关联原出库单 · 沿用既有数量、版本与生产耗用校验</p></div></header><a-alert v-if="control.error.value" type="error" :message="control.error.value" show-icon/><a-alert v-if="control.conflict.value" type="warning" message="出库记录已变化，退料输入已保留，请核对并重新加载。"><template #action><a-button @click="load">重新加载</a-button></template></a-alert>
<a-card title="原出库来源" class="form-section"><div class="master-form"><label><span class="form-field-label">原出库单</span><a-select v-model:value="issueId" aria-label="原出库单" show-search :filter-option="false" @search="search"><a-select-option v-for="o in options" :key="o.id" :value="o.id">{{o.issueNo}} · {{o.batchNo}} · {{o.productName}}</a-select-option></a-select></label><label><span class="form-field-label">生产批 / 产品</span><span>{{issue?`${issue.batchNo} · ${issue.productName}`:'请先选择原出库单'}}</span></label></div></a-card>
<a-card v-if="issue" title="出库明细与退料数量" class="form-section"><a-table :data-source="issue.items" row-key="id" :pagination="false" :columns="[{title:'原出库明细',dataIndex:'id'},{title:'物料',key:'material'},{title:'物料批次',key:'lot'},{title:'原出库量',dataIndex:'issuedQty'},{title:'已退 / 剩余量（原单位）',key:'returned'}]"><template #bodyCell="{column,record}"><ReadReference v-if="column.key==='material'" field="materialId" :value="lotFacts[record.materialLotId]?.materialId" :name="lotFacts[record.materialLotId]?.materialSnapshot?.materialName"/><ReadReference v-else-if="column.key==='lot'" field="materialLotId" :value="record.materialLotId"/><template v-if="column.key==='returned'">{{previous(record.id)?.returnedQty||'0'}} / {{previous(record.id)?.remainingReturnQty||record.issuedQty}} · <ReadReference field="unitId" :value="record.unitId" :name="previous(record.id)?.issuedUnitName"/></template></template></a-table><div class="master-form"><label><span class="form-field-label">原出库明细</span><a-select v-model:value="itemId" aria-label="原出库明细"><a-select-option v-for="i in issue.items" :key="i.id" :value="i.id">{{i.id}} · {{lotFacts[i.materialLotId]?.lotNo||`物料批次引用 ${i.materialLotId}`}}</a-select-option></a-select></label><label><span class="form-field-label">本次退料量</span><input v-model="quantity" class="master-native-input" aria-label="本次退料量"/></label><label><span class="form-field-label">退料单位</span><ProcessLookup v-model="unitId" resource="units" label="退料单位"/></label><label class="form-full-row"><span class="form-field-label">退料原因</span><textarea v-model="reason" class="master-native-input" aria-label="退料原因" maxlength="1000"/></label></div><a-button type="primary" :loading="control.busy.value" :disabled="control.conflict.value||issue.status!=='CONFIRMED'||!issue.allowedActions?.includes('RETURN')" @click="submit">提交退料</a-button></a-card></main></template>

<style scoped>.master-form :deep(.process-lookup){width:100%;min-width:0}.master-form :deep(.process-lookup .ant-select){width:100%}</style>
