<script setup lang="ts">
import {ref,computed,watch} from 'vue'
import {useRoute,useRouter,onBeforeRouteLeave} from 'vue-router'
import {api} from '../../api/http'
import {useControlledRequest} from '../../api/controlled'
import {useAuthStore} from '../../stores/auth'
import IncomingReferencePicker from '../quality/IncomingReferencePicker.vue'
import ReadReference from '../master/ReadReference.vue'
import MaterialRequestPicker from './MaterialRequestPicker.vue'
import ProcessLookup from '../process/ProcessLookup.vue'
interface Item{materialRequestItemId?:string;materialName?:string;id?:string;materialLotId:string;formulaItemId:string;issuedQty:string;unitId:string}
interface Issue{materialRequestId?:string;materialRequestNo?:string;batchNo?:string;productName?:string;id:string;mainBatchId:string;issueNo:string;status:string;versionNo:number;issuedAt?:string;items:Item[];returns:Array<{id:string;issueItemId:string;quantity:string;unitId:string;reason:string;returnedBy:string;returnedAt:string}>}
const route=useRoute(),router=useRouter(),auth=useAuthStore(),request=useControlledRequest(),{error,conflict,busy}=request,record=ref<Issue|null>(null),mainBatchId=ref(''),issueNo=ref(''),items=ref<Item[]>([]),reason=ref(''),returnOpen=ref(false),returnItemId=ref(''),returnQuantity=ref(''),returnUnitId=ref(''),baseline=ref(''),materialRequestId=ref(''),linkedRequest=ref<Record<string,any>|null>(null)
const batchContext=ref<Record<string,unknown>>({}),formulaItems=computed<Record<string,unknown>[]>(()=>{const snapshot=(batchContext.value.processSnapshot as {snapshot?:{process?:{formula?:{items?:Record<string,unknown>[]}};materials?:Record<string,unknown>[]}}|undefined)?.snapshot;return (snapshot?.process?.formula?.items??[]).map(item=>({...item,materialName:item.materialName??snapshot?.materials?.find(m=>String(m.id??m.materialId)===String(item.materialId))?.materialName}))})
let batchTicket=0
watch(mainBatchId,async id=>{const ticket=++batchTicket;batchContext.value={};if(!id||!auth.can('production:batch:view'))return;try{const row=await api<Record<string,unknown>>({url:`/main-batches/${id}`});if(ticket===batchTicket)batchContext.value=row}catch{/* Preserve the bound reference if upstream read is unavailable. */}})
const create=computed(()=>route.meta.mode==='create'),edit=computed(()=>create.value||route.meta.mode==='edit'),editable=computed(()=>edit.value&&(!record.value||record.value.status==='DRAFT')&&!busy.value&&!conflict.value)
function state(){return JSON.stringify({materialRequestId:materialRequestId.value,mainBatchId:mainBatchId.value,issueNo:issueNo.value,items:items.value})}
async function load(){request.clear();busy.value=true;try{if(create.value){record.value=null;materialRequestId.value=String(route.query.materialRequestId??'');items.value=[{materialLotId:'',formulaItemId:'',issuedQty:'',unitId:''}]}else{record.value=await api<Issue>({url:`/material-issues/${route.params.id}`});materialRequestId.value=record.value.materialRequestId??'';mainBatchId.value=record.value.mainBatchId;issueNo.value=record.value.issueNo;items.value=record.value.items.map(i=>({...i}))}if(create.value&&materialRequestId.value)chooseRequest(await api({url:`/material-requests/${materialRequestId.value}`}));baseline.value=state()}catch(e){await request.failure(e)}finally{busy.value=false}}
async function save(action=''){busy.value=true;error.value='';try{if(!reason.value.trim())throw Error('请填写操作原因');const r=record.value;const body=action==='confirm'?{versionNo:r!.versionNo,reason:reason.value}:action==='returns'?{versionNo:r!.versionNo,reason:reason.value,items:[{issueItemId:returnItemId.value,quantity:returnQuantity.value,unitId:returnUnitId.value}]}:{...(materialRequestId.value?{materialRequestId:materialRequestId.value}:{}),mainBatchId:mainBatchId.value,issueNo:issueNo.value,items:items.value.map(({materialLotId,formulaItemId,issuedQty,unitId,materialRequestItemId})=>({materialLotId,formulaItemId,issuedQty,unitId,...(materialRequestItemId?{materialRequestItemId}:{})})),reason:reason.value,...(r?{versionNo:r.versionNo}:{})};const result=await request.mutate<Issue>(r?`/material-issues/${r.id}${action?'/'+action:''}`:'/material-issues',r&&!action?'PUT':'POST',body,r?.versionNo);baseline.value=state();returnOpen.value=false;reason.value='';await router.replace({path:`/wms/issues/${result.id}`,query:route.query});await load()}catch(e){await request.failure(e)}finally{busy.value=false}}
function splitAllocation(index:number){const item=items.value[index];if(item)items.value.splice(index+1,0,{...item,id:undefined,materialLotId:'',issuedQty:''})}
function addRequestAllocation(){const line=linkedRequest.value?.items.find((i:Record<string,any>)=>!/^0(?:\.0+)?$/.test(String(i.remainingQty)));if(line)items.value.push({materialRequestItemId:line.id,materialName:line.materialName,materialLotId:'',formulaItemId:line.formulaItemId,issuedQty:'',unitId:line.unitId})}
function selectRequestLine(item:Item){const line=linkedRequest.value?.items.find((i:Record<string,any>)=>i.id===item.materialRequestItemId);if(line){item.formulaItemId=line.formulaItemId;item.materialName=line.materialName;item.unitId=line.unitId;item.materialLotId='';item.issuedQty=''}}
function chooseRequest(r:Record<string,any>){linkedRequest.value=r;materialRequestId.value=r.id;mainBatchId.value=r.mainBatchId;items.value=r.items.filter((i:Record<string,any>)=>!/^0(?:\.0+)?$/.test(String(i.remainingQty))).map((i:Record<string,any>)=>({materialRequestItemId:i.id,materialName:i.materialName,materialLotId:'',formulaItemId:i.formulaItemId,issuedQty:i.remainingQty,unitId:i.unitId}))}
watch(materialRequestId,id=>{if(!id&&create.value){linkedRequest.value=null;items.value=[{materialLotId:'',formulaItemId:'',issuedQty:'',unitId:''}]}})
watch(returnItemId,id=>{returnUnitId.value=record.value?.items.find(i=>i.id===id)?.unitId??''})
onBeforeRouteLeave(()=>!edit.value||baseline.value===state()||window.confirm('离开将放弃未保存的出库输入，是否继续？'))
watch(()=>route.fullPath,load,{immediate:true})
</script>
<template><main :data-ui-template="edit?'T2':'T3'" class="admin-page master-page"><header class="admin-page-header"><div><a-button type="link" @click="router.push({path:'/wms/issues',query:route.query})">← 返回出库列表</a-button><h1>{{create?'新增出库单':edit?'编辑出库单':'出库单详情'}}</h1><p v-if="record">{{record.issueNo}} · {{record.status==='CONFIRMED'?'已确认':record.status==='DRAFT'?'草稿':'已关闭'}}</p></div><a-space><a-button v-if="record?.status==='DRAFT'&&!edit&&auth.can('wms:issue:update')" @click="router.push({path:`/wms/issues/${record.id}/edit`,query:route.query})">编辑</a-button><a-button v-if="record?.status==='CONFIRMED'&&auth.can('wms:issue:return')" @click="returnOpen=true">登记退料</a-button><a-button v-if="record&&auth.can('audit:view')" @click="router.push({path:'/audit',query:{objectType:'MaterialIssue',objectId:record.id}})">审计追踪</a-button></a-space></header><a-alert v-if="error" type="error" :message="error" show-icon/><a-alert v-if="conflict" type="warning" message="记录已变化，输入已保留。请核对后重新加载。"><template #action><a-button @click="load">重新加载</a-button></template></a-alert>
<a-card title="出库信息" class="form-section"><div class="master-form"><label><span class="form-field-label">领料申请</span><MaterialRequestPicker v-if="editable&&!record" v-model="materialRequestId" @selected="chooseRequest"/><span v-else>{{record?.materialRequestNo||linkedRequest?.requestNo||'历史兼容记录：未关联申请'}}</span></label><label><span class="form-field-label">产品</span><span>{{record?.productName||linkedRequest?.productName||'由生产批确定'}}</span></label><label><span class="form-field-label">出库单号</span><input v-model="issueNo" class="master-native-input" aria-label="出库单号" :disabled="!editable"/></label><label><span class="form-field-label">生产批</span><ReadReference v-if="!editable||record||materialRequestId" field="mainBatchId" :value="mainBatchId" :name="record?.batchNo||linkedRequest?.batchNo"/><input v-else-if="!auth.can('production:batch:view')" v-model="mainBatchId" aria-label="生产批" class="master-native-input"/><IncomingReferencePicker v-else v-model="mainBatchId" field="mainBatchId" :context="{}" required/></label></div></a-card>
<a-card v-for="(item,index) in items" :key="index" :title="`出库明细 ${index+1}`" class="form-section"><div class="master-form"><label><span class="form-field-label">物料批次</span><ReadReference v-if="!editable" field="materialLotId" :value="item.materialLotId"/><input v-else-if="!auth.can('wms:inventory:view')" v-model="item.materialLotId" :aria-label="`物料批次 ${index+1}`" class="master-native-input"/><IncomingReferencePicker v-else v-model="item.materialLotId" field="materialLotId" :input-label="`物料批次 ${index+1}`" :context="{}" required/></label><label><span class="form-field-label">处方明细</span><select v-if="create&&editable&&materialRequestId" v-model="item.materialRequestItemId" class="master-native-input" :aria-label="`申请明细 ${index+1}`" @change="selectRequestLine(item)"><option v-for="line in linkedRequest?.items" :key="line.id" :value="line.id">{{line.materialName}} · 剩余 {{line.remainingQty}} {{line.unitName}}</option></select><span v-else-if="!editable||materialRequestId" class="master-read-value">{{item.materialName??formulaItems.find(f=>String(f.formulaItemId)===item.formulaItemId)?.materialName??`来源引用 ${item.formulaItemId}`}}</span><input v-else-if="!auth.can('production:batch:view')" v-model="item.formulaItemId" :aria-label="`处方明细 ${index+1}`" class="master-native-input"/><IncomingReferencePicker v-else v-model="item.formulaItemId" field="formulaItemId" :input-label="`处方明细 ${index+1}`" :context="{formulaItems}" required/></label><label><span class="form-field-label">出库数量</span><input v-model="item.issuedQty" class="master-native-input" :aria-label="`出库数量 ${index+1}`" :disabled="!editable"/></label><label><span class="form-field-label">单位</span><ProcessLookup v-model="item.unitId" resource="units" :label="`出库单位 ${index+1}`" :disabled="!editable"/></label></div><a-space v-if="create&&editable&&materialRequestId"><a-button :aria-label="`拆分批次分配 ${index+1}`" @click="splitAllocation(index)">拆分批次分配</a-button><a-button :aria-label="`移除本次出库明细 ${index+1}`" :disabled="items.length<=1" @click="items.splice(index,1)">移除本次明细</a-button></a-space></a-card>
<a-button v-if="create&&editable&&materialRequestId" @click="addRequestAllocation">添加申请明细分配</a-button><a-button v-if="editable&&!materialRequestId" @click="items.push({materialLotId:'',formulaItemId:'',issuedQty:'',unitId:''})">添加出库明细</a-button>
<a-card v-if="record?.returns?.length" title="退料记录" class="form-section"><a-table :data-source="record.returns" row-key="id" :pagination="false" :scroll="{x:800}" :columns="[{title:'明细',dataIndex:'issueItemId'},{title:'退料数量',dataIndex:'quantity'},{title:'单位',dataIndex:'unitId'},{title:'原因',dataIndex:'reason'},{title:'操作人',dataIndex:'returnedBy'},{title:'时间',dataIndex:'returnedAt'}]"/></a-card>
<a-card v-if="edit||returnOpen||(record?.status==='DRAFT'&&auth.can('wms:issue:confirm'))" title="受控操作" class="form-section"><div class="master-form"><template v-if="returnOpen"><label><span class="form-field-label">退料明细</span><select v-model="returnItemId" class="master-native-input" aria-label="退料明细"><option value="">请选择</option><option v-for="item in record?.items" :key="item.id" :value="item.id">{{item.id}} · 物料批 {{item.materialLotId}}</option></select></label><label><span class="form-field-label">退料数量</span><input v-model="returnQuantity" class="master-native-input" aria-label="退料数量"/></label><label><span class="form-field-label">退料单位</span><ProcessLookup v-model="returnUnitId" resource="units" label="退料单位"/></label></template><label class="form-full-row"><span class="form-field-label">操作原因</span><textarea v-model="reason" class="master-native-input" aria-label="操作原因" maxlength="1000"/></label></div><a-space><a-button v-if="edit" type="primary" :disabled="!editable" :loading="busy" @click="save()">保存出库单</a-button><a-button v-if="record?.status==='DRAFT'&&!edit&&auth.can('wms:issue:confirm')" type="primary" :loading="busy" :disabled="conflict" @click="save('confirm')">确认出库</a-button><a-button v-if="returnOpen" type="primary" :loading="busy" :disabled="conflict" @click="save('returns')">提交退料</a-button></a-space></a-card></main></template>
