<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,type Page} from '../../api/http'
import {useControlledRequest} from '../../api/controlled'
import {useAuthStore} from '../../stores/auth'
import {statusLabels} from './model'
import type {MaterialLot,Inventory} from './types'
import WmsLookup from './WmsLookup.vue'
import MaterialLotLineage from './MaterialLotLineage.vue'
import FunctionalQualityActions from '../quality/FunctionalQualityActions.vue'
import ProcessLookup from '../process/ProcessLookup.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),request=useControlledRequest(),{error,conflict,busy}=request,record=ref<MaterialLot|null>(null),stock=ref<Page<Inventory>>({items:[],total:0,page:0,size:20}),operationOpen=ref(false),mode=ref<'MOVE'|'ADJUST'>('MOVE'),locationId=ref(''),containerId=ref(''),toLocationId=ref(''),toContainerId=ref(''),unitId=ref(''),quantity=ref(''),reason=ref(''),notice=ref('')
async function load(page=0){request.clear();try{record.value=await api({url:`/wms/material-lots/${route.params.id}`});stock.value=await api({url:'/inventory',params:{materialLotId:route.params.id,page,size:20}})}catch(e){await request.failure(e)}}
function can(action:string){return !!record.value?.allowedActions?.includes(action)&&auth.can(`wms:inventory:${action.toLowerCase()}`)}
function selectStock(row:Inventory,action:'MOVE'|'ADJUST'){operationOpen.value=true;mode.value=action;locationId.value=row.locationId??'';containerId.value=row.containerId??'';unitId.value=row.unitId??'';quantity.value='';notice.value=''}
async function save(){busy.value=true;error.value='';notice.value='';try{if(!reason.value.trim())throw Error('请填写操作原因');const r=record.value!;const body={materialLotId:r.id,versionNo:r.versionNo,unitId:unitId.value,reason:reason.value,...(mode.value==='MOVE'?{fromLocationId:locationId.value,...(containerId.value?{fromContainerId:containerId.value}:{}),toLocationId:toLocationId.value,...(toContainerId.value?{toContainerId:toContainerId.value}:{}),quantity:quantity.value}:{locationId:locationId.value,...(containerId.value?{containerId:containerId.value}:{}),deltaQty:quantity.value})};await request.mutate(`/inventory/${mode.value.toLowerCase()}`,'POST',body,r.versionNo);await load();notice.value=mode.value==='MOVE'?'移库已记录':'库存调整已记录';quantity.value='';reason.value=''}catch(e){await request.failure(e)}finally{busy.value=false}}
onMounted(()=>load())
</script>
<!-- UI Template: T4 Aggregate Detail; lineage is read-only from existing trace source. -->
<template><main class="admin-page master-page lot-page"><header class="admin-page-header"><div><a-button type="link" @click="router.back()">← 返回</a-button><h1>物料批详情</h1><p>{{record?.lotNo}} · {{record?.materialSnapshot?.materialName}}</p></div><a-space wrap><a-button v-if="record&&auth.can('qa:material-release:view')" @click="router.push(`/qa/material-lots/${record.id}/review`)">物料放行审查</a-button><a-button v-if="record&&auth.can('trace:view')" @click="router.push({path:'/trace',query:{materialLotId:record.id}})">完整追溯</a-button><a-button v-if="record&&auth.can('audit:view')" @click="router.push({path:'/audit',query:{objectType:'MaterialLot',objectId:record.id}})">审计追踪</a-button></a-space></header><a-alert v-if="error" type="error" :message="error"/><a-alert v-if="conflict" type="warning" message="记录已变化，输入已保留，请重新加载后继续。"><template #action><a-button @click="load()">重新加载</a-button></template></a-alert><a-alert v-if="notice" type="success" :message="notice"/>
<a-card v-if="record" class="form-section"><a-tabs><a-tab-pane key="overview" tab="概览"><div class="master-form"><label v-for="[key,label] in [['lotNo','物料批号'],['supplierLotNo','供应商批号'],['manufactureDate','生产日期'],['expiryDate','有效期至'],['retestDate','复验日期'],['receiptItemId','收货明细 ID']]" :key="key"><span class="form-field-label">{{label}}</span><span class="master-read-value">{{(record as any)[key!]||'—'}}</span></label><label><span class="form-field-label">质量状态</span><span class="master-read-value">{{statusLabels[record.qualityStatus??'']||record.qualityStatus}}</span></label><label><span class="form-field-label">库存状态</span><span class="master-read-value">{{statusLabels[record.inventoryStatus??'']||record.inventoryStatus}}</span></label><label><span class="form-field-label">入库必验快照</span><span class="master-read-value">{{record.requiresIncomingInspectionSnapshot?'是':'否'}}</span></label></div><a-alert type="info" message="生产使用资格由物料质量放行、库存状态与冻结、有效期/复验规则及生产使用场景共同控制，以服务端资格校验为准。"/></a-tab-pane>
<a-tab-pane key="receiving" tab="收货"><MaterialLotLineage :lot-id="record.id!" :types="['RECEIPT','RECEIPT_ITEM']"/></a-tab-pane>
<a-tab-pane key="request" tab="请验"><MaterialLotLineage :lot-id="record.id!" :types="['INSPECTION_REQUEST']"/></a-tab-pane>
<a-tab-pane key="sampling" tab="取样"><MaterialLotLineage :lot-id="record.id!" :types="['SAMPLING_TASK','SAMPLING_DETAIL']"/></a-tab-pane>
<a-tab-pane key="samples" tab="样品"><MaterialLotLineage :lot-id="record.id!" :types="['SAMPLE']"/></a-tab-pane>
<a-tab-pane key="inspection" tab="检验"><MaterialLotLineage :lot-id="record.id!" :types="['INSPECTION_TASK','INSPECTION_ITEM','TEST_EXECUTION','RESULT_REVISION']"/></a-tab-pane>
<a-tab-pane key="reports" tab="检验报告"><MaterialLotLineage :lot-id="record.id!" :types="['REPORT']"/></a-tab-pane>
<a-tab-pane key="release" tab="质量放行"><MaterialLotLineage :lot-id="record.id!" :types="['RELEASE_DECISION','INVESTIGATION']"/></a-tab-pane>
<a-tab-pane key="stock" tab="库存"><div class="table-scroll"><table><thead><tr><th>库位 ID</th><th>容器 ID</th><th>数量</th><th>单位 ID</th><th>操作</th></tr></thead><tbody><tr v-for="(row,i) in stock.items" :key="i"><td>{{row.locationId}}</td><td>{{row.containerId||'—'}}</td><td>{{row.quantity}}</td><td>{{row.unitId}}</td><td><a-button v-if="can('MOVE')" type="link" aria-label="移库" @click="selectStock(row,'MOVE')">移库</a-button><a-button v-if="can('ADJUST')" type="link" aria-label="调整" @click="selectStock(row,'ADJUST')">调整</a-button></td></tr></tbody></table></div><a-empty v-if="!stock.total" description="暂无库存记录"/><a-button v-if="can('ADJUST')" @click="operationOpen=true;mode='ADJUST';locationId='';containerId='';unitId=String(record?.materialSnapshot?.baseUnitId??'');quantity=''">新增库存调整</a-button><div class="table-footer"><span>共 {{stock.total}} 条</span><a-pagination :current="stock.page+1" :page-size="stock.size" :total="stock.total" :show-size-changer="false" @change="(p:number)=>load(p-1)"/></div>
<form v-if="operationOpen&&can(mode)" class="master-form lot-operation" @submit.prevent="save"><label><span class="form-field-label">操作</span><span class="master-read-value">{{mode==='MOVE'?'移库':'库存调整'}}</span></label><label><span class="form-field-label">来源库位</span><WmsLookup v-model="locationId" resource="locations" label="来源库位" :disabled="mode==='MOVE'"/></label><label v-if="mode==='ADJUST'"><span class="form-field-label">容器</span><WmsLookup v-model="containerId" resource="containers" label="调整容器"/></label><label v-if="mode==='MOVE'"><span class="form-field-label">目标库位</span><WmsLookup v-model="toLocationId" resource="locations" label="目标库位"/></label><label v-if="mode==='MOVE'"><span class="form-field-label">目标容器</span><WmsLookup v-model="toContainerId" resource="containers" label="目标容器"/></label><label><span class="form-field-label">{{mode==='MOVE'?'移动数量':'调整差额'}}</span><input v-model="quantity" aria-label="库存数量" class="master-native-input" required/></label><label><span class="form-field-label">单位</span><ProcessLookup v-model="unitId" resource="units" label="库存单位"/></label><label class="form-full-row"><span class="form-field-label">操作原因</span><textarea v-model="reason" aria-label="操作原因" class="master-native-input" required/></label><a-space><a-button type="primary" html-type="submit" :disabled="busy||conflict">提交{{mode==='MOVE'?'移库':'调整'}}</a-button><a-button @click="operationOpen=false">取消</a-button></a-space></form>
</a-tab-pane>
<a-tab-pane key="production" tab="生产使用"><MaterialLotLineage :lot-id="record.id!" :types="['MAIN_BATCH','EXECUTION_UNIT','OPERATION','CHARGE','WEIGHING']"/></a-tab-pane>
<a-tab-pane key="audit" tab="审计 / 追溯"><a-space wrap><a-button v-if="auth.can('trace:view')" @click="router.push({path:'/trace',query:{materialLotId:record.id}})">完整追溯</a-button><a-button v-if="auth.can('audit:view')" @click="router.push({path:'/audit',query:{objectType:'MaterialLot',objectId:record.id}})">审计追踪</a-button></a-space><MaterialLotLineage :lot-id="record.id!" :types="['SIGNATURE','INVENTORY_DECISION']"/></a-tab-pane>
</a-tabs></a-card><FunctionalQualityActions v-if="record" :row="record" kind="lot" @reload="load()"/></main></template>
<style scoped>.lot-operation{margin-top:20px}.lot-page :deep(.process-lookup .ant-select){width:100%}</style>
