<script setup lang="ts">
import {ref,computed,watch} from 'vue'
import {useRoute,useRouter,onBeforeRouteLeave} from 'vue-router'
import {api} from '../../api/http'
import {useControlledRequest} from '../../api/controlled'
import {useAuthStore} from '../../stores/auth'
import IncomingReferencePicker from '../quality/IncomingReferencePicker.vue'
import ReadReference from '../master/ReadReference.vue'
import ProcessLookup from '../process/ProcessLookup.vue'
import {statusLabels} from './model'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),control=useControlledRequest(),record=ref<Record<string,any>|null>(null),batch=ref<Record<string,any>>({}),mainBatchId=ref(''),requestNo=ref(''),items=ref<Record<string,any>[]>([]),reason=ref(''),baseline=ref('')
const create=computed(()=>route.meta.mode==='create'),edit=computed(()=>create.value||route.meta.mode==='edit'),editable=computed(()=>edit.value&&(!record.value||record.value.status==='DRAFT')&&!control.busy.value&&!control.conflict.value)
const formulas=computed<Record<string,any>[]>(()=>(batch.value.processSnapshot?.snapshot?.process?.formula?.items??[]).map((i:Record<string,any>)=>({...i,materialName:batch.value.processSnapshot.snapshot.materials.find((m:Record<string,any>)=>String(m.id)===String(i.materialId))?.materialName})))
const blank=()=>({formulaItemId:'',requestedQty:'',unitId:''});function state(){return JSON.stringify({mainBatchId:mainBatchId.value,requestNo:requestNo.value,items:items.value})}
let batchTicket=0
watch(mainBatchId,async id=>{const t=++batchTicket;batch.value={};if(!id)return;try{const b=await api<Record<string,any>>({url:`/main-batches/${id}`});if(t===batchTicket)batch.value=b}catch(e){if(create.value)await control.failure(e)}})
async function load(){control.clear();control.busy.value=true;try{reason.value='';if(create.value){record.value=null;mainBatchId.value='';requestNo.value='';items.value=[blank()]}else{record.value=await api({url:`/material-requests/${route.params.id}`});mainBatchId.value=record.value!.mainBatchId;requestNo.value=record.value!.requestNo;items.value=record.value!.items.map((i:Record<string,any>)=>({...i}))}baseline.value=state()}catch(e){await control.failure(e)}finally{control.busy.value=false}}
async function save(action=''){control.busy.value=true;control.error.value='';try{if(!reason.value.trim())throw Error('请填写操作原因');const r=record.value;const body=action?{versionNo:r!.versionNo,reason:reason.value}:{requestNo:requestNo.value,reason:reason.value,items:items.value.map(i=>({...(!create.value&&i.id?{id:i.id}:{}),formulaItemId:i.formulaItemId,requestedQty:i.requestedQty,unitId:i.unitId})),...(r?{versionNo:r.versionNo}:{mainBatchId:mainBatchId.value})};const result=await control.mutate<Record<string,any>>(r?`/material-requests/${r.id}${action?'/'+action:''}`:'/material-requests',r&&!action?'PUT':'POST',body,r?.versionNo);baseline.value=state();await router.replace({path:`/wms/requests/${result.id}`,query:route.query});await load()}catch(e){await control.failure(e)}finally{control.busy.value=false}}
onBeforeRouteLeave(()=>!edit.value||baseline.value===state()||window.confirm('离开将放弃未保存的领料申请，是否继续？'))
watch([()=>route.params.id,()=>route.meta.mode],load,{immediate:true})
</script>
<template><main :data-ui-template="edit?'T2':'T3'" class="admin-page master-page"><header class="admin-page-header"><div><a-button type="link" @click="router.push({path:'/wms/requests',query:route.query})">← 返回领料申请</a-button><h1>{{create?'新增领料申请':edit?'编辑领料申请':record?.requestNo||'领料申请详情'}}</h1><p v-if="record"><a-tag>{{statusLabels[record.status]}}</a-tag> {{record.batchNo}} · {{record.productName}}</p></div><a-space><a-button v-if="!edit&&record?.allowedActions?.includes('UPDATE')&&auth.can('wms:request:update')" @click="router.push({path:`/wms/requests/${record.id}/edit`,query:route.query})">编辑</a-button><a-button v-if="!edit&&['SUBMITTED','PARTIALLY_ISSUED'].includes(record?.status)&&auth.can('wms:issue:create')" type="primary" @click="router.push({path:'/wms/issues/create',query:{materialRequestId:record!.id}})">创建出库单</a-button><a-button v-if="record&&auth.can('audit:view')" @click="router.push({path:'/audit',query:{objectType:'MaterialRequest',objectId:record.id}})">审计追踪</a-button></a-space></header>
<a-alert v-if="control.error.value" type="error" :message="control.error.value" show-icon/><a-alert v-if="control.conflict.value" type="warning" message="记录已变化，输入已保留；请核对后重新加载。"><template #action><a-button @click="load">重新加载</a-button></template></a-alert>
<a-card title="申请信息" class="form-section"><div class="master-form"><label><span class="form-field-label">申请单号</span><input v-if="edit" v-model="requestNo" aria-label="申请单号" class="master-native-input" :disabled="!editable" maxlength="80"/><span v-else>{{requestNo}}</span></label><label><span class="form-field-label">生产批</span><IncomingReferencePicker v-if="create" v-model="mainBatchId" field="mainBatchId" :context="{}" required input-label="生产批"/><span v-else>{{record?.batchNo}}</span></label><label><span class="form-field-label">产品</span><ReadReference v-if="record?.productId||batch.productId" field="productId" :value="record?.productId||batch.productId" :name="record?.productName"/><span v-else>请先选择生产批</span></label><label v-if="record"><span class="form-field-label">冻结处方版本</span><span>{{record.formulaVersionId}} · 快照引用 {{record.processSnapshotId}}</span></label></div></a-card>
<a-card title="申请物料" class="form-section"><template v-if="edit"><div v-for="(item,index) in items" :key="item.id||index" class="master-form request-line"><label><span class="form-field-label">处方物料</span><span v-if="item.id">{{item.materialName}}</span><IncomingReferencePicker v-else v-model="item.formulaItemId" field="formulaItemId" :context="{formulaItems:formulas}" :input-label="`处方物料 ${index+1}`" required/></label><label><span class="form-field-label">申请数量</span><input v-model="item.requestedQty" :aria-label="`申请数量 ${index+1}`" class="master-native-input" :disabled="!editable"/></label><label><span class="form-field-label">单位</span><ProcessLookup v-model="item.unitId" resource="units" :label="`申请单位 ${index+1}`" :disabled="!editable"/></label></div><a-button :disabled="!editable" @click="items.push(blank())">添加申请物料</a-button></template><a-table v-else :data-source="items" row-key="id" :pagination="false" :columns="[{title:'物料编码',dataIndex:'materialCode'},{title:'物料',dataIndex:'materialName'},{title:'申请数量',dataIndex:'requestedQty'},{title:'已出库量',dataIndex:'issuedQty'},{title:'剩余需求',dataIndex:'remainingQty'},{title:'单位',dataIndex:'unitName'}]"/></a-card>
<a-card v-if="record?.linkedIssues?.length" title="关联出库单" class="form-section"><a-button v-for="i in record.linkedIssues" :key="i.id" type="link" @click="router.push(`/wms/issues/${i.id}`)">{{i.issueNo}} · {{statusLabels[i.status]}}</a-button></a-card>
<a-card v-if="edit||record?.allowedActions?.length" title="受控操作" class="form-section"><div class="master-form"><label class="form-full-row"><span class="form-field-label">操作原因</span><textarea v-model="reason" aria-label="操作原因" class="master-native-input" maxlength="1000"/></label></div><a-space><a-button v-if="edit" type="primary" :disabled="!editable" :loading="control.busy.value" @click="save()">保存领料申请</a-button><a-button v-if="!edit&&record?.allowedActions?.includes('SUBMIT')&&auth.can('wms:request:submit')" type="primary" :disabled="control.conflict.value" :loading="control.busy.value" @click="save('submit')">提交领料申请</a-button><a-button v-if="!edit&&record?.allowedActions?.includes('CANCEL')&&auth.can('wms:request:cancel')" :disabled="control.conflict.value" :loading="control.busy.value" @click="save('cancel')">取消申请</a-button></a-space></a-card></main></template>
<style scoped>.master-form :deep(.process-lookup){width:100%;min-width:0}.master-form :deep(.process-lookup .ant-select){width:100%}.request-line{padding-bottom:16px;margin-bottom:16px;border-bottom:1px solid #eef1f5}</style>
