<script setup lang="ts">
import {ref,computed,watch} from 'vue'
import {useRoute,useRouter,onBeforeRouteLeave} from 'vue-router'
import {api} from '../../api/http'
import {useControlledRequest} from '../../api/controlled'
import {useAuthStore} from '../../stores/auth'
import {blankReceipt,blankItem,receiptPayload,checks,statusLabels} from './model'
import type {Receipt,ReceiptCreate} from './types'
import WmsLookup from './WmsLookup.vue'
import ReceiptAttachments from './ReceiptAttachments.vue'
import ProcessLookup from '../process/ProcessLookup.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),request=useControlledRequest(),{error,conflict,busy,fields}=request,record=ref<Receipt|null>(null),form=ref<ReceiptCreate>(blankReceipt()),reason=ref(''),baseline=ref(''),savedCount=ref(0),create=computed(()=>route.meta.mode==='create'),view=computed(()=>route.meta.mode==='view'),editable=computed(()=>!view.value&&(create.value||record.value?.allowedActions?.includes('UPDATE'))&&!busy.value&&!conflict.value),dirty=computed(()=>!view.value&&baseline.value!==JSON.stringify(form.value))
async function load(){request.clear();record.value=null;form.value=blankReceipt();savedCount.value=0;reason.value='';busy.value=true;try{if(!create.value){record.value=await api<Receipt>({url:`/wms/receipts/${route.params.id}`});form.value={...blankReceipt(),...receiptPayload(record.value as ReceiptCreate)};savedCount.value=form.value.items.length}baseline.value=JSON.stringify(form.value)}catch(e){await request.failure(e)}finally{busy.value=false}}
async function save(confirm=false){busy.value=true;error.value='';try{if(!create.value&&!reason.value.trim())throw Error('请填写操作原因');const r=record.value,body=confirm?{versionNo:r!.versionNo,reason:reason.value}:{...receiptPayload(form.value),...(!create.value?{versionNo:r!.versionNo,reason:reason.value}:{})};const result=await request.mutate<Receipt>(create.value?'/wms/receipts':`/wms/receipts/${r!.id}${confirm?'/confirm':''}`,create.value||confirm?'POST':'PUT',body,r?.versionNo);baseline.value=JSON.stringify(form.value);await router.push({path:`/wms/receipts/${result.id}`,query:route.query});if(view.value)await load()}catch(e){await request.failure(e)}finally{busy.value=false}}
async function reloadAttachmentVersion(){if(record.value)record.value=await api<Receipt>({url:`/wms/receipts/${record.value.id}`})}
function add(){form.value.items.push(blankItem())}
const headerFields=[['receiptNo','收货单号'],['purchaseOrderNo','采购单号'],['deliveryNoteNo','送货单号']] as const
const itemFields=[['lotNo','物料批号','text'],['supplierLotNo','供应商批号','text'],['manufacturerLotNo','生产商批号','text'],['manufactureDate','生产日期','date'],['expiryDate','有效期至','date'],['retestDate','复验日期','date'],['receivedQty','收货数量','text'],['packageSpec','包装规格','text'],['packageCount','包装件数','number']] as const
onBeforeRouteLeave(()=>!dirty.value||window.confirm('离开页面将放弃未保存的收货输入，是否继续？'))
watch(()=>route.fullPath,load,{immediate:true})
</script>
<template><main :data-ui-template="view?'T3':'T2'" class="admin-page master-page receipt-page"><header class="admin-page-header"><div><a-button type="link" @click="router.push({path:'/wms/receipts',query:route.query})">← 返回收货列表</a-button><h1>{{create?'新增收货单':view?'收货单详情':'编辑收货单'}}</h1><p v-if="record">{{record.receiptNo}} · 记录状态：{{statusLabels[record.recordStatus??'']}} · 乐观锁版本 {{record.versionNo}}</p></div><a-space wrap><a-button v-if="record&&auth.can('audit:view')" @click="router.push({path:'/audit',query:{objectType:'MaterialReceipt',objectId:record.id}})">审计追踪</a-button><a-button v-if="view&&auth.can('wms:receipt:update')&&record?.allowedActions?.includes('UPDATE')" type="primary" @click="router.push({path:`/wms/receipts/${record.id}/edit`,query:route.query})">编辑收货单</a-button></a-space></header><a-alert v-if="error" type="error" :message="error" show-icon/><a-alert v-if="conflict" type="warning" message="记录已变化，输入已保留，请重新加载后继续。"><template #action><a-button @click="load">重新加载</a-button></template></a-alert><ul v-if="fields.length" class="error"><li v-for="(f,i) in fields" :key="i">{{f.field||f.path}}：{{f.message}}</li></ul>
<form @submit.prevent="save()"><a-card title="收货信息" class="form-section"><div class="master-form"><label v-for="[key,label] in headerFields" :key="key"><span class="form-field-label">{{label}}</span><input v-model="form[key]" :name="key" :aria-label="label" class="master-native-input" :disabled="!editable" :required="key==='receiptNo'"/></label><label><span class="form-field-label">供应商</span><WmsLookup v-model="form.supplierId" resource="suppliers" label="供应商" :disabled="!editable"/></label><label><span class="form-field-label">仓库</span><WmsLookup v-model="form.warehouseId" resource="warehouses" label="仓库" :disabled="!editable"/></label><label><span class="form-field-label">运输检查通过</span><input v-model="form.transportCheckPassed" aria-label="运输检查通过" name="transportCheckPassed" type="checkbox" :disabled="!editable"/></label><template v-if="view"><label><span class="form-field-label">确认人</span><span class="master-read-value">{{record?.confirmedBy||'尚未确认'}}</span></label><label><span class="form-field-label">确认时间</span><span class="master-read-value">{{record?.confirmedAt||'—'}}</span></label></template></div></a-card>
<a-card v-for="(item,i) in form.items" :key="i" :title="`收货明细 ${i+1}`" class="form-section"><template #extra><a-button v-if="!view&&i>=savedCount" danger :disabled="!editable||form.items.length===1" @click="form.items.splice(i,1)">移除未保存行</a-button></template><div class="master-form"><label><span class="form-field-label">物料</span><ProcessLookup :model-value="item.materialId" resource="materials" :label="`物料 ${i+1}`" :disabled="!editable" @update:model-value="v=>item.materialId=v??''"/></label><label v-for="[key,label,type] in itemFields" :key="key"><span class="form-field-label">{{label}}</span><input v-if="type==='number'" v-model.number="item.packageCount" :aria-label="`${label} ${i+1}`" :name="`items[${i}].${key}`" type="number" min="1" step="1" class="master-native-input" :disabled="!editable" required/><input v-else v-model="item[key]" :aria-label="`${label} ${i+1}`" :name="`items[${i}].${key}`" :type="type" class="master-native-input" :disabled="!editable" :required="['lotNo','supplierLotNo','receivedQty'].includes(key)"/></label><label><span class="form-field-label">收货单位</span><ProcessLookup :model-value="item.unitId" resource="units" :label="`收货单位 ${i+1}`" :disabled="!editable" @update:model-value="v=>item.unitId=v??''"/></label><label><span class="form-field-label">库位</span><WmsLookup v-model="item.locationId" resource="locations" :warehouse-id="form.warehouseId" :label="`库位 ${i+1}`" :disabled="!editable"/></label><label><span class="form-field-label">容器</span><WmsLookup v-model="item.containerId" resource="containers" :label="`容器 ${i+1}`" :disabled="!editable"/></label><label v-for="[key,label] in checks" :key="key"><span class="form-field-label">{{label}}通过</span><input v-model="item[key]" :name="`items[${i}].${key}`" :aria-label="`${label}通过 ${i+1}`" type="checkbox" :disabled="!editable"/></label><label v-if="record?.items?.[i]?.materialLotId"><span class="form-field-label">生成物料批</span><a-button type="link" :aria-label="`查看物料批 ${item.lotNo}`" :disabled="!auth.can('wms:inventory:view')" @click="router.push({path:`/wms/material-lots/${record.items[i]!.materialLotId}`,query:route.query})">{{item.lotNo}}</a-button></label></div><p v-if="view&&record?.items?.[i]?.materialLotId" class="muted">入库是否必验快照：{{record.items[i]!.requiresIncomingInspectionSnapshot?'是':'否'}}。生产使用须经过物料质量放行。</p></a-card>
<a-button v-if="!view" :disabled="!editable" @click="add">添加收货明细</a-button><a-card v-if="!view||(auth.can('wms:receipt:confirm')&&record?.allowedActions?.includes('CONFIRM'))" title="受控操作" class="form-section receipt-actions"><div class="master-form"><label v-if="!create" class="form-full-row"><span class="form-field-label">操作原因</span><textarea v-model="reason" aria-label="操作原因" name="reason" class="master-native-input" maxlength="1000"/></label><a-space wrap><a-button v-if="!view" html-type="submit" type="primary" :loading="busy" :disabled="!editable">保存收货单</a-button><a-button v-if="view&&auth.can('wms:receipt:confirm')&&record?.allowedActions?.includes('CONFIRM')" type="primary" :disabled="busy||conflict" @click="save(true)">确认收货</a-button><a-button @click="router.push({path:'/wms/receipts',query:route.query})">取消</a-button></a-space></div></a-card></form><ReceiptAttachments v-if="record?.id && record.versionNo !== undefined" :receipt-id="record.id" :version-no="record.versionNo" @reload="reloadAttachmentVersion"/></main></template>
<style scoped>.receipt-actions{margin-top:16px}.receipt-page :deep(.process-lookup .ant-select){width:100%}</style>
