<script setup lang="ts">
import {ref,computed,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,errorMessage,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {statusLabels} from './model'
import WmsLookup from './WmsLookup.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),receipt=computed(()=>route.meta.resource==='receipts'),title=computed(()=>receipt.value?'收货单查询':'发料单查询'),keyword=ref(''),status=ref(''),supplierId=ref(''),warehouseId=ref(''),error=ref(''),busy=ref(false),data=ref<Page<Record<string,any>>>({items:[],total:0,page:0,size:20}),suppliers=ref<Record<string,string>>({}),materials=ref<Record<string,string>>({}),units=ref<Record<string,string>>({})
const columns=computed(()=>receipt.value?[{title:'收货单号',dataIndex:'receiptNo'},{title:'物料 / 供应商批号',key:'items'},{title:'供应商',key:'supplier'},{title:'收货数量',key:'quantity'},{title:'记录状态',key:'status'},{title:'日期',dataIndex:'receivedAt'},{title:'操作',key:'actions'}]:[{title:'发料单号',dataIndex:'issueNo'},{title:'生产批 ID',dataIndex:'mainBatchId'},{title:'状态',key:'status'},{title:'发料时间',dataIndex:'issuedAt'},{title:'创建人',dataIndex:'createdBy'},{title:'操作',key:'actions'}])
function open(id='create',edit=false){void router.push({path:`/wms/${receipt.value?'receipts':'issues'}/${id}${edit?'/edit':''}`,query:route.query})}
async function load(page=0){busy.value=true;error.value='';try{const params={keyword:keyword.value||undefined,...(receipt.value?{recordStatus:status.value||undefined,supplierId:supplierId.value||undefined,warehouseId:warehouseId.value||undefined}:{status:status.value||undefined}),page,size:20};await router.replace({query:Object.fromEntries(Object.entries(params).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]))});data.value=await api({url:receipt.value?'/wms/receipts':'/material-issues',params});if(receipt.value){await Promise.all([['materials','master:material:view',materials.value,'materialName','materialId'],['units','master:uom:view',units.value,'unitName','unitId']].map(async ([resource,permission,map,name,key])=>{if(!auth.can(permission as string))return;const ids=[...new Set(data.value.items.flatMap(r=>(r.items??[]).map((i:any)=>i[key as string])))];await Promise.all(ids.map(async id=>{if((map as Record<string,string>)[String(id)])return;try{const item=await api<Record<string,string>>({url:`/${resource}/${id}`});(map as Record<string,string>)[String(id)]=item[name as string]!}catch{/* Keep the exact reference when lookup is forbidden. */}}))}))}if(receipt.value&&auth.can('master:supplier:view')){const ids=[...new Set(data.value.items.map(r=>r.supplierId))].filter(id=>id&&!suppliers.value[id]);await Promise.all(ids.map(async id=>{try{const s=await api<Record<string,string>>({url:`/suppliers/${id}`});suppliers.value[id]=s.supplierName!}catch{/* Receipt data remains visible if lookup is unavailable. */}}))}}catch(e){error.value=errorMessage(e)}finally{busy.value=false}}
watch(()=>route.meta.resource,()=>{keyword.value=String(route.query.keyword??'');status.value=String(route.query.recordStatus??route.query.status??'');supplierId.value=String(route.query.supplierId??'');warehouseId.value=String(route.query.warehouseId??'');void load(Number(route.query.page??0))},{immediate:true})
</script>
<template><main class="admin-page master-page"><header class="admin-page-header"><div><h1>{{title}}</h1><p>仓储记录 · 查询条件随导航保留</p></div><a-button v-if="auth.can(receipt?'wms:receipt:create':'wms:issue:create')" type="primary" @click="open()">＋ 新增</a-button></header><a-alert v-if="!receipt" type="warning" message="生产批与物料资格 Gate 尚未就绪，发料写入暂不可用。"/><a-card title="查询条件" class="query-card"><form class="query-form" @submit.prevent="load()"><label>单号 / 关键字<a-input v-model:value="keyword" aria-label="单号查询"/></label><label>状态<a-select v-model:value="status" allow-clear aria-label="状态"><a-select-option v-for="s in receipt?['DRAFT','APPROVED']:['DRAFT','CONFIRMED','CLOSED']" :key="s" :value="s">{{statusLabels[s]}}</a-select-option></a-select></label><template v-if="receipt"><label>供应商<WmsLookup v-model="supplierId" resource="suppliers" label="供应商查询"/></label><label>仓库<WmsLookup v-model="warehouseId" resource="warehouses" label="仓库查询"/></label></template><a-space><a-button @click="keyword='';status='';supplierId='';warehouseId='';load()">重置</a-button><a-button html-type="submit" type="primary">查询</a-button></a-space></form></a-card><a-alert v-if="error" type="error" :message="error" show-icon/><a-card title="数据列表" class="result-card"><a-table :columns="columns" :data-source="data.items" :loading="busy" :pagination="false" row-key="id" :scroll="{x:900}"><template #bodyCell="{column,record}"><a-tag v-if="column.key==='status'">{{statusLabels[record.recordStatus||record.status]||record.recordStatus||record.status}}</a-tag><template v-else-if="column.key==='supplier'">{{suppliers[record.supplierId]||`供应商 #${record.supplierId}`}}</template><template v-else-if="column.key==='items'"><div v-for="item in record.items" :key="item.id">{{item.materialSnapshot?.materialName||materials[item.materialId]||`物料 #${item.materialId}`}} · {{item.supplierLotNo}}</div></template><template v-else-if="column.key==='quantity'"><div v-for="item in record.items" :key="item.id">{{item.receivedQty}} · {{units[item.unitId]||(item.unitId===item.materialSnapshot?.baseUnitId?item.materialSnapshot?.baseUnitName:undefined)||`单位 #${item.unitId}`}}</div></template><template v-else-if="column.key==='actions'"><a-button type="link" @click="open(record.id)">查看</a-button><a-button v-if="auth.can(receipt?'wms:receipt:update':'wms:issue:update')&&record.allowedActions?.includes('UPDATE')" type="link" @click="open(record.id,true)">编辑</a-button></template></template></a-table><div class="table-footer"><span>共 {{data.total}} 条</span><a-pagination :current="data.page+1" :page-size="data.size" :total="data.total" :show-size-changer="false" @change="(p:number)=>load(p-1)"/></div></a-card></main></template>
<style scoped>.query-form label>.wms-lookup{flex:1;min-width:0}</style>
