<script setup lang="ts">
import {ref,computed,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,errorMessage,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import WmsLookup from './WmsLookup.vue'
import ProcessLookup from '../process/ProcessLookup.vue'
import IncomingReferencePicker from '../quality/IncomingReferencePicker.vue'
import {statusLabels} from './model'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),finishedInventory=computed(()=>route.meta.finishedInventory===true),kind=computed(()=>String(route.meta.resource)),title=computed(()=>kind.value==='inventory'?(finishedInventory.value?'成品库存':'库存管理'):kind.value==='requests'?'领料申请':'退料管理'),filters=ref<Record<string,string>>({}),error=ref(''),busy=ref(false),data=ref<Page<Record<string,any>>>({items:[],total:0,page:0,size:20})
const endpoint=computed(()=>kind.value==='inventory'?'/wms/inventory':kind.value==='requests'?'/material-requests':'/material-returns')
const columns=computed(()=>kind.value==='inventory'?[
 ...(finishedInventory.value?[{title:'生产批',key:'batch'},{title:'产品',key:'product'},{title:'规格',dataIndex:'productSpecification'}]:[{title:'物料',key:'material'}]),{title:'批次',key:'lot'},{title:'仓库 / 库位',key:'locations'},{title:'批次在库量',dataIndex:'onHandQty'},{title:'批次预留量',dataIndex:'reservedQty'},{title:'批次可用量',dataIndex:'availableQty'},{title:'单位',dataIndex:'unitName'},{title:'质量状态',key:'quality'},{title:'库存状态',key:'stock'}
]:kind.value==='requests'?[
 {title:'申请单号',dataIndex:'requestNo'},{title:'生产批',dataIndex:'batchNo'},{title:'产品',dataIndex:'productName'},{title:'申请物料 / 数量',key:'items'},{title:'申请时间',dataIndex:'createdAt'},{title:'状态',key:'status'},{title:'操作',key:'actions'}
]:[
 {title:'退料记录编号',dataIndex:'id'},{title:'原出库单',key:'issue'},{title:'生产批',dataIndex:'batchNo'},{title:'物料',dataIndex:'materialName'},{title:'物料批次',key:'lot'},{title:'本次退料量',key:'returnQty'},{title:'原出库量 / 累计已退',key:'originalQty'},{title:'原因',dataIndex:'reason'},{title:'退料时间',dataIndex:'returnedAt'}])
const allowedFilters=computed(()=>kind.value==='inventory'?['keyword',...(finishedInventory.value?['productId','mainBatchId']:['materialId']),'materialLotId','warehouseId','locationId','qualityStatus','inventoryStatus']:kind.value==='requests'?['keyword','mainBatchId','productId','status','createdFrom','createdTo']:['keyword','issueId','mainBatchId','materialId','materialLotId','returnedFrom','returnedTo'])
let loadGeneration=0
async function load(page=0){const generation=++loadGeneration,url=endpoint.value;busy.value=true;error.value='';try{const params={...Object.fromEntries(Object.entries(filters.value).filter(([k,v])=>allowedFilters.value.includes(k)&&v)),...(finishedInventory.value?{finishedOnly:true}:{}),page,size:20};await router.replace({query:Object.fromEntries(Object.entries(params).map(([k,v])=>[k,String(v)]))});if(generation!==loadGeneration)return;const result=await api<Page<Record<string,any>>>({url,params});if(generation===loadGeneration)data.value=result}catch(e){if(generation===loadGeneration)error.value=errorMessage(e)}finally{if(generation===loadGeneration)busy.value=false}}
function reset(){filters.value={};void load()}
function formatQty(value:unknown){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat('zh-CN',{maximumFractionDigits:6}).format(n):String(value??'—')}
function open(id='create',edit=false){void router.push({path:`/wms/${kind.value}/${id}${edit?'/edit':''}`,query:route.query})}
watch(()=>[route.meta.resource,route.meta.finishedInventory],()=>{data.value={items:[],total:0,page:0,size:20};filters.value=Object.fromEntries(allowedFilters.value.map(k=>[k,String(route.query[k]??'')]));void load(Number(route.query.page??0))},{immediate:true})
const qualities=['QUARANTINE','PENDING_SAMPLING','SAMPLING','SAMPLED','TESTING','PENDING_QC_REVIEW','QC_PASSED','QC_FAILED','PENDING_QA_RELEASE','PENDING_DISPOSITION','RELEASED','REJECTED']
</script>
<template><main data-ui-template="T1" class="admin-page master-page t1-query-list wms-management-page"><header class="admin-page-header"><div><h1>{{title}}</h1></div><a-button v-if="kind==='requests'&&auth.can('wms:request:create')" type="primary" @click="open()">＋ 新增领料申请</a-button><a-button v-if="kind==='returns'&&auth.can('wms:issue:return')" type="primary" @click="open()">＋ 登记退料</a-button></header>

<a-card title="查询条件" class="query-card"><form class="query-form" @submit.prevent="load()"><label><span class="form-field-label">关键字</span><a-input v-model:value="filters.keyword" aria-label="关键字"/></label>
<template v-if="kind==='inventory'"><template v-if="finishedInventory"><label v-if="auth.can('master:product:view')"><span class="form-field-label">产品</span><ProcessLookup  :model-value="filters.productId??null" @update:model-value="(v:string|null)=>filters.productId=v??''" resource="products" label="产品查询" allow-clear/></label><label v-if="auth.can('production:batch:view')"><span class="form-field-label">生产批</span><IncomingReferencePicker v-model="filters.mainBatchId" field="mainBatchId" :context="{}" :query-filters="{productId:filters.productId}" input-label="生产批查询"/></label></template><label v-else><span class="form-field-label">物料</span><IncomingReferencePicker v-model="filters.materialId" field="materialId" :context="{}" input-label="物料查询"/></label><label><span class="form-field-label">仓库</span><WmsLookup v-model="filters.warehouseId" resource="warehouses" label="仓库查询"/></label><label><span class="form-field-label">库位</span><WmsLookup v-model="filters.locationId" resource="locations" label="库位查询" :warehouse-id="filters.warehouseId"/></label><label><span class="form-field-label">质量状态</span><a-select show-search option-filter-prop="children" v-model:value="filters.qualityStatus" allow-clear aria-label="质量状态"><a-select-option v-for="s in qualities" :key="s" :value="s">{{statusLabels[s]||s}}</a-select-option></a-select></label><label><span class="form-field-label">库存状态</span><a-select show-search option-filter-prop="children" v-model:value="filters.inventoryStatus" allow-clear aria-label="库存状态"><a-select-option v-for="s in ['BLOCKED','AVAILABLE','FROZEN']" :key="s" :value="s">{{finishedInventory&&s==='BLOCKED'?'禁止发货':statusLabels[s]}}</a-select-option></a-select></label></template>
<template v-else><label><span class="form-field-label">生产批</span><IncomingReferencePicker v-model="filters.mainBatchId" field="mainBatchId" :context="{}" input-label="生产批查询"/></label><label v-if="kind==='requests'"><span class="form-field-label">状态</span><a-select show-search option-filter-prop="children" v-model:value="filters.status" allow-clear aria-label="申请状态"><a-select-option v-for="s in ['DRAFT','SUBMITTED','PARTIALLY_ISSUED','FULFILLED','CANCELLED']" :key="s" :value="s">{{statusLabels[s]}}</a-select-option></a-select></label></template><a-space><a-button @click="reset">重置</a-button><a-button type="primary" html-type="submit">查询</a-button></a-space></form></a-card>
<a-alert v-if="error" type="error" :message="error" show-icon/><a-card title="数据列表" class="result-card"><a-table :columns="columns" :data-source="data.items" :loading="busy" :pagination="false" :row-key="kind==='inventory'?'materialLotId':'id'" :scroll="{x:1100}"><template #bodyCell="{column,record}"><template v-if="column.key==='batch'"><a-button v-if="auth.can('production:batch:view')" type="link" @click="router.push(`/production/batches/${record.mainBatchId}`)">{{record.batchNo}}</a-button><span v-else>{{record.batchNo}}</span></template><template v-else-if="column.key==='product'">{{record.productName}}<small class="wms-secondary">{{record.productCode}}</small></template><template v-else-if="column.key==='material'">{{record.materialName}}<small class="wms-secondary">{{record.materialCode}}</small></template><a-button v-else-if="column.key==='lot'" type="link" @click="router.push(`/wms/material-lots/${record.materialLotId}`)">{{record.lotNo}}</a-button><template v-else-if="column.key==='locations'"><div v-for="(l,i) in record.locationBalances" :key="i">{{l.warehouseName}} / {{l.locationName}}<small class="wms-secondary">{{formatQty(l.onHandQty)}} {{l.unitName}}</small></div></template><template v-else-if="['onHandQty','reservedQty','availableQty'].includes(column.dataIndex)">{{formatQty(record[column.dataIndex])}}</template><a-tag v-else-if="['status','quality','stock'].includes(column.key)">{{finishedInventory&&column.key==='stock'&&record.inventoryStatus==='BLOCKED'?'禁止发货':statusLabels[column.key==='quality'?record.qualityStatus:column.key==='stock'?record.inventoryStatus:record.status]||record.status}}</a-tag><template v-else-if="column.key==='items'"><div v-for="i in record.items" :key="i.id">{{i.materialName}} · {{i.requestedQty}} {{i.unitName}}</div></template><a-button v-else-if="column.key==='issue'" type="link" @click="router.push(`/wms/issues/${record.issueId}`)">{{record.issueNo}}</a-button><template v-else-if="column.key==='returnQty'">{{record.quantity}} {{record.unitName}}</template><template v-else-if="column.key==='originalQty'">{{record.originalIssuedQty}} / {{record.returnedQty}} {{record.issuedUnitName}}</template><template v-else-if="column.key==='actions'"><a-button type="link" @click="open(record.id)">查看</a-button><a-button v-if="record.allowedActions?.includes('UPDATE')&&auth.can('wms:request:update')" type="link" @click="open(record.id,true)">编辑</a-button></template></template></a-table><div class="table-footer"><span>共 {{data.total}} 条</span><a-pagination :current="data.page+1" :page-size="data.size" :total="data.total" :show-size-changer="false" @change="(p:number)=>load(p-1)"/></div></a-card></main></template>
<style scoped>@media(min-width:1200px){:global(#app main.wms-management-page.master-page .query-form){grid-template-columns:repeat(3,minmax(0,1fr))}:global(#app main.wms-management-page.master-page .query-form>.ant-space){grid-column:1/-1}}.query-form label:has(>.wms-lookup){min-width:0}.query-form label>.wms-lookup{flex:1;min-width:0}.query-form :deep(.process-lookup){flex:1;min-width:0}.query-form :deep(.process-lookup>.ant-select){width:100%}.wms-secondary{display:block;color:#667085;font-size:12px}.query-form label>span:not(.form-field-label){flex:1;min-width:0}</style>
