package com.hospital.mes.master.integration;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.ObjectNode;
import com.hospital.mes.audit.application.*;import com.hospital.mes.masterdata.application.*;
import java.time.*;import java.util.*;import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.http.MediaType;import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.test.web.servlet.MockMvc;import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.support.TransactionTemplate;

/** Approved DCP-MATERIAL-BASIC-001 replaces the old business-version test contract. */
@SpringBootTest @ActiveProfiles("ci") @AutoConfigureMockMvc @Transactional
class MaterialSupplierIT {
 @Autowired MaterialService materials;@Autowired MaterialQueryService queries;@Autowired SupplierService suppliers;@Autowired MaterialSupplierService relationships;
 @Autowired ApprovedSupplierQueryService supplierQueries;@Autowired UnitService units;@Autowired UnitConversionService conversions;@Autowired MasterQueryService masterQueries;
 @Autowired JdbcTemplate jdbc;@Autowired ObjectMapper json;@Autowired MockMvc mvc;@Autowired PlatformTransactionManager transactions;
 @MockitoBean CurrentPlatformContextResolver contexts;@MockitoSpyBean AuditApplicationService audit;
 Set<String> permissions;String suffix;CurrentPlatformContext context;
 @BeforeEach void setup(){suffix=UUID.randomUUID().toString().replace("-", "").substring(0,12);permissions=new HashSet<>();for(String type:List.of("material","supplier","uom"))for(String action:List.of("view","create","update","disable"))permissions.add("master:"+type+":"+action);long actor=actor("mb_"+suffix);context=new CurrentPlatformContext(1,actor,Set.of("TEST_MASTER"),permissions,"test","basic-"+suffix);when(contexts.current()).thenReturn(context);}
 long actor(String name){jdbc.update("INSERT INTO sys_user(login_name,login_name_normalized,display_name,password_hash,enabled,must_change_password) VALUES(?,?,?,?,TRUE,FALSE)",name,name,"Rollback actor","not-a-secret");return jdbc.queryForObject("SELECT id FROM sys_user WHERE login_name_normalized=?",Long.class,name);}
 String key(){return UUID.randomUUID().toString();}
 JsonNode unit(String code,String dimension){return units.create(new UnitCommands.Create(code+suffix,code,dimension,3),key());}
 MaterialCommands.Create request(String code,String base){var data=new HashMap<String,Object>();data.put("materialCode",code);data.put("materialName","Test material");data.put("materialType","FINISHED");data.put("specification","100 g");data.put("gradePurity","99.9%");data.put("appearance","White");data.put("baseUnitId",base);data.put("packSpec","1 box");data.put("packUnitId",base);data.put("manufacturerName","Test manufacturer");data.put("lotControlled",true);data.put("remark","Rollback evidence");return json.convertValue(data,MaterialCommands.Create.class);}
 MaterialCommands.Update edit(JsonNode m,String name,boolean policy){var r=request("ignored",m.get("baseUnitId").asText());var n=(ObjectNode)json.valueToTree(r);n.remove("materialCode");n.put("materialName",name);n.put("requiresIncomingInspection",policy);n.put("versionNo",m.path("versionNo").asLong());n.put("reason","basic maintenance");return json.convertValue(n,MaterialCommands.Update.class);}
 JsonNode material(){return materials.create(request("BASIC"+suffix,unit("KG","MASS").get("id").asText()),key());}
 JsonNode supplier(String code){var s=suppliers.create(new SupplierCommands.Create(code+suffix,"Supplier "+code,LocalDate.now(ZoneOffset.UTC).plusYears(1)),key());return s;}
 SupplierCommands.Relationship link(JsonNode s,boolean preferred){return new SupplierCommands.Relationship(s.get("id").asText(),true,preferred,null);}
 @Test void tcMat001BasicCreate201WithoutBusinessVersion() throws Exception {
  var r=request("BAPI"+suffix,unit("U","MASS").get("id").asText());String k=key();
  var result=mvc.perform(post("/api/v1/materials").with(user("test").authorities(new SimpleGrantedAuthority("master:material:create"))).header("Idempotency-Key",k).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(r))).andExpect(status().isCreated()).andExpect(jsonPath("$.data.status").value("ACTIVE")).andExpect(jsonPath("$.data.requiresIncomingInspection").value(true)).andExpect(jsonPath("$.data.selectedVersion").doesNotExist()).andExpect(jsonPath("$.data.versions").doesNotExist()).andReturn();
  var m=json.readTree(result.getResponse().getContentAsString()).get("data");assertThat(m.has("genericName")||m.has("englishName")||m.has("aliasName")).isFalse();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM md_material_version WHERE material_id=?",Long.class,m.get("id").asLong())).isZero();assertThat(jdbc.queryForObject("SELECT http_status FROM platform_idempotency_record WHERE idempotency_key=?",Integer.class,k)).isEqualTo(201);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_audit_event WHERE object_type='Material' AND object_id=?",Long.class,m.get("id").asText())).isZero();
 }
 @Test void tcMat002DuplicateCodeRejected() throws Exception {var r=request("BDUP"+suffix,unit("U","MASS").get("id").asText());materials.create(r,key());mvc.perform(post("/api/v1/materials").with(user("test").authorities(new SimpleGrantedAuthority("master:material:create"))).header("Idempotency-Key",key()).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(r))).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("MATERIAL_CODE_EXISTS"));}
 @Test void tcMat003DirectEditReplayAndStaleToken(){var m=material();String id=m.get("id").asText();var r=edit(m,"Edited immediately",false);String k=key();var edited=materials.update(id,r,null,k);assertThat(edited.get("materialName").asText()).isEqualTo("Edited immediately");assertThat(edited.get("status").asText()).isEqualTo("ACTIVE");assertThat(materials.update(id,r,null,k)).isEqualTo(edited);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_audit_event WHERE object_id=? AND action='Material:UPDATE'",Long.class,id)).isZero();assertThat(materials.update(id,r,null,key()).path("materialName").asText()).isEqualTo("Edited immediately");}
 @Test void tcMat004And005DetachedSnapshotAndEditablePolicy(){var m=material();var snapshot=queries.snapshot(1,m.get("id").asLong());var captured=snapshot.deepCopy();materials.update(m.get("id").asText(),edit(m,"New basic name",false),null,key());assertThat(snapshot).isEqualTo(captured);assertThat(snapshot.get("requiresIncomingInspection").asBoolean()).isTrue();assertThat(queries.snapshot(1,m.get("id").asLong()).get("requiresIncomingInspection").asBoolean()).isFalse();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM md_material_version WHERE material_id=?",Long.class,m.get("id").asLong())).isZero();}
 @Test void tcSup001MultipleSwitchPreferredAndRetainRevocation(){var m=material();var a=supplier("A");var b=supplier("B");String id=m.get("id").asText();var assigned=relationships.assign(id,new SupplierCommands.Assign(0L,"two suppliers",List.of(link(a,true),link(b,false))),null,key());assertThat(assigned.get("suppliers")).hasSize(2);assertThat(supplierQueries.requirePreferred(1,m.get("id").asLong(),Instant.now()).get("supplierId").asText()).isEqualTo(a.get("id").asText());var switched=relationships.assign(id,new SupplierCommands.Assign(assigned.path("versionNo").asLong(),"switch",List.of(link(a,false),link(b,true))),null,key());assertThat(supplierQueries.requirePreferred(1,m.get("id").asLong(),Instant.now()).get("supplierId").asText()).isEqualTo(b.get("id").asText());var revoked=relationships.assign(id,new SupplierCommands.Assign(switched.path("versionNo").asLong(),"revoke B",List.of(link(a,true))),null,key());assertThat(revoked.get("suppliers")).hasSize(2);assertThat(jdbc.queryForObject("SELECT preferred FROM md_material_supplier WHERE material_id=? AND supplier_id=?",Boolean.class,m.get("id").asLong(),b.get("id").asLong())).isFalse();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM md_material_supplier WHERE material_id=? AND preferred=1",Long.class,m.get("id").asLong())).isEqualTo(1);}
 @Test void preferredZeroMultipleAndPhysicalUniqueness(){var m=material();var a=supplier("A");var b=supplier("B");String id=m.get("id").asText();assertThatThrownBy(()->relationships.assign(id,new SupplierCommands.Assign(0L,"missing",List.of(link(a,false))),null,key())).hasMessageContaining("PREFERRED_SUPPLIER_REQUIRED");assertThatThrownBy(()->relationships.assign(id,new SupplierCommands.Assign(0L,"two",List.of(link(a,true),link(b,true))),null,key())).hasMessageContaining("PREFERRED_SUPPLIER_REQUIRED");relationships.assign(id,new SupplierCommands.Assign(0L,"one",List.of(link(a,true))),null,key());assertThatThrownBy(()->jdbc.update("INSERT INTO md_material_supplier(org_id,created_by,updated_by,material_id,supplier_id,approved,preferred) VALUES(1,?,?,?,?,1,1)",context.actorId(),context.actorId(),m.get("id").asLong(),b.get("id").asLong())).isInstanceOf(org.springframework.dao.DuplicateKeyException.class);}
 @Test void tcSup002ExpiryNoAutomaticPreferredFallback(){var m=material();var a=supplier("A");var b=supplier("B");var end=LocalDate.now(ZoneOffset.UTC).plusDays(1);relationships.assign(m.get("id").asText(),new SupplierCommands.Assign(0L,"validity",List.of(new SupplierCommands.Relationship(a.get("id").asText(),true,true,end),link(b,false))),null,key());assertThat(supplierQueries.requirePreferred(1,m.get("id").asLong(),end.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant().minusMillis(1)).get("supplierId").asText()).isEqualTo(a.get("id").asText());assertThatThrownBy(()->supplierQueries.requirePreferred(1,m.get("id").asLong(),end.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant())).hasMessageContaining("SUPPLIER_NOT_APPROVED");assertThat(relationships.get(m.get("id").asText()).get("suppliers").get(0).get("preferred").asBoolean()).isTrue();}
 @Test void relationReplayStaleAndPermissionBeforeReplay(){var m=material();var a=supplier("A");var r=new SupplierCommands.Assign(0L,"once",List.of(link(a,true)));String k=key();var written=relationships.assign(m.get("id").asText(),r,null,k);assertThat(relationships.assign(m.get("id").asText(),r,null,k)).isEqualTo(written);assertThat(relationships.assign(m.get("id").asText(),r,null,key()).path("suppliers")).hasSize(1);permissions.remove("master:material:update");when(contexts.current()).thenReturn(new CurrentPlatformContext(1,context.actorId(),Set.of(),permissions,"s","r"));assertThatThrownBy(()->relationships.assign(m.get("id").asText(),r,null,k)).hasMessageContaining("Permission required");}
 @Test void sameOrgAndMaterialSpecificConversion(){var m=material();var volume=unit("L","VOLUME");conversions.create(new UnitConversionCommands.Create(m.get("baseUnitId").asText(),volume.get("id").asText(),"0.5",m.get("id").asText()),key());assertThat(masterQueries.convert(1,m.get("baseUnitId").asLong(),volume.get("id").asLong(),m.get("id").asLong(),new java.math.BigDecimal("4")).convertedValue()).isEqualTo("2.000");when(contexts.current()).thenReturn(new CurrentPlatformContext(2,context.actorId(),Set.of(),permissions,"s","r"));assertThatThrownBy(()->materials.get(m.get("id").asText())).isInstanceOf(NoSuchElementException.class);assertThatThrownBy(()->queries.snapshot(2,m.get("id").asLong())).isInstanceOf(NoSuchElementException.class);}
 @Test void legacyEvidenceKeptAndRetiredApiUnavailable() throws Exception {var m=material();jdbc.update("UPDATE md_material SET status='APPROVED' WHERE id=?",m.get("id").asLong());jdbc.update("INSERT INTO md_material_version(org_id,created_by,updated_by,material_id,version_no_business,status,content_hash,requires_incoming_inspection) VALUES(1,?,?,?,1,'APPROVED','legacy-evidence',1)",context.actorId(),context.actorId(),m.get("id").asLong());var legacy=materials.get(m.get("id").asText());assertThat(legacy.get("status").asText()).isEqualTo("ACTIVE");assertThat(materials.list(0,20,m.get("materialCode").asText(),Map.of("status","ACTIVE")).total()).isEqualTo(1);materials.update(m.get("id").asText(),edit(legacy,"Direct basic edit",false),null,key());assertThat(jdbc.queryForObject("SELECT content_hash FROM md_material_version WHERE material_id=?",String.class,m.get("id").asLong())).isEqualTo("legacy-evidence");for(String action:List.of("versions","submit","approve"))mvc.perform(post("/api/v1/materials/"+m.get("id").asText()+"/"+action).with(user("test").authorities(new SimpleGrantedAuthority("master:material:approve"),new SimpleGrantedAuthority("master:material:update"))).header("Idempotency-Key",key()).contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isForbidden());}
 @Test void flatDtoRejectsVersionAndDisabledGate() throws Exception {var m=material();mvc.perform(put("/api/v1/materials/"+m.get("id").asText()).with(user("test").authorities(new SimpleGrantedAuthority("master:material:update"))).header("Idempotency-Key",key()).header("If-Match","0").contentType(MediaType.APPLICATION_JSON).content("{\"versionId\":\"1\",\"reason\":\"invalid\"}")).andExpect(status().isBadRequest());materials.disable(m.get("id").asText(),new MaterialCommands.Disable(0L,"withdraw"),null,key());assertThatThrownBy(()->queries.requireUsable(1,m.get("id").asLong(),Instant.now())).hasMessageContaining("MATERIAL_NOT_ACTIVE");}
 @Test void auditAvailabilityDoesNotControlBasicCreate(){doThrow(new IllegalStateException("injected audit failure")).when(audit).append(any());var row=material();assertThat(row.path("id").asText()).isNotBlank();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_audit_event WHERE actor_id=?",Long.class,context.actorId())).isZero();verify(audit,never()).append(any());}
 @Test void preferredMaintenanceHasNoAuditOrRootVersionDependency(){
  var m=material();var a=supplier("A");String k=key();doThrow(new IllegalStateException("injected audit failure")).when(audit).append(any());
  var row=relationships.assign(m.path("id").asText(),new SupplierCommands.Assign(null,null,List.of(link(a,true))),null,k);
  assertThat(row.path("suppliers")).hasSize(1);assertThat(jdbc.queryForObject("SELECT version_no FROM md_material WHERE id=?",Long.class,m.path("id").asLong())).isZero();
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,k)).isEqualTo(1);
  verify(audit,never()).append(any());
 }


 @Test void retiredNamesAreRejectedHiddenUnsearchableAndPreserved() throws Exception {
  var m=material();String id=m.path("id").asText(),legacy="RETIRED"+suffix;
  jdbc.update("UPDATE md_material SET generic_name=?,english_name=?,alias_name=? WHERE id=?",legacy,"Legacy English","Legacy alias",id);
  var result=materials.update(id,edit(m,"Still editable",false),null,key());
  for(String field:List.of("genericName","englishName","aliasName")){
   assertThat(result.has(field)).isFalse();assertThat(queries.snapshot(1,Long.parseLong(id)).has(field)).isFalse();
   var body=(ObjectNode)json.valueToTree(request("INVALID"+suffix,m.path("baseUnitId").asText()));body.put(field,"retired value");
   mvc.perform(post("/api/v1/materials").with(user("test").authorities(new SimpleGrantedAuthority("master:material:create"))).header("Idempotency-Key",key()).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(body))).andExpect(status().isBadRequest());
  }
  assertThat(materials.list(0,20,legacy,Map.of()).total()).isZero();
  assertThat(jdbc.queryForObject("SELECT generic_name FROM md_material WHERE id=?",String.class,id)).isEqualTo(legacy);
  assertThat(jdbc.queryForObject("SELECT english_name FROM md_material WHERE id=?",String.class,id)).isEqualTo("Legacy English");
  assertThat(jdbc.queryForObject("SELECT alias_name FROM md_material WHERE id=?",String.class,id)).isEqualTo("Legacy alias");
 }

 @Test void storageConditionPersistsAuditedAndDetached(){
  var input=(ObjectNode)json.valueToTree(request("STORAGE"+suffix,unit("STU","MASS").path("id").asText()));input.put("storageCondition","阴凉干燥");
  var m=materials.create(json.convertValue(input,MaterialCommands.Create.class),key());String id=m.path("id").asText();assertThat(m.path("storageCondition").asText()).isEqualTo("阴凉干燥");
  var captured=queries.snapshot(1,Long.parseLong(id)).deepCopy();var body=(ObjectNode)json.valueToTree(edit(m,"Storage maintenance",true));body.put("storageCondition","避光密闭");String k=key();var command=json.convertValue(body,MaterialCommands.Update.class);var updated=materials.update(id,command,null,k);
  assertThat(materials.update(id,command,null,k)).isEqualTo(updated);assertThat(materials.get(id).path("storageCondition").asText()).isEqualTo("避光密闭");assertThat(captured.path("storageCondition").asText()).isEqualTo("阴凉干燥");
  assertThat(jdbc.queryForObject("SELECT storage_condition FROM md_material WHERE id=?",String.class,id)).isEqualTo("避光密闭");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_audit_event WHERE object_id=? AND action='Material:UPDATE'",Long.class,id)).isZero();
  body.put("versionNo",updated.path("versionNo").asLong());body.put("storageCondition","x".repeat(501));assertThatThrownBy(()->materials.update(id,json.convertValue(body,MaterialCommands.Update.class),null,key())).isInstanceOf(IllegalArgumentException.class);
 }
 @Test void manufacturerBelongsToMaterialSupplierRelationship(){
  var m=material();var s=supplier("SOURCE");String id=m.path("id").asText();var r=new SupplierCommands.Assign(0L,"source manufacturer",List.of(new SupplierCommands.Relationship(s.path("id").asText(),true,true,null,"厂家甲")));String k=key();var assigned=relationships.assign(id,r,null,k);
  assertThat(assigned.path("suppliers").get(0).path("manufacturerName").asText()).isEqualTo("厂家甲");assertThat(relationships.assign(id,r,null,k)).isEqualTo(assigned);assertThat(relationships.assign(id,r,null,key()).path("suppliers")).hasSize(1);
  assertThat(supplierQueries.freezeSource(1,Long.parseLong(id),s.path("id").asLong(),Instant.now()).path("manufacturerName").asText()).isEqualTo("厂家甲");
  assertThat(materials.get(id).path("manufacturerName").asText()).isNotEqualTo("厂家甲");
  when(contexts.current()).thenReturn(new CurrentPlatformContext(2,context.actorId(),Set.of(),permissions,"s","r"));assertThatThrownBy(()->relationships.get(id)).isInstanceOf(NoSuchElementException.class);
 }

 @Test void freezeSourceUsesCurrentReadAfterConsistentSnapshot(){
  var tx=new TransactionTemplate(transactions);tx.setPropagationBehavior(org.springframework.transaction.TransactionDefinition.PROPAGATION_REQUIRES_NEW);
  // Committed uniquely-owned fixtures are deleted by exact IDs after concurrency verification.
  var fixture=tx.execute(t->{long a=actor("source_current_"+suffix);when(contexts.current()).thenReturn(new CurrentPlatformContext(1,a,Set.of(),permissions,"s","r"));var u=unit("CURU","MASS");var m=materials.create(request("CURM"+suffix,u.path("id").asText()),key());var supplier=supplier("CURS");relationships.assign(m.path("id").asText(),new SupplierCommands.Assign(0L,"initial",List.of(new SupplierCommands.Relationship(supplier.path("id").asText(),true,true,null,"厂家旧"))),null,key());return Map.of("material",m.path("id").asLong(),"supplier",supplier.path("id").asLong(),"unit",u.path("id").asLong(),"actor",a);});
  try {tx.execute(t->{assertThat(jdbc.queryForObject("SELECT manufacturer_name FROM md_material_supplier WHERE material_id=?",String.class,fixture.get("material"))).isEqualTo("厂家旧");
   tx.execute(w->{relationships.assign(fixture.get("material").toString(),new SupplierCommands.Assign(1L,"source changed between read and lock",List.of(new SupplierCommands.Relationship(fixture.get("supplier").toString(),true,true,null,"厂家新"))),null,key());return null;});
   assertThat(jdbc.queryForObject("SELECT manufacturer_name FROM md_material_supplier WHERE material_id=?",String.class,fixture.get("material"))).isEqualTo("厂家旧");
   try {assertThat(supplierQueries.freezeSource(1,fixture.get("material"),fixture.get("supplier"),Instant.now()).path("manufacturerName").asText()).isEqualTo("厂家新");}
   catch(com.hospital.mes.common.exception.ResourceConflictException conflict){assertThat(conflict).hasMessageContaining("Concurrent record change");} // MariaDB current-read snapshot conflict fails closed, never freezes the old source.
   return null;
  });tx.execute(t->{assertThat(supplierQueries.freezeSource(1,fixture.get("material"),fixture.get("supplier"),Instant.now()).path("manufacturerName").asText()).isEqualTo("厂家新");return null;});} finally {tx.execute(t->{jdbc.update("DELETE FROM md_material_supplier WHERE material_id=? AND supplier_id=?",fixture.get("material"),fixture.get("supplier"));jdbc.update("DELETE FROM md_material WHERE id=? AND material_code=?",fixture.get("material"),"CURM"+suffix);jdbc.update("DELETE FROM md_supplier WHERE id=? AND supplier_code=?",fixture.get("supplier"),"CURS"+suffix);jdbc.update("DELETE FROM md_unit WHERE id=? AND unit_code=?",fixture.get("unit"),"CURU"+suffix);jdbc.update("DELETE FROM platform_idempotency_record WHERE actor_id=?",fixture.get("actor"));jdbc.update("DELETE FROM sys_user WHERE id=? AND login_name_normalized=?",fixture.get("actor"),"source_current_"+suffix);return null;});}
 }
}
