package com.hospital.mes.release.application;
import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.*;import java.util.*;
import com.hospital.mes.masterdata.application.*;import com.hospital.mes.production.application.*;import com.hospital.mes.process.application.*;import com.hospital.mes.execution.application.*;import com.hospital.mes.ebr.application.*;import com.hospital.mes.qms.application.*;import com.hospital.mes.wms.application.*;import com.hospital.mes.wms.infrastructure.*;import com.hospital.mes.audit.attachment.application.*;import com.hospital.mes.common.exception.*;import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
/** Each producer authorizes its own source object; no frontend evidence is consumed. */
@org.springframework.stereotype.Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class BookSourceAdapter {
 private final MasterMutation mutations;private final ProductionQueryService batches;private final ProductionService production;private final ProcessQueryService process;private final ExecutionQueryService execution;private final EbrRuntimeService runtime;private final EbrRuntimeModel model;private final ClearanceService clearance;private final WmsStore wmsStore;private final WmsService wms;private final FinishedInspectionService quality;private final AttachmentService attachments;private final MasterQueryService units;private final ObjectMapper json;
 public BookSourceAdapter(MasterMutation mutations,ProductionQueryService batches,ProductionService production,ProcessQueryService process,ExecutionQueryService execution,EbrRuntimeService runtime,EbrRuntimeModel model,ClearanceService clearance,WmsStore wmsStore,WmsService wms,FinishedInspectionService quality,AttachmentService attachments,MasterQueryService units,ObjectMapper json){this.mutations=mutations;this.batches=batches;this.production=production;this.process=process;this.execution=execution;this.runtime=runtime;this.model=model;this.clearance=clearance;this.wmsStore=wmsStore;this.wms=wms;this.quality=quality;this.attachments=attachments;this.units=units;this.json=json;}
 public List<ObjectNode> read(long batch,BookDefinition.Entry entry){var c=mutations.context("ebr:form:view");long org=c.organizationId();var ctx=batches.batch(org,batch);var result=new ArrayList<ObjectNode>();
  switch(entry.kind()){
   case "FORM"->{var selected=new LinkedHashMap<String,JsonNode>();for(long op:execution.batchOperationIds(org,batch))for(var f:model.operationForms(org,op)){var render=runtime.render(f.getId().toString());if(render.path("formCode").asText().equals(entry.formCode()))selected.putIfAbsent(f.getId().toString(),render);}for(var f:selected.values()){var rows=json.createArrayNode();for(var field:f.path("fields")){if(!entry.fields().contains(field.path("fieldCode").asText())||!field.path("visible").asBoolean())continue;String standard="";for(var definition:f.path("definition").path("fields"))if(definition.path("fieldCode").equals(field.path("fieldCode")))standard=definition.path("helpText").asText("");rows.add(json.createArrayNode().add(field.path("label").asText()).add(standard).add(field.path("displayValue").asText("")).add(unit(org,field.path("unitId"))).add(sourceLabel(field.path("source").asText())));}boolean complete=runtime.evaluateOperation(org,f.path("operationExecutionId").asLong()).complete();String status=f.path("status").asText().equals("DRAFT")?"DRAFT":complete?"COMPLETE":"PENDING_REVIEW";var doc=document("FORM",f.path("id").asText(),f.path("formRevision").asText(),entry.title(),status,f, List.of("项目","标准/规定","实际记录","单位","记录来源"),rows);long executionId=execution.operation(org,f.path("operationExecutionId").asLong()).executionUnitId();for(var executionUnit:batches.batchFact(org,batch).path("executionUnits"))if(executionUnit.path("id").asLong()==executionId)doc.put("title",entry.title()+" / "+executionUnit.path("executionNo").asText("执行单元"));doc.put("formId",f.path("id").asText()).put("executionUnitId",Long.toString(executionId)).put("url","/mes/execution/"+executionId+"/forms/"+f.path("id").asText());doc.set("signatureIds",f.path("signatureIds"));result.add(doc);}}
   case "PROCESS_INSTRUCTIONS"->{mutations.context("process:package:view");var p=ctx.snapshot().path("process");var rows=json.createArrayNode();for(var op:p.path("route").path("operations"))if(entry.operationCode()==null||entry.operationCode().equals(op.path("operationCode").asText())){rows.add(json.createArrayNode().add(op.path("operationCode").asText()).add(op.path("operationName").asText()).add("固定工艺版本；未提供的SOP不推断").add(op.path("parameters").toString()));}result.add(document("PROCESS_INSTRUCTIONS",p.path(p.hasNonNull("processPackageId")?"currentDefinitionId":"packageVersionId").asText(),mutations.digest(p),entry.title(),"COMPLETE",p,List.of("工序标识","工序","规定来源","冻结过程参数"),rows));}
   case "PRODUCTION_ORDER"->{var b=batches.batchFact(org,batch);var order=production.order(b.path("productionOrderId").asText());mutations.context("master:product:view");var product=process.productLabels(org,order.path("productId").asLong());var rows=json.createArrayNode();rows.add(json.createArrayNode().add("生产指令号").add(order.path("orderNo").asText()));rows.add(json.createArrayNode().add("品名").add(product.productName()));rows.add(json.createArrayNode().add("规格").add(product.specification()));rows.add(json.createArrayNode().add("计划批量").add(order.path("plannedQty").asText()+" "+unit(org,order.path("unitId"))));rows.add(json.createArrayNode().add("计划生产日期").add(order.path("plannedDate").asText("未记录")));rows.add(json.createArrayNode().add("状态").add(stateLabel(order.path("status").asText())));result.add(document("PRODUCTION_ORDER",order.path("id").asText(),order.path("versionNo").asText(),entry.title(),Set.of("COMPLETED","CLOSED","IN_PROGRESS").contains(order.path("status").asText())?"COMPLETE":"DRAFT",order,List.of("记录项目","原始记录内容"),rows).put("url","/production/orders/"+order.path("id").asText()));}
   case "MATERIAL_ISSUES"->{mutations.context("wms:issue:view");for(var r:wmsStore.materialIssueMapper().selectList(new QueryWrapper<MaterialIssueEntity>().eq("org_id",org).eq("main_batch_id",batch).orderByAsc("issued_at","id"))){var issue=wms.get("MaterialIssue",r.getId().toString());var rows=json.createArrayNode();for(var line:issue.path("items")){var lot=wms.get("MaterialLot",line.path("materialLotId").asText());rows.add(json.createArrayNode().add(line.path("id").asText()).add(lot.path("lotNo").asText()).add(lot.path("manufacturerName").asText("未提供厂家资料")).add(line.path("issuedQty").asText()).add(unit(org,line.path("unitId"))));}result.add(document("MATERIAL_ISSUES",r.getId().toString(),issue.path("versionNo").asText(),issue.path("issueNo").asText(),r.getStatus().equals("CONFIRMED")?"COMPLETE":"DRAFT",issue,List.of("明细ID","真实物料批号","厂家资料","实发数量","单位"),rows).put("url","/wms/issues/"+r.getId()));}}
   case "CHARGES"->{mutations.context("mes:charge:view");for(var charge:execution.chargesForBatch(org,batch)){var lot=wms.get("MaterialLot",charge.path("materialLotId").asText());var rows=json.createArrayNode();rows.add(json.createArrayNode().add(lot.path("lotNo").asText()).add(charge.path("chargedQty").asText()).add(unit(org,charge.path("unitId"))).add(charge.path("status").asText()).add("实际投料来源；纯化水加至总量不推算实际投水量"));var data=(ObjectNode)charge.deepCopy();data.set("materialLot",lot);result.add(document("CHARGES",charge.path("id").asText(),charge.path("versionNo").asText(),entry.title(),charge.path("status").asText().equals("CONFIRMED")?"COMPLETE":"DRAFT",data,List.of("批号","实际投料","单位","状态","说明"),rows));}}
   case "CLEARANCE"->{mutations.context("mes:operation:view");for(long op:execution.batchOperationIds(org,batch)){var fact=execution.operationFact(org,op);if(entry.operationCode()!=null&&!matchesOperation(ctx.snapshot(),fact.path("operationDefId").asText(),entry.operationCode()))continue;for(var record:clearance.history(org,op)){boolean passed=record.path("outcome").asText().equals("PASS")&&record.path("review").path("decision").asText().equals("APPROVED")&&record.hasNonNull("signatureId")&&record.path("review").hasNonNull("signatureId");result.add(facts("CLEARANCE",record,entry.title(),passed?"COMPLETE":"PENDING_REVIEW","/mes/execution/"+execution.operation(org,op).executionUnitId()));}}}
   case "INSPECTION_REPORTS"->{mutations.context("qms:finished-request:view");mutations.context("qms:finished-report:view");for(var request:quality.sourceEvidence(org,batch).path("requests")){var req=quality.getRequest(request.path("id").asText());for(var report:req.path("reports")){var fact=quality.getReport(report.path("id").asText());result.add(facts("INSPECTION_REPORTS",fact,fact.path("reportNo").asText(),fact.path("status").asText().equals("APPROVED")?"COMPLETE":"PENDING_REVIEW","/finished/reports/"+fact.path("id").asText()));}}}
   case "ATTACHMENTS"->{for(String id:entry.attachmentIds()){var file=attachments.get(id);var fact=json.valueToTree(file);result.add(facts("ATTACHMENTS",fact,file.fileName(),"COMPLETE","/api/v1/attachments/"+id+"/content"));}}
   default->throw new IllegalArgumentException("Unknown directory source");
  }return List.copyOf(result);
 }
 public AttachmentService.Download attachment(String id){attachments.get(id);return attachments.download(id);}
 private boolean matchesOperation(JsonNode snapshot,String id,String code){for(var op:snapshot.path("process").path("route").path("operations"))if(op.path("operationDefId").asText().equals(id)&&op.path("operationCode").asText().equals(code))return true;return false;}
 private String unit(long org,JsonNode id){if(id.isMissingNode()||id.isNull()||id.asText().isBlank())return "";mutations.context("master:uom:view");return units.unitName(org,MasterMutation.id(id.asText()));}
 private ObjectNode facts(String kind,JsonNode fact,String title,String status,String url){var rows=json.createArrayNode();flatten(fact,"",rows);return document(kind,fact.path("id").asText(),fact.path("versionNo").asText(fact.path("recordVersion").asText()),title,status,fact,List.of("记录项目","原始记录内容"),rows).put("url",url);}
 private ObjectNode document(String kind,String id,String version,String title,String status,JsonNode snapshot,List<String> columns,ArrayNode rows){var n=json.createObjectNode().put("sourceType",kind).put("sourceId",id).put("sourceVersion",version).put("sourceHash",mutations.digest(stable(snapshot))).put("title",title).put("status",status);n.set("snapshot",stable(snapshot));n.set("columns",json.valueToTree(columns));n.set("rows",rows);return n;}
 private void flatten(JsonNode node,String prefix,ArrayNode rows){if(rows.size()>10000)throw new IllegalArgumentException("Source record detail limit");if(node.isObject()){node.fields().forEachRemaining(f->{if(!Set.of("allowedActions","authContextJson","signatureEvidenceJson","password","reauthToken").contains(f.getKey()))flatten(f.getValue(),prefix.isEmpty()?label(f.getKey()):prefix+" / "+label(f.getKey()),rows);});}else if(node.isArray()){int i=0;for(var value:node)flatten(value,prefix+" 第"+(++i)+"行",rows);}else rows.add(json.createArrayNode().add(prefix).add(node.isNull()?"未记录":node.asText()));}
 public static JsonNode stable(JsonNode original){JsonNode n=original.deepCopy();sanitize(n);return n;}
 private static void sanitize(JsonNode n){if(n instanceof ObjectNode o){o.remove(List.of("allowedActions","readonly","visible","validationState","authContextJson","password","reauthToken"));o.elements().forEachRemaining(BookSourceAdapter::sanitize);}else if(n.isArray())n.forEach(BookSourceAdapter::sanitize);}

 private String sourceLabel(String key){return switch(key){case "MANUAL"->"人工录入";case "CONTEXT"->"业务上下文";case "SYSTEM"->"系统记录";case "CALCULATED","CALCULATION"->"受控计算";default->"源记录（"+key+"）";};}
 private String stateLabel(String key){return switch(key){case "DRAFT"->"草稿";case "IN_PROGRESS"->"生产中";case "COMPLETED"->"已完成";case "CLOSED"->"已关闭";case "RELEASED"->"已下达";case "QA_RELEASED"->"QA已放行";case "REJECTED"->"已拒绝";default->key;};}
 private String label(String key){return switch(key){case "id"->"来源记录ID";case "orderNo"->"生产指令号";case "reportNo"->"检验报告号";case "plannedQty"->"计划批量";case "productId"->"产品记录";case "status"->"状态";case "items"->"项目明细";case "approvedBy"->"审批人员记录";case "signatureId"->"电子签名记录ID";case "signatureEvidence"->"电子签名证据";case "versionNo","recordVersion"->"来源版本";case "overallResult"->"检验结论";case "createdAt"->"创建时间";case "updatedAt"->"更新时间";case "unitId"->"单位记录（追溯）";case "plannedDate"->"计划生产日期";case "fileName"->"原文件名称";default->key;};}
}
