package com.hospital.mes.release.application;
import org.apache.pdfbox.Loader;import org.apache.pdfbox.pdmodel.*;import org.apache.pdfbox.pdmodel.common.PDRectangle;import org.apache.pdfbox.pdmodel.font.PDType0Font;import org.apache.pdfbox.pdmodel.interactive.documentnavigation.outline.*;import org.apache.pdfbox.pdmodel.interactive.documentnavigation.destination.PDPageFitDestination;import java.io.*;import java.util.*;
/** Book pages are actual rendered record PDFs. Originals stay retained; no merged signature claim. */
@org.springframework.stereotype.Component
public class BookPdfComposer {
 public record Part(String title,byte[] pdf){public Part{pdf=pdf.clone();}public byte[] pdf(){return pdf.clone();}}
 public byte[] compose(List<String> cover,List<Part> parts,String kind){if(parts.isEmpty()||parts.size()>300)throw new IllegalArgumentException("Book part limit");try(var doc=new PDDocument();var fs=getClass().getResourceAsStream("/fonts/NotoSansSC-Regular.ttf")){if(fs==null)throw new IllegalStateException("Licensed Chinese font unavailable");var font=PDType0Font.load(doc,fs,true);int tocPages=(parts.size()+34)/35;var coverPage=new PDPage(PDRectangle.A4);doc.addPage(coverPage);try(var s=new PDPageContentStream(doc,coverPage)){write(s,font,"电子批记录",60,760,22);int y=710;for(String line:cover){write(s,font,line,60,y,11);y-=30;}write(s,font,kind.equals("FINAL")?"正式归档":"审核副本 · 草稿",60,160,16);write(s,font,"电子签名以原始记录和证据为准；附件原件单独保留。",60,120,10);}
  var toc=new ArrayList<PDPage>();for(int i=0;i<tocPages;i++){var p=new PDPage(PDRectangle.A4);doc.addPage(p);toc.add(p);}var starts=new ArrayList<Integer>();var outline=new PDDocumentOutline();doc.getDocumentCatalog().setDocumentOutline(outline);
  for(var part:parts){starts.add(doc.getNumberOfPages()+1);if(part.pdf().length>25*1024*1024)throw new IllegalArgumentException("Source PDF limit");try(var source=Loader.loadPDF(part.pdf())){if(source.isEncrypted()||source.getNumberOfPages()<1||doc.getNumberOfPages()+source.getNumberOfPages()>1000)throw new IllegalArgumentException("Unsafe or oversized source PDF");int offset=doc.getNumberOfPages();var catalog=source.getDocumentCatalog().getCOSObject();for(String active:List.of("OpenAction","AA","Names","AcroForm"))catalog.removeItem(org.apache.pdfbox.cos.COSName.getPDFName(active));new org.apache.pdfbox.multipdf.PDFMergerUtility().appendDocument(doc,source);PDPage first=doc.getPage(offset);for(int p=offset;p<doc.getNumberOfPages();p++)doc.getPage(p).setAnnotations(List.of());var mark=new PDOutlineItem();mark.setTitle(part.title());var dest=new PDPageFitDestination();dest.setPage(first);mark.setDestination(dest);outline.addLast(mark);}}
  for(int i=0;i<toc.size();i++)try(var s=new PDPageContentStream(doc,toc.get(i))){write(s,font,"目录",50,770,18);int y=730;for(int j=i*35;j<Math.min((i+1)*35,parts.size());j++){String title=parts.get(j).title();if(title.codePointCount(0,title.length())>42)title=title.substring(0,title.offsetByCodePoints(0,28))+"…"+title.substring(title.offsetByCodePoints(0,title.codePointCount(0,title.length())-12));write(s,font,(j+1)+". "+title,50,y,10);write(s,font,Integer.toString(starts.get(j)),525,y,10);y-=19;}}
  int total=doc.getNumberOfPages(),pageNo=0;for(var page:doc.getPages()){pageNo++;try(var s=new PDPageContentStream(doc,page,PDPageContentStream.AppendMode.APPEND,true,true)){s.setNonStrokingColor(java.awt.Color.WHITE);s.addRect(35,8,Math.max(1,page.getMediaBox().getWidth()-70),18);s.fill();s.setNonStrokingColor(java.awt.Color.DARK_GRAY);write(s,font,"第 "+pageNo+" / "+total+" 页"+(kind.equals("FINAL")?" · 正式归档":" · 草稿"),40,16,8);}}
  doc.getDocumentCatalog().setDocumentOutline(outline);outline.openNode();doc.getDocumentInformation().setTitle("电子批记录");var out=new ByteArrayOutputStream();doc.save(out);if(out.size()>75*1024*1024)throw new IllegalArgumentException("Book output limit");return out.toByteArray();}catch(IOException ex){throw new IllegalStateException("Book PDF composition failed",ex);}}
 public byte[] imageAttachment(byte[] bytes){if(bytes.length>25*1024*1024)throw new IllegalArgumentException("Image attachment byte limit");try(var in=javax.imageio.ImageIO.createImageInputStream(new ByteArrayInputStream(bytes))){var readers=javax.imageio.ImageIO.getImageReaders(in);if(!readers.hasNext())throw new IllegalArgumentException("Unsupported image attachment");var reader=readers.next();try{reader.setInput(in);int width=reader.getWidth(0),height=reader.getHeight(0);if(width<1||height<1||(long)width*height>40_000_000L)throw new IllegalArgumentException("Image attachment pixel limit");var image=reader.read(0);try(var doc=new PDDocument()){var page=new PDPage(PDRectangle.A4);doc.addPage(page);var x=org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory.createFromImage(doc,image);float scale=Math.min(515f/width,742f/height);try(var stream=new PDPageContentStream(doc,page)){stream.drawImage(x,(595-width*scale)/2,(842-height*scale)/2,width*scale,height*scale);}var out=new ByteArrayOutputStream();doc.save(out);return out.toByteArray();}}finally{reader.dispose();}}catch(IOException ex){throw new IllegalStateException("Image attachment conversion failed",ex);}}
 private void write(PDPageContentStream s,PDType0Font font,String text,float x,float y,int size)throws IOException{if(text.length()>300)throw new IllegalArgumentException("Cover text limit");s.beginText();s.setFont(font,size);s.newLineAtOffset(x,y);s.showText(text.replaceAll("[\\p{Cntrl}]"," "));s.endText();}
}
