package com.hospital.mes.release.application;
import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.masterdata.application.*;import com.hospital.mes.process.application.*;import com.hospital.mes.ebr.application.*;import com.hospital.mes.production.application.*;import com.hospital.mes.reporting.application.*;import com.hospital.mes.common.exception.*;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.support.*;import org.springframework.transaction.annotation.Transactional;
import java.util.*;import org.springframework.transaction.annotation.Propagation;
@org.springframework.stereotype.Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class BookTemplateService implements ProductionBookPort {
 private final JdbcTemplate db;private final ObjectMapper json;private final MasterMutation mutations;private final ProcessQueryService process;private final EbrQueryService ebr;private final PrintService print;
 public BookTemplateService(JdbcTemplate db,ObjectMapper json,MasterMutation mutations,ProcessQueryService process,EbrQueryService ebr,PrintService print){this.db=db;this.json=json;this.mutations=mutations;this.process=process;this.ebr=ebr;this.print=print;}
 public JsonNode list(){var c=mutations.context("ebr:template:view");var out=json.createArrayNode();for(var row:db.queryForList("SELECT * FROM ebr_book_template WHERE org_id=? ORDER BY id DESC LIMIT 200",c.organizationId()))out.add(view(row));return out;}
 public JsonNode get(String id){var c=mutations.context("ebr:template:view");return view(row(c.organizationId(),MasterMutation.id(id),false));}
 @Transactional public JsonNode create(String code,JsonNode definition,String reason){var c=mutations.context("ebr:template:create");if(code==null||!code.matches("[A-Za-z][A-Za-z0-9_-]{0,63}"))throw new IllegalArgumentException("Invalid template code");reason(reason);var d=BookDefinition.parse(definition,json);db.queryForList("SELECT id FROM ebr_book_template WHERE org_id=? AND template_code=? FOR UPDATE",c.organizationId(),code);Integer revision=db.queryForObject("SELECT COALESCE(MAX(revision_no),0)+1 FROM ebr_book_template WHERE org_id=? AND template_code=?",Integer.class,c.organizationId(),code);var key=new GeneratedKeyHolder();db.update(conn->{var s=conn.prepareStatement("INSERT INTO ebr_book_template(org_id,template_code,revision_no,status,definition_json,definition_hash,created_by) VALUES(?,?,?,'DRAFT',?,?,?)",java.sql.Statement.RETURN_GENERATED_KEYS);s.setLong(1,c.organizationId());s.setString(2,code);s.setInt(3,revision);s.setString(4,definition.toString());s.setString(5,mutations.digest(definition));s.setLong(6,c.actorId());return s;},key);long id=Objects.requireNonNull(key.getKey()).longValue();var result=view(row(c.organizationId(),id,false));mutations.auditSnapshot(c,"EBR_BOOK_TEMPLATE_CREATE","EbrBookTemplate",id,null,result,reason,null);return result;}
 @Transactional public JsonNode transition(String id,String action,long expected,String reason){var c=mutations.context("ebr:template:publish");reason(reason);long target=MasterMutation.id(id);var r=row(c.organizationId(),target,true);if(((Number)r.get("version_no")).longValue()!=expected)throw new ResourceConflictException("VERSION_CONFLICT","Book template changed");var before=view(r);String next;if(action.equals("PUBLISH")&&r.get("status").equals("DRAFT")){var d=BookDefinition.parse(parse(r.get("definition_json")),json);validate(c.organizationId(),d);for(var other:db.queryForList("SELECT * FROM ebr_book_template WHERE org_id=? AND status='PUBLISHED' AND id<>? FOR UPDATE",c.organizationId(),target)){var od=BookDefinition.parse(parse(other.get("definition_json")),json);if(d.mappings().stream().anyMatch(m->od.mappings().stream().anyMatch(o->m.productId().equals(o.productId())&&m.packageVersionId().equals(o.packageVersionId())&&m.ebrTemplateVersionId().equals(o.ebrTemplateVersionId()))))throw new ComplianceException("BOOK_MAPPING_CONFLICT","Deactivate the previous book before publishing overlapping mapping");}next="PUBLISHED";}else if(action.equals("DEACTIVATE")&&r.get("status").equals("PUBLISHED"))next="INACTIVE";else throw new ComplianceException("BOOK_TRANSITION_INVALID","Invalid book template transition");db.update("UPDATE ebr_book_template SET status=?,published_by=COALESCE(published_by,?),published_at=COALESCE(published_at,CURRENT_TIMESTAMP(3)),version_no=version_no+1 WHERE org_id=? AND id=? AND version_no=?",next,c.actorId(),c.organizationId(),target,expected);var result=view(row(c.organizationId(),target,false));mutations.auditSnapshot(c,"EBR_BOOK_TEMPLATE_"+action,"EbrBookTemplate",target,before,result,reason,null);return result;}
 public void validate(long org,BookDefinition d){Map<String,JsonNode> portable=new HashMap<>();for(var m:d.mappings()){var p=process.requireUsableIdentified(org,MasterMutation.id(m.packageVersionId()));var e=ebr.requirePublished(org,MasterMutation.id(m.ebrTemplateVersionId()));if(!p.path("productId").asText().equals(m.productId())||!e.path("packageVersionId").asText().equals(m.packageVersionId()))throw new ComplianceException("BOOK_MAPPING_INVALID","Product/process/eBR mapping mismatch");for(var entry:d.entries())if(entry.kind().equals("FORM")){JsonNode f=null;for(var candidate:e.path("definition").path("forms"))if(candidate.path("formCode").asText().equals(entry.formCode()))f=candidate;if(f==null)throw new ComplianceException("BOOK_FORM_MISSING","Mapped form missing: "+entry.formCode());var op=process.requireOperation(org,MasterMutation.id(m.packageVersionId()),f.path("operationDefId").asLong());if(!op.operationCode().equals(entry.operationCode()))throw new ComplianceException("BOOK_OPERATION_MISMATCH","Stable operation binding mismatch");for(String field:entry.fields()){boolean found=false;for(var fd:f.path("fields"))found|=field.equals(fd.path("fieldCode").asText());if(!found)throw new ComplianceException("BOOK_FIELD_MISSING","Unknown stable field "+field);}var shape=(ObjectNode)f.deepCopy();shape.remove("operationDefId");var prior=portable.putIfAbsent(entry.formCode(),shape);if(prior!=null&&!prior.equals(shape))throw new ComplianceException("BOOK_SPECIFICATION_SCHEMA_MISMATCH","Shared specification form schemas differ");if(entry.printTemplateVersionId()!=null)print.requirePublishedTemplate(entry.printTemplateVersionId(),"EBR_PROCESS_FORM");}}}
 @Override @Transactional(propagation=Propagation.MANDATORY) public JsonNode freeze(long org,long productId,JsonNode processDefinition,JsonNode ebrDefinition){var candidates=new ArrayList<ObjectNode>();for(var r:db.queryForList("SELECT * FROM ebr_book_template WHERE org_id=? AND status='PUBLISHED' FOR UPDATE",org)){var raw=parse(r.get("definition_json"));if(!mutations.digest(raw).equals(r.get("definition_hash")))throw new ComplianceException("BOOK_TEMPLATE_CORRUPT","Book template digest mismatch");var d=BookDefinition.parse(raw,json);for(var m:d.mappings())if(m.productId().equals(Long.toString(productId))&&m.packageVersionId().equals(processDefinition.path("packageVersionId").asText())&&m.ebrTemplateVersionId().equals(ebrDefinition.path("templateVersionId").asText())){var n=json.createObjectNode();n.put("templateVersionId",r.get("id").toString()).put("templateRevision",((Number)r.get("revision_no")).intValue()).put("definitionHash",r.get("definition_hash").toString());n.set("definition",raw);n.set("mapping",json.valueToTree(m));n.set("batchFormCodes",json.valueToTree(d.batchFormCodes().stream().sorted().toList()));candidates.add(n);}}if(candidates.size()>1)throw new ComplianceException("BOOK_MAPPING_CONFLICT","Ambiguous published book mapping");return candidates.isEmpty()?json.nullNode():candidates.getFirst();}
 private Map<String,Object> row(long org,long id,boolean lock){var rows=db.queryForList("SELECT * FROM ebr_book_template WHERE org_id=? AND id=?"+(lock?" FOR UPDATE":""),org,id);if(rows.isEmpty())throw new NoSuchElementException("Book template not found");return rows.getFirst();}
 private ObjectNode view(Map<String,Object> r){var n=json.createObjectNode();n.put("id",r.get("id").toString()).put("templateCode",r.get("template_code").toString()).put("revision",((Number)r.get("revision_no")).intValue()).put("status",r.get("status").toString()).put("versionNo",((Number)r.get("version_no")).longValue()).put("definitionHash",r.get("definition_hash").toString()).put("createdBy",r.get("created_by").toString());n.set("definition",parse(r.get("definition_json")));return n;}
 private JsonNode parse(Object s){try{return json.readTree(s.toString());}catch(Exception e){throw new IllegalStateException("Invalid retained book JSON",e);}}
 private static void reason(String s){if(s==null||s.isBlank()||s.length()>1000)throw new IllegalArgumentException("Reason required");}
}
