package com.hospital.mes.release.application;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.hospital.mes.audit.application.*;
import com.hospital.mes.audit.attachment.application.*;
import com.hospital.mes.audit.idempotency.*;
import com.hospital.mes.audit.infrastructure.*;
import com.hospital.mes.common.exception.*;
import com.hospital.mes.ebr.application.*;
import com.hospital.mes.production.application.*;
import com.hospital.mes.production.infrastructure.*;
import com.hospital.mes.execution.application.*;
import com.hospital.mes.qms.application.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.release.domain.*;
import com.hospital.mes.release.infrastructure.*;
import org.springframework.transaction.annotation.*;
import java.util.*;
import java.time.*;

/** Read-only aggregation of owner evidence; archive metadata is deliberately outside the source digest. */
@org.springframework.stereotype.Service
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class EbrArchiveService implements FinishedReviewEvidencePort,AttachmentAccessPolicy {
 private final ProductionQueryService batches; private final ProductionStore production;private final ProductionViews views;
 private final ExecutionQueryService execution;private final EbrRuntimeService ebr;private final ProductionQualityService quality;private final MaterialBalanceService balance;
 private final com.hospital.mes.wms.application.WmsQueryService wms;private final ProductionQualityPlanService plans;private final ProductionQuantityService quantities;private final FinishedDecisionQuery decisions;private final EbrPdfManifestMapper manifests;private final AttachmentService files;
 private final com.hospital.mes.wms.application.FinishedQualityDecisionService stock;private final SignedRecordSupport signing;private final MasterMutation mutations;private final PlatformIdempotencyService keys;private final ObjectMapper json;private final SignatureMapper signatures;private final AuditEventMapper audits;private final EbrPdfRenderer renderer;
 public EbrArchiveService(ProductionQueryService batches,ProductionStore production,ProductionViews views,ExecutionQueryService execution,EbrRuntimeService ebr,ProductionQualityService quality,MaterialBalanceService balance,ProductionQuantityService quantities,ProductionQualityPlanService plans,com.hospital.mes.wms.application.WmsQueryService wms,FinishedDecisionQuery decisions,EbrPdfManifestMapper manifests,AttachmentService files,MasterMutation mutations,SignedRecordSupport signing,com.hospital.mes.wms.application.FinishedQualityDecisionService stock,PlatformIdempotencyService keys,ObjectMapper json,SignatureMapper signatures,AuditEventMapper audits,EbrPdfRenderer renderer){this.batches=batches;this.production=production;this.views=views;this.execution=execution;this.ebr=ebr;this.quality=quality;this.balance=balance;this.quantities=quantities;this.plans=plans;this.wms=wms;this.decisions=decisions;this.manifests=manifests;this.files=files;this.mutations=mutations;this.signing=signing;this.stock=stock;this.keys=keys;this.json=json;this.signatures=signatures;this.audits=audits;this.renderer=renderer;}
 @Transactional(readOnly=true) public JsonNode get(String id){var c=mutations.context("ebr:form:view");return readModel(c.organizationId(),MasterMutation.id(id));}
 @Transactional(readOnly=true) public JsonNode readModel(long org,long batch){var source=(ObjectNode)sourceEvidence(org,batch);var n=json.createObjectNode();n.put("mainBatchId",batch+"");n.put("definitionHash",source.path("ebr").path("definitionHash").asText());n.put("recordDigest",mutations.digest(source));n.set("batch",batches.batchFact(org,batch));n.set("processSnapshot",source.get("processSnapshot"));n.set("forms",projectEnvelopes(source.path("ebr").path("forms")));var q=quality.evidence(org,batch);n.set("qcTests",q.path("tests"));n.set("deviations",q.path("deviations"));n.set("balances",balance.evidence(org,batch));n.set("decisions",json.valueToTree(decisions.decisions(org,batch)));n.set("operations",views.read(execution.batchOperationIds(org,batch).stream().map(x->execution.operationFact(org,x)).toList()));n.set("charges",views.read(execution.chargesForBatch(org,batch)));n.set("quantityEvents",json.valueToTree(quantities.facts(org,batch)));var g=n.putArray("genealogy");for(var row:execution.genealogyForBatch(org,batch)){var item=(ObjectNode)row.deepCopy();item.retain("id","mainBatchId","inputMaterialLotId","chargeId","outputLotId","relationType");g.add(item);}var env=n.putArray("signatures");collectEnvelopes(source,env,new HashSet<>());var pdf=n.putArray("pdfManifests");for(var row:manifestRows(org,batch))pdf.add(manifestView(row));return n;}
 @Override @Transactional(readOnly=true) public JsonNode sourceEvidence(long org,long batch){var b=production.batches.get(org,batch);var n=json.createObjectNode();n.set("batch",batches.batchFact(org,batch));n.set("processSnapshot",b.getProcessSnapshotId()==null?json.nullNode():views.view(production.snapshots.get(org,b.getProcessSnapshotId())));n.set("ebr",ebr.archiveEvidence(org,batch));var ops=n.putArray("operations");for(long id:execution.batchOperationIds(org,batch))ops.add(execution.operationFact(org,id));n.set("charges",json.valueToTree(execution.chargesForBatch(org,batch)));n.set("quantityEvents",json.valueToTree(quantities.facts(org,batch)));var qe=n.putArray("quantitySignatures");for(String raw:quantities.envelopes(org,batch+":"+b.getVersionNo()))qe.add(parse(raw));var weighing=n.putArray("weighings");Set<Long> weighingIds=new TreeSet<>();for(var charge:n.path("charges"))if(charge.hasNonNull("weighingRecordId"))weighingIds.add(charge.path("weighingRecordId").asLong());for(long wid:weighingIds)weighing.add(execution.weighing(org,wid));n.set("genealogy",json.valueToTree(execution.genealogyForBatch(org,batch)));n.set("quality",quality.sourceEvidence(org,batch));n.set("qualityPlan",plans.sourceEvidence(org,batch));n.set("balance",balance.sourceEvidence(org,batch));n.set("decisions",json.valueToTree(decisions.sourceDecisionEvidence(org,batch)));var inventory=n.putObject("finishedInventory");if(b.getFinishedLotId()!=null){inventory.set("lot",json.valueToTree(wms.materialLot(org,b.getFinishedLotId())));inventory.set("ledger",json.valueToTree(wms.ledger(org,b.getFinishedLotId())));}
  Set<Long> signatureIds=new TreeSet<>();archiveFormSignatures(n,org,signatureIds);collectSignatureIds(n,signatureIds);var sig=n.putArray("signatureRecords");for(long id:signatureIds){var row=signatures.selectOne(new QueryWrapper<SignatureEntity>().eq("org_id",org).eq("id",id));if(row==null)throw new ComplianceException("SIGNATURE_EVIDENCE_MISSING","Referenced signature missing");var node=bean(row);node.remove("authContextJson");sig.add(node);}
  var trail=n.putArray("auditTrail");Map<String,Set<String>> targets=new TreeMap<>();target(targets,"MainBatch",batch+"");target(targets,"ProductionOrder",b.getProductionOrderId()+"");if(batches.batch(org,batch).snapshot().path("qualityPlan").hasNonNull("id"))target(targets,"ProductionQualityPlan",batches.batch(org,batch).snapshot().path("qualityPlan").path("id").asText());archiveTargets(n,targets);for(var entry:targets.entrySet())if(!entry.getValue().isEmpty())for(var row:audits.selectList(new QueryWrapper<AuditEventEntity>().eq("org_id",org).eq("object_type",entry.getKey()).in("object_id",entry.getValue()).orderByAsc("id")))trail.add(bean(row));sanitize(n);return n;}
 @Transactional public JsonNode generate(String target,ArchiveCommand command,String match,String key){command.validate();var c=mutations.context("ebr:pdf:generate");if(match==null||!match.equals("\""+command.versionNo()+"\""))throw new IllegalArgumentException("Exact quoted If-Match required");long batch=MasterMutation.id(target);String canonical=canonical(Map.of("batch",target,"command",command));var ownership=keys.begin(new IdempotencyCommand(c.organizationId(),c.actorId(),"EBR_PDF_GENERATE:"+target,key,canonical));if(ownership.type()==IdempotencyDecisionType.REPLAY)return parse(ownership.responseJson());if(ownership.type()!=IdempotencyDecisionType.OWNER)throw new ResourceConflictException("IDEMPOTENCY_CONFLICT","Archive command key conflict");var root=batches.lockBatch(c.organizationId(),batch);if(root.versionNo()!=command.versionNo())throw new ResourceConflictException("VERSION_CONFLICT","Batch evidence changed");var identity=batches.qualityIdentity(c.organizationId(),batch);if(identity.finishedLotId()!=null)stock.lockEvidence(c.organizationId(),identity.finishedLotId());var source=sourceEvidence(c.organizationId(),batch);String digest=mutations.digest(source);var chain=decisions.decisions(c.organizationId(),batch);Long decisionId=null;if(command.archiveKind().equals("FINAL")){if(chain.isEmpty()||!Set.of("QA_RELEASED","REJECTED").contains(root.status()))throw new ComplianceException("FINAL_ARCHIVE_DECISION_REQUIRED","A real finished QA decision is required");var latest=decisions.effective(c.organizationId(),batch);var actualLot=batches.qualityIdentity(c.organizationId(),batch).finishedLotId();if(latest==null||!Objects.equals(latest.getFinishedLotId(),actualLot)||!signing.valid(c.organizationId(),latest.getSignatureId())||!root.status().equals(latest.getDecision().equals("RELEASED")?"QA_RELEASED":"REJECTED")||!wms.materialLot(c.organizationId(),actualLot).path("qualityStatus").asText().equals(latest.getDecision()))throw new ComplianceException("FINAL_ARCHIVE_DECISION_REQUIRED","Valid effective QA signature and matching batch/lot decision required");decisionId=latest.getId();}
  var rows=manifestRows(c.organizationId(),batch);for(var row:rows)if(row.getArchiveKind().equals(command.archiveKind())&&row.getRecordDigest().equals(digest)){verifyFile(row);return complete(ownership,row);}
  var model=readModel(c.organizationId(),batch);if(!digest.equals(model.path("recordDigest").asText()))throw new ResourceConflictException("ARCHIVE_SOURCE_CHANGED","Archive source changed during generation");byte[] bytes=renderer.render(model,source,command.archiveKind());var file=files.createGenerated(c,"eBR-"+batch+"-"+command.archiveKind()+".pdf","application/pdf",bytes);var row=new EbrPdfManifestRow();row.setOrgId(c.organizationId());row.setCreatedBy(c.actorId());var now=LocalDateTime.now(ZoneOffset.UTC).truncatedTo(java.time.temporal.ChronoUnit.MILLIS);row.setCreatedAt(now);row.setMainBatchId(batch);row.setGenerationVersion(rows.stream().mapToInt(EbrPdfManifestRow::getGenerationVersion).max().orElse(0)+1);row.setDefinitionHash(model.path("definitionHash").asText());row.setRecordDigest(digest);row.setFileId(Long.parseLong(file.id()));row.setFileHash(file.sha256());row.setGeneratedBy(c.actorId());row.setGeneratedAt(now);row.setArchiveKind(command.archiveKind());row.setReleaseDecisionId(decisionId);manifests.insert(row);mutations.auditSnapshot(c,"EBR_PDF_GENERATED","EbrPdfManifest",row.getId(),null,manifestView(row),command.reason(),key);return complete(ownership,row);}
 @Transactional(readOnly=true) public JsonNode manifest(String batchId,String id){var c=mutations.context("ebr:form:view");long batch=MasterMutation.id(batchId);batches.batch(c.organizationId(),batch);var row=manifests.selectOne(new QueryWrapper<EbrPdfManifestRow>().eq("org_id",c.organizationId()).eq("main_batch_id",batch).eq("id",MasterMutation.id(id)));if(row==null)throw new NoSuchElementException("Archive manifest not found");verifyFile(row);return manifestView(row);}
 @Override public boolean mayRead(CurrentPlatformContext c,long file){return (c.hasPermission("ebr:form:view")||c.hasPermission("qa:batch-review"))&&manifests.selectCount(new QueryWrapper<EbrPdfManifestRow>().eq("org_id",c.organizationId()).eq("file_id",file))>0;}
 private List<EbrPdfManifestRow> manifestRows(long org,long batch){return manifests.selectList(new QueryWrapper<EbrPdfManifestRow>().eq("org_id",org).eq("main_batch_id",batch).orderByAsc("generation_version"));}
 private JsonNode complete(IdempotencyDecision d,EbrPdfManifestRow row){var result=manifestView(row);keys.complete(d.handle(),200,result.toString(),"EbrPdfManifest",row.getId()+"");return result;}
 private void verifyFile(EbrPdfManifestRow row){byte[] bytes=files.readContent(row.getOrgId(),row.getFileId()).content();if(!sha(bytes).equals(row.getFileHash()))throw new ComplianceException("ARCHIVE_FILE_HASH_MISMATCH","Stored archive hash mismatch");}
 private static String sha(byte[] bytes){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(bytes));}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private ObjectNode manifestView(EbrPdfManifestRow row){return bean(row);}
 private ObjectNode bean(Object object){ObjectNode n=json.valueToTree(object);var w=new org.springframework.beans.BeanWrapperImpl(object);for(var p:w.getPropertyDescriptors()){String name=p.getName();if(!n.hasNonNull(name))continue;var value=w.getPropertyValue(name);if(value instanceof Long)n.put(name,value.toString());else if(value instanceof LocalDateTime t)n.put(name,t.toInstant(ZoneOffset.UTC).toString());}return n;}
 private void archiveFormSignatures(ObjectNode source,long org,Set<Long> ids){var canonicalizer=new com.hospital.mes.audit.signature.Rfc8785SignatureCanonicalizer(json);for(var item:source.path("ebr").path("forms")){var form=item.path("form");String formId=form.path("id").asText();for(var sig:signatures.selectList(new QueryWrapper<SignatureEntity>().eq("org_id",org).eq("object_type","EBR_FORM_INSTANCE").eq("object_id",formId).orderByAsc("id"))){ids.add(sig.getId());List<JsonNode> eligible=new ArrayList<>();Instant cutoff=sig.getSignedAt().toInstant(ZoneOffset.UTC);for(var value:item.path("values"))if(!Instant.parse(value.path("recordedAt").asText()).isAfter(cutoff))eligible.add(value);boolean found=false;Map<String,JsonNode> current=new LinkedHashMap<>();for(int prefix=0;prefix<=eligible.size()&&!found;prefix++){if(prefix>0){var value=eligible.get(prefix-1);current.put(value.path("fieldCode").asText()+"|"+value.path("occurrencePath").asText(),value);}for(int revision=0;revision<=form.path("formRevision").asInt();revision++){var record=json.createObjectNode().put("formId",formId).put("formRevision",revision).put("definitionHash",source.path("ebr").path("definitionHash").asText());var values=record.putArray("values");List<String> evidence=new ArrayList<>();for(var raw:current.values()){var value=(ObjectNode)raw.deepCopy();value.put("superseded",false);values.add(value);evidence.add("FieldValueRevision:"+value.path("id").asText());}var object=new com.hospital.mes.audit.signature.SignableObject("EBR_FORM_INSTANCE",formId,revision,record,evidence);if(canonicalizer.digest(object).equals(sig.getRecordDigest())){((ArrayNode)item.path("signatures")).add(json.valueToTree(object));found=true;break;}}}if(!found)throw new ComplianceException("SIGNATURE_EVIDENCE_MISSING","Historic form signature cannot be reconstructed from original value lineage");}}}
 private static void sanitize(JsonNode n){if(n.isArray()){n.forEach(EbrArchiveService::sanitize);return;}if(n instanceof ObjectNode o){o.remove(List.of("allowedActions","reauthToken","password","authContextJson","pdfManifests"));o.elements().forEachRemaining(EbrArchiveService::sanitize);}}
 private JsonNode projectEnvelopes(JsonNode source){JsonNode n=source.deepCopy();replaceEnvelopes(n);return n;}
 private void replaceEnvelopes(JsonNode n){if(n.isArray()){for(int i=0;i<n.size();i++){JsonNode x=n.get(i);if(isEnvelope(x))((ArrayNode)n).set(i,envelope(x));else replaceEnvelopes(x);}return;}if(n.isObject())n.elements().forEachRemaining(this::replaceEnvelopes);}
 private static boolean isEnvelope(JsonNode n){return n.isObject()&&n.has("objectType")&&n.has("objectId")&&n.has("recordVersion")&&(n.has("record")||n.has("canonicalRecord"));}
 private ObjectNode envelope(JsonNode raw){var n=json.createObjectNode();n.set("objectType",raw.get("objectType"));n.set("objectId",raw.get("objectId"));n.set("recordVersion",raw.get("recordVersion"));n.set("canonicalRecord",raw.has("canonicalRecord")?raw.get("canonicalRecord"):raw.get("record"));n.set("evidenceIds",raw.path("evidenceIds").isArray()?raw.path("evidenceIds"):json.createArrayNode());return n;}
 private void collectEnvelopes(JsonNode n,ArrayNode output,Set<String> seen){if(isEnvelope(n)){var e=envelope(n);if(seen.add(e.toString()))output.add(e);return;}if(n.isContainerNode())n.elements().forEachRemaining(x->collectEnvelopes(x,output,seen));}
 private static void collectSignatureIds(JsonNode n,Set<Long> ids){if(n.isObject())n.fields().forEachRemaining(e->{if(e.getKey().endsWith("SignatureId")||e.getKey().equals("signatureId")){if(!e.getValue().isNull())ids.add(e.getValue().asLong());}else collectSignatureIds(e.getValue(),ids);});else if(n.isArray())n.forEach(x->collectSignatureIds(x,ids));}
 private static void target(Map<String,Set<String>> targets,String type,String id){targets.computeIfAbsent(type,k->new TreeSet<>()).add(id);}
 private static void archiveTargets(JsonNode n,Map<String,Set<String>> targets){if(n.isObject()){if(n.hasNonNull("objectType")&&n.hasNonNull("objectId"))target(targets,n.path("objectType").asText(),n.path("objectId").asText());if(n.hasNonNull("id")){String type=n.has("resultRevisionId")&&n.has("disposition")?"qms_production_test_review":n.has("capaId")&&n.has("reviewNo")?"qms_capa_review":n.has("deltaQty")?"InventoryLedger":n.has("targetQty")?"WeighingRecord":n.has("chargeId")&&n.has("inputMaterialLotId")?"Genealogy":n.has("equipmentUsageId")?"EquipmentRun":n.has("eventType")?"QuantityEvent":n.has("operationDefId")&&n.has("operationSeq")?"OperationExecution":n.has("chargedQty")?"MaterialCharge":n.has("sampleNo")?"qms_sample":n.has("qcSpecificationItemId")?"qms_production_test_instance":n.has("lotNo")?"MaterialLot":n.has("formDefId")?"EBR_FORM_INSTANCE":n.has("fieldDefId")?"EBR_FIELD_VALUE":n.has("balanceRuleId")?"BalanceResult":n.has("balanceResultId")?"BalanceInvestigation":n.has("deviationNo")?"qms_deviation":n.has("capaNo")?"qms_capa":n.has("productionTestInstanceId")?"qms_test_result_revision":n.has("releaseScope")?"ReleaseDecision":null;if(type!=null)target(targets,type,n.path("id").asText());}n.elements().forEachRemaining(x->archiveTargets(x,targets));}else if(n.isArray())n.forEach(x->archiveTargets(x,targets));}
 private String canonical(Object value){try{return new org.erdtman.jcs.JsonCanonicalizer(json.writeValueAsBytes(value)).getEncodedString();}catch(java.io.IOException e){throw new IllegalArgumentException(e);}}
 private JsonNode parse(String text){try{return json.readTree(text);}catch(java.io.IOException e){throw new IllegalStateException(e);}}
}
