package com.hospital.mes.release.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.audit.application.CurrentPlatformContext;
import com.hospital.mes.audit.idempotency.*;
import com.hospital.mes.audit.signature.SignatureMeaning;
import com.hospital.mes.common.exception.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.production.application.*;
import com.hospital.mes.execution.application.ExecutionQueryService;
import com.hospital.mes.ebr.application.EbrRuntimeService;
import com.hospital.mes.qms.application.*;
import com.hospital.mes.qms.infrastructure.*;
import com.hospital.mes.wms.application.*;
import com.hospital.mes.release.domain.*;
import org.springframework.transaction.annotation.*;
import org.springframework.context.ApplicationEventPublisher;
import java.util.*;
import static com.hospital.mes.production.application.ProductionInput.*;
import static com.hospital.mes.qms.domain.IncomingRules.gate;
@org.springframework.stereotype.Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class FinishedReleaseService {
 private final com.hospital.mes.audit.application.CurrentPlatformContextResolver contexts;private final ProductionQueryService batches;private final ProductionService production;private final ExecutionQueryService operations;private final EbrRuntimeService ebr;private final ProductionQualityService quality;private final MaterialBalanceService balances;private final WmsQueryService inventory;private final FinishedQualityDecisionService stock;private final FinishedDecisionQuery decisions;private final IncomingStore db;private final IncomingActorPort actors;private final MasterMutation mutations;private final SignedRecordSupport signing;private final PlatformIdempotencyService keys;private final FinishedReviewEvidencePort evidence;private final ObjectMapper json;private final ApplicationEventPublisher events;
 public FinishedReleaseService(com.hospital.mes.audit.application.CurrentPlatformContextResolver contexts,ProductionQueryService batches,ProductionService production,ExecutionQueryService operations,EbrRuntimeService ebr,ProductionQualityService quality,MaterialBalanceService balances,WmsQueryService inventory,FinishedQualityDecisionService stock,FinishedDecisionQuery decisions,IncomingStore db,IncomingActorPort actors,MasterMutation mutations,SignedRecordSupport signing,PlatformIdempotencyService keys,FinishedReviewEvidencePort evidence,ObjectMapper json,ApplicationEventPublisher events){this.contexts=contexts;this.batches=batches;this.production=production;this.operations=operations;this.ebr=ebr;this.quality=quality;this.balances=balances;this.inventory=inventory;this.stock=stock;this.decisions=decisions;this.db=db;this.actors=actors;this.mutations=mutations;this.signing=signing;this.keys=keys;this.evidence=evidence;this.json=json;this.events=events;}
 @Transactional public JsonNode review(String id){var c=mutations.context("qa:batch-review");return review(c.organizationId(),MasterMutation.id(id));}
 @Transactional(propagation=Propagation.MANDATORY) public JsonNode review(long org,long batch){
  var context=batches.lockBatch(org,batch);var identity=batches.qualityIdentity(org,batch);var n=json.createObjectNode();n.put("mainBatchId",Long.toString(batch));n.put("versionNo",context.versionNo());n.put("batchNo",batches.batchNumber(org,batch));n.put("status",context.status());var lots=n.putArray("finishedLots");if(identity.finishedLotId()!=null)lots.add(identity.finishedLotId().toString());
  var codes=new LinkedHashSet<String>();var gates=n.putArray("gates");
  List<String> stateCodes=Set.of("PENDING_QA","QA_RELEASED","REJECTED").contains(context.status())?List.of():List.of("FINISHED_RELEASE_STATE_CONFLICT");addGate(gates,codes,"BATCH_QA_STATE",stateCodes,List.of(batch));
  var plan=context.snapshot().path("qualityPlan");var planCodes=new ArrayList<String>();if(!plan.path("status").asText().equals("APPROVED"))planCodes.add("QUALITY_PLAN_REQUIRED");else if(!signing.valid(org,plan.path("signatureId").asLong()))planCodes.add("QUALITY_PLAN_SIGNATURE_INVALID");addGate(gates,codes,"QUALITY_PLAN",planCodes,plan.hasNonNull("id")?List.of(plan.path("id").asLong()):List.of());
  var ebrCodes=new LinkedHashSet<String>();var operationIds=operations.batchOperationIds(org,batch);if(operationIds.isEmpty())ebrCodes.add("BATCH_EXECUTION_INCOMPLETE");for(long op:operationIds){if(!operations.operation(org,op).operationStatus().equals("COMPLETED"))ebrCodes.add("BATCH_EXECUTION_INCOMPLETE");collectBlocker(()->{var actual=ebr.evaluateOperation(org,op);ebrCodes.addAll(actual.blockingCodes());ebr.requireOperationReview(org,op);},ebrCodes);}addGate(gates,codes,"EBR_REVIEW",List.copyOf(ebrCodes),operationIds);
  var qualityCodes=quality.blockingCodes(org,batch,true);addGate(gates,codes,"PRODUCTION_QC",qualityCodes,List.of());
  var balanceCodes=new ArrayList<String>();collectBlocker(()->balances.requireCheckpoint(org,batch,"QA_RELEASE",null),balanceCodes);addGate(gates,codes,"MATERIAL_BALANCE",balanceCodes,List.of());
  var lotCodes=new ArrayList<String>();if(identity.finishedLotId()==null)lotCodes.add("FINISHED_OUTPUT_REQUIRED");else{stock.lockEvidence(org,identity.finishedLotId());var lot=inventory.materialLot(org,identity.finishedLotId());if(!lot.path("materialId").asText().equals(plan.path("finishedMaterialId").asText()))lotCodes.add("FINISHED_LOT_BATCH_MISMATCH");if(!Set.of("QUARANTINE","RELEASED","REJECTED").contains(lot.path("qualityStatus").asText())||!Set.of("BLOCKED","AVAILABLE").contains(lot.path("inventoryStatus").asText()))lotCodes.add("FINISHED_LOT_LOCKED");if(!lot.hasNonNull("expiryDate")||!java.time.LocalDate.now(java.time.ZoneOffset.UTC).isBefore(java.time.LocalDate.parse(lot.path("expiryDate").asText())))lotCodes.add("FINISHED_LOT_EXPIRED");var ledger=inventory.ledger(org,identity.finishedLotId());if(ledger.stream().map(x->new java.math.BigDecimal(x.path("deltaQty").asText())).reduce(java.math.BigDecimal.ZERO,java.math.BigDecimal::add).signum()<=0)lotCodes.add("FINISHED_OUTPUT_REQUIRED");}addGate(gates,codes,"FINISHED_INVENTORY",lotCodes,identity.finishedLotId()==null?List.of():List.of(identity.finishedLotId()));
  var blocking=n.putArray("blockingCodes");codes.forEach(blocking::add);n.put("reviewDigest",mutations.digest(Map.of("source",evidence.sourceEvidence(org,batch),"gates",gates)));var actions=n.putArray("allowedActions");if(authorizedQa(org)&&stateCodes.isEmpty()&&identity.finishedLotId()!=null){if(codes.isEmpty())actions.add("RELEASE");actions.add("REJECT");}return n;
 }
 // Expected gate rejection must not poison the outer read-model transaction.
 // Roll back the check's savepoint (including any partial synchronization), then
 // retain its blocking code. Unexpected failures still roll back the whole request.
 private void collectBlocker(Runnable check,java.util.Collection<String> codes){
  var transaction=org.springframework.transaction.interceptor.TransactionAspectSupport.currentTransactionStatus();
  var savepoint=transaction.createSavepoint();
  try{check.run();}catch(ComplianceException blocked){transaction.rollbackToSavepoint(savepoint);codes.add(blocked.code());}
  finally{transaction.releaseSavepoint(savepoint);}
 }
 private boolean authorizedQa(long org){var c=contexts.current();if(c.organizationId()!=org||!c.hasPermission("qa:release")||!c.hasPermission("ebr:sign"))return false;try{actors.requireQualified(org,c.actorId(),"qa-release");return true;}catch(com.hospital.mes.common.exception.MesException ex){return false;}}
 private void addGate(ArrayNode gates,Set<String> codes,String code,List<String> blocking,List<Long> ids){var gate=gates.addObject();gate.put("code",code);gate.put("passed",blocking.isEmpty());var b=gate.putArray("blockingCodes");blocking.forEach(b::add);var e=gate.putArray("evidenceIds");ids.forEach(x->e.add(x.toString()));codes.addAll(blocking);}
 @Transactional(readOnly=true) public JsonNode get(String id){var c=mutations.context("qa:batch-review");return decisions.get(c.organizationId(),MasterMutation.id(id));}
 public List<JsonNode> sourceDecisions(long org,long batch){return decisions.sourceDecisionEvidence(org,batch);}
 @Transactional public JsonNode decide(JsonNode body,String header,String key){
  fields(body,"mainBatchId","finishedLotId","decision","releaseBasis","reason","versionNo","reviewDigest","supersedesDecisionId","signature");var c=mutations.context("qa:release");mutations.context("ebr:sign");long expected=quotedVersion(body,header),batch=strictId(body,"mainBatchId"),lot=strictId(body,"finishedLotId");String reason=text(body,"reason",1000),decision=text(body,"decision",30),digest=text(body,"reviewDigest",64);FinishedReleaseRules.requireDecision(decision);if(!digest.matches("[0-9a-f]{64}")||!text(body,"releaseBasis",30).equals("FULL_INSPECTION"))throw new IllegalArgumentException("Invalid finished release contract");
  var sig=body.get("signature");if(sig==null||!sig.isObject()||sig.size()!=1||!sig.path("reauthToken").isTextual()||sig.path("reauthToken").asText().isBlank())throw new IllegalArgumentException("Controlled signature reauthentication required");
  ObjectNode request=body.deepCopy();request.remove("signature");var claim=keys.begin(new IdempotencyCommand(c.organizationId(),c.actorId(),"FINISHED_QA_DECISION:"+batch,key,canonical(request)));if(claim.type()==IdempotencyDecisionType.REPLAY)return parse(claim.responseJson());if(claim.type()!=IdempotencyDecisionType.OWNER)throw new ResourceConflictException("IDEMPOTENCY_CONFLICT","Finished decision key conflict");
  try{
   var root=batches.lockBatch(c.organizationId(),batch);com.hospital.mes.qms.domain.IncomingRules.version(root.versionNo(),expected);var identity=batches.qualityIdentity(c.organizationId(),batch);gate(Objects.equals(identity.finishedLotId(),lot),"FINISHED_LOT_BATCH_MISMATCH","Exact batch-owned finished lot required");actors.requireQualified(c.organizationId(),c.actorId(),"qa-release");var effective=decisions.effective(c.organizationId(),batch);Long previous=body.hasNonNull("supersedesDecisionId")?strictId(body,"supersedesDecisionId"):null;FinishedReleaseRules.predecessor(effective==null?null:effective.getId(),previous);FinishedReleaseRules.resultingBatchStatus(root.status(),decision,effective!=null);if(effective!=null)independent(c.actorId(),effective.getDecisionBy());
   var current=review(c.organizationId(),batch);FinishedReleaseRules.digest(current.path("reviewDigest").asText(),digest);if(decision.equals("RELEASED")){gate(current.path("blockingCodes").isEmpty(),"RELEASE_GATE_FAILED",current.path("blockingCodes").toString());var qc=quality.sourceEvidence(c.organizationId(),batch);for(var test:qc.path("tests"))for(var result:test.path("results")){independent(c.actorId(),result.path("recordedBy").asLong());for(var review:result.path("reviews"))independent(c.actorId(),review.path("reviewedBy").asLong());}}
   var row=new ReleaseDecisionRow();row.setReleaseScope("FINISHED_PRODUCT");row.setMainBatchId(batch);row.setFinishedLotId(lot);row.setDecision(decision);row.setReleaseBasis("FULL_INSPECTION");row.setDecisionSource("USER_QA");row.setReason(reason);row.setDecisionBy(c.actorId());row.setDecisionAt(IncomingStore.now());row.setSupersedesDecisionId(previous);row.setEvidenceDigest(digest);row.setRuleEvidenceJson(canonical(current));
   var refs=new ArrayList<>(List.of("MainBatch:"+batch,"MaterialLot:"+lot));if(previous!=null)refs.add("ReleaseDecision:"+previous);var signature=signing.sign(c,"QA_RELEASE_DECISION",batch+":"+expected,expected,decision.equals("RELEASED")?SignatureMeaning.RELEASE:SignatureMeaning.REJECT,row,body.get("signature"),key,refs);row.setSignatureId(signature.id());row.setSignatureEvidenceJson(signature.envelope());db.insert(FinishedDecisionQuery.TABLE,row,c.organizationId(),c.actorId());
   stock.decide(c,lot,root.snapshot().path("qualityPlan").path("finishedMaterialId").asLong(),decision,effective!=null,reason,key);production.applyFinishedQaDecision(c,batch,expected,lot,decision,effective!=null,reason,key);mutations.auditSnapshot(c,"FINISHED_QA_"+decision,"ReleaseDecision",row.getId(),null,db.view(row),reason,key);events.publishEvent(new FinishedDecisionRecorded(c.organizationId(),c.actorId(),row.getId(),batch,lot,decision,digest));var response=decisions.view(row);keys.complete(claim.handle(),201,response.toString(),"ReleaseDecision",row.getId().toString());return response;
  }catch(RuntimeException ex){throw ScopedStore.translateConcurrency(ex);}
 }
 private static void independent(long actor,Long source){gate(source==null||source==0||actor!=source,"QA_INDEPENDENT_REQUIRED","Independent QA identity required");}
 private static long strictId(JsonNode body,String field){String value=text(body,field,30);if(!value.matches("[1-9][0-9]*"))throw new IllegalArgumentException("Canonical positive ID required: "+field);return MasterMutation.id(value);}
 private static long quotedVersion(JsonNode b,String header){if(!b.path("versionNo").canConvertToLong())throw new IllegalArgumentException("Bounded integer version required");if(header==null||!header.matches("\"(?:0|[1-9][0-9]*)\""))throw new IllegalArgumentException("Quoted If-Match required");return SignedRecordSupport.expected(b,header);}
 private String canonical(Object value){try{return new org.erdtman.jcs.JsonCanonicalizer(json.writeValueAsBytes(value)).getEncodedString();}catch(Exception ex){throw new IllegalArgumentException("Invalid source evidence",ex);}}
 private JsonNode parse(String value){try{return json.readTree(value);}catch(Exception ex){throw new IllegalStateException("Invalid stored decision",ex);}}
}
