package com.hospital.mes.integration.infrastructure;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.hospital.mes.common.exception.ValidationException;
import com.hospital.mes.integration.application.IntegrationMessageStore;
import com.hospital.mes.integration.domain.*;
import java.time.Instant;import java.time.LocalDateTime;import java.time.ZoneOffset;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Repository;

@Repository @ConditionalOnProperty(prefix="spring.datasource",name="url")
public class MybatisIntegrationMessageStore implements IntegrationMessageStore{
 private final InboxMapper inbox;private final OutboxMapper outbox;public MybatisIntegrationMessageStore(InboxMapper i,OutboxMapper o){inbox=i;outbox=o;}
 @Override public InboxMessage receive(InboxMessage m){InboxEntity e=inboxEntity(m,m.actorId(),m.receivedAt());try{inbox.insert(e);}catch(DuplicateKeyException duplicate){e=inbox.selectOne(new LambdaQueryWrapper<InboxEntity>().eq(InboxEntity::getOrgId,m.organizationId()).eq(InboxEntity::getSourceSystem,m.sourceSystem()).eq(InboxEntity::getMessageId,m.messageId()));}return inboxDomain(e);}
 @Override public InboxMessage findInbox(long org,long id){InboxEntity e=inbox.selectOne(new LambdaQueryWrapper<InboxEntity>().eq(InboxEntity::getOrgId,org).eq(InboxEntity::getId,id));if(e==null)throw new ValidationException("INTEGRATION_MESSAGE_NOT_FOUND","Integration message not found");return inboxDomain(e);}
 @Override public OutboxMessage enqueue(OutboxMessage m){OutboxEntity e=outboxEntity(m,m.actorId(),m.createdAt());try{outbox.insert(e);}catch(DuplicateKeyException duplicate){e=outbox.selectOne(new LambdaQueryWrapper<OutboxEntity>().eq(OutboxEntity::getOrgId,m.organizationId()).eq(OutboxEntity::getMessageId,m.messageId()));}return outboxDomain(e);}
 @Override public OutboxMessage findOutbox(long org,long id){OutboxEntity e=outbox.selectOne(new LambdaQueryWrapper<OutboxEntity>().eq(OutboxEntity::getOrgId,org).eq(OutboxEntity::getId,id));if(e==null)throw new ValidationException("INTEGRATION_MESSAGE_NOT_FOUND","Integration message not found");return outboxDomain(e);}
 @Override public boolean claimInbox(long org,long id,long version,long actor,Instant now){return inbox.claim(org,id,version,actor,local(now))==1;}
 @Override public boolean claimOutbox(long org,long id,long version,long actor,Instant now){return outbox.claim(org,id,version,actor,local(now))==1;}
 @Override public boolean saveInbox(InboxMessage m,long previous,long actor,Instant now){return inbox.save(inboxEntity(m,actor,now),previous)==1;}
 @Override public boolean saveOutbox(OutboxMessage m,long previous,long actor,Instant now){return outbox.save(outboxEntity(m,actor,now),previous)==1;}
 private static InboxEntity inboxEntity(InboxMessage m,long actor,Instant updatedAt){var e=new InboxEntity();var at=local(m.receivedAt());e.setId(m.id()==0?null:m.id());e.setOrgId(m.organizationId());e.setCreatedBy(m.actorId());e.setCreatedAt(at);e.setUpdatedBy(actor);e.setUpdatedAt(local(updatedAt));e.setVersionNo(m.versionNo());e.setSourceSystem(m.sourceSystem());e.setMessageId(m.messageId());e.setPayloadJson(m.payloadJson());e.setStatus(m.status().name());e.setReceivedAt(at);e.setProcessedAt(localNull(m.processedAt()));e.setRetryCount(m.retryCount());e.setNextRetryAt(localNull(m.nextRetryAt()));e.setLastErrorCode(m.lastErrorCode());e.setLastErrorMessage(m.lastErrorMessage());return e;}
 private static OutboxEntity outboxEntity(OutboxMessage m,long actor,Instant updatedAt){var e=new OutboxEntity();var at=local(m.createdAt());e.setId(m.id()==0?null:m.id());e.setOrgId(m.organizationId());e.setCreatedBy(m.actorId());e.setCreatedAt(at);e.setUpdatedBy(actor);e.setUpdatedAt(local(updatedAt));e.setVersionNo(m.versionNo());e.setMessageId(m.messageId());e.setTargetSystem(m.targetSystem());e.setEventType(m.eventType());e.setAggregateType(m.aggregateType());e.setAggregateId(m.aggregateId());e.setPayloadJson(m.payloadJson());e.setStatus(m.status().name());e.setRetryCount(m.retryCount());e.setNextRetryAt(localNull(m.nextRetryAt()));e.setPublishedAt(localNull(m.publishedAt()));e.setLastErrorCode(m.lastErrorCode());e.setLastErrorMessage(m.lastErrorMessage());return e;}
 private static InboxMessage inboxDomain(InboxEntity e){return new InboxMessage(e.getId(),e.getOrgId(),e.getCreatedBy(),e.getSourceSystem(),e.getMessageId(),e.getPayloadJson(),InboxStatus.valueOf(e.getStatus()),instant(e.getReceivedAt()),instantNull(e.getProcessedAt()),e.getRetryCount(),instantNull(e.getNextRetryAt()),e.getLastErrorCode(),e.getLastErrorMessage(),e.getVersionNo(),"PROCESSING".equals(e.getStatus())?instant(e.getUpdatedAt()):null);}
 private static OutboxMessage outboxDomain(OutboxEntity e){return new OutboxMessage(e.getId(),e.getOrgId(),e.getCreatedBy(),e.getMessageId(),e.getTargetSystem(),e.getEventType(),e.getAggregateType(),e.getAggregateId(),e.getPayloadJson(),OutboxStatus.valueOf(e.getStatus()),e.getRetryCount(),instantNull(e.getNextRetryAt()),instantNull(e.getPublishedAt()),e.getLastErrorCode(),e.getLastErrorMessage(),instant(e.getCreatedAt()),e.getVersionNo(),"DISPATCHING".equals(e.getStatus())?instant(e.getUpdatedAt()):null);}
 private static LocalDateTime local(Instant i){return i.atOffset(ZoneOffset.UTC).toLocalDateTime();}private static LocalDateTime localNull(Instant i){return i==null?null:local(i);}private static Instant instant(LocalDateTime v){return v.toInstant(ZoneOffset.UTC);}private static Instant instantNull(LocalDateTime v){return v==null?null:instant(v);}
}
