<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {attributes} from './attributes'
import {fieldTypes,fieldLabels,newField,moveItem} from './model'
import type {EbrDefinition,EbrField,EbrOperationChoice} from './types'
import ProcessLookup from '../process/ProcessLookup.vue'
const props=defineProps<{definition:EbrDefinition;editable:boolean;operationChoices:EbrOperationChoice[];savedDefinition:EbrDefinition}>()
type Node=Record<string,any>
const selected=ref<Node|null>(null),kind=ref(''),parent=ref<Node[]>([]),selectedForm=ref<Node|null>(null),selectedSection=ref<Node|null>(null),selectedGroup=ref<Node|null>(null),drag=ref<{rows:Node[];index:number}|null>(null)
const labels:Record<string,string>={sectionCode:'章节编码',title:'标题',sequenceNo:'顺序',repeatMode:'重复方式',visibilityRuleCode:'显示规则',pageBreakFlag:'分页',groupCode:'分组编码',layoutColumns:'列数',minOccurs:'最少次数',maxOccurs:'最多次数',formCode:'表单编码',formName:'表单名称',operationDefId:'关联工序',schemaVersion:'Schema 版本',fieldCode:'字段编码',label:'字段名称',fieldType:'字段类型',sourceType:'数据来源',dataType:'数据类型',unitId:'单位',precisionScale:'小数位数',requiredFlag:'必填',readonlyFlag:'只读',defaultExpr:'默认表达式',placeholder:'占位提示',helpText:'帮助说明',validationJson:'校验配置 JSON',optionCode:'选项编码',optionLabel:'选项名称',optionValue:'选项值',activeFlag:'启用',ruleCode:'规则编码',ruleType:'规则类型',triggerPoint:'触发时机',expression:'白名单表达式',severity:'严重程度',errorCode:'错误编码',messageTemplate:'提示信息',deviationTrigger:'触发偏差',objectScope:'对象范围',objectCode:'对象编码',meaning:'签名含义',requiredRole:'所需角色',reauthRequired:'要求再认证',invalidateOnChange:'更正后失效',reviewType:'复核类型',independentUserRequired:'要求独立人员'}
const title=computed(()=>({EbrSection:'章节属性',EbrGroup:'分组属性',EbrForm:'表单属性',EbrField:'字段属性',EbrOption:'选项属性',EbrRule:'规则属性',EbrSignatureRule:'签名规则',EbrReviewRule:'复核规则'}[kind.value]??'属性'))
const allGroups=computed(()=>props.definition.sections.flatMap(s=>s.groups)),allFields=computed(()=>props.definition.forms.flatMap(f=>f.fields))
function choose(node:Node,type:string,rows:Node[]){selected.value=node;kind.value=type;parent.value=rows;if(type==='EbrForm')selectedForm.value=node;if(type==='EbrSection')selectedSection.value=node;if(type==='EbrGroup')selectedGroup.value=node}
function code(prefix:string){const used=JSON.stringify(props.definition);let i=1;while(used.includes(`"${prefix}${i}"`))i++;return `${prefix}${i}`}
function add(type:string,fieldType:EbrField['fieldType']='TEXT'){
 let rows:Node[],node:Node
 if(type==='EbrSection'){rows=props.definition.sections;node={sectionCode:code('SEC'),title:'新章节',sequenceNo:rows.length+1,repeatMode:'NONE',visibilityRuleCode:null,pageBreakFlag:false,groups:[]}}
 else if(type==='EbrGroup'){if(!selectedSection.value)return;rows=selectedSection.value.groups;node={groupCode:code('GRP'),title:'新分组',sequenceNo:rows.length+1,layoutColumns:2,repeatMode:'NONE',minOccurs:null,maxOccurs:null}}
 else if(type==='EbrForm'){rows=props.definition.forms;node={formCode:code('FORM'),formName:'新表单',operationDefId:null,schemaVersion:'1.0',sequenceNo:rows.length+1,fields:[]}}
 else if(type==='EbrField'){if(!selectedForm.value)return;rows=selectedForm.value.fields;node={...newField(code('FIELD'),fieldType),groupCode:selectedGroup.value?.groupCode??null,sequenceNo:rows.length+1}}
 else if(type==='EbrOption'){if(kind.value!=='EbrField'||!selected.value)return;rows=selected.value.options;node={optionCode:code('OPT'),optionLabel:'新选项',optionValue:'',sequenceNo:rows.length+1,activeFlag:true}}
 else if(type==='EbrRule'){rows=props.definition.rules;node={ruleCode:code('RULE'),formCode:selectedForm.value?.formCode??null,fieldCode:null,ruleType:'VALIDATION',triggerPoint:'ON_SUBMIT',expression:'',severity:'BLOCK',errorCode:null,messageTemplate:null,deviationTrigger:false,activeFlag:true}}
 else if(type==='EbrSignatureRule'){rows=props.definition.signatureRules;node={objectScope:'FORM',objectCode:selectedForm.value?.formCode??'',meaning:'VERIFY',requiredRole:'',reauthRequired:true,sequenceNo:rows.length+1,invalidateOnChange:true}}
 else {rows=props.definition.reviewRules;node={objectScope:'FORM',objectCode:selectedForm.value?.formCode??'',reviewType:'VERIFY',requiredRole:'',independentUserRequired:true,sequenceNo:rows.length+1}}
 rows.push(node);choose(node,type,rows)
}
const stableKeys=['sectionCode','groupCode','formCode','fieldCode','optionCode','ruleCode']
function saved(node:Node){const key=stableKeys.find(k=>k in node);if(key)return JSON.stringify(props.savedDefinition).includes(`"${key}":${JSON.stringify(node[key])}`);const source=kind.value==='EbrSignatureRule'?props.savedDefinition.signatureRules:props.savedDefinition.reviewRules;return source.some((r:any)=>r.objectScope===node.objectScope&&r.objectCode===node.objectCode&&r.sequenceNo===node.sequenceNo)}
function remove(){if(!selected.value||saved(selected.value))return;const removed=selected.value;parent.value.splice(parent.value.indexOf(removed),1);if(selectedForm.value===removed)selectedForm.value=props.definition.forms[0]??null;if(selectedSection.value===removed){selectedSection.value=props.definition.sections[0]??null;selectedGroup.value=null}if(selectedGroup.value===removed)selectedGroup.value=null;selected.value=null}
function reorder(delta:number){if(!selected.value)return;moveItem(parent.value as {sequenceNo:number}[],parent.value.indexOf(selected.value),parent.value.indexOf(selected.value)+delta)}
function drop(rows:Node[],index:number){if(!props.editable||!drag.value||drag.value.rows!==rows)return;moveItem(rows as {sequenceNo:number}[],drag.value.index,index);drag.value=null}
watch(()=>props.definition,()=>{selected.value=null;selectedForm.value=props.definition.forms[0]??null;selectedSection.value=props.definition.sections[0]??null;selectedGroup.value=null;const f=props.definition.forms[0];if(f?.fields[0])choose(f.fields[0],'EbrField',f.fields)},{immediate:true})
</script>
<template><div class="ebr-designer">
<a-card v-if="editable" title="组件库" class="ebr-palette"><div class="ebr-components"><a-button @click="add('EbrSection')">添加章节</a-button><a-button :disabled="!selectedSection" @click="add('EbrGroup')">添加分组</a-button><a-button @click="add('EbrForm')">添加表单</a-button><p class="muted">选择表单后添加字段</p><a-button v-for="t in fieldTypes" :key="t" :aria-label="fieldLabels[t]" :disabled="!selectedForm" @click="add('EbrField',t)">{{fieldLabels[t]}}</a-button><a-button @click="add('EbrRule')">添加规则</a-button><a-button @click="add('EbrSignatureRule')">签名规则</a-button><a-button @click="add('EbrReviewRule')">复核规则</a-button></div></a-card>
<section class="ebr-canvas" aria-label="模板定义画布"><div class="ebr-paper"><p v-if="!definition.sections.length&&!definition.forms.length" class="muted">模板尚无定义，请添加章节与表单。</p>
<section v-for="(s,si) in definition.sections" :key="si" class="ebr-section" :draggable="editable" @dragstart.stop="drag={rows:definition.sections,index:si}" @dragover.prevent @drop.stop.prevent="drop(definition.sections,si)"><button class="ebr-node ebr-section-title" :class="{selected:selected===s}" @click="choose(s,'EbrSection',definition.sections)">{{s.title}} <small>{{s.sectionCode}}</small></button><div class="ebr-group-chips"><button v-for="g in s.groups" :key="g.groupCode" class="ebr-node" :class="{selected:selected===g}" @click="choose(g,'EbrGroup',s.groups);selectedSection=s">{{g.title||g.groupCode}} · {{g.repeatMode==='LIST'?'重复组':'分组'}}</button></div></section>
<section v-for="(f,fi) in definition.forms" :key="fi" class="ebr-form-block" :draggable="editable" @dragstart.stop="drag={rows:definition.forms,index:fi}" @dragover.prevent @drop.stop.prevent="drop(definition.forms,fi)"><button class="ebr-node ebr-form-title" :class="{selected:selected===f}" @click="choose(f,'EbrForm',definition.forms)">{{f.formName}} <small>{{f.formCode}}</small></button><p v-if="!f.fields.length" class="muted">选择此表单后，从组件库添加字段。</p><div v-for="(field,i) in f.fields" :key="i" class="ebr-field-node" :class="{selected:selected===field}" :draggable="editable" @dragstart.stop="drag={rows:f.fields,index:i}" @dragover.prevent @drop.stop.prevent="drop(f.fields,i)"><button class="ebr-node" @click="choose(field,'EbrField',f.fields);selectedForm=f"><span>{{field.label}} <span v-if="field.requiredFlag" class="required-mark">*</span></span><span class="ebr-control-preview">{{field.placeholder||fieldLabels[field.fieldType]}}<small v-if="field.groupCode"> · {{field.groupCode}}</small></span></button></div></section>
<section v-for="config in [{key:'rules',type:'EbrRule',title:'规则'},{key:'signatureRules',type:'EbrSignatureRule',title:'签名规则'},{key:'reviewRules',type:'EbrReviewRule',title:'复核规则'}]" :key="config.key" class="ebr-rule-list"><h3 v-if="(definition as any)[config.key].length">{{config.title}}</h3><button v-for="(r,i) in (definition as any)[config.key]" :key="i" class="ebr-node" :class="{selected:selected===r}" @click="choose(r,config.type,(definition as any)[config.key])">{{r.ruleCode||r.objectCode}} · {{r.ruleType||r.meaning||r.reviewType}}<small>{{r.expression||r.requiredRole}}</small></button></section>
</div></section>
<a-card :title="title" class="ebr-inspector"><p v-if="!selected" class="muted">选择画布中的定义以查看属性。</p><div v-else class="master-form"><label v-for="a in attributes[kind]" :key="a.key"><span class="form-field-label">{{labels[a.key]}}</span>
<ProcessLookup v-if="a.key==='unitId'" v-model="selected[a.key]" resource="units" label="单位" allow-clear :disabled="!editable"/>
<select v-else-if="a.key==='operationDefId'" v-model="selected[a.key]" :aria-label="labels[a.key]" class="master-native-input" :disabled="!editable"><option :value="null">不关联</option><option v-for="o in operationChoices" :key="o.id" :value="o.id">{{o.operationName}}（{{o.operationCode}}）</option></select>
<select v-else-if="a.key==='groupCode'&&kind==='EbrField'" v-model="selected[a.key]" aria-label="所属分组" class="master-native-input" :disabled="!editable||saved(selected)"><option :value="null">不分组</option><option v-for="g in allGroups" :key="g.groupCode" :value="g.groupCode">{{g.title||g.groupCode}}</option></select>
<select v-else-if="(a.key==='formCode'||a.key==='fieldCode')&&kind==='EbrRule'" v-model="selected[a.key]" :aria-label="labels[a.key]" class="master-native-input" :disabled="!editable"><option :value="null">模板范围</option><option v-for="r in a.key==='formCode'?definition.forms:allFields" :key="(r as any)[a.key]" :value="(r as any)[a.key]">{{(r as any).formName||(r as any).label}}（{{(r as any)[a.key]}}）</option></select>
<select v-else-if="a.options" v-model="selected[a.key]" :aria-label="labels[a.key]" class="master-native-input" :disabled="!editable"><option v-if="a.nullable" :value="null">未设置</option><option v-for="o in a.options" :key="o" :value="o">{{fieldLabels[o]||o}}</option></select>
<input v-else-if="a.type==='boolean'" v-model="selected[a.key]" :aria-label="labels[a.key]" type="checkbox" :disabled="!editable"/>
<textarea v-else-if="['expression','defaultExpr','helpText','validationJson','messageTemplate'].includes(a.key)" :value="selected[a.key]??''" @input="selected[a.key]=($event.target as HTMLTextAreaElement).value||(a.nullable?null:'')" :aria-label="labels[a.key]" :name="a.key" class="master-native-input" :maxlength="a.max" :disabled="!editable"/>
<input v-else-if="a.type==='integer'" :value="selected[a.key]??''" :aria-label="labels[a.key]" :name="a.key" type="number" :min="a.min" :max="a.maxNumber" class="master-native-input" :disabled="!editable" @input="selected[a.key]=($event.target as HTMLInputElement).value===''?null:Number(($event.target as HTMLInputElement).value)"/>
<input v-else :value="selected[a.key]??''" :aria-label="labels[a.key]" :name="a.key" class="master-native-input" :maxlength="a.max" :disabled="!editable||(stableKeys.includes(a.key)&&saved(selected))" @input="selected[a.key]=($event.target as HTMLInputElement).value||(a.nullable?null:'')"/>
</label><template v-if="kind==='EbrField'"><div class="form-full-row"><a-button v-if="editable" @click="add('EbrOption')">添加选项</a-button><button v-for="o in selected.options" :key="o.optionCode" class="ebr-node" @click="choose(o,'EbrOption',selected!.options)">{{o.optionLabel}} · {{o.optionValue}}</button></div></template><a-space v-if="editable" wrap><a-button v-if="'sequenceNo' in selected" @click="reorder(-1)">上移</a-button><a-button v-if="'sequenceNo' in selected" @click="reorder(1)">下移</a-button><a-button danger :disabled="saved(selected)" @click="remove">移除未保存项</a-button></a-space></div></a-card>
</div></template>
<style scoped>
.ebr-designer{display:grid;grid-template-columns:180px minmax(280px,1fr) 320px;gap:14px;align-items:start}.ebr-designer:not(:has(.ebr-palette)){grid-template-columns:minmax(280px,1fr) 320px}.ebr-components{display:grid;gap:8px}.ebr-components p{font-size:12px;margin:5px 0}.ebr-palette :deep(.ant-card-body),.ebr-inspector :deep(.ant-card-body){padding:14px}.ebr-canvas{padding:18px;background:#eaf0f6;border:1px solid #dbe3ee;border-radius:5px;min-width:0}.ebr-paper{background:#fff;min-height:650px;padding:22px;box-shadow:0 3px 15px #102b4e0a}.ebr-section{margin-bottom:18px}.ebr-node{display:block;border:1px solid transparent;background:transparent;text-align:left;color:inherit;font:inherit;cursor:pointer;border-radius:4px;padding:8px;width:100%;white-space:normal}.ebr-node:hover{background:#f5f8fd}.ebr-node:focus-visible{outline:2px solid #1677ff}.selected{border-color:#1677ff!important;background:#edf5ff!important}.ebr-node small{display:block;font-size:11px;color:#65758b;overflow-wrap:anywhere}.ebr-section-title{font-weight:650;color:#205597;background:#eef5ff}.ebr-form-title{font-size:17px;font-weight:650}.ebr-form-block{padding:12px;border:1px dashed #ccd9e7;margin:12px 0}.ebr-group-chips{display:flex;flex-wrap:wrap;margin-top:5px}.ebr-group-chips button{width:auto;font-size:12px}.ebr-field-node{border:1px solid transparent;margin-top:8px}.ebr-field-node .ebr-node{display:grid;grid-template-columns:minmax(70px,100px) minmax(0,1fr);align-items:center;gap:10px;font-size:13px}.ebr-control-preview{min-height:32px;border:1px solid #dbe3ee;border-radius:4px;padding:6px;color:#8b96a5}.ebr-inspector .master-form{grid-template-columns:1fr;gap:12px}.ebr-inspector .master-form>label{grid-template-columns:95px minmax(0,1fr);gap:8px}.ebr-inspector .form-field-label{font-size:12px}.ebr-inspector .master-form>.ant-space{padding-left:0}.ebr-inspector textarea{min-height:65px}.ebr-rule-list h3{font-size:14px}.ebr-rule-list>.ebr-node{border:1px solid #dbe3ee;margin:6px 0}
@media(max-width:1250px){.ebr-designer{grid-template-columns:150px minmax(260px,1fr)}.ebr-inspector{grid-column:1/-1}.ebr-inspector .master-form{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.ebr-designer,.ebr-designer:not(:has(.ebr-palette)){grid-template-columns:1fr}.ebr-components{grid-template-columns:repeat(2,minmax(0,1fr))}.ebr-components p{grid-column:1/-1}.ebr-inspector .master-form{grid-template-columns:1fr}.ebr-canvas{padding:8px}.ebr-paper{padding:12px;min-height:320px}.ebr-form-block{padding:5px}.ebr-inspector .master-form>label{grid-template-columns:100px minmax(0,1fr)}}
</style>
