<script setup lang="ts">
import {ref,reactive,computed,watch} from 'vue'
import {useRoute,useRouter,onBeforeRouteLeave} from 'vue-router'
import {api} from '../../api/http'
import {useControlledRequest} from '../../api/controlled'
import {useAuthStore} from '../../stores/auth'
import {clone,emptyDefinition,states,simulationInputs,triggers,duplicateFieldIssues,type SimulationRow} from './model'
import type {EbrDetail,EbrComparison,EbrLint,EbrSimulationResult} from './types'
import DefinitionDesigner from './DefinitionDesigner.vue'
import ProcessVersionPicker from './ProcessVersionPicker.vue'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),request=useControlledRequest(),{error,conflict,busy,fields}=request,record=ref<EbrDetail|null>(null),definition=ref(emptyDefinition()),savedDefinition=ref(emptyDefinition()),reason=ref(''),notice=ref(''),compareId=ref(''),comparison=ref<EbrComparison|null>(null),lint=ref<EbrLint|null>(null),simulation=ref<EbrSimulationResult|null>(null),simulationRows=ref<SimulationRow[]>([]),trigger=ref('ON_SUBMIT'),copyDefinition=ref(true),createForm=reactive({templateCode:'',packageVersionId:''})
const create=computed(()=>route.meta.mode==='create'),designer=computed(()=>route.meta.mode==='designer'),editable=computed(()=>designer.value&&can('EDIT','ebr:template:update')&&!busy.value&&!conflict.value),dirty=computed(()=>JSON.stringify(definition.value)!==JSON.stringify(savedDefinition.value))
function can(action:string,permission:string){return !!record.value?.allowedActions.includes(action)&&auth.can(permission)}
function sync(r:EbrDetail){record.value=r;definition.value=clone(r.definition);savedDefinition.value=clone(r.definition);simulationRows.value=r.definition.forms.flatMap(f=>f.fields).map(f=>({fieldCode:f.fieldCode,type:['NUMBER','TIMER','CALCULATED','INSTRUMENT_VALUE'].includes(f.fieldType)?'number':f.fieldType==='BOOLEAN'?'boolean':'string',value:''}));lint.value=null;simulation.value=null}
async function load(){request.clear();notice.value='';record.value=null;if(create.value)return;busy.value=true;try{sync(await api<EbrDetail>({url:`/ebr/templates/${route.params.id}`}))}catch(e){await request.failure(e)}finally{busy.value=false}}
async function save(){busy.value=true;error.value='';notice.value='';try{if(create.value){const result=await request.mutate<EbrDetail>('/ebr/templates','POST',createForm);await router.push({path:`/ebr/templates/${result.id}/designer`,query:route.query})}else{if(!reason.value.trim())throw Error('请填写操作原因');const r=record.value!;sync(await request.mutate<EbrDetail>(`/ebr/templates/${r.id}`,'PUT',{versionNo:r.versionNo,reason:reason.value,definition:definition.value},r.versionNo));notice.value='草稿已保存'}}catch(e){await request.failure(e)}finally{busy.value=false}}
async function action(name:string){busy.value=true;error.value='';notice.value='';try{if(name==='lint'&&dirty.value){const issues=duplicateFieldIssues(definition.value);if(issues.length){lint.value={valid:false,issues};return}}if(dirty.value)throw Error('请先保存草稿后执行该操作');if(!reason.value.trim())throw Error('请填写操作原因');const r=record.value!,body={versionNo:r.versionNo,reason:reason.value,...(name==='simulate'?{triggerPoint:trigger.value,inputs:simulationInputs(simulationRows.value)}:{})};const result=await request.mutate<EbrDetail|EbrLint|EbrSimulationResult>(`/ebr/versions/${r.id}/${name}`,'POST',body,r.versionNo);if(name==='lint')lint.value=result as EbrLint;else if(name==='simulate')simulation.value=result as EbrSimulationResult;else sync(result as EbrDetail)}catch(e){await request.failure(e)}finally{busy.value=false}}
async function newVersion(){busy.value=true;error.value='';try{if(dirty.value)throw Error('请先保存草稿');if(!reason.value.trim())throw Error('请填写操作原因');const r=record.value!,created=await request.mutate<EbrDetail>(`/ebr/templates/${r.id}/versions`,'POST',{versionNo:r.versionNo,reason:reason.value,copyDefinition:copyDefinition.value},r.versionNo);await router.push({path:`/ebr/templates/${created.id}/designer`,query:route.query})}catch(e){await request.failure(e)}finally{busy.value=false}}
async function compare(){comparison.value=null;try{comparison.value=await api({url:`/ebr/versions/${record.value!.id}/compare`,params:{otherVersionId:compareId.value}})}catch(e){await request.failure(e)}}
function switchVersion(id:string){void router.push({path:`/ebr/templates/${id}${designer.value?'/designer':''}`,query:route.query})}
onBeforeRouteLeave(()=>!dirty.value||window.confirm('离开页面将放弃未保存的定义，是否继续？'))
watch(()=>route.fullPath,load,{immediate:true})
</script>
<template><main :data-ui-template="create?'T2':designer?'Specialized':'T3'" class="admin-page master-page ebr-page"><header class="admin-page-header"><div><a-button type="link" @click="router.push({path:'/ebr/templates',query:route.query})">← 返回模板列表</a-button><h1>{{create?'新增 eBR 模板':designer?'eBR 模板设计器':'eBR 模板详情'}}</h1><p v-if="record">{{record.templateCode}} · V{{record.version}} · {{states[record.status]}}</p></div><a-space wrap><a-button v-if="record&&auth.can('audit:view')" @click="router.push({path:'/audit',query:{objectType:'EbrTemplateVersion',objectId:record.id}})">审计追踪</a-button><a-button v-if="!designer&&can('EDIT','ebr:template:update')" type="primary" @click="router.push({path:`/ebr/templates/${record!.id}/designer`,query:route.query})">编辑模板</a-button></a-space></header>
<a-alert v-if="error" type="error" :message="error" show-icon/><a-alert v-if="conflict" type="warning" message="记录已变化，输入已保留，请重新加载后继续。"><template #action><a-button @click="load">重新加载</a-button></template></a-alert><ul v-if="fields.length" class="error"><li v-for="(f,i) in fields" :key="i">{{f.field||f.path}}：{{f.message}}</li></ul><a-alert v-if="notice" type="success" :message="notice"/>
<a-card v-if="create" title="基本信息" class="form-section"><form class="master-form" @submit.prevent="save"><label><span class="form-field-label">模板编码</span><input v-model="createForm.templateCode" aria-label="模板编码" name="templateCode" class="master-native-input" required maxlength="64"/></label><ProcessVersionPicker v-model="createForm.packageVersionId"/><a-space><a-button html-type="submit" type="primary" :loading="busy" :disabled="!createForm.packageVersionId">创建模板</a-button><a-button @click="router.push({path:'/ebr/templates',query:route.query})">取消</a-button></a-space></form></a-card>
<template v-else-if="record"><a-card title="版本信息" class="form-section"><div class="master-form"><label><span class="form-field-label">当前版本</span><select :value="record.id" aria-label="当前版本" class="master-native-input" :disabled="dirty||busy" @change="switchVersion(($event.target as HTMLSelectElement).value)"><option v-for="v in record.versions" :key="v.id" :value="v.id">V{{v.version}} · {{states[v.status]}}</option></select></label><label><span class="form-field-label">审批记录</span><span class="master-read-value">{{record.approvedBy?`${record.approvedBy} · ${record.approvedAt}`:'尚未审批'}}</span></label><label><span class="form-field-label">生效时间</span><span class="master-read-value">{{record.effectiveFrom||'—'}}</span></label><label><span class="form-field-label">内容摘要</span><span class="ebr-digest">{{record.contentHash||'未发布'}}</span></label></div></a-card>
<a-alert v-if="record.status!=='DRAFT'" type="info" message="此版本只读，定义变更需创建新版本。"/>
<a-card v-if="record.allowedActions.length" title="受控操作" class="form-section ebr-footer"><div class="master-form"><label class="form-full-row"><span class="form-field-label">操作原因</span><textarea v-model="reason" name="reason" aria-label="操作原因" class="master-native-input" maxlength="1000"/></label><label v-if="can('NEW_VERSION','ebr:designer:edit')"><span class="form-field-label">复制当前定义</span><input v-model="copyDefinition" type="checkbox"/></label><a-space wrap><a-button v-if="designer&&can('EDIT','ebr:template:update')" type="primary" :loading="busy" :disabled="conflict" @click="save">保存草稿</a-button><a-button v-if="can('SUBMIT','ebr:template:submit')" :disabled="busy||dirty||conflict" @click="action('submit')">提交审批</a-button><a-button v-if="can('APPROVE','ebr:template:approve')" :disabled="busy||conflict" @click="action('approve')">批准模板</a-button><a-button v-if="can('PUBLISH','ebr:template:publish')" type="primary" :disabled="busy||conflict" @click="action('publish')">发布模板</a-button><a-button v-if="can('NEW_VERSION','ebr:designer:edit')" :disabled="busy||conflict" @click="newVersion">创建新版本</a-button></a-space></div></a-card>
<DefinitionDesigner :definition="definition" :saved-definition="savedDefinition" :editable="editable" :operation-choices="record.operationChoices??[]"/>
<a-card title="规则测试与差异" class="form-section ebr-tools"><a-tabs><a-tab-pane key="lint" tab="发布校验"><a-button v-if="can('LINT','ebr:designer:edit')" :disabled="busy||conflict" @click="action('lint')">运行 Lint</a-button><p v-if="lint">{{lint.valid?'校验通过':'校验未通过'}}</p><ul v-if="lint"><li v-for="issue in lint.issues" :key="issue.path+issue.code">{{issue.path}}：{{issue.message}}</li></ul></a-tab-pane><a-tab-pane key="simulate" tab="模拟运行"><p class="muted">以下为定义测试输入与服务器返回的模拟结果，不是生产记录。每行代表一次重复输入。</p><div class="master-form"><label><span class="form-field-label">触发时机</span><select v-model="trigger" class="master-native-input"><option v-for="t in triggers" :key="t">{{t}}</option></select></label><label v-for="r in simulationRows" :key="r.fieldCode"><span class="form-field-label">{{r.fieldCode}}（{{r.type}}）</span><textarea v-model="r.value" :aria-label="`模拟 ${r.fieldCode}`" class="master-native-input"/></label></div><a-button v-if="can('SIMULATE','ebr:designer:edit')" :disabled="busy||dirty||conflict" @click="action('simulate')">运行模拟</a-button><template v-if="simulation"><p>{{simulation.allowed?'模拟规则允许通过':'模拟被规则阻断'}}</p><div class="table-scroll"><table><thead><tr><th>规则</th><th>结果</th><th>输出</th><th>说明</th><th>引擎版本</th></tr></thead><tbody><tr v-for="r in simulation.results" :key="r.ruleCode"><td>{{r.ruleCode}}</td><td>{{r.passed?'通过':'未通过'}} · {{r.severity}}</td><td>{{r.outputValue}}</td><td>{{r.message}}</td><td>{{r.engineVersion}}</td></tr></tbody></table></div></template></a-tab-pane><a-tab-pane key="compare" tab="版本差异"><div class="master-form"><label><span class="form-field-label">比较版本</span><select v-model="compareId" class="master-native-input"><option value="">请选择</option><option v-for="v in record.versions.filter(v=>v.id!==record!.id)" :key="v.id" :value="v.id">V{{v.version}}</option></select></label><a-space><a-button :disabled="!compareId" @click="compare">比较</a-button></a-space></div><div v-if="comparison" class="table-scroll"><p v-if="!comparison.differences.length">定义无差异</p><table v-else><thead><tr><th>定义路径</th><th>比较前</th><th>比较后</th></tr></thead><tbody><tr v-for="d in comparison.differences" :key="d.path"><td>{{d.path}}</td><td class="ebr-difference">{{d.before}}</td><td class="ebr-difference">{{d.after}}</td></tr></tbody></table></div></a-tab-pane></a-tabs></a-card>
</template><a-spin v-else-if="busy"/></main></template>
<style scoped>.ebr-tools{margin-top:16px}.ebr-digest{overflow-wrap:anywhere;min-width:0;padding:6px 0}.ebr-difference{white-space:pre-wrap;max-width:420px;overflow-wrap:anywhere}.ebr-footer{position:relative}.ebr-page :deep(.process-lookup .ant-select){width:100%}</style>
