<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,errorMessage,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {states} from './model'
import ProcessVersionPicker from './ProcessVersionPicker.vue'
import ReadReference from '../master/ReadReference.vue'
import type {EbrSummary} from './types'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),keyword=ref(String(route.query.keyword??'')),status=ref(String(route.query.status??'')),processPackageId=ref(String(route.query.processPackageId??'')),error=ref(''),busy=ref(false),data=ref<Page<EbrSummary>>({items:[],total:0,page:0,size:20})
async function load(page=0){busy.value=true;error.value='';try{const params={keyword:keyword.value||undefined,status:status.value||undefined,processPackageId:processPackageId.value||undefined,page,size:20};await router.replace({query:Object.fromEntries(Object.entries(params).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]))});data.value=await api({url:'/ebr/templates',params})}catch(e){error.value=errorMessage(e)}finally{busy.value=false}}
function open(id='create',designer=false){void router.push({path:`/ebr/templates/${id}${designer?'/designer':''}`,query:route.query})}
onMounted(()=>load(Number(route.query.page??0)))
const columns=[{title:'模板名称',key:'templateName'},{title:'模板编码',dataIndex:'templateCode'},{title:'生产工艺',dataIndex:'processPackageId'},{title:'版本',dataIndex:'version'},{title:'状态',key:'status'},{title:'生效时间',dataIndex:'effectiveFrom'},{title:'操作',key:'actions'}]
</script>
<template><main data-ui-template="T1" class="admin-page master-page t1-query-list"><header class="admin-page-header"><div><h1>eBR 模板查询</h1></div><a-button v-if="auth.can('ebr:template:create')" type="primary" @click="open()">＋ 新增</a-button></header><a-card title="查询条件" class="query-card"><form class="query-form" @submit.prevent="load()"><label><span class="form-field-label">模板名称 / 编码</span><a-input v-model:value="keyword" aria-label="模板名称或编码查询"/></label><label><span class="form-field-label">状态</span><a-select show-search option-filter-prop="children" v-model:value="status" aria-label="模板状态" allow-clear><a-select-option v-for="(name,key) in states" :key="key" :value="key">{{name}}</a-select-option></a-select></label><ProcessVersionPicker v-model="processPackageId" :required="false"/><a-space><a-button @click="keyword='';status='';processPackageId='';load()">重置</a-button><a-button type="primary" html-type="submit">查询</a-button></a-space></form></a-card><a-alert v-if="error" type="error" :message="error" show-icon/><a-card title="数据列表" class="result-card"><a-table :columns="columns" :data-source="data.items" :loading="busy" :pagination="false" row-key="id" :scroll="{x:750}"><template #bodyCell="{column,record}"><span v-if="column.key==='templateName'">{{record.templateName||'未命名（历史模板）'}}</span><ReadReference v-if="column.dataIndex==='processPackageId'" field="processPackageId" :value="record.processPackageId"/><a-tag v-else-if="column.key==='status'">{{states[record.status]||record.status}}</a-tag><template v-if="column.key==='actions'"><a-button type="link" @click="open(record.id)">查看</a-button><a-button v-if="auth.can('ebr:template:update')&&record.allowedActions.includes('EDIT')" type="link" @click="open(record.id,true)">编辑</a-button></template></template></a-table><div class="table-footer"><span>共 {{data.total}} 条</span><a-pagination :current="data.page+1" :page-size="data.size" :total="data.total" :show-size-changer="false" @change="(p:number)=>load(p-1)"/></div></a-card></main></template>
