package com.hospital.mes.wms.domain;
import java.util.List;
public final class WmsCommands {
 private WmsCommands() {}
 public record WarehouseCreate(String warehouseCode,String warehouseName,String warehouseType) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record WarehouseUpdate(String warehouseCode,String warehouseName,String warehouseType,String reason,Long versionNo,String action) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record LocationCreate(String warehouseId,String locationCode,String locationName) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record LocationUpdate(String warehouseId,String locationCode,String locationName,String reason,Long versionNo,String action) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record ContainerCreate(String containerCode,String containerType) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record ContainerUpdate(String containerCode,String containerType,String reason,Long versionNo,String action) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record ReceiptItemInput(String materialId,String lotNo,String supplierLotNo,String manufacturerLotNo,String manufactureDate,String expiryDate,String retestDate,String receivedQty,String unitId,String packageSpec,Long packageCount,String locationId,String containerId,Boolean packageCheckPassed,Boolean sealCheckPassed,Boolean labelCheckPassed,Boolean damageCheckPassed,Boolean contaminationCheckPassed) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record ReceiptCreate(String receiptNo,String supplierId,String purchaseOrderNo,String deliveryNoteNo,String warehouseId,Boolean transportCheckPassed,List<ReceiptItemInput> items) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record ReceiptUpdate(String receiptNo,String supplierId,String purchaseOrderNo,String deliveryNoteNo,String warehouseId,Boolean transportCheckPassed,List<ReceiptItemInput> items,Long versionNo,String reason) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record Command(Long versionNo,String reason) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record InventoryMove(String materialLotId,String fromLocationId,String fromContainerId,String toLocationId,String toContainerId,String quantity,String unitId,Long versionNo,String reason) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record InventoryAdjust(String materialLotId,String locationId,String containerId,String deltaQty,String unitId,Long versionNo,String reason) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
 public record DependencyCommand(String mainBatchId,String issueNo,Long versionNo,String reason,List<com.fasterxml.jackson.databind.JsonNode> items) {@com.fasterxml.jackson.annotation.JsonAnySetter public void unknown(String name,Object value){throw new IllegalArgumentException("Unknown field: "+name);}}
}
