package com.hospital.mes.qms.api;
import com.fasterxml.jackson.databind.*;
import org.springframework.stereotype.Component;
import java.util.*;
@Component public class IncomingCommandValidator {
 private final JsonNode schemas;
 public IncomingCommandValidator(ObjectMapper json){try(var in=getClass().getResourceAsStream("/incoming-command-schemas.json")){schemas=json.readTree(in);}catch(Exception e){throw new IllegalStateException(e);}}
 public void validate(String schema,JsonNode value){check(schemas.required(schema),value,schema);}
 private void check(JsonNode schema,JsonNode value,String field){if(schema.has("$ref")){String r=schema.get("$ref").asText();check(schemas.required(r.substring(r.lastIndexOf('/')+1)),value,field);return;}if(value==null||value.isNull())throw new IllegalArgumentException(field+" must not be null");String type=schema.path("type").asText();switch(type){case "object"->{if(!value.isObject())throw new IllegalArgumentException(field+" must be object");for(var name:schema.path("required"))if(!value.hasNonNull(name.asText()))throw new IllegalArgumentException(name.asText()+" is required");value.fieldNames().forEachRemaining(n->{if(schema.has("properties")&&schema.get("properties").has(n))check(schema.get("properties").get(n),value.get(n),n);else if(schema.path("additionalProperties").isBoolean()&&!schema.path("additionalProperties").asBoolean())throw new IllegalArgumentException("Unknown field: "+n);});}case "array"->{if(!value.isArray()||value.size()<schema.path("minItems").asInt(0))throw new IllegalArgumentException("Invalid array: "+field);if(value.size()>1000)throw new IllegalArgumentException("Too many items");Set<String> unique=new HashSet<>();for(var v:value){check(schema.path("items"),v,field);if(schema.path("uniqueItems").asBoolean()&&!unique.add(v.toString()))throw new IllegalArgumentException("Duplicate item");}}case "string"->{if(!value.isTextual())throw new IllegalArgumentException(field+" must be a string");String v=value.asText();if(v.length()<schema.path("minLength").asInt(0)||v.length()>schema.path("maxLength").asInt(1000000)||schema.has("pattern")&&!v.matches(schema.get("pattern").asText()))throw new IllegalArgumentException("Invalid field: "+field);}case "integer"->{if(!value.isIntegralNumber()||value.asLong()<schema.path("minimum").asLong(Long.MIN_VALUE))throw new IllegalArgumentException("Invalid integer: "+field);}case "boolean"->{if(!value.isBoolean())throw new IllegalArgumentException(field+" must be boolean");}default->{}}
 if(schema.has("enum")){boolean ok=false;for(var v:schema.get("enum"))if(v.equals(value))ok=true;if(!ok)throw new IllegalArgumentException("Invalid enum: "+field);}}
}
