from pathlib import Path
root=Path(__file__).resolve().parents[1]
def modify(path,work):
 p=root/path;p.write_text(work(p.read_text(encoding='utf-8')),encoding='utf-8')
modify('frontend/mes-web/src/views/wms/MaterialLotView.vue',lambda s:s.replace("import WmsLookup from './WmsLookup.vue'","import WmsLookup from './WmsLookup.vue'\nimport FunctionalQualityActions from '../quality/FunctionalQualityActions.vue'").replace('</a-card></main></template>','</a-card><FunctionalQualityActions v-if="record" :row="record" kind="lot" @reload="load()"/></main></template>'))
modify('frontend/mes-web/src/views/production/ExecutionWorkbench.vue',lambda s:s.replace("import IncomingFacts from '../quality/IncomingFacts.vue'","import IncomingFacts from '../quality/IncomingFacts.vue'\nimport FunctionalQualityActions from '../quality/FunctionalQualityActions.vue'").replace('<IncomingFacts :value="operation"/>','<IncomingFacts :value="operation"/><FunctionalQualityActions :row="operation" kind="operation" @reload="load"/>'))
modify('frontend/mes-web/src/views/process/model.ts',lambda s:s.replace('export interface Operation {','export interface IpcDefinition {ipcCode:string;name:string;required:boolean;resultType:string;lowerLimit:string|null;upperLimit:string|null;expectedText:string|null;unitId:string|null;methodReference:string}\nexport interface Operation {').replace('clearanceRequired:boolean;parameters:Parameter[]','clearanceRequired:boolean;parameters:Parameter[];ipcDefinitions?:IpcDefinition[]'))
ui='''<a-tab-pane key="ipc" tab="过程检验 IPC"><a-card v-for="op in definition.operations" :key="op.operationCode" :title="`${op.operationCode} · ${op.operationName}`" class="process-operation"><div v-for="(ipc,i) in op.ipcDefinitions" :key="i" class="master-form"><label><span class="form-field-label">IPC 编码</span><input v-model="ipc.ipcCode" class="master-native-input" aria-label="IPC 编码" maxlength="64" :disabled="!editable"/></label><label><span class="form-field-label">检验名称</span><input v-model="ipc.name" class="master-native-input" aria-label="IPC 检验名称" maxlength="200" :disabled="!editable"/></label><label><span class="form-field-label">必检项目</span><input v-model="ipc.required" type="checkbox" aria-label="IPC 必检项目" :disabled="!editable"/></label><label><span class="form-field-label">结果类型</span><select v-model="ipc.resultType" class="master-native-input" aria-label="IPC 结果类型" :disabled="!editable" @change="ipc.lowerLimit=null;ipc.upperLimit=null;ipc.expectedText=null;ipc.unitId=null"><option value="NUMERIC">数值</option><option value="TEXT">文本</option></select></label><template v-if="ipc.resultType==='NUMERIC'"><label><span class="form-field-label">标准下限</span><input v-model="ipc.lowerLimit" class="master-native-input" aria-label="IPC 标准下限" :disabled="!editable"/></label><label><span class="form-field-label">标准上限</span><input v-model="ipc.upperLimit" class="master-native-input" aria-label="IPC 标准上限" :disabled="!editable"/></label><label><span class="form-field-label">检验单位</span><ProcessLookup v-model="ipc.unitId" resource="units" label="IPC 检验单位" allow-clear :disabled="!editable"/></label></template><label v-else><span class="form-field-label">预期结果</span><input v-model="ipc.expectedText" class="master-native-input" aria-label="IPC 预期结果" maxlength="1000" :disabled="!editable"/></label><label><span class="form-field-label">方法及版本引用</span><input v-model="ipc.methodReference" class="master-native-input" aria-label="IPC 方法及版本引用" maxlength="200" :disabled="!editable"/></label><a-button v-if="editable" danger @click="op.ipcDefinitions?.splice(i,1)">移除草稿 IPC</a-button></div><a-button v-if="editable" @click="(op.ipcDefinitions??=[]).push({ipcCode:'',name:'',required:true,resultType:'NUMERIC',lowerLimit:null,upperLimit:null,expectedText:null,unitId:null,methodReference:''})">添加 IPC</a-button></a-card><a-button v-if="editable" type="primary" :disabled="busy||conflict" @click="save('route')">保存路线与 IPC</a-button></a-tab-pane>'''
def process(s):
 s=s.replace('clearanceRequired:false,parameters:[]','clearanceRequired:false,parameters:[],ipcDefinitions:[]').replace('savedLines.value=formula.items.map','for(const op of definition.operations)op.ipcDefinitions??=[];savedLines.value=formula.items.map')
 marker='<a-tab-pane key="parameters"';index=s.index(marker);return s[:index]+ui+s[index:]
modify('frontend/mes-web/src/views/process/ProcessDetailView.vue',process)
print('Integrated approved functional controls into three existing pages')
