<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,errorMessage,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {states,type Product,type Package} from './model'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),isProduct=computed(()=>route.meta.resource==='products')
const title=computed(()=>isProduct.value?'产品管理':'生产工艺'),endpoint=computed(()=>isProduct.value?'products':'process-packages'),root=computed(()=>`/process/${isProduct.value?'products':'packages'}`)
const keyword=ref(''),status=ref(''),error=ref(''),busy=ref(false)
const data=ref<Page<Product|Package>>({items:[],total:0,page:0,size:20})
const columns=computed(()=>isProduct.value?[{title:'产品编码',dataIndex:'productCode'},{title:'产品名称',dataIndex:'productName'},{title:'剂型',dataIndex:'dosageForm'},{title:'规格',dataIndex:'specification'},{title:'状态',key:'status'},{title:'操作',key:'actions'}]:[{title:'生产工艺编码',dataIndex:'packageCode'},{title:'工序数',key:'operations'},{title:'适用关系',key:'scope'},{title:'状态',key:'status'},{title:'操作',key:'actions'}])
async function load(page=0){busy.value=true;error.value='';try{const params={keyword:keyword.value,status:status.value,page,size:20};await router.replace({query:Object.fromEntries(Object.entries(params).filter(([,v])=>v!==''&&v!==undefined).map(([k,v])=>[k,String(v)]))});data.value=await api({url:`/${endpoint.value}`,params})}catch(e){error.value=errorMessage(e)}finally{busy.value=false}}
function reset(){keyword.value='';status.value='';void load()}
function open(id?:string,edit=false){void router.push({path:`${root.value}/${id?`${id}${edit?'/edit':''}`:'create'}`,query:route.query})}
watch(()=>route.meta.resource,()=>{for(const [key,field] of Object.entries({keyword,status}))field.value=String(route.query[key]??'');void load(Number(route.query.page??0))},{immediate:true})
</script>
<template><main data-ui-template="T1" class="admin-page master-page t1-query-list"><header class="admin-page-header"><div><h1>{{title}}</h1></div><a-button v-if="auth.can(isProduct?'master:product:create':'process:package:create')" type="primary" @click="open()">＋ 新增</a-button></header>
<a-card title="查询条件" class="query-card"><form class="query-form" @submit.prevent="load()"><label><span class="form-field-label">编码 / 关键字</span><a-input v-model:value="keyword" allow-clear/></label><label><span class="form-field-label">状态</span><a-select show-search option-filter-prop="children" v-model:value="status" allow-clear style="min-width:140px"><a-select-option v-for="s in ['ACTIVE','INACTIVE']" :key="s" :value="s">{{states[s]}}</a-select-option></a-select></label><a-space><a-button @click="reset">重置</a-button><a-button type="primary" html-type="submit">查询</a-button></a-space></form></a-card>
<a-alert v-if="error" type="error" :message="error" show-icon/><a-card title="数据列表" class="result-card"><a-table :columns="columns" :data-source="data.items" :loading="busy" :pagination="false" row-key="id" :scroll="{x:900}"><template #bodyCell="{column,record}"><template v-if="column.key==='actions'"><a-button type="link" @click="open(record.id)">查看</a-button><a-button v-if="isProduct?auth.can('master:product:update'):auth.can('process:package:edit')&&record.status==='ACTIVE'" type="link" @click="open(record.id,true)">编辑</a-button></template><template v-else-if="column.key==='operations'">{{record.currentDefinition?.route?.operations?.length??0}}</template><template v-else-if="column.key==='scope'">{{record.productId?'历史产品关联':'通用工艺'}}</template><a-tag v-else-if="column.key==='status'">{{states[record.status]??'—'}}</a-tag></template></a-table><div class="table-footer"><span>共 {{data.total}} 条</span><a-pagination :current="data.page+1" :page-size="data.size" :total="data.total" :show-size-changer="false" @change="(p:number)=>load(p-1)"/></div></a-card></main></template>
