<script setup lang="ts">
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,errorMessage,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {states,type Product,type Package} from './model'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),isProduct=computed(()=>route.meta.resource==='products')
const title=computed(()=>isProduct.value?'产品管理':'工艺包管理'),endpoint=computed(()=>isProduct.value?'products':'process-packages'),root=computed(()=>`/process/${isProduct.value?'products':'packages'}`)
const keyword=ref(''),status=ref(''),version=ref(''),effectiveFrom=ref(''),productId=ref(''),products=ref<Product[]>([]),error=ref(''),busy=ref(false)
const data=ref<Page<Product|Package>>({items:[],total:0,page:0,size:20})
const columns=computed(()=>isProduct.value?[{title:'产品编码',dataIndex:'productCode'},{title:'产品名称',dataIndex:'productName'},{title:'剂型',dataIndex:'dosageForm'},{title:'规格',dataIndex:'specification'},{title:'状态',key:'status'},{title:'操作',key:'actions'}]:[{title:'产品',dataIndex:'productName'},{title:'工艺包编码',dataIndex:'packageCode'},{title:'版本',key:'version'},{title:'版本状态',key:'status'},{title:'生效时间',key:'effective'},{title:'审批人',key:'approver'},{title:'操作',key:'actions'}])
async function load(page=0){busy.value=true;error.value='';try{const params={keyword:keyword.value,status:status.value,page,size:20,...(!isProduct.value?{version:version.value,effectiveFrom:effectiveFrom.value?`${effectiveFrom.value}T00:00:00Z`:'',productId:productId.value}:{})};await router.replace({query:Object.fromEntries(Object.entries(params).filter(([,v])=>v!==''&&v!==undefined).map(([k,v])=>[k,String(v)]))});data.value=await api({url:`/${endpoint.value}`,params})}catch(e){error.value=errorMessage(e)}finally{busy.value=false}}
function reset(){keyword.value='';status.value='';version.value='';effectiveFrom.value='';productId.value='';void load()}
function open(id?:string,edit=false){void router.push({path:`${root.value}/${id?`${id}${edit?'/edit':''}`:'create'}`,query:route.query})}
async function searchProducts(keyword=''){if(auth.can('master:product:view')){try{products.value=(await api<Page<Product>>({url:'/products',params:{keyword,size:100}})).items}catch(e){error.value=errorMessage(e)}}}
watch(()=>route.meta.resource,()=>{for(const [key,field] of Object.entries({keyword,status,version,effectiveFrom,productId}))field.value=key==='effectiveFrom'?String(route.query[key]??'').slice(0,10):String(route.query[key]??'');void load(Number(route.query.page??0));if(!isProduct.value)void searchProducts()},{immediate:true})
</script>
<template><main class="admin-page master-page"><header class="admin-page-header"><div><h1>{{title}}</h1><p>产品与工艺定义 · 受控版本管理</p></div><a-button v-if="auth.can(isProduct?'master:product:create':'process:package:create')" type="primary" @click="open()">＋ 新增</a-button></header>
<a-card title="查询条件" class="query-card"><form class="query-form" @submit.prevent="load()"><label>编码 / 关键字<a-input v-model:value="keyword" allow-clear/></label><label>状态<a-select v-model:value="status" allow-clear style="min-width:140px"><a-select-option v-for="s in isProduct?['ACTIVE','INACTIVE']:['DRAFT','SUBMITTED','APPROVED','EFFECTIVE']" :key="s" :value="s">{{states[s]}}</a-select-option></a-select></label><template v-if="!isProduct"><label>产品<a-select v-model:value="productId" show-search :filter-option="false" allow-clear style="min-width:170px" @search="searchProducts"><a-select-option v-for="p in products" :key="p.id" :value="p.id">{{p.productName}}（{{p.productCode}}）</a-select-option></a-select></label><label>版本<input v-model="version" type="number" min="1" class="master-native-input"/></label><label>生效日期<input v-model="effectiveFrom" type="date" class="master-native-input"/></label></template><a-space><a-button @click="reset">重置</a-button><a-button type="primary" html-type="submit">查询</a-button></a-space></form></a-card>
<a-alert v-if="error" type="error" :message="error" show-icon/><a-card title="数据列表" class="result-card"><a-table :columns="columns" :data-source="data.items" :loading="busy" :pagination="false" row-key="id" :scroll="{x:900}"><template #bodyCell="{column,record}"><template v-if="column.key==='actions'"><a-button type="link" @click="open(record.id)">查看</a-button><a-button v-if="isProduct?auth.can('master:product:update'):auth.can('process:package:edit')&&record.selectedVersion?.status==='DRAFT'&&record.status==='ACTIVE'" type="link" @click="open(record.id,true)">编辑</a-button></template><a-tag v-else-if="column.key==='status'">{{states[isProduct?record.status:record.selectedVersion?.status]??'—'}}</a-tag><template v-else-if="column.key==='version'">V{{record.selectedVersion?.businessVersion}}</template><template v-else-if="column.key==='effective'">{{record.selectedVersion?.effectiveFrom??'—'}}</template><template v-else-if="column.key==='approver'">{{record.selectedVersion?.approval?.signerId??'—'}}</template></template></a-table><div class="table-footer"><span>共 {{data.total}} 条</span><a-pagination :current="data.page+1" :page-size="data.size" :total="data.total" :show-size-changer="false" @change="(p:number)=>load(p-1)"/></div></a-card></main></template>
