<script setup lang="ts">
import {computed,reactive,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,idempotencyKey,errorMessage,type Page} from '../../api/http'
import {useAuthStore} from '../../stores/auth'
import {states,type Product} from './model'
const route=useRoute(),router=useRouter(),auth=useAuthStore(),create=computed(()=>route.meta.mode==='create'),readonly=computed(()=>route.meta.mode==='view'),record=ref<Product|null>(null),error=ref(''),busy=ref(false),loading=ref(true),reason=ref('')
const form=reactive({productCode:'',productName:'',dosageForm:'',specification:'',baseUnitId:''}),units=ref<{id:string;unitName:string;unitCode:string}[]>([])
let pending='',key=idempotencyKey()
async function searchUnits(keyword=''){if(!auth.can('master:uom:view'))return;try{const list=(await api<Page<{id:string;unitName:string;unitCode:string}>>({url:'/units',params:{keyword,size:100}})).items;units.value=[...list,...units.value.filter(u=>u.id===form.baseUnitId&&!list.some(n=>n.id===u.id))]}catch(e){error.value=errorMessage(e)}}
async function load(){loading.value=true;error.value='';record.value=null;Object.assign(form,{productCode:'',productName:'',dosageForm:'',specification:'',baseUnitId:''});try{if(!create.value){record.value=await api<Product>({url:`/products/${route.params.id}`});Object.assign(form,record.value);await searchUnits();if(form.baseUnitId&&!units.value.some(u=>u.id===form.baseUnitId)&&auth.can('master:uom:view'))units.value.push(await api({url:`/units/${form.baseUnitId}`}))}else await searchUnits()}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
async function save(disable=false){busy.value=true;error.value='';try{if(!create.value&&!reason.value.trim())throw Error('请填写变更原因');const body=create.value?{productCode:form.productCode,productName:form.productName,dosageForm:form.dosageForm||null,specification:form.specification||null,baseUnitId:form.baseUnitId}:{versionNo:record.value!.versionNo,reason:reason.value,action:disable?'DISABLE':'UPDATE',productName:form.productName,dosageForm:form.dosageForm||null,specification:form.specification||null,baseUnitId:form.baseUnitId};const encoded=JSON.stringify(body);if(encoded!==pending){key=idempotencyKey();pending=encoded}const result=await api<Product>({url:create.value?'/products':`/products/${record.value!.id}`,method:create.value?'POST':'PUT',data:body,headers:{'Idempotency-Key':key,...(record.value?{'If-Match':`"${record.value.versionNo}"`}:{})}});pending='';reason.value='';if(route.path===`/process/products/${result.id}`)await load();else await router.push({path:`/process/products/${result.id}`,query:route.query})}catch(e){error.value=(e as Error).message==='请填写变更原因'?(e as Error).message:errorMessage(e)}finally{busy.value=false}}
watch(()=>route.path,load,{immediate:true})
</script>
<template><main class="admin-page master-page"><header class="admin-page-header"><div><a-button type="link" @click="router.push({path:'/process/products',query:route.query})">← 返回产品列表</a-button><h1>{{create?'新增产品':readonly?'产品详情':'编辑产品'}}</h1><p v-if="record">{{record.productCode}} · {{states[record.status]}}</p></div><a-space><a-button v-if="record&&auth.can('audit:view')" @click="router.push({path:'/audit',query:{objectType:'Product',objectId:record.id}})">审计追踪</a-button><a-button v-if="readonly&&auth.can('master:product:update')" type="primary" @click="router.push({path:`/process/products/${record!.id}/edit`,query:route.query})">编辑产品</a-button></a-space></header><a-alert v-if="error" type="error" :message="error" show-icon><template #action><a-button @click="load">重新加载</a-button></template></a-alert>
<a-card title="基本信息" class="form-section"><form class="master-form" @submit.prevent="save()"><label v-for="f in [{key:'productCode',label:'产品编码',max:64},{key:'productName',label:'产品名称',max:200},{key:'dosageForm',label:'剂型',max:100},{key:'specification',label:'规格',max:200}]" :key="f.key"><span class="form-field-label">{{f.label}}</span><input v-model="form[f.key as keyof typeof form]" class="master-native-input" :aria-label="f.label" :maxlength="f.max" :required="f.key==='productCode'||f.key==='productName'" :disabled="loading||busy||readonly||f.key==='productCode'&&!create"/></label><label><span class="form-field-label">基本单位</span><a-select v-model:value="form.baseUnitId" aria-label="基本单位" :disabled="loading||busy||readonly||!auth.can('master:uom:view')" show-search :filter-option="false" @search="searchUnits"><a-select-option v-for="u in units" :key="u.id" :value="u.id">{{u.unitName}}（{{u.unitCode}}）</a-select-option></a-select></label><label v-if="!create&&(!readonly||auth.can('master:product:update'))" class="form-full-row"><span class="form-field-label">变更原因</span><input v-model="reason" class="master-native-input" maxlength="1000"/></label><a-space class="form-full-row"><a-button v-if="!readonly" type="primary" html-type="submit" :loading="busy" :disabled="loading">保存产品</a-button><a-button v-if="record?.status==='ACTIVE'&&auth.can('master:product:update')" danger :disabled="busy||loading" @click="save(true)">停用产品</a-button></a-space></form></a-card></main></template>
