package com.hospital.mes.wms.application;

import static com.hospital.mes.wms.application.MaterialRequestService.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.hospital.mes.audit.application.CurrentPlatformContext;
import com.hospital.mes.audit.signature.SignatureMeaning;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.wms.domain.FinishedGoodsRules;
import com.hospital.mes.wms.infrastructure.*;
import java.math.*;
import java.time.*;
import java.util.*;
import org.springframework.transaction.annotation.*;

/** WMS-owned finished receiving and shipment commands; quantities originate in signed production facts. */
@org.springframework.stereotype.Service
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class FinishedGoodsService {
 private final FinishedInboundRequestMapper inboundMapper;
 private final FinishedShipmentMapper shipmentMapper;
 private final ScopedStore<FinishedInboundRequestEntity> inbound;
 private final ScopedStore<FinishedShipmentEntity> shipments;
 private final WmsProductionContextPort production;
 private final WmsStore stock;
 private final WmsProductionService reservations;
 private final MasterQueryService units;
 private final MasterMutation mutations;
 private final SignedRecordSupport signing;
 private final ObjectMapper json;
 private final org.springframework.context.ApplicationEventPublisher events;
 private final com.hospital.mes.audit.application.CurrentPlatformContextResolver contexts;
 public FinishedGoodsService(FinishedInboundRequestMapper i,FinishedShipmentMapper s,WmsProductionContextPort p,WmsStore stock,WmsProductionService reservations,MasterQueryService units,MasterMutation m,SignedRecordSupport signing,ObjectMapper json,com.hospital.mes.audit.application.CurrentPlatformContextResolver contexts,org.springframework.context.ApplicationEventPublisher events){
  this.inboundMapper=i;this.shipmentMapper=s;this.inbound=new ScopedStore<>(i,List.of("request_no"),Map.of("status","status","mainBatchId","main_batch_id"));this.shipments=new ScopedStore<>(s,List.of("shipment_no","receiving_party"),Map.of("status","status","mainBatchId","main_batch_id"));this.production=p;this.stock=stock;this.reservations=reservations;this.units=units;this.mutations=m;this.signing=signing;this.json=json;this.contexts=contexts;this.events=events;
 }
 private static LocalDateTime now(){return LocalDateTime.now(ZoneOffset.UTC).truncatedTo(java.time.temporal.ChronoUnit.MILLIS);}
 private static long expected(JsonNode body,String header){if(header==null||!header.matches("\"(?:0|[1-9][0-9]*)\""))throw new IllegalArgumentException("Exact quoted If-Match required");return version(body,header);}
 private static void match(long actual,long expected){if(actual!=expected)throw new com.hospital.mes.common.exception.ResourceConflictException("VERSION_CONFLICT","Record version changed");}
 private BigDecimal exact(long org,BigDecimal amount,long source,long target,long material){var c=units.convert(org,source,target,material,amount.abs());var value=amount.abs().multiply(new BigDecimal(c.factor()));gate(value.compareTo(new BigDecimal(c.convertedValue()))==0,"QUANTITY_PRECISION_LOSS");try{value=value.setScale(6,RoundingMode.UNNECESSARY);}catch(ArithmeticException e){throw new IllegalArgumentException("Exact quantity required");}gate(value.precision()-value.scale()<=12,"QUANTITY_OUT_OF_RANGE");return amount.signum()<0?value.negate():value;}
 private JsonNode snapshot(long org,long batch){
  var fact=production.batchFact(org,batch);gate(fact.hasNonNull("finishedLotId"),"FINISHED_OUTPUT_REQUIRED");var lot=stock.materialLot().get(org,fact.path("finishedLotId").asLong());var material=read(lot.getMaterialSnapshotJson());long unit=material.path("baseUnitId").asLong();gate(unit>0,"FINISHED_UNIT_REQUIRED");
  var all=production.finishedOutputs(org,batch);Set<Long> outputs=new HashSet<>();all.stream().filter(x->"OUTPUT".equals(x.path("eventType").asText())).forEach(x->outputs.add(x.path("id").asLong()));var selected=json.createArrayNode();BigDecimal quantity=BigDecimal.ZERO;
  for(var row:all)if("OUTPUT".equals(row.path("eventType").asText())||row.hasNonNull("reversalOfId")&&outputs.contains(row.path("reversalOfId").asLong())){gate(row.path("materialLotId").asLong()==lot.getId(),"FINISHED_OUTPUT_LOT_MISMATCH");selected.add(row);quantity=quantity.add(exact(org,new BigDecimal(row.path("amount").asText()),row.path("unitId").asLong(),unit,lot.getMaterialId()));}
  gate(quantity.signum()>0,"FINISHED_OUTPUT_REQUIRED");var n=json.createObjectNode();n.put("mainBatchId",batch+"");n.put("productId",fact.path("productId").asText());n.put("materialLotId",lot.getId()+"");n.put("quantity",quantity.setScale(6).toPlainString());n.put("unitId",unit+"");n.set("completedAt",fact.path("completedAt"));n.set("outputs",selected);return n;
 }
 private JsonNode read(String source){try{return json.readTree(source);}catch(java.io.IOException e){throw new IllegalStateException("Invalid frozen source",e);}}
 @Transactional public JsonNode createInbound(JsonNode body,String key){fields(body,"requestNo","mainBatchId","reason","createInspectionDraft","inspectionRequestNo");if(body.has("createInspectionDraft")&&!body.path("createInspectionDraft").isBoolean())throw new IllegalArgumentException("createInspectionDraft must be boolean");boolean draft=body.path("createInspectionDraft").asBoolean(false);if(!draft&&body.has("inspectionRequestNo"))throw new IllegalArgumentException("inspectionRequestNo requires createInspectionDraft");String inspectionNo=draft?text(body,"inspectionRequestNo",80):null;var c=mutations.context("wms:finished-inbound:create");if(draft)mutations.context("qms:finished-request:create");return mutations.execute(c,"FINISHED_INBOUND_CREATE",key,body,()->{
  long batch=id(body,"mainBatchId");var root=production.lockBatch(c.organizationId(),batch);gate("PRODUCTION_COMPLETED".equals(root.status()),"FINISHED_PRODUCTION_REQUIRED");var source=snapshot(c.organizationId(),batch);var row=new FinishedInboundRequestEntity();row.setRequestNo(text(body,"requestNo",80));row.setMainBatchId(batch);row.setMaterialLotId(source.path("materialLotId").asLong());row.setProductId(source.path("productId").asLong());row.setQuantity(new BigDecimal(source.path("quantity").asText()));row.setUnitId(source.path("unitId").asLong());row.setStatus("DRAFT");row.setReason(text(body,"reason",1000));row.setSourceSnapshotJson(source.toString());row.setSourceDigest(mutations.digest(source));inbound.insert(row,c.organizationId(),c.actorId());mutations.auditSnapshot(c,"FINISHED_INBOUND_CREATE","FinishedInboundRequest",row.getId(),null,view(row),row.getReason(),key);if(draft)events.publishEvent(new com.hospital.mes.wms.domain.FinishedInboundInspectionDraftRequested(c.organizationId(),c.actorId(),row.getId(),inspectionNo,row.getReason(),key));return row;
 },x->view((FinishedInboundRequestEntity)x),201);}
 @Transactional public JsonNode inboundAction(String target,String action,JsonNode body,String header,String key){
  if(!Set.of("submit","cancel","confirm").contains(action))throw new IllegalArgumentException("Unknown inbound action");if(action.equals("confirm"))fields(body,"versionNo","locationId","reason","signature");else fields(body,"versionNo","reason");var c=mutations.context("wms:finished-inbound:"+action);long expected=expected(body,header);String reason=text(body,"reason",1000);
  return mutations.execute(c,"FINISHED_INBOUND_"+action+":"+target,key,Map.of("target",target,"body",body),()->{
   var found=inbound.get(c.organizationId(),id(target));var batch=production.lockBatch(c.organizationId(),found.getMainBatchId());var row=inbound.lock(c.organizationId(),found.getId());match(row.getVersionNo(),expected);var before=view(row);var changed=new ArrayList<String>(List.of("status","reason"));row.setReason(reason);
   if(action.equals("submit")){gate("PRODUCTION_COMPLETED".equals(batch.status()),"FINISHED_PRODUCTION_REQUIRED");gate("DRAFT".equals(row.getStatus()),"FINISHED_REQUEST_STATE_CONFLICT");row.setStatus("SUBMITTED");row.setSubmittedBy(c.actorId());row.setSubmittedAt(now());changed.addAll(List.of("submittedBy","submittedAt"));}
   else if(action.equals("cancel")){gate(Set.of("DRAFT","SUBMITTED").contains(row.getStatus()),"FINISHED_REQUEST_STATE_CONFLICT");row.setStatus("CANCELLED");}
   else{
    FinishedGoodsRules.confirmReceipt(batch.status(),row.getStatus(),row.getCreatedBy(),c.actorId());gate(row.getSourceDigest().equals(mutations.digest(snapshot(c.organizationId(),row.getMainBatchId()))),"FINISHED_OUTPUT_SOURCE_CHANGED");long location=id(body,"locationId");var destination=stock.location().get(c.organizationId(),location);gate("ACTIVE".equals(destination.getStatus())&&"ACTIVE".equals(stock.warehouse().get(c.organizationId(),destination.getWarehouseId()).getStatus()),"FINISHED_DESTINATION_INVALID");var lot=stock.materialLot().lock(c.organizationId(),row.getMaterialLotId());gate("QUARANTINE".equals(lot.getQualityStatus())&&"BLOCKED".equals(lot.getInventoryStatus()),"FINISHED_RECEIPT_LOT_STATE");
    var ledger=stock.ledgerMapper().selectList(new QueryWrapper<LedgerEntity>().eq("org_id",c.organizationId()).eq("material_lot_id",lot.getId()).orderByAsc("id").last("FOR UPDATE"));
    if(ledger.isEmpty())row.setLedgerId(append(c,lot.getId(),location,row.getUnitId(),row.getQuantity(),"FINISHED_RECEIPT","FinishedInboundRequest",row.getId()+"",reason,key).getId());
    else{gate(ledger.stream().anyMatch(x->"PRODUCTION_OUTPUT".equals(x.getEventType())),"FINISHED_RECEIPT_SOURCE_CONFLICT");BigDecimal total=BigDecimal.ZERO;for(var l:ledger){gate(l.getLocationId()==location&&l.getUnitId().equals(row.getUnitId()),"FINISHED_LEGACY_RECEIPT_LOCATION");total=total.add(l.getDeltaQty());}gate(total.compareTo(row.getQuantity())==0,"FINISHED_LEGACY_RECEIPT_QUANTITY");row.setLedgerId(ledger.size()==1?ledger.getFirst().getId():null);}
    row.setStatus("CONFIRMED");row.setLocationId(location);row.setConfirmedBy(c.actorId());row.setConfirmedAt(now());var signature=signing.sign(c,"FINISHED_WAREHOUSE_RECEIPT",row.getId()+":"+expected,expected,SignatureMeaning.VERIFY,row,body.get("signature"),key,List.of("MainBatch:"+row.getMainBatchId(),"MaterialLot:"+lot.getId()));row.setSignatureId(signature.id());row.setSignatureEvidenceJson(signature.envelope());changed.addAll(List.of("locationId","ledgerId","confirmedBy","confirmedAt","signatureId","signatureEvidenceJson"));
   }
   inbound.update(row,expected,c.actorId(),changed);mutations.auditSnapshot(c,"FINISHED_INBOUND_"+action.toUpperCase(Locale.ROOT),"FinishedInboundRequest",row.getId(),before,view(row),reason,key);return row;
  },x->view((FinishedInboundRequestEntity)x),200);
 }
 @Transactional(readOnly=true) public JsonNode getInbound(String target){var c=mutations.context("wms:finished-inbound:view");return view(inbound.get(c.organizationId(),id(target)));}
 @Transactional(readOnly=true) public ScopedStore.PageData<JsonNode> listInbound(int page,int size,Map<String,String> filters){var c=mutations.context("wms:finished-inbound:view");validateFilters(filters,Set.of("page","size","keyword","status","mainBatchId","sort"));var rows=inbound.list(c.organizationId(),page,size,filters.get("keyword"),filters);return new ScopedStore.PageData<>(rows.items().stream().map(x->(JsonNode)view(x)).toList(),rows.total(),page,size);}
 public JsonNode inboundFact(long org,long target){return stable(view(inbound.get(org,target)));}
 public JsonNode confirmedInbound(long org,long batch){var row=inboundMapper.selectOne(new QueryWrapper<FinishedInboundRequestEntity>().eq("org_id",org).eq("main_batch_id",batch).last("LOCK IN SHARE MODE"));gate(row!=null&&"CONFIRMED".equals(row.getStatus())&&signing.valid(org,row.getSignatureId()),"FINISHED_RECEIPT_REQUIRED");return stable(view(row));}
 public List<JsonNode> inboundFacts(long org,long lot){return inboundMapper.selectList(new QueryWrapper<FinishedInboundRequestEntity>().eq("org_id",org).eq("material_lot_id",lot).orderByAsc("id")).stream().map(x->(JsonNode)stable(view(x))).toList();}
 private ObjectNode view(FinishedInboundRequestEntity row){var n=SignedRecordSupport.publicView(row,json);n.remove("sourceSnapshotJson");n.set("sourceSnapshot",read(row.getSourceSnapshotJson()));n.set("batch",production.batchFact(row.getOrgId(),row.getMainBatchId()));n.set("lot",lotView(row.getOrgId(),row.getMaterialLotId()));var actions=n.putArray("allowedActions");var c=contexts.current();if("DRAFT".equals(row.getStatus())&&c.hasPermission("wms:finished-inbound:submit"))actions.add("SUBMIT");if(Set.of("DRAFT","SUBMITTED").contains(row.getStatus())&&c.hasPermission("wms:finished-inbound:cancel"))actions.add("CANCEL");if("SUBMITTED".equals(row.getStatus())&&c.actorId()!=row.getCreatedBy()&&c.hasPermission("wms:finished-inbound:confirm"))actions.add("CONFIRM");return n;}
 private ObjectNode lotView(long org,long lot){var n=SignedRecordSupport.publicView(stock.materialLot().get(org,lot),json);n.set("materialSnapshot",read(n.path("materialSnapshotJson").asText()));n.remove("materialSnapshotJson");return n;}
 private LedgerEntity append(CurrentPlatformContext c,long lot,long location,long unit,BigDecimal delta,String type,String source,String ref,String reason,String key){var row=new LedgerEntity();row.setMaterialLotId(lot);row.setLocationId(location);row.setUnitId(unit);row.setDeltaQty(delta);row.setEventType(type);row.setSourceType(source);row.setSourceRef(ref);row.setOccurredAt(now());row.setIdempotencyKey(mutations.digest(Map.of("key",key,"event",type,"source",ref)));stock.ledger().insert(row,c.organizationId(),c.actorId());mutations.auditSnapshot(c,type,"InventoryLedger",row.getId(),null,SignedRecordSupport.publicView(row,json),reason,key);return row;}
 @Transactional public JsonNode createShipment(JsonNode body,String key){fields(body,"shipmentNo","mainBatchId","locationId","quantity","unitId","receivingParty","reason");var c=mutations.context("wms:finished-shipment:create");return mutations.execute(c,"FINISHED_SHIPMENT_CREATE",key,body,()->{long batch=id(body,"mainBatchId");var root=production.lockBatch(c.organizationId(),batch);gate("QA_RELEASED".equals(root.status()),"FINISHED_SHIPMENT_RELEASE_REQUIRED");var fact=production.batchFact(c.organizationId(),batch);gate(fact.hasNonNull("finishedLotId"),"FINISHED_OUTPUT_REQUIRED");var row=new FinishedShipmentEntity();row.setShipmentNo(text(body,"shipmentNo",80));row.setMainBatchId(batch);row.setMaterialLotId(fact.path("finishedLotId").asLong());row.setLocationId(id(body,"locationId"));stock.location().get(c.organizationId(),row.getLocationId());row.setQuantity(quantity(text(body,"quantity",30)));row.setUnitId(id(body,"unitId"));units.unit(c.organizationId(),row.getUnitId());row.setReceivingParty(text(body,"receivingParty",200));row.setStatus("DRAFT");row.setReason(text(body,"reason",1000));shipments.insert(row,c.organizationId(),c.actorId());mutations.auditSnapshot(c,"FINISHED_SHIPMENT_CREATE","FinishedShipment",row.getId(),null,view(row),row.getReason(),key);return row;},x->view((FinishedShipmentEntity)x),201);}
 private static BigDecimal quantity(String raw){if(!raw.matches("(?:0|[1-9][0-9]{0,11})(?:\\.[0-9]{1,6})?"))throw new IllegalArgumentException("Exact positive quantity required");var n=new BigDecimal(raw);gate(n.signum()>0,"FINISHED_QUANTITY_INVALID");return n;}
 @Transactional public JsonNode shipmentAction(String target,String action,JsonNode body,String header,String key){if(!Set.of("confirm","cancel").contains(action))throw new IllegalArgumentException("Unknown shipment action");if(action.equals("confirm"))fields(body,"versionNo","reason","signature");else fields(body,"versionNo","reason");var c=mutations.context("wms:finished-shipment:"+action);long expected=expected(body,header);String reason=text(body,"reason",1000);return mutations.execute(c,"FINISHED_SHIPMENT_"+action+":"+target,key,Map.of("target",target,"body",body),()->{
  var found=shipments.get(c.organizationId(),id(target));var batch=production.lockBatch(c.organizationId(),found.getMainBatchId());var row=shipments.lock(c.organizationId(),found.getId());match(row.getVersionNo(),expected);gate("DRAFT".equals(row.getStatus()),"FINISHED_SHIPMENT_STATE_CONFLICT");var before=view(row);row.setReason(reason);var changed=new ArrayList<String>(List.of("status","reason"));
  if(action.equals("cancel"))row.setStatus("CANCELLED");else{
   var lot=stock.materialLot().lock(c.organizationId(),row.getMaterialLotId());gate(production.batchFact(c.organizationId(),row.getMainBatchId()).path("finishedLotId").asLong()==lot.getId(),"FINISHED_SHIPMENT_LOT_MISMATCH");var decision=production.finishedDecision(c.organizationId(),row.getMainBatchId());gate(decision.path("decision").asText().equals("RELEASED")&&decision.path("finishedLotId").asLong()==lot.getId()&&decision.path("signatureVerified").asBoolean(),"FINISHED_SHIPMENT_RELEASE_REQUIRED");var location=stock.location().get(c.organizationId(),row.getLocationId());gate("ACTIVE".equals(location.getStatus())&&"ACTIVE".equals(stock.warehouse().get(c.organizationId(),location.getWarehouseId()).getStatus()),"FINISHED_SHIPMENT_LOCATION_INACTIVE");
   var ledger=stock.ledgerMapper().selectList(new QueryWrapper<LedgerEntity>().eq("org_id",c.organizationId()).eq("material_lot_id",lot.getId()).orderByAsc("id").last("FOR UPDATE"));long base=read(lot.getMaterialSnapshotJson()).path("baseUnitId").asLong();BigDecimal balance=BigDecimal.ZERO;for(var l:ledger)if(l.getLocationId().equals(row.getLocationId()))balance=balance.add(exact(c.organizationId(),l.getDeltaQty(),l.getUnitId(),base,lot.getMaterialId()));balance=balance.subtract(reservations.outstandingReservations(c.organizationId(),lot,base));BigDecimal debit=exact(c.organizationId(),row.getQuantity(),row.getUnitId(),base,lot.getMaterialId());FinishedGoodsRules.ship(batch.status(),lot.getQualityStatus(),lot.getInventoryStatus(),lot.getExpiryDate()==null||!LocalDate.now(ZoneOffset.UTC).isBefore(lot.getExpiryDate()),balance,debit);
   row.setStatus("CONFIRMED");row.setReleaseDecisionId(decision.path("id").asLong());row.setConfirmedBy(c.actorId());row.setConfirmedAt(now());var signature=signing.sign(c,"FINISHED_SHIPMENT",row.getId()+":"+expected,expected,SignatureMeaning.VERIFY,row,body.get("signature"),key,List.of("MainBatch:"+row.getMainBatchId(),"MaterialLot:"+lot.getId(),"ReleaseDecision:"+row.getReleaseDecisionId()));row.setSignatureId(signature.id());row.setSignatureEvidenceJson(signature.envelope());row.setLedgerId(append(c,lot.getId(),row.getLocationId(),base,debit.negate(),"FINISHED_SHIPMENT","FinishedShipment",row.getId()+"",reason,key).getId());changed.addAll(List.of("releaseDecisionId","confirmedBy","confirmedAt","signatureId","signatureEvidenceJson","ledgerId"));
  }
  shipments.update(row,expected,c.actorId(),changed);mutations.auditSnapshot(c,"FINISHED_SHIPMENT_"+action.toUpperCase(Locale.ROOT),"FinishedShipment",row.getId(),before,view(row),reason,key);return row;
 },x->view((FinishedShipmentEntity)x),200);}
 private ObjectNode view(FinishedShipmentEntity row){var n=SignedRecordSupport.publicView(row,json);n.set("batch",production.batchFact(row.getOrgId(),row.getMainBatchId()));n.set("lot",lotView(row.getOrgId(),row.getMaterialLotId()));var actions=n.putArray("allowedActions");var c=contexts.current();if("DRAFT".equals(row.getStatus())){if(c.hasPermission("wms:finished-shipment:confirm")&&"QA_RELEASED".equals(n.path("batch").path("status").asText())&&"RELEASED".equals(n.path("lot").path("qualityStatus").asText())&&"AVAILABLE".equals(n.path("lot").path("inventoryStatus").asText())&&n.path("lot").hasNonNull("expiryDate")&&LocalDate.now(ZoneOffset.UTC).isBefore(LocalDate.parse(n.path("lot").path("expiryDate").asText())))actions.add("CONFIRM");if(c.hasPermission("wms:finished-shipment:cancel"))actions.add("CANCEL");}return n;}
 @Transactional(readOnly=true) public JsonNode getShipment(String target){var c=mutations.context("wms:finished-shipment:view");return view(shipments.get(c.organizationId(),id(target)));}
 @Transactional(readOnly=true) public ScopedStore.PageData<JsonNode> listShipments(int page,int size,Map<String,String> f){var c=mutations.context("wms:finished-shipment:view");validateFilters(f,Set.of("page","size","keyword","status","mainBatchId","sort"));var data=shipments.list(c.organizationId(),page,size,f.get("keyword"),f);return new ScopedStore.PageData<>(data.items().stream().map(x->(JsonNode)view(x)).toList(),data.total(),page,size);}
 public List<JsonNode> shipmentFacts(long org,long lot){return shipmentMapper.selectList(new QueryWrapper<FinishedShipmentEntity>().eq("org_id",org).eq("material_lot_id",lot).orderByAsc("id")).stream().map(x->(JsonNode)stable(view(x))).toList();}
 private ObjectNode stable(ObjectNode n){n.remove(List.of("allowedActions","batch","lot"));return n;}
 public List<String> envelopes(String type,long org,String target){long id=id(target.split(":")[0]);String value=type.equals("FINISHED_SHIPMENT")?shipments.get(org,id).getSignatureEvidenceJson():inbound.get(org,id).getSignatureEvidenceJson();return value==null?List.of():List.of(value);}
}
