package com.hospital.mes.wms.application;
import static com.hospital.mes.wms.application.MaterialRequestService.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.wms.infrastructure.*;
import com.hospital.mes.wms.domain.MaterialRequestRules;
import java.math.BigDecimal;
import java.util.*;
import org.springframework.stereotype.Service;
@Service @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
@org.springframework.transaction.annotation.Transactional(readOnly=true)
public class WmsManagementQueryService {
 private final WmsStore db;private final IssueReturnMapper returns;private final MaterialRequestService requests;private final WmsProductionService production;private final MasterMutation mutations;private final MasterQueryService units;private final WmsViews views;private final ObjectMapper json;
 public WmsManagementQueryService(WmsStore db,IssueReturnMapper returns,MaterialRequestService requests,WmsProductionService production,MasterMutation mutations,MasterQueryService units,WmsViews views,ObjectMapper json){this.db=db;this.returns=returns;this.requests=requests;this.production=production;this.mutations=mutations;this.units=units;this.views=views;this.json=json;}
 public ScopedStore.PageData<JsonNode> inventory(int page,int size,Map<String,String> f){
  var c=mutations.context("wms:inventory:view");page(List.of(),page,size);validateFilters(f,Set.of("keyword","materialId","materialLotId","warehouseId","locationId","qualityStatus","inventoryStatus","page","size"));
  for(String k:List.of("materialId","materialLotId","warehouseId","locationId"))if(nonblank(f,k))id(f.get(k));
  var qualities=Set.of("QUARANTINE","PENDING_SAMPLING","SAMPLING","SAMPLED","TESTING","PENDING_QC_REVIEW","QC_PASSED","QC_FAILED","PENDING_QA_RELEASE","PENDING_DISPOSITION","RELEASED","REJECTED");if(nonblank(f,"qualityStatus")&&!qualities.contains(f.get("qualityStatus")))throw new IllegalArgumentException("Invalid quality status");if(nonblank(f,"inventoryStatus")&&!Set.of("BLOCKED","AVAILABLE","FROZEN").contains(f.get("inventoryStatus")))throw new IllegalArgumentException("Invalid inventory status");
  record Bucket(long lot,long location,Long container,long unit){}var buckets=new LinkedHashMap<Bucket,BigDecimal>();
  for(var e:db.ledgerMapper().selectList(new QueryWrapper<LedgerEntity>().eq("org_id",c.organizationId()).orderByAsc("material_lot_id","location_id","container_id","id")))buckets.merge(new Bucket(e.getMaterialLotId(),e.getLocationId(),e.getContainerId(),e.getUnitId()),e.getDeltaQty(),BigDecimal::add);
  var lots=new TreeMap<Long,ObjectNode>();var matches=new HashSet<Long>();
  for(var entry:buckets.entrySet()){
   var b=entry.getKey();var lot=db.materialLot().get(c.organizationId(),b.lot());var snapshot=views.view(lot).path("materialSnapshot");long base=id(snapshot,"baseUnitId");var amount=requests.converted(c.organizationId(),lot.getMaterialId(),b.unit(),base,entry.getValue());gate(amount.signum()>=0,"INVENTORY_INTEGRITY");
   if(nonblank(f,"materialId")&&lot.getMaterialId()!=id(f.get("materialId")))continue;if(nonblank(f,"materialLotId")&&lot.getId()!=id(f.get("materialLotId")))continue;if(nonblank(f,"qualityStatus")&&!lot.getQualityStatus().equals(f.get("qualityStatus")))continue;if(nonblank(f,"inventoryStatus")&&!lot.getInventoryStatus().equals(f.get("inventoryStatus")))continue;
   if(nonblank(f,"keyword")&&!contains(snapshot.path("materialName").asText()+snapshot.path("materialCode").asText()+lot.getLotNo(),f.get("keyword")))continue;
   var location=db.location().get(c.organizationId(),b.location());var warehouse=db.warehouse().get(c.organizationId(),location.getWarehouseId());
   var n=lots.computeIfAbsent(b.lot(),x->{var row=json.createObjectNode();row.put("materialLotId",lot.getId().toString());row.put("materialId",lot.getMaterialId().toString());row.put("lotNo",lot.getLotNo());row.put("materialCode",snapshot.path("materialCode").asText());row.put("materialName",snapshot.path("materialName").asText());row.put("unitId",Long.toString(base));row.put("unitCode",units.unit(c.organizationId(),base).unitCode());row.put("unitName",units.unitName(c.organizationId(),base));row.put("qualityStatus",lot.getQualityStatus());row.put("inventoryStatus",lot.getInventoryStatus());row.put("onHandQty","0");row.putArray("locationBalances");return row;});
   n.put("onHandQty",new BigDecimal(n.path("onHandQty").asText()).add(amount).toPlainString());if(amount.signum()!=0){var l=n.withArray("locationBalances").addObject();l.put("warehouseId",warehouse.getId().toString());l.put("warehouseName",warehouse.getWarehouseName());l.put("locationId",location.getId().toString());l.put("locationName",location.getLocationName()==null?location.getLocationCode():location.getLocationName());if(b.container()==null)l.putNull("containerId");else l.put("containerId",b.container().toString());l.put("unitId",Long.toString(base));l.put("unitName",units.unitName(c.organizationId(),base));l.put("onHandQty",amount.toPlainString());}
   if((amount.signum()!=0||(!nonblank(f,"warehouseId")&&!nonblank(f,"locationId")))&&(!nonblank(f,"warehouseId")||warehouse.getId()==id(f.get("warehouseId")))&&(!nonblank(f,"locationId")||location.getId()==id(f.get("locationId"))))matches.add(b.lot());
  }
  var rows=new ArrayList<JsonNode>();for(var entry:lots.entrySet()){var row=entry.getValue();var lot=db.materialLot().get(c.organizationId(),entry.getKey());var reserved=production.outstandingReservations(c.organizationId(),lot,id(row,"unitId"));row.put("reservedQty",reserved.toPlainString());row.put("availableQty",MaterialRequestRules.available(new BigDecimal(row.path("onHandQty").asText()),reserved).toPlainString());if(matches.contains(entry.getKey()))rows.add(row);}return page(rows,page,size);
 }
 public ScopedStore.PageData<JsonNode> returns(int page,int size,Map<String,String> f){
  var c=mutations.context("wms:issue:view");page(List.of(),page,size);validateFilters(f,Set.of("issueId","mainBatchId","materialId","materialLotId","returnedFrom","returnedTo","keyword","page","size"));for(String k:List.of("issueId","mainBatchId","materialId","materialLotId"))if(nonblank(f,k))id(f.get(k));var q=new QueryWrapper<IssueReturnEntity>().eq("org_id",c.organizationId()).orderByAsc("id");if(nonblank(f,"issueId"))q.eq("issue_id",id(f.get("issueId")));dates(q,f,"returned_at","returnedFrom","returnedTo");var result=new ArrayList<JsonNode>();
  for(var r:returns.selectList(q)){var issue=db.materialIssue().get(c.organizationId(),r.getIssueId());var item=db.materialIssueItem().get(c.organizationId(),r.getIssueItemId());gate(item.getIssueId().equals(issue.getId()),"RETURN_LINEAGE_INVALID");var lot=db.materialLot().get(c.organizationId(),item.getMaterialLotId());if(nonblank(f,"mainBatchId")&&issue.getMainBatchId()!=id(f.get("mainBatchId")))continue;if(nonblank(f,"materialId")&&lot.getMaterialId()!=id(f.get("materialId")))continue;if(nonblank(f,"materialLotId")&&lot.getId()!=id(f.get("materialLotId")))continue;var material=views.view(lot).path("materialSnapshot");var batch=requests.batchFact(c.organizationId(),issue.getMainBatchId());if(nonblank(f,"keyword")&&!contains(issue.getIssueNo()+lot.getLotNo()+material.path("materialName").asText()+batch.path("batchNo").asText(),f.get("keyword")))continue;
   var n=json.createObjectNode();n.put("id",r.getId().toString());n.put("issueId",issue.getId().toString());n.put("issueItemId",item.getId().toString());n.put("issueNo",issue.getIssueNo());n.put("mainBatchId",issue.getMainBatchId().toString());requests.context(n,batch);n.put("materialId",lot.getMaterialId().toString());n.put("materialCode",material.path("materialCode").asText());n.put("materialName",material.path("materialName").asText());n.put("materialLotId",lot.getId().toString());n.put("lotNo",lot.getLotNo());n.put("quantity",r.getQuantity().toPlainString());n.put("unitId",r.getUnitId().toString());n.put("unitName",units.unitName(c.organizationId(),r.getUnitId()));n.put("reason",r.getReason());n.put("returnedBy",r.getReturnedBy().toString());n.put("returnedAt",r.getReturnedAt().toInstant(java.time.ZoneOffset.UTC).toString());n.put("recordVersion",r.getRecordVersion());n.put("originalIssuedQty",item.getIssuedQty().toPlainString());n.put("issuedUnitId",item.getUnitId().toString());n.put("issuedUnitName",units.unitName(c.organizationId(),item.getUnitId()));BigDecimal total=BigDecimal.ZERO;for(var previous:returns.selectList(new QueryWrapper<IssueReturnEntity>().eq("org_id",c.organizationId()).eq("issue_item_id",item.getId())))total=total.add(requests.converted(c.organizationId(),lot.getMaterialId(),previous.getUnitId(),item.getUnitId(),previous.getQuantity()));n.put("returnedQty",total.toPlainString());n.put("remainingReturnQty",item.getIssuedQty().subtract(total).toPlainString());result.add(n);
  }return page(result,page,size);
 }
 public ScopedStore.PageData<JsonNode> issues(int page,int size,String keyword,Map<String,String> f){
  var c=mutations.context("wms:issue:view");page(List.of(),page,size);validateFilters(f,Set.of("page","size","keyword","mainBatchId","materialRequestId","productId","status","issuedFrom","issuedTo","sort"));if(nonblank(f,"productId"))id(f.get("productId"));var q=new QueryWrapper<MaterialIssueEntity>().eq("org_id",c.organizationId());for(String k:List.of("mainBatchId","materialRequestId"))if(nonblank(f,k))q.eq(k.equals("mainBatchId")?"main_batch_id":"material_request_id",id(f.get(k)));if(nonblank(f,"status")){if(!Set.of("DRAFT","CONFIRMED","CLOSED").contains(f.get("status")))throw new IllegalArgumentException("Invalid issue status");q.eq("status",f.get("status"));}dates(q,f,"issued_at","issuedFrom","issuedTo");if(keyword!=null&&!keyword.isBlank())q.like("issue_no",keyword.strip());String[] sort=f.getOrDefault("sort","id,desc").split(",");String col=sort[0].replaceAll("([a-z])([A-Z])","$1_$2").toLowerCase(Locale.ROOT);if(sort.length!=2||!Set.of("id","issue_no","main_batch_id","status","updated_at","version_no").contains(col)||!Set.of("asc","desc").contains(sort[1]))throw new IllegalArgumentException("Invalid sort");q.orderBy(true,sort[1].equals("asc"),col);if(!col.equals("id"))q.orderByAsc("id");var rows=new ArrayList<JsonNode>();for(var i:db.materialIssueMapper().selectList(q)){var n=requests.issueView(i);if(nonblank(f,"productId")&&!n.path("productId").asText().equals(Long.toString(id(f.get("productId")))))continue;rows.add(n);}return page(rows,page,size);
 }
}
