package com.hospital.mes.wms.application;
import org.springframework.transaction.annotation.Propagation;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.hospital.mes.masterdata.application.*;
import com.hospital.mes.masterdata.domain.MasterRules;
import com.hospital.mes.masterdata.infrastructure.ScopedEntity;
import com.hospital.mes.wms.infrastructure.*;
import com.hospital.mes.wms.domain.WmsRules;
import com.hospital.mes.common.exception.*;
import com.hospital.mes.audit.application.CurrentPlatformContext;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;

@org.springframework.stereotype.Service
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class WmsProductionService {
 private final IssueReturnMapper returns;private final WmsStore db;private final WmsViews views;private final MasterMutation mutations;private final MasterQueryService units;private final ObjectMapper json;private final ObjectProvider<WmsProductionContextPort> contexts;private final ObjectProvider<ProductionMaterialGate> eligibility;
 public WmsProductionService(IssueReturnMapper returns,WmsStore db,WmsViews views,MasterMutation mutations,MasterQueryService units,ObjectMapper json,ObjectProvider<WmsProductionContextPort> contexts,ObjectProvider<ProductionMaterialGate> eligibility){this.returns=returns;this.db=db;this.views=views;this.mutations=mutations;this.units=units;this.json=json;this.contexts=contexts;this.eligibility=eligibility;}
 @Transactional public JsonNode reserve(String batchId,JsonNode body,String header,String key){fields(body,"items","versionNo","reason");var c=mutations.context("wms:reservation:create");String why=text(body,"reason",1000);long expected=version(body,header);var created=new ArrayList<ReservationEntity>();return mutations.execute(c,"Reservation:CREATE:"+batchId,key,Map.of("batchId",batchId,"version",expected,"body",body),()->{
  var batch=batch(c.organizationId(),id(batchId));WmsRules.version(batch.versionNo(),expected);for(var line:items(body)){fields(line,"formulaItemId","materialLotId","reservedQty","unitId");long formulaId=id(line,"formulaItemId");var formula=formula(batch.snapshot(),formulaId);long material=id(formula,"materialId");long requestedUnit=id(line,"unitId");BigDecimal remaining=WmsRules.quantity(text(line,"reservedQty",50),false);var q=new QueryWrapper<MaterialLotEntity>().eq("org_id",c.organizationId()).eq("material_id",material).orderByAsc("id");if(line.hasNonNull("materialLotId"))q.eq("id",id(line,"materialLotId"));var lots=db.materialLotMapper().selectList(q.last("FOR UPDATE"));lots.sort(Comparator.comparing(MaterialLotEntity::getExpiryDate,Comparator.nullsLast(Comparator.naturalOrder())).thenComparing(MaterialLotEntity::getCreatedAt).thenComparing(MaterialLotEntity::getId));
   for(var lot:lots){try{eligible(c.organizationId(),batch.mainBatchId(),lot.getId());}catch(ComplianceException e){if(line.hasNonNull("materialLotId"))throw e;continue;}long base=baseUnit(lot);BigDecimal free=onHand(c.organizationId(),lot.getId(),base).subtract(outstandingReservations(c.organizationId(),lot,base));BigDecimal amount=convert(c.organizationId(),material,requestedUnit,base,remaining).min(free);if(amount.signum()<=0)continue;var row=new ReservationEntity();row.setMainBatchId(batch.mainBatchId());row.setFormulaItemId(formulaId);row.setMaterialLotId(lot.getId());row.setReservedQty(amount);row.setUnitId(base);row.setStatus("ACTIVE");db.reservation().insert(row,c.organizationId(),c.actorId());created.add(row);mutations.auditSnapshot(c,"Reservation:CREATE","Reservation",row.getId(),null,views.view(row),why,key);remaining=remaining.subtract(convert(c.organizationId(),material,base,requestedUnit,amount));if(remaining.signum()==0)break;}
   gate(remaining.signum()==0,"INSUFFICIENT_ELIGIBLE_INVENTORY","No eligible unreserved quantity satisfies request");
  }return created.getFirst();},row->{var a=json.createArrayNode();created.forEach(x->a.add(views.view(x)));return a;},200);}
 @Transactional public JsonNode createIssue(JsonNode body,String key){fields(body,"mainBatchId","issueNo","items","reason");var c=mutations.context("wms:issue:create");String why=text(body,"reason",1000);return mutations.execute(c,"MaterialIssue:CREATE",key,body,()->{var batch=batch(c.organizationId(),id(body,"mainBatchId"));var issue=new MaterialIssueEntity();issue.setMainBatchId(batch.mainBatchId());issue.setIssueNo(text(body,"issueNo",80));issue.setStatus("DRAFT");db.materialIssue().insert(issue,c.organizationId(),c.actorId());writeItems(c,issue,batch,items(body),false);mutations.auditSnapshot(c,"MaterialIssue:CREATE","MaterialIssue",issue.getId(),null,view(issue),why,key);return issue;},this::view,200);}
 @Transactional public JsonNode updateIssue(String id,JsonNode body,String header,String key){fields(body,"mainBatchId","issueNo","items","versionNo","reason");var c=mutations.context("wms:issue:update");long expected=version(body,header);String why=text(body,"reason",1000);return mutations.execute(c,"MaterialIssue:EDIT:"+id,key,Map.of("id",id,"version",expected,"body",body),()->{var known=db.materialIssue().get(c.organizationId(),id(id));gate(known.getMainBatchId()==id(body,"mainBatchId"),"ISSUE_BATCH_IMMUTABLE","Issue batch identity cannot change");var batch=batch(c.organizationId(),known.getMainBatchId());var issue=db.materialIssue().lock(c.organizationId(),known.getId());WmsRules.version(issue.getVersionNo(),expected);state(issue,"DRAFT");var before=view(issue);issue.setIssueNo(text(body,"issueNo",80));writeItems(c,issue,batch,items(body),true);db.materialIssue().update(issue,expected,c.actorId(),List.of("issueNo"));mutations.auditSnapshot(c,"MaterialIssue:EDIT","MaterialIssue",issue.getId(),before,view(issue),why,key);return issue;},this::view,200);}
 private void writeItems(CurrentPlatformContext c,MaterialIssueEntity issue,WmsProductionContextPort.BatchContext batch,List<JsonNode> lines,boolean edit){var old=issueItems(c.organizationId(),issue.getId());if(edit)gate(lines.size()>=old.size(),"ISSUE_ITEM_REMOVAL_FORBIDDEN","Retained issue rows cannot be physically removed");for(int i=0;i<lines.size();i++){var line=lines.get(i);fields(line,"materialLotId","formulaItemId","issuedQty","unitId");long formulaId=id(line,"formulaItemId");var formula=formula(batch.snapshot(),formulaId);var lot=db.materialLot().get(c.organizationId(),id(line,"materialLotId"));gate(lot.getMaterialId()==id(formula,"materialId"),"MATERIAL_NOT_IN_BOM","Issue material does not match frozen BOM");eligible(c.organizationId(),batch.mainBatchId(),lot.getId());var row=i<old.size()?old.get(i):new MaterialIssueItemEntity();row.setIssueId(issue.getId());row.setMaterialLotId(lot.getId());row.setFormulaItemId(formulaId);row.setIssuedQty(WmsRules.quantity(text(line,"issuedQty",50),false));row.setUnitId(id(line,"unitId"));convert(c.organizationId(),lot.getMaterialId(),row.getUnitId(),baseUnit(lot),row.getIssuedQty());if(row.getId()==null)db.materialIssueItem().insert(row,c.organizationId(),c.actorId());else db.materialIssueItem().update(row,row.getVersionNo(),c.actorId(),List.of("materialLotId","formulaItemId","issuedQty","unitId"));}}
 @Transactional public JsonNode confirmIssue(String id,JsonNode body,String header,String key){fields(body,"versionNo","reason","reauthToken");var c=mutations.context("wms:issue:confirm");long expected=version(body,header);String why=text(body,"reason",1000);return mutations.execute(c,"MaterialIssue:CONFIRM:"+id,key,Map.of("id",id,"version",expected,"reason",why),()->{var known=db.materialIssue().get(c.organizationId(),id(id));var batch=batch(c.organizationId(),known.getMainBatchId());var issue=db.materialIssue().lock(c.organizationId(),known.getId());WmsRules.version(issue.getVersionNo(),expected);state(issue,"DRAFT");var before=view(issue);var lines=issueItems(c.organizationId(),issue.getId());for(long lotId:lines.stream().map(MaterialIssueItemEntity::getMaterialLotId).distinct().sorted().toList())db.materialLot().lock(c.organizationId(),lotId);
  var pairs=new LinkedHashMap<Allocation,BigDecimal>();var totals=new LinkedHashMap<Long,BigDecimal>();for(var line:lines){var lot=db.materialLot().get(c.organizationId(),line.getMaterialLotId());eligible(c.organizationId(),batch.mainBatchId(),lot.getId());gate(lot.getMaterialId()==id(formula(batch.snapshot(),line.getFormulaItemId()),"materialId"),"MATERIAL_NOT_IN_BOM","Issue material mismatch");var amount=convert(c.organizationId(),lot.getMaterialId(),line.getUnitId(),baseUnit(lot),line.getIssuedQty());totals.merge(lot.getId(),amount,BigDecimal::add);pairs.merge(new Allocation(lot.getId(),line.getFormulaItemId()),amount,BigDecimal::add);}
  for(var entry:totals.entrySet()){var lot=db.materialLot().get(c.organizationId(),entry.getKey());long unit=baseUnit(lot);var reserved=reserved(c.organizationId(),batch.mainBatchId(),lot.getId(),unit);var dispatched=issued(c.organizationId(),batch.mainBatchId(),lot.getId(),unit);gate(dispatched.add(entry.getValue()).compareTo(reserved)<=0,"ISSUE_EXCEEDS_RESERVATION","Confirmed issues exceed reservation");gate(entry.getValue().compareTo(onHand(c.organizationId(),lot.getId(),unit))<=0,"INSUFFICIENT_INVENTORY","Insufficient physical inventory");}
  for(var entry:pairs.entrySet()){var pair=entry.getKey();var lot=db.materialLot().get(c.organizationId(),pair.lotId());long unit=baseUnit(lot);gate(issued(c.organizationId(),batch.mainBatchId(),lot.getId(),unit,pair.formulaItemId()).add(entry.getValue()).compareTo(reserved(c.organizationId(),batch.mainBatchId(),lot.getId(),unit,pair.formulaItemId()))<=0,"ISSUE_EXCEEDS_RESERVATION","Exact formula line and lot reservation required");}
  issue.setStatus("CONFIRMED");issue.setIssuedAt(now());db.materialIssue().update(issue,expected,c.actorId(),List.of("status","issuedAt"));mutations.auditSnapshot(c,"MaterialIssue:CONFIRM","MaterialIssue",issue.getId(),before,view(issue),why,key);return issue;},this::view,200);}
 @Transactional public JsonNode returnIssue(String id,JsonNode body,String header,String key){fields(body,"versionNo","reason","items");var c=mutations.context("wms:issue:return");long expected=version(body,header);String why=text(body,"reason",1000);return mutations.execute(c,"MaterialIssue:RETURN:"+id,key,Map.of("id",id,"version",expected,"body",body),()->{var initial=db.materialIssue().get(c.organizationId(),id(id));var batch=batch(c.organizationId(),initial.getMainBatchId());var issue=db.materialIssue().lock(c.organizationId(),initial.getId());WmsRules.version(issue.getVersionNo(),expected);state(issue,"CONFIRMED");var before=view(issue);var source=issueItems(c.organizationId(),issue.getId());var submitted=new ArrayList<IssueReturnEntity>();var seen=new HashSet<Long>();var byLot=new TreeMap<Long,BigDecimal>();
  for(var line:items(body)){fields(line,"issueItemId","quantity","unitId");long itemId=id(line,"issueItemId");gate(seen.add(itemId),"DUPLICATE_RETURN_ITEM","An issue item may appear only once per return command");var item=source.stream().filter(x->x.getId()==itemId).findFirst().orElseThrow(()->new java.util.NoSuchElementException("Issue item not in parent issue"));var lot=db.materialLot().get(c.organizationId(),item.getMaterialLotId());long unit=id(line,"unitId");BigDecimal qty=WmsRules.quantity(text(line,"quantity",50),false);gate(convert(c.organizationId(),lot.getMaterialId(),unit,item.getUnitId(),qty).compareTo(remaining(c.organizationId(),item))<=0,"RETURN_QTY_INVALID","Cumulative return exceeds issued item quantity");byLot.merge(lot.getId(),convert(c.organizationId(),lot.getMaterialId(),unit,baseUnit(lot),qty),BigDecimal::add);var fact=new IssueReturnEntity();fact.setOrgId(c.organizationId());fact.setIssueId(issue.getId());fact.setIssueItemId(itemId);fact.setQuantity(qty);fact.setUnitId(unit);fact.setReason(why);fact.setReturnedBy(c.actorId());fact.setReturnedAt(now());fact.setRecordVersion(1L);submitted.add(fact);}
  for(var entry:byLot.entrySet()){var lot=db.materialLot().lock(c.organizationId(),entry.getKey());long base=baseUnit(lot);gate(issued(c.organizationId(),batch.mainBatchId(),lot.getId(),base).subtract(entry.getValue()).compareTo(port().chargedQuantity(c.organizationId(),batch.mainBatchId(),lot.getId(),base))>=0,"RETURN_QTY_INVALID","Return would withdraw already consumed entitlement");}
  submitted.forEach(returns::insert);db.materialIssue().update(issue,expected,c.actorId(),List.of());mutations.auditSnapshot(c,"MaterialIssue:RETURN","MaterialIssue",issue.getId(),before,view(issue),why,key);return issue;},this::view,200);}

 @Transactional(propagation=Propagation.MANDATORY) public void lockLot(long organizationId,long lotId){db.materialLot().lock(organizationId,lotId);}
 @Transactional(propagation=Propagation.MANDATORY)
 public void requireOperationMaterials(long org,long batchId){var context=batch(org,batchId);var issues=db.materialIssueMapper().selectList(new QueryWrapper<MaterialIssueEntity>().eq("org_id",org).eq("main_batch_id",batchId).in("status","CONFIRMED","CLOSED"));gate(!issues.isEmpty(),"PRECONDITION_FAILED","Confirmed material issue evidence is required");var lines=db.materialIssueItemMapper().selectList(new QueryWrapper<MaterialIssueItemEntity>().eq("org_id",org).in("issue_id",issues.stream().map(MaterialIssueEntity::getId).toList()).orderByAsc("material_lot_id","id"));for(var formula:context.snapshot().path("process").path("formula").path("items")){long item=id(formula,"formulaItemId");gate(lines.stream().anyMatch(x->Objects.equals(x.getFormulaItemId(),item)&&remaining(org,x).signum()>0),"PRECONDITION_FAILED","Confirmed issue for every frozen BOM line is required");}for(long lotId:lines.stream().filter(x->remaining(org,x).signum()>0).map(MaterialIssueItemEntity::getMaterialLotId).distinct().sorted().toList()){db.materialLot().lock(org,lotId);eligible(org,batchId,lotId);}}
 /** Called only within the actual charge transaction. Charge fact is already inserted, so chargedQuantity includes this charge. */
 @Transactional(propagation=Propagation.MANDATORY)
 public void consume(CurrentPlatformContext c,long batchId,long lotId,long chargeId,BigDecimal quantity,long unitId,String key){batch(c.organizationId(),batchId);var lot=db.materialLot().lock(c.organizationId(),lotId);eligible(c.organizationId(),batchId,lotId);long base=baseUnit(lot);var amount=convert(c.organizationId(),lot.getMaterialId(),unitId,base,quantity);gate(port().chargedQuantity(c.organizationId(),batchId,lotId,base).compareTo(issued(c.organizationId(),batchId,lotId,base))<=0,"CHARGE_QTY_INVALID","Charge exceeds confirmed issue entitlement");var buckets=stock(c.organizationId(),lotId,base);BigDecimal remaining=amount;for(var entry:buckets.entrySet()){if(entry.getValue().signum()<=0)continue;var take=entry.getValue().min(remaining);append(c,lot,entry.getKey(),"CONSUME",take.negate(),base,"MaterialCharge",Long.toString(chargeId),key+":"+entry.getKey());remaining=remaining.subtract(take);if(remaining.signum()==0)break;}gate(remaining.signum()==0,"INSUFFICIENT_INVENTORY","Charge would make a stock bucket negative");db.materialLot().update(lot,lot.getVersionNo(),c.actorId(),List.of());}
 @Transactional(propagation=Propagation.MANDATORY)
 public void reverseConsumption(CurrentPlatformContext c,long batchId,long lotId,long chargeId,String key){batch(c.organizationId(),batchId);var lot=db.materialLot().lock(c.organizationId(),lotId);var original=db.ledgerMapper().selectList(new QueryWrapper<LedgerEntity>().eq("org_id",c.organizationId()).eq("source_type","MaterialCharge").eq("source_ref",Long.toString(chargeId)).eq("event_type","CONSUME").orderByAsc("id"));gate(!original.isEmpty(),"CHARGE_QTY_INVALID","Original consumption required");gate(db.ledgerMapper().selectCount(new QueryWrapper<LedgerEntity>().eq("org_id",c.organizationId()).eq("source_type","MaterialChargeReversal").eq("source_ref",Long.toString(chargeId)))==0,"CHARGE_ALREADY_REVERSED","Charge already reversed");for(var e:original){gate(e.getMaterialLotId()==lotId,"CHARGE_QTY_INVALID","Original lot mismatch");append(c,lot,new Bucket(e.getLocationId(),e.getContainerId()),"REVERSE_CONSUME",e.getDeltaQty().negate(),e.getUnitId(),"MaterialChargeReversal",Long.toString(chargeId),key+":"+e.getId());}db.materialLot().update(lot,lot.getVersionNo(),c.actorId(),List.of());}
 private record Bucket(long locationId,Long containerId){}
 private LinkedHashMap<Bucket,BigDecimal> stock(long org,long lot,long unit){var rows=db.ledgerMapper().selectList(new QueryWrapper<LedgerEntity>().eq("org_id",org).eq("material_lot_id",lot).eq("unit_id",unit).orderByAsc("location_id","container_id","id"));var result=new LinkedHashMap<Bucket,BigDecimal>();for(var e:rows)result.merge(new Bucket(e.getLocationId(),e.getContainerId()),e.getDeltaQty(),BigDecimal::add);return result;}
 private BigDecimal onHand(long org,long lot,long unit){return stock(org,lot,unit).values().stream().reduce(BigDecimal.ZERO,BigDecimal::add);}
 private BigDecimal outstandingReservations(long org,MaterialLotEntity lot,long unit){var rows=db.reservationMapper().selectList(new QueryWrapper<ReservationEntity>().eq("org_id",org).eq("material_lot_id",lot.getId()).eq("status","ACTIVE"));var byBatch=new HashMap<Long,BigDecimal>();for(var row:rows)byBatch.merge(row.getMainBatchId(),convert(org,lot.getMaterialId(),row.getUnitId(),unit,row.getReservedQty()),BigDecimal::add);BigDecimal total=BigDecimal.ZERO;for(var entry:byBatch.entrySet())total=total.add(entry.getValue().subtract(port().chargedQuantity(org,entry.getKey(),lot.getId(),unit)).max(BigDecimal.ZERO));return total;}
 private record Allocation(long lotId,long formulaItemId){}
 private BigDecimal reserved(long org,long batch,long lot,long unit){return reserved(org,batch,lot,unit,null);}
 private BigDecimal reserved(long org,long batch,long lot,long unit,Long formula){var material=db.materialLot().get(org,lot);return db.reservationMapper().selectList(new QueryWrapper<ReservationEntity>().eq("org_id",org).eq("main_batch_id",batch).eq("material_lot_id",lot).in("status","ACTIVE","CONSUMED").eq(formula!=null,"formula_item_id",formula)).stream().map(r->convert(org,material.getMaterialId(),r.getUnitId(),unit,r.getReservedQty())).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private BigDecimal issued(long org,long batch,long lot,long unit){return issued(org,batch,lot,unit,null);}
 private BigDecimal issued(long org,long batch,long lot,long unit,Long formula){var material=db.materialLot().get(org,lot);var issues=db.materialIssueMapper().selectList(new QueryWrapper<MaterialIssueEntity>().eq("org_id",org).eq("main_batch_id",batch).in("status","CONFIRMED","CLOSED"));if(issues.isEmpty())return BigDecimal.ZERO;return db.materialIssueItemMapper().selectList(new QueryWrapper<MaterialIssueItemEntity>().eq("org_id",org).in("issue_id",issues.stream().map(MaterialIssueEntity::getId).toList()).eq("material_lot_id",lot).eq(formula!=null,"formula_item_id",formula)).stream().map(r->convert(org,material.getMaterialId(),r.getUnitId(),unit,remaining(org,r))).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private void append(CurrentPlatformContext c,MaterialLotEntity lot,Bucket bucket,String event,BigDecimal delta,long unit,String source,String ref,String key){var e=new LedgerEntity();e.setMaterialLotId(lot.getId());e.setLocationId(bucket.locationId());e.setContainerId(bucket.containerId());e.setEventType(event);e.setDeltaQty(delta);e.setUnitId(unit);e.setSourceType(source);e.setSourceRef(ref);e.setIdempotencyKey(mutations.digest(Map.of("org",c.organizationId(),"event",event,"key",key)));e.setOccurredAt(now());db.ledger().insert(e,c.organizationId(),c.actorId());mutations.auditSnapshot(c,"InventoryLedger:"+event,"InventoryLedger",e.getId(),null,views.view(e),source+":"+ref,com.hospital.mes.audit.idempotency.PlatformIdempotencyService.digest(key));}
 public ArrayNode returnFacts(long org,long issue){db.materialIssue().get(org,issue);var result=json.createArrayNode();for(var r:returns.selectList(new QueryWrapper<IssueReturnEntity>().eq("org_id",org).eq("issue_id",issue).orderByAsc("id"))){var n=result.addObject();n.put("id",r.getId().toString());n.put("issueId",r.getIssueId().toString());n.put("issueItemId",r.getIssueItemId().toString());n.put("quantity",r.getQuantity().toPlainString());n.put("unitId",r.getUnitId().toString());n.put("reason",r.getReason());n.put("returnedBy",r.getReturnedBy().toString());n.put("returnedAt",r.getReturnedAt().toInstant(ZoneOffset.UTC).toString());n.put("recordVersion",r.getRecordVersion());}return result;}
 private BigDecimal remaining(long org,MaterialIssueItemEntity item){var lot=db.materialLot().get(org,item.getMaterialLotId());BigDecimal total=BigDecimal.ZERO;for(var r:returns.selectList(new QueryWrapper<IssueReturnEntity>().eq("org_id",org).eq("issue_item_id",item.getId())))total=total.add(convert(org,lot.getMaterialId(),r.getUnitId(),item.getUnitId(),r.getQuantity()));return item.getIssuedQty().subtract(total);}
 private List<MaterialIssueItemEntity> issueItems(long org,long issue){return db.materialIssueItemMapper().selectList(new QueryWrapper<MaterialIssueItemEntity>().eq("org_id",org).eq("issue_id",issue).orderByAsc("id"));}
 private JsonNode view(ScopedEntity e){var result=views.view(e);if(e instanceof MaterialIssueEntity issue){var a=result.putArray("items");issueItems(issue.getOrgId(),issue.getId()).forEach(x->a.add(views.view(x)));result.set("returns",returnFacts(issue.getOrgId(),issue.getId()));}return result;}
 private WmsProductionContextPort port(){var value=contexts.getIfAvailable();if(value==null)throw new ComplianceException("DEPENDENCY_NOT_READY","Real production contract unavailable");return value;}
 private WmsProductionContextPort.BatchContext batch(long org,long id){var b=port().lockBatch(org,id);gate(Set.of("RELEASED","IN_PROGRESS").contains(b.status())&&b.snapshot().isObject(),"INVALID_BATCH_STATE","Released active batch required");return b;}
 private void eligible(long org,long batch,long lot){var p=eligibility.getIfAvailable();if(p==null)throw new ComplianceException("DEPENDENCY_NOT_READY","Material eligibility unavailable");p.requireEligible(org,batch,lot,Instant.now());}
 private JsonNode formula(JsonNode snapshot,long id){for(var row:snapshot.path("process").path("formula").path("items"))if(row.path("formulaItemId").asText().equals(Long.toString(id)))return row;throw new ComplianceException("MATERIAL_NOT_IN_BOM","Formula item not in frozen batch");}
 private long baseUnit(MaterialLotEntity lot){try{return id(json.readTree(lot.getMaterialSnapshotJson()),"baseUnitId");}catch(java.io.IOException ex){throw new IllegalStateException("Lot snapshot invalid",ex);}}
 private BigDecimal convert(long org,long material,long from,long to,BigDecimal qty){var c=units.convert(org,from,to,material,qty);return WmsRules.exact(qty,c.factor(),c.convertedValue());}
 private static void state(MaterialIssueEntity row,String expected){if(!expected.equals(row.getStatus()))throw new StateTransitionException("INVALID_ISSUE_STATE","Issue must be "+expected);}
 private static void gate(boolean value,String code,String message){if(!value)throw new ComplianceException(code,message);}
 private static long id(String value){return MasterMutation.id(value);}private static long id(JsonNode node,String field){return id(text(node,field,30));}
 private static String text(JsonNode body,String field,int max){if(!body.path(field).isTextual())throw new IllegalArgumentException(field+": string required");return MasterRules.text(body.get(field).asText(),max);}
 private static void fields(JsonNode body,String...allowed){if(body==null||!body.isObject())throw new IllegalArgumentException("Object request required");var names=Set.of(allowed);body.fieldNames().forEachRemaining(k->{if(!names.contains(k))throw new IllegalArgumentException("Unknown field: "+k);});}
 private static long version(JsonNode body,String header){if(body.hasNonNull("versionNo")&&(!body.get("versionNo").isIntegralNumber()||!body.get("versionNo").canConvertToLong()||body.get("versionNo").longValue()<0))throw new IllegalArgumentException("Nonnegative integral versionNo required");return MasterMutation.version(header,body.hasNonNull("versionNo")?body.get("versionNo").longValue():null);}
 private static List<JsonNode> items(JsonNode body){if(!body.path("items").isArray()||body.get("items").isEmpty()||body.get("items").size()>500)throw new IllegalArgumentException("1..500 items required");var result=new ArrayList<JsonNode>();body.get("items").forEach(result::add);return result;}
 private static LocalDateTime now(){return LocalDateTime.now(ZoneOffset.UTC).truncatedTo(java.time.temporal.ChronoUnit.MILLIS);}
}
