package com.hospital.mes.qc.application;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.hospital.mes.audit.application.*;
import com.hospital.mes.audit.signature.*;
import com.hospital.mes.masterdata.application.MasterQueryService;
import com.hospital.mes.qc.infrastructure.*;
import com.hospital.mes.qc.domain.*;
import java.time.*;
import java.math.BigDecimal;
import java.util.*;
import org.junit.jupiter.api.*;
class QcSpecificationEvidenceTest {
 QcStore store;AuditQueryService audit;SignatureRepository signatures;QcDefinitions definitions;SignatureCanonicalizer canonical;SpecificationVersionEntity version;QcSigningIntent intent;
 @BeforeEach void setup(){store=mock(QcStore.class);audit=mock(AuditQueryService.class);signatures=mock(SignatureRepository.class);intent=new QcSigningIntent();var mapper=new ObjectMapper();canonical=new Rfc8785SignatureCanonicalizer(mapper);definitions=new QcDefinitions(store,mapper,mock(MasterQueryService.class),audit,signatures,canonical,intent);var root=new SpecificationEntity();root.setId(10L);root.setOrgId(1L);root.setMaterialId(5L);root.setSpecificationCode("QC-A");root.setSpecificationName("Standard");when(store.root(1,10)).thenReturn(root);version=new SpecificationVersionEntity();version.setId(20L);version.setOrgId(1L);version.setSpecificationId(10L);version.setVersionNoBusiness(1);version.setVersionNo(1L);version.setCreatedBy(7L);version.setStatus("APPROVED");version.setApprovedBy(8L);version.setApprovedAt(LocalDateTime.of(2026,10,3,0,0));version.setApprovalSignatureId(30L);version.setApprovalReason("Controlled approval");when(store.version(1,20,false)).thenReturn(version);when(store.version(1,20,true)).thenReturn(version);var item=new SpecificationItemEntity();item.setId(21L);item.setItemCode("ASSAY");item.setItemName("Assay");item.setRequired(true);item.setResultType("NUMERIC");item.setLowerLimit(new BigDecimal("1.000000"));item.setUpperLimit(new BigDecimal("3.000000"));item.setUnitId(3L);item.setMethodCode("M1");item.setMethodVersion("1");when(store.items(1,20,true)).thenReturn(List.of(item));version.setContentHash(definitions.contentHash(version));}
 @Test void retirementKeepsApprovalDigestAndHistoricalSnapshotStable(){var original=definitions.signable(1,"20","APPROVE");var snapshot=definitions.snapshot(version);String digest=canonical.digest(original);when(signatures.find(1,30)).thenReturn(signature(digest));definitions.requireValid(version);version.setStatus("RETIRED");version.setVersionNo(2L);version.setRetirementReason("Replaced");version.setRetirementSignatureId(31L);assertThat(canonical.digest(definitions.signable(1,"20","APPROVE"))).isEqualTo(digest);definitions.requireValid(version);assertThat(new QcSpecificationQueryService(store,definitions).getHistorical(1,20)).isEqualTo(snapshot);assertThat(definitions.signable(1,"20","RETIRE").canonicalRecord().path("approvalSignatureId").asText()).isEqualTo("30");assertThatThrownBy(()->new QcSpecificationQueryService(store,definitions).requireSelectable(1,5,20)).hasMessageContaining("selectable");}
 @Test void contentAndSignatureBindingFailClosed(){String digest=canonical.digest(definitions.signable(1,"20","APPROVE"));when(signatures.find(1,30)).thenReturn(signature(digest));version.setApprovalReason("Changed reason");assertThatThrownBy(()->definitions.requireValid(version)).hasMessageContaining("invalid");version.setApprovalReason("Controlled approval");version.setContentHash("0".repeat(64));assertThatThrownBy(()->definitions.requireValid(version)).hasMessageContaining("invalid");}
 @Test void creatorAndEarlierOverwrittenAuthorCannotApprove(){assertThatThrownBy(()->definitions.independent(version,7)).hasMessageContaining("author");when(audit.query(eq(1L),any())).thenReturn(new AuditEventPage(List.of(),0,1,0),new AuditEventPage(List.of(),0,1,1));assertThatThrownBy(()->definitions.independent(version,9)).hasMessageContaining("author");}
 @Test void genericSignCannotBypassCommandAndSnapshotsAreImmutable(){var c=new CurrentPlatformContext(1,8,Set.of("QA"),Set.of("qms:specification:approve","ebr:sign"),"session","request");var object=definitions.signable(1,"20","APPROVE");assertThatThrownBy(()->definitions.validateSigning(new SignatureValidationContext(c,SignatureMeaning.APPROVE),object,"APPROVE")).hasMessageContaining("business command");assertThatThrownBy(()->definitions.snapshot(version).items().clear()).isInstanceOf(UnsupportedOperationException.class);assertThatThrownBy(()->new QcSpecificationQueryService(store,definitions).requireSelectable(1,999,20)).hasMessageContaining("another material");}
 @Test void authorRowsRejectEvenWhenPaginationTotalIsUnavailable(){var event=new com.hospital.mes.audit.domain.AuditEvent(1,1,9,"QC","QC_SPEC_VERSION_EDITED","QcSpecificationVersion","20",null,null,"Changed",null,Instant.now(),"transaction","request",com.hospital.mes.audit.domain.AuditSource.API);when(audit.query(eq(1L),any())).thenReturn(new AuditEventPage(List.of(),0,1,0),new AuditEventPage(List.of(event),0,1,0));assertThatThrownBy(()->definitions.independent(version,9)).hasMessageContaining("author");}
 private SignatureRecord signature(String digest){return new SignatureRecord(30,1,8,SignatureMeaning.APPROVE,"QcSpecificationVersion","20",digest,Instant.parse("2026-10-03T00:00:00Z"),SignatureStatus.VALID,null,null,"{}",null,0);}
}
