package com.hospital.mes.production;
import com.hospital.mes.release.application.EbrArchiveService;
import com.hospital.mes.release.domain.ArchiveCommand;
import com.hospital.mes.audit.attachment.application.AttachmentService;
import com.hospital.mes.audit.signature.SignatureRepository;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.text.PDFTextStripper;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.mockito.ArgumentMatchers.*;
class EbrArchiveIT extends FinishedReleaseIT {
 @Autowired EbrArchiveService archive;@Autowired AttachmentService attachments;@Autowired SignatureRepository signatureRepository;
 private ArchiveCommand command(com.fasterxml.jackson.databind.JsonNode batch,String kind){return new ArchiveCommand(batch.path("versionNo").asLong(),kind,"Actual source evidence archive");}
 @Test void reviewCopyReuseAndFinalChangedSourcePreserveImmutableHashHistory()throws Exception {
  var batch=completedQaBatch();var before=archive.get(id(batch));String digest=before.path("recordDigest").asText();var copy=archive.generate(id(batch),command(batch,"REVIEW_COPY"),token(batch),key());assertThat(archive.get(id(batch)).path("recordDigest").asText()).isEqualTo(digest);var repeat=archive.generate(id(batch),command(batch,"REVIEW_COPY"),token(batch),key());assertThat(repeat).isEqualTo(copy);assertThat(copy.path("generationVersion").asInt()).isEqualTo(1);
  byte[] bytes=attachments.readContent(1,copy.path("fileId").asLong()).content();assertThat(copy.path("fileHash").asText()).isEqualTo(java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(bytes)));try(var pdf=Loader.loadPDF(bytes)){assertThat(new PDFTextStripper().getText(pdf)).contains("医院制剂","审核副本","MaterialCharge","signatureRecords");}
  as(qa);var decision=finishedQa.decide(releaseCommand(batch,"RELEASED",null),token(batch),key());var released=production.batch(id(batch));var finalManifest=archive.generate(id(batch),command(released,"FINAL"),token(released),key());assertThat(finalManifest.path("generationVersion").asInt()).isEqualTo(2);assertThat(finalManifest.path("releaseDecisionId").asText()).isEqualTo(id(decision));assertThat(finalManifest.path("recordDigest").asText()).isNotEqualTo(digest);assertThat(archive.manifest(id(batch),id(copy))).isEqualTo(copy);assertThat(archive.get(id(batch)).path("recordDigest").asText()).isEqualTo(finalManifest.path("recordDigest").asText());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ebr_pdf_manifest WHERE main_batch_id=?",Long.class,id(batch))).isEqualTo(2);
  assertThatThrownBy(()->jdbc.update("UPDATE ebr_pdf_manifest SET archive_kind='FINAL' WHERE id=?",id(copy))).isInstanceOf(org.springframework.dao.DataAccessException.class);
 }
 @Test void preQaFinalAndInvalidatedFinalSignatureAreBlockedWithoutFiles(){var batch=completedQaBatch();long count=jdbc.queryForObject("SELECT COUNT(*) FROM gxp_attachment",Long.class);blockedCode("FINAL_ARCHIVE_DECISION_REQUIRED",()->archive.generate(id(batch),command(batch,"FINAL"),token(batch),key()));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_attachment",Long.class)).isEqualTo(count);as(qa);var decision=finishedQa.decide(releaseCommand(batch,"RELEASED",null),token(batch),key());var sig=signatureRepository.find(1,decision.path("signatureId").asLong());assertThat(signatureRepository.invalidate(1,sig.id(),sig.versionNo(),qa,java.time.Instant.now(),"Controlled quality investigation invalidation")).isTrue();var released=production.batch(id(batch));blockedCode("FINAL_ARCHIVE_DECISION_REQUIRED",()->archive.generate(id(batch),command(released,"FINAL"),token(released),key()));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ebr_pdf_manifest WHERE main_batch_id=?",Long.class,id(batch))).isZero();}
 @Test void archiveAuditFailureRollsBackFileManifestAndKeyThenReplayWorks(){var batch=completedQaBatch();String k=key();long filesBefore=jdbc.queryForObject("SELECT COUNT(*) FROM gxp_attachment",Long.class);doAnswer(inv->{var auditCommand=(com.hospital.mes.audit.domain.AuditCommand)inv.getArgument(0);if(auditCommand.action().equals("EBR_PDF_GENERATED"))throw new IllegalStateException("Injected archive audit failure");return inv.callRealMethod();}).when(audit).append(any());rejected(IllegalStateException.class,()->archive.generate(id(batch),command(batch,"REVIEW_COPY"),token(batch),k));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_attachment",Long.class)).isEqualTo(filesBefore);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ebr_pdf_manifest WHERE main_batch_id=?",Long.class,id(batch))).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,k)).isZero();reset(audit);var first=archive.generate(id(batch),command(batch,"REVIEW_COPY"),token(batch),k);assertThat(archive.generate(id(batch),command(batch,"REVIEW_COPY"),token(batch),k)).isEqualTo(first);}
 @Test void delegatedHttpReadAllowsOnlyOwnedArchiveAndClosedCommands()throws Exception {var batch=completedQaBatch();permissions.add("attachment:upload");as(author);var unrelated=attachments.upload("unrelated.pdf","application/pdf",new byte[]{1,2,3},key());var copy=archive.generate(id(batch),command(batch,"REVIEW_COPY"),token(batch),key());var actualModel=archive.get(id(batch));try{FrozenSchemaAssertions.assertSchema(json,"BatchEbrReadModel",actualModel);}catch(AssertionError mismatch){java.nio.file.Files.writeString(java.nio.file.Path.of(System.getProperty("java.io.tmpdir"),"mes013-archive-response.json"),actualModel.toPrettyString(),java.nio.charset.StandardCharsets.UTF_8);throw mismatch;}FrozenSchemaAssertions.assertSchema(json,"EbrPdfManifest",copy);permissions.remove("attachment:view");as(author);var http=org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user("archive-reader").authorities(new org.springframework.security.core.authority.SimpleGrantedAuthority("ebr:form:view"));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/attachments/"+copy.path("fileId").asText()+"/content").with(http)).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk());mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/attachments/"+unrelated.id()+"/content").with(http)).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isForbidden());when(contexts.current()).thenReturn(new com.hospital.mes.audit.application.CurrentPlatformContext(2,author,Set.of("INCOMING_TEST"),permissions,"incoming-session","other-org"));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/attachments/"+copy.path("fileId").asText()+"/content").with(http)).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isForbidden());as(author);var generate=org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user("archive-writer").authorities(new org.springframework.security.core.authority.SimpleGrantedAuthority("ebr:pdf:generate"));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/v1/main-batches/"+id(batch)+"/ebr/pdf").with(generate).header("If-Match",token(batch)).header("Idempotency-Key",key()).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(body("versionNo",batch.path("versionNo").asLong(),"archiveKind","REVIEW_COPY","reason","Actual archive","inventedField",true).toString())).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isBadRequest());}
}
