package com.hospital.mes.production;
import com.fasterxml.jackson.databind.JsonNode;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import com.hospital.mes.wms.domain.WmsCommands.*;
class FinishedGoodsLifecycleIT extends FinishedReleaseIT {
 @BeforeEach void finishedGoodsPermissions(){permissions.addAll(Set.of("wms:finished-inbound:view","wms:finished-inbound:create","wms:finished-inbound:submit","wms:finished-inbound:confirm","wms:finished-inbound:cancel","wms:finished-shipment:view","wms:finished-shipment:create","wms:finished-shipment:confirm","wms:finished-shipment:cancel"));as(author);}
 @Autowired com.hospital.mes.wms.infrastructure.WmsStore finishedStock;
 @Test void incompleteProductionCannotRequestFinishedWarehouseReceipt(){var running=approvedBatch();blockedCode("FINISHED_PRODUCTION_REQUIRED",()->finishedGoods.createInbound(body("requestNo","EARLY"+suffix,"mainBatchId",id(running),"reason","No precompletion warehouse stock"),key()));}
 @Test void legacyOutputStockIsConfirmedWithoutDuplicateReceipt(){
  var complete=completedProductionBatch(()->{});as(author);String lotId=complete.path("finishedLotId").asText();
  var request=finishedGoods.createInbound(body("requestNo","LEGACY"+suffix,"mainBatchId",id(complete),"reason","Confirm historical measured stock"),key());request=finishedGoods.inboundAction(id(request),"submit",body("versionNo",0,"reason","Submit legacy receipt"),token(request),key());
  var wh=wms.maintenance("Warehouse",null,new WarehouseCreate("LEGW"+suffix,"Legacy finished","FINISHED"),null,key());var location=wms.maintenance("Location",null,new LocationCreate(id(wh),"LEGL"+suffix,"Legacy location"),null,key());
  var legacy=new com.hospital.mes.wms.infrastructure.LedgerEntity();legacy.setMaterialLotId(Long.valueOf(lotId));legacy.setLocationId(Long.valueOf(id(location)));legacy.setUnitId(Long.valueOf(unit));legacy.setDeltaQty(new java.math.BigDecimal("10"));legacy.setEventType("PRODUCTION_OUTPUT");legacy.setSourceType("PRODUCTION_OUTPUT");legacy.setSourceRef("LEGACY"+suffix);legacy.setIdempotencyKey(key());legacy.setOccurredAt(java.time.LocalDateTime.now(java.time.ZoneOffset.UTC));finishedStock.ledger().insert(legacy,1,author);
  as(qa);var confirmed=finishedGoods.inboundAction(id(request),"confirm",body("versionNo",request.path("versionNo").asLong(),"locationId",id(location),"reason","Independent exact legacy verification","signature",Map.of("reauthToken","token")),token(request),key());
  assertThat(confirmed.path("ledgerId").asLong()).isEqualTo(legacy.getId());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_inventory_ledger WHERE material_lot_id=?",Long.class,lotId)).isEqualTo(1);
  assertThat(jdbc.queryForObject("SELECT SUM(delta_qty) FROM wms_inventory_ledger WHERE material_lot_id=?",java.math.BigDecimal.class,lotId)).isEqualByComparingTo("10");assertThat(verifier.verify(1,confirmed.path("signatureId").asLong())).isTrue();
 }
 @Test void finishedWarehouseReceiptRequiresCompletedAndIndependentSourceAndPostsOnlyOnce(){
  var complete=completedProductionBatch(()->{});as(author);
  String lotId=complete.path("finishedLotId").asText();
  assertThat(jdbc.queryForObject("SELECT COALESCE(SUM(delta_qty),0) FROM wms_inventory_ledger WHERE material_lot_id=?",java.math.BigDecimal.class,lotId)).isEqualByComparingTo("0");
  var request=finishedGoods.createInbound(body("requestNo","FIN_REQ"+suffix,"mainBatchId",id(complete),"reason","Actual completed production inbound request"),key());
  assertThat(request.path("quantity").asText()).isEqualTo("10.000000");
  request=finishedGoods.inboundAction(id(request),"submit",body("versionNo",0,"reason","Production submits completed output"),token(request),key());
  var wh=wms.maintenance("Warehouse",null,new WarehouseCreate("FRW"+suffix,"Finished receiving","FINISHED"),null,key());
  var location=wms.maintenance("Location",null,new LocationCreate(id(wh),"FRL"+suffix,"Finished receiving location"),null,key());
  var command=body("versionNo",request.path("versionNo").asLong(),"locationId",id(location),"reason","Independent warehouse confirms actual quantity","signature",Map.of("reauthToken","token"));
  var pending=request;
  blockedCode("FINISHED_RECEIPT_INDEPENDENT",()->finishedGoods.inboundAction(id(pending),"confirm",command,token(pending),key()));
  as(qa);String confirmKey=key();var confirmed=finishedGoods.inboundAction(id(pending),"confirm",command,token(pending),confirmKey);
  assertThat(finishedGoods.inboundAction(id(pending),"confirm",command,token(pending),confirmKey)).isEqualTo(confirmed);
  FrozenSchemaAssertions.assertSchema(json,"FinishedInboundRequest",confirmed);assertThat(confirmed.path("status").asText()).isEqualTo("CONFIRMED");
  assertThat(jdbc.queryForObject("SELECT SUM(delta_qty) FROM wms_inventory_ledger WHERE material_lot_id=?",java.math.BigDecimal.class,lotId)).isEqualByComparingTo("10");
  assertThat(verifier.verify(1,confirmed.path("signatureId").asLong())).isTrue();
  assertThat(stockQuery.materialLot(1,Long.parseLong(lotId)).path("qualityStatus").asText()).isEqualTo("QUARANTINE");
 }
 @BeforeEach void finishedInspectionPermissions(){permissions.addAll(Set.of("qms:finished-request:view","qms:finished-request:create","qms:finished-request:submit","qms:finished-request:accept","qms:finished-sampling:view","qms:finished-sampling:create","qms:finished-report:view","qms:finished-report:generate","qms:finished-report:approve"));as(author);}
 @Test void finishedPostCompletionSamplingFreezesLotAndReportUsesActualReviewedResults(){
  var completed=completedProductionBatch(()->{});var receipt=confirmedFinishedReceipt(completed);var request=acceptedFinishedRequest(receipt);as(author);
  var sampling=finishedInspection.sample(id(request),body("versionNo",request.path("versionNo").asLong(),"samplingNo","FSR"+suffix,"sampleNo","FSM"+suffix,"sampleType","TEST_SAMPLE","samplingLocation","Finished receiving location","quantity","1","unitId",unit,"samplingMethod","Approved representative sampling","reason","Actual post-completion finished sampling","signature",Map.of("reauthToken","token")),token(request),key());
  FrozenSchemaAssertions.assertSchema(json,"FinishedSamplingRecord",sampling);FrozenSchemaAssertions.assertSchema(json,"FinishedInspectionRequest",request);assertThat(sampling.path("materialLotId").asText()).isEqualTo(completed.path("finishedLotId").asText());assertThat(verifier.verify(1,sampling.path("signatureId").asLong())).isTrue();
  var sample=productionQuality.get(com.hospital.mes.qms.application.ProductionQualityService.SAMPLE,sampling.path("sampleId").asText());sample=productionQuality.receiveSample(id(sample),body("versionNo",0,"reason","QC receives actual finished sample"),token(sample),key());
  String item=request.path("specificationSnapshot").path("specification").path("items").get(0).path("specificationItemId").asText();
  var test=productionQuality.createTest(body("sampleId",id(sample),"specificationItemId",item,"reason","Frozen finished assay"),key());test=productionQuality.result(id(test),false,body("versionNo",0,"resultNumeric","2","reason","Actual finished result","signature",Map.of("reauthToken","token")),token(test),key());
  as(reviewer);productionQuality.review(id(test),body("versionNo",test.path("versionNo").asLong(),"resultRevisionId",test.path("currentResultRevisionId").asText(),"disposition","CONFIRMED","reason","Independent original result review","signature",Map.of("reauthToken","token")),token(test),key());
  as(author);var fresh=finishedInspection.getRequest(id(request));var report=finishedInspection.generateReport(id(request),body("versionNo",fresh.path("versionNo").asLong(),"reportNo","FREP"+suffix,"reason","Aggregate actual TestResult only"),token(fresh),key());
  assertThat(report.path("overallConclusion").asText()).isEqualTo("PASS");assertThat(report.path("summary").path("items").get(0).path("effectiveResult").path("id").asText()).isEqualTo(test.path("currentResultRevisionId").asText());
  as(reviewer);report=finishedInspection.approveReport(id(report),body("versionNo",0,"reason","Independent QC report approval","signature",Map.of("reauthToken","token")),token(report),key());FrozenSchemaAssertions.assertSchema(json,"FinishedInspectionReport",report);assertThat(report.path("status").asText()).isEqualTo("APPROVED");
  assertThat(finishedInspection.getRequest(id(request)).path("status").asText()).isEqualTo("COMPLETED");assertThat(stockQuery.materialLot(1,completed.path("finishedLotId").asLong()).path("qualityStatus").asText()).isEqualTo("QUARANTINE");
 }

 @Autowired com.hospital.mes.configuration.FinishedChainQuery finishedChain;
 @Autowired com.hospital.mes.traceability.application.TraceService finishedTrace;
 @Test void completeChainRequiresQaThenShipsExactStockOnceAndTracesAllSources(){
  var completed=completedProductionBatch(()->{});completeFinishedQuality(completed);as(qa);String lot=completed.path("finishedLotId").asText();var receipt=finishedGoods.getInbound(jdbc.queryForObject("SELECT id FROM wms_finished_inbound_request WHERE main_batch_id=?",Long.class,id(completed))+"");
  blockedCode("FINISHED_SHIPMENT_RELEASE_REQUIRED",()->finishedGoods.createShipment(body("shipmentNo","EARLY"+suffix,"mainBatchId",id(completed),"locationId",receipt.path("locationId").asText(),"quantity","4","unitId",unit,"receivingParty","Hospital dispensary","reason","Cannot select unreleased lot"),key()));
  var pending=production.submitQa(id(completed),body("reason","All actual finished evidence ready"),token(completed),key());var d=finishedQa.decide(releaseCommand(pending,"RELEASED",null),token(pending),key());  var shipment=finishedGoods.createShipment(body("shipmentNo","SHIP"+suffix,"mainBatchId",id(completed),"locationId",receipt.path("locationId").asText(),"quantity","4.000001","unitId",unit,"receivingParty","Hospital dispensary","reason","Actual finished dispatch"),key());var command=body("versionNo",0,"reason","Actual release and stock confirmed","signature",Map.of("reauthToken","token"));assertThat(d.path("finishedInspectionReportId").asText()).isNotBlank();String k=key();var shipped=finishedGoods.shipmentAction(id(shipment),"confirm",command,token(shipment),k);assertThat(finishedGoods.shipmentAction(id(shipment),"confirm",command,token(shipment),k)).isEqualTo(shipped);
  assertThat(jdbc.queryForObject("SELECT SUM(delta_qty) FROM wms_inventory_ledger WHERE material_lot_id=?",java.math.BigDecimal.class,lot)).isEqualByComparingTo("5.999999");FrozenSchemaAssertions.assertSchema(json,"FinishedShipment",shipped);assertThat(verifier.verify(1,shipped.path("signatureId").asLong())).isTrue();assertThatThrownBy(()->jdbc.update("UPDATE wms_finished_shipment SET quantity=1 WHERE id=?",id(shipped))).isInstanceOf(org.springframework.dao.DataAccessException.class);
  var chain=finishedChain.get(lot);FrozenSchemaAssertions.assertSchema(json,"FinishedLotChain",chain);assertThat(chain.path("receiving")).hasSize(1);assertThat(chain.path("finishedQuality").path("requests").get(0).path("reports")).hasSize(1);assertThat(chain.path("shipments").get(0).path("releaseDecisionId").asText()).isEqualTo(id(d));var trace=finishedTrace.trace(null,lot);assertThat(trace.path("nodes")).extracting(n->n.path("type").asText()).contains("FINISHED_INBOUND_REQUEST","FINISHED_INSPECTION_REQUEST","FINISHED_SAMPLING_RECORD","SAMPLE","PRODUCTION_TEST","RESULT_REVISION","FINISHED_REPORT","RELEASE_DECISION","FINISHED_SHIPMENT","CHARGE","RECEIPT","RESULT_REVIEW","FINISHED_REPORT_REVIEW","INVENTORY_LEDGER");
  var over=finishedGoods.createShipment(body("shipmentNo","OVER"+suffix,"mainBatchId",id(completed),"locationId",receipt.path("locationId").asText(),"quantity","6","unitId",unit,"receivingParty","Hospital dispensary","reason","Quantity guard trial"),key());blockedCode("FINISHED_SHIPMENT_STOCK_SHORT",()->finishedGoods.shipmentAction(id(over),"confirm",command,token(over),key()));
  permissions.remove("wms:finished-shipment:confirm");as(qa);rejected(com.hospital.mes.common.exception.PermissionException.class,()->finishedGoods.shipmentAction(id(shipment),"confirm",command,token(shipment),k));permissions.add("wms:finished-shipment:confirm");as(qa);
 }
 @Test void finishedReceiptAndFormalReportCannotBeBypassedAtQaSubmission(){var completed=completedProductionBatch(()->{});as(qa);blockedCode("FINISHED_RECEIPT_REQUIRED",()->production.submitQa(id(completed),body("reason","Missing receiving must block"),token(completed),key()));confirmedFinishedReceipt(completed);as(qa);blockedCode("FINISHED_INSPECTION_REQUEST_REQUIRED",()->production.submitQa(id(completed),body("reason","Missing finished QC must block"),token(completed),key()));assertThat(production.batch(id(completed)).path("status").asText()).isEqualTo("PRODUCTION_COMPLETED");}

 JsonNode finishedTest(JsonNode request,String result){as(author);request=finishedInspection.getRequest(id(request));String unique=key();var sampling=finishedInspection.sample(id(request),body("versionNo",request.path("versionNo").asLong(),"samplingNo","SR"+unique,"sampleNo","SA"+unique,"sampleType","TEST_SAMPLE","samplingLocation","Actual finished location","quantity","1","unitId",unit,"samplingMethod","Approved representative method","reason","Post-completion sample","signature",Map.of("reauthToken","token")),token(request),key());var sample=productionQuality.get(com.hospital.mes.qms.application.ProductionQualityService.SAMPLE,sampling.path("sampleId").asText());sample=productionQuality.receiveSample(id(sample),body("versionNo",0,"reason","Receive actual sample"),token(sample),key());String item=request.path("specificationSnapshot").path("specification").path("items").get(0).path("specificationItemId").asText();var t=productionQuality.createTest(body("sampleId",id(sample),"specificationItemId",item,"reason","Frozen finished standard"),key());t=productionQuality.result(id(t),false,body("versionNo",0,"resultNumeric",result,"reason","Actual original result","signature",Map.of("reauthToken","token")),token(t),key());as(reviewer);return productionQuality.review(id(t),body("versionNo",t.path("versionNo").asLong(),"resultRevisionId",t.path("currentResultRevisionId").asText(),"disposition","CONFIRMED","reason","Independent original review","signature",Map.of("reauthToken","token")),token(t),key());}
 @Test void reportMissingResultsSelfApprovalAndChangedSamplingAreControlled(){var completed=completedProductionBatch(()->{});var request=acceptedFinishedRequest(confirmedFinishedReceipt(completed));as(author);var initial=request;blockedCode("FINISHED_SAMPLING_REQUIRED",()->finishedInspection.generateReport(id(initial),body("versionNo",initial.path("versionNo").asLong(),"reportNo","EMPTY"+suffix,"reason","No samples yet"),token(initial),key()));finishedTest(request,"2");as(author);request=finishedInspection.getRequest(id(request));var report=finishedInspection.generateReport(id(request),body("versionNo",request.path("versionNo").asLong(),"reportNo","STALE"+suffix,"reason","Actual report"),token(request),key());var approval=body("versionNo",0,"reason","Independent approval","signature",Map.of("reauthToken","token"));blockedCode("FINISHED_QC_INDEPENDENT_REQUIRED",()->finishedInspection.approveReport(id(report),approval,token(report),key()));finishedTest(request,"2");as(reviewer);blockedCode("FINISHED_REPORT_EVIDENCE_CHANGED",()->finishedInspection.approveReport(id(report),approval,token(report),key()));assertThat(finishedInspection.getReport(id(report)).path("status").asText()).isEqualTo("GENERATED");assertThatThrownBy(()->jdbc.update("UPDATE qms_finished_inspection_report SET summary_json='{}' WHERE id=?",id(report))).isInstanceOf(org.springframework.dao.DataAccessException.class);}
 @Test void finishedRequestReadCannotExposeDeniedSamplingOrReportAndDigestRemainsStable(){var completed=completedProductionBatch(()->{});completeFinishedQuality(completed);var source=finishedInspection.sourceEvidence(1,Long.parseLong(id(completed)));var request=source.path("requests").get(0);permissions.remove("qms:finished-report:view");permissions.remove("qms:finished-sampling:view");as(author);var restricted=finishedInspection.getRequest(id(request));assertThat(restricted.has("reports")).isFalse();assertThat(restricted.has("samplingRecords")).isFalse();var list=finishedInspection.list("requests",0,20,Map.of("mainBatchId",id(completed)));assertThat(list.items().getFirst().has("reports")).isFalse();assertThat(list.items().getFirst().has("samplingRecords")).isFalse();assertThat(finishedInspection.sourceEvidence(1,Long.parseLong(id(completed)))).isEqualTo(source);}
 @Test void unrelatedNewPassingSampleCannotReplaceUnresolvedOriginalFailInReport(){var completed=completedProductionBatch(()->{});var request=acceptedFinishedRequest(confirmedFinishedReceipt(completed));var failed=finishedTest(request,"5");finishedTest(request,"2");as(author);request=finishedInspection.getRequest(id(request));var report=finishedInspection.generateReport(id(request),body("versionNo",request.path("versionNo").asLong(),"reportNo","NO_MASK"+suffix,"reason","All original failures must be resolved by authorized investigation"),token(request),key());assertThat(report.path("overallConclusion").asText()).isEqualTo("FAIL");assertThat(report.path("summary").path("items").get(0).path("originalResults")).hasSize(2);assertThat(jdbc.queryForObject("SELECT result_conclusion FROM qms_test_result_revision WHERE id=?",String.class,failed.path("currentResultRevisionId").asText())).isEqualTo("FAIL");}
 @Test void finishedOriginalFailRemainsAndCannotReleaseOrBecomePassingReport(){var completed=completedProductionBatch(()->{});var request=acceptedFinishedRequest(confirmedFinishedReceipt(completed));var failed=finishedTest(request,"5");as(author);blockedCode("RESULT_CORRECTION_FORBIDDEN",()->productionQuality.result(id(failed),true,body("versionNo",failed.path("versionNo").asLong(),"previousRevisionId",failed.path("currentResultRevisionId").asText(),"resultNumeric","2","reason","Cannot overwrite FAIL","signature",Map.of("reauthToken","token")),token(failed),key()));request=finishedInspection.getRequest(id(request));var report=finishedInspection.generateReport(id(request),body("versionNo",request.path("versionNo").asLong(),"reportNo","FAIL"+suffix,"reason","Report actual failure"),token(request),key());assertThat(report.path("overallConclusion").asText()).isEqualTo("FAIL");as(reviewer);report=finishedInspection.approveReport(id(report),body("versionNo",0,"reason","Document reviewed failure","signature",Map.of("reauthToken","token")),token(report),key());as(qa);blockedCode("PRODUCTION_OOS_UNRESOLVED",()->production.submitQa(id(completed),body("reason","Failure and OOS must block QA submission"),token(completed),key()));assertThat(jdbc.queryForObject("SELECT result_conclusion FROM qms_test_result_revision WHERE id=?",String.class,failed.path("currentResultRevisionId").asText())).isEqualTo("FAIL");assertThat(stockQuery.materialLot(1,completed.path("finishedLotId").asLong()).path("qualityStatus").asText()).isEqualTo("QUARANTINE");}
 @Test void shipmentExpiryFrozenCrossOrgAndConcurrentRootCannotOversell() throws Exception {var pending=completedQaBatch();as(qa);finishedQa.decide(releaseCommand(pending,"RELEASED",null),token(pending),key());String loc=jdbc.queryForObject("SELECT location_id FROM wms_finished_inbound_request WHERE main_batch_id=?",Long.class,id(pending))+"";var shipment=finishedGoods.createShipment(body("shipmentNo","GUARD"+suffix,"mainBatchId",id(pending),"locationId",loc,"quantity","1","unitId",unit,"receivingParty","Hospital dispensary","reason","Boundary trial"),key());var command=body("versionNo",0,"reason","Controlled confirm trial","signature",Map.of("reauthToken","token"));String lot=pending.path("finishedLotId").asText();jdbc.update("UPDATE md_material_lot SET expiry_date=? WHERE id=?",java.time.LocalDate.now(java.time.ZoneOffset.UTC),lot);blockedCode("FINISHED_SHIPMENT_EXPIRED",()->finishedGoods.shipmentAction(id(shipment),"confirm",command,token(shipment),key()));jdbc.update("UPDATE md_material_lot SET expiry_date=?,inventory_status='FROZEN' WHERE id=?",java.time.LocalDate.now(java.time.ZoneOffset.UTC).plusDays(365),lot);blockedCode("FINISHED_SHIPMENT_NOT_RELEASED",()->finishedGoods.shipmentAction(id(shipment),"confirm",command,token(shipment),key()));jdbc.update("UPDATE md_material_lot SET inventory_status='AVAILABLE' WHERE id=?",lot);
  org.mockito.Mockito.when(contexts.current()).thenReturn(new com.hospital.mes.audit.application.CurrentPlatformContext(2,qa,Set.of("TEST"),permissions,"other-session","other-request"));rejected(NoSuchElementException.class,()->finishedGoods.getShipment(id(shipment)));as(qa);
  long actor=jdbc.queryForObject("SELECT MIN(id) FROM sys_user",Long.class);org.mockito.Mockito.when(contexts.current()).thenReturn(new com.hospital.mes.audit.application.CurrentPlatformContext(1,actor,Set.of("TEST"),permissions,"concurrent-session","concurrent-request"));try(var workers=java.util.concurrent.Executors.newSingleThreadExecutor()){var task=workers.submit(()->{var tx=new org.springframework.transaction.support.TransactionTemplate(transactions);tx.setPropagationBehavior(org.springframework.transaction.TransactionDefinition.PROPAGATION_REQUIRES_NEW);tx.setIsolationLevel(org.springframework.transaction.TransactionDefinition.ISOLATION_READ_UNCOMMITTED);return tx.execute(status->{int old=jdbc.queryForObject("SELECT @@innodb_lock_wait_timeout",Integer.class);jdbc.execute("SET SESSION innodb_lock_wait_timeout=1");try{finishedGoods.shipmentAction(id(shipment),"confirm",command,token(shipment),key());return (RuntimeException)null;}catch(RuntimeException e){return e;}finally{status.setRollbackOnly();jdbc.execute("SET SESSION innodb_lock_wait_timeout="+old);}});});assertThat(task.get(10,java.util.concurrent.TimeUnit.SECONDS)).isInstanceOf(com.hospital.mes.common.exception.ResourceConflictException.class);}as(qa);assertThat(jdbc.queryForObject("SELECT SUM(delta_qty) FROM wms_inventory_ledger WHERE material_lot_id=?",java.math.BigDecimal.class,lot)).isEqualByComparingTo("10");}

}
