package com.hospital.mes.production;

import com.fasterxml.jackson.databind.JsonNode;
import com.hospital.mes.common.exception.PermissionException;
import com.hospital.mes.wms.domain.WmsCommands.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;

/** Actual unique native fixtures, rollback-only; no shared seed/schema modifications. */
class FinishedInboundInspectionDraftIT extends FinishedGoodsLifecycleIT {
 private JsonNode paired(JsonNode batch){return body("requestNo","PAIR"+suffix,"mainBatchId",id(batch),"reason","Generate linked finished drafts","createInspectionDraft",true,"inspectionRequestNo","PAIRQC"+suffix);}
 private JsonNode child(JsonNode batch){var list=finishedInspection.list("requests",0,20,Map.of("mainBatchId",id(batch)));assertThat(list.items()).hasSize(1);return list.items().getFirst();}
 private void noPair(JsonNode batch,String commandKey){assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_finished_inbound_request WHERE main_batch_id=?",Long.class,id(batch))).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM qms_finished_inspection_request WHERE main_batch_id=?",Long.class,id(batch))).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,commandKey)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_audit_event WHERE idempotency_key=?",Long.class,commandKey)).isZero();assertThat(jdbc.queryForObject("SELECT COALESCE(SUM(delta_qty),0) FROM wms_inventory_ledger WHERE material_lot_id=?",java.math.BigDecimal.class,batch.path("finishedLotId").asText())).isEqualByComparingTo("0");}

 @Test void pairedDraftReplayFreezesPlanAndWarehouseConfirmationStillControlsQcAndQa(){
  var completed=completedProductionBatch(()->{});as(author);var command=paired(completed);String k=key();var inbound=finishedGoods.createInbound(command,k);assertThat(finishedGoods.createInbound(command,k)).isEqualTo(inbound);var request=child(completed);
  assertThat(inbound.path("status").asText()).isEqualTo("DRAFT");assertThat(request.path("status").asText()).isEqualTo("DRAFT");assertThat(request.path("inboundRequestId").asText()).isEqualTo(id(inbound));assertThat(request.path("mainBatchId").asText()).isEqualTo(id(completed));assertThat(request.path("materialLotId").asText()).isEqualTo(completed.path("finishedLotId").asText());assertThat(request.path("qcSpecificationVersionId").asText()).isEqualTo(request.path("specificationSnapshot").path("qcSpecificationVersionId").asText());assertThat(request.path("allowedActions")).noneMatch(x->"SUBMIT".equals(x.asText()));
  assertThat(jdbc.queryForObject("SELECT COALESCE(SUM(delta_qty),0) FROM wms_inventory_ledger WHERE material_lot_id=?",java.math.BigDecimal.class,completed.path("finishedLotId").asText())).isEqualByComparingTo("0");
  var draft=request;blockedCode("FINISHED_RECEIPT_REQUIRED",()->finishedInspection.requestAction(id(draft),"submit",body("versionNo",0,"reason","Warehouse not received"),token(draft),key()));blockedCode("FINISHED_RECEIPT_REQUIRED",()->finishedInspection.requestAction(id(draft),"accept",body("versionNo",0,"reason","No premature QC acceptance"),token(draft),key()));
  blockedCode("FINISHED_QC_ACCEPTANCE_REQUIRED",()->finishedInspection.sample(id(draft),body("versionNo",0,"samplingNo","EARLYS"+suffix,"sampleNo","EARLYSM"+suffix,"sampleType","TEST_SAMPLE","samplingLocation","No physical receipt yet","quantity","1","unitId",unit,"samplingMethod","Approved method","reason","No early sampling","signature",Map.of("reauthToken","token")),token(draft),key()));as(qa);blockedCode("FINISHED_RECEIPT_REQUIRED",()->production.submitQa(id(completed),body("reason","Draft must not satisfy QA receipt gate"),token(completed),key()));as(author);
  String frozen=request.path("specificationDigest").asText();inbound=finishedGoods.inboundAction(id(inbound),"submit",body("versionNo",0,"reason","Submit actual warehouse application"),token(inbound),key());var wh=wms.maintenance("Warehouse",null,new WarehouseCreate("PDW"+suffix,"Paired receipt","FINISHED"),null,key());var location=wms.maintenance("Location",null,new LocationCreate(id(wh),"PDL"+suffix,"Paired receipt location"),null,key());as(qa);finishedGoods.inboundAction(id(inbound),"confirm",body("versionNo",inbound.path("versionNo").asLong(),"locationId",id(location),"reason","Independent actual receiving","signature",Map.of("reauthToken","token")),token(inbound),key());
  as(author);request=child(completed);assertThat(request.path("allowedActions")).anyMatch(x->"SUBMIT".equals(x.asText()));request=finishedInspection.requestAction(id(request),"submit",body("versionNo",0,"reason","Actual receiving now confirmed"),token(request),key());as(qa);request=finishedInspection.requestAction(id(request),"accept",body("versionNo",request.path("versionNo").asLong(),"reason","QC accepts frozen request"),token(request),key());finishedTest(request,"2");as(author);request=child(completed);assertThat(request.path("specificationDigest").asText()).isEqualTo(frozen);var report=finishedInspection.generateReport(id(request),body("versionNo",request.path("versionNo").asLong(),"reportNo","PDREPORT"+suffix,"reason","Actual finished results"),token(request),key());as(reviewer);finishedInspection.approveReport(id(report),body("versionNo",0,"reason","Independent actual report approval","signature",Map.of("reauthToken","token")),token(report),key());as(qa);var pending=production.submitQa(id(completed),body("reason","Full actual paired receiving and QC evidence"),token(completed),key());finishedQa.decide(releaseCommand(pending,"RELEASED",null),token(pending),key());assertThat(stockQuery.materialLot(1,completed.path("finishedLotId").asLong()).path("inventoryStatus").asText()).isEqualTo("AVAILABLE");
 }

 @Test void deniedChildPermissionAndChildAuditFailureLeaveNoPartialPairOrReplay(){
  var completed=completedProductionBatch(()->{});as(author);var command=paired(completed);String k=key();permissions.remove("qms:finished-request:create");as(author);rejected(PermissionException.class,()->finishedGoods.createInbound(command,k));noPair(completed,k);permissions.add("qms:finished-request:create");as(author);
  org.mockito.Mockito.doAnswer(inv->{var a=(com.hospital.mes.audit.domain.AuditCommand)inv.getArgument(0);if(a.action().equals("FINISHED_INSPECTION_CREATE"))throw new IllegalStateException("Injected child audit failure");return inv.callRealMethod();}).when(audit).append(org.mockito.ArgumentMatchers.any());rejected(IllegalStateException.class,()->finishedGoods.createInbound(command,k));noPair(completed,k);org.mockito.Mockito.reset(audit);
  var created=finishedGoods.createInbound(command,k);assertThat(finishedGoods.createInbound(command,k)).isEqualTo(created);child(completed);rejected(com.hospital.mes.common.exception.ResourceConflictException.class,()->finishedGoods.createInbound(((com.fasterxml.jackson.databind.node.ObjectNode)command.deepCopy()).put("inspectionRequestNo","CHANGED"+suffix),k));assertThat(child(completed).path("inspectionRequestNo").asText()).isEqualTo(command.path("inspectionRequestNo").asText());child(completed);permissions.remove("qms:finished-request:create");as(author);rejected(PermissionException.class,()->finishedGoods.createInbound(command,k));
 }

 @Test void uncheckedAndInvalidOptionsPreserveExistingCreationAndStandaloneReceiptGate(){
  var completed=completedProductionBatch(()->{});as(author);String k=key();rejected(IllegalArgumentException.class,()->finishedGoods.createInbound(body("requestNo","BAD"+suffix,"mainBatchId",id(completed),"reason","Flag must be boolean","createInspectionDraft","true","inspectionRequestNo","BADQC"+suffix),k));noPair(completed,k);rejected(IllegalArgumentException.class,()->finishedGoods.createInbound(body("requestNo","BAD"+suffix,"mainBatchId",id(completed),"reason","Number requires selected option","inspectionRequestNo","BADQC"+suffix),k));noPair(completed,k);
  var inbound=finishedGoods.createInbound(body("requestNo","NORMAL"+suffix,"mainBatchId",id(completed),"reason","Existing creation without inspection option"),k);assertThat(finishedInspection.list("requests",0,20,Map.of("mainBatchId",id(completed))).items()).isEmpty();blockedCode("FINISHED_RECEIPT_REQUIRED",()->finishedInspection.createRequest(body("inspectionRequestNo","STANDALONE"+suffix,"inboundRequestId",id(inbound),"reason","Standalone create retains actual receiving gate"),key()));
 }

 @Test void cancelledInboundPreservesDraftButCannotSubmitInspection(){
  var completed=completedProductionBatch(()->{});as(author);var inbound=finishedGoods.createInbound(paired(completed),key());var request=child(completed);finishedGoods.inboundAction(id(inbound),"cancel",body("versionNo",0,"reason","Cancel unreceived warehouse application"),token(inbound),key());blockedCode("FINISHED_RECEIPT_REQUIRED",()->finishedInspection.requestAction(id(request),"submit",body("versionNo",0,"reason","Cancelled source cannot progress QC"),token(request),key()));assertThat(child(completed).path("status").asText()).isEqualTo("DRAFT");assertThat(child(completed).path("allowedActions")).noneMatch(x->"SUBMIT".equals(x.asText()));
 }
}
