package com.hospital.mes.production;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import static org.assertj.core.api.Assertions.*;
/** Reuses the approved retained native-fixture harness; own lots are rejected after each race. */
class FunctionalClosureConcurrencyIT extends NativeConcurrencyIT {
 @Autowired com.hospital.mes.wms.application.InventoryDecisionService inventory;
 @Autowired com.hospital.mes.execution.application.ClearanceService clearances;
 @Autowired com.hospital.mes.qms.application.IpcService ipc;
 @BeforeEach void functionalPermissions(){permissions.addAll(Set.of("qa:material-inventory:freeze","qa:material-inventory:unfreeze","mes:clearance:record","mes:clearance:review","qms:ipc:view","qms:ipc:record","qms:ipc:review"));as(author);}
 @Override @AfterEach void retainBlockedEvidence() throws Exception {
  if(committed&&"FROZEN".equals(jdbc.queryForObject("SELECT inventory_status FROM md_material_lot WHERE id=?",String.class,lot))){as(qa);var current=wms.get("MaterialLot",lot);new org.springframework.transaction.support.TransactionTemplate(transactions).execute(s->inventory.decide(lot,false,body("versionNo",current.path("versionNo").asLong(),"reason","End retained freeze race before independent QA rejection","signature",Map.of("reauthToken","token")),token(current),key()));}
  super.retainBlockedEvidence();
 }
 @org.junit.jupiter.params.ParameterizedTest
 @org.junit.jupiter.params.provider.CsvSource({"RESERVE,false","ISSUE,true","ISSUE,false","WEIGH,true","WEIGH,false","CHARGE,true","CHARGE,false"})
 void signedFreezeSerializesWithEveryActualFinalProductionGate(String gate,boolean freezeFirst) throws Exception {
  prepareGate(gate);commitFixture();as(author);var productionActor=actorContext.get();as(qa);var qualityActor=actorContext.get();String commandKey=key(),freezeKey=key();long ledgerBefore=jdbc.queryForObject("SELECT COUNT(*) FROM wms_inventory_ledger WHERE material_lot_id=?",Long.class,lot);
  java.util.concurrent.Callable<JsonNode> consume=()->command(gate,commandKey),freeze=()->{var current=wms.get("MaterialLot",lot);return inventory.decide(lot,true,body("versionNo",current.path("versionNo").asLong(),"reason","IT_RACE freeze all final gates","signature",Map.of("reauthToken","token")),token(current),freezeKey);};
  var r=race("SELECT id FROM md_material_lot WHERE id=? FOR UPDATE",lot,freezeFirst?qualityActor:productionActor,freezeFirst?freeze:consume,freezeFirst?productionActor:qualityActor,freezeFirst?consume:freeze);assertThat(r.firstError()).isNull();assertThat(r.first()).isNotNull();
  if(freezeFirst){assertThat(r.secondError()).isInstanceOfSatisfying(com.hospital.mes.common.exception.MesException.class,e->assertThat(e.code()).isIn("MATERIAL_NOT_ELIGIBLE","CONCURRENT_MODIFICATION"));as(author);assertThatThrownBy(()->new org.springframework.transaction.support.TransactionTemplate(transactions).execute(s->command(gate,commandKey))).isInstanceOfSatisfying(com.hospital.mes.common.exception.MesException.class,e->assertThat(e.code()).isEqualTo("MATERIAL_NOT_ELIGIBLE"));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_inventory_ledger WHERE material_lot_id=?",Long.class,lot)).isEqualTo(ledgerBefore);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,commandKey)).isZero();}
  else {if(r.secondError()!=null){assertThat(r.secondError()).isInstanceOfSatisfying(com.hospital.mes.common.exception.MesException.class,e->assertThat(e.code()).isEqualTo("CONCURRENT_MODIFICATION"));as(qa);assertThat(new org.springframework.transaction.support.TransactionTemplate(transactions).<JsonNode>execute(s->{try{return freeze.call();}catch(Exception e){throw new RuntimeException(e);}})).isNotNull();}else assertThat(r.second()).isNotNull();as(author);assertThat(new org.springframework.transaction.support.TransactionTemplate(transactions).<JsonNode>execute(s->command(gate,commandKey))).isEqualTo(r.first());}
  assertThat(jdbc.queryForObject("SELECT inventory_status FROM md_material_lot WHERE id=?",String.class,lot)).isEqualTo("FROZEN");assertThat(jdbc.queryForObject("SELECT quality_status FROM md_material_lot WHERE id=?",String.class,lot)).isEqualTo("RELEASED");var decisions=inventory.history(1,Long.parseLong(lot));assertThat(decisions).hasSize(1);assertThat(verifier.verify(1,decisions.get(0).path("signatureId").asLong())).isTrue();
 }
 @Test void committedFreezeWinsAgainstWaitingReservationWithoutProductionFacts() throws Exception {
  prepareGate("RESERVE");as(qa);var lotView=wms.get("MaterialLot",lot);var payload=body("versionNo",lotView.path("versionNo").asLong(),"reason","Retained real freeze race","signature",Map.of("reauthToken","token"));commitFixture();as(qa);var quality=actorContext.get();as(author);var productionActor=actorContext.get();String freezeKey=key(),reserveKey=key();
  var r=race("SELECT id FROM md_material_lot WHERE id=? FOR UPDATE",lot,quality,()->inventory.decide(lot,true,payload,token(lotView),freezeKey),productionActor,()->command("RESERVE",reserveKey));assertThat(r.firstError()).isNull();assertThat(r.first().path("inventoryStatus").asText()).isEqualTo("FROZEN");assertThat(r.secondError()).isInstanceOfSatisfying(com.hospital.mes.common.exception.MesException.class,e->assertThat(e.code()).isIn("MATERIAL_NOT_ELIGIBLE","CONCURRENT_MODIFICATION"));as(author);assertThatThrownBy(()->new org.springframework.transaction.support.TransactionTemplate(transactions).execute(tx->command("RESERVE",reserveKey))).isInstanceOfSatisfying(com.hospital.mes.common.exception.MesException.class,e->assertThat(e.code()).isEqualTo("MATERIAL_NOT_ELIGIBLE"));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_material_lot_inventory_decision WHERE material_lot_id=?",Long.class,lot)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_reservation WHERE main_batch_id=?",Long.class,batchId)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,reserveKey)).isZero();
 }
 @Test void committedIpcFailBlocksWaitingCompletionUsingCurrentResult() throws Exception {
  ipcDefinitions=List.of(new com.hospital.mes.process.domain.ProcessCommands.IpcDefinition("PH","Acidity",true,"NUMERIC","1","3",null,null,"SOP-IPC/V1"));prepareGate("WEIGH");recordAndSubmitOperationForm(executionId);var op=executionService.operations(executionId).getFirst();var instance=ipc.instances(1,Long.parseLong(id(op))).get(0);var payload=body("versionNo",0,"resultNumeric","4","reason","Retained real IPC race","signature",Map.of("reauthToken","token"));commitFixture();as(author);var actor=actorContext.get();String submitKey=key(),completeKey=key();
  var r=race("SELECT id FROM prd_production_order WHERE id=? FOR UPDATE",orderId,actor,()->ipc.submit(id(instance),payload,token(instance),submitKey),actor,()->executionService.complete(id(op),body("reason","Current IPC must be rechecked"),token(op),completeKey));assertThat(r.firstError()).isNull();assertThat(r.first().path("results").get(0).path("resultConclusion").asText()).isEqualTo("FAIL");assertThat(r.secondError()).isInstanceOfSatisfying(com.hospital.mes.common.exception.MesException.class,e->assertThat(e.code()).isIn("IPC_VALID_FAIL_BLOCKING","CONCURRENT_MODIFICATION"));as(author);var current=executionService.operation(1,Long.parseLong(id(op)));assertThatThrownBy(()->new org.springframework.transaction.support.TransactionTemplate(transactions).execute(tx->executionService.complete(id(op),body("reason","Reload current IPC after concurrency conflict"),token(current),completeKey))).isInstanceOfSatisfying(com.hospital.mes.common.exception.MesException.class,e->assertThat(e.code()).isEqualTo("IPC_VALID_FAIL_BLOCKING"));assertThat(jdbc.queryForObject("SELECT status FROM mes_operation_execution WHERE id=?",String.class,id(op))).isEqualTo("IN_PROGRESS");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,completeKey)).isZero();
 }
 @Test void committedNewClearanceFailPreventsWaitingStartFromUsingOldPass() throws Exception {
  withClearance=true;prepareGate("RESERVE");stock.reserve(batchId,body("items",List.of(Map.of("formulaItemId",formulaId,"materialLotId",lot,"reservedQty","2","unitId",unit)),"reason","Clearance race reservation"),token(batch),key());issue=stock.createIssue(body("mainBatchId",batchId,"issueNo","IT_RACE_CLR_"+suffix,"items",List.of(Map.of("formulaItemId",formulaId,"materialLotId",lot,"issuedQty","2","unitId",unit)),"reason","Clearance race issue"),key());issueId=id(issue);stock.confirmIssue(issueId,body("reason","Clearance race confirm"),token(issue),key());production.startBatch(batchId,body("reason","Clearance race batch start"),token(batch),key());var op=executionService.operations(executionId).getFirst();var record=clearances.record(id(op),body("versionNo",op.path("versionNo").asLong(),"outcome","PASS","reason","Original clearance","signature",Map.of("reauthToken","token")),token(op),key());String original=id(record.path("clearanceRecords").get(0));as(reviewer);var approved=clearances.review(id(op),body("versionNo",record.path("versionNo").asLong(),"clearanceRecordId",original,"decision","APPROVED","reason","Independent original review","signature",Map.of("reauthToken","token")),token(record),key());as(author);var payload=body("versionNo",approved.path("versionNo").asLong(),"previousRecordId",original,"outcome","FAIL","reason","New failed clearance race","signature",Map.of("reauthToken","token"));commitFixture();as(author);var actor=actorContext.get();String recordKey=key(),startKey=key();
  var r=race("SELECT id FROM prd_production_order WHERE id=? FOR UPDATE",orderId,actor,()->clearances.record(id(op),payload,token(approved),recordKey),actor,()->executionService.start(id(op),body("reason","Cannot use old signed PASS"),token(approved),startKey));assertThat(r.firstError()).isNull();assertThat(r.secondError()).isInstanceOfSatisfying(com.hospital.mes.common.exception.MesException.class,e->assertThat(e.code()).isEqualTo("CONCURRENT_MODIFICATION"));as(author);var current=executionService.operation(1,Long.parseLong(id(op)));assertThatThrownBy(()->new org.springframework.transaction.support.TransactionTemplate(transactions).execute(s->executionService.start(id(op),body("reason","Fresh read still sees latest FAIL"),token(current),key()))).isInstanceOfSatisfying(com.hospital.mes.common.exception.MesException.class,e->assertThat(e.code()).isEqualTo("PRECONDITION_FAILED"));assertThat(current.path("status").asText()).isEqualTo("READY");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_clearance_record WHERE operation_execution_id=?",Long.class,id(op))).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,startKey)).isZero();
 }
}
