package com.hospital.mes.production;
import com.fasterxml.jackson.databind.JsonNode;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import static org.assertj.core.api.Assertions.*;
/** Native actual commands; all unique fixture facts roll back with the inherited transaction. */
class FunctionalClosureIT extends IncomingProductionIT {
 @Autowired ApplicationContext application;
 void conflictCode(String code,Runnable action){var tx=new org.springframework.transaction.support.TransactionTemplate(transactions);tx.setPropagationBehavior(org.springframework.transaction.TransactionDefinition.PROPAGATION_NESTED);assertThatThrownBy(()->tx.execute(status->{action.run();return null;})).isInstanceOfSatisfying(com.hospital.mes.common.exception.ResourceConflictException.class,e->assertThat(e.code()).isEqualTo(code));}
 @Autowired com.hospital.mes.execution.application.ClearanceService clearances;
 @Autowired com.hospital.mes.qms.application.IpcService ipc;
 @Autowired com.hospital.mes.wms.application.InventoryDecisionService inventory;
 @org.junit.jupiter.api.BeforeEach void functionalPermissions(){
  permissions.addAll(java.util.Set.of("qa:material-inventory:freeze","qa:material-inventory:unfreeze","mes:clearance:record","mes:clearance:review","qms:ipc:view","qms:ipc:record","qms:ipc:review"));as(author);
 }
 @Test void clearanceRecordAndIndependentReviewAuditFailuresRollBackSignaturesVersionsAndKeys(){
  withClearance=true;var batch=releasedBatch(false);String eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();var payload=body("versionNo",op.path("versionNo").asLong(),"outcome","PASS","reason","Atomic clearance evidence","signature",java.util.Map.of("reauthToken","token"));String recordKey=key();long signatures=jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature",Long.class);
  org.mockito.Mockito.doAnswer(inv->{var a=(com.hospital.mes.audit.domain.AuditCommand)inv.getArgument(0);if(a.action().equals("CLEARANCE_RECORD"))throw new IllegalStateException("injected clearance audit failure");return inv.callRealMethod();}).when(audit).append(org.mockito.ArgumentMatchers.any());rejected(IllegalStateException.class,()->clearances.record(id(op),payload,token(op),recordKey));org.mockito.Mockito.reset(audit);assertThat(clearances.history(1,Long.parseLong(id(op)))).isEmpty();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature",Long.class)).isEqualTo(signatures);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,recordKey)).isZero();assertThat(executionService.operation(1,Long.parseLong(id(op))).path("versionNo").asLong()).isEqualTo(op.path("versionNo").asLong());
  var recorded=clearances.record(id(op),payload,token(op),recordKey);assertThat(clearances.record(id(op),payload,token(op),recordKey)).isEqualTo(recorded);String rid=id(recorded.path("clearanceRecords").get(0));var review=body("versionNo",recorded.path("versionNo").asLong(),"clearanceRecordId",rid,"decision","APPROVED","reason","Atomic independent review","signature",java.util.Map.of("reauthToken","token"));String reviewKey=key();long originalSignatures=jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature",Long.class);as(reviewer);
  org.mockito.Mockito.doAnswer(inv->{var a=(com.hospital.mes.audit.domain.AuditCommand)inv.getArgument(0);if(a.action().equals("CLEARANCE_REVIEW"))throw new IllegalStateException("injected review audit failure");return inv.callRealMethod();}).when(audit).append(org.mockito.ArgumentMatchers.any());rejected(IllegalStateException.class,()->clearances.review(id(op),review,token(recorded),reviewKey));org.mockito.Mockito.reset(audit);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_clearance_review WHERE clearance_record_id=?",Long.class,rid)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature",Long.class)).isEqualTo(originalSignatures);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,reviewKey)).isZero();var approved=clearances.review(id(op),review,token(recorded),reviewKey);assertThat(clearances.review(id(op),review,token(recorded),reviewKey)).isEqualTo(approved);assertThat(verifier.verify(1,approved.path("clearanceRecords").get(0).path("review").path("signatureId").asLong())).isTrue();
 }
 @Test void exactPredecessorSelfReviewStaleVersionAndOtherOrganizationCannotChangeFrozenEvidence(){
  withClearance=true;ipcDefinitions=java.util.List.of(new com.hospital.mes.process.domain.ProcessCommands.IpcDefinition("PH","Acidity",true,"NUMERIC","1","3",null,null,"SOP-IPC/V1"));var batch=releasedBatch(false);String eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();var instance=ipc.instances(1,Long.parseLong(id(op))).get(0);var submitted=ipc.submit(id(instance),body("versionNo",0,"resultNumeric","4","reason","Original protected FAIL","signature",java.util.Map.of("reauthToken","token")),token(instance),key());var original=submitted.path("results").get(0);var self=body("versionNo",submitted.path("versionNo").asLong(),"resultRevisionId",id(original),"disposition","CONFIRMED","reason","Independent reviewer required","signature",java.util.Map.of("reauthToken","token"));blockedCode("INDEPENDENT_REVIEW_REQUIRED",()->ipc.reviewResult(id(instance),self,token(submitted),key()));conflictCode("VERSION_CONFLICT",()->ipc.submit(id(instance),body("versionNo",0,"resultNumeric","2","reason","Stale cannot replace FAIL","signature",java.util.Map.of("reauthToken","token")),token(instance),key()));
  var record=clearanceRecord(op,"PASS",null,null);blockedCode("CLEARANCE_PREDECESSOR_CONFLICT",()->clearanceRecord(record,"FAIL",null,null));
  org.mockito.Mockito.when(contexts.current()).thenReturn(new com.hospital.mes.audit.application.CurrentPlatformContext(2,author,java.util.Set.of("INCOMING_TEST"),permissions,"other-org","other-org"));rejected(java.util.NoSuchElementException.class,()->ipc.get(id(instance)));rejected(java.util.NoSuchElementException.class,()->clearances.record(id(op),body("versionNo",record.path("versionNo").asLong(),"outcome","FAIL","reason","Other org cannot access","signature",java.util.Map.of("reauthToken","token")),token(record),key()));as(author);
  assertThatThrownBy(()->jdbc.update("UPDATE qms_ipc_result_revision SET result_conclusion='PASS' WHERE id=?",id(original))).isInstanceOf(org.springframework.dao.DataAccessException.class);assertThatThrownBy(()->jdbc.update("DELETE FROM qms_ipc_result_revision WHERE id=?",id(original))).isInstanceOf(org.springframework.dao.DataAccessException.class);assertThat(ipc.get(id(instance)).path("results").get(0).path("resultConclusion").asText()).isEqualTo("FAIL");assertThat(verifier.verify(1,original.path("signatureId").asLong())).isTrue();assertThat(clearances.history(1,Long.parseLong(id(op)))).hasSize(1);
 }
 @Test void chargedMaterialReverseTraceIncludesActualSignedInventoryDecisions(){
  var batch=startActualBatch(releasedBatch(false));String eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();var running=executionService.start(id(op),body("reason","Trace actual operation"),token(op),key());var execution=production.execution(eid);String formula=productionQuery.batch(1,Long.parseLong(id(batch))).snapshot().path("process").path("formula").path("items").get(0).path("formulaItemId").asText();var scale=equipment.create(new com.hospital.mes.equipment.application.EquipmentCommands.Create("FTRACE"+suffix,"Trace scale","PRODUCTION_IT_SCALE",java.time.LocalDate.now(java.time.ZoneOffset.UTC).plusDays(30),"Production"),key());var weighed=weighing.createWeighing(body("executionUnitId",eid,"materialLotId",lot,"formulaItemId",formula,"targetQty","2","actualQty","2","unitId",unit,"scaleEquipmentId",id(scale),"versionNo",execution.path("versionNo").asLong(),"reason","Trace actual weighing"),key());as(reviewer);var verified=weighing.verifyWeighing(id(weighed),body("reason","Trace independent weighing verification","reauthToken","token"),token(weighed),key());as(author);var charge=weighing.createCharge(body("executionUnitId",eid,"operationExecutionId",id(op),"materialLotId",lot,"weighingRecordId",id(verified),"chargedQty","2","unitId",unit,"versionNo",running.path("versionNo").asLong(),"reason","Trace actual charged lot"),key());as(qa);var current=wms.get("MaterialLot",lot);var frozen=inventory.decide(lot,true,body("versionNo",current.path("versionNo").asLong(),"reason","Actual post-charge freeze","signature",java.util.Map.of("reauthToken","token")),token(current),key());var decision=frozen.path("inventoryDecisions").get(0);as(author);var graph=trace.trace(id(batch),null);
  assertThat(graph.path("nodes")).anySatisfy(n->{assertThat(n.path("type").asText()).isEqualTo("CHARGE");assertThat(n.path("id").asText()).isEqualTo(id(charge));});assertThat(graph.path("nodes")).anySatisfy(n->{assertThat(n.path("type").asText()).isEqualTo("INVENTORY_DECISION");assertThat(n.path("id").asText()).isEqualTo(id(decision));});assertThat(graph.path("edges")).anySatisfy(e->assertThat(e.path("relation").asText()).isEqualTo("INVENTORY_CONTROL"));assertThat(verifier.verify(1,decision.path("signatureId").asLong())).isTrue();
 }
 @Test void publishedSecondIpcDefinitionDoesNotChangeExistingFirstBatchSnapshot(){
  ipcDefinitions=java.util.List.of(new com.hospital.mes.process.domain.ProcessCommands.IpcDefinition("PH","Acidity",true,"NUMERIC","1","3",null,null,"SOP-IPC/V1"));var batch=releasedBatch(false);String eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();var instance=ipc.instances(1,Long.parseLong(id(op))).get(0);String original=instance.path("definitionSnapshot").toString();String pid=packageVersionId;var current=process.getPackage(pid,null).path("currentDefinition");
  var published=process.saveCurrentDefinition(pid,new com.hospital.mes.process.domain.ProcessCommands.CurrentDefinitionSave(null,null,null,json.convertValue(current.path("formula"),com.hospital.mes.process.domain.ProcessCommands.FormulaSave.class),new com.hospital.mes.process.domain.ProcessCommands.RouteSave(null,"New V2 IPC limit","V2R"+suffix,java.util.List.of(new com.hospital.mes.process.domain.ProcessCommands.Operation("MIX","Mix",1,null,null,java.util.List.of(),null,false,java.util.List.of(),java.util.List.of(new com.hospital.mes.process.domain.ProcessCommands.IpcDefinition("PH","Acidity",true,"NUMERIC","1","5",null,null,"SOP-IPC/V2")))))),null,key()).path("currentDefinition");as(author);
  assertThat(published.path("route").path("operations").get(0).path("ipcDefinitions").get(0).path("upperLimit").asText()).isEqualTo("5");assertThat(ipc.get(id(instance)).path("definitionSnapshot").toString()).isEqualTo(original);assertThat(productionQuery.batch(1,Long.parseLong(id(batch))).snapshot().path("process").path("route").path("operations").get(0).path("ipcDefinitions").get(0).path("upperLimit").asText()).isEqualTo("3");
 }
 @Test void inventoryPermissionSigningAuditRollbackReplayAndExpiryGate(){
  releaseIncoming(()->{});as(qa);var current=wms.get("MaterialLot",lot);var command=body("versionNo",current.path("versionNo").asLong(),"reason","Atomic freeze","signature",java.util.Map.of("reauthToken","token"));String freezeKey=key();
  permissions.remove("qa:material-inventory:freeze");as(qa);rejected(com.hospital.mes.common.exception.PermissionException.class,()->inventory.decide(lot,true,command,token(current),freezeKey));permissions.add("qa:material-inventory:freeze");as(qa);
  permissions.remove("ebr:sign");as(qa);rejected(com.hospital.mes.common.exception.PermissionException.class,()->inventory.decide(lot,true,command,token(current),freezeKey));permissions.add("ebr:sign");as(qa);
  long signatures=jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature",Long.class);
  org.mockito.Mockito.doAnswer(inv->{var a=(com.hospital.mes.audit.domain.AuditCommand)inv.getArgument(0);if(a.action().equals("INVENTORY_FREEZE"))throw new IllegalStateException("injected inventory audit failure");return inv.callRealMethod();}).when(audit).append(org.mockito.ArgumentMatchers.any());
  rejected(IllegalStateException.class,()->inventory.decide(lot,true,command,token(current),freezeKey));org.mockito.Mockito.reset(audit);
  assertThat(wms.get("MaterialLot",lot).path("inventoryStatus").asText()).isEqualTo("AVAILABLE");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_material_lot_inventory_decision WHERE material_lot_id=?",Long.class,lot)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature",Long.class)).isEqualTo(signatures);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,freezeKey)).isZero();
  var frozen=inventory.decide(lot,true,command,token(current),freezeKey);assertThat(inventory.decide(lot,true,command,token(current),freezeKey)).isEqualTo(frozen);
  rejected(com.hospital.mes.common.exception.ResourceConflictException.class,()->inventory.decide(lot,true,command.deepCopy().put("reason","Different command"),token(current),freezeKey));
  jdbc.update("UPDATE md_material_lot SET expiry_date=? WHERE id=?",java.time.LocalDate.now(java.time.ZoneOffset.UTC),lot);
  blockedCode("UNFREEZE_GATE_FAILED",()->inventory.decide(lot,false,body("versionNo",frozen.path("versionNo").asLong(),"reason","Expired cannot unfreeze","signature",java.util.Map.of("reauthToken","token")),token(frozen),key()));assertThat(inventory.history(1,Long.parseLong(lot))).hasSize(1);
 }
 JsonNode clearanceRecord(JsonNode op,String outcome,String previous,String usage){
  var b=body("versionNo",op.path("versionNo").asLong(),"outcome",outcome,"reason","Actual controlled clearance","signature",java.util.Map.of("reauthToken","token"));if(previous!=null)b.put("previousRecordId",previous);if(usage!=null)b.put("equipmentUsageId",usage);return clearances.record(id(op),b,token(op),key());
 }
 JsonNode clearanceReview(JsonNode op,String record,String decision){as(reviewer);var n=clearances.review(id(op),body("versionNo",op.path("versionNo").asLong(),"clearanceRecordId",record,"decision",decision,"reason","Independent exact clearance review","signature",java.util.Map.of("reauthToken","token")),token(op),key());as(author);return n;}
 @Test void newlyBoundEquipmentAndNewFailureInvalidateEarlierClearanceBeforeStartAndResume(){
  withClearance=true;var batch=startActualBatch(releasedBatch(false));String eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();var record=clearanceRecord(op,"PASS",null,null);var approved=clearanceReview(record,id(record.path("clearanceRecords").get(0)),"APPROVED");
  var eq=equipment.create(new com.hospital.mes.equipment.application.EquipmentCommands.Create("CLR"+suffix,"Clearance equipment","PRODUCTION_IT_SCALE",java.time.LocalDate.now(java.time.ZoneOffset.UTC).plusDays(30),"Production"),key());executionService.bindEquipment(id(op),body("equipmentId",id(eq),"usageRole","PROCESS","reason","New binding needs own clearance"),token(approved),key());var bound=executionService.operation(1,Long.parseLong(id(op)));String usage=jdbc.queryForObject("SELECT CAST(id AS CHAR) FROM mes_equipment_usage WHERE operation_execution_id=?",String.class,id(op));
  blockedCode("PRECONDITION_FAILED",()->executionService.start(id(op),body("reason","Old no-equipment clearance cannot cover new binding"),token(bound),key()));
  var fresh=clearanceRecord(bound,"PASS",null,usage);String passId=id(fresh.path("clearanceRecords").get(1));var pass=clearanceReview(fresh,passId,"APPROVED");var running=executionService.start(id(op),body("reason","All current bindings approved"),token(pass),key());var paused=executionService.pause(id(op),body("reason","Pause for new clearance"),token(running),key());var fail=clearanceRecord(paused,"FAIL",passId,usage);String failId=id(fail.path("clearanceRecords").get(2));
  as(reviewer);blockedCode("CLEARANCE_FAILED",()->clearances.review(id(op),body("versionNo",fail.path("versionNo").asLong(),"clearanceRecordId",failId,"decision","APPROVED","reason","FAIL cannot be approved","signature",java.util.Map.of("reauthToken","token")),token(fail),key()));as(author);
  blockedCode("PRECONDITION_FAILED",()->executionService.resume(id(op),body("reason","Old PASS cannot override latest FAIL"),token(fail),key()));
  var corrected=clearanceRecord(fail,"PASS",failId,usage);var reviewed=clearanceReview(corrected,id(corrected.path("clearanceRecords").get(3)),"APPROVED");assertThat(executionService.resume(id(op),body("reason","Latest clearance independently approved"),token(reviewed),key()).path("status").asText()).isEqualTo("IN_PROGRESS");assertThat(clearances.history(1,Long.parseLong(id(op)))).hasSize(4);
 }
 @Test void ipcSignatureRejectionAndAuditFailureLeaveNoPartialFactThenExactReplay(){
  ipcDefinitions=java.util.List.of(new com.hospital.mes.process.domain.ProcessCommands.IpcDefinition("PH","Acidity",true,"NUMERIC","1","3",null,null,"SOP-IPC/V1"));var batch=startActualBatch(releasedBatch(false));String eid=batch.path("executionUnits").get(0).path("id").asText();var instance=ipc.instances(1,Long.parseLong(id(executionService.operations(eid).getFirst()))).get(0);var command=body("versionNo",0,"resultNumeric","2.00000001","reason","Exact decimal original","signature",java.util.Map.of("reauthToken","token"));String submitKey=key();long signatures=jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature",Long.class);
  org.mockito.Mockito.when(reauth.consume(org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.any())).thenThrow(new com.hospital.mes.common.exception.ComplianceException("REAUTH_DENIED","Rejected exact test reauthentication"));blockedCode("REAUTH_DENIED",()->ipc.submit(id(instance),command,token(instance),submitKey));org.mockito.Mockito.doReturn(new com.hospital.mes.audit.signature.ConsumedReauthentication(java.time.Instant.now(),"PASSWORD")).when(reauth).consume(org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.any());
  org.mockito.Mockito.doAnswer(inv->{var a=(com.hospital.mes.audit.domain.AuditCommand)inv.getArgument(0);if(a.action().equals("IPC_RESULT"))throw new IllegalStateException("injected IPC audit failure");return inv.callRealMethod();}).when(audit).append(org.mockito.ArgumentMatchers.any());rejected(IllegalStateException.class,()->ipc.submit(id(instance),command,token(instance),submitKey));org.mockito.Mockito.reset(audit);
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM qms_ipc_result_revision WHERE ipc_instance_id=?",Long.class,id(instance))).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM gxp_signature",Long.class)).isEqualTo(signatures);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,submitKey)).isZero();assertThat(ipc.get(id(instance)).path("status").asText()).isEqualTo("PENDING");
  var result=ipc.submit(id(instance),command,token(instance),submitKey);assertThat(ipc.submit(id(instance),command,token(instance),submitKey)).isEqualTo(result);var original=result.path("results").get(0);assertThat(original.path("resultNumeric").asText()).isEqualTo("2.00000001");assertThat(verifier.verify(1,original.path("signatureId").asLong())).isTrue();String envelope=jdbc.queryForObject("SELECT signature_evidence_json FROM qms_ipc_result_revision WHERE id=?",String.class,id(original));assertThat(envelope).contains("\"resultNumeric\":\"2.00000001\"");
 }
 org.springframework.test.web.servlet.request.RequestPostProcessor httpPermission(String... names){return org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user("closure-http").authorities(java.util.Arrays.stream(names).map(org.springframework.security.core.authority.SimpleGrantedAuthority::new).toArray(org.springframework.security.core.GrantedAuthority[]::new));}
 @Test void frozenActionHttpContractsAuthorizeExactPermissionsAndReturnStringIds() throws Exception {
  withClearance=true;ipcDefinitions=java.util.List.of(new com.hospital.mes.process.domain.ProcessCommands.IpcDefinition("PH","Acidity",true,"NUMERIC","1","3",null,null,"SOP-IPC/V1"));var batch=releasedBatch(false);releaseIncoming(()->{});as(qa);var current=wms.get("MaterialLot",lot);String freezePath="/api/v1/material-lots/"+lot+"/freeze";var payload=body("versionNo",current.path("versionNo").asLong(),"reason","HTTP exact controlled action","signature",java.util.Map.of("reauthToken","token"));
  mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(freezePath).with(httpPermission("wms:inventory:view")).header("If-Match",token(current)).header("Idempotency-Key",key()).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(json.writeValueAsBytes(payload))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isForbidden());
  var frozenHttp=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(freezePath).with(httpPermission("qa:material-inventory:freeze","ebr:sign")).header("If-Match",token(current)).header("Idempotency-Key",key()).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(json.writeValueAsBytes(payload))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk()).andReturn();var frozen=json.readTree(frozenHttp.getResponse().getContentAsString()).path("data");assertThat(frozen.path("id").isTextual()).isTrue();assertThat(frozen.path("inventoryDecisions").get(0).path("signatureId").isTextual()).isTrue();
  var unfreeze=body("versionNo",frozen.path("versionNo").asLong(),"reason","HTTP unfreeze current eligible lot","signature",java.util.Map.of("reauthToken","token"));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/v1/material-lots/"+lot+"/unfreeze").with(httpPermission("qa:material-inventory:unfreeze","ebr:sign")).header("If-Match",token(frozen)).header("Idempotency-Key",key()).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(json.writeValueAsBytes(unfreeze))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk());
  as(author);String eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();String clearancePath="/api/v1/operations/"+id(op)+"/record-clearance";var clearance=body("versionNo",op.path("versionNo").asLong(),"outcome","PASS","reason","HTTP clearance exact record","signature",java.util.Map.of("reauthToken","token"));
  var clearHttp=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(clearancePath).with(httpPermission("mes:clearance:record","ebr:sign")).header("If-Match",token(op)).header("Idempotency-Key",key()).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(json.writeValueAsBytes(clearance))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk()).andReturn();assertThat(json.readTree(clearHttp.getResponse().getContentAsString()).path("data").path("clearanceRecords").get(0).path("id").isTextual()).isTrue();
  var instance=ipc.instances(1,Long.parseLong(id(op))).get(0);String ipcPath="/api/v1/ipc/"+id(instance);mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get(ipcPath).with(httpPermission("mes:operation:view"))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isForbidden());mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get(ipcPath).with(httpPermission("qms:ipc:view"))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk());var resultPayload=body("versionNo",0,"resultNumeric","2","reason","HTTP exact IPC","signature",java.util.Map.of("reauthToken","token"));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(ipcPath+"/submit-result").with(httpPermission("qms:ipc:record","ebr:sign")).header("Idempotency-Key",key()).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(json.writeValueAsBytes(resultPayload))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isBadRequest());var ipcHttp=mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(ipcPath+"/submit-result").with(httpPermission("qms:ipc:record","ebr:sign")).header("If-Match",token(instance)).header("Idempotency-Key",key()).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(json.writeValueAsBytes(resultPayload))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk()).andReturn();var result=json.readTree(ipcHttp.getResponse().getContentAsString()).path("data").path("results").get(0);assertThat(result.path("resultNumeric").isTextual()).isTrue();assertThat(result.path("id").isTextual()).isTrue();
 }
 @Test void requiredClearanceNeedsRealIndependentSignedEvidenceBeforeStart() {
  withClearance=true;var batch=startActualBatch(releasedBatch(false));String eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();
  blockedCode("PRECONDITION_FAILED",()->executionService.start(id(op),body("reason","No clearance evidence"),token(op),key()));
  var recorded=clearances.record(id(op),body("versionNo",op.path("versionNo").asLong(),"outcome","PASS","reason","Actual clearance execution","signature",java.util.Map.of("reauthToken","token")),token(op),key());String clearanceId=recorded.path("clearanceRecords").get(0).path("id").asText();
  var review=body("versionNo",recorded.path("versionNo").asLong(),"clearanceRecordId",clearanceId,"decision","APPROVED","reason","Independent clearance review","signature",java.util.Map.of("reauthToken","token"));
  blockedCode("INDEPENDENT_REVIEW_REQUIRED",()->clearances.review(id(op),review,token(recorded),key()));
  as(reviewer);var approved=clearances.review(id(op),review,token(recorded),key());as(author);
  var started=executionService.start(id(op),body("reason","Start after real clearance"),token(approved),key());assertThat(started.path("status").asText()).isEqualTo("IN_PROGRESS");
  for(var fact:started.path("clearanceRecords")){assertThat(verifier.verify(1,fact.path("signatureId").asLong())).isTrue();assertThat(verifier.verify(1,fact.path("review").path("signatureId").asLong())).isTrue();}
 }
 @Test void pendingIpcBlocksCompletionThenOriginalFailRequiresSignedInvalidationAndNewResult() {
  ipcDefinitions=java.util.List.of(new com.hospital.mes.process.domain.ProcessCommands.IpcDefinition("PH","Acidity",true,"NUMERIC","1","3",null,null,"SOP-IPC/V1"));
  var batch=startActualBatch(releasedBatch(false));String eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();var started=executionService.start(id(op),body("reason","Actual production start"),token(op),key());recordAndSubmitOperationForm(eid);
  var instances=executionService.operations(eid).getFirst().path("ipcInstances");assertThat(instances).hasSize(1);var instance=instances.get(0);assertThat(instance.path("status").asText()).isEqualTo("PENDING");
  blockedCode("IPC_REQUIRED_PENDING",()->executionService.complete(id(op),body("reason","Required actual IPC pending"),token(started),key()));
  var fail=ipc.submit(id(instance),body("versionNo",0,"resultNumeric","4","reason","Original measured FAIL","signature",java.util.Map.of("reauthToken","token")),token(instance),key());var original=fail.path("results").get(0);assertThat(original.path("resultConclusion").asText()).isEqualTo("FAIL");
  blockedCode("IPC_ORIGINAL_RESULT_PROTECTED",()->ipc.submit(id(instance),body("versionNo",fail.path("versionNo").asLong(),"previousRevisionId",id(original),"resultNumeric","2","reason","Cannot replace FAIL","signature",java.util.Map.of("reauthToken","token")),token(fail),key()));
  as(reviewer);var invalid=ipc.reviewResult(id(instance),body("versionNo",fail.path("versionNo").asLong(),"resultRevisionId",id(original),"disposition","INVALIDATED","reason","Approved invalid measurement; original retained","signature",java.util.Map.of("reauthToken","token")),token(fail),key());as(author);
  var pass=ipc.submit(id(instance),body("versionNo",invalid.path("versionNo").asLong(),"previousRevisionId",id(original),"resultNumeric","2","reason","New measurement after approved invalidation","signature",java.util.Map.of("reauthToken","token")),token(invalid),key());var current=pass.path("results").get(1);
  blockedCode("IPC_REQUIRED_PENDING",()->executionService.complete(id(op),body("reason","PASS still awaiting independent confirmation"),token(started),key()));as(reviewer);
  var confirmed=ipc.reviewResult(id(instance),body("versionNo",pass.path("versionNo").asLong(),"resultRevisionId",id(current),"disposition","CONFIRMED","reason","Confirm exact current PASS","signature",java.util.Map.of("reauthToken","token")),token(pass),key());as(author);
  assertThat(confirmed.path("results").get(0).path("resultConclusion").asText()).isEqualTo("FAIL");assertThat(verifier.verify(1,original.path("signatureId").asLong())).isTrue();
  var completed=executionService.complete(id(op),body("reason","All required IPC independently confirmed"),token(started),key());assertThat(completed.path("status").asText()).isEqualTo("COMPLETED");
  blockedCode("IPC_OPERATION_NOT_MUTABLE",()->ipc.reviewResult(id(instance),body("versionNo",confirmed.path("versionNo").asLong(),"resultRevisionId",id(current),"disposition","INVALIDATED","reason","Completed evidence cannot be changed","signature",java.util.Map.of("reauthToken","token")),token(confirmed),key()));
 }
 @Test void signedInventoryFreezeBlocksActualReservationAndUnfreezeRestoresEligibility() throws Exception {
  releaseIncoming(()->{}); as(qa); var batch=releasedBatch(false); as(qa);
  assertThat(application.containsBean("inventoryDecisionService")).as("approved freeze business producer exists").isTrue();
  var commands=application.getBean("inventoryDecisionService");
  var action=commands.getClass().getMethod("decide",String.class,boolean.class,JsonNode.class,String.class,String.class);
  var current=wms.get("MaterialLot",lot);
  JsonNode frozen=(JsonNode)action.invoke(commands,lot,true,body("versionNo",current.path("versionNo").asLong(),"reason","Actual signed inventory restriction","signature",java.util.Map.of("reauthToken","token")),token(current),key());
  assertThat(frozen.path("inventoryStatus").asText()).isEqualTo("FROZEN");
  assertThat(frozen.path("qualityStatus").asText()).isEqualTo("RELEASED");
  as(author); var formula=productionQuery.batch(1,Long.parseLong(id(batch))).snapshot().path("process").path("formula").path("items").get(0).path("formulaItemId").asText();
  assertReservationBlocked(id(batch),formula,token(batch)); as(qa);
  JsonNode available=(JsonNode)action.invoke(commands,lot,false,body("versionNo",frozen.path("versionNo").asLong(),"reason","Restriction resolved; QA release remains valid","signature",java.util.Map.of("reauthToken","token")),token(frozen),key());
  assertThat(available.path("inventoryStatus").asText()).isEqualTo("AVAILABLE");
  assertThat(available.path("inventoryDecisions")).hasSize(2);
  for(var decision:available.path("inventoryDecisions")) assertThat(verifier.verify(1,decision.path("signatureId").asLong())).isTrue();
  assertThat(queries.evaluate(1,Long.parseLong(lot),"PRODUCTION",java.time.Instant.now()).path("eligible").asBoolean()).isTrue();
 }
}
