package com.hospital.mes.production;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.hospital.mes.incoming.IncomingQualityFixture;
import com.hospital.mes.production.application.*;
import com.hospital.mes.execution.application.*;
import com.hospital.mes.traceability.application.TraceService;
import com.hospital.mes.wms.application.*;
import com.hospital.mes.process.application.*;
import com.hospital.mes.process.domain.ProcessCommands;
import com.hospital.mes.ebr.application.EbrService;
import com.hospital.mes.ebr.domain.EbrCommands;
import com.hospital.mes.equipment.application.*;
import java.util.*;
import java.time.*;
import java.math.BigDecimal;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.core.env.MapPropertySource;

/** Actual receipt/QC/QA/production/stock/signature chain; unique fixtures rolled back by base class. */
@SpringBootTest(properties={
 "mes.qualification.required-codes.sample-execute=IQ_INCOMING_IT",
 "mes.qualification.required-codes.test-execute=IQ_INCOMING_IT",
 "mes.qualification.required-codes.test-review=IQ_INCOMING_IT",
 "mes.qualification.required-codes.qa-release=IQ_INCOMING_IT",
 "mes.qualification.required-codes.operation-start=IQ_INCOMING_IT",
 "mes.qualification.required-codes.operation-resume=IQ_INCOMING_IT",
 "mes.qualification.required-codes.weigh-create=IQ_INCOMING_IT",
 "mes.qualification.required-codes.weigh-verify=IQ_INCOMING_IT",
 "mes.qualification.required-codes.charge-create=IQ_INCOMING_IT",
 "mes.qualification.required-codes.charge-reverse=IQ_INCOMING_IT",
 "mes.weighing.scale-equipment-types=PRODUCTION_IT_SCALE"})
@org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc
class IncomingProductionIT extends IncomingQualityFixture {
 @Autowired org.springframework.test.web.servlet.MockMvc mvc;
 @Autowired @org.springframework.beans.factory.annotation.Qualifier("requestMappingHandlerMapping") org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping productionMappings;
 @Autowired ProductionService production; @Autowired ProductionQueryService productionQuery;
 @Autowired ProcessService process; @Autowired ProcessQueryService processQuery;
 @Autowired EbrService ebr; @Autowired ExecutionService executionService;
 @Autowired WeighChargeService weighing; @Autowired WmsProductionService stock;
 @Autowired WmsQueryService stockQuery; @Autowired EquipmentService equipment;
 @Autowired com.hospital.mes.ebr.application.EbrRuntimeService runtime; @Autowired TraceService trace; @Autowired ConfigurableEnvironment environment;
 List<ProcessCommands.IpcDefinition> ipcDefinitions=List.of();
 String configurationName,packageVersionId,templateVersionId,productId,orderId,incomingReportId; boolean withSubBatches,withParameters,withClearance;
 @Test void requiredClearanceWithoutProducerBlocksStartAndClientCannotSupplyPassed(){
  withClearance=true;var batch=startActualBatch(releasedBatch());String eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();
  blockedCode("PRECONDITION_FAILED",()->executionService.start(id(op),body("reason","Missing actual clearance"),token(op),key()));
  rejected(IllegalArgumentException.class,()->executionService.start(id(op),body("reason","Client cannot certify clearance","clearancePassed",true),token(op),key()));
  assertThat(executionService.operation(1,Long.parseLong(id(op))).path("status").asText()).isEqualTo("READY");
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_equipment_run r JOIN mes_equipment_usage u ON u.id=r.equipment_usage_id WHERE u.operation_execution_id=?",Long.class,id(op))).isZero();
 }
 @org.springframework.test.context.bean.override.mockito.MockitoSpyBean com.hospital.mes.execution.infrastructure.GenealogyMapper genealogyMapper;

 @BeforeEach void productionPermissions(){
  for(String prefix:List.of("master:product:","master:equipment:","process:package:","ebr:template:","production:order:","production:batch:","mes:execution:","mes:operation:","mes:weigh:","mes:charge:","wms:reservation:","wms:issue:"))
   for(String action:List.of("view","create","update","edit","submit","approve","publish","release","start","pause","complete","verify","reverse","confirm","return"))permissions.add(prefix+action);
  permissions.addAll(Set.of("production:subbatch:create","mes:equipment:bind","mes:param:record","qa:batch-review","ebr:designer:edit","trace:view","ebr:form:view","ebr:form:edit","ebr:form:submit"));as(author);
  configurationName="production-it-"+suffix;var properties=new HashMap<String,Object>();String p="mes.production.material-weighing-policies[0].";
  properties.put(p+"organization-id","1");properties.put(p+"material-id",material);properties.put(p+"required",true);properties.put(p+"precision","0.001");properties.put(p+"tolerance-pct","0.5");properties.put(p+"policy-version","TEST-"+suffix);
  environment.getPropertySources().addFirst(new MapPropertySource(configurationName,properties));
 }
 @AfterEach void removeTestConfiguration(){if(configurationName!=null)environment.getPropertySources().remove(configurationName);}

 JsonNode releaseIncoming(Runnable beforeQa){as(analyst);var request=request();var sampling=sample(request);var task=task(request,sampling);var measured=execution(task);var result=result(task,measured,"2","PASS");review(task,result);var report=report(request);beforeQa.run();as(qa);var gate=service.releaseReview(lot);service.decideRelease(lot,body("decision","RELEASED","releaseBasis","FULL_INSPECTION","inspectionReportId",id(report),"reason","Actual independent incoming release","reauthToken","token"),token(gate),key());return report;}
 JsonNode releasedBatch(){return releasedBatch(false);}
 JsonNode releasedBatch(boolean duplicateMaterialLine){var batch=preparedBatch(duplicateMaterialLine);return production.releaseBatch(id(batch),body("packageVersionId",packageVersionId,"ebrTemplateVersionId",templateVersionId,"reason","Release actual batch"),token(batch),key());}
 JsonNode preparedBatch(boolean duplicateMaterialLine){
  as(author);var product=process.createProduct(new ProcessCommands.ProductCreate("PP"+suffix,"Production integration product",null,null,unit),key());var pkg=process.createPackage(new ProcessCommands.PackageCreate(id(product),"PK"+suffix),key());String packageId=pkg.path("selectedVersion").path("id").asText();
  process.saveFormula(packageId,new ProcessCommands.FormulaSave(0L,"Real formula","PF"+suffix,"10",unit,duplicateMaterialLine?List.of(new ProcessCommands.FormulaLine(1,material,"2",unit,"0",true),new ProcessCommands.FormulaLine(2,material,"1",unit,"0",true)):List.of(new ProcessCommands.FormulaLine(1,material,"2",unit,"0",true))),null,key());
  process.saveRoute(packageId,new ProcessCommands.RouteSave(1L,"Controlled route","PR"+suffix,withParameters?List.of(new ProcessCommands.Operation("MIX","Mix",1,null,null,List.of(),"PRODUCTION_IT_SCALE",withClearance,List.of(new ProcessCommands.Parameter("MASS","Mass","HYBRID",unit,"1","3")),ipcDefinitions),new ProcessCommands.Operation("FINISH","Finish",2,null,null,List.of("MIX"),null,false,List.of())):List.of(new ProcessCommands.Operation("MIX","Mix",1,null,null,List.of(),null,withClearance,List.of(),ipcDefinitions))),null,key());
  process.transition(packageId,"SUBMIT",new ProcessCommands.Transition(2L,"Submit",null),null,key());as(approver);process.transition(packageId,"APPROVE",new ProcessCommands.Transition(3L,"Independent approve","token"),null,key());process.transition(packageId,"PUBLISH",new ProcessCommands.Transition(4L,"Publish",null),null,key());as(author);
  String operationDef=processQuery.operations(1,Long.parseLong(packageId)).getFirst().id();var field=new EbrCommands.Field("OBS",null,"Observation","TEXT","MANUAL","STRING",null,null,true,false,null,null,null,1,null,List.of());
  var definition=new EbrCommands.Definition(List.of(),List.of(new EbrCommands.Form("F","Production form",operationDef,"1.0",1,List.of(field))),List.of(),List.of(),List.of());var template=ebr.create(new EbrCommands.Create(packageId,"PT"+suffix),key());template=ebr.save(id(template),new EbrCommands.Save(0L,"Real eBR definition",definition),null,key());template=ebr.command(id(template),"SUBMIT",new EbrCommands.Command(template.path("versionNo").asLong(),"Submit"),null,key());as(approver);template=ebr.command(id(template),"APPROVE",new EbrCommands.Command(template.path("versionNo").asLong(),"Independent approval"),null,key());template=ebr.command(id(template),"PUBLISH",new EbrCommands.Command(template.path("versionNo").asLong(),"Publish"),null,key());as(author);
  var order=production.createOrder(body("orderNo","PO"+suffix,"productId",id(product),"plannedQty","10","unitId",unit,"reason","Real order"),key());var batchBody=body("batchNo","PB"+suffix,"productionOrderId",id(order),"productId",id(product),"plannedQty","10","unitId",unit,"reason","Real batch");if(withSubBatches)((com.fasterxml.jackson.databind.node.ObjectNode)batchBody).set("subBatchPlan",json.valueToTree(List.of(Map.of("subBatchNo","S1"+suffix,"sequenceNo",1,"plannedQty","4"),Map.of("subBatchNo","S2"+suffix,"sequenceNo",2,"plannedQty","6"))));var batch=production.createBatch(batchBody,key());packageVersionId=packageId;templateVersionId=id(template);productId=id(product);orderId=id(order);return batch;
 }
 void assertReservationBlocked(String batchId,String formula,String match){var tx=new org.springframework.transaction.support.TransactionTemplate(transactions);tx.setPropagationBehavior(org.springframework.transaction.TransactionDefinition.PROPAGATION_NESTED);assertThatThrownBy(()->tx.execute(status->stock.reserve(batchId,body("items",List.of(Map.of("formulaItemId",formula,"materialLotId",lot,"reservedQty","3","unitId",unit)),"reason","Prove actual production reservation blocked"),match,key()))).isInstanceOf(com.hospital.mes.common.exception.ComplianceException.class);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_reservation WHERE main_batch_id=?",Long.class,batchId)).isZero();long issuesBefore=jdbc.queryForObject("SELECT COUNT(*) FROM wms_material_issue WHERE main_batch_id=?",Long.class,batchId);long ledgerBefore=jdbc.queryForObject("SELECT COUNT(*) FROM wms_inventory_ledger WHERE material_lot_id=?",Long.class,lot);blockedCode("MATERIAL_NOT_ELIGIBLE",()->stock.createIssue(body("mainBatchId",batchId,"issueNo","BLOCKED-"+key(),"items",List.of(Map.of("formulaItemId",formula,"materialLotId",lot,"issuedQty","1","unitId",unit)),"reason","Actual issue rejects ineligible incoming lot"),key()));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_material_issue WHERE main_batch_id=?",Long.class,batchId)).isEqualTo(issuesBefore);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_material_issue_item i JOIN wms_material_issue h ON h.id=i.issue_id WHERE h.main_batch_id=?",Long.class,batchId)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_inventory_ledger WHERE material_lot_id=?",Long.class,lot)).isEqualTo(ledgerBefore);}
 void rejected(Class<? extends Throwable> type,Runnable action){var tx=new org.springframework.transaction.support.TransactionTemplate(transactions);tx.setPropagationBehavior(org.springframework.transaction.TransactionDefinition.PROPAGATION_NESTED);assertThatThrownBy(()->tx.execute(status->{action.run();return null;})).isInstanceOf(type);}
 void blockedCode(String code,Runnable action){var tx=new org.springframework.transaction.support.TransactionTemplate(transactions);tx.setPropagationBehavior(org.springframework.transaction.TransactionDefinition.PROPAGATION_NESTED);assertThatThrownBy(()->tx.execute(status->{action.run();return null;})).isInstanceOfSatisfying(com.hospital.mes.common.exception.ComplianceException.class,ex->assertThat(ex.code()).isEqualTo(code));}
 void blocked(Runnable action){rejected(com.hospital.mes.common.exception.ComplianceException.class,action);}
 BigDecimal onHand(){return stockQuery.ledger(1,Long.parseLong(lot)).stream().map(x->new BigDecimal(x.path("deltaQty").asText())).reduce(BigDecimal.ZERO,BigDecimal::add);}

 @Test void sameMaterialDifferentFormulaLineCannotBorrowReservationEntitlement(){
  releaseIncoming(()->{});as(author);var batch=releasedBatch(true);String batchId=id(batch);var items=productionQuery.batch(1,Long.parseLong(batchId)).snapshot().path("process").path("formula").path("items");String first=items.get(0).path("formulaItemId").asText(),second=items.get(1).path("formulaItemId").asText();
  stock.reserve(batchId,body("items",List.of(Map.of("formulaItemId",first,"materialLotId",lot,"reservedQty","3","unitId",unit)),"reason","Reserve only first formula line"),token(batch),key());
  var issue=stock.createIssue(body("mainBatchId",batchId,"issueNo","PAIR"+suffix,"items",List.of(Map.of("formulaItemId",second,"materialLotId",lot,"issuedQty","1","unitId",unit)),"reason","Same material, different frozen formula line"),key());
  blockedCode("ISSUE_EXCEEDS_RESERVATION",()->stock.confirmIssue(id(issue),body("reason","Must reject cross-line entitlement"),token(issue),key()));assertThat(jdbc.queryForObject("SELECT status FROM wms_material_issue WHERE id=?",String.class,id(issue))).isEqualTo("DRAFT");
  stock.reserve(batchId,body("items",List.of(Map.of("formulaItemId",second,"materialLotId",lot,"reservedQty","1","unitId",unit)),"reason","Reserve exact second formula line"),token(batch),key());
  var confirmed=stock.confirmIssue(id(issue),body("reason","Exact line reservation now exists"),token(issue),key());assertThat(confirmed.path("status").asText()).isEqualTo("CONFIRMED");
 }

 @Test void realIncomingReleaseThroughSignedWeighChargeReturnAndReversePreservesTrace(){
  var batch=releasedBatch();String batchId=id(batch),executionId=batch.path("executionUnits").get(0).path("id").asText();var snapshot=productionQuery.batch(1,Long.parseLong(batchId)).snapshot();String formula=snapshot.path("process").path("formula").path("items").get(0).path("formulaItemId").asText();
  String batchVersion=token(batch);assertReservationBlocked(batchId,formula,batchVersion);var report=releaseIncoming(()->{as(author);assertReservationBlocked(batchId,formula,batchVersion);});as(author);
  var frozenPolicy=snapshot.path("materials").get(0).path("weighingPolicy").deepCopy();var config=(MapPropertySource)environment.getPropertySources().get(configurationName);config.getSource().put("mes.production.material-weighing-policies[0].tolerance-pct","8");assertThat(productionQuery.batch(1,Long.parseLong(batchId)).snapshot().path("materials").get(0).path("weighingPolicy")).isEqualTo(frozenPolicy);
  assertThat(snapshot.path("materials").get(0).path("weighingPolicy").path("required").asBoolean()).isTrue();
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ebr_form_instance f JOIN mes_operation_execution o ON o.id=f.operation_execution_id JOIN prd_execution_unit u ON u.id=o.execution_unit_id WHERE u.main_batch_id=?",Long.class,batchId)).isPositive();
  stock.reserve(batchId,body("items",List.of(Map.of("formulaItemId",formula,"materialLotId",lot,"reservedQty","3","unitId",unit)),"reason","Reserve eligible actual lot"),token(batch),key());
  var issue=stock.createIssue(body("mainBatchId",batchId,"issueNo","PI"+suffix,"items",List.of(Map.of("formulaItemId",formula,"materialLotId",lot,"issuedQty","3","unitId",unit)),"reason","Issue reservation"),key());issue=stock.confirmIssue(id(issue),body("reason","Confirm actual issue"),token(issue),key());
  blocked(()->{var excess=stock.createIssue(body("mainBatchId",batchId,"issueNo","EXCESS"+suffix,"items",List.of(Map.of("formulaItemId",formula,"materialLotId",lot,"issuedQty","1","unitId",unit)),"reason","Reject overissue"),key());stock.confirmIssue(id(excess),body("reason","Reject entitlement overflow"),token(excess),key());});
  batch=production.startBatch(batchId,body("reason","Start"),token(batch),key());var op=executionService.operations(executionId).getFirst();op=executionService.start(id(op),body("reason","Start operation"),token(op),key());
  var scale=equipment.create(new EquipmentCommands.Create("SC"+suffix,"Actual configured scale","PRODUCTION_IT_SCALE",LocalDate.now(ZoneOffset.UTC).plusDays(30),"Production"),key());var unitFact=production.execution(executionId);
  var weighed=weighing.createWeighing(body("executionUnitId",executionId,"materialLotId",lot,"formulaItemId",formula,"targetQty","2","actualQty","2","unitId",unit,"scaleEquipmentId",id(scale),"versionNo",unitFact.path("versionNo").asLong(),"reason","Controlled actual weighing"),key());
  String opId=id(op);long opVersion=op.path("versionNo").asLong();String unverifiedId=id(weighed);blocked(()->weighing.verifyWeighing(unverifiedId,body("reason","Reject self verification","reauthToken","token"),token(weighed),key()));blocked(()->weighing.createCharge(body("executionUnitId",executionId,"operationExecutionId",opId,"materialLotId",lot,"weighingRecordId",unverifiedId,"chargedQty","2","unitId",unit,"versionNo",opVersion,"reason","Reject unsigned weighing"),key()));blocked(()->weighing.createCharge(body("executionUnitId",executionId,"operationExecutionId",opId,"materialLotId",lot,"chargedQty","2","unitId",unit,"versionNo",opVersion,"reason","Reject missing required weighing"),key()));
  org.mockito.Mockito.when(contexts.current()).thenReturn(new com.hospital.mes.audit.application.CurrentPlatformContext(2,author,Set.of("INCOMING_TEST"),permissions,"incoming-session","wrong-org"));rejected(java.util.NoSuchElementException.class,()->production.batch(batchId));as(author);
  String weighingId=id(weighed);String verificationKey=key();var verification=body("reason","Independent verification","reauthToken","token");String weighingVersion=token(weighed);as(reviewer);var verified=weighing.verifyWeighing(weighingId,verification,weighingVersion,verificationKey);assertThat(weighing.verifyWeighing(weighingId,verification,weighingVersion,verificationKey)).isEqualTo(verified);long signature=verified.path("signatureEvidence").get(0).path("signatureId").asLong();assertThat(verifier.verify(1,signature)).isTrue();
  as(author);BigDecimal before=onHand();var chargeBody=body("executionUnitId",executionId,"operationExecutionId",id(op),"materialLotId",lot,"weighingRecordId",weighingId,"chargedQty","2","unitId",unit,"versionNo",op.path("versionNo").asLong(),"reason","Actual charge");String chargeKey=key();var charge=weighing.createCharge(chargeBody,chargeKey);assertThat(weighing.createCharge(chargeBody,chargeKey)).isEqualTo(charge);assertThat(onHand()).isEqualByComparingTo(before.subtract(new BigDecimal("2")));assertThat(verifier.verify(1,signature)).isTrue();
  String issueId=id(issue),issueVersion=token(issue);String issueItem=issue.path("items").get(0).path("id").asText();blocked(()->stock.returnIssue(issueId,body("items",List.of(Map.of("issueItemId",issueItem,"quantity","2","unitId",unit)),"reason","Reject return of consumed entitlement"),issueVersion,key()));var returned=stock.returnIssue(id(issue),body("items",List.of(Map.of("issueItemId",issueItem,"quantity","1","unitId",unit)),"reason","Return unused entitlement"),token(issue),key());assertThat(returned.path("returns")).hasSize(1);assertThat(onHand()).isEqualByComparingTo(before.subtract(new BigDecimal("2")));
  var graph=trace.trace(batchId,null);assertThat(graph.toString()).contains("CHARGE","WEIGHING","RELEASE_DECISION","REPORT",id(report),weighingId,id(charge));assertThat(trace.trace(null,lot).toString()).contains(batchId,id(charge));assertThat(graph.toString()).contains(report.path("approvalSignatureId").asText(),"SIGNED_EVIDENCE");var incomingChain=queries.getLotChain(1,Long.parseLong(lot));var inspectionTask=incomingChain.path("requests").get(0).path("inspectionTasks").get(0);assertThat(inspectionTask.path("reviewSignatureId").asText()).isNotBlank();assertThat(graph.toString()).contains(inspectionTask.path("reviewSignatureId").asText());
  String inspectionRequestId=incomingChain.path("requests").get(0).path("id").asText();assertThat(inspectionRequestId).isNotBlank();
  assertThat(graph.path("nodes")).anySatisfy(node->{assertThat(node.path("type").asText()).isEqualTo("QC_SPECIFICATION_VERSION");assertThat(node.path("id").asText()).isEqualTo(version);});
  assertThat(graph.path("edges")).anySatisfy(edge->{assertThat(edge.path("sourceType").asText()).isEqualTo("INSPECTION_REQUEST");assertThat(edge.path("sourceId").asText()).isEqualTo(inspectionRequestId);assertThat(edge.path("targetType").asText()).isEqualTo("QC_SPECIFICATION_VERSION");assertThat(edge.path("targetId").asText()).isEqualTo(version);assertThat(edge.path("relation").asText()).isEqualTo("FROZEN_STANDARD");});
  var pendingIssue=stock.createIssue(body("mainBatchId",batchId,"issueNo","PENDING-"+suffix,"items",List.of(Map.of("formulaItemId",formula,"materialLotId",lot,"issuedQty","1","unitId",unit)),"reason","Create genuine draft before QA supersession"),key());long ledgerBeforeSupersession=jdbc.queryForObject("SELECT COUNT(*) FROM wms_inventory_ledger WHERE material_lot_id=?",Long.class,lot);
  as(qa);var decisionChain=queries.getLotChain(1,Long.parseLong(lot)).path("decisions");String previousDecision=decisionChain.get(decisionChain.size()-1).path("id").asText();var rejectedGate=service.releaseReview(lot);service.decideRelease(lot,body("decision","REJECTED","releaseBasis","FULL_INSPECTION","inspectionReportId",id(report),"supersedesDecisionId",previousDecision,"reason","Real superseding QA rejection after production consumption","reauthToken","token"),token(rejectedGate),key());as(author);blockedCode("MATERIAL_NOT_ELIGIBLE",()->stock.confirmIssue(id(pendingIssue),body("reason","Actual confirm must recheck superseded QA release"),token(pendingIssue),key()));assertThat(jdbc.queryForObject("SELECT status FROM wms_material_issue WHERE id=?",String.class,id(pendingIssue))).isEqualTo("DRAFT");assertThat(jdbc.queryForObject("SELECT issued_at FROM wms_material_issue WHERE id=?",java.sql.Timestamp.class,id(pendingIssue))).isNull();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM wms_inventory_ledger WHERE material_lot_id=?",Long.class,lot)).isEqualTo(ledgerBeforeSupersession);var nextCharge=chargeBody.deepCopy();((com.fasterxml.jackson.databind.node.ObjectNode)nextCharge).put("versionNo",executionService.operations(executionId).getFirst().path("versionNo").asLong());blockedCode("MATERIAL_NOT_ELIGIBLE",()->weighing.createCharge(nextCharge,key()));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_material_charge WHERE execution_unit_id=?",Long.class,executionId)).isEqualTo(1);assertThat(onHand()).isEqualByComparingTo(before.subtract(new BigDecimal("2")));
  var reversed=weighing.reverseCharge(id(charge),body("reason","Controlled reversal"),token(charge),key());assertThat(reversed.path("status").asText()).isEqualTo("REVERSED");assertThat(onHand()).isEqualByComparingTo(before);assertThat(queries.evaluate(1,Long.parseLong(lot),"CHARGE",Instant.now()).path("eligible").asBoolean()).isFalse();assertThat(trace.trace(batchId,null).toString()).contains("REVERSED",id(charge));
  var form=runtime.forms(executionId).get(0);String formId=id(form);runtime.command("SAVE",formId,new com.hospital.mes.ebr.domain.EbrRuntimeCommands.Save(0L,"Actual operator observation",List.of(new com.hospital.mes.ebr.domain.EbrRuntimeCommands.Value("OBS","",json.getNodeFactory().textNode("Completed actual observation"),null,null))),"\"0\"",key());runtime.command("SUBMIT",formId,new com.hospital.mes.ebr.domain.EbrRuntimeCommands.Command(1L,"Submit actual eBR"),"\"1\"",key());var currentOperation=executionService.operations(executionId).getFirst();var completed=executionService.complete(id(currentOperation),body("reason","Complete with actual submitted eBR"),token(currentOperation),key());assertThat(completed.path("status").asText()).isEqualTo("COMPLETED");
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_quantity_event WHERE source_type='MaterialCharge' AND source_ref=?",Long.class,id(charge))).isEqualTo(2);
 }

 long countForExecution(String table,String execution){return jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE execution_unit_id=?",Long.class,execution);}
 JsonNode startActualBatch(JsonNode batch){incomingReportId=id(releaseIncoming(()->{}));as(author);String batchId=id(batch),formula=productionQuery.batch(1,Long.parseLong(batchId)).snapshot().path("process").path("formula").path("items").get(0).path("formulaItemId").asText();stock.reserve(batchId,body("items",List.of(Map.of("formulaItemId",formula,"materialLotId",lot,"reservedQty","3","unitId",unit)),"reason","Real reservation for completion tests"),token(batch),key());var issue=stock.createIssue(body("mainBatchId",batchId,"issueNo","GATE"+suffix,"items",List.of(Map.of("formulaItemId",formula,"materialLotId",lot,"issuedQty","3","unitId",unit)),"reason","Real issued entitlement"),key());stock.confirmIssue(id(issue),body("reason","Actual issue"),token(issue),key());return production.startBatch(batchId,body("reason","Actual start"),token(batch),key());}
 JsonNode recordAndSubmitOperationForm(String execution){var form=runtime.forms(execution).get(0);String fid=id(form);runtime.command("SAVE",fid,new com.hospital.mes.ebr.domain.EbrRuntimeCommands.Save(0L,"Recorded execution",List.of(new com.hospital.mes.ebr.domain.EbrRuntimeCommands.Value("OBS","",json.getNodeFactory().textNode("Observed"),null,null))),"\"0\"",key());return runtime.command("SUBMIT",fid,new com.hospital.mes.ebr.domain.EbrRuntimeCommands.Command(1L,"Completed actual form"),"\"1\"",key());}
 @Test void releaseAuditFailureRollsBackSnapshotsAndRuntimeThenDirectReleaseReplays(){
  var draft=preparedBatch(false);String bid=id(draft),releaseKey=key();long snapshots=jdbc.queryForObject("SELECT COUNT(*) FROM prd_process_snapshot",Long.class);var payload=body("packageVersionId",packageVersionId,"ebrTemplateVersionId",templateVersionId,"reason","Atomic release");
  doAnswer(inv->{var command=(com.hospital.mes.audit.domain.AuditCommand)inv.getArgument(0);if(command.action().equals("MainBatch:RELEASE"))throw new IllegalStateException("injected release audit failure");return inv.callRealMethod();}).when(audit).append(any());
  rejected(IllegalStateException.class,()->production.releaseBatch(bid,payload,token(draft),releaseKey));assertThat(production.batch(bid).path("status").asText()).isEqualTo("DRAFT");assertThat(production.order(orderId).path("status").asText()).isEqualTo("DRAFT");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM prd_process_snapshot",Long.class)).isEqualTo(snapshots);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM prd_execution_unit WHERE main_batch_id=?",Long.class,bid)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ebr_batch_snapshot WHERE main_batch_id=?",Long.class,bid)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,releaseKey)).isZero();reset(audit);
  var released=production.releaseBatch(bid,payload,token(draft),releaseKey);assertThat(production.releaseBatch(bid,payload,token(draft),releaseKey).toString()).isEqualTo(released.toString());assertThat(released.path("executionUnits")).hasSize(1);var execution=released.path("executionUnits").get(0);assertThat(execution.path("unitType").asText()).isEqualTo("DIRECT");assertThat(execution.path("subBatchId").isNull()).isTrue();assertThat(countForExecution("mes_operation_execution",id(execution))).isEqualTo(1);
 }
 @Test void subBatchReleaseCreatesOnlySameParentExecutionsAndOrderCannotOverAllocate() throws Exception {
  withSubBatches=true;var batch=releasedBatch();assertThat(batch.path("executionUnits")).hasSize(2);assertThat(production.subBatches(id(batch))).hasSize(2);for(var execution:batch.path("executionUnits")){assertThat(execution.path("unitType").asText()).isEqualTo("SUB_BATCH");String parent=jdbc.queryForObject("SELECT main_batch_id FROM prd_sub_batch WHERE id=?",String.class,execution.path("subBatchId").asText());assertThat(parent).isEqualTo(id(batch));assertThat(runtime.forms(id(execution))).hasSize(1);}
  String subId=production.subBatches(id(batch)).getFirst().path("id").asText();mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/v1/sub-batches/"+subId+"/release").with(org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user("batch-owner").authorities(new org.springframework.security.core.authority.SimpleGrantedAuthority("production:batch:release")))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isForbidden());
  // Approved TC-BAT-002 contract: no individual SubBatch release/QA action or mapped endpoint.
  for(var sub:production.subBatches(id(batch)))assertThat(sub.path("allowedActions")).isEmpty();
  assertThat(productionMappings.getHandlerMethods().keySet().stream().flatMap(info->info.getPatternValues().stream())
      .filter(path->path.contains("sub-batches")&&(path.contains("release")||path.contains("qa"))).toList()).isEmpty();
  blockedCode("ORDER_ALLOCATION_EXCEEDED",()->production.createBatch(body("batchNo","EXTRA"+suffix,"productionOrderId",orderId,"productId",productId,"plannedQty","1","unitId",unit,"reason","Cannot overallocate"),key()));assertThat(production.batches(0,20,null,Map.of("productionOrderId",orderId)).total()).isEqualTo(1);
 }
 @Test void actualFormCompletionDrivesProductionCompleteButCannotFabricateQa(){
  var batch=startActualBatch(releasedBatch());String bid=id(batch),eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();rejected(com.hospital.mes.common.exception.StateTransitionException.class,()->executionService.complete(id(op),body("reason","Ready cannot complete"),token(op),key()));
  var running=executionService.start(id(op),body("reason","Start operation"),token(op),key());blockedCode("BATCH_EXECUTION_INCOMPLETE",()->production.completeProduction(bid,body("reason","Operation incomplete"),token(batch),key()));blockedCode("EBR_OPERATION_INCOMPLETE",()->executionService.complete(id(running),body("reason","Required form missing"),token(running),key()));recordAndSubmitOperationForm(eid);executionService.complete(id(running),body("reason","Actual execution complete"),token(running),key());blockedCode("QUALITY_PLAN_REQUIRED",()->production.completeProduction(bid,body("reason","Legacy batch has no approved quality plan"),token(batch),key()));assertThat(production.batch(bid).path("status").asText()).isEqualTo("IN_PROGRESS");assertThat(production.order(orderId).path("status").asText()).isNotEqualTo("COMPLETED");
 }
 @Test void productionOrderFilterIsAnExistingPositiveIdQueryContract(){
  var batch=preparedBatch(false);
  assertThat(production.batches(0,20,null,Map.of("productionOrderId",orderId)).items()).extracting(n->n.path("id").asText()).containsExactly(id(batch));
  assertThat(production.batches(0,20,null,Map.of("productionOrderId","9223372036854775806")).items()).isEmpty();
 }
 @Test void trustedDeviceReplayEquipmentSegmentsAndPredecessorStayConsistent(){
  withParameters=true;var batch=startActualBatch(releasedBatch());String eid=batch.path("executionUnits").get(0).path("id").asText();var ops=executionService.operations(eid);var mix=ops.get(0);var finish=ops.get(1);assertThat(finish.path("status").asText()).isEqualTo("PENDING");rejected(com.hospital.mes.common.exception.StateTransitionException.class,()->executionService.start(id(finish),body("reason","Cannot skip predecessor"),token(finish),key()));blockedCode("PRECONDITION_FAILED",()->executionService.start(id(mix),body("reason","Required binding missing"),token(mix),key()));
  var scale=equipment.create(new EquipmentCommands.Create("RUN"+suffix,"Calibrated test equipment","PRODUCTION_IT_SCALE",LocalDate.now(ZoneOffset.UTC).plusDays(30),"Production"),key());executionService.bindEquipment(id(mix),body("equipmentId",id(scale),"usageRole","PROCESS","reason","Real binding"),token(mix),key());var bound=executionService.operation(1,Long.parseLong(id(mix)));var running=executionService.start(id(bound),body("reason","Start bound operation"),token(bound),key());recordAndSubmitOperationForm(eid);
  String parameter=productionQuery.batch(1,Long.parseLong(id(batch))).snapshot().path("process").path("route").path("operations").get(0).path("parameters").get(0).path("parameterDefId").asText();String captured=Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MILLIS).toString();var message=body("parameterDefId",parameter,"sourceMode","DEVICE","rawValue","2.000","unitId",unit,"equipmentId",id(scale),"sourceMessageId","MSG"+suffix,"capturedAt",captured,"reason","Verified inbox message");String match=token(running);rejected(com.hospital.mes.common.exception.PermissionException.class,()->executionService.recordParameter(id(running),message,match,key()));var recorded=executionService.recordDeviceParameter(id(running),message,match,key());assertThat(executionService.recordDeviceParameter(id(running),message,match,key()).path("id")).isEqualTo(recorded.path("id"));var changed=message.deepCopy();((com.fasterxml.jackson.databind.node.ObjectNode)changed).put("rawValue","9.000");rejected(com.hospital.mes.common.exception.ResourceConflictException.class,()->executionService.recordDeviceParameter(id(running),changed,match,key()));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_parameter_value WHERE operation_execution_id=?",Long.class,id(running))).isEqualTo(1);
  var current=executionService.operation(1,Long.parseLong(id(running)));var paused=executionService.pause(id(current),body("reason","Pause actual run"),token(current),key());var resumed=executionService.resume(id(paused),body("reason","Resume actual run"),token(paused),key());var completed=executionService.complete(id(resumed),body("reason","All frozen gates satisfied"),token(resumed),key());assertThat(completed.path("status").asText()).isEqualTo("COMPLETED");var segments=jdbc.queryForList("SELECT r.status,r.ended_at FROM mes_equipment_run r JOIN mes_equipment_usage u ON u.id=r.equipment_usage_id WHERE u.operation_execution_id=?",id(completed));assertThat(segments).hasSize(2);assertThat(segments).allSatisfy(row->{assertThat(row.get("status")).isEqualTo("ENDED");assertThat(row.get("ended_at")).isNotNull();});assertThat(executionService.operation(1,Long.parseLong(id(finish))).path("status").asText()).isEqualTo("READY");var next=executionService.operation(1,Long.parseLong(id(finish)));next=executionService.start(id(next),body("reason","Predecessor completed"),token(next),key());next=executionService.complete(id(next),body("reason","No forms configured in frozen binding"),token(next),key());assertThat(next.path("status").asText()).isEqualTo("COMPLETED");assertThat(production.execution(eid).path("status").asText()).isEqualTo("COMPLETED");
 }

 @Test void fefoSelectsEarlierReleasedLotAndIssueIsNotConsumption(){
  releaseIncoming(()->{});String later=lot;var lotFact=stockQuery.materialLot(1,Long.parseLong(lot));var receipt=stockQuery.receipt(1,jdbc.queryForObject("SELECT i.receipt_id FROM wms_material_receipt_item i JOIN md_material_lot l ON l.receipt_item_id=i.id WHERE l.id=?",Long.class,lot));var sourceItem=receipt.path("items").get(0);as(author);
  var item=new com.hospital.mes.wms.domain.WmsCommands.ReceiptItemInput(material,"EARLY"+suffix,"SUP-EARLY"+suffix,null,LocalDate.now(ZoneOffset.UTC).minusDays(1).toString(),LocalDate.now(ZoneOffset.UTC).plusMonths(2).toString(),null,"10",unit,null,2L,sourceItem.path("locationId").asText(),null,true,true,true,true,true);
  var earlyReceipt=wms.createReceipt(new com.hospital.mes.wms.domain.WmsCommands.ReceiptCreate("EARLY-R"+suffix,receipt.path("supplierId").asText(),null,null,receipt.path("warehouseId").asText(),true,List.of(item)),key(),true);lot=earlyReceipt.path("items").get(0).path("materialLotId").asText();String earlier=lot;releaseIncoming(()->{});as(author);var batch=releasedBatch();String bid=id(batch),formula=productionQuery.batch(1,Long.parseLong(bid)).snapshot().path("process").path("formula").path("items").get(0).path("formulaItemId").asText();
  stock.reserve(bid,body("items",List.of(Map.of("formulaItemId",formula,"reservedQty","3","unitId",unit)),"reason","Actual FEFO"),token(batch),key());assertThat(jdbc.queryForList("SELECT material_lot_id FROM wms_reservation WHERE main_batch_id=?",String.class,bid)).containsExactly(earlier);
  var issue=stock.createIssue(body("mainBatchId",bid,"issueNo","FEFO"+suffix,"items",List.of(Map.of("formulaItemId",formula,"materialLotId",earlier,"issuedQty","3","unitId",unit)),"reason","Actual FEFO issue"),key());String issueKey=key();stock.confirmIssue(id(issue),body("reason","Issue is entitlement"),token(issue),issueKey);stock.confirmIssue(id(issue),body("reason","Issue is entitlement"),token(issue),issueKey);
  assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_material_charge WHERE execution_unit_id IN (SELECT id FROM prd_execution_unit WHERE main_batch_id=?)",Long.class,bid)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_quantity_event WHERE main_batch_id=?",Long.class,bid)).isZero();assertThat(stockQuery.ledger(1,Long.parseLong(earlier))).hasSize(1);assertThat(stockQuery.ledger(1,Long.parseLong(later))).hasSize(1);
 }
 @Test void weighingRejectsWrongFormulaToleranceExpiredScaleAndRevokedRelease(){
  var batch=startActualBatch(releasedBatch());String eid=batch.path("executionUnits").get(0).path("id").asText();var execution=production.execution(eid);String formula=productionQuery.batch(1,Long.parseLong(id(batch))).snapshot().path("process").path("formula").path("items").get(0).path("formulaItemId").asText();var scale=equipment.create(new EquipmentCommands.Create("BADSC"+suffix,"Scale boundary","PRODUCTION_IT_SCALE",LocalDate.now(ZoneOffset.UTC).plusDays(30),"Production"),key());
  var valid=body("executionUnitId",eid,"materialLotId",lot,"formulaItemId",formula,"targetQty","2","actualQty","2","unitId",unit,"scaleEquipmentId",id(scale),"versionNo",execution.path("versionNo").asLong(),"reason","Controlled weighing");var wrong=valid.deepCopy();((com.fasterxml.jackson.databind.node.ObjectNode)wrong).put("formulaItemId","9223372036854775806");blockedCode("MATERIAL_NOT_IN_BOM",()->weighing.createWeighing(wrong,key()));var source=jdbc.queryForMap("SELECT r.supplier_id,r.warehouse_id,i.location_id FROM md_material_lot l JOIN wms_material_receipt_item i ON i.id=l.receipt_item_id JOIN wms_material_receipt r ON r.id=i.receipt_id WHERE l.id=?",lot);var other=materials.create(json.convertValue(Map.of("materialCode","WRONG"+suffix,"materialName","Different test material","materialType","RAW","baseUnitId",unit,"lotControlled",true),com.hospital.mes.masterdata.application.MaterialCommands.Create.class),key());links.assign(id(other),new com.hospital.mes.masterdata.application.SupplierCommands.Assign(0L,"Test-owned supplier relation",List.of(new com.hospital.mes.masterdata.application.SupplierCommands.Relationship(source.get("supplier_id").toString(),true,true,null))),null,key());var otherItem=new com.hospital.mes.wms.domain.WmsCommands.ReceiptItemInput(id(other),"WRONGLOT"+suffix,"WRONGSUP"+suffix,null,LocalDate.now(ZoneOffset.UTC).minusDays(1).toString(),LocalDate.now(ZoneOffset.UTC).plusYears(1).toString(),null,"10",unit,null,2L,source.get("location_id").toString(),null,true,true,true,true,true);var otherReceipt=wms.createReceipt(new com.hospital.mes.wms.domain.WmsCommands.ReceiptCreate("WRONGR"+suffix,source.get("supplier_id").toString(),null,null,source.get("warehouse_id").toString(),true,List.of(otherItem)),key(),true);var wrongLot=valid.deepCopy();((com.fasterxml.jackson.databind.node.ObjectNode)wrongLot).put("materialLotId",otherReceipt.path("items").get(0).path("materialLotId").asText());blockedCode("MATERIAL_NOT_IN_BOM",()->weighing.createWeighing(wrongLot,key()));
  String unqualifiedLogin="noqual_"+suffix;jdbc.update("INSERT INTO sys_user(login_name,login_name_normalized,display_name,password_hash,enabled,must_change_password) VALUES(?,?,?,'test-only',TRUE,FALSE)",unqualifiedLogin,unqualifiedLogin,"No qualification test actor");long unqualified=jdbc.queryForObject("SELECT id FROM sys_user WHERE login_name_normalized=?",Long.class,unqualifiedLogin);as(unqualified);rejected(com.hospital.mes.masterdata.domain.MasterGateException.class,()->weighing.createWeighing(valid,key()));as(author);permissions.remove("mes:weigh:create");as(author);rejected(com.hospital.mes.common.exception.PermissionException.class,()->weighing.createWeighing(valid,key()));permissions.add("mes:weigh:create");as(author);var excess=valid.deepCopy();((com.fasterxml.jackson.databind.node.ObjectNode)excess).put("actualQty","3");blockedCode("WEIGHING_OUT_OF_TOLERANCE",()->weighing.createWeighing(excess,key()));
  scale=equipment.command(id(scale),new EquipmentCommands.Update("UPDATE","Calibration expired",scale.path("versionNo").asLong(),"Scale boundary","PRODUCTION_IT_SCALE",LocalDate.now(ZoneOffset.UTC).minusDays(1),"Production"),token(scale),key());rejected(com.hospital.mes.masterdata.domain.MasterGateException.class,()->weighing.createWeighing(valid,key()));assertThat(countForExecution("mes_weighing_record",eid)).isZero();scale=equipment.command(id(scale),new EquipmentCommands.Update("UPDATE","Recalibrated",scale.path("versionNo").asLong(),"Scale boundary","PRODUCTION_IT_SCALE",LocalDate.now(ZoneOffset.UTC).plusDays(30),"Production"),token(scale),key());
  as(qa);var review=service.releaseReview(lot);service.decideRelease(lot,body("decision","REJECTED","releaseBasis","FULL_INSPECTION","inspectionReportId",incomingReportId,"supersedesDecisionId",queries.getLotChain(1,Long.parseLong(lot)).path("decisions").get(0).path("id").asText(),"reason","Actual quality rejection supersedes release","reauthToken","token"),token(review),key());as(author);blockedCode("MATERIAL_NOT_ELIGIBLE",()->weighing.createWeighing(valid,key()));assertThat(countForExecution("mes_weighing_record",eid)).isZero();
 }
 @Test void genealogyOrAuditFailureRollsBackWholeChargeThenReplayConsumesOnlyOnce(){
  var batch=startActualBatch(releasedBatch());String bid=id(batch),eid=batch.path("executionUnits").get(0).path("id").asText();var op=executionService.operations(eid).getFirst();op=executionService.start(id(op),body("reason","Actual running operation"),token(op),key());var execution=production.execution(eid);String formula=productionQuery.batch(1,Long.parseLong(bid)).snapshot().path("process").path("formula").path("items").get(0).path("formulaItemId").asText();var scale=equipment.create(new EquipmentCommands.Create("ATOMSC"+suffix,"Transaction scale","PRODUCTION_IT_SCALE",LocalDate.now(ZoneOffset.UTC).plusDays(30),"Production"),key());var weighed=weighing.createWeighing(body("executionUnitId",eid,"materialLotId",lot,"formulaItemId",formula,"targetQty","2","actualQty","2","unitId",unit,"scaleEquipmentId",id(scale),"versionNo",execution.path("versionNo").asLong(),"reason","Real weighed material"),key());as(reviewer);weighed=weighing.verifyWeighing(id(weighed),body("reason","Independent verification","reauthToken","token"),token(weighed),key());as(author);
  var command=body("executionUnitId",eid,"operationExecutionId",id(op),"materialLotId",lot,"weighingRecordId",id(weighed),"chargedQty","2","unitId",unit,"versionNo",op.path("versionNo").asLong(),"reason","Atomic actual charge");String chargeKey=key();BigDecimal balance=onHand();long ledger=stockQuery.ledger(1,Long.parseLong(lot)).size();
  doThrow(new IllegalStateException("injected genealogy insert failure")).when(genealogyMapper).insert(any(com.hospital.mes.execution.infrastructure.GenealogyEntity.class));rejected(IllegalStateException.class,()->weighing.createCharge(command,chargeKey));reset(genealogyMapper);assertChargeRolledBack(eid,bid,chargeKey,balance,ledger);
  doAnswer(inv->{var a=(com.hospital.mes.audit.domain.AuditCommand)inv.getArgument(0);if(a.action().equals("MaterialCharge:CREATE"))throw new IllegalStateException("injected charge audit failure");return inv.callRealMethod();}).when(audit).append(any());rejected(IllegalStateException.class,()->weighing.createCharge(command,chargeKey));reset(audit);assertChargeRolledBack(eid,bid,chargeKey,balance,ledger);
  var charged=weighing.createCharge(command,chargeKey);assertThat(weighing.createCharge(command,chargeKey).toString()).isEqualTo(charged.toString());assertThat(countForExecution("mes_material_charge",eid)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_genealogy WHERE main_batch_id=?",Long.class,bid)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_quantity_event WHERE main_batch_id=? AND event_type='CHARGE'",Long.class,bid)).isEqualTo(1);assertThat(onHand()).isEqualByComparingTo(balance.subtract(new BigDecimal("2")));assertThat(trace.trace(bid,null).path("nodes")).anySatisfy(n->{assertThat(n.path("type").asText()).isEqualTo("CHARGE");assertThat(n.path("id").asText()).isEqualTo(id(charged));});when(contexts.current()).thenReturn(new com.hospital.mes.audit.application.CurrentPlatformContext(2,author,Set.of("INCOMING_TEST"),permissions,"incoming-session","other-org"));rejected(NoSuchElementException.class,()->trace.trace(bid,null));as(author);
 }
 void assertChargeRolledBack(String eid,String bid,String k,BigDecimal balance,long ledger){assertThat(countForExecution("mes_material_charge",eid)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_genealogy WHERE main_batch_id=?",Long.class,bid)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM mes_quantity_event WHERE main_batch_id=?",Long.class,bid)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM platform_idempotency_record WHERE idempotency_key=?",Long.class,k)).isZero();assertThat(stockQuery.ledger(1,Long.parseLong(lot))).hasSize((int)ledger);assertThat(onHand()).isEqualByComparingTo(balance);}

 @Test void productionHttpUsesClosedContractsPermissionAndImmutableSnapshot() throws Exception {
  var draft=preparedBatch(false);var auth=org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user("production-http").authorities(new org.springframework.security.core.authority.SimpleGrantedAuthority("production:batch:view"),new org.springframework.security.core.authority.SimpleGrantedAuthority("production:batch:release"),new org.springframework.security.core.authority.SimpleGrantedAuthority("production:batch:update"));String bid=id(draft);
  mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/main-batches/"+bid).with(org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user("wrong"))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isForbidden());
  var payload=body("packageVersionId",packageVersionId,"ebrTemplateVersionId",templateVersionId,"reason","Actual HTTP release");var spoof=payload.deepCopy();((com.fasterxml.jackson.databind.node.ObjectNode)spoof).put("status","QA_RELEASED");mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/v1/main-batches/"+bid+"/release").with(auth).header("Idempotency-Key",key()).header("If-Match",token(draft)).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(json.writeValueAsBytes(spoof))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isBadRequest());
  mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/v1/main-batches/"+bid+"/release").with(auth).header("Idempotency-Key",key()).header("If-Match",token(draft)).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content(json.writeValueAsBytes(payload))).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk()).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath("$.data.status").value("RELEASED")).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath("$.data.executionUnits[0].unitType").value("DIRECT"));
  var readAuth=org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user("production-http").authorities(new org.springframework.security.core.authority.SimpleGrantedAuthority("production:batch:view"),new org.springframework.security.core.authority.SimpleGrantedAuthority("mes:operation:view"),new org.springframework.security.core.authority.SimpleGrantedAuthority("trace:view"));
  String eid=production.batch(bid).path("executionUnits").get(0).path("id").asText();mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/execution-units/"+eid+"/operations").with(readAuth)).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk()).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath("$.data[0].status").value("READY"));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/main-batches").param("page","0").param("size","20").param("keyword","PB"+suffix).with(readAuth)).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk());mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/trace").param("mainBatchId",bid).with(readAuth)).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isOk()).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath("$.data.nodes[0].type").value("MAIN_BATCH"));
  var released=production.batch(bid);String snapshot=productionQuery.batch(1,Long.parseLong(bid)).snapshot().toString();assertThatThrownBy(()->jdbc.update("UPDATE prd_process_snapshot SET snapshot_json='{}' WHERE id=?",jdbc.queryForObject("SELECT process_snapshot_id FROM prd_main_batch WHERE id=?",Long.class,bid))).isInstanceOf(org.springframework.dao.DataAccessException.class);assertThatThrownBy(()->jdbc.update("DELETE FROM prd_process_snapshot WHERE id=?",jdbc.queryForObject("SELECT process_snapshot_id FROM prd_main_batch WHERE id=?",Long.class,bid))).isInstanceOf(org.springframework.dao.DataAccessException.class);assertThat(productionQuery.batch(1,Long.parseLong(bid)).snapshot().toString()).isEqualTo(snapshot);
  when(contexts.current()).thenReturn(new com.hospital.mes.audit.application.CurrentPlatformContext(2,author,Set.of("INCOMING_TEST"),permissions,"incoming-session","other-org"));mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get("/api/v1/main-batches/"+bid).with(auth)).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isNotFound());as(author);
 }
}
