package com.hospital.mes.production;
import com.hospital.mes.release.application.*;import com.hospital.mes.audit.signature.SignatureRepository;import com.fasterxml.jackson.databind.JsonNode;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import static org.assertj.core.api.Assertions.*;
/** Actual owner-module QA/signature workflow; synthetic fixtures roll back. */
class ProductionBookFinalIT extends FinishedReleaseIT {
 @Autowired BookTemplateService books;@Autowired BookService booklet;@Autowired SignatureRepository signatures;
 @BeforeEach void bookPermissions(){permissions.addAll(Set.of("ebr:template:view","ebr:template:create","ebr:template:publish","ebr:pdf:generate","master:product:view","master:uom:view","wms:issue:view"));as(author);}
 @Override JsonNode approvedBatch(){var batch=preparedBatch(false);var definition=body("varietyCode","SBFINAL"+suffix,"varietyName","合成正式归档验收");((com.fasterxml.jackson.databind.node.ObjectNode)definition).set("mappings",json.valueToTree(List.of(Map.of("productId",productId,"packageVersionId",packageVersionId,"ebrTemplateVersionId",templateVersionId))));var entries=((com.fasterxml.jackson.databind.node.ObjectNode)definition).putArray("entries");int i=0;for(String kind:List.of("PRODUCTION_ORDER","CHARGES")){var e=entries.addObject().put("code",kind).put("chapter","原始业务证据").put("title",kind).put("kind",kind).put("order",++i).put("required",true).put("minCount",1).put("scope","BATCH");e.putArray("fields");e.putArray("attachmentIds");}var t=books.create("SBFINAL"+suffix,definition,"合成正式归档模板");as(approver);books.transition(id(t),"PUBLISH",0,"独立发布");as(author);var p=plans.create(planBody(batch),key());as(qa);plans.approve(id(p),body("versionNo",0,"reason","Independent plan approval","signature",Map.of("reauthToken","token")),token(p),key());as(author);return startActualBatch(production.releaseBatch(id(batch),body("packageVersionId",packageVersionId,"ebrTemplateVersionId",templateVersionId,"reason","Approved production with book"),token(batch),key()));}
 @Test void actualQaFinalBookPreservesOriginalAndRechecksInvalidatedSignature()throws Exception{var pending=completedQaBatch();String bid=id(pending);blockedCode("FINAL_ARCHIVE_DECISION_REQUIRED",()->booklet.generate(bid,"FINAL",pending.path("versionNo").asLong(),"Before QA"));as(qa);var decision=finishedQa.decide(releaseCommand(pending,"RELEASED",null),token(pending),key());var released=production.batch(bid);var finalBook=booklet.generate(bid,"FINAL",released.path("versionNo").asLong(),"Real QA final book");byte[] original=booklet.pdf(bid,id(finalBook));assertThat(finalBook.path("archive_kind").asText()).isEqualTo("FINAL");assertThat(finalBook.path("legacy_manifest_id").asText()).isNotBlank();try(var pdf=org.apache.pdfbox.Loader.loadPDF(original)){assertThat(new org.apache.pdfbox.text.PDFTextStripper().getText(pdf)).contains("正式归档","受控原始证据附录");}assertThat(booklet.generate(bid,"FINAL",released.path("versionNo").asLong(),"Verified reuse").path("id")).isEqualTo(finalBook.path("id"));var signature=signatures.find(1,decision.path("signatureId").asLong());assertThat(signatures.invalidate(1,signature.id(),signature.versionNo(),qa,java.time.Instant.now(),"Synthetic controlled QA invalidation")).isTrue();blockedCode("FINAL_ARCHIVE_DECISION_REQUIRED",()->booklet.generate(bid,"FINAL",released.path("versionNo").asLong(),"Must recheck current QA"));assertThat(booklet.pdf(bid,id(finalBook))).isEqualTo(original);String dir=System.getProperty("mes.book.evidence");if(dir!=null)java.nio.file.Files.write(java.nio.file.Path.of(dir,"rollback-real-final-book.pdf"),original);}
}
