package com.hospital.mes.production;
import com.fasterxml.jackson.databind.JsonNode;
import com.hospital.mes.qms.application.ProductionQualityService;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import static org.assertj.core.api.Assertions.*;
class ProductionQualityIT extends ProductionQuantityIT {
 @Autowired ProductionQualityService quality;
 @BeforeEach void productionQualityPermissions(){permissions.addAll(Set.of("qms:sample:view","qms:sample:create","qms:sample:receive","qms:test:record","qms:test:view","qms:test:review","qms:test:retest","qms:deviation:view","qms:deviation:create","qms:deviation:update","qms:deviation:investigate","qms:deviation:decide","qms:deviation:close","qms:capa:create","qms:capa:view","qms:capa:update","qms:capa:verify"));as(author);}
 JsonNode testInstance(JsonNode batch){var s=quality.createSample(body("investigationScope","PRODUCTION","mainBatchId",id(batch),"sampleNo","PS"+suffix,"sampleType","TEST_SAMPLE","quantity","1","unitId",unit,"sourceRef","SRC"+suffix,"reason","Actual collected sample"),key());s=quality.receiveSample(id(s),body("versionNo",0,"reason","Actual sample received"),token(s),key());var item=productionQuery.batch(1,Long.parseLong(id(batch))).snapshot().path("qualityPlan").path("specification").path("items").get(0).path("specificationItemId").asText();return quality.createTest(body("sampleId",id(s),"specificationItemId",item,"reason","Frozen standard testing"),key());}
 JsonNode record(JsonNode t,String value){return quality.result(id(t),false,body("versionNo",t.path("versionNo").asLong(),"resultNumeric",value,"reason","Original measured result","signature",Map.of("reauthToken","token")),token(t),key());}
 JsonNode review(JsonNode t,String disposition){return quality.review(id(t),body("versionNo",t.path("versionNo").asLong(),"resultRevisionId",t.path("currentResultRevisionId").asText(),"disposition",disposition,"reason","Independent original review","signature",Map.of("reauthToken","token")),token(t),key());}
 @Test void actualSignedPassRequiresIndependentReviewAndOriginalFailCannotBeCorrectedToPass(){var batch=approvedBatch();var t=testInstance(batch);assertThat(quality.blockingCodes(1,Long.parseLong(id(batch)),true)).contains("PRODUCTION_QC_REQUIRED_RESULT");t=record(t,"2");var recorded=t;blockedCode("INDEPENDENT_REVIEW_REQUIRED",()->review(recorded,"CONFIRMED"));as(reviewer);t=review(t,"CONFIRMED");assertThat(quality.blockingCodes(1,Long.parseLong(id(batch)),true)).doesNotContain("PRODUCTION_QC_REQUIRED_RESULT");assertThat(verifier.verify(1,t.path("results").get(0).path("signatureId").asLong())).isTrue();}
 @Test void failOpensOosRetestConsumesExactQuotaAndPreservesImmutableOriginal(){var batch=approvedBatch();var t=record(testInstance(batch),"5");var failed=t;blockedCode("RESULT_CORRECTION_FORBIDDEN",()->quality.result(id(failed),true,body("versionNo",failed.path("versionNo").asLong(),"previousRevisionId",failed.path("currentResultRevisionId").asText(),"resultNumeric","2","reason","Forbidden fail overwrite","signature",Map.of("reauthToken","token")),token(failed),key()));assertThat(quality.blockingCodes(1,Long.parseLong(id(batch)),true)).contains("PRODUCTION_OOS_UNRESOLVED");as(reviewer);t=review(t,"INVALIDATED");as(author);var d=quality.list(ProductionQualityService.DEV,0,20,Map.of("mainBatchId",id(batch))).items().getFirst();d=quality.deviationAction(id(d),"investigate",body("versionNo",0,"investigationScope","PRODUCTION","investigationSummary","Instrument error investigated","reason","Document investigation"),token(d),key());as(qa);d=quality.deviationAction(id(d),"decide",body("versionNo",d.path("versionNo").asLong(),"investigationScope","PRODUCTION","decisionCode","AUTHORIZE_RETEST","disposition","One controlled retest","authorizedRetestCount",1,"originalResultDisposition","INVALID","reason","Independent authorization","signature",Map.of("reauthToken","token")),token(d),key());as(author);var original=t;var retest=quality.retest(id(t),body("versionNo",t.path("versionNo").asLong(),"investigationId",id(d),"reason","Consume approved retest"),token(t),key());var updated=quality.get(ProductionQualityService.TEST,id(t));var investigation=d;blockedCode("RETEST_QUOTA_EXHAUSTED",()->quality.retest(id(original),body("versionNo",updated.path("versionNo").asLong(),"investigationId",id(investigation),"reason","No second retest"),token(updated),key()));retest=record(retest,"2");as(reviewer);retest=review(retest,"CONFIRMED");d=quality.deviationAction(id(d),"close",body("versionNo",d.path("versionNo").asLong(),"investigationScope","PRODUCTION","selectedResultRevisionId",retest.path("currentResultRevisionId").asText(),"reason","Independent closure","signature",Map.of("reauthToken","token")),token(d),key());assertThat(quality.blockingCodes(1,Long.parseLong(id(batch)),true)).isEmpty();assertThat(jdbc.queryForObject("SELECT result_conclusion FROM qms_test_result_revision WHERE id=?",String.class,original.path("currentResultRevisionId").asText())).isEqualTo("FAIL");assertThat(quality.evidence(1,Long.parseLong(id(batch))).path("tests")).hasSize(2);}
 @Test void criticalDeviationAndCapaNeedSignedIndependentVerificationAndReopenHistory(){var batch=approvedBatch();var d=quality.createDeviation(body("investigationScope","PRODUCTION","mainBatchId",id(batch),"investigationKind","DEVIATION","severity","CRITICAL","description","Actual critical finding","reason","Document finding"),key());var c=quality.createCapa(id(d),body("capaNo","PC"+suffix,"actionText","Repair and verify","reason","Controlled action"),key());c=quality.capaAction(id(c),"start",body("versionNo",0,"reason","Start action"),token(c),key());c=quality.capaAction(id(c),"complete",body("versionNo",c.path("versionNo").asLong(),"completionText","Repair completed","reason","Completed action"),token(c),key());var complete=c;blockedCode("INDEPENDENT_REVIEW_REQUIRED",()->quality.capaAction(id(complete),"verify",body("versionNo",complete.path("versionNo").asLong(),"decision","VERIFIED","reason","Cannot self verify","signature",Map.of("reauthToken","token")),token(complete),key()));as(qa);c=quality.capaAction(id(c),"verify",body("versionNo",c.path("versionNo").asLong(),"decision","VERIFIED","reason","Independent action verification","signature",Map.of("reauthToken","token")),token(c),key());c=quality.capaAction(id(c),"verify",body("versionNo",c.path("versionNo").asLong(),"decision","REOPEN","reason","Further action necessary","signature",Map.of("reauthToken","token")),token(c),key());assertThat(c.path("reviews")).hasSize(2);for(var rv:c.path("reviews"))assertThat(verifier.verify(1,rv.path("signatureId").asLong())).isTrue();assertThat(c.path("status").asText()).isEqualTo("IN_PROGRESS");assertThat(quality.blockingCodes(1,Long.parseLong(id(batch)),false)).contains("PRODUCTION_CRITICAL_UNRESOLVED");}
 @Test void permissionReplayOrgVersionAndAuditFailureAreZeroWriteGuards(){var batch=approvedBatch();var t=testInstance(batch);var b=body("versionNo",0,"resultNumeric","2","reason","Guarded original result","signature",Map.of("reauthToken","token"));String resultKey=key();var result=quality.result(id(t),false,b,token(t),resultKey);assertThat(quality.result(id(t),false,b,token(t),resultKey)).isEqualTo(result);permissions.remove("qms:test:record");as(author);rejected(com.hospital.mes.common.exception.PermissionException.class,()->quality.result(id(t),false,b,token(t),resultKey));permissions.add("qms:test:record");as(author);rejected(com.hospital.mes.common.exception.ResourceConflictException.class,()->quality.review(id(t),body("versionNo",0,"resultRevisionId",result.path("currentResultRevisionId").asText(),"disposition","CONFIRMED","reason","Stale review","signature",Map.of("reauthToken","token")),token(t),key()));org.mockito.Mockito.when(contexts.current()).thenReturn(new com.hospital.mes.audit.application.CurrentPlatformContext(2,author,Set.of("TEST"),permissions,"other-session","other-request"));rejected(NoSuchElementException.class,()->quality.get(ProductionQualityService.TEST,id(t)));as(author);long count=jdbc.queryForObject("SELECT COUNT(*) FROM qms_deviation WHERE main_batch_id=?",Long.class,id(batch));org.mockito.Mockito.doThrow(new IllegalStateException("audit unavailable")).when(audit).append(org.mockito.ArgumentMatchers.argThat(x->x.action().equals("PRODUCTION_DEVIATION_CREATE")));rejected(IllegalStateException.class,()->quality.createDeviation(body("investigationScope","PRODUCTION","mainBatchId",id(batch),"investigationKind","DEVIATION","severity","MINOR","description","Audit rollback trial","reason","Mandatory audit"),key()));org.mockito.Mockito.doCallRealMethod().when(audit).append(org.mockito.ArgumentMatchers.any());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM qms_deviation WHERE main_batch_id=?",Long.class,id(batch))).isEqualTo(count);} JsonNode authorize(JsonNode test,int quota){as(reviewer);test=review(test,"INVALIDATED");String testId=id(test);as(author);var d=quality.list(ProductionQualityService.DEV,0,100,Map.of()).items().stream().filter(x->x.path("productionTestInstanceId").asText().equals(testId)).findFirst().orElseThrow();d=quality.deviationAction(id(d),"investigate",body("versionNo",d.path("versionNo").asLong(),"investigationScope","PRODUCTION","investigationSummary","Controlled failed attempt investigation","reason","Investigate original"),token(d),key());as(qa);return quality.deviationAction(id(d),"decide",body("versionNo",d.path("versionNo").asLong(),"investigationScope","PRODUCTION","decisionCode","AUTHORIZE_RETEST","disposition","Bounded authorized retest","authorizedRetestCount",quota,"originalResultDisposition","INVALID","reason","Independent authorization","signature",Map.of("reauthToken","token")),token(d),key());}
 JsonNode attempt(JsonNode test,JsonNode d){as(author);test=quality.get(ProductionQualityService.TEST,id(test));return quality.retest(id(test),body("versionNo",test.path("versionNo").asLong(),"investigationId",id(d),"reason","Approved actual attempt"),token(test),key());}
 @Test void laterFailedRetestAllocatesNextAttemptAndNarrativeDeviationCannotBorrowSource(){var batch=approvedBatch();var original=record(testInstance(batch),"5");var d1=authorize(original,1);var second=record(attempt(original,d1),"5");var d2=authorize(second,1);var third=attempt(second,d2);assertThat(third.path("attemptNo").asInt()).isEqualTo(3);as(author);blockedCode("RESULT_LINEAGE_MISMATCH",()->quality.createDeviation(body("investigationScope","PRODUCTION","mainBatchId",id(batch),"investigationKind","DEVIATION","severity","MINOR","description","Mismatched source is forbidden","productionTestInstanceId",id(original),"originalResultRevisionId",second.path("currentResultRevisionId").asText(),"reason","Source guard"),key()));suffix=suffix+"B";var other=preparedBatch(false);blockedCode("RESULT_LINEAGE_MISMATCH",()->quality.createDeviation(body("investigationScope","PRODUCTION","mainBatchId",id(other),"investigationKind","DEVIATION","severity","MINOR","description","Another batch source is forbidden","productionTestInstanceId",id(original),"originalResultRevisionId",original.path("currentResultRevisionId").asText(),"reason","Batch guard"),key()));assertThat(quality.list(ProductionQualityService.DEV,0,20,Map.of("mainBatchId",id(other))).items()).isEmpty();}
 @Test void fullRetestQuotaCannotCloseUntilEveryConsumedAttemptHasSignedIndependentReview(){var batch=approvedBatch();var original=record(testInstance(batch),"5");var d=authorize(original,2);var first=record(attempt(original,d),"2");var second=record(attempt(original,d),"2");as(reviewer);second=review(second,"CONFIRMED");var close=body("versionNo",d.path("versionNo").asLong(),"investigationScope","PRODUCTION","selectedResultRevisionId",second.path("currentResultRevisionId").asText(),"reason","All consumed attempts need review","signature",Map.of("reauthToken","token"));blockedCode("RETEST_UNRESOLVED",()->quality.deviationAction(id(d),"close",close,token(d),key()));assertThat(quality.blockingCodes(1,Long.parseLong(id(batch)),true)).contains("PRODUCTION_OOS_UNRESOLVED");first=review(first,"CONFIRMED");quality.deviationAction(id(d),"close",close,token(d),key());assertThat(quality.blockingCodes(1,Long.parseLong(id(batch)),true)).isEmpty();} @Test void legalSignedCorrectionsPreserveAllRevisionsAndCorrectedFailOpensActualOos(){
  var batch=approvedBatch();var t=record(testInstance(batch),"2");String original=t.path("currentResultRevisionId").asText();
  t=quality.result(id(t),true,body("versionNo",t.path("versionNo").asLong(),"previousRevisionId",original,"resultNumeric","2.5","reason","Correct transcription with original preserved","signature",Map.of("reauthToken","token")),token(t),key());
  String second=t.path("currentResultRevisionId").asText();assertThat(second).isNotEqualTo(original);assertThat(t.path("results")).hasSize(2);assertThat(t.path("results").get(1).path("revisionNo").asInt()).isEqualTo(2);assertThat(t.path("results").get(1).path("previousRevisionId").asText()).isEqualTo(original);
  for(var r:t.path("results"))assertThat(verifier.verify(1,r.path("signatureId").asLong())).isTrue();
  t=quality.result(id(t),true,body("versionNo",t.path("versionNo").asLong(),"previousRevisionId",second,"resultNumeric","5","reason","Controlled corrected result exceeds frozen criterion","signature",Map.of("reauthToken","token")),token(t),key());
  String third=t.path("currentResultRevisionId").asText();assertThat(t.path("results")).hasSize(3);assertThat(t.path("results").get(2).path("revisionNo").asInt()).isEqualTo(3);assertThat(t.path("results").get(2).path("previousRevisionId").asText()).isEqualTo(second);assertThat(t.path("results").get(2).path("resultConclusion").asText()).isEqualTo("FAIL");
  assertThat(jdbc.queryForObject("SELECT result_numeric FROM qms_test_result_revision WHERE id=?",java.math.BigDecimal.class,original)).isEqualByComparingTo("2");assertThat(jdbc.queryForObject("SELECT result_numeric FROM qms_test_result_revision WHERE id=?",java.math.BigDecimal.class,second)).isEqualByComparingTo("2.5");
  for(var r:t.path("results"))assertThat(verifier.verify(1,r.path("signatureId").asLong())).isTrue();
  var d=quality.list(ProductionQualityService.DEV,0,20,Map.of("mainBatchId",id(batch))).items();assertThat(d).hasSize(1);assertThat(d.getFirst().path("investigationKind").asText()).isEqualTo("OOS");assertThat(d.getFirst().path("originalResultRevisionId").asText()).isEqualTo(third);assertThat(d.getFirst().path("productionTestInstanceId").asText()).isEqualTo(id(t));assertThat(quality.blockingCodes(1,Long.parseLong(id(batch)),true)).contains("PRODUCTION_OOS_UNRESOLVED");
  var failed=t;blockedCode("RESULT_CORRECTION_FORBIDDEN",()->quality.result(id(failed),true,body("versionNo",failed.path("versionNo").asLong(),"previousRevisionId",third,"resultNumeric","2","reason","Original FAIL remains protected","signature",Map.of("reauthToken","token")),token(failed),key()));assertThat(quality.get(ProductionQualityService.TEST,id(t)).path("results")).hasSize(3);
 }}



