package com.hospital.mes.execution.api;
import com.fasterxml.jackson.databind.JsonNode;
import com.hospital.mes.common.api.ApiResponse;
import com.hospital.mes.common.trace.TraceIdProvider;
import com.hospital.mes.execution.application.*;
import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class ExecutionController {
 @org.springframework.beans.factory.annotation.Autowired private ClearanceService clearance;
 @PostMapping("/operations/{id}/record-clearance") public ApiResponse<?> recordClearance(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader("If-Match") String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(clearance.record(id,body,version,key)),traces.currentTraceId());}
 @PostMapping("/operations/{id}/review-clearance") public ApiResponse<?> reviewClearance(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader("If-Match") String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(clearance.review(id,body,version,key)),traces.currentTraceId());}
 private final com.hospital.mes.production.application.ProductionViews views;private final ExecutionService operations;private final WeighChargeService materials;private final TraceIdProvider traces;
 public ExecutionController(com.hospital.mes.production.application.ProductionViews views,ExecutionService operations,WeighChargeService materials,TraceIdProvider traces){this.views=views;this.operations=operations;this.materials=materials;this.traces=traces;}
 @GetMapping("/execution-units/{id}/operations") public ApiResponse<?> operations(@PathVariable("id") String id){return ApiResponse.success(views.read(operations.operations(id)),traces.currentTraceId());}
 @GetMapping("/execution-units/{id}/weighings") public ApiResponse<?> weighings(@PathVariable("id") String id){return ApiResponse.success(views.read(materials.weighings(id)),traces.currentTraceId());}
 @GetMapping("/execution-units/{id}/material-charges") public ApiResponse<?> charges(@PathVariable("id") String id){return ApiResponse.success(views.read(materials.charges(id)),traces.currentTraceId());}
 @PostMapping("/operations/{id}/start") public ApiResponse<?> start(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader(value="If-Match",required=false) String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(operations.start(id,body,version,key)),traces.currentTraceId());}
 @PostMapping("/operations/{id}/pause") public ApiResponse<?> pause(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader(value="If-Match",required=false) String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(operations.pause(id,body,version,key)),traces.currentTraceId());}
 @PostMapping("/operations/{id}/resume") public ApiResponse<?> resume(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader(value="If-Match",required=false) String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(operations.resume(id,body,version,key)),traces.currentTraceId());}
 @PostMapping("/operations/{id}/complete") public ApiResponse<?> complete(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader(value="If-Match",required=false) String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(operations.complete(id,body,version,key)),traces.currentTraceId());}
 @PostMapping("/operations/{id}/equipment-usages") public ApiResponse<?> bindEquipment(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader(value="If-Match",required=false) String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(operations.bindEquipment(id,body,version,key)),traces.currentTraceId());}
 @PostMapping("/operations/{id}/parameter-values") public ApiResponse<?> recordParameter(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader(value="If-Match",required=false) String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(operations.recordParameter(id,body,version,key)),traces.currentTraceId());}
 @ResponseStatus(org.springframework.http.HttpStatus.CREATED) @PostMapping("/weighings") public ApiResponse<?> createWeighing(@RequestBody JsonNode body,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(materials.createWeighing(body,key)),traces.currentTraceId());}
 @ResponseStatus(org.springframework.http.HttpStatus.CREATED) @PostMapping("/material-charges") public ApiResponse<?> createCharge(@RequestBody JsonNode body,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(materials.createCharge(body,key)),traces.currentTraceId());}
 @PostMapping("/weighings/{id}/verify") public ApiResponse<?> verifyWeighing(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader(value="If-Match",required=false) String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(materials.verifyWeighing(id,body,version,key)),traces.currentTraceId());}
 @PostMapping("/material-charges/{id}/reverse") public ApiResponse<?> reverseCharge(@PathVariable("id") String id,@RequestBody JsonNode body,@RequestHeader(value="If-Match",required=false) String version,@RequestHeader("Idempotency-Key") String key){return ApiResponse.success(views.read(materials.reverseCharge(id,body,version,key)),traces.currentTraceId());}
}
