CREATE TABLE gxp_audit_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    org_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    actor_id BIGINT NOT NULL,
    actor_role VARCHAR(100) NULL,
    action VARCHAR(80) NOT NULL,
    object_type VARCHAR(80) NOT NULL,
    object_id VARCHAR(100) NOT NULL,
    old_value_digest TEXT NULL,
    new_value_digest TEXT NULL,
    reason VARCHAR(1000) NULL,
    client_info VARCHAR(500) NULL,
    occurred_at DATETIME(3) NOT NULL,
    transaction_id VARCHAR(100) NOT NULL,
    request_id VARCHAR(100) NULL,
    source VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(128) NULL,
    PRIMARY KEY (id),
    KEY ix_gxp_audit_org_time (org_id, occurred_at, id),
    KEY ix_gxp_audit_actor_time (actor_id, occurred_at, id),
    KEY ix_gxp_audit_object_time (object_type, object_id, occurred_at, id),
    KEY ix_gxp_audit_action_time (action, occurred_at, id),
    KEY ix_gxp_audit_transaction (transaction_id),
    KEY ix_gxp_audit_request (request_id),
    CONSTRAINT fk_gxp_audit_actor FOREIGN KEY (actor_id) REFERENCES sys_user (id),
    CONSTRAINT ck_gxp_audit_source CHECK (source IN ('API', 'SCHEDULER', 'INTEGRATION', 'SYSTEM')),
    CONSTRAINT ck_gxp_audit_old_digest CHECK (old_value_digest IS NULL OR old_value_digest REGEXP '^[0-9a-f]{64}$'),
    CONSTRAINT ck_gxp_audit_new_digest CHECK (new_value_digest IS NULL OR new_value_digest REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE gxp_signature (
    id BIGINT NOT NULL AUTO_INCREMENT,
    org_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    version_no BIGINT NOT NULL DEFAULT 0,
    signer_id BIGINT NOT NULL,
    meaning VARCHAR(100) NOT NULL,
    object_type VARCHAR(80) NOT NULL,
    object_id VARCHAR(100) NOT NULL,
    record_digest CHAR(64) NOT NULL,
    signed_at DATETIME(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    invalidated_at DATETIME(3) NULL,
    invalidation_reason VARCHAR(1000) NULL,
    auth_context_json LONGTEXT NULL,
    revoked_signature_id BIGINT NULL,
    PRIMARY KEY (id),
    KEY ix_gxp_signature_object (org_id, object_type, object_id, status, id),
    KEY ix_gxp_signature_signer_time (signer_id, signed_at, id),
    CONSTRAINT fk_gxp_signature_signer FOREIGN KEY (signer_id) REFERENCES sys_user (id),
    CONSTRAINT fk_gxp_signature_revoked FOREIGN KEY (revoked_signature_id) REFERENCES gxp_signature (id),
    CONSTRAINT ck_gxp_signature_status CHECK (status IN ('VALID', 'INVALIDATED')),
    CONSTRAINT ck_gxp_signature_digest CHECK (record_digest REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE integration_inbox (
    id BIGINT NOT NULL AUTO_INCREMENT,
    org_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    version_no BIGINT NOT NULL DEFAULT 0,
    source_system VARCHAR(80) NOT NULL,
    message_id VARCHAR(128) NOT NULL,
    payload_json LONGTEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    processed_at DATETIME(3) NULL,
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME(3) NULL,
    last_error_code VARCHAR(100) NULL,
    last_error_message VARCHAR(1000) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_integration_inbox_identity (org_id, source_system, message_id),
    KEY ix_inbox_claim (org_id, status, next_retry_at, id),
    KEY ix_inbox_received (org_id, received_at, id),
    CONSTRAINT ck_inbox_status CHECK (status IN ('RECEIVED', 'PROCESSING', 'RETRY_WAIT', 'PROCESSED', 'DEAD_LETTER')),
    CONSTRAINT ck_inbox_retry_count CHECK (retry_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE integration_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT,
    org_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    version_no BIGINT NOT NULL DEFAULT 0,
    message_id VARCHAR(128) NOT NULL,
    target_system VARCHAR(80) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    payload_json LONGTEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME(3) NULL,
    published_at DATETIME(3) NULL,
    last_error_code VARCHAR(100) NULL,
    last_error_message VARCHAR(1000) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_integration_outbox_message (org_id, message_id),
    KEY ix_outbox_claim (org_id, status, next_retry_at, id),
    KEY ix_outbox_aggregate (org_id, aggregate_type, aggregate_id, id),
    KEY ix_outbox_target_created (org_id, target_system, created_at, id),
    CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING', 'DISPATCHING', 'RETRY_WAIT', 'PUBLISHED', 'DEAD_LETTER')),
    CONSTRAINT ck_outbox_retry_count CHECK (retry_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE platform_idempotency_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    org_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    version_no BIGINT NOT NULL DEFAULT 0,
    actor_id BIGINT NOT NULL,
    operation_code VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_digest CHAR(64) NOT NULL,
    state VARCHAR(20) NOT NULL,
    http_status SMALLINT NULL,
    response_json LONGTEXT NULL,
    resource_type VARCHAR(80) NULL,
    resource_id VARCHAR(100) NULL,
    expires_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_platform_idempotency_key (org_id, actor_id, operation_code, idempotency_key),
    CONSTRAINT fk_platform_idempotency_actor FOREIGN KEY (actor_id) REFERENCES sys_user (id),
    CONSTRAINT ck_platform_idempotency_state CHECK (state IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_platform_idempotency_digest CHECK (request_digest REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TRIGGER trg_gxp_audit_event_no_update
BEFORE UPDATE ON gxp_audit_event
FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'gxp_audit_event is append-only';

CREATE TRIGGER trg_gxp_audit_event_no_delete
BEFORE DELETE ON gxp_audit_event
FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'gxp_audit_event is append-only';
