package com.hospital.mes.release.api;
import com.hospital.mes.release.application.*;import com.hospital.mes.common.api.ApiResponse;import com.hospital.mes.common.trace.TraceIdProvider;import com.fasterxml.jackson.databind.JsonNode;import org.springframework.web.bind.annotation.*;import org.springframework.http.*;import java.util.*;
@RestController @RequestMapping("/api/v1") @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class BookController {
 private final BookCommandService commands;private final BookService books;private final BookTemplateService templates;private final TraceIdProvider traces;
 public BookController(BookCommandService commands,BookService books,BookTemplateService templates,TraceIdProvider traces){this.commands=commands;this.books=books;this.templates=templates;this.traces=traces;}
 @GetMapping("/ebr/book-templates")public ApiResponse<JsonNode> list(){return ok(templates.list());}
 @GetMapping("/ebr/book-templates/{id}")public ApiResponse<JsonNode> template(@PathVariable("id")String id){return ok(templates.get(id));}
 @PostMapping("/ebr/book-templates")public ApiResponse<JsonNode> create(@RequestBody JsonNode body,@RequestHeader("Idempotency-Key")String key){exact(body,Set.of("templateCode","definition","reason"));return ok(commands.execute("ebr:template:create","EBR_BOOK_TEMPLATE_CREATE",key,body,()->templates.create(body.path("templateCode").asText(),body.path("definition"),body.path("reason").asText())));}
 @PostMapping("/ebr/book-templates/{id}/{action}")public ApiResponse<JsonNode> transition(@PathVariable("id")String id,@PathVariable("action")String action,@RequestBody JsonNode body,@RequestHeader("If-Match")String match,@RequestHeader("Idempotency-Key")String key){exact(body,Set.of("versionNo","reason"));return ok(commands.execute("ebr:template:publish","EBR_BOOK_TEMPLATE_"+action.toUpperCase(Locale.ROOT)+":"+id,key,Map.of("body",body,"match",match),()->templates.transition(id,action.toUpperCase(Locale.ROOT),com.hospital.mes.masterdata.application.MasterMutation.version(match,body.path("versionNo").asLong()),body.path("reason").asText())));}
 @GetMapping("/main-batches/{id}/book")public ApiResponse<JsonNode> read(@PathVariable("id")String id){return ok(books.read(id));}
 @GetMapping("/main-batches/{id}/book/pdfs")public ApiResponse<JsonNode> history(@PathVariable("id")String id){return ok(books.history(id));}
 @PostMapping("/main-batches/{id}/book/pdfs")public ApiResponse<JsonNode> generate(@PathVariable("id")String id,@RequestBody JsonNode body,@RequestHeader("If-Match")String match,@RequestHeader("Idempotency-Key")String key){exact(body,Set.of("versionNo","archiveKind","reason"));return ok(commands.execute("ebr:pdf:generate","EBR_BOOK_PDF_GENERATE:"+id,key,Map.of("body",body,"match",match),()->books.generate(id,body.path("archiveKind").asText(),com.hospital.mes.masterdata.application.MasterMutation.version(match,body.path("versionNo").asLong()),body.path("reason").asText())));}
 @GetMapping("/main-batches/{id}/book/pdfs/{pdfId}/content")public ResponseEntity<byte[]> pdf(@PathVariable("id")String id,@PathVariable("pdfId")String pdf){return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CACHE_CONTROL,"no-store").header(HttpHeaders.CONTENT_DISPOSITION,"inline; filename=production-batch-book.pdf").body(books.pdf(id,pdf));}
 private ApiResponse<JsonNode> ok(JsonNode data){return ApiResponse.success(data,traces.currentTraceId());}
 private void exact(JsonNode n,Set<String> keys){if(!n.isObject()||n.size()!=keys.size())throw new IllegalArgumentException("Exact book command required");n.fieldNames().forEachRemaining(k->{if(!keys.contains(k))throw new IllegalArgumentException("Unknown book command field");if(k.equals("versionNo")){if(!n.get(k).isIntegralNumber()||!n.get(k).canConvertToLong()||n.get(k).asLong()<0)throw new IllegalArgumentException("Integral versionNo required");}else if(!k.equals("definition")&&!n.get(k).isTextual())throw new IllegalArgumentException("Text command field required");});}
}
