package com.hospital.mes.traceability.application;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import com.hospital.mes.masterdata.application.MasterMutation;
import com.hospital.mes.production.application.ProductionQueryService;
import com.hospital.mes.execution.application.ExecutionQueryService;
import com.hospital.mes.common.exception.ComplianceException;
import org.springframework.beans.factory.ObjectProvider;
import java.util.*;
@org.springframework.stereotype.Service
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(prefix="spring.datasource",name="url")
public class TraceService {
 private final ObjectProvider<WmsTracePort> wms;private final MasterMutation mutations;private final ProductionQueryService production;private final ExecutionQueryService execution;private final ObjectProvider<IncomingTracePort> incoming;private final ObjectMapper json;private final ObjectProvider<FinishedTracePort> finished;
 public TraceService(MasterMutation mutations,ProductionQueryService production,ExecutionQueryService execution,ObjectProvider<IncomingTracePort> incoming,ObjectMapper json,ObjectProvider<FinishedTracePort> finished,ObjectProvider<WmsTracePort> wms){this.wms=wms;this.mutations=mutations;this.production=production;this.execution=execution;this.incoming=incoming;this.json=json;this.finished=finished;}
 @org.springframework.transaction.annotation.Transactional(readOnly=true) public JsonNode trace(String mainBatchId,String materialLotId){var c=mutations.context("trace:view");if((mainBatchId==null)==(materialLotId==null))throw new IllegalArgumentException("Exactly one mainBatchId/materialLotId is required");var nodes=new LinkedHashMap<String,JsonNode>();var edges=new LinkedHashMap<String,JsonNode>();var lots=new TreeSet<Long>();var batches=new TreeSet<Long>();var expanded=new HashSet<Long>();List<JsonNode> charges;var fp=finished.getIfAvailable();
  if(mainBatchId!=null){long batch=MasterMutation.id(mainBatchId);var context=production.batch(c.organizationId(),batch);node(nodes,"MAIN_BATCH",mainBatchId,"Main batch "+mainBatchId,context.status());charges=execution.chargesForBatch(c.organizationId(),batch);if(fp!=null){Long fl=fp.lotForBatch(c.organizationId(),batch);if(fl!=null)finishedGraph(fp.forLot(c.organizationId(),fl),nodes,edges);expanded.add(batch);}}else{long lot=MasterMutation.id(materialLotId);var fg=fp==null?null:fp.forLot(c.organizationId(),lot);if(fg==null){lots.add(lot);charges=execution.chargesForLot(c.organizationId(),lot);}else{finishedGraph(fg,nodes,edges);expanded.add(fg.path("mainBatchId").asLong());charges=execution.chargesForBatch(c.organizationId(),fg.path("mainBatchId").asLong());}}
  for(var charge:charges){long unit=MasterMutation.id(charge.path("executionUnitId").asText());var context=production.execution(c.organizationId(),unit);String batch=Long.toString(context.mainBatchId()),unitId=Long.toString(unit),op=charge.path("operationExecutionId").asText(),chargeId=charge.path("id").asText(),lot=charge.path("materialLotId").asText();boolean linked=execution.genealogyForBatch(c.organizationId(),context.mainBatchId()).stream().anyMatch(g->g.path("chargeId").asText().equals(chargeId)&&g.path("inputMaterialLotId").asText().equals(lot));if(!linked)throw new ComplianceException("TRACE_EVIDENCE_INCOMPLETE","Charge genealogy evidence missing");var opFact=execution.operationFact(c.organizationId(),MasterMutation.id(op));
   batches.add(context.mainBatchId());node(nodes,"MAIN_BATCH",batch,"Main batch "+batch,context.batchStatus());node(nodes,"EXECUTION_UNIT",unitId,"Execution "+unitId,context.executionStatus());node(nodes,"OPERATION",op,"Operation "+op,opFact.path("status").asText());node(nodes,"CHARGE",chargeId,"Charge "+chargeId,charge.path("status").asText());node(nodes,"MATERIAL_LOT",lot,"Material lot "+lot,null);lots.add(MasterMutation.id(lot));
   edge(edges,"MAIN_BATCH",batch,"EXECUTION_UNIT",unitId,"EXECUTES");edge(edges,"EXECUTION_UNIT",unitId,"OPERATION",op,"HAS_OPERATION");edge(edges,"OPERATION",op,"CHARGE",chargeId,"ACTUAL_CHARGE");edge(edges,"CHARGE",chargeId,"MATERIAL_LOT",lot,"CONSUMED_FROM");
   if(charge.hasNonNull("weighingRecordId")){String weighing=charge.get("weighingRecordId").asText();var fact=execution.weighing(c.organizationId(),MasterMutation.id(weighing));node(nodes,"WEIGHING",weighing,"Weighing "+weighing,fact.path("status").asText());edge(edges,"CHARGE",chargeId,"WEIGHING",weighing,"WEIGHING_EVIDENCE");edge(edges,"WEIGHING",weighing,"MATERIAL_LOT",lot,"WEIGHED_FROM");for(var signature:fact.path("signatureEvidence")){String sid=signature.path("signatureId").asText();node(nodes,"SIGNATURE",sid,"Verification signature "+sid,null);edge(edges,"WEIGHING",weighing,"SIGNATURE",sid,"VERIFIED_BY_SIGNATURE");}}
  }
  if(fp!=null)for(long batch:batches)if(expanded.add(batch)){Long lot=fp.lotForBatch(c.organizationId(),batch);if(lot!=null)finishedGraph(fp.forLot(c.organizationId(),lot),nodes,edges);}
  var producer=incoming.getIfAvailable();if(producer==null&&!lots.isEmpty())throw new ComplianceException("DEPENDENCY_NOT_READY","Actual incoming trace producer unavailable");for(long lot:lots){var graph=producer.forLot(c.organizationId(),lot);if(graph.path("nodes").isArray()&&graph.path("edges").isArray()){for(var n:graph.get("nodes"))nodes.put(n.path("type").asText()+":"+n.path("id").asText(),n.deepCopy());for(var e:graph.get("edges"))edges.put(edgeKey(e),e.deepCopy());}else incomingGraph(graph,nodes,edges);}
  var handovers=wms.getIfAvailable();if(handovers!=null)for(long lot:lots)wmsGraph(handovers.forLot(c.organizationId(),lot),Long.toString(lot),nodes,edges);
  // Permission-filtered source categories cannot leave edges to inaccessible nodes.
  edges.values().removeIf(e->!nodes.containsKey(e.path("sourceType").asText()+":"+e.path("sourceId").asText())||!nodes.containsKey(e.path("targetType").asText()+":"+e.path("targetId").asText()));
  var result=json.createObjectNode();result.set("nodes",json.valueToTree(nodes.values()));result.set("edges",json.valueToTree(edges.values()));return result;
 }
 private void finishedGraph(JsonNode chain,Map<String,JsonNode> nodes,Map<String,JsonNode> edges){
  if(chain==null)return;String lot=fact(nodes,"MATERIAL_LOT",chain.path("lot")),batch=chain.path("mainBatchId").asText();node(nodes,"MAIN_BATCH",batch,"生产批 "+batch,chain.path("production").path("batch").path("status").asText(null));edge(edges,"MAIN_BATCH",batch,"MATERIAL_LOT",lot,"FINISHED_OUTPUT");
  for(var receipt:chain.path("receiving")){String id=fact(nodes,"FINISHED_INBOUND_REQUEST",receipt);edge(edges,"MATERIAL_LOT",lot,"FINISHED_INBOUND_REQUEST",id,"WAREHOUSE_RECEIPT");signature(nodes,edges,"FINISHED_INBOUND_REQUEST",id,receipt,"signatureId");if(receipt.hasNonNull("ledgerId"))edge(edges,"FINISHED_INBOUND_REQUEST",id,"INVENTORY_LEDGER",receipt.path("ledgerId").asText(),"RECEIPT_STOCK_FACT");}
  for(var request:chain.path("finishedQuality").path("requests")){String rid=fact(nodes,"FINISHED_INSPECTION_REQUEST",request);edge(edges,"MATERIAL_LOT",lot,"FINISHED_INSPECTION_REQUEST",rid,"FINISHED_INSPECTION");for(var record:request.path("samplingRecords")){String id=fact(nodes,"FINISHED_SAMPLING_RECORD",record),sample=record.path("sampleId").asText();edge(edges,"FINISHED_INSPECTION_REQUEST",rid,"FINISHED_SAMPLING_RECORD",id,"SAMPLING");node(nodes,"SAMPLE",sample,"成品样品 "+sample,null);edge(edges,"FINISHED_SAMPLING_RECORD",id,"SAMPLE",sample,"CREATED_SAMPLE");signature(nodes,edges,"FINISHED_SAMPLING_RECORD",id,record,"signatureId");}for(var report:request.path("reports")){String id=fact(nodes,"FINISHED_REPORT",report);edge(edges,"FINISHED_INSPECTION_REQUEST",rid,"FINISHED_REPORT",id,"DERIVED_REPORT");signature(nodes,edges,"FINISHED_REPORT",id,report,"signatureId");for(var review:report.path("reviews")){String vid=fact(nodes,"FINISHED_REPORT_REVIEW",review);edge(edges,"FINISHED_REPORT",id,"FINISHED_REPORT_REVIEW",vid,"INDEPENDENT_REPORT_REVIEW");signature(nodes,edges,"FINISHED_REPORT_REVIEW",vid,review,"signatureId");}for(var item:report.path("summary").path("items"))for(var r:item.path("originalResults")){String result=fact(nodes,"RESULT_REVISION",r);edge(edges,"FINISHED_REPORT",id,"RESULT_REVISION",result,"SOURCE_RESULT");}}}
  for(var test:chain.path("rawQuality").path("tests")){String tid=fact(nodes,"PRODUCTION_TEST",test);edge(edges,"PRODUCTION_TEST",tid,"SAMPLE",test.path("sampleId").asText(),"TESTS_SAMPLE");for(var r:test.path("results")){String rid=fact(nodes,"RESULT_REVISION",r);edge(edges,"PRODUCTION_TEST",tid,"RESULT_REVISION",rid,"ORIGINAL_RESULT");signature(nodes,edges,"RESULT_REVISION",rid,r,"signatureId");for(var review:r.path("reviews")){String vid=fact(nodes,"RESULT_REVIEW",review);edge(edges,"RESULT_REVISION",rid,"RESULT_REVIEW",vid,"INDEPENDENT_RESULT_REVIEW");signature(nodes,edges,"RESULT_REVIEW",vid,review,"signatureId");}}}
  for(var d:chain.path("decisions")){String id=fact(nodes,"RELEASE_DECISION",d);edge(edges,"MATERIAL_LOT",lot,"RELEASE_DECISION",id,"QA_DECISION");if(d.hasNonNull("finishedInspectionReportId"))edge(edges,"RELEASE_DECISION",id,"FINISHED_REPORT",d.path("finishedInspectionReportId").asText(),"BASED_ON_REPORT");signature(nodes,edges,"RELEASE_DECISION",id,d,"signatureId");}
  for(var ledger:chain.path("ledger")){String id=fact(nodes,"INVENTORY_LEDGER",ledger);edge(edges,"INVENTORY_LEDGER",id,"MATERIAL_LOT",lot,"PHYSICAL_STOCK_MOVEMENT");}
  for(var shipment:chain.path("shipments")){String id=fact(nodes,"FINISHED_SHIPMENT",shipment);edge(edges,"FINISHED_SHIPMENT",id,"MATERIAL_LOT",lot,"SHIPPED_FROM");if(shipment.hasNonNull("releaseDecisionId"))edge(edges,"FINISHED_SHIPMENT",id,"RELEASE_DECISION",shipment.path("releaseDecisionId").asText(),"AUTHORIZED_BY");signature(nodes,edges,"FINISHED_SHIPMENT",id,shipment,"signatureId");if(shipment.hasNonNull("ledgerId"))edge(edges,"FINISHED_SHIPMENT",id,"INVENTORY_LEDGER",shipment.path("ledgerId").asText(),"SHIPMENT_DEBIT_FACT");}
 }
 private void incomingGraph(JsonNode chain,Map<String,JsonNode> nodes,Map<String,JsonNode> edges){
  var lot=chain.path("lot");String lotId=lot.path("id").asText();if(lotId.isBlank())throw new IllegalStateException("Incoming lot identity missing");
  node(nodes,"MATERIAL_LOT",lotId,"Material lot "+lotId,lot.path("qualityStatus").asText());
  for(var decision:chain.path("inventoryDecisions")){String did=fact(nodes,"INVENTORY_DECISION",decision);edge(edges,"MATERIAL_LOT",lotId,"INVENTORY_DECISION",did,"INVENTORY_CONTROL");signature(nodes,edges,"INVENTORY_DECISION",did,decision,"signatureId");}
  String receipt=lot.path("receiptId").asText(),item=lot.path("receiptItemId").asText();node(nodes,"RECEIPT",receipt,"Receipt "+receipt,null);node(nodes,"RECEIPT_ITEM",item,"Receipt item "+item,null);edge(edges,"MATERIAL_LOT",lotId,"RECEIPT_ITEM",item,"RECEIVED_AS");edge(edges,"RECEIPT_ITEM",item,"RECEIPT",receipt,"PART_OF");
  for(var attachment:chain.path("deliveryAttachments")){String file=attachment.path("attachmentId").asText(attachment.path("id").asText());node(nodes,"ATTACHMENT",file,attachment.path("fileName").asText("Attachment "+file),attachment.path("retentionStatus").asText(null));edge(edges,"RECEIPT",receipt,"ATTACHMENT",file,"DELIVERY_DOCUMENT");}
  for(var request:chain.path("requests")){
   String rid=fact(nodes,"INSPECTION_REQUEST",request);edge(edges,"MATERIAL_LOT",lotId,"INSPECTION_REQUEST",rid,"INSPECTED_UNDER");signature(nodes,edges,"INSPECTION_REQUEST",rid,request,"signatureId");
   String standard=request.path("qcSpecificationVersionId").asText("");if(standard.isBlank())throw new ComplianceException("TRACE_EVIDENCE_INCOMPLETE","Request frozen standard identity missing");node(nodes,"QC_SPECIFICATION_VERSION",standard,"质量标准版本 "+standard,null);edge(edges,"INSPECTION_REQUEST",rid,"QC_SPECIFICATION_VERSION",standard,"FROZEN_STANDARD");
   for(var task:request.path("samplingTasks")){String tid=fact(nodes,"SAMPLING_TASK",task);edge(edges,"INSPECTION_REQUEST",rid,"SAMPLING_TASK",tid,"SAMPLING_TASK");signature(nodes,edges,"SAMPLING_TASK",tid,task,"planSignatureId");signature(nodes,edges,"SAMPLING_TASK",tid,task,"completionSignatureId");for(var detail:task.path("details")){String did=fact(nodes,"SAMPLING_DETAIL",detail);edge(edges,"SAMPLING_TASK",tid,"SAMPLING_DETAIL",did,"SAMPLING_POSITION");for(var sample:detail.path("samples")){String sid=fact(nodes,"SAMPLE",sample);edge(edges,"SAMPLING_DETAIL",did,"SAMPLE",sid,"CREATED_SAMPLE");signature(nodes,edges,"SAMPLE",sid,sample,"disposalSignatureId");}}}
   for(var task:request.path("inspectionTasks")){String tid=fact(nodes,"INSPECTION_TASK",task);edge(edges,"INSPECTION_REQUEST",rid,"INSPECTION_TASK",tid,"TEST_TASK");if(task.hasNonNull("sampleId"))edge(edges,"INSPECTION_TASK",tid,"SAMPLE",task.get("sampleId").asText(),"TESTS_SAMPLE");signature(nodes,edges,"INSPECTION_TASK",tid,task,"reviewSignatureId");for(var testItem:task.path("items")){String iid=fact(nodes,"INSPECTION_ITEM",testItem);edge(edges,"INSPECTION_TASK",tid,"INSPECTION_ITEM",iid,"REQUIRED_ITEM");for(var execution:testItem.path("executions")){String eid=fact(nodes,"TEST_EXECUTION",execution);edge(edges,"INSPECTION_ITEM",iid,"TEST_EXECUTION",eid,"TEST_ATTEMPT");if(execution.hasNonNull("approvedInvestigationId"))edge(edges,"TEST_EXECUTION",eid,"INVESTIGATION",execution.get("approvedInvestigationId").asText(),"RETEST_APPROVAL");if(execution.hasNonNull("originalExecutionId"))edge(edges,"TEST_EXECUTION",eid,"TEST_EXECUTION",execution.get("originalExecutionId").asText(),"RETEST_OF");for(var result:execution.path("revisions")){String vid=fact(nodes,"RESULT_REVISION",result);edge(edges,"TEST_EXECUTION",eid,"RESULT_REVISION",vid,"RESULT_REVISION");signature(nodes,edges,"RESULT_REVISION",vid,result,"signatureId");}}}}
   for(var report:request.path("reports")){String reportId=fact(nodes,"REPORT",report);edge(edges,"INSPECTION_REQUEST",rid,"REPORT",reportId,"REPORT");signature(nodes,edges,"REPORT",reportId,report,"approvalSignatureId");for(var reportItem:report.path("items")){for(String field:List.of("result","originalResult")){var result=reportItem.path(field);if(result.hasNonNull("id")){String vid=fact(nodes,"RESULT_REVISION",result);edge(edges,"REPORT",reportId,"RESULT_REVISION",vid,field.equals("result")?"FINAL_RESULT":"ORIGINAL_RESULT");signature(nodes,edges,"RESULT_REVISION",vid,result,"signatureId");}}}}
  }
  for(var decision:chain.path("decisions")){String id=fact(nodes,"RELEASE_DECISION",decision);edge(edges,"MATERIAL_LOT",lotId,"RELEASE_DECISION",id,"QUALITY_DECISION");if(decision.hasNonNull("inspectionReportId"))edge(edges,"RELEASE_DECISION",id,"REPORT",decision.get("inspectionReportId").asText(),"BASED_ON_REPORT");signature(nodes,edges,"RELEASE_DECISION",id,decision,"signatureId");}
  for(var investigation:chain.path("investigations")){String id=fact(nodes,"INVESTIGATION",investigation);edge(edges,"MATERIAL_LOT",lotId,"INVESTIGATION",id,"QUALITY_INVESTIGATION");signature(nodes,edges,"INVESTIGATION",id,investigation,"decisionSignatureId");signature(nodes,edges,"INVESTIGATION",id,investigation,"closeSignatureId");}
 }
 private void wmsGraph(JsonNode facts,String lot,Map<String,JsonNode> nodes,Map<String,JsonNode> edges){
  var source=facts.path("source");if(source.hasNonNull("supplierId")){
   String supplier=source.path("supplierId").asText();String label="供应商 "+source.path("supplierName").asText(supplier);
   node(nodes,"SUPPLIER",supplier,label,null);
   for(var e:new ArrayList<>(edges.values()))if(e.path("sourceType").asText().equals("MATERIAL_LOT")&&e.path("sourceId").asText().equals(lot)&&e.path("targetType").asText().equals("RECEIPT_ITEM")){
    String item=e.path("targetId").asText();edge(edges,"SUPPLIER",supplier,"RECEIPT_ITEM",item,"FROZEN_SUPPLY_SOURCE");
    var receiptItem=(ObjectNode)nodes.get("RECEIPT_ITEM:"+item);if(receiptItem!=null)receiptItem.put("label","收货明细 "+item+" · "+source.path("supplierName").asText(supplier)+(source.hasNonNull("manufacturerName")?" · 生产厂家："+source.path("manufacturerName").asText():""));
   }
  }
  for(var issue:facts.path("issues")){
   String iid=fact(nodes,"MATERIAL_ISSUE",issue),batch=issue.path("mainBatchId").asText();((ObjectNode)nodes.get("MATERIAL_ISSUE:"+iid)).put("label","出库单 "+issue.path("issueNo").asText(iid));
   if(nodes.containsKey("MAIN_BATCH:"+batch))edge(edges,"MAIN_BATCH",batch,"MATERIAL_ISSUE",iid,"WAREHOUSE_HANDOVER");
   var request=issue.path("request");if(request.hasNonNull("id")){String rid=fact(nodes,"MATERIAL_REQUEST",request);((ObjectNode)nodes.get("MATERIAL_REQUEST:"+rid)).put("label","领料申请 "+request.path("requestNo").asText(rid));edge(edges,"MATERIAL_REQUEST",rid,"MATERIAL_ISSUE",iid,"FULFILLED_BY");if(nodes.containsKey("MAIN_BATCH:"+batch))edge(edges,"MAIN_BATCH",batch,"MATERIAL_REQUEST",rid,"MATERIAL_DEMAND");}
   for(var item:issue.path("items")){String id=fact(nodes,"MATERIAL_ISSUE_ITEM",item);edge(edges,"MATERIAL_ISSUE",iid,"MATERIAL_ISSUE_ITEM",id,"HANDOVER_ITEM");edge(edges,"MATERIAL_ISSUE_ITEM",id,"MATERIAL_LOT",lot,"HANDOVER_LOT");for(var returned:item.path("returns")){String rid=fact(nodes,"ISSUE_RETURN",returned);((ObjectNode)nodes.get("ISSUE_RETURN:"+rid)).put("label","退料记录 "+rid+" · "+returned.path("quantity").asText());edge(edges,"MATERIAL_ISSUE_ITEM",id,"ISSUE_RETURN",rid,"UNUSED_ENTITLEMENT_RETURN");}}
  }
 }
 private String fact(Map<String,JsonNode> nodes,String type,JsonNode fact){String id=fact.path("id").asText();if(id.isBlank())throw new IllegalStateException("Trace fact identity missing: "+type);node(nodes,type,id,type+" "+id+(fact.hasNonNull("resultConclusion")?" "+fact.get("resultConclusion").asText()+" (effective "+fact.path("effectiveConclusion").asText()+")":""),fact.path("status").asText(fact.path("decision").asText(null)));if(fact.hasNonNull("revisionNo"))((ObjectNode)nodes.get(type+":"+id)).set("revision",fact.get("revisionNo").deepCopy());return id;}
 private void signature(Map<String,JsonNode> nodes,Map<String,JsonNode> edges,String type,String id,JsonNode fact,String field){if(fact.hasNonNull(field)){String signature=fact.get(field).asText();node(nodes,"SIGNATURE",signature,"Signature "+signature,null);edge(edges,type,id,"SIGNATURE",signature,"SIGNED_EVIDENCE");}}
 private void node(Map<String,JsonNode> nodes,String type,String id,String label,String status){var n=json.createObjectNode();n.put("type",type);n.put("id",id);n.put("label",label);if(status==null)n.putNull("status");else n.put("status",status);n.putNull("revision");nodes.put(type+":"+id,n);}
 private void edge(Map<String,JsonNode> edges,String st,String sid,String tt,String tid,String relation){var e=json.createObjectNode();e.put("sourceType",st);e.put("sourceId",sid);e.put("targetType",tt);e.put("targetId",tid);e.put("relation",relation);edges.put(edgeKey(e),e);}
 private String edgeKey(JsonNode e){return e.path("sourceType").asText()+":"+e.path("sourceId").asText()+":"+e.path("targetType").asText()+":"+e.path("targetId").asText()+":"+e.path("relation").asText();}
}
